### ISSUE TITLE
Add word counts

### ISSUE THREAD

**Issue by bantilan** [WordPress/gutenberg#8242]
**Is your feature request related to a problem? Please describe.**
On the current build, there is no way knowing the word counts of the post in Gutenberg editor. Hope this feature will be added soon.

**Describe the solution you'd like**
Add a word counter in the editor, either in the right menu or on the top or bottom.

**Comment by chrisvanpatten** [comment]
Hi @bantilan -

Word count is available in the Content Structure popover, which you can find by clicking the "i" icon in the top toolbar:

![about_mindful___ _mindful_ _wordpress](https://user-images.githubusercontent.com/1231306/43299583-b54f7640-9128-11e8-848a-5932000835c5.png)

Hope this helps!

**Comment by bantilan** [comment]
Hi @chrisvanpatten,

I see.. I got error when I click it.. I think the error is something to do with my server configuration.

![image](https://user-images.githubusercontent.com/1697297/43302915-ec16c044-919f-11e8-9216-b8cb28e46993.png)

Invariant Violation: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Btype%2C%20props%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at Sg (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:142:327)
    at m (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:12:388)
    at Xb (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:79:171)
    at If (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:82:291)
    at v (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:84:389)
    at https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:88:328
    at rd (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:10)
    at O (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:90:455)
    at yh (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:105:190)
    at lg (https://gamingph.com/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88)

**Comment by maddisondesigns** [comment]
I just got the same error when clicking on the _Content Structure_ icon. Here's a vid...

https://cl.ly/391E3e1b1J1o

Some Pages/Posts work fine. Others break

**Comment by maddisondesigns** [comment]
Can replicate very easily by clicking on the _Gutenberg > Demo_ menu option. When the new Demo draft Post appears, click the _Content Structure_ icon and the page breaks.

**Comment by maddisondesigns** [comment]
Also, some Pages/Posts that I try to edit, break as soon you open them. It doesn't even show the editor, it just shows this error

**Comment by chrisvanpatten** [comment]
@bantilan @maddisondesigns That error looks like the one reported in #8150 and #8160, and fixed in #8204 :)

**Comment by bantilan** [comment]
thank you @chrisvanpatten, will look at it..

**Comment by karmatosed** [comment]
I don't get an error which makes me wonder if there is something specific on the pages others do. Were these written with specific blocks or maybe in different versions? Would love to dig into the reason in case there is a bug. This assumes everyone is using the latest plugin, could you confirm that please?

**Comment by chrisvanpatten** [comment]
@karmatosed The error is if you have a heading block with italics, it's documented better in #8160 and fixed in master at this point.

**Comment by designsimply** [comment]
Thank you for posting your @bantilan. 

I am closing this issue because the word count is available in the (i) Content Structure option in the top toolbar and the bug you mentioned about it not working when there is a heading block with formatting included on the page has been fixed (https://github.com/WordPress/gutenberg/issues/8160 → https://github.com/WordPress/gutenberg/pull/8204) and should be available for you in version 3.4.
