### ISSUE TITLE
Toggle switches don't display properly

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8243]
**Describe the bug**
Toggle switches such as the ones used for turning on/off Comments/Pingbacks, don't display properly.

This is how they look in TwentySeventeen

![screenshot_752](https://user-images.githubusercontent.com/2078245/43303427-11b1db50-91b3-11e8-9a10-cb9229b64503.png)

**To Reproduce**
1. Edit Post
2. Click on _document_ tab in sidebar 
3. Toggle open the _Discussion_ panel
4. View Toggle switches 

_macOS Sierra 10.12.6
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.3.0
TwentySeventeen_

**Comment by pento** [comment]
@maddisondesigns: This looks correct to me. Can you describe what you were expecting them to look like?

**Comment by maddisondesigns** [comment]
They should appear like this...

![gutenberg_toggleswitches](https://user-images.githubusercontent.com/2078245/43304244-b46d0aba-91b6-11e8-91a5-90e68b03f66e.jpg)

i.e. Without that weird white line showing

**Comment by pento** [comment]
This is intended, see #5500.

The [power symbols](https://en.wikipedia.org/wiki/Power_symbols) on the toggle switch are one of several visual cues to indicate whether the switch is in an "on" or "off" position.

**Comment by maddisondesigns** [comment]
Hmmm They look nothing like power symbols at the moment. I can see the issue with having text like ON/OFF and allowing for translations, but these just look like they aren't styled properly.

Even just making them slightly larger and centering them more would make them look better

![gutenberg_toggleswitches2](https://user-images.githubusercontent.com/2078245/43305262-72a4b980-91ba-11e8-8657-4c00e56081da.gif)
