### ISSUE TITLE
Color Palette Clear set to Transparent instead of Undefined?

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#8249]
Hi Everyone,

I would love to know how can I set the Clear button as transparent instead of undefined : https://github.com/WordPress/gutenberg/blob/288fe7897002f14c04f552b563d22af566742277/packages/components/src/color-palette/index.js . Thanks!

**Comment by youknowriad** [comment]
Unfortunately, this is not possible. You can try to define "transparent" as a color in the palette.

Otherwise, you can build your own ColorPalette component.
