### ISSUE TITLE
Insert link: text added after inserting an hyperlink is still included in the hyperlink

### ISSUE THREAD

**Issue by carladoria** [WordPress/gutenberg#8257]
**Steps to reproduce the issue**

1. Type some text and a link to it
2. Continue adding text after the link, you'll notice you're still in the link, clicking out of the link or spacing doesn't solve the issue, you're inside it.
3. Unclicking the link button removes all the linking

The only workaround right now seems to make sure to type text after the linked text and then only select the word to hyperlink, but this is not the natural flow for many users.

**What I expected**
Add the link and then continue typing text that is not linked

**What happened instead**
Whatever text I added continued inside the link

You can see the recording here:

https://drive.google.com/file/d/1zpb4F2WKSFfHD4aMjVf3LC39-qaja6Fg/view

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.7 and Gutenberg 3.3.0 with Firefox 61.0.1 on macOS 10.13.6.

<strong>Note:</strong> I agree if you click to the right of the link after adding it (as you did in your video example) that the link should be unselected at that point. 

<strong>Workaround note:</strong> you may click the right arrow to get out of the link boundary to continue typing.

**Comment by designsimply** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/7980 which is a very similar issue but I think the outcome there will resolve this issue. If it doesn't, or if you feel strongly that this issue should be separate, we can re-open!
