### ISSUE TITLE
Is there a icon picker type for attribute?

### ISSUE THREAD

**Issue by foysalremon** [WordPress/gutenberg#8261]
I have search a lot but couldn't find something to add font-awesome or others icon selector for my custom blocks. If this is not available how can I create custom control to add icon attributes feature.

**Comment by Soean** [comment]
@foysalremon You can use every SVG image you want. 
Gutenberg now uses SVGs from the Material icon library. Example in the Audio block: https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/audio/index.js
