### ISSUE TITLE
Insert link: there's no autocomplete when adding a link to an image

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#8265]
In the Classic Editor, users can add a link to an image via the standard "link inline modal". That means they can use the auto-completer and get link suggestions while they type in the url field:

![screen shot 2018-07-28 at 17 28 58](https://user-images.githubusercontent.com/1682452/43358089-717cc26e-928c-11e8-948d-9e544245d036.png)

In Gutenberg, after the changes in #7679 the image link functionality has been moved to the sidebar. There's now the ability to choose between the usual options: none, media file, attachment page, custom URL, and that make sense. We could argue if adding a link is a secondary action (and as such it's properly placed in the sidebar) or if it's a primary action and thus should stay in the block.

Regardless, when selecting "Custom URL", the URL field is a native input field. There's no auto-completer. This makes inserting a link to an existing post a painful experience. It is also a reduced functionality compared to the existing one in the Classic editor so I'm labelling this issue as a bug.

Just imagine the flow users will be forced to follow:
- insert an image
- discover there's no option to retrieve the URL of an existing post
- with some luck, remember the post URL and type it manually in the sidebar field (after discovering the custom URL option is there hidden in a select)
- otherwise: save draft, go back to the posts list (or pages or CPTs list) or go to the front-end
- find the post to link to
- grab its URL in some way and copy it
- go back to the edited post
- select again the image, and finally paste the URL in the custom URL field

Alternative approach:
- insert an image
- discover there's no option to retrieve the URL of an existing post
- use a paragraph block, insert a link there to grab its URL
- cancel and paste the URL in the image custom URL field

Worth noting that in the Classic editor, when inserting an image and selecting media file or attachment page, then it's always possible to edit again the link via the link inline modal so probably the two functionalities should coexist.

**Comment by designsimply** [comment]
Tested and confirmed the "Custom URL" field in the sidebar does not have autocomplete when inserting an image. I found that the classic editor does not have this in the insert image flow either but it does have it if you use the link icon in the classic editor toolbar to open the floating link toolbar after the link has been inserted. Tested with WordPress 4.9.7 and Gutenberg 3.3.0 using Chrome 67.0.3396.99 on macOS 10.13.6. ([3m25s](https://cloudup.com/c8pLgvGeUmf))

I believe consistency is important, so my vote would be two-fold: add a link icon to the image block toolbar to make it more consistent with how links are added in other blocks and add the capability to make the "Custom URL" field searchable.

**Comment by jorgefilipecosta** [comment]
I guess the UX change proposed by @designsimply: 
> I believe consistency is important, so my vote would be two-fold: add a link icon to the image block toolbar to make it more consistent with how links are added in other blocks and add the capability to make the "Custom URL" field searchable.

Is a good path to follow, @mapk any thoughts on this?

**Comment by mapk** [comment]
👍  @jorgefilipecosta I agree with @designsimply. The flow she suggested should work well. It would basically look like this, but for an image.

![link](https://user-images.githubusercontent.com/617986/56977087-465f6980-6b29-11e9-8b3d-0f79fd9f0822.gif)

**Comment by kjellr** [comment]
Here's a quick mockup of how this might look: 

![Frame](https://user-images.githubusercontent.com/1202812/57101247-aabf2c00-6cd5-11e9-9b9e-e9cc0b613868.png)
