### ISSUE TITLE
How to do validation of the metabox forms on Save or Publish

### ISSUE THREAD

**Issue by dev4press** [WordPress/gutenberg#8272]
Saving in Gutenberg is done through AJAX, so browsers do not get the trigger to validate the forms that may be in the metaboxes, so if the metabox form has fields that are required or need some other validation, they will not be validated.

Maybe adding a standard feature in Gutenberg to run HTML validation for metaboxes when the user clicks Save or Publish buttons in Gutenberg? Without that, there will be a lot of issues with submitting valid input from metaboxes that need validation. If not, is there a way in with Gutenberg to stop saving of draft or stop publishing until the validation of forms is completed? Something that can be used in JavaScript or even with jQuery to intercept Save/Publish, to run validation first.

**Comment by designsimply** [comment]
There is a long discussion about server-side awareness of blocks and I think this issue would be better if added to that discussion. Can we close this in favor of moving it to #2751? If not, can you explain why so I can get a better understanding? 🙂

**Comment by chrisvanpatten** [comment]
@designsimply this is about metaboxes, not blocks, so it’s unrelated to #2751.

**Comment by dev4press** [comment]
This is browser validation problem and the fact that Gutenberg effectively eliminates the browser validation before the data is submitted.

**Comment by aduth** [comment]
Related: #7020

>Maybe adding a standard feature in Gutenberg to run HTML validation for metaboxes when the user clicks Save or Publish buttons in Gutenberg?

There may be an option here for using validation API as a condition prior to save:

- https://developer.mozilla.org/en-US/docs/Learn/HTML/Forms/Form_validation#Validating_forms_using_JavaScript
- https://html.spec.whatwg.org/multipage/forms.html#dom-form-checkvalidity

**Comment by timnolte** [comment]
I find it very surprising that with all of the work being done with the Block Editor that it's been over a year and this is still an outstanding issue.

**Comment by awps** [comment]
> I find it very surprising that with all of the work being done with the Block Editor that it's been over a year and this is still an outstanding issue.

Another year and this issue is still open. :(

**Comment by gitgetgotgotten** [comment]
> > I find it very surprising that with all of the work being done with the Block Editor that it's been over a year and this is still an outstanding issue.
> 
> Another year and this issue is still open. :(

We are on the verge of 2022. Hasn't it been fixed yet?

**Comment by tellthemachines** [comment]
The [lockPostSaving action](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-editor/#lockpostsaving) might be of use here. You could add some custom validation logic and then unlock saving only if it passes.

**Comment by t-hamano** [comment]
> The [lockPostSaving action](https://developer.wordpress.org/block-editor/reference-guides/data/data-core-editor/#lockpostsaving) might be of use here. You could add some custom validation logic and then unlock saving only if it passes.

I also think that this problem can be solved by using this API. You could just detect a change in any field of the form and dispatch it via `lockPostSaving` or `unlockPostSaving`. Sample code is also present here:

- [lockPostSaving](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/data/data-core-editor.md#lockpostsaving)
- [unlockPostSaving](https://github.com/WordPress/gutenberg/blob/trunk/docs/reference-guides/data/data-core-editor.md#unlockpostsaving)

Therefore, I would like to close this issue, but if there is anything I have missed, please comment.

**Comment by timnolte** [comment]
Really, so this is just being left by the wayside? So functionality is broken and now completely abandoned by new development.
