### ISSUE TITLE
Can't delete to the first line of a multiline block

### ISSUE THREAD

**Issue by pento** [WordPress/gutenberg#8282]
**Describe the bug**

When there are multiple lines in a block, the first line can't be deleted.

**To Reproduce**
Steps to reproduce the behaviour:
1. Start with a paragraph block.
2. Write some text. Press Shift+Enter, to add a new line, but stay in the same block. Write some more text.
3. Use your keyboard to navigate to the end of the first line, then press Shift+Alt+Left (to select the text to the start of the line).
4. Press Delete.

**Expected behavior**

The selected content is deleted.

**Desktop:**
 - OS: MacOS
 - Browser: Chrome
 - Version: 68.0.3440.75

**Additional Information**

I'm able to reproduce similar behaviour in the List block, by adding two list items.

I can reproduce this behaviour in Gutenberg 3.3, and `master`.

**Comment by LZL0** [comment]
Is there a possible connection with #8268?

**Comment by pento** [comment]
Yup, this is a duplicate of #8268, thanks!
