### ISSUE TITLE
Paragraph Blocks use incorrect classes for text sizes

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8284]
**Describe the bug**
According to the Gutenberg documentation, when setting Paragraph text with the Text Settings buttons, it should add classes in the  format of `.has-small-font-size`

See: https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#block-font-sizes

Instead though, the classes being rendered on the front-end are formatted like `.is-small-text`

![screenshot_760](https://user-images.githubusercontent.com/2078245/43388797-658b4564-942d-11e8-8740-7fe236c7468c.png)

The format specified in the documentation makes more sense as it aligns with other classes used for columns and colours where the class name is prefixed with `has-...`

**To Reproduce**
1. Add paragraph block and dummy text
2. click on block to select and set text size to either S, M, L or XL
3. Save page
4. View page and view source

_macOS Sierra 10.12.6
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.3.0_

**Comment by designsimply** [comment]
Tested with Gutenberg 3.4.0 and found that `has-small-font-size` is now used on the front end for text set as `S` in paragraph block settings ([screenshot](https://cloudup.com/cpFp7lVcfLX)).

Noting that there's a point of confusion around documentation reflecting `master` as opposed to the latest stable release and https://github.com/WordPress/gutenberg/issues/6514#issuecomment-409086074 is the relevant discussion for that point.
