### ISSUE TITLE
Theme support for editor-font-sizes doesn't work

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8286]
**Describe the bug**
I'm trying to set the theme font sizes as per the [documentation](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#block-font-sizes) but it's not working.

I've added the following code into my `functions.php` file. The function containing this code also has all my other theme support calls and is hooked to `after_setup_theme`.

```
// Add support for custom font sizes in the Block Editor (Gutenberg)
add_theme_support( 'editor-font-sizes', array(
	array(
		'name' => __( 'small', 'ephemeris' ),
		'shortName' => __( 'S', 'ephemeris' ),
		'size' => 13,
		'slug' => 'small'
	),
	array(
		'name' => __( 'regular', 'ephemeris' ),
		'shortName' => __( 'M', 'ephemeris' ),
		'size' => 16,
		'slug' => 'regular'
	),
	array(
		'name' => __( 'large', 'ephemeris' ),
		'shortName' => __( 'L', 'ephemeris' ),
		'size' => 24,
		'slug' => 'large'
	),
	array(
		'name' => __( 'extralarge', 'ephemeris' ),
		'shortName' => __( 'XL', 'ephemeris' ),
		'size' => 36,
		'slug' => 'extralarge'
	)
) );
```

When selecting the font size on a paragraph, it styles the text in the editor with the default font sizes, either 14, 16, 36, or 48px, instead of my custom sizes.

If I change the `shortName` value, which I presume is the text on the button in the editor, that's also ignored.

On the rendered page, the classes that are added to the paragraphs are using names from the default classes (small, medium, large, larger), instead of my own class names (small, medium, large, extralarge)

The site is a local site so there's no caching and browser cache was also cleared, just to be sure.

See also #8284 - Paragraph Blocks use incorrect classes for text sizes

_macOS Sierra 10.12.6
Firefox Quantum 61.0.1 (64-bit)
Gutenberg 3.3.0_

**Comment by chrisvanpatten** [comment]
@maddisondesigns This won't be in Gutenberg until 3.4; the Gutenberg handbook docs reflect what's in master, not the last release. See #6514 for more discussion.

**Comment by bgardner** [comment]
@chrisvanpatten Thanks for letting us know that it won't be in Gutenberg until 3.4, because I'm working on the Genesis Sample Theme and noticed the same thing @maddisondesigns did. (Thank God for Google, and for quick responses from the team.)

**Comment by chrisvanpatten** [comment]
@bgardner No problem! It’s a little confusing because the docs are built when master changes. Definitely leave a comment over at #6514; it got stalled but I think it’s worth revisiting having docs built with releases and the extra comments help.

**Comment by maddisondesigns** [comment]
@chrisvanpatten Thanks for letting me know. This is the first time that I've heard that.

A couple of recommendations:
1. Can you please put a big notice at the top of the [Introduction page](https://wordpress.org/gutenberg/handbook/) advising people of this. Something like "PLEASE NOTE: This Gutenberg handbook documentation reflects what's in master, not the current plugin release."
2. When a new section is added, such as "Block Font Sizes", also add what version it's available from. There is nothing in the docs at the moment that gives any indication as to what is available now or what is available in the next or following releases.

**Comment by chrisvanpatten** [comment]
@maddisondesigns I don't really have the power to do that (just a lowly third party contributor), but I agree. I'd strongly suggest commenting on #6514 too.

**Comment by maddisondesigns** [comment]
@chrisvanpatten No probs. I've just left a comment on #6514. Thanks for your help with this.

**Comment by josephdickson** [comment]
I just updated to Gutenberg 3.4 and it appears to be working on my end. Thanks @maddisondesigns for submitting the bug report. I ran into the same problem last week and thought I had done something wrong on my end.

**Comment by designsimply** [comment]
Closing in favor of #6514.

**Comment by swinggraphics** [comment]
Using Gutenberg 4.0 here. editor-font-sizes and disable-custom-font-sizes are not working.

**Comment by designsimply** [comment]
@swinggraphics thanks for the note! I noticed this came up again 7 days ago at https://github.com/WordPress/gutenberg/issues/10940#issuecomment-438181299 and I'm wondering whether you've upgraded to Gutenberg 4.4 and if you're still having trouble with `editor-font-sizes` and `disable-custom-font-sizes` in that version?

**Comment by swinggraphics** [comment]
I have updated to 4.4. `disable-custom-font-sizes` still does not work. `editor-font-sizes` is okay.

**Comment by apmeyer** [comment]
Adding another note that `disable-custom-font-sizes` does not work in 4.5.1.

**Comment by designsimply** [comment]
Is this problem still happening for you in WordPress 5.1?

**Comment by Headlab** [comment]
@designsimply not only it was happening in 5.1, it's happening in 5.2.4. 
add_theme_support( 'disable-custom-font-sizes' ); does absolutely nothing.

**Comment by DarkChris86** [comment]
These are not working yet with the newest release neither:

 WordPress: **5.6.1.**
 Gutenberg:  **8.6-9.2**

I see my new fonts styles but:

- shortName parameter is not working
- when I click any of custom sizes always keeps the default font size

![image](https://user-images.githubusercontent.com/18347405/107612124-d78fc980-6c45-11eb-9efa-8ce80b3febcd.png)


```
// Disable custom font sizes
add_theme_support( 'disable-custom-font-sizes' );

// Editor Font Styles
add_theme_support( 'editor-font-sizes', [
	[
		'name'      => __( 'small', 'test' ),
		'shortName' => __( 'S', 'test' ),
		'size'      => 18,
		'slug'      => 'small'
	],
	[
		'name'      => __( 'normal', 'test' ),
		'shortName' => __( 'M', 'test' ),
		'size'      => 22,
		'slug'      => 'normal'
	],
	[
		'name'      => __( 'large', 'test' ),
		'shortName' => __( 'L', 'test' ),
		'size'      => 25,
		'slug'      => 'large'
	],
]);
```

**Comment by marxcie** [comment]
Following this, I'm experiencing the same issue. Not even the basic WP font sizes working, and the same happens to me: When I click on a style or input a number, it doesn't add anything to the code, and the picker doesn't change to the new value. WP 5.6.1

**Comment by apmeyer** [comment]
Same. I can report the same behavior. The font size selection menu is having no affect.

**Comment by klogges** [comment]
Same here. Custom font sizes are working on WP 5.6.
Same theme and scripts not working with WP 5.6.1.

**Comment by maddisondesigns** [comment]
@klogges @apmeyer @marxcie @DarkChris86 If this functionality isn't working in Gutenberg now, then you'd be better off creating a new issue rather than posting on this one, which has already been closed.

**Comment by klogges** [comment]
An open issue to this bug can be found here: https://github.com/WordPress/gutenberg/issues/28738

**Comment by klogges** [comment]
As mentioned in #28738 using the Gutenberg plugin is a workaround.
