### ISSUE TITLE
Can't save, won't save

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#829]
This is a fun one and may be related to: https://github.com/WordPress/gutenberg/issues/828

I saw there were saved changes, yet could not save. On refresh they had saved. This was after the issue I found in #828, so maybe I made it grumpy.

Here is a video:
https://cldup.com/CSpT15pSnU.mp4

**Comment by jasmussen** [comment]
Ah yes —  my own apologies for this, we have not made it clear. The alpha zip we released was so early that although saving actually works (it does I promise!) we intentionally disabled it for that first release. 

A nice improvement would have been a message stating that saving was disabled. But at this point we're moving so fast that we might actually allow saving sooner than we could build that message :)

So for now I'm closing this, but thanks for the reports!
