### ISSUE TITLE
Testing: Remove beautification from block fixtures

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8294]
Related: #7892

As of #7892, we no longer apply HTML beautification to the output of blocks. However, our block test fixtures "original" markup was not updated to reflect this. The original markup should ideally align with more-or-less exactly what is expected as the output of the block itself.

**Task:** For each `.html` file (_not_ `.serialized.html`) in `test/integration/full-content/fixtures`, remove excess whitespace which would not have been generated in the output of block serialization. This could be done by using the `.serialized.html` which is expected to be equivalent, but should be done so carefully so as not to simply assume that the `.serialized.html` is "correct" (as it's the intention of these tests to ensure sensible parse / reserialize flow).

**Comment by Taym95** [comment]
Hi, first of all, thank you for this great editor, I would like to help, can you give an example of which whitespace you mean?

**Comment by aduth** [comment]
Hi @Taym95 ! Thanks for your willingness to step in. If you look at this folder, you'll see that, for each fixture, there are two HTML files, one ending in `.html` and another as `.serialized.html`:

https://github.com/WordPress/gutenberg/tree/master/core-blocks/test/fixtures

The idea with these fixtures tests is that we treat the `.html` as a copy of the block saved to the database, and want to ensure that the output (`.serialized.html`) is the same.

For example, consider the gallery fixture:

- [`core__gallery.html`](https://github.com/WordPress/gutenberg/blob/master/core-blocks/test/fixtures/core__gallery.html)
- [`core__gallery.serialized.html`](https://github.com/WordPress/gutenberg/blob/master/core-blocks/test/fixtures/core__gallery.serialized.html)

The first one includes extra tabs and newlines, since this is how prior to #7892 blocks were written to the database. Since this is no longer true, it would be more accurate for us to rewrite them without the excess whitespace.

The process may very well be to copy contents of `.serialized.html` into the plain `.html`, for each fixture in this directory. Since tests are currently passing, we should be able to assume that these are still correct / equivalent.

**Comment by Taym95** [comment]
Hi @aduth , Thank you for clarifications, I got it I will try to submit PR for this issue.

**Comment by ecotechie** [comment]
Looks like this is no longer relevant? The files are not there.
Looks like these are them now, but they do look different.

**Comment by aduth** [comment]
The files have since been moved to:

https://github.com/WordPress/gutenberg/tree/master/test/integration/full-content/fixtures

>Looks like these are them now, but they do look different.

As best I can tell, the original point of the task remains (the original `.html` files include unnecessary/inaccurate beautification).

**Comment by gziolo** [comment]
New home for fixtures:

https://github.com/WordPress/gutenberg/tree/354c1ff6b5337837eb4183d4eb8302ffeccd1be8/packages/e2e-tests/fixtures/blocks

**Comment by aduth** [comment]
I don't think this is very important to address. In fact, the variations between the source and output could be seen as a good real-world stress-test of whitespace variations.
