### ISSUE TITLE
Centre-aligning the file block doesn't centre-align anything

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8296]
When centre-aligning the file block, it looks exactly the same in the editor as the left-aligned and default file block.

**Default alignment:**
![Uploading Screenshot 2018-07-30 14.51.48.png…]()

**Centre-aligned:**
<img width="671" alt="screenshot 2018-07-30 14 51 59" src="https://user-images.githubusercontent.com/376315/43401603-7f42de60-9408-11e8-98e4-a9bc3cb793f1.png">

**Left-aligned:**
<img width="680" alt="screenshot 2018-07-30 14 52 27" src="https://user-images.githubusercontent.com/376315/43401617-8a6a6bf0-9408-11e8-9f25-620fd2e16820.png">

**Right-aligned:**
<img width="642" alt="screenshot 2018-07-30 14 52 19" src="https://user-images.githubusercontent.com/376315/43401660-a7668bee-9408-11e8-86ee-2e003e009d01.png">

**To Reproduce**
1. Create a new post and add a file.
2. Centre-align block using the toolbar.
3. See left alignment!

Tested in Firefox Nightly on Mac. Seems to be properly centre-aligned in the frontend—looks as though the alignment class just isn't added in the editor.

**Comment by noisysocks** [comment]
Fixed by #8303.
