### ISSUE TITLE
Gallery Block: Add "Upload / Media Library" buttons to the "Upload an Image" placeholder area.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8309]
**Is your feature request related to a problem? Please describe.**

Once an image has been added to the gallery, we don't provide a straightforward way to add more images from the media library. There's a placeholder area at the bottom of the block, but that only allows you to drag+drop or click to upload a new image: 

<img width="640" alt="untitled" src="https://user-images.githubusercontent.com/1202812/43418703-c294bf7c-940c-11e8-980c-6da8e4eda189.png">

**Describe the solution you'd like**

We should consider adding "Upload / Media Library" buttons to the "Add an Image" placeholder area. This would align the appearance and functionality of that area with both the initial state of the gallery block, and with the standard placeholder for all other media-based blocks as well. 

<img width="640" alt="image" src="https://user-images.githubusercontent.com/1202812/43418806-2339d2a4-940d-11e8-8060-b785510f6a0e.png">

**Comment by kriskarkoski** [comment]
I noticed this in some recent testing as well, and +1 to that mockup. You can click the pencil to manage it and then add from the existing library from there, but it feels pretty hidden.
