### ISSUE TITLE
Add a way to change the post status in the sidepannel

### ISSUE THREAD

**Issue by dazunE** [WordPress/gutenberg#8313]
**Is your feature request related to a problem? Please describe.**
With the current status of the Gutenberg, in order to change the post status needs to go to quick edit in all posts screen, the other status are not clearly visible in the side panel.
Post status feature is very important when we are working with the custom post types and custom post status.

**Describe the solution you'd like**
Add a drop-down option in, side panel under the Status & Visibility, so users can easily update the post status.
![Suggested Design](https://dasunedirisinghe.files.wordpress.com/2018/07/screen-shot-2018-07-31-at-09-55-14.png)

**Comment by designsimply** [comment]
Thank you for the suggestion! I am adding a screenshot showing the current existing UI around Post Status for Draft, Published, and Pending Review for reference:

![screen shot 2018-07-31 at tue jul 31 11 15 15 am](https://user-images.githubusercontent.com/1119271/43475703-d0f1ff56-94b3-11e8-9a14-198e7a6719bf.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14091&action=edit running WordPress 4.9.7 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

Here is the UI for Post Status in the classic editor for comparison:

![screen shot 2018-07-31 at tue jul 31 11 21 23 am](https://user-images.githubusercontent.com/1119271/43475867-49e0008e-94b4-11e8-9a9a-d2400e88f1d4.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14091&action=edit&classic-editor running WordPress 4.9.7 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by chrisvanpatten** [comment]
Related: #3144

**Comment by designsimply** [comment]
Closing in favor of #3144.

Thanks @chrisvanpatten!
