### ISSUE TITLE
Del key doesn't work when you have all text (⌘A) selected

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#8320]
Possibly related to the recent work on expanding selection on multiple consecutive ⌘A's. GIF:

![command a](https://user-images.githubusercontent.com/1204802/43459707-a4d63ba6-94ce-11e8-915b-6cdab77107ab.gif)

Steps to reproduce:

- Write text in a paragraph
- Set caret in text
- Press ⌘A

Observe that pressing Delete does not do anything.

**Comment by cassands** [comment]
I was curious and decided to give this a try and wound up with slightly more extensive issues.

[Delete]
When the paragraph being tested was above another paragraph, hitting delete merged the two together. If it was above something other than another paragraph nothing happened when pressing delete.

[Backspace]
Backspace misbehaved in a similar fashion. When the paragraph was manually selected, it deleted the space between that paragraph and the one before. Backspace worked normally with [Ctr + A]. Undo functioned normally with Backspace as well in all attempts.

[Ctr + A]
However, this only happened the first time [Ctr + A] was pressed. After undoing the above merge, I hit [Ctr + A] again. This time, it did not select the block text as expected, but instead selected quite literally everything on the page despite the cursor being in the block. This was true even when trying different blocks.

At this point, delete worked just fine to delete everything on the page. I then hit undo to continue.

[Undo]
After this, I decided to try manually selecting the text in the paragraph. When manually selected, the text could be deleted with [delete]. However it was impossible to get the text back with the [undo] button.

Exiting and re-entering the page reset the process. This happened both with and without plugins active (aside from Gutenberg) and on multiple posts, including new.


I don't know if this is all one issue or separate, but can confirm that delete is not behaving as expected for me either. Also I didn't want to make a duplicate issue post.

**Comment by designsimply** [comment]
Closing in order to consolidate with #8268 which is a similar enough issue it would be good to combine them. Thank you @jasmussen for the report and @cassands for testing!
