### ISSUE TITLE
Table Block: cannot see more than three columns at a time when adding new columns

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#8325]
Steps to reproduce:

1. Add a table block.
1. Click the "Edit Table" > "Add Column After" option several times.
1. Note that you can only see 3 columns at a time and a horizontal scroll bar.
1. Switch to Edit as HTML then switch back to Edit Visually.

**Note:** instead of switching to Edit as HTML and back, you can also save and refresh the page or save, close, and re-open the post.

<strong>Result:</strong> when adding several columns to a table, you cannot see more than 3 columns at a time until the view is refreshed.

<strong>Video:</strong> <a href="https://cloudup.com/cA-gxsZNZIm">1m8s</a>
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14085&action=edit running WordPress 4.9.7 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

![screen shot 2018-07-31 at tue jul 31 9 23 36 am](https://user-images.githubusercontent.com/1119271/43471199-9dc57862-94a7-11e8-996e-de7a5f8cfd87.png)

<sup>h/t @mermel for the original report (internal reference: p1532989996000185-slack-p2-gutenberg)</sup>

**Comment by talldan** [comment]
I think this is no longer an issue since the table block was re-written. @designsimply - are you able to reproduce it?

**Comment by talldan** [comment]
I've set this to close once #9801 is merged. That provides more control over table width, and sets the default width to 100% for new table blocks.

**Comment by designsimply** [comment]
@talldan! My apologies for missing this @ mention earlier! 

I re-tested just now and found that I was able to add 8 columns and no horizontal scrollbar appeared. LGTM! 🎉

![screen shot 2019-02-05 at 1 48 43 pm](https://user-images.githubusercontent.com/1119271/52303298-dd62be00-294c-11e9-939b-709bd0bb838d.png)
