### ISSUE TITLE
Simplify insertion flow

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#833]
After discussions with @mtias (https://github.com/WordPress/gutenberg/issues/798#issuecomment-301882482) and @aduth and seeing some of the complexity that the proposed flow for inserting (#323) has presented, perhaps we should think of a simpler flow for insertion.

To be absolutely clear —  the purpose of these mockups is to make the code simpler too. If these ideas and concepts _add_ complexity, please do let me know. They are not gospel, and your thoughts are important here. 

## Flow

The inserter lives in the Editor bar at the top, and at the bottom of the post for quick access near where you're writing:

![inserter](https://cloud.githubusercontent.com/assets/1204802/26200721/cfcc05ce-3bcf-11e7-8bf6-e87f78216926.png)

Click the inserter to open the block tray. Hovering a block in the inserter shows a blue line where the block will be inserted. The block will always be inserted *after the selected block*, and if nothing is selected, at the end of the document:

![inserter after a block](https://cloud.githubusercontent.com/assets/1204802/26200922/dfd63556-3bd0-11e7-859d-b4795e6a8a0b.png)

In the above mockup, the first two paragraphs constitute a single text block, and the last paragraph is also a separate text block. Since the caret is in the first text block, the image about to be inserted will show up after.

CC: @aduth @youknowriad —  will this make for a simpler, codewise, flow?

**Comment by youknowriad** [comment]
@jasmussen This looks good to me and simple enough in terms of "code". I'm going to try to implement it.

**Comment by mtias** [comment]
Agreed this is a much simpler flow code wise, since we only deal with block ordering. The selection state is slightly related to: #827.
