### ISSUE TITLE
Image and video blocks break out of the content column on the Twenty Ten theme. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8334]
**Describe the bug**

On the Twenty Ten theme, the image and video blocks break out of the content column and look broken. 

This could be considered a theme bug (for an 8-year-old theme 🙂), but something as simple as an image block seems like it should work near-universally. Are we missing some default CSS that we should be including for cases like this? 

**Screenshots**

_Image:_
![atomic test_](https://user-images.githubusercontent.com/1202812/43480932-9e6c5a1c-94d2-11e8-8722-af7a8d219175.png)

_Video:_
![atomic test__p 38](https://user-images.githubusercontent.com/1202812/43481233-635d928c-94d3-11e8-906d-a07fed79bda5.png)

**To Reproduce**

1. Start with a site using the Twenty Ten theme. 
2. Add an image or video block to a page. 
3. View the page.

**Tested In**
Mac OS 10.13.6, Safari 11.1.2
Mac OS 10.13.6, Chrome 67.0.3396.99
Gutenberg 3.4.0

---
Discovered during testing for #8291

**Comment by pento** [comment]
I had the same thing happen in p2 with videos. I hacked a fix into the p2's custom CSS, but I suspect this issue will be more widespread than just a handful of older themes.

For reference, this was the CSS I added:

```css
.wp-block-video > video {
	width: 100%;
}
```
