### ISSUE TITLE
Block audit: Verse

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8336]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="49" alt="screenshot 2018-07-31 20 34 31" src="https://user-images.githubusercontent.com/376315/43482662-3d7cf9e4-9501-11e8-8a2c-9c4f373316a0.png">

**Name:** Verse
**Description:** A block for haiku? Why not? Blocks for all the things! (See what we did here?)
**Category:** Formatting
**CSS class:** `wp-block-verse` in frontend and editor
**Can be converted to:** paragraph

# States

*Empty:*
<img width="689" alt="screenshot 2018-07-31 20 30 27" src="https://user-images.githubusercontent.com/376315/43482676-4606b424-9501-11e8-8800-ee1998a5bb91.png">

*Selected:*
<img width="693" alt="screenshot 2018-07-31 20 18 19" src="https://user-images.githubusercontent.com/376315/43482714-5bbd6a56-9501-11e8-8f11-e3fc98db02f0.png">

*Unselected:*
<img width="652" alt="screenshot 2018-07-31 20 29 58" src="https://user-images.githubusercontent.com/376315/43482700-534b50c2-9501-11e8-8e0f-9d03516aa7de.png">

*Placeholder:*
<img width="664" alt="screenshot 2018-07-31 20 30 19" src="https://user-images.githubusercontent.com/376315/43482689-4c0ea53e-9501-11e8-862f-a0be56985c2e.png">

# Primary (toolbar) settings

Align left, centre, right, bold, italic, strikethrough

# Secondary (sidebar) settings

Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg starter theme:**

**Atomic Blocks**

**twentyseventeen:**

**twentyten:**

# Documentation

No devdocs in https://github.com/WordPress/gutenberg/tree/master/core-blocks/verse

Suggestion for user-facing docs:

# Performance on mobile

# Accessibility

# Bugs/errors

_Individual issues will be opened for these soon_

# Suggestions

_Individual issues will be opened for these soon_

1. This one makes me even more confused about what the preformatted block is for.

2. Placeholder doesn't fit with other placeholders, stylistically.

3. Should there be an option for a link in there as well, for consistency with other text blocks?

4. Why call it "Verse" instead of "Poem"? The latter seems more descriptive.

5. The slash inserter pops up a verse block if you type "poetry", but not if you type "poem".

6. Not sure the pencil icon best represents this block. The pencil represents an *action*, whereas most of the block icons represent a visual abstraction of the actual block's appearance.

7. In a lot of themes, preformatted and verse blocks look exactly the same. (This is because they both use the `pre` element, and neither ships with default styles.)

**Comment by SuperGeniusZeb** [comment]
>Why call it "Verse" instead of "Poem"? The latter seems more descriptive.

Well, song lyrics fit this block as well, and both songs and poems have verses, hence the name, I guess.

Also, ideally the Verse block would indent soft new lines but not hard new lines. That is not actually the case right now, though. See the discussion in #4138. That would be a difference in behavior from the Preformatted block. Additionally, you probably do not want your poetry or song lyrics to use a monospace font, which is another reason this is separate from the Preformatted block. Different semantic meaning and implied styling/behavior.

**Comment by melchoyce** [comment]
We should look at replacing the block icon with a feather/quill icon.
