### ISSUE TITLE
Tips don't reappear when toggling 'Show Tips' option

### ISSUE THREAD

**Issue by maddisondesigns** [WordPress/gutenberg#8342]
**Describe the bug**
I wanted to retest another issue but I needed the tips to appear first. With the tips cleared, the _Show Tips_ option was still enabled. I tried un-ticking this option, refreshing the page and then re-ticking the option in the hope that the Tips would re-appear but they didn't.

**To Reproduce**
Steps to reproduce the behaviour:
1. Clear Tips if they're showing
2. Un-tick _Show Tips_ if it's still ticked
3. Refresh page
4. Tick _Show Tips_ option

**Expected behaviour**
Tips should re-appear when enabling the Show Tips option in the 'More' menu at the top-right of the page

**Desktop (please complete the following information):**
 - macOS Sierra 10.12.6
 - Firefox Quantum 61.0.1 (64-bit)
 - Gutenberg 3.4.0

**Comment by maddisondesigns** [comment]
I just tried on another site where the tips had been cleared. I created a new post and then published and exited the page. I then edited the page again and confirmed that Show Tips option was still ticked. I then unticked the option, closed the page and reopened, and re-ticked the option and the Tips didn't re-appear again.

Here's a vid: https://cl.ly/2D1f2J322a0F

(That vid was just made with v3.3.0 but I just updated to 3.4.0 and performed the same steps and produced the same result)

**Comment by pento** [comment]
Okay, found the problem. The default block inserter adds the tip:

https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/default-block-appender/index.js#L60-L64

But the block list inserter doesn't:

https://github.com/WordPress/gutenberg/blob/f9f20aabe4941049747670ecf76723d8767e21a3/packages/editor/src/components/block-list/block.js#L569-L572

**Comment by designsimply** [comment]
Closing in order to consolidate at #7753.
