### ISSUE TITLE
In the editor package, scss files are not rebuilt while running `npm run dev`

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#8343]
**Describe the bug**
In the editor package, scss files are not rebuilt while running `npm run dev`

**To Reproduce**
1. Run `npm run dev`
2. Make a change to a scss file in the editor package
3. Observe that the change does not trigger a rebuild

**Expected behavior**
Changes to scss file should trigger a rebuild

**Additional context**
Editing scss in the components package DOES trigger a rebuild. It seems as though this is due to the main scss file being imported in a js file, and so it's part of webpack's build tree - https://github.com/WordPress/gutenberg/blob/f9f20aabe4941049747670ecf76723d8767e21a3/components/index.js#L5

The editor's main scss file has no such import and so is not rebuilt.

**Comment by youknowriad** [comment]
I think we probably need to add `watch` support for stylesheets in the `bin/packages/watch.js` script.

**Comment by talldan** [comment]
Thanks for the pointer at @youknowriad - I've attempted a resolution in #8380
