### ISSUE TITLE
Filter to disable Gutenberg on a post-level

### ISSUE THREAD

**Issue by junaidbhura** [WordPress/gutenberg#8346]
## Issue Overview
Gutenberg can currently only be disabled on a post-type level. For more complicated setups, where the rollout needs to be more granular, there needs to be a filter which disables Gutenberg on a post-level.

This way the rollout can be, let's say, on a template by template level too.

## Expected Behavior
A new filter needs to be added in `gutenberg_can_edit_post()` for more granular control.

## Current Behavior
No such filter exists.

**Comment by designsimply** [comment]
Closing as a duplicate of #5692.
