### ISSUE TITLE
Add new block in code editor mode

### ISSUE THREAD

**Issue by nukaga** [WordPress/gutenberg#8348]
**Describe the bug**
If you add a block with the "add block" button in the upper left corner of the code editor mode, the block is added at the bottom regardless of the position of the cursor.

**To Reproduce**
1. Go to 'code editor mode'
2. Click on 'add block' button in the upper left corner
3. Scroll down to 'the bottom'

**Expected behavior**
A block (Gutenberg comment) should be added at the position of the cursor, or just below it.

**Screenshots**
![1](https://user-images.githubusercontent.com/3480985/43506912-9c7bff76-95a6-11e8-8b70-1ee7cce242fd.png)

**Desktop (please complete the following information):**
 - OS: [mac OS Sierra 10.12.6]
 - Browser [chrome]
 - Version [67.0.3396.99]

**Additional context**
- Gutenberg 3.4.0

**Comment by davoraltman** [comment]
Looks like the ability to insert blocks in the code editor has been removed:

https://github.com/WordPress/gutenberg/issues/9807

We should close this issue.
