### ISSUE TITLE
Improve handling of floated images

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#8355]
**Describe the bug**
When an image block is floated, it "merges" to whatever block is next to it, you are no longer able to move the image, so if you wanted to float it right, disliked the placement and wanted to move it around, you now have to un-float the image, move it next to a new block, and then float it again. The problem here is you may not want it wrapped with that specific line of text in the block, you may have a 10 line paragraph and the image should come in and float at line 7.

**To Reproduce**
1. Create a post with a few paragraphs of text
2. Insert an image block anywhere between the paragraphs
3. Choose the float this image left or right (doesn't matter which way)
4. Decide it should be somewhere else and try to move it

**Expected behavior**
Once the image is floated, it loses it's block boundary, so you can't drag it around by holding and dragging in the gutter. I expect an image that's now technically been converted to a static inline image, to be draggable by clicking and holding on the image, then moving it to where I want it.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 68
 - Gutenberg 3.4.0

**Comment by designsimply** [comment]
Moved to #7500 so we can consolidate. #7500 covers how to handle floated blocks in general.
