### ISSUE TITLE
IE11 Copy and pasting fails

### ISSUE THREAD

**Issue by jrmd** [WordPress/gutenberg#8359]
**Describe the bug**
When trying to copy and paste content into the editor nothing happens, in console it shows nothing as the input and nothing as the output

**To Reproduce**
1. Create a post in IE11
2. Copy some content from a website
3. Try paste it into the editor

**Expected behavior**
This should paste the desired content into the editor

**Screenshots**
[Screen cast of this happening (Droplr link)](http://bigbite.im/dgDAni)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Internet Explorer
 - Version: 11

**Additional context**
- Gutenberg Version 3.4

**Comment by Clorith** [comment]
I can confirm this behavior, with debugging enabled I've got a few warnings.

Before pasting:

```javascript
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in Unknown (created by e)
    in e (created by RemountOnPropChange(e))
    in RemountOnPropChange(e)
    in WithSelect(Component)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: t

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

Not sure if it's related, but loading up the Gutenberg editor also throws a console error in IE11, which looks similar so might be related?

```javascript
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
    in Unknown (created by e)
    in e (created by RemountOnPropChange(e))
    in RemountOnPropChange(e)
    in WithSelect(Component)

componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: t

componentWillUpdate: Please update the following components to use componentDidUpdate instead: t

Learn more about this warning here:
https://fb.me/react-strict-mode-warnings
```

**Comment by IreneStr** [comment]
This bug is still present. I also get an 'Updating failed' and 'Unspecified error' that might or might not be related.
![image 5](https://user-images.githubusercontent.com/17744553/49014853-bd12c800-f181-11e8-9743-f8c31b93ccde.png)

**Comment by ellatrix** [comment]
Is this still an issue with Gutenberg 7.1?

**Comment by Clorith** [comment]
I can't replicate this any more, so I suspect it's been resolved in a preceding commit somewhere :)

**Comment by pento** [comment]
Closing this, it appears to have been fixed at some point in the past.
