### ISSUE TITLE
Provide different oEmbed services based on locale, geography, demographic, etc.

### ISSUE THREAD

**Issue by ShinichiNishikawa** [WordPress/gutenberg#8364]
No offence but the services that are covered by the oEmbed are mainly used in the Western world.

I’m pretty sure that the following services are used less than 1% of Japanese average internet users.

- VR Image
- Animoto
- Cloudup
- CollgeHumor
- Dailymotion
- Funny or Die
- Imgur
- Issuu
- Mixcloud
- Photobucket
- Reddit
- ReverbNation
- Screencast
- Scribd
- SmugMug

Too large number of icons/services is not useful, and it's worse when there are a lot of services which a person even don't know.

**Describe the solution you'd like**

I'm not sure if this is the best solution but maybe creating a way to control what to show up.

**Describe alternatives you've considered**

Language based selection.

**Comment by danielbachhuber** [comment]
Hi @ShinichiNishikawa,

Thanks for the report.

> I'm not sure if this is the best solution but maybe creating a way to control what to show up.

You do have control over which blocks appear. One suggestion would be to create a `Japanese Embed Services` plugin which deregisters the default embed blocks, and then registers embed blocks for popular Japanese services.

I'm not sure Gutenberg will do something like this in the near future, but it's certainly a good idea to keep on the radar.

**Comment by ShinichiNishikawa** [comment]
Thank you for the suggestion! I'll do that!

**Comment by swissspidy** [comment]
Although it sounds interesting at first glance, from a WordPress core point of view I don't think it would be feasible to add something like this.

On a multi-author site with people from all over the place it would be really weird if one person would saw embed option X and the other option Y.

On an English site it would be really confusing if embed option Z suddenly disappears after installing the Japanese translation.

**Comment by swissspidy** [comment]
Suggesting closing this one as a won't fix.

**Comment by jasmussen** [comment]
Closing as suggested. We can always revisit. Thank you for the report!
