### ISSUE TITLE
Intermittently, multiple preview tabs are opened in the preview e2e test

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#8367]
**Describe the bug**

See: https://github.com/WordPress/gutenberg/pull/8301/files#diff-46acebe2b5c3907767eb03ce378ad48fR106

**To Reproduce**

1. Be me. Half joking here, but this is intermittent and of all the environments I've seen this happen in, it's most frequent on my baremetal linux setup.
2. Remove the part of the code from the above commit that closes and opens the preview tab
3. Run the test in non-headless mode (makes no difference, but you can _see_ the effect)
4. Sometimes, the test opens two preview tabs, and should not.

**Expected behavior**

There should only ever be one preview tab open.

**Comment by aduth** [comment]
Has this been resolved? Thinking by either #8301 and/or #8330

**Comment by notnownikki** [comment]
Will move this up on my list of things to check!

**Comment by notnownikki** [comment]
Looks fine now! I've opened a PR to remove the workaround at https://github.com/WordPress/gutenberg/pull/8928
