### ISSUE TITLE
Single line breaks become paragraphs when pasting from Google Docs

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#8371]
Steps to reproduce:

1. Copy some content from a Google Doc that has single line breaks.
1. Paste the content into a new post.
1. Check to see if single line breaks are retained.

<strong>Result:</strong> single line breaks are not respected when pasting content from another source.

<strong>Video:</strong> [52s](https://cloudup.com/c4My2QnsHPR )

![screen shot 2018-08-01 at wed aug 1 11 28 25 am](https://user-images.githubusercontent.com/1119271/43538082-42f84482-957e-11e8-868c-0b844a01dc94.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14100&action=edit running WordPress 4.9.7 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Note:** also tested copying and pasting content with single line breaks from another webpage and it worked in that case. Would it be worth testing other editors besides Google Docs?

h/t @annezazu for the original report.

**Comment by mtias** [comment]
Proper line breaks are pasting correctly for me. Google Docs shows paragraphs by default without margins, so they may look like line breaks but are really new paragraphs.
