### ISSUE TITLE
Classic Block: Read More tag is missing "More" text label. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8372]
**Describe the bug**

In the current classic editor, the "More" divider has a text label inside of it, to more clearly convey what the dotted line means:

<img width="643" alt="screen shot 2018-08-01 at 1 56 34 pm" src="https://user-images.githubusercontent.com/1202812/43539675-82d08b7c-9593-11e8-98d9-88fc0d5c1afc.png">

The classic block removes that label: 

<img width="599" alt="screen shot 2018-08-01 at 1 56 39 pm" src="https://user-images.githubusercontent.com/1202812/43539685-89918376-9593-11e8-9f5d-a248a7c7946c.png">

I'm unsure if that was intentional or not, but I think including the label would be more clear — the dotted line on its own is confusing. 

**To Reproduce**

1. Add a Classic block
2. Insert a "Read More" tag from the Classic bar's toolbar.

**Comment by draganescu** [comment]
@kjellr It appears to have been an optimisation of some sort, b/c in the classic editor the more tag used a large image to set that more text on a dashed line while the classic block uses a dashed border. I am looking into using some pseudo element in the classic block to achieve the same effect.
