### ISSUE TITLE
Header text scale is inconsistent and should be standardized. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8373]
In the Classic Editor block, the header text sizes (and line heights) do not match the header text sizes used in the rest of the editor. These should be identical.

Classic Editor:

<img width="673" alt="screen shot 2018-08-01 at 2 34 06 pm" src="https://user-images.githubusercontent.com/1202812/43541383-4febb3bc-9598-11e8-9b1d-4e2179f1ecb5.png">

Gutenberg Header Blocks:

<img width="651" alt="screen shot 2018-08-01 at 2 34 11 pm" src="https://user-images.githubusercontent.com/1202812/43541399-5c6e6e0e-9598-11e8-86b3-9550a6477f86.png">

**Comment by kjellr** [comment]
Cool — I've updated the title to make it a bit more broad in that case.

**Comment by afercia** [comment]
Please notice in #8069 there's some more detailed information that is important to correctly address this issue. Also, avoiding rounding should be considered also for paragraphs, see example and screenshots on https://github.com/WordPress/gutenberg/issues/8069#issuecomment-407006362

**Comment by jorgefilipecosta** [comment]
Hi @kjellr it seems like to solution to this is update the classic block styles to match the rest of the editor. Could you confirm if that's the case?

**Comment by kjellr** [comment]
@jorgefilipecosta Yes, that's a good first step. I think we'd also wanted to address the fraction-of-a-pixel rendering caused by our type scale (as noted in #8069 too), but that can be handled separately. 

For now, it's definitely weird that a `h2` in the classic block isn't the same size as a `h2` outside of it for instance. So fixing that would be great.
