### ISSUE TITLE
Classic block: "Paste as Text" notification uses inconsistent styles.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8374]
**Describe the bug**

Inside of a classic block, you can toggle a "Paste as Text" button in the toolbar to paste contents as plain text. The first time you select this option, you're shown a notification that explains its functionality: 

<img width="1258" alt="screen shot 2018-08-01 at 3 18 50 pm" src="https://user-images.githubusercontent.com/1202812/43543511-391a4ec2-959e-11e8-8ee9-2871dd65d93d.png">

The style and placement of this notification are inconsistent with everything else in the editor — it feels broken. I wonder if we can customize it a bit so it doesn't feel so out of place?  

**To Reproduce**
1. Add a Classic editor block
2. Click "More" in the classic editor toolbar to show the second row of controls.
3. Click the "Paste as Text" button in the second row of the classic editor toolbar.

_([Note that this issue does exist in the Classic Editor as well.](https://cloudup.com/cI26_7Grbot))_

**Comment by karmatosed** [comment]
Design wise, lets use the strip message we have in place over blocks. I think ideally though yes let's get this made more inline with what we have usually.

**Comment by kjellr** [comment]
Thanks! Here's a mockup, using that pattern (Visually, it's similar to the ["This block has been modified externally" message](https://cloudup.com/cil-2LivUmT)). 

![mockup](https://user-images.githubusercontent.com/1202812/43662982-cbc1da86-9735-11e8-95d9-d4386bf8d051.png)

**Comment by karmatosed** [comment]
@kjellr that totally is what I was thinking thanks.

**Comment by paaljoachim** [comment]
This issue is still valid in WordPress 5.7 beta 3 and Gutenberg plugin 10.
Tested with Twenty Twenty One.

![Screen Shot 2021-02-21 at 00 02 23](https://user-images.githubusercontent.com/5323259/108610701-1822dc00-73d8-11eb-974b-65e77a348e4e.png)

@tellthemachines @talldan @jasmussen

**Comment by talldan** [comment]
This is still a very low priority.

**Comment by Mamaduka** [comment]
I think we can close this minor bug. The general plan is to deprecate the Classic block. See #50387.

**Comment by t-hamano** [comment]
If the editor is running as an iframe, the content will be edited in a modal. Note that in this case, the notification text will be almost invisible:

![Image](https://github.com/user-attachments/assets/480a7c83-a06e-4ddc-af02-083d983b93d2)

> I think we can close this minor bug. The general plan is to deprecate the Classic block. See https://github.com/WordPress/gutenberg/pull/50387.

However, I agree with this, so I think this issue can be closed.

**Comment by jasmussen** [comment]
Let's close for now, and we can reopen if the issue re-emerges.
