### ISSUE TITLE
Data loss when converting to a shared block

### ISSUE THREAD

**Issue by wpscholar** [WordPress/gutenberg#8375]
**Describe the bug**
In some cases, a block is altered when converting to a shared block.

See: https://github.com/WordPress/gutenberg/issues/7098#issuecomment-407810840

**To Reproduce**

1. Add a pull-quote block to the page
2. Add a citation to the block
3. Convert the block to a shared block
4. The citation in my case was altered (middle character only was retained)

**Note:** This appears to be an intermittent issue or some sort of race condition as I've not had it break since. This may warrant a further investigation/testing.

**Expected behavior**
That the contents of the block would persist when converted to a shared block.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: 67.0.3396.99

**Additional context**
- Gutenberg version 3.4

**Comment by jorgefilipecosta** [comment]
Hi @wpscholar thank you for reporting this issue. I tried to reproduce this bug in the last version of Gutenberg multiple times and I was never able to reproduce the problem. I'm closing the issue for now if you manage to reproduce the problem again feel free to reopen and we can look further.
