### ISSUE TITLE
Fixed toolbar loses buttons when switching between classic and any other block

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#8376]
**Describe the bug**
If you have the Fixed toolbar option enabled, then select the classic block, followed by selecting any other block, the toolbar that should be fixed at the top only shows the block converter option.

This only happens the first time you pick a new block after selecting the classic block, moving to another non-classic block then back to your intended block will show the options again.

There are no console errors during this.

**To Reproduce**
1. Select `Fix toolbar to top`
2. Create 2 blocks of any text type (paragraphs, quotes etc)
3. Add a Classic block
4. Select one of your other two blocks and see the toolbar is now empty, except for the block change option.
5. Select the other of your 2 existing blocks, the toolbar now appears
6. Select the first of the two regular text blocks and it, too, now has a toolbar as it should.

**Expected behavior**
The toolbar is always appropriate when fixed, there is no similar problem if the toolbar is not fixed to the top.

**Screenshots**
![fixed-toolbar](https://user-images.githubusercontent.com/468735/43550422-ce6fa45a-95e3-11e8-8f03-e0f4baeead81.gif)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 68
 - Gutenberg 3.4.0

**Comment by youknowriad** [comment]
Some debugging information:

It looks like this bug only happens when you switch to "fixed toolbar" but before reloading the page, if you reload the page everything works as expected. It could be that a component has a state value not updating when props change, but I can't find it at the moment.

**Comment by youknowriad** [comment]
I'm not able to reproduce this issue anymore.
