### ISSUE TITLE
Event or callback after block loaded on editor

### ISSUE THREAD

**Issue by adekherry** [WordPress/gutenberg#8379]
I'm making a block that using ServerSideRender. In this case, i will need to trigger some javascript (jquery) function when the element finish loaded on the backend editor. Is there any event listener or hook for gutenberg for this case?

**Comment by buzzclue** [comment]
@adekherry have you found the solution? 
```
el( ServerSideRender, {
	block: 'meetongo/meetup-slider',
	attributes: props.attributes,
	onChange: sliderIsUpdated()
} ),
```

I have tried onChange but its triggered before render or right after block settings have changed.

**Comment by adekherry** [comment]
@buzzclue, previously i  create a new components (extends the ServerSideRender components), then i override componentDidUpdate method. It's looks like this:

<pre>
componentDidUpdate( prevProps, prevState ) {
		super.componentDidUpdate(prevProps);
		if ( this.state.response !== prevState.response ) {
			// do something
		}
	}
</pre>

**Comment by designsimply** [comment]
@adekherry I am closing this issue because it appears that you have found a solution already. If I have misread that or if you are suggesting a change to `componentDidUpdate` would you please leave a comment letting me know so I can re-open the issue in that case?

**Comment by premitheme** [comment]
Hi, I'm still a beginner in React and learning about all the new stuff about WP editor.

I searched a lot but didn't find any related issues other than this, so I chose to reopen it instead of creating another one.

I'm trying to create a custom image slider block/carousel, and I faced the same problem: I need an event to hook the slider init function to.

Whether the block renders the structure directly or using `ServerSideRender` for doing this, I think it's helpful and very important to have a built-in block-specific event that is fired directly after the block is loaded (each block has its own event, maybe using block name as an identifier).

For example, I used to create custom widgets for Elementor, it provides such an event for every widget so I can make sure that my custom scripts initialized at the right moment.

If there's already such a way for doing this, or I'm missing anything, please direct me.

**Comment by dgwyer** [comment]
I also need this.

I have a block that runs some vanilla JS (i.e. not React) as soon as the page is ready. At the moment it's contained inside a jQuery ready block.

```JS
jQuery(document).ready(function ($) {
  // code here...
}
```

This works fine on the front end but not for the block editor as the code should run as soon as the page/editor is ready.

Incidentally, if the code was waiting for some interaction from the user such as a form submission or a mouse-click then it would work fine as the editor would have fully loaded before this could take place.

Ideally, the code should only run if the editor is loaded and all blocks have been mounted.

**Comment by mohsinrasool** [comment]
@designsimply Any news on this? I want to call some functions as soon editor is visible and whole page is rendered. On WP 5.2.2, `jQuery(document).ready(function () {` and `wp.domReady(function() {` both called the function before components are rendered.

Are there any similar function or events that we can use to accomplish this situation?

Thanks

**Comment by designsimply** [comment]
@mohsinrasool I'm sorry but this is a bit outside of my expertise. May I ask that you please try asking for help at https://wordpress.stackexchange.com/ and include a code sample for them if possible.

**Comment by codersantosh** [comment]
I was also looking for the same options but could not find any solutions anywhere. It seems like no event trigger after block loaded. 

I have created following function and it works.

```
let blockLoaded = false;
let blockLoadedInterval = setInterval(function() {
    if (document.getElementById('post-title-0')) {/*post-title-0 is ID of Post Title Textarea*/
        //Actual functions goes here

        blockLoaded = true;
    }
    if ( blockLoaded ) {
        clearInterval( blockLoadedInterval );
    }
}, 500);
```

**Comment by mohsinrasool** [comment]
It will work in some cases only. Because, React render each component based on its states. So, what I want to do, this snippet can't help me.  Thanks for sharing, anyway.

**Comment by BrunoIvanAmadori** [comment]
> I was also looking for the same options but could not find any solutions anywhere. It seems like no event trigger after block loaded.
> 
> I have created following function and it works.
> 
> ```
> let blockLoaded = false;
> let blockLoadedInterval = setInterval(function() {
>     if (document.getElementById('post-title-0')) {/*post-title-0 is ID of Post Title Textarea*/
>         //Actual functions goes here
> 
>         blockLoaded = true;
>     }
>     if ( blockLoaded ) {
>         clearInterval( blockLoadedInterval );
>     }
> }, 500);
> ```

Thank you so much for this snippet. Definitely saved the day. Great workaround.

Although I'm still dissatisfied... It seems there's no way to attach code after all the Gutenberg editor is loaded, being outside of Gutenberg.

All solutions I got on google point to "componentDidMount", but I can't access to that unless I'm coding a Gutenberg React plugin I understand... which is not the case.

**Comment by sanzeeb3** [comment]
> I was also looking for the same options but could not find any solutions anywhere. It seems like no event trigger after block loaded.
> 
> I have created following function and it works.
> 
> let blockLoaded = false;
> let blockLoadedInterval = setInterval(function() {
>     if (document.getElementById('post-title-0')) {/*post-title-0 is ID of Post Title Textarea*/
>         //Actual functions goes here
> 
>         blockLoaded = true;
>     }
>     if ( blockLoaded ) {
>         clearInterval( blockLoadedInterval );
>     }
> }, 500);

Thanks @codersantosh for sharing the solution. Post title text area id is now `post-title-1`?

**Comment by mitogh** [comment]
In case someone is still looking for a solution that is not using intervals and relies in events from the editor to avoid race conditions you can use:

```js
const { select, subscribe } = wp.data;

const closeListener = subscribe( () => {
	const isReady = select( 'core/editor' ).__unstableIsEditorReady();
	if ( ! isReady ) {
		// Editor not ready.
		return;
	}
	// Close the listener as soon as we know we are ready to avoid an infinite loop.
	closeListener();
        // Your code is placed after this comment, once the editor is ready.
	alert( 'is ready' );
});
```

**Comment by digamber89** [comment]
@mitogh where exactly should i write this code ?

**Comment by mitogh** [comment]
Usually this code is placed, on any JS file that loads alongside the editor on your site. 

For example: main.js

Make sure you enqueue only for the admin screen @digamber89

**Comment by land0r** [comment]
Why is it a closed issue? We still needed such functionality

**Comment by Skatox** [comment]
Why is this issue closed? This is a required feature for many developers.

**Comment by ughimire** [comment]
I am also searching for the same feature. It's already available ? Why it's closed now ?

**Comment by dennisheiden** [comment]
> In case someone is still looking for a solution that is not using intervals and relies in events from the editor to avoid race conditions you can use:
> 
> ```js
> const { select, subscribe } = wp.data;
> 
> const closeListener = subscribe( () => {
> 	const isReady = select( 'core/editor' ).__unstableIsEditorReady();
> 	if ( ! isReady ) {
> 		// Editor not ready.
> 		return;
> 	}
> 	// Close the listener as soon as we know we are ready to avoid an infinite loop.
> 	closeListener();
>         // Your code is placed after this comment, once the editor is ready.
> 	alert( 'is ready' );
> });
> ```

This works. I use this to register a block style for all available blocks at once.
Just enqueue a js file in editor screen view within your plugin / theme.

**Comment by lipemat** [comment]
I came up with a workaround which seems to do the job while we wait for a stable event.
By passing a `LoadingResponsePlaceholder` component to `ServerSideRender` we can call an action when the "Loading" component unmounts, thus firing when loading has finished.

Something like this.
```js

const TriggerWhenLoadingFinished = attributes => {
	return ( {children, showLoader} ) => {
		useEffect( () => {
			// Call action when the loading component unmounts because loading is finished.
			return () => {
				doAction( 'server-side-loading-finished', attributes );
			};
		} );

		return (
			<div style={{position: 'relative'}}>
				{showLoader && (
					<div
						style={{
							position: 'absolute',
							top: '50%',
							left: '50%',
							marginTop: '-9px',
							marginLeft: '-9px',
						}}
					>
						<Spinner />
					</div>
				)}
				<div style={{opacity: showLoader ? '0.3' : 1}}>
					{children}
				</div>
			</div>
		);
	};
};
<ServerSideRender
	LoadingResponsePlaceholder={TriggerWhenLoadingFinished( attributes )}
	attributes={attributes}
	block={block}
	httpMethod={'POST'} />
```

Note the loader contents was taken verbatim from the server-side-render package's `DefaultLoadingResponsePlaceholder` component. (not exported).

**Comment by adrianahdez** [comment]
For me, the solution proposed by @mitogh didn't work, and the one proposed by @codersantosh was the one that helped me (thanks!!).

In my case, I wanted to add some JavaScript to a specific block (the latest-posts block) which was to add a "Read more" button to posts cards, so I needed the block and the class .wp-block-latest-posts__list to exists in the DOM before I execute the function that append the button, in order the querySelector can find it.

So my javascript file ended up like this:

```
(function () {

  /**
   * Append the read-more button to each post card in the latest posts block
   */
  const addReadMoreButtonToPostCards = () => {
    const postCards = document.querySelectorAll('.wp-block-latest-posts__list > li');
    postCards && postCards.forEach((postCard) => {
      // ...The code to append the 'read more' button...
    });
  };

  /**
   * Check if I'm in the editor
   */
  function isGutenbergActive() {
    return document.body.classList.contains( 'block-editor-page' );
  }

  /**
   * Perform an action when a block is loaded on the editor. Wait for the block to be loaded and then execute the function.
   * @param {string} blockSelector - The block selector to wait for
   * @param {function} action - The function to execute when the block is loaded
   */
  const onBlockLoadedInEditor = (blockSelector, action) => {
    let blockLoaded = false;
    let blockLoadedInterval = setInterval(function() {
        if (document.querySelector(blockSelector)) {
          action();
          blockLoaded = true;
        }
        if ( blockLoaded ) {
            clearInterval( blockLoadedInterval );
        }
    }, 500);
  };
  
  window.addEventListener("DOMContentLoaded", function () {
    if (isGutenbergActive()) {
      // For the editor:
      onBlockLoadedInEditor('.wp-block-latest-posts__list > li', addReadMoreButtonToPostCards);
    
    } else {
      // For the front-end:
      addReadMoreButtonToPostCards();
    }

  });
})();
```
