### ISSUE TITLE
Backspace jumps to previous block instead of going to previous line in same paragraph block

### ISSUE THREAD

**Issue by SNaushadS** [WordPress/gutenberg#8388]
**Describe the bug**
When working in a Paragraph Block, hitting backspace skips the previous empty line and jumps to previous block

**To Reproduce**
1. Create a New Post
2. Add 2 Blocks
An Image Block and a paragraph Block
3. In the paragraph block have an empty line followed by a second line with text.
4. Go to the start of the second line and hit Backspace.
5. Observe that the focus moves to the previous block i.e.: Image block.

**Expected behavior**
The cursor should delete the first line and move the Line 2 text up 1 row.

**Screenshots**
GIF Captures for the same.
Tested by Creating a New Post
![wp-para-block-2](https://user-images.githubusercontent.com/1532907/43581886-206023cc-9678-11e8-900b-742727f469b1.gif)

Observed originally while working on this post.
![wp-para-block](https://user-images.githubusercontent.com/1532907/43581887-209be038-9678-11e8-9f78-79ace9760c36.gif)

**Comment by designsimply** [comment]
Possibly related: #8268.

**Comment by aduth** [comment]
Fixed by #8461
