### ISSUE TITLE
Image block: secondary settings hidden on mobile

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8390]
The image block on desktop shows a whole slew of secondary settings:

<img width="299" alt="screenshot 2018-08-02 14 00 46" src="https://user-images.githubusercontent.com/376315/43585260-98ff5dfa-965c-11e8-9841-806aa316f69f.png">

On smaller screens, they're all hidden:

<img width="299" src="https://user-images.githubusercontent.com/376315/43585362-d29d4e8c-965c-11e8-9bde-7892c376f41b.png">

We should probably show them everywhere instead.

**Comment by nfmohit-wpmudev** [comment]
Possible duplicate of #8056, fixed by #7781.

**Comment by sarahmonster** [comment]
Whoops, my bad. Thanks!
