### ISSUE TITLE
Image block: clarify what alternative text is used for

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8391]
The image block offers some contextual help to explain what alt text is, but I think we could make it a bit more clear. Getting the explanation right will help more people create accessible sites. 🎉

<img width="296" alt="screenshot 2018-08-02 14 17 22" src="https://user-images.githubusercontent.com/376315/43586193-e0e100ea-965e-11e8-91fa-e08522f38665.png">

Currently it reads:

> Describe the purpose of the image. Leave empty if the image is not a key part of the content.

As a user with no understanding of alternative text, my instinct here is to write something like "The purpose of this image is to illustrate my post", which isn't really helpful.

What about instead, something along the lines of:

> Alternative text is used to describe your image to people who may not be able to see it. Provide a short description of the image or leave empty if the image isn't important to your post content.

**Comment by designsimply** [comment]
Would a link to more info be preferable to keep descriptive text short so that it doesn't make the UI too cluttered? Also keep translation in mind.

**Comment by sarahmonster** [comment]
A link to more detailed documentation would be 💯!
