### ISSUE TITLE
Can block attributes be defined as a function?

### ISSUE THREAD

**Issue by ccprog** [WordPress/gutenberg#8394]
The [blocks API readme](https://github.com/WordPress/gutenberg/blob/master/packages/blocks/README.md) states the following about the `attributes` property of type definitions:

> `attributes: Object | Function` - An object of attribute schemas... Alternatively, define attributes as a function which returns the `attributes` object.

I found no other information about this variant and could not trace it back in the sources. Does it even exist? If yes, when is that function executed, and with which parameters?

**Comment by youknowriad** [comment]
This was possible at some point but we removed it because it's not context-agnostic (it can't work on the server). The docs have been updated.
