### ISSUE TITLE
Image block: consolidate + simplify size controls

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8397]
If I want to change the size of an image, there are currently four different ways of accomplishing this:

- the image size drop-down
- editing the width and height values
- selecting 25/50/75/100%
- scaling using the blue dot handles.

This leads to a slightly cluttered-looking settings sidebar:

<img width="978" alt="screenshot 2018-08-02 14 30 18" src="https://user-images.githubusercontent.com/376315/43592560-bc1fb990-966d-11e8-8302-88771effcf26.png">

As a user, I don't immediately understand the difference between "Image size" and "Image dimensions", and it's not immediately clear (particularly in a default state) what the former refers to.

**Some suggestions for improvement:**

- Since there's so much going on with the image size, I think it might be better if it were its own section/panel here, at the very least.
- "Image size" should be renamed to something more descriptive—"predefined image size"? I'm not sure exactly what it should be called, but I'm sure there's a better way to communicate "size templates that your theme or plugins have provided."
- I think the 25/50/75/100 would be a good candidate for removal here. My guess is that they exist here to allow proportional image resizing, but I think that could be better accomplished with a "lock proportions" button here, a la graphics programs:

<img width="314" alt="screenshot 2018-08-02 17 11 12" src="https://user-images.githubusercontent.com/376315/43596447-3bfe9b14-9677-11e8-9afd-97a1bccb4c2f.png">

<img width="209" alt="screenshot 2018-08-02 17 12 09" src="https://user-images.githubusercontent.com/376315/43596448-3c85aaaa-9677-11e8-890b-39fa60c0481c.png">

**Comment by xavivars** [comment]
IMHO, the blue dots are everything but intuitive, even more when the image has a white background. (see example)

![image](https://user-images.githubusercontent.com/134083/48793460-4d22be80-ecf7-11e8-9e74-8dbdff7ff5c8.png)

 It would be great if there was some kind of "dashed/dotted border highlighting", like in some image editors, that would make it easier to realize those are actual places to scale the image. Also, having a blue dot in the bottom-right corner (to fix ratio) would be great.

**Comment by nabrown** [comment]
Are there any plans to implement the lock aspect ratio bit of this enhancement? I agree the % selectors should be removed. It's not even clear if it indicated a percent of the image's inherent dimensions or a percent of its container.

**Comment by mtias** [comment]
The biggest part of this work is going to happen through the "Dimensions" panel described in https://github.com/WordPress/gutenberg/issues/27331

**Comment by mtias** [comment]
There's a lot of improvements in the width handling and more to come. Going to close this as it's not very actionable on its own.
