### ISSUE TITLE
File block: Outputs an unencoded line break on frontend

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8402]
The file block looks like this in the editor:

<img width="729" alt="screenshot 2018-08-02 18 43 23" src="https://user-images.githubusercontent.com/376315/43600969-f88c9ff4-9683-11e8-8dfd-699bd51729a9.png">

But when I preview the post in my theme, I'm seeing an unencoded line break. This, in turn, mucks up some of the post that follows it:

<img width="676" alt="screenshot 2018-08-02 18 36 18" src="https://user-images.githubusercontent.com/376315/43600628-0c6d0ab4-9683-11e8-85f8-fcd625d92d44.png">

This seems to have been recently introduced, and/or it only happens when you edit the filename text. 

### Unedited text 👌
<img width="332" alt="screenshot 2018-08-02 18 45 56" src="https://user-images.githubusercontent.com/376315/43601117-65e58ebc-9684-11e8-8e20-0e1f0b554ec2.png">

### Edited text 😱
<img width="561" alt="screenshot 2018-08-02 18 46 17" src="https://user-images.githubusercontent.com/376315/43601193-a4bdee40-9684-11e8-878d-e669ff320077.png">

## Steps to reproduce:
1. Insert a new file block.
2. Upload a file.
3. Edit the filename text string in the editor.
4. Preview the post.
5. Line breaks ensue.

**Comment by jorgefilipecosta** [comment]
Hi @sarahmonster thank you for reporting this issue. I'm not being able to replicate this problem. File block was changed to use RichText and I think as a side effect this bug got solved. If you are still able to reproduce this problem feel free to reopen the issue and I will look again into this problem.
