### ISSUE TITLE
Make it easier to insert a Reusable block as a standalone block (using the Reusable block as a template)

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#8403]
## The issue
Reusable blocks are good for things like footers or headers. Or at least, they will be once Gutenberg gets to the template building stage.

But sometimes you do not want to have a globally-updating block reused in multiple places. Often, you just want a pre-made template that you can quickly insert and then modify for the post/page you are using it in.

Examples include a Container block with nested Paragraph and Button blocks used as a call-to-action template. You would not want all CTAs to be exactly the same, but you would want a quick template you could insert.

Now, you can technically already use Reusable blocks like this:
![image](https://user-images.githubusercontent.com/19592990/43973106-21f1cde2-9c9c-11e8-9add-d113dc502aac.png)

However, while this is nice, it is not very discoverable, and is kind of clunky. In order to use a Reusable block as a template, you have to convert it to a standalone block after you have already inserted. This feels a bit awkward, particularly in comparison to existing page builder plugins.

## Proposed solution

I suggest that, upon clicking a Reusable block in the inserter, a pop-up/dropdown appears that allows you to choose whether to insert it as a global instance or as a standalone regular block.

Here is what this looks like for Reusable Parts in Oxygen:

![image](https://user-images.githubusercontent.com/19592990/43602757-7f9005a0-9656-11e8-9a9f-cc5d5c0e4a54.png)

**Comment by slimmilkduds** [comment]
This would really be great, I’m introducing more and more people to our inhouse Gutenberg project and this is one request that comes up very frequently (the other one being ”why can’t I make a template with a reusable block that uses columns without it breaking when I convert”)

**Comment by chrisvanpatten** [comment]
I have some ideas for this that I'd like to explore… leaving this as a note to remind myself to do this :)

**Comment by cecoates** [comment]
I found myself naturally trying to use blocks in this way.

What if it was a toggle switch instead, though. That way if you're the type of person who needs to add a lot of template type blocks, you don't have those extra clicks each time.

Global toggle on:

Blocks are inserted that when edited, update the reusable block period.

Global toggle off:

Blocks are inserted into posts, editable, and the changes aren't saved back to the reusable block.

**Comment by JiveDig** [comment]
Coming from the discussion on a Section block, this makes so much sense and would be an amazing part of Gutenberg core.

**Comment by noisysocks** [comment]
This touches on some of the themes that we'll be exploring as part of Phase 2.

**Comment by starxedsteph2** [comment]
> I found myself naturally trying to use blocks in this way.

I had the same expectation initially.

Reusable template blocks would be a huge time saver for my team when writing complicated posts that have one of a few set templates each time.

**Comment by Orlandster** [comment]
@noisysocks Some update on this one would be great! It's not in the `Phase 2` project so far.

**Comment by noisysocks** [comment]
This isn't a priority for Phase 2 or the current [WordPress roadmap](https://wordpress.org/about/roadmap/).

**Comment by noisysocks** [comment]
> However, while this is nice, it is not very discoverable, and is kind of clunky. In order to use a Reusable block as a template, you have to convert it to a standalone block after you have already inserted. This feels a bit awkward, particularly in comparison to existing page builder plugins.

Perhaps a simpler change we could make here is to improve this flow by making _Convert to Regular Block_ a more primary action in the interface? 

<img width="620" alt="Screen Shot 2019-06-07 at 14 55 22" src="https://user-images.githubusercontent.com/612155/59082004-4aef1d00-8934-11e9-8341-99a5d03a77c5.png">

What do you think, @mapk?

**Comment by slimmilkduds** [comment]
@noisysocks I think what you are suggesting  would be a improvement for sure! I would  prefer an option when you import the block but this would certainly be better than nothing.

**Comment by mapk** [comment]
Thanks for the ping @noisysocks!

This issue is definitely leaning towards "Block Templates" which is something we're exploring very soon! 

In the interim, I think @noisysocks' solution is about right. I love the language of "Detach" because it reminds me of Sketch, but I don't think that word will work on its own with other WP users.

Maybe... 

`Detach from reusable block`
`Convert to regular block`

Wow, I'm struggling here. @michelleweber, can you help? We need some button language that informs the user that the action will detach the reusable block from the reusable block pattern and convert it to just regular blocks.

**Comment by michelleweber** [comment]
Just to make sure I get what's going on here: when I detach, it turns my block into a stand-alone editable block but the resuable block still exists and can be used again? Or does clicking detach on one instance of a resuable block detach all instances of the reusable block? Or neither of those things?

**Comment by mapk** [comment]
@michelleweber, detaching it from a reusable block just makes this current instance its own block. The reusable block still exists and is untouched.

**Comment by michelleweber** [comment]
Hmm. This is a pretty new kind of action within WP, so that gives us a little more leeway with words -- we can establish the word that describes this action. 

I don't love "convert" because it doesn't make clear that this block is becoming its own thing AND the reusable block is still there; I think you need something like detach, or sever, or disconnect. I feel like "disconnect" is probably the least scary sounding of those, altho we'd want to think about whether there are other places in the UI that use that word and whether using it here would be consistent.

I'm gonna ask Obi Elledge to take a peek at this, too.

**Comment by obi2020** [comment]
Agree with @michelleweber that `convert` isn't the right description, so thinking of other ways to say `disconnect`:

My first thought was `decouple` which, of course, is terrible. So I looked for synonyms:

`split` 
`separate`
`unlink` 

FWIW I think `detach` is also a good option

**Comment by mapk** [comment]
@michelleweber and @obi2020 It appears "Detach" is the way to go. Do you think we need the extra language of "Detach from reusable block" or "Detach block"? Or can we simply use the one word, "Detach"?

Would love your thoughts here!

**Comment by michelleweber** [comment]
I think this is a new enough action that the additional detail is useful. I'd opt for the longer, more descriptive option here.

**Comment by mapk** [comment]
@noisysocks let's try using "Detach block" and see if that's clear enough. If we just had a cool name for reusable blocks, like "symbols" or something, than we can use that one word. Oh well.

**Comment by colinduwe** [comment]
I'll echo the feedback of others that I expected reusable blocks to be reusable templates of pre-configured sets of blocks.  Maybe the change needs to happen when the user creates the re-usable block. 
Click "Add to Reusable Blocks" 
Enter a name
Set a radio: Reusable Template / Global Block 

That seems easier for a less-trained content writer because they can use the "Foobar" reusable block just like a paragraph block.

**Comment by talldan** [comment]
Thinking aloud, I was wondering if there might be a printing analogy:
- "Stamp Blocks"
- "Imprint Blocks"
- "Paint Blocks"

Not sure though, might be a bit crazy and I still don't think it accurately describes the process, but thought I'd share just in case it leads to other ideas.

**Comment by ZebulanStanphill** [comment]
@talldan I really doubt the printing analogy would be easily explainable to the average user.

I recently had an idea: perhaps a toolbar button to detach a block from the reusable instance would make things easier? It would make the action more visible compared to hiding it in the <kbd><samp>More options</samp></kbd> menu.
![image](https://user-images.githubusercontent.com/19592990/70069074-cdd8f380-15b6-11ea-818e-5e959fd0751f.png)

**Comment by phpbits** [comment]
@ZebulanStanphill You can use [EditorsKit](https://wordpress.org/plugins/block-options/) plugin which is free on the plugin directory. I've recently added a toolbar option to easily convert reusable block to regular blocks.

![Make it easier to insert a Reusable block as a standalone block (using the Reusable block as a template)
](https://user-images.githubusercontent.com/3365507/70635380-c24c9300-1c6e-11ea-8074-5de2fe64697a.gif)

**Comment by mapk** [comment]
When I see it in play, I'm liking "convert" as a word to use. "Detach" does feel  a lot more messy.

**Comment by talldan** [comment]
I closed #18814 as a duplicate, but that issue also had the suggestion of duplicating reusable blocks in addition to detaching them as something that would be quite useful. The use case was creating variations of existing reusable blocks.

**Comment by noisysocks** [comment]
It's worth noting that a Reusable Block which, when selected, inserts a copy of Reusable Block and not a `core/block` is exactly what a Block Pattern is. There may be an opportunity to fuse these two concepts (see https://github.com/WordPress/gutenberg/issues/21080#issuecomment-616276449).

For now, moving _Convert to Regular Block_ from the _More options_ menu to the Reusable Block toolbar as per https://github.com/WordPress/gutenberg/issues/8403#issuecomment-499756305 is a good first step and is sufficient for closing this issue.

**Comment by youknowriad** [comment]
It seems like this issue means: "making reusable blocks behave as patterns". While there's value in that, the confusion with block patterns will become more important. It can also be understood as "Add a way to persist custom patterns" (and there are already plugins for that).

**Comment by ZebulanStanphill** [comment]
When I created this issue, block patterns didn't exist yet.

The difference between a reusable block and a block pattern is simply that one is shared-instance, and the other is just a template that is cloned upon use. But other than that, they're really not that different at all.

However, one thing that is notably missing from block patterns is the ability for the user to create their own. Right now, users have to use reusable blocks as a stand-in for block patterns since they can create reusable blocks but not block patterns.

Is there an open issue about allowing users to create their own patterns?

**Comment by skorasaurus** [comment]
@ZebulanStanphill not sure if there is, but in the absence of one; I've been using https://github.com/justintadlock/block-pattern-builder to make them.

**Comment by ZebulanStanphill** [comment]
I've begun work on implementing this change. My first step is a refactor + code quality PR for one of the involved components so that the PR that implements the desired change can be smaller in size/scope: #24015.

**Comment by ZebulanStanphill** [comment]
The PR mentioned in my previous comment has now been merged, so I've created #24066 to close this issue. :smile:
