### ISSUE TITLE
Table block: Row/Column selection color isn't from the WordPress palette. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8404]
**Describe the bug**

When you drag your mouse over a row or column in the table block, that row/column gets highlighted in `#2276d2`. This color appears to be from a TinyMCE stylesheet, and doesn't match any color I can find in Gutenberg or in the [WordPress color palette](https://make.wordpress.org/design/handbook/design-guide/foundations/colors/). 

![table-select](https://user-images.githubusercontent.com/1202812/43603101-fcd97416-965f-11e8-9968-1cf6f3f400a8.gif)

I'd suggest we swap that out for a tint of Medium Blue ([maybe the 40% or 60% version](https://codepen.io/hugobaeta/pen/RNOzoV)). This would likely improve the text contrast there as well.

**To reproduce**

1. Add a table block
2. Click and drag your mouse across a row or column
3. Take note of the highlight color.

**Comment by talldan** [comment]
I think this is no longer an issue since the table block rewrite because It doesn't seem possible to select multiple cells at all.

I'll probably repurpose this issue for adding that feature, and will make sure the selection color is correct.

**Comment by talldan** [comment]
Closing this in favour of #16294.
