### ISSUE TITLE
Column Block (beta): Adding a new block in the same column with Enter, doesn't maintain the block's style.

### ISSUE THREAD

**Issue by correliebre** [WordPress/gutenberg#8405]
**Describe the bug**
When adding a new block inside a column using the Enter key, the style of the text is lost. If you try command+Z to undo the action, it will leave the original block, and the new one. Both. 

**To Reproduce**
1. Go to a column inside a column block
2. Write some text and assign a specific style (in the example: Small size + Centered)
3. Go to the beginning of the text, and click enter.
4. The new empty block will be created, but the original one will lose it's text style.
5. Try command+Z to undo the action
6. You'll get two blocks, the original one, and the new one.

**Expected behavior**
The original block would keep it's format. When using command+Z to undo the action, the action would've gotten undone. 

**Screencast**
![gutenberg-1](https://user-images.githubusercontent.com/25516017/43603765-efe6fb6e-9661-11e8-8fad-9191d46f920e.gif)

**Desktop:**
 - OS: High Sierra 10.13.6
 - Browser: Firefox 
 - Version: 61.0.1

**Additional context**
- Gutenberg 3.4.0

**Comment by arunsathiya** [comment]
Noting that I am able to reproduce this behaviour on Gutenberg 4.0.0 as well. 

- [Video indicating that the original cell's formatting is lost](https://cloudup.com/coJVwZ9jIEw).
- [Video indicating that the formatting done is carried over to the newly created cell, just above the cell on which the formatting was done previously](https://cloudup.com/cQoynEe5KTw).

<img width="687" alt="screenshot 2018-10-18 at 19 26 28" src="https://user-images.githubusercontent.com/18581859/47159549-bcc61800-d30b-11e8-91a6-357746e902f1.png">
<sup>Image indicating that the formatting done is set to the new cell</sup> 

--- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 4.0.0 using Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) on macOS 10.14 - Mac OS Mojave

**Comment by jorgefilipecosta** [comment]
I'm able to reproduce this issue, it does not seem related to the columns block, it happens in paragraphs outside of the columns.

**Comment by youknowriad** [comment]
This seems fixed
