### ISSUE TITLE
Column Block (beta): Style menu from the block, makes it almost impossible to click on the + button to add a new block.

### ISSUE THREAD

**Issue by correliebre** [WordPress/gutenberg#8406]
**Describe the bug**
When adding a new block inside a column using the + button, it's almost impossible to click it. The text style menu of the block, overlaps with the + button.

**To Reproduce**
1. Go to a block inside a column block
2. Write some text in the block
3. Go to the + button to try and add a new block inside the same column
4. The style menu from the current block, will make it almost impossible to click the + button.

**Expected behavior**
The + button should be easy to click. The style menu from the current block, shouldn't be overlapping.

**Screencast**
![gutenberg-3](https://user-images.githubusercontent.com/25516017/43610069-458c710a-9673-11e8-8ae2-d6987d28f5d9.gif)

**Desktop:**
 - OS: High Sierra 10.13.6
 - Browser: Firefox 
 - Version: 61.0.1

**Additional context**
- Gutenberg 3.4.0

**Comment by mtias** [comment]
Thanks for the report. This seems to be working well for me in Chrome. If it still happens it should be related to #11559.

![image](https://user-images.githubusercontent.com/548849/48325476-8632a300-e614-11e8-8d0b-e2ad3c6e9006.png)
