### ISSUE TITLE
Cannot load blocks when the TinyMCE Table plugin is active

### ISSUE THREAD

**Issue by grafruessel** [WordPress/gutenberg#8407]
**Describe the bug**
When I'm editing my post in Gutenberg. I get an error:

An error has occurred in this block and a preview is not possible.

**To Reproduce**
1. Go to 'post'
2. Click on 'any'
3. Take any block inside gutenberg editor

**Expected behavior**
preview everything

**Screenshots**
![gutenberg-error](https://user-images.githubusercontent.com/30730935/43615403-cdcd293a-96b7-11e8-89e5-cd64377a21f4.JPG)

**Desktop (please complete the following information):**
 - Win 10 pro
 - chrome 68
 - Just updatest 2 newest

**Comment by designsimply** [comment]
The screenshot you included makes a reference to a `tinymce-plugin-lists.min.137fa94a.js` file. Is that from a plugin? If yes, and if you disable that plugin (and any plugin that relates to TinyMCE), does it solve the problem? It's possible the plugins are incompatible.

**Comment by designsimply** [comment]
Could we work together to make the title of this issue more descriptive? Once confirmed (based on the above comment) would something like this work?

> Cannot load blocks when the TinyMCE Table plugin is active

**Comment by grafruessel** [comment]
![wp-support-2](https://user-images.githubusercontent.com/30730935/43616502-1528dffe-96bd-11e8-9226-0a40bc79ce8f.JPG)

deactivated almost all plugins and deleted my cache... still the error...

**Comment by pento** [comment]
@grafruessel: Do you use Plesk? If so, there's an issue with their security settings that can cause this error. You can [find a workaround here](https://support.plesk.com/hc/en-us/articles/213925505-Unable-to-use-WordPress-plugin-403-Forbidden).

**Comment by grafruessel** [comment]
thanks... plesk it is.
