### ISSUE TITLE
Improve consistency of empty states for media blocks

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8409]
For the most part, the media blocks use pretty consistent empty states, but there are a few areas where they could be fine-tuned.

## Image
<img width="614" alt="screenshot 2018-07-30 13 54 15" src="https://user-images.githubusercontent.com/376315/43398566-5eaec130-9400-11e8-807a-e2d799874756.png">

## Cover image
<img width="642" alt="screen shot 2018-07-25 at 9 35 29 am" src="https://user-images.githubusercontent.com/1202812/43204120-180cfbae-8fee-11e8-98f1-d559dcc07684.png">

## Gallery
<img width="609" alt="screen shot 2018-07-30 at 2 38 31 pm" src="https://user-images.githubusercontent.com/1202812/43416672-f48fb528-9406-11e8-800c-ca2c5291c4bc.png">

## Video
<img width="619" alt="screenshot 2018-07-30 15 30 20" src="https://user-images.githubusercontent.com/376315/43405368-92d0189a-9411-11e8-9a05-8a1bfb74cd8a.png">

## Audio
<img width="617" alt="screenshot 2018-07-30 15 04 45" src="https://user-images.githubusercontent.com/376315/43402899-ab841ea0-940b-11e8-9fb5-f1231bd2b822.png">

## File
<img width="616" alt="screenshot 2018-07-30 14 30 41" src="https://user-images.githubusercontent.com/376315/43401128-42dbe2c4-9407-11e8-8996-4350040b9956.png">

## Suggestions

1. The "Use URL" option is great. Can we use it for all media blocks?

2. The copy is a bit jargony—not everyone understands URL. Can we make this a bit friendlier? Additionally, are there accessibility concerns with using a placeholder instead of a label here? Something along these lines, perhaps:
<img width="664" alt="screenshot 2018-08-03 00 25 11" src="https://user-images.githubusercontent.com/376315/43616299-c46e05f2-96b3-11e8-9246-cedaa355f79b.png">

3. "Upload" is very desktop-centric. Could we use "add" instead?

4. Can we improve the format of this sentence, used across all blocks here? "Drag an audio, upload a new one or select a file from your library." There are actually four options for [most] blocks: link, upload, drag, and select from library, but the first three are more or less the same effect. Perhaps instead "Add a new [whatever] file or select a file from your library."?

**Comment by michelleweber** [comment]
+1 for changing "Drag an audio, upload a new one or select a file from your library." I'd still specify all the options, though to be super clear. I'm thinking something like:

> Add a new file to your media library -- you can drag and drop it here, or click "Add" to select one -- or choose a file you've already added.

> Add a new file to your media library -- you can drag and drop it here, or click "Add" to select one -- choose a file you've already added, or insert a link to the file.

On the "upload" point -- am I not still uploading a file to my site when I add it via the app? It wouldn't occur to me that this work is desktop-specific, so I would love to understand more. And does the "drag a file" instruction have the same problem re: desktop-centricness? Does mobile actually need a whole other set of copy?

**Comment by kjellr** [comment]
> Add a new file to your media library -- you can drag and drop it here, or click "Add" to select one -- or choose a file you've already added.

This is getting a little too long for my taste, and it's missing the URL option... I wonder if we can keep it light, and let the buttons/fields speak for themselves?

![artboard](https://user-images.githubusercontent.com/1202812/43655012-4c356b80-971b-11e8-9b39-d3526de64630.png)

> On the "upload" point -- am I not still uploading a file to my site when I add it via the app? It wouldn't occur to me that this work is desktop-specific, so I would love to understand more.

Yeah, I think upload is fine here. Even on mobile, you're uploading. 

> does the "drag a file" instruction have the same problem re: desktop-centricness? Does mobile actually need a whole other set of copy?

This _does_ feel a little desktop-centric. Swapping out the copy on mobile might be a good route to take.

**Comment by michelleweber** [comment]
It looked like some blocks include the URL and some don't, so there are two versions. That said, yeah, it is longer. We can go with Sarah's "Add a new X file here, or pick one from your media library."

**Comment by kjellr** [comment]
> It looked like some blocks include the URL and some don't, so there are two versions.

Ah, sorry — I somehow missed that second version. 

> We can go with Sarah's "Add a new X file here, or pick one from your media library."

Sounds good to me. 👍

**Comment by kjellr** [comment]
Hey folks! Just want to confirm the phrasing here. Most of these have URL options, and I think it's getting little wordy: 

![gutenberg test_wp-admin_post php_post=1 action=edit (1)](https://user-images.githubusercontent.com/1202812/59369754-ef3ae000-8cf5-11e9-9944-3c8aff5e2601.png)

cc @michelleweber

**Comment by michelleweber** [comment]
I'd delete the "here" to save a few characters. Seeing it now, it's not needed. "Pick one from your media library" could also be "browse your media library."
