### ISSUE TITLE
Try Gutenberg results in a 500 Server Internal Error

### ISSUE THREAD

**Issue by jaz3** [WordPress/gutenberg#8410]
Try Gutenberg results in a 500 Server Internal Error

1. Install Gutenberg plugin
2. Activate Gutenberg plugin
3. Click on Try Gutenberg
4. Results in 500 Server Internal Error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by pento** [comment]
Thank you for the bug report, @jaz3!

As this is a WordPress Core issue, I've moved it over to the [WordPress issue tracker](https://core.trac.wordpress.org/ticket/44711). I'll close this issue to continue it over there.

If you have a WordPress.org account, could you post over on the new issue any extra information you have?

In particular:

- When you install a plugin, do you usually need to type your FTP username/password (or do you have `FTP_*` settings in your `wp-config.php` file)?
- Do you have access to your web server error log? If so, could you attach a copy of it?

**Comment by leninnair** [comment]
I have the same issue. I updated to Gutenberg Version 3.8.0 . WordPress 4.9.8 running hestia theme. I have also yoast SEO plugin. Whenever I try to edit an existing post, it results in internal server error 500. When I disable Gutenberg, it all functions perfectly. Disabling yoast doesn't help.

**Comment by designsimply** [comment]
@leninnair I see that the original issue reported here is about the "Try Gutenberg" button and your issue is about trying to edit an existing post. Since those are different, opening a separate issue is the right thing and I see that you have done that at #9983. Thank you for testing Gutenberg and continue the discussion there!
