### ISSUE TITLE
"Updating failed" error and error log "ModSecurity: JSON support was not enabled"

### ISSUE THREAD

**Issue by thejoydutta** [WordPress/gutenberg#8413]
After installing new code editor in WordPress it shows updating error from every update I do like Post draft or any updation

**Comment by pento** [comment]
Sorry to hear that, @thejoydutta.

Do you use CloudFlare on your site, our do you have any WordPress security plugins installed?

**Comment by kalich5** [comment]
I have same problém!

**Comment by pento** [comment]
@kalich5: Do you use CloudFlare, or a WordPress security plugin that disables the REST API?

**Comment by kalich5** [comment]
No, clean installation.

**Comment by kalich5** [comment]
Can not the problem be in PHP?
I've tried all the options we have on the server ...
Here is the setting:
7.2 https://php72.skauting.cz/
7.1 https://php71.skauting.cz/
7.0 https://php70.skauting.cz/
5.6 https://php56.skauting.cz/

**Comment by kalich5** [comment]
Or is there a need for something new on the server? Compared to old WP versions?

**Comment by pento** [comment]
There's no need for anything new on the server, it should work with any version and configuration of PHP that WordPress currently works with.

Do you have anything in your web server error logs?

Do you see any errors in your browser's Developer Tools console or Network info?

**Comment by kalich5** [comment]
[Fri Aug 03 09:22:56.158622 2018] [:error] [pid 7877:tid 140662142297856] [client 95.80.198.175:61390] [client 95.80.198.175] ModSecurity: JSON support was not enabled [hostname "skautis-testlogin.skauting.cz"] [uri "/wp-json/wp/v2/posts/1214/autosaves"] [unique_id "W2QC0JxKabqj7ARCybJoLQAAAAQ"], referer: https://skautis-testlogin.skauting.cz/wp-admin/post.php?post=1214&action=edit

**Comment by pento** [comment]
Cool, thank you for the extra information!

This is caused by an old version of `mod_security` being installed on your server. If you compiled `mod_security` yourself, you'll need to install YAJL recompile it with the `--with-yajl` option.

If you're using your OS's version of `mod_security`, you may need to upgrade your OS. For example, it seems like Debian 8 and older will get this error message.

**Comment by thejoydutta** [comment]
@pento yes, I use cloudflare

**Comment by pento** [comment]
Thank you for the info, @thejoydutta.

Cloudflare is blocking REST API requests: they're testing a fix which they currently intend to deploy Monday next week. Please follow #2704 for updates.
