### ISSUE TITLE
Multiple editor width

### ISSUE THREAD

**Issue by ThomasFx** [WordPress/gutenberg#8420]
How to define width of editor? But different for post, page (product), custom page template etc...

**Comment by youknowriad** [comment]
You can probably enqueue a stylesheet that tweaks the editor width See https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor

If you want to make different per post type, there's a body class per post type, you can rely on For instance `.post-type-post` for posts.

**Comment by designsimply** [comment]
I posted an explanation of the current situation and a workaround code example at #12874 (comment). Please have a look!
