### ISSUE TITLE
Editor: Stop exposing internal components starting with underscore

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#8421]
We iniitally exposed `wp.editor._BlockSettingsMenuFirstItem` in #7199:

https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/index.js#L87

#7895 is going to introduce another component which follows the same approach.

We should refactor code to stop exposing components that are not meant for public consumption.

**Comment by gziolo** [comment]
@aduth @youknowriad any ideas on how to attack it? Can we move those slots to `edit-post` and inject to `BlockSettingsMenu` similar to what we do with publish panels?

**Comment by aduth** [comment]
The introduction in #7199 was a bit of a judgment call and in some ways a stop-gap solution to provide some level of prioritization to menu items. If we want to surface priority: We should do so. If we don't: Then `_` prefixing is fine ([see also mention of precedent](https://github.com/WordPress/gutenberg/pull/7199#issuecomment-396271783)).

**Comment by gziolo** [comment]
@aduth, it seems like we should rename them to begin with `__Unstable*`, what do you think?

**Comment by aduth** [comment]
Yes, I recall mentioning it recently as well in some pull request. I think it would be a good idea.

**Comment by gziolo** [comment]
When reviewing https://github.com/WordPress/gutenberg/pull/15195 I discovered that those components listed in this issue are marked now as experimental. We can close this issue now.
