### ISSUE TITLE
Add option to edit HTML of full page 

### ISSUE THREAD

**Issue by xaviarnl** [WordPress/gutenberg#8422]
At the moment, you can only edit the HTML code of blocks of content (text, image, and the like). However, there is no option/button to switch to the HTML code of the full page: you have to go through each block one by one. As I use quite a lot of custom CSS classes in my page contents, I find this rather cumbersome.

**Comment by pento** [comment]
Thank you for contacting us, @xaviarnl!

You can find the option to edit all of the HTML in the menu at the top right, by clicking on "Code Editor".

![](https://user-images.githubusercontent.com/31212934/43632165-c83e154e-971e-11e8-926e-29d51bef3823.png)

For adding CSS classes, you can find an "Additional CSS classes" box under the Advanced tab of the Block Option sidebar.
