### ISSUE TITLE
SelectControl don't support options attributes and optgroups

### ISSUE THREAD

**Issue by ghost** [WordPress/gutenberg#8426]
**Describe the bug**
[SelectControl](https://github.com/WordPress/gutenberg/tree/master/packages/components/src/select-control) lack support for options attributes ( disabled namely ) and there is no support for optgroup.

**Expected behavior**
Ability to pass into component options disabled attribute and be able to add options in optgroups.

**Additional context**
- You can read about option tag here: https://www.w3schools.com/tags/tag_option.asp
- Here is a link for optgroup tag: https://www.w3schools.com/tags/tag_optgroup.asp

Terrible job so far, keep it up! And for love of god start working on proper documentation for this monster.

**Comment by paaljoachim** [comment]
Is this issue still relevant?
If so how can we move in onward?

**Comment by Ugoku** [comment]
Yes, this is still relevant! Please see https://github.com/WordPress/gutenberg/issues/17032 as well

**Comment by paaljoachim** [comment]
Thank you for the feedback!

Pinging:
@WordPress/gutenberg-core

**Comment by tellthemachines** [comment]
It's already possible to add attributes such as `disabled` to the underlying `select` element in `SelectControl`. See [this section](https://github.com/WordPress/gutenberg/blob/master/packages/components/src/select-control/README.md#L124) of the readme for details.

As the only remaining item to address is optgroups, I'm closing this issue in favour of #17032.
