### ISSUE TITLE
Text show outside of editor box

### ISSUE THREAD

**Issue by rvpatel** [WordPress/gutenberg#8428]
**Describe the bug**
when you have used a Drop Cap text show on backed outside of editor.

**Screenshots**
http://easycaptures.com/fs/uploaded/1215/6111088468.png
http://easycaptures.com/fs/uploaded/1215/2927840798.png

**Desktop (please complete the following information):**
 - OS: window7
 - Browser : Firefox - 61.0.1

**Comment by youknowriad** [comment]
Let's consolidate all "Drop cap" floating issues on #8447 

Closing as a duplicate
