### ISSUE TITLE
Can't use the featured image in the side bar anymore.

### ISSUE THREAD

**Issue by PriscaVisser** [WordPress/gutenberg#8430]

**Comment by youknowriad** [comment]
<img width="282" alt="screen shot 2018-08-03 at 11 48 53" src="https://user-images.githubusercontent.com/272444/43639162-39f0873c-9713-11e8-9601-7501ab68c4a2.png">

The featured image panel is there? Any particular information/detail about your setup? Any errors in the console?

**Comment by PriscaVisser** [comment]
![screenshot](https://user-images.githubusercontent.com/42064146/43639535-df849a90-971c-11e8-8391-f1ed8ca5b080.png)

It's gone by me. No errors, it just disappeard.

**Comment by youknowriad** [comment]
Gotcha, do you seen any javascript error in the console?
Which browser are you using?

Thanks

**Comment by PriscaVisser** [comment]
I'm using Google Chrome. Can't find any errors in Javascript.

**Comment by PriscaVisser** [comment]
In older blogposts i can't change or remove the featured image. I can see it though. Maybe that's some extra info that will help.

**Comment by PriscaVisser** [comment]
And... it's not possible to drag and drop photo's from the gallery into a block. Only 'upload' is possible. Maybe the problem is my theme in combi with Gutenberg?

**Comment by swissspidy** [comment]
Are there any errors in the browser console (open via F12 key)

**Comment by PriscaVisser** [comment]
![screenshot2](https://user-images.githubusercontent.com/42064146/43641032-6799a31c-9722-11e8-81ba-d73d29434285.png)

**Comment by PriscaVisser** [comment]
That's all i can find..

**Comment by youknowriad** [comment]
I think it's related to the REST API somehow. 

 - Try enabling permalinks (or updating them)
 - Do you use CloudFlare?
 - Do you disable REST API endpoints? or use plugins that tweak them?

**Comment by PriscaVisser** [comment]
- Done
- No
- No, i'm not sure, how can i check this? / No, i've deactive one for one. Not a single change.

This drives me crazy.. I love the design Gutenberg very much but it has to work. :-)

**Comment by youknowriad** [comment]
Can you try to check the "network" tab (filter to see only XHR requests) in the console. And do:

 - Close The sidebar
 - Refresh the page
 - Go to the network tab in the console
 - Open the sidebar
 - Check the response of the triggered XHR requests. Any failing request? 

Thanks for your help debugging this, it's very hard for us to fix something if we can't reproduce it.

**Comment by PriscaVisser** [comment]
![screenshot3](https://user-images.githubusercontent.com/42064146/43642751-14b56fb2-9729-11e8-9332-29d3090cb0bd.png)

I think everything is normal? I've an other site, other theme. Tryed Gutenberg and got the same problems.

**Comment by stnsvn-mike** [comment]
This is a theme related issue (Coastal theme) using an outdated version of ACF Pro. Updating to the latest version of the theme resolves the issue (v2.3.3) :)

**Comment by designsimply** [comment]
I've closed this issue based on the latest reply noting upgrading the Coastal theme to v2.3.3 resolves the problem. @PriscaVisser, if you are using a different theme please reply here to note your theme name and version.

**Comment by PriscaVisser** [comment]
Yes, thanx a lot to the team from Station Seven (@stnsvn-mike. The update workes fine, i'm one happy girl! Thank youy all for reacting.

**Comment by Satheeshraj1** [comment]
I'm using Newspaper theme V 9.1.2. Feature Image tab is not showing in the classic editor
