### ISSUE TITLE
Hide Gutenberg Promotion when Gutenberg is already installed

### ISSUE THREAD

**Issue by SNaushadS** [WordPress/gutenberg#8431]
**Is your feature request related to a problem? Please describe.**
After updating to WordPress 4.9.8, i got the banner as below. This isn't a deal-breaker as such. But it would be good if i don't get to see this promotion when i already have Gutenberg plugin installed.

<img width="1232" alt="gutenberg-promotion" src="https://user-images.githubusercontent.com/1532907/43639647-8a534774-973a-11e8-87ed-d9ad0e17b80c.png">

**Describe the solution you'd like**
A basic check to have this banner not shown if the plugin is already installed. 

**Describe alternatives you've considered**
- No alternatives that i can think of. I am also not certain if this should be a feature request.
- Additionally, we may ignore it for now as the number of users impacted is less (number of installs)

**Comment by youknowriad** [comment]
I think this issue is probably better in Core because the callout is in Core Trac https://core.trac.wordpress.org/ (The callout code lives there) but I think the idea is that a user can have installed the plugin while another user of the same site didn't know about it. So we keep the callout for these users, so when you have Gutenberg installed, it invites you to test it and not install it.

**Comment by SNaushadS** [comment]
Core Trac, I can create it there if need be.
_Other user now knowing about the plugin already installed ?_
I am not certain if this scenario is valid, because if User A has already installed the plugin all subsequent users will see the Post creation in the new Gutenberg Layout (My assumption).

**Comment by swissspidy** [comment]
> I am not certain if this scenario is valid, because if User A has already installed the plugin all subsequent users will see the Post creation in the new Gutenberg Layout (My assumption).

Yes, they will. And they will be like "What is going on?!".

That's why there is a callout to say "Hey, we added something new. Learn more about what this means »".

**Comment by youknowriad** [comment]
I think we still want to keep the behavior as is for now, so I'm closing for now. Thanks for the suggestion.
