### ISSUE TITLE
Update link references on WordPress.org

### ISSUE THREAD

**Issue by Clorith** [WordPress/gutenberg#8432]
I couldn't find the readme for WordPress.org anywhere on here, so a ticket will do :)

There's currently a link to the FAQ, but it references a github file where the link is wrong (ends in a 404 page). It's currently pointing to `https://github.com/WordPress/gutenberg/blob/master/docs/faq.md`, when it should probably point to `https://wordpress.org/gutenberg/handbook/reference/faq/` now.
This same link is also referenced in the FAQ section of the readme.

There's a link to `http://gutenberg-devdoc.surge.sh/`, which is now a redirect to the Gutenberg handbook at `https://wordpress.org/gutenberg/handbook/`, we can probably make this direct link.

There's a link to `http://gutenberg-devdoc.surge.sh/reference/design-principles/`, which also redirects to a handbook subpage at `https://wordpress.org/gutenberg/handbook/reference/design-principles/` that could be a direct link.

**Comment by youknowriad** [comment]
I fixed the links but not sure when the plugins page will reflect those changes.

**Comment by Clorith** [comment]
It needs to be updated in readme file in the stable tag as well, only the stable tag is grabbed form the readme in trunk :)

**Comment by youknowriad** [comment]
I guess this means it will be updated once we release the next Gutenberg version which won't last too much. Maybe we can close this issue now?

**Comment by Clorith** [comment]
Oh, you can retroactively update the readme at any time without pushing a new version, so feel free to just do a svn copy of the readme :)

**Comment by youknowriad** [comment]
We have a guide to follow when doing releases and I don't want to update a file in the tags folder. I'll leave it for the others with more experience handling plugins. (In git Tags are immutable and I expect them to be the same in SVN, or use them as is even if it's not really the case).

**Comment by ajitbohra** [comment]
Do we have any actionable item here? or good to close this!

**Comment by youknowriad** [comment]
Probably fine to close, it was just waiting for a plugin release at some point.
