### ISSUE TITLE
Picture in the text

### ISSUE THREAD

**Issue by jucunda** [WordPress/gutenberg#8434]
Where can I set the text wrapping around pictures?

**Comment by jucunda** [comment]
I can not find the buttons to the left or
To adjust the rightfulness

**Comment by youknowriad** [comment]
When you insert an image block, notice that there are alignment options when you select the image. You can choose, left, right. And this will make sure the text after the image will wrap. (float alignments)

<img width="642" alt="screen shot 2018-08-03 at 12 57 19" src="https://user-images.githubusercontent.com/272444/43641817-f811a6fc-971c-11e8-8d5e-edeb8d597fde.png">

(Notice the buttons on the trop left of the selected block)

I hope this helps.

**Comment by jucunda** [comment]
This function should also be on the inline picture. It is without function on the picture blog

 

Von: Riad Benguella <notifications@github.com> 
Gesendet: Freitag, 3. August 2018 14:01
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: jucunda <redaktion@jucunda-juechen.de>; Author <author@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] Picture in the text (#8434)

 

When you insert an image block, notice that there are alignment options when you select the image. You can choose, left, right. And this will make sure the text after the image will wrap. (float alignments)

 <https://user-images.githubusercontent.com/272444/43641817-f811a6fc-971c-11e8-8d5e-edeb8d597fde.png> 

(Notice the buttons on the trop left of the selected block)

I hope this helps.

**Comment by youknowriad** [comment]
> This function should also be on the inline picture. It is without function on the picture blog

The "inline image" is by definition "inline" so you can't float "inline" elements.

**Comment by jucunda** [comment]
I cant find it

 

Von: Riad Benguella <notifications@github.com> 
Gesendet: Freitag, 3. August 2018 17:07
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: jucunda <redaktion@jucunda-juechen.de>; Author <author@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] Picture in the text (#8434)

 

This function should also be on the inline picture. It is without function on the picture blog

The "inline image" is by definition "inline" so you can't float "inline" elements.

**Comment by youknowriad** [comment]
What I'm saying is that if you want the "wrapping" feature, you should not use the "inline image" because these are "inline" in the text, the text won't wrap those images.

you need to use the separate "image" block for that. Click the inserter and search for "Image" block.

**Comment by jucunda** [comment]
On. It isnt. Take a look to the Screenshot.

 

Von: Riad Benguella <notifications@github.com> 
Gesendet: Freitag, 3. August 2018 17:07
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: jucunda <redaktion@jucunda-juechen.de>; Author <author@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] Picture in the text (#8434)

 

This function should also be on the inline picture. It is without function on the picture blog

The "inline image" is by definition "inline" so you can't float "inline" elements.

**Comment by jucunda** [comment]
What do I have to do to wrap the pictures? So far, I just had to put them in the text

 

Von: Riad Benguella <notifications@github.com> 
Gesendet: Freitag, 3. August 2018 17:14
An: WordPress/gutenberg <gutenberg@noreply.github.com>
Cc: jucunda <redaktion@jucunda-juechen.de>; Author <author@noreply.github.com>
Betreff: Re: [WordPress/gutenberg] Picture in the text (#8434)

 

What I'm saying is that if you want the "wrapping" feature, you should not use the "inline image" because these are "inline" in the text, the text won't wrap those images.

you need to use the separate "image" block for that. Click the inserter and search for "Image" block.

**Comment by youknowriad** [comment]
I can't see the screenshot. Can you upload it to the GitHub issue, instead of replying in your email?

**Comment by jucunda** [comment]
![zwischenablage01](https://user-images.githubusercontent.com/42065490/43651246-2274cddc-9742-11e8-9036-0b3bab16a68c.jpg)

**Comment by youknowriad** [comment]
See the GIF, it shows how you wrap images.

![wrap](https://user-images.githubusercontent.com/272444/43651257-c8756416-9739-11e8-903d-86b76ab8df3c.gif)


Also, I noticed in your screenshot that you're trying to write everything in a single block. That's not how Gutenberg works, in Gutenberg each paragraph should be a separate block, if you want to keep writing this way you can use the "Classic" block for that, but you'll have more options/possibilities if you use granular blocks.

**Comment by jucunda** [comment]
Thank You. 
Now i know

**Comment by youknowriad** [comment]
You're welcome, Glad it helped.
