### ISSUE TITLE
Problem customizing menu with js

### ISSUE THREAD

**Issue by tuvelijn** [WordPress/gutenberg#8437]
In plugins map I have this code to add a button to the menu:

(function () {
    tinymce.PluginManager.add('noten_oplichten_tc_button', function (editor, url) {
        editor.addButton('noten_oplichten_tc_button', {
            text: 'Noot toevoegen',
            icon: false,
            onclick: function () {
                tinymce.activeEditor.execCommand('mceInsertContent', false, "<span class=\"editor_noot\">[ref][/ref]</span> ");
            }
        });
    });
})();

How will you provide this functionality in the gutenberg version? It's part of a system voor entering notes in my blog and I must have this facility also in the gutenberg version.

**Comment by youknowriad** [comment]
I think I saw a "note block" that is removed from the frontend and only appears as "notes" in Gutenberg. You can try to build a block for that, or you can try the "inline blocks". Check the handbook https://wordpress.org/gutenberg/handbook/ for more details about Gutenberg Extensibility. 

cc @iseulde for inline block APIs
