### ISSUE TITLE
Restricted Content Area Won't Work (plus weird formatting)

### ISSUE THREAD

**Issue by KendallRogersD1** [WordPress/gutenberg#8442]
**Describe the bug**
We have two subscription options we always put in the restricted content area -- and in the gutenberg style, when we try to find/type to find them, they don't show up. Plus, there's some odd formatting in that box.

**Expected behavior**
When you start to type "premium" or "annual" or "monthly" in the restricted content area, should show up as options. They don't in the new admin style.

**Screenshots**
<img width="298" alt="screen shot 2018-08-03 at 8 34 22 am" src="https://user-images.githubusercontent.com/42068351/43645632-221dadee-96f8-11e8-8e6d-adc61fac050a.png">

**Comment by youknowriad** [comment]
Is this "Restrict Content" panel a metabox coming from a plugin? Can you try reaching out to the plugin authors to see if they can add Gutenberg support for their plugins? Based on the screenshots, It looks like a CSS issue.

**Comment by designsimply** [comment]
Closing this because a suggestion was made to reach out to the plugin author. If you are still having trouble and would also like to continue the discussion here, please reply with more information about the plugin which adds the "Restrict Content" panel.
