### ISSUE TITLE
Author Option Box

### ISSUE THREAD

**Issue by fantasysixpack** [WordPress/gutenberg#8443]
I run a blog with 12-15 writers at any given time and I sometimes have to change who the author is. I do this currently by using the drop-down box called 'Authors'. 

I can't seem to find this in the new editor. How do I do this now?

**Comment by SuperGeniusZeb** [comment]
I see the Authors dropdown on my site:

![image](https://user-images.githubusercontent.com/19592990/43646115-98aa7c02-96f9-11e8-943f-c7f9ee221c96.png)

What do you see? Could you provide a screenshot?

**Comment by fantasysixpack** [comment]
On mine that option is missing. I'm logged in as the super admin too.

![image](https://user-images.githubusercontent.com/42068349/43647235-08d30aca-9705-11e8-835f-3191c81395f1.png)

**Comment by youknowriad** [comment]
@fantasysixpack Do you see any error in the Console? Any failing Network request? 

Can you try to enable/update permalinks? This is most likely a REST API issue.

**Comment by fantasysixpack** [comment]
I turned on the chrome debugger and now the author box appears everytime I enter the post. It is a bit delayed, but it does work.

I guess this is a non-issue now. 

Thanks for the replies.
