### ISSUE TITLE
hierarchical-term-selector not using modified `add_new_item` label

### ISSUE THREAD

**Issue by krisgale** [WordPress/gutenberg#8448]
**the bug**

Categories meta box not respecting changes made via `taxonomy_labels_category`, "Add new category" always used

**to reproduce**

implement `taxonomy_labels_category` and change default labeling for `category` taxonomy, go to edit a post, see "Add new category" shown in gutenberg-i-fied Categories meta box.

**expected behavior**

for "Add new category" label to use `add_new_item` label property in modified `category` taxonomy

![image](https://user-images.githubusercontent.com/1486351/43649057-1d460c6e-970a-11e8-8a98-e70bef5d1219.png)

**Comment by krisgale** [comment]
that's correct, but i feel this logic is not:

https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-taxonomies/hierarchical-term-selector.js#L251

my specific use case was to re-label the built-in 'category' taxonomy, and saw the above-screencapped end result.

**Comment by youknowriad** [comment]
In theory, this code gives priority to the labels specified in the `register_taxonomy` call. This logic is just a fallback in case there's no defined label. Is this your case?

**Comment by krisgale** [comment]
i definitely had set both `new_item_name` and `add_new_item` in a hook for `taxonomy_labels_{$taxonomy}` (`taxonomy_labels_category`) when i captured the above image...

**Comment by youknowriad** [comment]
I'm reopening to investigate more, thanks

**Comment by krisgale** [comment]
@youknowriad is labelWithFallback necessary? does WP not set/provide defaults for taxonomy labels?

**Comment by youknowriad** [comment]
@krisgale Some custom taxonomies don't provide labels.

**Comment by krisgale** [comment]
@youknowriad which is why wordpress sets defaults for all labels
https://github.com/WordPress/WordPress/blob/master/wp-includes/taxonomy.php#L548

**Comment by youknowriad** [comment]
Good observation, Maybe it's useless than :), we'll have to check if the REST API sends these fallback labels (even if unchanged). Feel free to PR it

**Comment by fienen** [comment]
Adding this case to this issue, as I think it's probably an instance of the same basic issue. Noticed today custom taxonomies are using the generic "term" verbiage for all the various labels instead of the specific singular/plural labels set in the taxonomy arguments. This problem doesn't exist with the classic editor. Case in point, everything uses "speaker"/"speakers" when it's set to the classic editor.
![capture](https://user-images.githubusercontent.com/784502/44605404-d38a3b80-a7ae-11e8-8006-fd659b33ffda.JPG)

**Comment by macemmek** [comment]
I confirm the above, I'd also expect the editor to utilize 'add_new_item' and other labels registered with a custom taxonomy.

**Comment by youknowriad** [comment]
cc @jorgefilipecosta in case you have more context here.

**Comment by krisgale** [comment]
did a fresh install of wp and guten on a vm today and i plan to make some time tomorrow / this weekend to fork g7g to see if removing the duplication of labels in js results in the desired behavior (only using data provided by wp’s rest api)
