### ISSUE TITLE
New Post is blank with only the top and left WordPress menus available

### ISSUE THREAD

**Issue by RookieRaceline** [WordPress/gutenberg#8455]
**Describe the bug**
I got the promt to install gutenberg on the dashboard, but when i click on try Gutenberg, it goes to New Post, but the page is blank (only side panel of wordpress is visible)
The New Post feature simply does not work any more

Gutenberg is installed and activated in the plugins, but on the dashboard it still says "Try Gutenberg"

I am using this on Desctop, Gutenberg  3.4.0

![screenshot_2018-08-03 add new post rookie raceline wordpress](https://user-images.githubusercontent.com/42073517/43656082-6eeee4d6-9751-11e8-8c5d-359d2dd1827b.png)

**Comment by ellenloehman** [comment]
Me, too. Website newmexicotrout.org.

Probably an old version of php. I will try to get the system info.

**Comment by ellenloehman** [comment]
// Generated by the Send System Info Plugin //

Multisite:                No

SITE_URL:                 http://www.newmexicotrout.org
HOME_URL:                 http://www.newmexicotrout.org

WordPress Version:        4.9.8
Permalink Structure:      /%postname%/
Active Theme:             Accelerate Pro 2.2.1

Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed, archive, spam

Platform:                 Apple 
Browser Name:             Safari  
Browser Version:          11.1.2 
User Agent String:        Mozilla/5.0 (Macintosh; Intel Ma 
			  c OS X 10_11_6) AppleWebKit/605.
                          1.15 (KHTML, like Gecko) Version
                          /11.1.2 Safari/605.1.15
                          
PHP Version:              5.4.45-pl0-gentoo
MySQL Version:            5.0.84-log
Web Server Info:          Apache

WordPress Memory Limit:   40MB
PHP Safe Mode:            No
PHP Memory Limit:         256M
PHP Upload Max Size:      50M
PHP Post Max Size:        50M
PHP Upload Max Filesize:  50M
PHP Time Limit:           60
PHP Max Input Vars:       2000
PHP Arg Separator:        &
PHP Allow URL File Open:  Yes
WP_DEBUG:                 Disabled

WP Table Prefix:          Length: 7 Status: Acceptable

Show On Front:            page
Page On Front:             (#4)
Page For Posts:           Blog (#2430)

WP Remote Post:           wp_remote_post() works

Session:                  Disabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:                /tmp
Use Cookies:              On
Use Only Cookies:         On

DISPLAY ERRORS:           N/A
FSOCKOPEN:                Your server supports fsockopen.
cURL:                     Your server supports cURL.
SOAP Client:              Your server has the SOAP Client enabled.
SUHOSIN:                  Your server does not have SUHOSIN installed.

ACTIVE PLUGINS:

AdRotate: 4.13
Akismet Anti-Spam: 4.0.8
Archived Post Status: 0.3.7
Broken Link Checker: 1.11.5
Content Views: 2.0.2
Content Views Pro: 5.3.3.1
Gravity Forms: 2.3.3
Gravity Forms Coupons Add-On: 2.6
Gravity Forms PayPal Standard Add-On: 3.1
Gravity Forms Toolbar: 1.7.0
Gravity Forms User Registration Add-On: 3.9
Gutenberg: 3.4.0
iThemes Security: 7.0.4
Jetpack by WordPress.com: 6.3.3
Login With Ajax: 3.1.7
menu shortcode: 1.0
Page Builder by SiteOrigin: 2.7.3
Send System Info: 1.3
Simple Calendar: 3.1.19
SiteOrigin Widgets Bundle: 1.12.1
UpdraftPlus - Backup/Restore: 1.14.12
WP-Sweep: 1.0.12
WP Facebook Auto Publish: 1.4.9

**Comment by weindler** [comment]
Hello, i have the same issue. I cleaned the cache of chrome but this don´t help to resolve the issue. i deactivated the plugin then it´s all right.
I hope you can find the issue.

**Comment by youknowriad** [comment]
So this could happen for several reasons:

 - Do you see any errors in the JavaScript console of your browser?
 - Do you see any failing XHR requests in the console?

It can also happen without any of those and in that case, we may have found the issue here https://meta.trac.wordpress.org/changeset/7593 (sometimes refreshing the page fix it). Hopefully, we'll land a fix soon.

**Comment by mlopezcoria** [comment]
I have the same problem. I also have troubles with permalinks. I use post names but it doesn't work.

**Comment by diver864** [comment]
I am having same issue as original post.  Install the Gutenberg plugin and then try to create a new post, but I only see the WP Admin sidebar and top bar.

                // Generated by the Send System Info Plugin //

Multisite:                No

SITE_URL:                 http://test.catalyzeit.net
HOME_URL:                 http://test.catalyzeit.net

WordPress Version:        4.9.8
Permalink Structure:      /%year%/%monthnum%/%day%/%postname%/
Active Theme:             Twenty Seventeen 1.7

Registered Post Stati:    publish, future, draft, pending, private, trash, auto-draft, inherit, request-pending, request-confirmed, request-failed, request-completed

Platform:                 Windows 
Browser Name:             Chrome  
Browser Version:          67.0.3396.99 
User Agent String:        Mozilla/5.0 (Windows NT 6.1) App 
			  leWebKit/537.36 (KHTML, like Gec
                          ko) Chrome/67.0.3396.99 Safari/5
                          37.36
                          
PHP Version:              5.4.45
MySQL Version:            5.6.40-84.0-log
Web Server Info:          Apache

WordPress Memory Limit:   40MB
PHP Safe Mode:            No
PHP Memory Limit:         768M
PHP Upload Max Size:      128M
PHP Post Max Size:        128M
PHP Upload Max Filesize:  128M
PHP Time Limit:           120
PHP Max Input Vars:       3000
PHP Arg Separator:        &
PHP Allow URL File Open:  Yes
WP_DEBUG:                 Disabled

WP Table Prefix:          Length: 4 Status: Acceptable

Show On Front:            posts
Page On Front:             (#0)
Page For Posts:            (#0)

WP Remote Post:           wp_remote_post() works

Session:                  Disabled
Session Name:             PHPSESSID
Cookie Path:              /
Save Path:                /tmp
Use Cookies:              On
Use Only Cookies:         Off

DISPLAY ERRORS:           On (1)
FSOCKOPEN:                Your server supports fsockopen.
cURL:                     Your server supports cURL.
SOAP Client:              Your server has the SOAP Client enabled.
SUHOSIN:                  Your server does not have SUHOSIN installed.

ACTIVE PLUGINS:

Better Search Replace: 1.3.2
Gutenberg: 3.4.0
Send System Info: 1.3

**Comment by designsimply** [comment]
I see this has a fix in place and I am just looping back to add a screenshot including a console error for reference in case it's helpful for others searching for this issue before they have updated to 3.5:

> TypeError: undefined is not an object (evaluating '$( '#publishing-action #publish' ).val().toLowerCase')
> post-new.php:3315

![screen shot 2018-08-06 at mon aug 6 1 33 30 pm](https://user-images.githubusercontent.com/1119271/43738062-a4faa412-9980-11e8-9657-55518385832a.png)
<sup>Seen at https://cute.wordpress.com/wp-admin/post-new.php running Gutenberg 3.2 on WordPress.com using Safari 11.1.2 on macOS 10.13.6.</sup>

**Comment by youknowriad** [comment]
@designsimply That javascript error looks like a plugin conflict error, independent from the fix in the PR related to this PR.

**Comment by designsimply** [comment]
@youknowriad thanks for the update. I wasn't sure if it was related!
