### ISSUE TITLE
Youtube Block cuts off URL paramters

### ISSUE THREAD

**Issue by aloppnow** [WordPress/gutenberg#8458]
Added the YT Block and pasted Video URL: 
https://www.youtube.com/watch?v=JJr0lNDJ1Vc&modestbranding=1&autohide=1&showinfo=0&controls=0

Frontend embedded iframe has this URL 
src="https://www.youtube.com/embed/JJr0lNDJ1Vc?feature=oembed&enablejsapi=1&origin=https%3A%2F%2Fwww.safeconnectsystems.com"

**Comment by designsimply** [comment]
Thank you for posting your feedback! This is an oEmbed issue which is not specific to Gutenberg. 

For reference, here are screenshots showing a similar outcome without using Gutenberg:

![screen shot 2018-08-03 at fri aug 3 4 49 46 pm](https://user-images.githubusercontent.com/1119271/43669290-2152261e-973f-11e8-83b2-fd442cb06cb5.png)

![screen shot 2018-08-03 at fri aug 3 5 01 18 pm](https://user-images.githubusercontent.com/1119271/43669291-22a46720-973f-11e8-9cbe-11bb671d18f5.png)

I searched https://core.trac.wordpress.org/ and found a similar issue asking about YouTube parameters (more specifically the `rel` parameter) and the reply there says:

> We would have to manually parse the URL and change the embed code to include those, which is hacky at best (the embed code can change any day). Thus, I would say this is plugin territory. Here's one plugin you can try: https://wordpress.org/plugins/hide-youtube-related-videos/

<sup>Source: https://core.trac.wordpress.org/ticket/37552</sup>

Related note: I found that `autohide` is no longer used by YouTube for for embedded HTML5 players:

> The `autohide` parameter has been deprecated for the HTML5 player. In HTML5 players, the video progress bar and player controls display or hide automatically.

<sup>Source: https://developers.google.com/youtube/player_parameters#release_notes_08_19_2015</sup>

If you would like to raise the issue again to see if it's something that can be re-considered, please follow the guide at https://make.wordpress.org/core/handbook/testing/reporting-bugs/
