### ISSUE TITLE
Cant find permalink

### ISSUE THREAD

**Issue by chalamministries** [WordPress/gutenberg#8460]
Where is the permalink? And how do I edit it?

**Comment by kjellr** [comment]
Hi @chalamministries — you can edit the permalink by clicking on the title of the post. The permalink, along with an "Edit" button will display above the title when it's selected:

![permalink](https://user-images.githubusercontent.com/1202812/43657481-fc644dc0-9723-11e8-96e2-c7b4656d9400.gif)

**Comment by designsimply** [comment]
The permalink is editable after the first time a post is saved as long as the permalink setting contains `%postname%` or `%pagename%` (which is common unless you've set permalinks to "Plain" or made some custom modifications to permalinks).

It should appear just above when you click on the title. If there is a notice bar, dismiss it to see the permalink option.

**Comment by youknowriad** [comment]
Closing. let us know if those answers don't help.
