### ISSUE TITLE
Adding a new post results in a blank screen

### ISSUE THREAD

**Issue by henryoladeji** [WordPress/gutenberg#8471]
**Describe the bug**
After i install the plugin, it works for sometime but anytime i want to add new post, it becomes blank.

**Comment by designsimply** [comment]
Thank you for reporting this! I tested and couldn't make this problem happen, and I want to know more. May I ask what OS and browser version you are using? Can you see any errors your browser console when you add a new post?

**Video:** [33s](https://cloudup.com/cZlF_XA_mXc)
<sup>Seen at http://alittletestblog.com/wp-admin/post-new.php running WordPress 4.9.8 and Gutenberg 3.4.0 using Chrome 67.0.3396.99 on macOS 10.13.6.</sup>

**Comment by designsimply** [comment]
Let's move to #8455 which reports the same problem and has more information.
