### ISSUE TITLE
Saving a post does not update the Featured Image box

### ISSUE THREAD

**Issue by MartinStehle** [WordPress/gutenberg#8474]
## Issue Overview
If a post is saved the Featured Image panel does not change if changes of the post featured image via the "save_post" hook were fired.

## Steps to Reproduce

1. In the functions.php add an action on "save_post" which sets a featured image for the saved post; the WP core function "set_post_thumbnail()" helps. Imagine a code like:
```
function test_save_post_hook( $post_id = 0 ) {
	// change the second parameter to an ID 
	// of an existing image in the media library
	set_post_thumbnail( $post_id, 44 ); 
);
add_action( 'save_post', 'test_save_post_hook', 10, 1 );
```
2. Create a post with dummy texts and save it as a draft or as a published post (this does not matter here).
3. Look at the Featured Image panel: there is no change.
4. Open the post edit page again: the featured image is displayed.

## Expected Behavior
It is expected that the Featured Image panel is updated on any change via the "save_post" hook after saving the post.

## Current Behavior
The Featured Image panel is not updated on any change via the "save_post" hook after saving the post.

## Possible Solution
Also consider the Featured Image panel when saving the post: was a featured image set, modified or deleted? If so, update the Featured Image panel accordingly.

**Comment by ngygen323** [comment]
Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.

**Comment by designsimply** [comment]
Noting I deleted a comment which was saying the same thing over and over many times per minute in various locations. Spamming and unacceptable behavior towards anyone, or this community, will not be allowed. If you want to give feedback, please do it without spamming or personal attacks.

My apologies for those who were effected during this. Please know we have a zero tolerance policy over this type of behavior.

**Comment by MartinStehle** [comment]
@danielbachhuber 
Thank you for the note. I think this has to be a WP core feature, not a feature of a plugin, dropin or theme.

**Comment by MartinStehle** [comment]
That is right but the box or panel "Featured Image" does not become updated when a post is updated in Document mode.

**Comment by danielbachhuber** [comment]
> "Featured Image" does not become updated when a post is updated in Document mode.

Correct. This is a difference of behavior between Gutenberg and the Classic Editor.

**Comment by MartinStehle** [comment]
And why that difference?

**Comment by MartinStehle** [comment]
If clients use a plugin that sets a featured image automatically they excpect the change in the "Featured Image" panel while updating. This panel has to be updated if the featured image has changed. Is that possible?

**Comment by danielbachhuber** [comment]
> This panel has to be updated if the featured image has changed. Is that possible?

Good question. I think the logic would need to be something like this:

1. When a post is saved,
2. Fetch only the `featured` attribute for the post,
3. Update the store with this new `featured` attribute,
4. The Featured Image component updates itself automatically.

@aduth @gziolo Any suggestions on how this might be achieved? I'll create some documentation if there isn't already.

**Comment by aduth** [comment]
I am certain there are some incidentals that complicate what's occurring here, but at a high-level I am expecting this should work out of the box. When a post update completes, we (should) apply what we received from the server's response to the canonical version of the post. Since the featured image field in the editor (should) read from this attribute directly, it (should) update what's shown in the UI to reflect whatever changes occurred in the saving of the post.

**Comment by danielbachhuber** [comment]
> When a post update completes, we (should) apply what we received from the server's response to the canonical version of the post.

Is this the current behavior? I was actually thinking this would be problematic, as it would cause a re-render of the entire editor.

**Comment by aduth** [comment]
"(should)" is to mark how I expect it to work, regardless of if in-fact it's occurring that way.

It also shouldn't cause a re-render of the entire editor for two reasons:

- Components independently consume only data they need, so it should only be the components consuming from post properties that would need to update
- If the value of the state has not changed, the component won't be updated (this is handled by `withSelect`).
   - For most post property values we would assume to be the case, except those which are filtered and modified server.

**Comment by danielbachhuber** [comment]
I tested this again today with the following code snippet:

```
add_action( 'save_post', function( $post_id ) {
	$attach_id = 1;
	set_post_thumbnail( $post_id, $attach_id );
});
```

The post is correctly assigned the featured image when it's created or updated:

![featured](https://user-images.githubusercontent.com/36432/46246188-5dc94f00-c3ae-11e8-8896-4a7550661e03.gif)

However, you'll notice in my GIF that the image doesn't actually load. It looks like this issue is documented with #9982

**Comment by danielbachhuber** [comment]
> However, you'll notice in my GIF that the image doesn't actually load. It looks like this issue is documented with #9982

Actually, this issue was #10214
