### ISSUE TITLE
Popup will appear asking me if I am certain to leave the article unsaved then disappears and leaves the article stuck open

### ISSUE THREAD

**Issue by Actionerd** [WordPress/gutenberg#8477]
Hi,, 
First of all, I wanna say that I am using the latest version of Chrome, with Windows 8.1. I don't know if that happens with anyone else but : 

Let's say that I wanna close a Window on Chrome or to rewind to a previous page from an article that hasn't been saved. A popup will appear asking me if I am certain to leave the article unsaved. With Gutenberg, the pop-up will appear, then disappear within the next seconds, letting me stuck on the article. I can't provide you with a screenshot of the problem, I am not fast enough.

**Comment by ngygen323** [comment]
Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.

**Comment by ngygen323** [comment]
Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.

**Comment by ngygen323** [comment]
Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.

**Comment by ngygen323** [comment]
Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.Read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this. Is this purely driven by core developers? I see you are ignoring a lot of responses.

**Comment by karmatosed** [comment]
Noting I deleted 2 comments saying the same thing and minimised 2 more saying again the same thing. Spamming and unacceptable behaviour towards anyone or this community will not be allowed in this repo. If you want to give feedback please do it without spamming or personal attacks.

My apologies for those whose issues were hijacked during this. Please know we have a zero tolerance policy over this type of behaviour.
