### ISSUE TITLE
The custom HTML block should be further improved

### ISSUE THREAD

**Issue by babblebykev** [WordPress/gutenberg#8479]
The custom HTML block should have a visual editing mode, and automatic paragraphs, like the text editor in the old version had, for less distracting writing. Also, there should be an option to automatically wrap each custom HTML in a div.

**Comment by youknowriad** [comment]
No, that's not the purpose of the HTML block, the HTML block is for people that want to always write HTML but stay in the visual mode of Gutenberg for other blocks.

If you want a block similar to the old visual editor, you can use the "Classic" block and notice that you can switch most blocks to a dedicated "Code mode" per block when you click on the ellipsis menu at the right of the selected block. (so this works for the classic block if you want a similar experience to the previous editor).

**Comment by babblebykev** [comment]
Thanks for the response.

On a final note, is there any way to auto-wrap each HTML block in a div through a function or anything? I'm currently using those as a way to group a heading with a set of paragraphs in a post to fit the theme I'm developing.

**Comment by youknowriad** [comment]
@babblebykev A plugin could be developed to allow that. Take a look at the Gutenberg Handbook to see the extensibility APIs.

This filter could probably be used to add wrappers https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#blocks-getsaveelement


This PR adds an example usage for this filter (which is slightly different from what you need but hopefully, it gives you an idea) https://github.com/WordPress/gutenberg/pull/8470/files

**Comment by babblebykev** [comment]
Hello again,

So I was able to make a plugin to auto-wrap the HTML blocks. However, although I'm pretty sure I got the code right, my console reported an "Uncaught SyntaxError: Unexpected token <", particularly with this line:

`return ( <div className="row"> { element } </div> );`

What should I do to fix this error?

**Comment by youknowriad** [comment]
Are you transpiling your code? It seems that you're using JSX, if you do so, you need to use babel to "build" your javascript code. Alternatively, you can replace the line above with:

```
return wp.createElement('div', { className: 'row' }, element );
```

**Comment by babblebykev** [comment]
Just replaced the line with the alternate code, and the editor ended up returning an "Unexpected error".

**Comment by youknowriad** [comment]
This happens when you have JavaScript errors. You can see those in the console, it's more likely coming from the script you wrote.

**Comment by babblebykev** [comment]
Just reviewed the code, and it's finally working. Thanks for the help, @youknowriad! 👍

**Comment by youknowriad** [comment]
Glad you got it working 👍
