### ISSUE TITLE
High memory in a fresh wordpress installation

### ISSUE THREAD

**Issue by ngygen323** [WordPress/gutenberg#8482]
I also took some time to install it and test it in a fresh container. The memory overhead is high. The difference is as high as 50 MB. This must be a plugin and not a core function.

**Comment by youknowriad** [comment]
Hi There!

The plugin is `1.3MB` and installing it doesn't trigger anything special. If you have more details about the memory increase you're seeing, we'd be happy to investigate more but this is most likely not related to the plugin at all.
