### ISSUE TITLE
Not in the core. This looks like a plugin.

### ISSUE THREAD

**Issue by ngygen323** [WordPress/gutenberg#8483]
Please read the reviews of people who are against it. Usually a project gets hate for the change. But in this case I feel that everyone has a fair point for the opposition. Text editor is a vital part and it should not be like this.

Is this purely driven by the core developers? I see that you are ignoring a lot of responses.

**Comment by youknowriad** [comment]
Can you please stop opening the same issue over and over again. We hear you and we've been hearing reviews for a long time now. 

If you have specific issues you'd like to be improved in the editor, do open issues and we'll try to work on them as much as we can, but opening this kind of issues don't help.

We get it, it's a big change but it's a needed change that's not driven by specific persons but years of thoughts and insights. Please give it some time.

Thanks.
