### ISSUE TITLE
Sidebar: Allow hiding sidebar panels

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#851]
This button:

![screen shot 2017-05-22 at 10 54 03](https://cloud.githubusercontent.com/assets/1204802/26299971/0a5514fa-3edd-11e7-8bf2-11937e532373.png)

should invoke an equivalent of the "Screen Options" panel from the admin:

![screen shot 2017-05-22 at 10 53 50](https://cloud.githubusercontent.com/assets/1204802/26299989/1b50d294-3edd-11e7-9b62-6aa0404f7782.png)

Needs #450, as well as the rest of the panels. 

Context:

![screen shot 2017-05-22 at 10 53 57](https://cloud.githubusercontent.com/assets/1204802/26300025/343f4a6a-3edd-11e7-88ab-f0db97903a7c.png)

**Comment by mtias** [comment]
Closing as duplicate of #851 which has more activity.

**Comment by mtias** [comment]
Sorry, #1351.
