### ISSUE TITLE
Sidebar: Status & Visibility panel

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#852]
Design:

![screen shot 2017-05-22 at 10 56 24](https://cloud.githubusercontent.com/assets/1204802/26300061/519b2d04-3edd-11e7-9655-739fe2e96483.png)

Context:

![post settings](https://cloud.githubusercontent.com/assets/1204802/26300074/5f407b6c-3edd-11e7-99d3-3ee9521cc08e.png)

CC: @youknowriad because you've essentially built 90% of this in PRs already.

**Comment by youknowriad** [comment]
closed by #841
