### ISSUE TITLE
After activating, new editor won’t open Safari on iPad 10.5 Pro 11.4.1 - Wordpress 4.9.8

### ISSUE THREAD

**Issue by iamundead** [WordPress/gutenberg#8523]
**Describe the bug**
I simply followed the activation steps for the new editor in the wp-admin site. Now when I open the post editor it does not load and displays a white page with all of my normal navigation tree on the left side

**To Reproduce**
1. Go to Dashboard
2. Follow steps to activate new editor
3. Open editor for posts or pages or click “try new editor”
4. Editor will not load

**Expected behavior**
the new editor should open

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: iPad Pro 10.5
 - OS: 11.4.1
 - Browser: Safari
Wordpress 4.9.8

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
I think this is a duplicate of #8455 Let's consolidate and fix this kind of issues there.
