### ISSUE TITLE
Accessibility: block label in the upper right corner can create motion sickness when quickly jumping from one block to another

### ISSUE THREAD

**Issue by samikeijonen** [WordPress/gutenberg#8524]
**Is your feature request related to a problem? Please describe.**
This issue is submitted in WP.org support forum. It's about [flashy block type in the upper right corner](https://wordpress.org/support/topic/feature-request-accessibility-options-2/) can create motion sickness.

<img width="681" alt="block type in the upper right corner" src="https://user-images.githubusercontent.com/1820415/43676016-b5a59988-97f1-11e8-9a09-ddc07ed3b75e.png">

When quickly hovering over blocks you can image that it can certainly feel flashy.

> At the moment I’m editing a lot of pages quite quickly and jumping from one block to another is making me sick

**Describe the solution you'd like**
What I'd like to suggest is to change blue color to grey color.

**Describe alternatives you've considered**
User also noted can there be option to turn these off or change to another color. But I guess options like these is not a good idea since there would be a lot of options here and there.

But there could be a plugin for these options if needed.

I can look for articles about this subject in general.

**Comment by aduth** [comment]
I assume this was meant to have been closed by #9197 , with delays added to the display of the label .

cc @kjellr

**Comment by kjellr** [comment]
That's right, thanks @aduth!
