### ISSUE TITLE
No wrapping of text around inline image in paragraph

### ISSUE THREAD

**Issue by tuvelijn** [WordPress/gutenberg#8527]
See example at http://www.spaceintime.eu/2018/08/04/saline-royale-in-arc-et-senans-2/.
De words don't wrap around the images.

**Comment by youknowriad** [comment]
Hi there!

Inline images don't wrap around text, you should use the "image" block for that (not the "inline image" block). See this GIF and issue for more details https://github.com/WordPress/gutenberg/issues/8434#issuecomment-410289123
