### ISSUE TITLE
Incorrect text saved for RichText when using a span tag

### ISSUE THREAD

**Issue by donnapep** [WordPress/gutenberg#8531]
**Describe the bug**
Using Gutenberg 3.4.0, when setting the `tagname` prop of the `RichText` component to `span`, the backspace key doesn't trigger the `onChange` handler. As a consequence, the text that is saved is incorrect.

**To Reproduce**
1. Add a block containing a `RichText` component configured similar to:
```
<RichText
	onChange={ ( nextContent ) => {
		setAttributes( {
			title: nextContent,
		} );
	} }
	placeholder={ __( 'Enter title…' ) }
	tagName="span"
	value={ title }
	keepPlaceholderOnFocus />
```
2. Create a new post and add the block.
3. Enter _A_, then remove the _A_ by hitting the Backspace key, and then enter _B_.
4. Click _Save Draft_ and then preview the post. Refresh the editor.

**Expected behavior**
I expected both the preview and the editor to show _B_, but instead they show _A_.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version: 67.0.3396.99

**Comment by youknowriad** [comment]
I'm closing this issue in favor of #8531

TinyMCE doesn't allow inline tagNames for containers so we need to move away from them.
