### ISSUE TITLE
Block validation: exclude data attributes / add support for custom validators

### ISSUE THREAD

**Issue by AndiDittrich** [WordPress/gutenberg#8532]
Dear Gutenberg Team,

i'm currently developing a [Gutenberg Plugin](https://github.com/EnlighterJS/Plugin.Gutenberg) to integrate [EnlighterJS](https://github.com/EnlighterJS/EnlighterJS) Syntax Highlighter into to editor and ran into serious trouble regarding the "block/element validation":

Because of the strict **1:1** structure validation there seems to be no possibility? to add **optional attributes** to the elements generated by the `save` function. 
The editor always throws element validation errors in case custom attributes are added (e.g. manually by a user - which might be legitimate).

Of course, its possible to add **all** allowed attributes to the output...but this will mess-up the generated html with a lot of **unused attributes**

#### Example HTML Structure ####

```html
<pre 
data-enlighter-language="less" 
data-enlighter-highlight="2" 
data-enlighter-lineoffset="" 
data-enlighter-linenumbers="" 
data-enlighter-title="">
...
</pre>
```

#### Typical Validation Error ####

![gutenberg_validation_error](https://user-images.githubusercontent.com/1474107/43678670-fc9df990-9817-11e8-8233-c0715450f89d.png)

#### Suggestions ####

* Exclude `data-` attributes from validation (they represent an elements state, not its structure)
* Add support for custom block validation methods (within `registerBlockType`) to allow users to override the default behaviour
* Maybe use the **attribute** schema to validate the structure, including an `optional` flag

best regards, Andi

**Comment by designsimply** [comment]
Closing in favor of consolidating with #7604. If you feel it's not a good consolidation, please leave a comment explaining why and we can re-open!
