### ISSUE TITLE
Gutenberg Editor fails to load, leaving blank page where it should be

### ISSUE THREAD

**Issue by primedcore** [WordPress/gutenberg#8534]
**Describe the bug**
Possibly a duplicate of #8455, however the same bug is also induced by changing the default Permalinks format to "Day and Title".
**To Reproduce**
1. Install Gutenberg 3.4.0 on WordPress 4.9.8 with PHP 7.2.8 and latest versions of other software required.
2. Go to WordPress Dashboard
3. Hover over Settings in the left hand side menu
4. Click on Permalinks in the expanded ribbon
5. Change the default of the Permalinks format from "Plain" to "Day and Name"
6. Go to Posts or Pages
7. Click on the arrow on the right of the new Add New button
8. Select Gutenberg Editor
9. Bug displays (👎)

**Expected behavior**
The Gutenberg editor loads properly and waits for the user to edit a new page.

**Actual behavior**
The Gutenberg editor fails to load, and the content page is left blank, with no "Publish" button or sidebar, except for the WordPress menu on the left hand side and the top "admin" bar of WordPress.

**Desktop:**
 - OS: Windows 10 Home
 - Browser: Opera 54, Chrome 67 (yes, out of date)
 - Gutenberg Version: 3.4.0

**Additional context**
- again. Gutenberg version 3.4.0, wordpress 4.9.8, other listed above

**Comment by abwdvm** [comment]
Maybe upgrade your WordPress 3.9.8  to Wordpress 4.9.8

**Comment by primedcore** [comment]
I meant 4.9.8. I have the latest version

**Comment by youknowriad** [comment]
Could this fix it #8578?

**Comment by primedcore** [comment]
Nope, found the solution. The permalinks were improperly set up. I needed to add permissions to .htaccess through httpd.conf. That solved it and now it's working as expected. Thank you for your help anyway.
