### ISSUE TITLE
Handbook FAQ needs updating

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#8535]
With the try callout having gone out, there are a lot of duplicate questions and a lot of confusion and misconceptions. There is also quite a bit of negativity. This can be one or two things: a lot people do not want Gutenberg and/or they do not understand Gutenberg. Hopefully it is the latter, though that would show that core has done a poor job explaining what Gutenberg is.

To combat confusion and misconceptions and to answer questions, I think linking to a FAQ in all first responses to support requests and reviews is a good first step. Unfortunately, the [FAQ page in the handbook](https://wordpress.org/gutenberg/handbook/reference/faq/) seems to have been neglected a bit and could really use some updates.

## Out-of-date info

[**Will there be columns?**](https://wordpress.org/gutenberg/handbook/reference/faq/#will-there-be-columns)

This section references a closed issue and does not acknowledge the existence of the Columns block. This section should be updated to talk about the current Columns block and why it currently lacks responsive columns and multi-width columns. It should also link to more current tickets.

[**Will there be nested blocks?**](https://wordpress.org/gutenberg/handbook/reference/faq/#will-there-be-nested-blocks)

This section is out-of-date since nested block and child block support has been added. It should be changed to say that nested blocks already exist, and mention the parent/child support.

[**How will block styles work in both the front-end and back-end?**](https://wordpress.org/gutenberg/handbook/reference/faq/#will-there-be-nested-blocks)

This section seems slightly out-of-date. I think the way themes support wide/full widths is finished now?

[**Will I be able to opt out of Gutenberg for my site?**](https://wordpress.org/gutenberg/handbook/reference/faq/#will-i-be-able-to-opt-out-of-gutenberg-for-my-site)

This section should mention the Classic Editor and Gutenberg Ramp plugins.

[**How can I parse the post content back out into blocks in PHP or JS?**](https://wordpress.org/gutenberg/handbook/reference/faq/#how-can-i-parse-the-post-content-back-out-into-blocks-in-php-or-js)

I think this section might need updating due to the recent splitting off of JS packages.

## General recommendations for improvement and other thoughts

I know it is said in a general sort of sense, but I think the FAQ could do a better job of explaining that Gutenberg is not a page builder and is not supposed to be a page builder until later, though it does have a lot of the foundations of a page builder already in place.

Is the FAQ aimed mostly at developers? Because if so, there needs to be an average user-friendly FAQ that includes the answers to questions like "why is the editor so thin" or "where are responsive/non-equal-width columns" or "what happened to coloring text" or "why are you removing options" or just in general "where is X feature and why has it not been added yet or been removed".

Also, I think the FAQ should be linked in the first response to any support requests and plugin reviews. It is tiresome to explain the same things over and over again, and generic responses with no helpful info tend to annoy people, so linking to helpful information would definitely make for better PR. And looking at the generally negative response in the Gutenberg plugin reviews, you are really gonna need better PR.

**Comment by tofumatt** [comment]
There's some helpful stuff in this issue for sure, but I'm not quite sure how actionable it is as there are several points worth addressing meaning this might actually be a few issues in one.

Do you think you could separate out these issues or possibly create a pull request aimed at closing this that addresses the **Out-of-date info** section? I think if you addressed those in a pull request we could consider this closed, and then discuss your questions in another issue. 😄

**Comment by mkaz** [comment]
In PR #12486, I've tried to address some of the concerns listed in this ticket, mostly updating of the clearly outdated information. 

There are several other concerns in the ticket, but as @tofumatt said not as actionable.  It will help us make progress to have more targeted tickets per topic so we can address and update where needed.

Also, a User's Handbook is under development and will probably address the concerns around that. See https://github.com/WordPress/gutenberg/issues/11252
