### ISSUE TITLE
Auto-save fail with remove_post_type_support

### ISSUE THREAD

**Issue by arnolem** [WordPress/gutenberg#8536]
**Describe the bug**
I have a plugin who use this : 
```
add_action('init', function () {
    remove_post_type_support('post', 'revisions');
});
```
When the **auto-save** query is sent to `/wp-json/wp/v2/posts/12/autosaves`, WordPress send a **404 HTTP error**

`{"code":"rest_no_route","message":"No route was found matching the URL and request method","data":{"status":404}}`

**To Reproduce**
1. Add the following code on function.php
```
add_action('init', function () {
    remove_post_type_support('post', 'revisions');
});
```
2. Create a new article with Gutenberg
3. Write a title and a little paragraph
4. Wait autosave to view error

**Screenshots**
![image](https://user-images.githubusercontent.com/2263103/43680370-73aa3924-9839-11e8-8b42-f1abaf600c45.png)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser Firefox 61.0.1 (64 bits)

**Additional context**
- WordPress Version 4.9.8
- Gutenberg Version 3.4.0

**Comment by abwdvm** [comment]
I had a similar problem. I fixed it with the Cloudflare Firewall "fix"

**Comment by abwdvm** [comment]
I made this ;)
http://www.ksstradio.com/2017/12/the-gutenberg-cloudflare-free-fix/
