### ISSUE TITLE
Gutenberg removes Twenty Fourteen's "featured" tag from posts

### ISSUE THREAD

**Issue by agkozak** [WordPress/gutenberg#8544]
When used with the Twenty Fourteen theme, Gutenberg removes the `featured` tag that makes posts show up in the home page's Featured Content section. Attempts to re-add the `featured` tag result in new tags called `featured`, but with slugs such as `featured-2` and `featured-3`, so that the posts still do not appear in Featured Content.

A workaround would appear to be to change the featured content tag name (in Customizer/Featured Content/Tag Name) to anything else and then to change it back to `featured`.

**To Reproduce**

1. Install WordPress 4.9.8 on development server.
2. Install and activate Twenty Fourteen theme (v2.2).
3. Create three posts, each with several tags, among which is `featured`.
4. The posts will now be visible in Featured Content on the Home Page.
5. Install the Gutenberg plugin.
6. In the Gutenberg editor, the `featured` tag will now be invisible. If each post is saved, it will lose its `featured` tag and status, disappearing from Featured Content.
7. If one attempts to re-add the `featured` tag inside the Gutenberg editor, a new tag named `featured` will be created with the slug `featured-2`, so that the post will not appear in Featured Content. Further attempts will result in `featured-3`, `featured-4`, etc.

**Expected behavior**
From the point of view of the Gutenberg editor, `featured` should just be a tag like any other. As far as I know, it's Twenty Fourteen that treats it as being special, and even that can be adjusted.

**Additional context**
Gutenberg v3.4.0

**Comment by youknowriad** [comment]
Gutenberg don't have any impacts on the taxonomies AFAIK. Are you still having the issue?
Closing for now as this is probably obsolete, let's reopen if you're still experiencing the issue with 5.0.

**Comment by youknowriad** [comment]
Tip: This tag is not returned by the REST API for some reasons.

**Comment by organ-droid** [comment]
I still have this issue on a running server. Anyone at it?

**Comment by mcguffin** [comment]
You can work around this issue by adding the following code into a mu-plugin:

```
add_action('rest_api_init', function(){
	if ( get_template() === 'twentyfourteen' && class_exists('Featured_Content') && has_action( 'get_terms', [ 'Featured_Content','hide_featured_term'] ) ) {
		remove_filter( 'get_terms', [ 'Featured_Content', 'hide_featured_term' ], 10 );
	}	
});
```

**Comment by carolinan** [comment]
Hi, this should be solved in the theme.
The condition to hide the term on the front is using `is_admin()`, it needs an exception for REST requests as well.

Replaced by https://core.trac.wordpress.org/ticket/64882
