### ISSUE TITLE
Gutenberg Shortcode "Button"

### ISSUE THREAD

**Issue by 3zimmer** [WordPress/gutenberg#8550]
I miss when entering the URL in the Shortcode Button, that you can open it in a separate link.
It would also be helpful if you could also integrate small, possibly pre-made icons (Analog Plugin Shortcode Ultimate).

**Comment by youknowriad** [comment]
This looks like a duplicate of #8000 Let me know if I'm reading wrong?

**Comment by 3zimmer** [comment]
Yes, I would like to open the link in **a new window**, but that will not work if I integrate a new "button" in the new Gutenberg editor. (we can not put a tick) By closing this URL, I also close the whole WP page at the same time, and that should not be
