### ISSUE TITLE
Code block doesn't render less than symbol (renders &lt; instead)

### ISSUE THREAD

**Issue by JeremyTBradshaw** [WordPress/gutenberg#8552]
**Describe the bug**
Gutenberg code blocks convert "<" to "&lt;".  It's such a common code character, there must be something I'm missing?

**To Reproduce**
1. Insert a new block in the gutenberg editor.
2. Type in a PowerShell multiline help, starting with <# and ending with #>. 
4. See erroneous rendering in preview.

**Expected behavior**
It should leave the "<" intact.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser: chrome,

**Smartphone (please complete the following information):**
N/A

**Additional context**
Current version with WordPress 4.9.8

**Comment by designsimply** [comment]
I tested adding the following sample code to a code block and previewing and the code looked correct to me in the preview:

```
<# powershell #>

<# powershell 
multiline
help #>
```

![screen shot 2018-08-07 at tue aug 7 1 59 57 pm](https://user-images.githubusercontent.com/1119271/43799277-51aa36b8-9a4a-11e8-8644-53635c8c7b52.png)
<sup>Tested with WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

Is it possible you have a theme or plugin conflict affecting the preview? Can you try testing with the default theme or the [Gutenberg Starter Theme](https://github.com/WordPress/gutenberg-starter-theme) as a test?

**Comment by JeremyTBradshaw** [comment]
Well I do have a custom theme (Lodestar) in use, and I'm using Crayon Syntax Highlighter.  I will take your word for it, based on your screenshot that either of these is my problem.  Thanks for taking the time to try it and sharing the results.

**Comment by JeremyTBradshaw** [comment]
Sure enough, I just tested with and without Crayon plugin enabled.  When it is activated, only Guteburg's Code blocks are affected, Classic blocks are not affected.  When it is deactivated, the issue is resolved.

I guess it's not Gutenberg's fault :).  I will try to find an alternative means to do what Crayon does.  Thanks again.

**Comment by vijayst** [comment]
Thanks for isolating this to Crayon. I had the same problem and I got around it by checking the box in Crayon settings: Decode HTML entities in code.

**Comment by JeremyTBradshaw** [comment]
Ahhh, good to know, I'll give this a try soon.  Thanks as well.

**Comment by XTronical** [comment]
Thanks vijayst, I've used Crayon for sometime and at the start this wasn't or didn't seem to be a problem then it crept in somehow, anyway, your suggestion sorted it for me as well.
