### ISSUE TITLE
FocusableIframe: React does not recognize the forwardedRef prop on a DOM element

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#8560]
**Describe the bug**
When rendering a `FocusableIframe`, the following warning message appears in the console: 

> Warning: React does not recognize the `forwardedRef` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `forwardedref` instead. If you accidentally passed it from a parent component, remove it from the DOM element.

**To Reproduce**
Execute the code below in a new React project after installing `@wordpress/components`.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { FocusableIframe } from '@wordpress/components';

import '@wordpress/components/build-style/styles.css';

const MyFocusableIframe = () => (
	<FocusableIframe
		src="/"
		onFocus={ () => console.log( 'iframe is focused' ) }
	/>
);
ReactDOM.render(
	<MyFocusableIframe />,
	document.getElementById( 'root' )
);
```

**Expected behavior**
No warning message should appear.

**Desktop:**
 - OS: macOS High Sierra
 - Browser Chrome
 - Version 67

**Additional context**
Issue found while working on #8338 and Automattic/wp-calypso#26367

**Comment by aduth** [comment]
Fixed by #8570
