### ISSUE TITLE
Posts available, pages disappears and shows Posts

### ISSUE THREAD

**Issue by asonic** [WordPress/gutenberg#8562]
## Issue Overview
After activating Gutenberg Plugin, my Pages disappears and where not available (404)

## Steps to Reproduce (for bugs)
1. download, install an activate gutenberg
2. do some new posts (my Problem exists after one new Post)
3. save your work, but do not publish
4. look at all pages, there is only the overview of posts available
5. look at the website, the page-created sites shows a 404-Error
6. disable Plugin, the pages where available again
7. the 404-Error disappears

I´ve used Firefox Quantum 61.0.1 (64 Bit) (Standardbrowser
## Expected Behavior
This is a Bug, so please ensure that the pages does not disappear (backend and frontend)

## Current Behavior
All Pages disappearaded, at the front-end, i became a 404-Error on all linked pages, on the back-end all pages disappearded and showed the Posts instead. (When you select all pages in the pages section)

## Possible Solution
Maybe a wrong Databasequery? (seems like Copy & paste-Error)

**Comment by abwdvm** [comment]
Do you use Cloudflare?

**Comment by asonic** [comment]
No, i don´t use Cloudflare.

**Comment by asonic** [comment]
No, i don´t use Cloudflare.

**Comment by designsimply** [comment]
Gutenberg should not affect the availability of all previously published pages the moment the plugin is enabled. May I confirm that is what you are still seeing even with the latest version of Gutenberg which is 3.8? If yes, do you have any custom pathways or redirects in place on the server side which may be affecting how pages are served?

I am going to close this issue for now, but we can continue the conversation and re-open later if more information becomes available to help uncover possible sources of this problem.
