### ISSUE TITLE
NavigableContainer: Items in TabbableContainer are not navigated in order

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#8563]
**Describe the bug**
When rendering a `TabbableContainer` component outside Gutenberg, the items are not navigated in order when pressing the `tab` key.

The menu navigates from the Section 1 to the Section 3 and from the Section 2 to the Section 4.

**To Reproduce**
Execute the code below in a new React project after installing `@wordpress/components`.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { TabbableContainer, Button } from '@wordpress/components';

import '@wordpress/components/build-style/styles.css';

const MyTabbableContainer = () => (
	<TabbableContainer onNavigate={ onNavigate }>
		<Button isDefault tabIndex="0">Section 1</Button>
		<Button isDefault tabIndex="0">Section 2</Button>
		<Button isDefault tabIndex="0">Section 3</Button>
		<Button isDefault tabIndex="0">Section 4</Button>
	</TabbableContainer>
);

ReactDOM.render(
	<MyTabbableContainer />,
	document.getElementById( 'root' )
);
```

**Expected behavior**
The menu navigates from the Section 1 to the Section 2 and from the Section 2 to the Section 3.

**Screenshots**
![aug-05-2018 23-22-22](https://user-images.githubusercontent.com/1233880/43690206-81c8fa54-9906-11e8-9d36-26a5f487b3fb.gif)

**Desktop:**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: 67

**Additional context**
Issue found while working on #8338 and Automattic/wp-calypso#26367

**Comment by aduth** [comment]
`TabbableContainer` is meant to manage key events on your behalf. Have you tried omitting `tabIndex`?

Even if that works, `TabbableContainer` should at worst be preventing the default browser behavior to avoid the double-skip.

**Comment by tn3rb** [comment]
wow this is old...
can confirm that the `TabbableContainer` jumps to every other item upon tabbing.
removing `tabIndex` had no effect and did not prevent the double-skip.

**Comment by paaljoachim** [comment]
How should we move this old issue forward?
@mcsf @ockham

**Comment by mcsf** [comment]
Closing until someone can fix this. If it's not impacting usage within Gutenberg, it can't be prioritised. There are also opportunities with the [partial adoption of Reakit](https://github.com/WordPress/gutenberg/pull/28085), as well as the [new Components project](https://github.com/WordPress/gutenberg/issues/27484), to see this component superseded by better solutions.
