### ISSUE TITLE
Placeholder: Width exceeds the width of the parent

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#8564]
**Describe the bug**
When rendering a `Placeholder` component outside Gutenberg, its width exceeds the width of the parent element.

It's caused by a [padding of 1em](https://github.com/WordPress/gutenberg/blob/3450273fe7522101e3809b270c80a7b9a3ebcf3a/packages/components/src/placeholder/style.scss#L6) that is added to the width because `box-sizing` is not `border-box`.

**To Reproduce**
Execute the code below in a new React project after installing `@wordpress/components`.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Placeholder } from '@wordpress/components';

import '@wordpress/components/build-style/styles.css';

const MyPlaceholder = () => (
	<div style={ { border: 1px solid black; } }>
		<Placeholder
			icon="wordpress-alt"
			label="Placeholder"
		/>
	</div>
);

ReactDOM.render(
	<MyPlaceholder />,
	document.getElementById( 'root' )
);
```

**Expected behavior**
The placeholder doesn't exceed the width of the parent.

**Screenshots**
![screen shot 2018-08-05 at 23 36 58](https://user-images.githubusercontent.com/1233880/43690320-80b2f794-9908-11e8-8ddb-77f022ad5130.png)

**Desktop:**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: 67

**Additional context**
Issue found while working on #8338 and Automattic/wp-calypso#26367

**Comment by youknowriad** [comment]
We should just add an explicit border-box box sizing property. Ideally all components work properly without global resets.
