### ISSUE TITLE
SandBox: Content not displayed

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#8565]
**Describe the bug**
When rendering a `SandBox` component outside Gutenberg, its content is not displayed because the iframe has a width set to 0.

**To Reproduce**
Execute the code below in a new React project after installing `@wordpress/components`.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { SandBox } from '@wordpress/components';

import '@wordpress/components/build-style/styles.css';

const MySandBox = () => (
	<SandBox
		html="<p>Content</p>"
		title="Sandbox"
		type="embed"
	/>
);

ReactDOM.render(
	<MySandBox />,
	document.getElementById( 'root' )
);
```

**Expected behavior**
The sandbox content is displayed.

**Screenshots**
![screen shot 2018-08-05 at 23 42 56](https://user-images.githubusercontent.com/1233880/43690392-5f4496d4-9909-11e8-8b0c-95fc69bd3574.png)

**Desktop:**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: 67

**Additional context**
Issue found while working on #8338 and Automattic/wp-calypso#26367

**Comment by jorgefilipecosta** [comment]
Thank you for reporting this bug @mmtr, I was able to reproduce this problem.
