### ISSUE TITLE
Spinner: Nothing is displayed

### ISSUE THREAD

**Issue by mmtr** [WordPress/gutenberg#8566]
**Describe the bug**
When rendering a `Spinner` component outside Gutenberg, nothing is displayed. Actually, a `div` with the `spinner` and `is-active` classes is rendered, but these classes are not giving any style at all.

**To Reproduce**
Execute the code below in a new React project after installing `@wordpress/components`.

```jsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Spinner } from '@wordpress/components';

import '@wordpress/components/build-style/styles.css';

const MySpinner = () => (
	<Spinner />
);

ReactDOM.render(
	<MySpinner />,
	document.getElementById( 'root' )
);
```

**Expected behavior**
A spinner should appear.

**Desktop:**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version: 67

**Additional context**
Issue found while working on #8338 and Automattic/wp-calypso#26367

**Comment by youknowriad** [comment]
I think we should do the same we did for the button component: Avoid relying on WordPress Core Styles for the spinner component and copy those styles to Gutenberg itself.
