### ISSUE TITLE
Sidebar: Add Post Format panel, or infer post formats

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#857]
It would be nice if we could infer the post format of a post, based on which block(s) are inserted in the post.

Barring that, here's a design for a transitional panel:

![screen shot 2017-05-22 at 12 19 00](https://cloud.githubusercontent.com/assets/1204802/26303796/25949ec8-3ee9-11e7-9b7e-a14b6284a03f.png)

Context:

![post settings](https://cloud.githubusercontent.com/assets/1204802/26303802/29f648fe-3ee9-11e7-8265-b18cfdf7aacc.png)

**Comment by dshanske** [comment]
In order to infer, you would have to reopen the discussion of what post formats are...what their properties are. But if you want an opinion, inferring is the better move.

**Comment by karmatosed** [comment]
Could we go one step further and have this flow:

- Infer what post format is.
- Only when saved with suggestion can you then edit and change.

Why this? I have seek time and time again people set to standard or just get confused by post formats. Maybe an idea too far, but how useful are they to majority of users on first save?

**Comment by jasmussen** [comment]
Matías has a pretty cool branch in one of the PRs where inferring works. It is based on what the first block in the post is. Right now it _only_ infers, with no option to change. But adding Tammie's suggestion above to that, making this a blue dropdown sheet with options seems like a great way to go about it, and would sync up with what mobile does too.

**Comment by mtias** [comment]
We are already inferring the post format based on what block is present, and whether it matches one of the default post formats. We'll still need the ability to _explicitly_ change it.
