### ISSUE TITLE
Nothing is showing upon activation

### ISSUE THREAD

**Issue by migo33** [WordPress/gutenberg#8571]
**Describe the bug**
Once I installed and activated the plugin the page redirected to the 'new post' page but it's blank.

**To Reproduce**
1. Installed Gotenbertg via the welcome screen
2. Activate
3. New post page
4. Page is blank

**Expected behavior**
Show new editor

**Screenshots**
screenshot
<img width="1414" alt="screen shot 2018-08-06 at 2 40 04 pm" src="https://user-images.githubusercontent.com/670211/43697318-b52420f6-9986-11e8-851f-1fdc0f237843.png">
 attached.

**Desktop (please complete the following information):**
 OS 10.13.6
Chrome (latest)

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by abwdvm** [comment]
Are you using Cloudflare?

**Comment by migo33** [comment]
no.

**Comment by youknowriad** [comment]
This is a duplicate of #8455 and should be fixed by #8578
