### ISSUE TITLE
Private - Public

### ISSUE THREAD

**Issue by SehNSucht12** [WordPress/gutenberg#8574]
Hello!

I use Enfold & Chrome - both actual versions. Gutenberg is 3.4.0

When I set my post to private, it saves it automatically. That part is ok.

If I continue editing and press update, it will be put back to public. That is not ok!

I want it private as long as I do not choose anything else!!!

**Comment by earnjam** [comment]
Hi @SehNSucht12, thanks for reporting this!

I haven't been able to replicate this in my testing. Does this happen if you are using one of the default themes, or only when using Enfold?

**Comment by earnjam** [comment]
Can you test with one of the default themes? I suspect the issue is with the Enfold theme, but I don't have a copy of it to confirm that.

**Comment by designsimply** [comment]
Thank you for the report! I think #9396 is the same issue. I am closing the issue here as a duplicate and because the other issue has more detail and relevant discussion, but please do reply back if you think that's not the case and we can look again.
