### ISSUE TITLE
Theme's Full-Width page template breaks when editor activated 

### ISSUE THREAD

**Issue by NWJeff** [WordPress/gutenberg#8575]
**Describe the bug**
I manage the MustangsNorthwest.com website and have using the Simply Read Theme without issue until the latest WP update. When the editor is activated, the theme's full-width page template (used for the home page) is not retained or used. As a result the page reverts to a default page template that is not full width. Reselecting "Full-Width" does not correct the problem. Switching back to the Classic Editor does not restore the old behavior and Full-Width page selection is not restored. How can I fix this problem? Thank you.

**To Reproduce**
1. Activate editor
2. Go to All Pages
3. Select Welcome - Front Page
4. View page attribute, set to Default, should be Full-Width
5. See error (Preview of page shows side widget on page rather than full-width page style per template)

**Expected behavior**
When initializing editor, it should continue to use Full-Width page template that is provided by theme.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 61.0.1 (64 bit)

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
3.4.0

**Comment by earnjam** [comment]
Hi @NWJeff thanks for reporting this. 

I haven't been able to recreate the issue of the page template not being saved properly in my testing. Can you tell me what plugins you might have active? 

One thing I noticed with the Simply Read theme is that it has a default layout it uses when you choose "Your Latests Posts" under Settings > Reading > "Your homepage displays"
![image](https://user-images.githubusercontent.com/4267290/43706880-91bbc990-9934-11e8-9bbc-cd2ac3da9767.png)

It looks like this:
![image](https://user-images.githubusercontent.com/4267290/43706856-828c7410-9934-11e8-8ccf-b32426c8a924.png)

If you switch that to a static page, it seemed to save and utilize the page template setting properly.

**Comment by NWJeff** [comment]
Thanks for trying to reproduce the problem. Yes, I do use the static page setting to set the Homepage to the Welcome Front Page. That page is one of the pages that uses the Full-Width page template of the theme.

I have to report that I also was not successful today in reproducing the problem. I tried many times with different combinations, uninstalled Gutenberg plug-in and then reinstalled. Could not reproduce. Sorry for the noise. I will mark the issue as closed.

**Comment by earnjam** [comment]
Hmm, very strange. Well, thanks for reporting. If this issue comes back or you have any others, please share them here!
