### ISSUE TITLE
Editor displays white text on a white background when using and Enfold theme

### ISSUE THREAD

**Issue by SehNSucht12** [WordPress/gutenberg#8576]
Hello!

I use Enfold & Chrome - both actual versions. Gutenberg is 3.4.0

In the text block - backend - I do not see, what I write because it is white on white - Frontend is ok - there it  is shown correctly. It looks like this

![textblock](https://user-images.githubusercontent.com/42134551/43704648-a7118b8c-9960-11e8-97bd-8169a394efdb.jpg)

In the post - Backend - I do not see what is written - it looks like this

![textblock1](https://user-images.githubusercontent.com/42134551/43704746-f5162bda-9960-11e8-9eee-8352c7fce8db.jpg)

**Comment by youknowriad** [comment]
Hi there!

Thanks for the report, I think it's probably better if you reach out to the theme's author to see if they have plans on adding Gutenberg support (or at least fixing the conflicting styles) I'm not certain we can do something about it in Gutenberg itself.

Thanks

**Comment by designsimply** [comment]
I checked https://themeforest.net/item/enfold-responsive-multipurpose-theme/4519990/support and I found that the last update at the time of this writing was 5 June 18. I followed the link to the sub support forum and found the following notice about Gutenberg compatibility:

> Enfold 4.4.1 is not compatible with Gutenberg however our devs have already started working on it and improvements/fixes will be included in Enfold 4.4.2. We may need to push back release date of Enfold 4.4.2 a little while our devs are working on Gutenberg compatibility.

Source: https://kriesi.at/support/topic/enfold-4-4-1-gutenberg/

There are also some workarounds provided if you do not want to wait for an official release, which is nice!
