### ISSUE TITLE
ACF content not being saved

### ISSUE THREAD

**Issue by justincavery** [WordPress/gutenberg#8577]
**Describe the bug**
I have a number of Custom Post Types each with their own Advanced Custom Field items.

Once I enable the Gutenberg editor I can still see the ACF below the post, I can add content to the the post and the ACF and they both appear to save successfully. When I view the front end, or reload the page (revisit the post) the ACF content has disappeared.

**Expected behavior**
My content in the ACF remains after saving.

**Screenshots**
update and save gutenberg
<img width="772" alt="update and save gutenberg" src="https://user-images.githubusercontent.com/204469/43705205-d09938d0-9959-11e8-9cd0-11f372166aca.png">

refresh after saving gutenberg
<img width="759" alt="refresh after saving gutenberg" src="https://user-images.githubusercontent.com/204469/43705204-d077ee1e-9959-11e8-9366-d2a166591606.png">

**Comment by earnjam** [comment]
Hi @justincavery thanks for reporting this!

When I've done some basic testing of ACF to try to replicate, it seems to be saving my fields properly on save or publish, and loading them correctly the next time I bring up/refresh the editor. 

Are you seeing any errors in your browser javascript console?

**Comment by youknowriad** [comment]
Also, are you running the last versions of both plugins? I recall similar issues fixed with an ACF upgrade

**Comment by justincavery** [comment]
Definitely the latest version of Gutenberg, will check the ACF version now.

**Comment by justincavery** [comment]
That worked. My license had not been updated and the upgrade to the latest version of the ACF Plugin saved the data. Thank you!
