### ISSUE TITLE
@babel/runtime 7.0.0-beta.56 Causes build errors when using various packages.

### ISSUE THREAD

**Issue by Xyfi** [WordPress/gutenberg#8580]
**Describe the bug**
2 Days ago babel released `runtime` version 7.0.0-beta.56, which has breaking changes. These cause build errors in every project that require gutenberg packages that rely on babel.

**Workaround:** In the `package.json` of your project define ` "@babel/runtime": "7.0.0-beta.55",` as a dependency so `npm` doesn't install version `7.0.0-beta.56`.

**Screenshots**
<img width="667" alt="screen shot 2018-08-06 at 10 49 42" src="https://user-images.githubusercontent.com/5389513/43706727-7a810cfe-9966-11e8-9f83-4fd1482c20d8.png">

**Additional context**
https://github.com/babel/babel/pull/8266

**Comment by tsira** [comment]
+1

**Comment by belcherj** [comment]
Getting this:

```
    ERROR in ./node_modules/@wordpress/i18n/build-module/index.js
    Module not found: Error: Can't resolve '@babel/runtime/core-js/object/assign' in '/var/www/wordpress/wp-content/node_modules/@wordpress/i18n/build-module'
     @ ./node_modules/@wordpress/i18n/build-module/index.js 168:80-127
```

Thinking it may be related.
