### ISSUE TITLE
Summary not working with columns

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#8581]
**Describe the bug**
When using the columns block, heading blocks aren't identified and the summary block doesn't show anything.
 
**To Reproduce**
1. create a post with 2 columns
2. Add a couple of headings inside the columns
3. click on "content structure"
4. click "insert summary"

**Expected behavior**
I expect the summary to show the same content structure as I get when I press the "content structure" icon. Instead it says "Your current post/page has no headings. Try add some headings and update this block later"

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser: Chrome
 - Version 67.0.3396.99

**Additional context**
- Gutenberg version 3.4

**Comment by earnjam** [comment]
Hi @slimmilkduds thanks for reporting this. 

The Content Summary block is something from the [Advanced Gutenberg plugin](https://wordpress.org/plugins/advanced-gutenberg/). You should report this to [the support forum for that plugin](https://wordpress.org/support/plugin/advanced-gutenberg), as it's not an included core block at this time. 

See #7115, #1760, #2871 for more information.

**Comment by slimmilkduds** [comment]
Whoops. I totally missed that, thanks!
