### ISSUE TITLE
Preview is Not Working

### ISSUE THREAD

**Issue by sonugpc** [WordPress/gutenberg#8583]
**Describe the bug**
preview button opens the new page but it does not load the preview. I hop it will be fixed in next uodat
**To Reproduce**
1. Go to New Post
2. Click on Preview
3. See "Loading Message But Preview is not generating"

**Comment by youknowriad** [comment]
Do you have CloudFlare enabled on your website? this is most likely a duplicate of #8441

**Comment by sonugpc** [comment]
Yes , cloudflare is enabled

**Comment by youknowriad** [comment]
There are some workarounds in the mentioned issue above, I'm closing this as duplicate.
