### ISSUE TITLE
Inserter: optimize for mobile

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#859]
Current look:

![screen shot 2017-05-22 at 14 03 26](https://cloud.githubusercontent.com/assets/1204802/26307971/82afb4fe-3ef7-11e7-9380-5e96a60c9879.png)

Suggested improvements:

- Bigger touch targets
- Close button
- Perhaps full screen/modal experience like the sidebar

Edit: There's also a sweet mockup/animatic here, which we should look at for this https://github.com/WordPress/gutenberg/issues/44#issuecomment-282115026

**Comment by jwold** [comment]
I'm thinking a separate screen makes more sense in this instance. Some phones are larger and could handle a small popup well, but for many others it won't look good.

**Comment by jasmussen** [comment]
> I'm thinking a separate screen makes more sense in this instance. Some phones are larger and could handle a small popup well, but for many others it won't look good.

I agree. No reason not to make this a big modal on the small screens. The popout is already dismissed when you click the block inside, so should be enough to CSS this up.
