### ISSUE TITLE
IE11: posts page "Object doesn't support property or method remove"

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#8592]
Not sure if this part related to the "split button" in the posts page is going to stay when Gutenberg will be merged in core, however it uses a method not supported by IE11:

https://github.com/WordPress/gutenberg/blob/4fc46e769b24f4f4a16435ccf76d51ef39d8362e/gutenberg.php#L385

**Comment by youknowriad** [comment]
Looks like this is a duplicate of #8377
