### ISSUE TITLE
IE: Block icons appear at inconsistent sizes in the Block Settings sidebar.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8595]
**Describe the bug**

When using IE11, icons in the Block Settings appear at inconsistent sizes. Some (`Paragraph`) appear correctly sized. Others  appear a little smaller than they should (`Image`, `Heading`), and some appear really tiny (`Gallery`, `Cover Image`, `Quote`). 

<img width="280" alt="screen shot 2018-08-06 at 9 52 04 am" src="https://user-images.githubusercontent.com/1202812/43720698-d691205e-995e-11e8-8ef4-12f620bc1e84.png">
<img width="279" alt="screen shot 2018-08-06 at 9 51 54 am" src="https://user-images.githubusercontent.com/1202812/43720699-d6a3b30e-995e-11e8-889e-44edd7d86c74.png">
<img width="279" alt="screen shot 2018-08-06 at 9 51 37 am" src="https://user-images.githubusercontent.com/1202812/43720700-d6b1e488-995e-11e8-996b-3b5727f54a71.png">
<img width="279" alt="screen shot 2018-08-06 at 9 51 26 am" src="https://user-images.githubusercontent.com/1202812/43720701-d6be5a1a-995e-11e8-98b1-8431e880b3ec.png">
<img width="280" alt="screen shot 2018-08-06 at 9 51 00 am" src="https://user-images.githubusercontent.com/1202812/43720702-d6cb8316-995e-11e8-85e7-dda8e94c9a17.png">
<img width="280" alt="screen shot 2018-08-06 at 9 50 20 am" src="https://user-images.githubusercontent.com/1202812/43720703-d6e044cc-995e-11e8-93f0-472799baa30a.png">

_Note: I did not test every single block, so these are just a small set of examples._

**To Reproduce**

1. Use IE11
2. Insert a block
3. Compare the icon size in the Block Settings Sidebar.

**Tested in:**
Windows 7, IE 11.0.9600.17420
Gutenberg 3.4

**Comment by aduth** [comment]
I tested this today, May 31, 2019. The issue with sizing appears to have been resolved. However, there is frequently overlap of the placement of the icon relative its description.

![image](https://user-images.githubusercontent.com/1779930/58720568-86bc3c80-83a0-11e9-8694-e9e5749b9747.png)

I could close this and create a separate ticket, but since it's so closely related, I think we could repurpose this, as it's still related to sizing/placement of the block icon.

**Comment by paaljoachim** [comment]
What needs to be done here?

**Comment by paaljoachim** [comment]
I believe we are about to stop supporting IE. Which means this will likely be closed at a later time as a non fix.

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
