### ISSUE TITLE
Post preview is not working!

### ISSUE THREAD

**Issue by SiddharthKGiri** [WordPress/gutenberg#8597]
**Describe the bug**
Whenever I try to see the preview of any post it says "Please wait... Generating preview." but never able to generate the preview.

**To Reproduce**
1. Add Post.
2. Type Something.
3. Click 'Preview'.
4. See error.

**Screenshots**
![image](https://user-images.githubusercontent.com/42145814/43722241-70d0d698-99b2-11e8-9236-1faf223df5fc.png)

**Tested In**
 - OS: Windows 10.
 - Browser Chrome Version 68.0.3440.84 and FireFox Version 61.0.1

**Comment by abwdvm** [comment]
Do you CloudFlare?
http://www.ksstradio.com/2017/12/the-gutenberg-cloudflare-free-fix/

**Comment by SiddharthKGiri** [comment]
Yes! I am using CloudFlare.

And, Thank you, Now Preview is working.
