### ISSUE TITLE
wp.hooks: support the special `all` hook

### ISSUE THREAD

**Issue by adamsilverstein** [WordPress/gutenberg#8602]
To match feature parity with the current PHP hooks system in WordPress core, can we add support for an `all` action? 

A callback added to the 'all' hook fires on any/every hook - especially useful for debugging.

see:
https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/plugin.php#L183-L199
https://github.com/WordPress/wordpress-develop/blob/master/src/wp-includes/plugin.php#L437-L453

**Comment by aduth** [comment]
If it is primarily intended for debugging, then it might be worth exploring optimizations to avoid any impact in typical usage, e.g. monkey-patching `runHooks` when an `all` hook is added.

**Comment by adamsilverstein** [comment]
> e.g. monkey-patching runHooks when an all hook is added.

great suggestion, I am also concerned about the performance impact and this might be a way to address that.

**Comment by adamsilverstein** [comment]
WIP: https://github.com/WordPress/gutenberg/pull/12038
