### ISSUE TITLE
Plugin conflict: OTW Portfolio Manager

### ISSUE THREAD

**Issue by csbeck** [WordPress/gutenberg#8604]
I received this error when I opened Gutenberg for the first time in my WP admin.

Failed to load plugin url: https://www.beckerstudio.com/wp-content/plugins/otw-portfolio-manager/include/otw_components/otw_shortcode//js/langs/en.js'

**Expected behavior**
I didn't expect an error.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 67.0.3396.99 (Official Build) (64-bit)

**Additional context**
- Gutenberg: Version 3.4.0
- Portfolio Manager for WordPress: Version 2.3 | By OTWthemes.com

**Comment by csbeck** [comment]
Great. I'll let the other plugin author know about this conflict.

**Comment by youknowriad** [comment]
Any news on this front. Are you still having issues now that 5.0 is out?

Closing, let's reopen if there's any actionable item here.

**Comment by jcperezglez** [comment]
I am still having the same problem editing pages on:

Windows 10
Chrome version 71.0.3578.98 (Build oficial) (64 bits)
Gutenberg version 3.4.0
