### ISSUE TITLE
IE11: Vertical spacing of placeholder elements is broken in IE11. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8607]
**Describe the bug**

The content inside of placeholders is meant to be centered vertically. In most browsers, it is. For example: 

<img width="597" alt="screen shot 2018-08-06 at 12 14 19 pm" src="https://user-images.githubusercontent.com/1202812/43728177-440cb5a4-9972-11e8-8555-d8814e0e54f1.png">

In IE11 however, that spacing is broken, and all content is aligned to the top of the container: 

<img width="654" alt="screen shot 2018-08-06 at 12 09 18 pm" src="https://user-images.githubusercontent.com/1202812/43728201-548e4ece-9972-11e8-9948-5a7ed638a043.png">
<img width="641" alt="screen shot 2018-08-06 at 12 09 37 pm" src="https://user-images.githubusercontent.com/1202812/43728202-54c45168-9972-11e8-9d49-f3ba7cd1cbcf.png">
<img width="610" alt="screen shot 2018-08-06 at 12 09 56 pm" src="https://user-images.githubusercontent.com/1202812/43728203-54d523d0-9972-11e8-88a6-a51c97ebfb41.png">
<img width="607" alt="screen shot 2018-08-06 at 12 10 19 pm" src="https://user-images.githubusercontent.com/1202812/43728204-54e2bf72-9972-11e8-81c9-a0e0dc886d35.png">
<img width="603" alt="screen shot 2018-08-06 at 12 11 47 pm" src="https://user-images.githubusercontent.com/1202812/43728205-54f17b34-9972-11e8-9eae-72b29482246e.png">

**To Reproduce**

1. Use IE11
2. Add a block that uses a placeholder (The `Image` block for example)
3. Observe the alignment of the items inside the light gray container. 

**Tested in:**
Windows 7, IE 11.0.9600.17420
Gutenberg 3.4

**Comment by webmandesign** [comment]
This is actually related to #5791

Fix could be the same.

**Comment by aduth** [comment]
Related: The text does not wrap as expected and exceeds boundaries of the placeholder.

![image](https://user-images.githubusercontent.com/1779930/58730508-60a39600-83ba-11e9-82dc-4af308948b6f.png)

**Comment by talldan** [comment]
This still seems to be a little bit of an issue, though not quite as pronounced as before:
<img width="593" alt="Screenshot 2020-04-22 at 4 00 56 pm" src="https://user-images.githubusercontent.com/677833/79956308-8ba34680-84b2-11ea-985b-cbf79dd89324.png">

**Comment by paaljoachim** [comment]
What needs to be done here?

**Comment by youknowriad** [comment]
IE11 support is being dropped, context:

- https://make.wordpress.org/core/2021/03/04/discussion-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/03/25/discussion-summary-dropping-support-for-ie11/
- https://make.wordpress.org/core/2021/04/22/ie-11-support-phase-out-plan/ 

I'm closing this issue as it's not something we'll be investing in.
