### ISSUE TITLE
Photo Resizing

### ISSUE THREAD

**Issue by luxelookbook** [WordPress/gutenberg#8610]
1. When adding a new photo, the dragging tool can only resize down, not up. Also, if you accidentally go too far, it won't let you correct via the dragging tool. You have to go back to the side panel to image settings. Not a deal breaker, but less convenient and intuitive than to continue with the tool you were just using. 

2. With existing posts, when I click on an image in the block editor, the image settings under the side panel does not show up, nor does the dragging tool to resize the image. 

3. I'm not sure if anyone brought it up yet, but could there be a setting (beyond CSS) to have all images open in a new tab? I would assume more bloggers would prefer that toggle to remain checked across the board...but I could be wrong! 

Overall this looks like a great improvement. Thank you!

**Comment by youknowriad** [comment]
I'm not able to reproduce 1 and 2 and 3 is supported now.
