### ISSUE TITLE
Sidebar panels added by plugins may inherit styles from WordPress that should be reset

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#8616]
Noticed while working on #8554 /Cc @jasmussen 

Seems that sidebar panels added by plugin may inherit (depending on their implementation) styles from WordPress that could lead to unexpected results. 

For example, when using the `Ctrl + backtick` keyboard shortcut to navigate through the main regions, the focus style applied around the sidebar may look wrong:

![screen shot 2018-08-06 at 19 27 58](https://user-images.githubusercontent.com/1682452/43733587-7dc03b5c-99b5-11e8-8764-d41881e05c14.png)

See the last sidebar panel that overlaps the focus style. This specific panel uses some markup from the WordPress meta boxes. After a quick investigation, seems two `position: relative` CSS declarations are responsible for this:

from Gutenberg:
```
.edit-post-meta-boxes-area {
    position: relative;
}
```

from WordPress

```
.postbox {
    position: relative;
    ...
```

Potentially, there could be other inherited CSS rules that could produce unexpected results. Soem special care should be taken in overriding these rules for the panels in the sidebar.

**Comment by youknowriad** [comment]
I don't have any specific context to add at first sight. I don't recall any particular reason for the relative positioning.

**Comment by afercia** [comment]
Worth noting this happens only in combination with https://github.com/WordPress/gutenberg/pull/8554 because it uses `outline` instead of `box-shadow`. An inset `box-shadow` is drawn on top of any other children, while the outline behaves differently.

I've just noticed that hovering the "Revisions" panels produces the same effect:

![sidebar panel background](https://user-images.githubusercontent.com/1682452/43791281-750d3a44-9a75-11e8-988f-e41ffeca013e.png)

This happens because the "Revisions" panels (specifically the link icon-button within it) gets a white background _only when hovered_. So I've checked the panel added by the plugin and it does have a white background (set on the `.postbox` div). All the other panels don't have a background.

Seems the easier fix would be resetting these backgrounds?

**Comment by jasmussen** [comment]
Hmm that's interesting — simply removing the background there does seem to fix the issue. But I wonder why that is? Would any other CSS properties cause it to shift upwards like that?

**Comment by afercia** [comment]
Well the background is set on a children of the element with outline, and the children has a higher stack index. That is. Box-shadow [works differently](https://www.w3.org/TR/css-backgrounds-3/#shadow-layers).

**Comment by jasmussen** [comment]
Right, but I'm wondering what makes the `background` property elevate this element. It also has `border`s and lots of other things, what makes those not elevate it?

**Comment by nerrad** [comment]
@afercia is this issue still present? I'm don't seen the hover issue with the Revisions panel anymore.

**Comment by afercia** [comment]
@nerrad can't reproduce as well. I think this was fixed as a side effect of the navigate regions focus style in #8554.
