### ISSUE TITLE
Columns block collapses in IE11. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8617]
**Describe the bug**

In IE11, any blocks underneath the columns block are moved up and overlap the columns completely. This does not occur on the front end.

**To Reproduce**

1. Use IE11
2. Add a Columns Block
3. Add content to the Columns block
4. Add content below the columns block. 

 (Note that this may be difficult because of the error above) Alternatively:

1. Use a non-IE11 browser
2. Add a columns block.
3. Add content to the Columns block.
4. Add content below the columns block.
5. Open that same post, using IE11. 

**Screenshots**

Here's how one of my tests looks in Safari:

<img width="669" alt="screen shot 2018-08-06 at 2 18 18 pm" src="https://user-images.githubusercontent.com/1202812/43733759-b0848160-9983-11e8-8576-844575af6740.png">

And here is that same content in IE11:

<img width="657" alt="screen shot 2018-08-06 at 2 18 38 pm" src="https://user-images.githubusercontent.com/1202812/43733776-bbd3201c-9983-11e8-80b2-83af87c65b37.png">

**Tested in:**
Windows 7, IE 11.0.9600.17420
Gutenberg 3.4

**Comment by mtias** [comment]
@kjellr is this still an issue?

**Comment by kjellr** [comment]
I'm not seeing any more overlap. 👍 Will close for now.

![screen shot 2018-11-12 at 11 16 53 am](https://user-images.githubusercontent.com/1202812/48360136-8bbbd780-e66c-11e8-8156-265c8cfe94a4.png)

**Comment by jk-propeller** [comment]
This is still an Issue:

![Bildschirmfoto 2019-10-10 um 13 33 09](https://user-images.githubusercontent.com/56393143/66565539-07ffb900-eb63-11e9-8c9b-04a4c59c7474.png)
![Bildschirmfoto 2019-10-10 um 13 35 34](https://user-images.githubusercontent.com/56393143/66565540-07ffb900-eb63-11e9-851f-d9f5564b8b7c.png)

IE: 11.0.9600.19431
Windows 7
WordPress: 5.2.3
