### ISSUE TITLE
Use ::before (pseudo elements) instead of :before (pseudo classes)

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#8618]
We should be using `::before` across the project instead of `:before`; browser support is there and it's more semantically correct. See: 
https://github.com/WordPress/gutenberg/pull/8588#discussion_r207855059

We should probably add a lint warning to the project as well so future devs don't use `:before` instead of `::before` by mistake, once this is closed.

**Comment by tomjn** [comment]
Should we do the same for `:after` vs `::after`?

**Comment by tofumatt** [comment]
Yes. 😄

**Comment by ntwb** [comment]
`::after` is taken care of in #8647
