### ISSUE TITLE
Inserter: + icon overlaps on mobile

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8621]
On smaller screens (< 600px), the + icon is right-aligned, causing it to overlap with your most-frequently-used blocks:

<img width="342" alt="screenshot 2018-08-06 20 08 37" src="https://user-images.githubusercontent.com/376315/43736257-ded0d2ea-99b4-11e8-8648-4105803ab0b1.png">

<img width="320" src="https://user-images.githubusercontent.com/376315/43736288-fbc9337e-99b4-11e8-8d89-7453faff6347.jpeg">

**Comment by mtias** [comment]
Currently block shortcuts are not displayed:
![image](https://user-images.githubusercontent.com/548849/48325374-03114d00-e614-11e8-8586-31ed3136a2a5.png)
