### ISSUE TITLE
Unable to add text to the Table block in IE11. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8622]
**Describe the bug**

In IE11, the table block appears normally, but I am unable to enter text inside of it. 

In other browsers, when I add the table block, the focus is automatically shifted to the first cell. This does not happen in IE 11. I'm also unable to click on individual cells to enter content: the cursor does not turn into a text cursor when it hovers over the cells, and clicking has no effect. 

No errors are shown in the console. 

**To Reproduce**

1. Use IE11
2. Add a table block
3. Attempt to enter text into any of the cells. 

**Tested in**
Windows 7, IE 11.0.9600.19080
Gutenberg 3.4

**Comment by nerrad** [comment]
This probably needs retested to see if it's still an issue.

**Comment by kjellr** [comment]
I just gave it a test, and I'm unable to reproduce. 🎉 

I'll close for now, but if this pops up again in the future, we can re-open.
