### ISSUE TITLE
Add inline <code> tag to formattingControls on RichText API

### ISSUE THREAD

**Issue by arnolem** [WordPress/gutenberg#8626]
**Is your feature request related to a problem? Please describe.**
On technical blogs (like CatsWhoCode, SmashingMagazine, ...), the html CODE tag is often used in "inline" to put forward keyword language, a command, etc.

**Describe the solution you'd like**
Can add a "code" button

**Describe alternatives you've considered**
Add it via the RichText API, so you can easily add the code tag in a paragraph

Thanks !

**Comment by tomjn** [comment]
I'd find this very handy too, for reference though:

 - You can use a backtick markdown style and it will auto-convert to a code tag
 - The classic editor doesn't have a code tag button, I've always had a plugin that adds it, so this would be a new feature if it reached gutenberg

**Comment by iseulde** [comment]
We've added the backtick (wrap some text with `` ` ``) shortcut, and a keyboard shortcut (access+x). This is the same what the old editor has. A button remains plugin territory.
