### ISSUE TITLE
How did I lose the Inline Images Block and how do I get it back?

### ISSUE THREAD

**Issue by KPeregrinePgh** [WordPress/gutenberg#8629]
Somehow I lost the Inline Elements [Inline Image] Block format as a selection in Gutenberg.  Perhaps I was trying to move it down in the list.  Anyway, it's gone.
How do I get it back?  I want to use an inline image.

**Comment by youknowriad** [comment]
Inline images appear in the inserter when you're in a RichText selection (when the caret is inside a paragraph, a heading etc...)

**Comment by KPeregrinePgh** [comment]
Aha!  Thanks. Now I see it.
