### ISSUE TITLE
Inserting new block above image

### ISSUE THREAD

**Issue by weavertheme** [WordPress/gutenberg#8632]
**Describe the bug**
Gutenberg 3.4.0
Firefox, Chrome
Theme: Gutenberg-starter-theme-master

I'm having problems inserting a new block above an image using the circle-+ in the block outline when the Settings: Fix Toolbar to Top is NOT checked. It seems to always fail on Firefox, but less so on Chrome, where it fails consistently only if the image is the last block.

**To Reproduce**

It may be a bit difficult to reproduce, but I'll try to explain the steps.

1. Try this with Firefox first. Will repeat in Chrome. Check the Settings: Fix Toolbar to Top option
2. Add some images - like a test of standard, wide, and full. Maybe mix in some other blocks to help see what is going on.
3. Make the LAST block an image in either Wide or Full width.
4 If you hover on the last block (the wide image), you get the Add Block + in the middle, and can add a block above.
5. Disable the Settings: Fix Tool To Top.
6. Refresh the edit page, just to be sure things are "synced".
7. Select some block other than the last image. The toolbar should pop up.
8. THE PROBLEM: Now move to the last image block, and click once. This should pop up the toolbar. It is now impossible to get the Circle-+ add a block on the blocks boundary. This seems to happen for any image.
9 2nd PROBLEM -consistently for last image, sometimes others. Set up as before - click on some block to open the pop-up tool bar. Now just hover the LAST image until the Circle-+ is displayed. If you click that now, you'll get the pop-up tool bar, and not a new block inserted above.

This procedure seems to fail consistently with not Fix Toolbar to Top, while things work as expeced with Fixed to Top set. And Full/Wide makes is fail more consistently, but I can get it to fail with normal images, too.

**Expected behavior**

**Screenshots**

**Comment by talldan** [comment]
Hi @weavertheme - new options for inserting blocks before and after have recently been added to the block settings menu (along with keyboard shortcuts). This PR has the detail - https://github.com/WordPress/gutenberg/pull/8909. Does that suffice as a fix for your issue?

**Comment by ellatrix** [comment]
Currently, it doesn't seem possible at all to insert a block above a selected block. Instead you could select the previous block or use the buttons in the menu as suggested above.
