### ISSUE TITLE
Edit slug?

### ISSUE THREAD

**Issue by cclambie** [WordPress/gutenberg#8634]
**Describe the bug**
This is probably not a Gutenberg bug, but it did bring up this issue of editing the slug.
I use Yoast SEO and edited the slug using that plugin tool (as Gutenberg didn't have an obvious place to do it?) The slug did not save, and the post had the mydomin.com/?p=xx address. 

**To Reproduce**
1. Go to 'new post'
2. Add some content
3. Edit the slug with Yoast SEO plugin widget (as no option - feature request?)
4. Edit the time to publish to a future time, for me is was 7am next day
5. Press 'Schedule'
6. The Post URL remains the domain.com/?p=post_id

**Expected behavior**
A. Ability to edit the slug (without using Yoast SEO plugin); and/or
B. Yoast plugin hook to edit the slug to work with the plugin/ editor

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67.0.3396.99

**Additional context**
- Gutenberg Version 3.4.0

**Comment by youknowriad** [comment]
There's is an option to edit the slug. It appears when you click the title of the post. I'm closing for now, let me know how this works for you. Thanks.

**Comment by cclambie** [comment]
Thanks @youknowriad I see it now, that is not intuitive at all, but fair enough, I guess users could learn to find it there.

**Comment by youknowriad** [comment]
Yes, it needs some iteration and there are open issues considering updates. Thanks for the feedback.

**Comment by JasonPokines** [comment]
Just wanted to +1 on this issue. I think where the slug editing takes place is fine, but hover/click-in visibility is a poor choice.

Glad Google found this thread so I could find the answer!

**Comment by bahia0019** [comment]
This is a really poor experience. I looked all over the place for this. Clicked, poked, and dug for 3 minutes before googling. This needs to be fixed.
I'd suggest an option at the Document level. Seems most appropriate.

<img width="479" alt="screen shot 2018-09-20 at 1 14 35 am" src="https://user-images.githubusercontent.com/1586037/45805148-dde70a80-bc72-11e8-9884-579a6ffb6d3a.png">

**Comment by itssri** [comment]
> This is a really poor experience. I looked all over the place for this. Clicked, poked, and dug for 3 minutes before googling. This needs to be fixed.
> I'd suggest an option at the Document level. Seems most appropriate.
> 
> <img alt="screen shot 2018-09-20 at 1 14 35 am" width="479" src="https://user-images.githubusercontent.com/1586037/45805148-dde70a80-bc72-11e8-9884-579a6ffb6d3a.png">

Totally agree. It is the aim to make it simpler, isn't it?

**Comment by pinksharpii** [comment]
Also coming here to say that it's not intuitive and thank god for Google bringing me here. Additionally, if you have a long prefix like we do four our blog, the box to place the permalink is SUUUUPER tiny. Not a good UI.
<img width="648" alt="screen shot 2018-11-09 at 1 42 35 pm" src="https://user-images.githubusercontent.com/3431241/48284568-5f624a00-e425-11e8-9543-4464687a3a9c.png">

**Comment by Hube2** [comment]
Can someone clue me in here, I'm working with a CPT and I've been looking for this mysterious way to edit the slug for a very long time. No amount of clicking or poking around seems to reveal it to me.

**Comment by stormwild** [comment]
To view and edit the slug, you need to be in the Code Editor view. 

- Click on the Show more tools button on the upper right corner of the toolbar.

![image](https://user-images.githubusercontent.com/657249/50665941-9603ad80-0fed-11e9-8118-fdebe0c7ca95.png)

- Click on the title and the slug/permalink will appear above.

![image](https://user-images.githubusercontent.com/657249/50665957-a3b93300-0fed-11e9-81d2-11ba43a0ffba.png)
