### ISSUE TITLE
Schedule button text typo/ issue

### ISSUE THREAD

**Issue by cclambie** [WordPress/gutenberg#8635]
**Describe the bug**
Seems to be a typo or code issue with the schedule feature of the editor.

**To Reproduce**
1. Go to 'new post'
2. Add some content
3. Edit the time to publish to a future time, for me is was 7am next day
4. Press 'Schedule'
5. The scheduling button appears to have a typo on it, as per the screenshot below `Scheduling&hellip;`

**Expected behavior**
I think it should just say "scheduling" but maybe something else too?

**Screenshot**
![gutenberg_scheduling_button](https://user-images.githubusercontent.com/877921/43748933-5eb71b92-9a35-11e8-8edc-546b47c68ccc.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67.0.3396.99

**Additional context**
- Gutenberg Version 3.4.0

**Comment by swissspidy** [comment]
Which language is set in your WordPress profile / WordPress settings? The default English (US) or perhaps English (GB)  or something?

Technically it's not a _typo_, but just the HTML entity for `…`. So it should read `Scheduling…`.

**Comment by cclambie** [comment]
@youknowriad I haven't got any plugins that effect the UI I don't think - happy to take your suggestion how to show you a list (I installed a plugin "plugin list" but it is broken)

@swissspidy I use "English (Australia)" as language - so this might be the issue yes - I get it is not a "typo" as such, but some sort of error.

Do you have some suggestions for creating a file for you to look at with plugins and versions etc.  I know of some plugins I have used in the past that have a "download this for support" type function.

**Comment by swissspidy** [comment]
@cclambie Good to know! And thanks for offering to help :-)

As far as I can see, this is a translation issue.

The original string is `Scheduling…`, but it was translated to `Scheduling&hellip;` for English (Australia) a while ago.

The translations all happen on WordPress.org where anyone with a WordPress.org account can suggest new translations for a plugin like Gutenberg. Which I just did! See See: https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/en-au/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=5853054&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

Now someone needs to approve my translation. Perhaps @ntwb or @pento :-)

As soon as that happens, WordPress.org will update the translation files and you should be able to update these via Dashboard -> Updates on your WordPress site. It might take ~30 minutes for that process to complete. You can click on the "Check Again" button on that page to make sure the site gets the newest translation

**Comment by pento** [comment]
Noice, approved!
