### ISSUE TITLE
Issue with columns when last block is paragraph

### ISSUE THREAD

**Issue by HardeepAsrani** [WordPress/gutenberg#8636]
**Describe the bug**
I was working on a custom block, with a Pricing Area (parent block), which can only have Pricing Block (child block) which is also a column block which uses default Core blocks, such as Heading and Paragraph.

If the last element is a paragraph, you can't add another block.

You can find more info here in this video: https://drive.google.com/file/d/1y0MfQtEM16dlTUhOgsb0wC26G1VLyCm5/view?usp=sharing

It's the latest version from WPOrg, running on FF on Mac.

**Comment by nerrad** [comment]
@HardeepAsrani sorry for the length of time between your report and any followup here.  Was this resolved for you?  Do you still experience the same issue as originally reported?

**Comment by HardeepAsrani** [comment]
I've actually forgotten the issue and seems like I also mistakenly deleted the video from Google Drive just last week.

**Comment by nerrad** [comment]
Okay, I'll close this for now, if you have any additional information, please do post it here and the issue will be re-opened if necessary.
