### ISSUE TITLE
Custom excerpt code that works before Gutenberg but gives an error message after GB is activated.

### ISSUE THREAD

**Issue by paaljoachim** [WordPress/gutenberg#8644]
**Describe the bug**

The following custom excerpt code:

```
// Blog page Excerpt 
// https://community.getbeans.io/discussion/how-to-show-post-excerpts/

add_filter( 'the_content', 'beans_child_modify_post_content' );
function beans_child_modify_post_content( $content ) {
// Stop here if we are on a single view.
if ( is_singular() || is_admin() ) {
return $content;
}
// Return the excerpt() if it exists other truncate.
if ( has_excerpt() )
$content = '<p>' . get_the_excerpt() . '</p>';
else
$content = '<p>' . wp_trim_words( get_the_content(), 40, '...' ) . '</p>';

// Return content and readmore.
return $content . '<p>' . beans_post_more_link() . '</p>';
}
```
The above excerpt code works when Gutenberg is not installed.
Activating Gutenberg and going to a post shows an Auto save error.

POST https://religionskritikk-aug.dev.cc/wp-json/wp/v2/posts/353/autosaves 400 (Bad Request)
(anonymous) @ index.js?ver=1533566665:1
t @ index.js?ver=1533566665:1
x @ index.js?ver=1533566665:1
t @ index.js?ver=1533566665:1
y @ index.js?ver=1533566665:1
t @ index.js?ver=1533566665:1
(anonymous) @ index.js?ver=1533566665:1
t @ index.js?ver=1533566665:1
(anonymous) @ index.js?ver=1533566665:1
y @ index.js?ver=1533566665:1
(anonymous) @ index.js?ver=1533566665:1
t @ index.js?ver=1533566665:1
(anonymous) @ index.js?ver=1533566665:1
t @ index.js?ver=1533566665:1
b @ index.js?ver=1533566665:1
(anonymous) @ index.js?ver=1533566666:12
k @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
e.(anonymous function) @ index.js?ver=1533566666:12
o @ index.js?ver=1533566666:12
a @ index.js?ver=1533566666:12
Promise.then (async)
o @ index.js?ver=1533566666:12
a @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
t @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
REQUEST_POST_UPDATE @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:1
value @ index.js?ver=1533566666:1
(anonymous) @ index.js?ver=1533566666:12
setTimeout (async)
value @ index.js?ver=1533566666:12
value @ index.js?ver=1533566666:12
jc @ react-dom.min.82e21c65.js:134
gc @ react-dom.min.82e21c65.js:127
vb @ react-dom.min.82e21c65.js:126
ub @ react-dom.min.82e21c65.js:126
zd @ react-dom.min.82e21c65.js:124
ra @ react-dom.min.82e21c65.js:123
enqueueSetState @ react-dom.min.82e21c65.js:189
q.setState @ react.min.ab6b06d4.js:18
(anonymous) @ index.js?ver=1533566666:1
(anonymous) @ index.js?ver=1533566666:1
(anonymous) @ index.js?ver=1533566666:1
d @ index.js?ver=1533566666:1
(anonymous) @ index.js?ver=1533566666:12
dispatch @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:1
(anonymous) @ index.js?ver=1533566666:1
d @ index.js?ver=1533566666:1
(anonymous) @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
dispatch @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
k @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
e.(anonymous function) @ index.js?ver=1533566666:12
o @ index.js?ver=1533566666:12
s @ index.js?ver=1533566666:12
Promise.then (async)
o @ index.js?ver=1533566666:12
a @ index.js?ver=1533566666:12
Promise.then (async)
o @ index.js?ver=1533566666:12
a @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
t @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
REQUEST_POST_UPDATE @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:12
(anonymous) @ index.js?ver=1533566666:1
value @ index.js?ver=1533566666:1
onClick @ index.js?ver=1533566666:12
Sh @ react-dom.min.82e21c65.js:143
invokeGuardedCallback @ react-dom.min.82e21c65.js:143
invokeGuardedCallbackAndCatchFirstError @ react-dom.min.82e21c65.js:143
Wd @ react-dom.min.82e21c65.js:14
Bg @ react-dom.min.82e21c65.js:145
Ug @ react-dom.min.82e21c65.js:146
Va @ react-dom.min.82e21c65.js:15
yc @ react-dom.min.82e21c65.js:16
Yd @ react-dom.min.82e21c65.js:16
rh @ react-dom.min.82e21c65.js:40
ug @ react-dom.min.82e21c65.js:136
ue @ react-dom.min.82e21c65.js:25
Nb @ react-dom.min.82e21c65.js:41
wg @ react-dom.min.82e21c65.js:137
Ze @ react-dom.min.82e21c65.js:41

![screen shot 2018-08-07 at 08 37 16](https://user-images.githubusercontent.com/5323259/43758658-1eea8a16-9a1d-11e8-8067-da84b5df782f.png)

Clicking update of a post/page of another post that have yet to auto save. An Updating failed message shows up and a lot of errors also show up in the Console Network section:

![screen shot 2018-08-07 at 08 32 29](https://user-images.githubusercontent.com/5323259/43758468-7bfc1bf8-9a1c-11e8-85d8-29560f2ca8e6.png)

lock validation: Block validation failed for `core/paragraph` (Object).

Block validation: Expected token of type `StartTag` (Object), instead saw `Chars` (Object).
(anonymous) @ index.js?ver=1533566665:2

Expected:
<p></p>
Actual:
Some info here. More text....
(anonymous) @ index.js?ver=1533566665:2

--

**To Reproduce**
I installed the beans framework theme. https://www.getbeans.io/ and then the child theme: https://www.getbeans.io/documentation/starter-child-theme/ then added the excerpt which I posted above. Works when Gutenberg is not active. Then activated Gutenberg and went to a post. Noticed the updating failed message.

**Expected behavior**
That it just works the same as before Gutenberg was activated.

**Desktop (please complete the following information):**
 - OS: OSX10.13.6
 - Chrome. Local site in Desktop Server.
-  I installed Gutenberg through the callout.

**Comment by youknowriad** [comment]
Here's the correct error here.

<img width="631" alt="screen shot 2018-08-07 at 09 03 13" src="https://user-images.githubusercontent.com/272444/43762807-dea5da92-9a20-11e8-932e-377ea9ac6de7.png">

The issue is that these beans theme functions are not working on API endpoints. I'm not certain this is a Gutenberg issue. The difference is that the classic editor doesn't call the REST API. 

Several options:

 - The Beans theme should make sure these functions are available in REST API endpoints?
 - Update your snippet to check for `beans_post_more_link` existence before calling it.

**Comment by youknowriad** [comment]
You can also change this check `if ( is_singular() || is_admin() ) {
return $content;
}`

to check if your in a REST endpoint as well and return the content as is in that case.
