### ISSUE TITLE
Hi, how to change with drag column width?

### ISSUE THREAD

**Issue by paolobortolotti** [WordPress/gutenberg#8649]
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by youknowriad** [comment]
You probably can't. Let's consolidate the drag handle discussions in #7114 to improve it and avoid duplicate issues. Thanks.
