### ISSUE TITLE
cannot install gutenberg

### ISSUE THREAD

**Issue by benjaminfauchald** [WordPress/gutenberg#8652]
**Describe the bug**

**To Reproduce**
on new site creation in multisite I tried to install the new gutenberg editor.
First int seemed to install fine, but it said access denied.
After a refresh I tried to install again and then it said "Installation failed, destination folder already exists"

**Expected behavior**
Press install and it installs...

**Screenshots**

![ublf6zvw](https://user-images.githubusercontent.com/8008370/43774926-06a2a8aa-9a75-11e8-95e1-d29dad9af08e.png)

**Desktop (please complete the following information):**
 - OS: os x
 - Browser chrome

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by benjaminfauchald** [comment]
after I gave this user access to this site in multisite it works fine, however that should be the error.

**Comment by youknowriad** [comment]
There's nothing specific about the Gutenberg installation process. It works like any other plugin. You probably had permission issues or something like that.

**Comment by Ipstenu** [comment]
That sounds like a misuse of Multisite. You don’t install plugins per site, you activate them per site. If Gutenberg was already network installed but not active, that would cause this.

**Comment by youknowriad** [comment]
I'm closing per @Ipstenu's comment. Thanks for the report

**Comment by benjaminfauchald** [comment]
![unspecified-1](https://user-images.githubusercontent.com/8008370/43783893-03942ea0-9a8d-11e8-9501-a44064ad788c.png)
![unspecified-3](https://user-images.githubusercontent.com/8008370/43783896-05701db0-9a8d-11e8-94ca-b2f71efb2e85.png)

Thats not it. This works perfectly now and it gave an error message before.
