### ISSUE TITLE
SVG Images not displaying in visual editor

### ISSUE THREAD

**Issue by vfontjr** [WordPress/gutenberg#8658]
**Describe the bug**
After adding a SVG image to a post or page, only the thumbnail is visible while the image block is active(selected). Move to any another block and the image disappears.

**To Reproduce**
1. Add an SVG image to a post or page
2. Click in any other block to make it active

**Expected behavior**
SVG images should remain visible just like any bitmap image.

**Comment by bkjproductions** [comment]
I am able to see a SVG when it is in the Gutenberg editor, and it shows the dimensions, which is great. However, there are two blue dots that appear on the image. If the blue dot is supposed to be a "control" handle for the image I would expect to see only one blue dot, but I do not know what the second blue dot is for.

Related: When looking in the Media Library, the SVG does not show, nor does it have any dimensions.  It shows just the default icon for an item in the media library.

**Comment by swinggraphics** [comment]
Uploading SVGs is blocked in WordPress by default. Gutenberg allows you to drag an SVG into a post and will display it, but the image will not be added to the media library, and after you update and reload the page, the SVG will be gone, leaving an empty image block.

**Comment by ellatrix** [comment]
I've added SVGs manually to WordPress before (normally you cannot upload, but there's plugins that allow you to do it) and the SVGs display correctly.

Please reopen if there is still an issue, with extra information on how you inserted the SVG, and ideally the SVG itself so the issue can be reproduced. Thanks!

**Comment by swinggraphics** [comment]
If Gutenberg isn't going to allow an SVG to be uploaded, it should show an error message and not display the image in the editor.

**Comment by ellatrix** [comment]
@swinggraphics How are you uploading the image? I cannot do it, I get an error.

**Comment by florianbrinkmann** [comment]
I have the same issue with SVGs being hidden in the image block, when no dimensions are set. I use the Safe SVG plugin for the upload.
