### ISSUE TITLE
Blocks: Splitting paragraph inside inline code block transfers to new block

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8664]
**Describe the bug**

With links, if the user is inside the link inline boundary and presses enter, the link formatting is not applied to the new paragraph. For code blocks, however, the formatting persists. We should be consistent in not applying the inline formatting.

**To Reproduce**

1. Navigate to Posts > Add New
2. Add a new paragraph
3. Type "\`", some text, "\`" to create an inline code boundary
3. Press ArrowLeft
4. Press Enter
5. Observe new paragraph with empty inline code tag.

**Expected behavior**

New paragraph is added, with no formatting.

**Comment by aduth** [comment]
The difference in behavior can be attributed to this default behavior in TinyMCE, which removes empty links (among others), but not inline code tags:

https://github.com/tinymce/tinymce/blob/9f8cbf3a9589f0e67027e81975b72c37ff680456/src/core/main/ts/api/html/Schema.ts#L743-L748

**Comment by iseulde** [comment]
This should be fixed with the new internal RichText state. Tested with `master` and seems fine.
