### ISSUE TITLE
Blocks: Empty code tag impossible to remove

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8665]
**Describe the bug**

In a paragraph block consisting of the following HTML, it is not possible to remove the code tag through the Visual editor:

```html
<p><code></code></p>
```

It is possible to get into this state following instructions from #8664.

**To Reproduce**

1. Repeat steps from #8664 
2. Try to remove empty code tag

**Expected behavior**

It should be possible to remove the code tag, by backspace or delete.

**Comment by iseulde** [comment]
This should be fixed with the new internal RichText state. Tested with `master` and seems fine. When the `code` tag is empty, the value will be empty.
