### ISSUE TITLE
Wonky Editing Screen Layout

### ISSUE THREAD

**Issue by downhillmedia** [WordPress/gutenberg#8667]
**Describe the bug**
Editor screen layout wonky. Some elements of the page in upper left are partially hidden behind the left hand menu (Dashboard, Posts, Pages, etc.). Top of the left menu is expanded by the height of those elements. 

**To Reproduce**
Simply try to edit a post or page.

**Expected behavior**
To be able to see/use all elements of the editing screen.

**Screenshots**
[http://dine.downhillmedia.com/imgs/gutenberg-mess.jpg](url)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox, Chrome, Opera
 - Version: 61.0.1 64-bit, 68.0.3440.84 (Official Build) (64-bit), 54.0.2952.71 64-bit

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Gutenberg Plugin 3.4.0
WordPress 4.9.8
Thesis Theme
Flex Skin

**Comment by earnjam** [comment]
Those fields appear to be from another plugin. I see WooCommerce is active. Do you have any other plugins active?

**Comment by downhillmedia** [comment]
Good thought. Apparently, caused by a plugin I was testing called WP Family Tree.

 

_______________________________

Michael Lewis

Downhill Media

 <mailto:michael@downhillmedia.com> michael@downhillmedia.com

**Comment by earnjam** [comment]
Thanks for following up. I'm gonna close this as invalid/issue outside of Gutenberg.
