### ISSUE TITLE
Framework: redirecting to wp-admin URL

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#867]
In some places, we need to build and redirect to wp-admin URLs. In order to achieve this, we'll have to provide the `baseUrl` of `wp-admin` to JS. 

We're already building URLs to the gutenberg editor by parsing the current URL and appending a query string but this not enough to navigate to other wp-admin pages. (see https://github.com/WordPress/gutenberg/pull/862#issuecomment-303108269) 

How do you think we should do this? append the base URL to the settings endpoint? provide a global JS variable while initializing the Editor?

**Comment by aduth** [comment]
There are some filters run server-side that will be problematic to recreate (notably `admin_url`), to the point that we may simply need to ignore those effects.

See: https://github.com/WordPress/WordPress/blob/21b1135/wp-includes/link-template.php#L3105-L3133

For a solution, I like the global containing `siteurl` to which we could append, or maybe even just a relative link (e.g. `edit.php?...`). This is what's done for the admin sidebar menu navigation ([source](https://github.com/WordPress/WordPress/blob/master/wp-admin/menu.php)).

**Comment by youknowriad** [comment]
I'm closing this for now, It doesn't seem so useful after all. The current approach works well. This could be a concern later once we move other parts of WordPress to frontend.
