### ISSUE TITLE
PCRE infinite recursion segmentation fault after activating gutenberg plugin

### ISSUE THREAD

**Issue by michaelkrieger** [WordPress/gutenberg#8671]
## Issue Overview
Upon activating Gutenberg, going to any page which includes the editor causes PHP5 to segmentation fault due to PCRE doing infinite recursion.

## Steps to Reproduce (for bugs)
Install Gutenberg and activate.  Deactivating solves the problem.

## Expected Behavior
It should work

## Current Behavior
Segmentation Fault due to looping PCRE.
Backtrace [myfile2.txt.gz](https://github.com/WordPress/gutenberg/files/2267416/myfile2.txt.gz)
I cut off the repeating PCREs saving megabytes of files.  Eventually it exhausts the stack and PHP segmentation faults.

The call seems to be around #16342.

**Comment by danielbachhuber** [comment]
Hi @michaelkrieger,

Thanks for the report. Some follow-up questions to help us debug further:

1. Do you have other plugins active at the same time? If so, can you deactivate them to see if one might be the cause of the problem?
2. Which specific PHP version are you running?

**Comment by danielbachhuber** [comment]
Related #8244
#4852 could also be related

**Comment by michaelkrieger** [comment]
1. I have found 'Subresource Integrity (SRI) Manager' to be a plugin which, if disabled, allows it to work.  It is reproducable if i re-enable it/disable it.  All other plugins had no effect on the operation. The plugin page is at https://wordpress.org/plugins/wp-sri/ .

2. PHP 5.6.36 (Debian)

While of course it's easy to blame the plugin, the introduction of Gutenberg shouldn't break a plugin which doesn't use the editor at all- especially to the point of a PCRE segmentation fault.

**Comment by danielbachhuber** [comment]
> I have found 'Subresource Integrity (SRI) Manager' to be a plugin which, if disabled, allows it to work.

Great, thanks for tracking it down.

> While of course it's easy to blame the plugin, the introduction of Gutenberg shouldn't break a plugin which doesn't use the editor at all- especially to the point of a PCRE segmentation fault.

I agree. I asked solely so we could diagnose the source of the problem. We'll make sure this is addressed with #8244
