### ISSUE TITLE
JUSTIFICATION

### ISSUE THREAD

**Issue by parnanet** [WordPress/gutenberg#8673]
In the past, it was a BIG mistake to remove text justification from WordPress.  

The problem was solved installing a plugin.   Now,  with the new editor, the plugin lost its effect.   

What make developers think justification is not the nicest way to format a text ????

Please, guys ....  make sense.

**Comment by earnjam** [comment]
Thanks for the feedback @parnanet. You can read more about the original decision to remove that button from TinyMCE on [core trac ticket #39326](8450). My understanding was that justified alignment had varying browser implementations, caused lots of theme rendering issues and was bad for accessibility. 

As far as Gutenberg, we're tracking this in #8433 and #8450, so I'm going to close this as a duplicate.
