### ISSUE TITLE
List Block: Increase/Decrease Indent icons should be switched when using RTL language.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8674]
**Describe the bug**

When using a LTR language, the arrows on the increase/decrease indent buttons on the List block indicate the direction the text will move when you press the button:

![list-ltr](https://user-images.githubusercontent.com/1202812/43794208-90d57784-9a4b-11e8-8dde-46d4a8c31351.gif)

When you switch to a RTL language, the arrows do not point in the direction that the text will move:

![list-rtl](https://user-images.githubusercontent.com/1202812/43794632-e4d50f88-9a4c-11e8-804b-8276b030dc8c.gif)

I'd argue that these icons should be swapped when a RTL language is being used, so that the arrows properly represent the direction text will be moving. 

**To Reproduce**

1. Switch to a RTL language (Arabic, Hebrew, etc)
2. Insert a list block with at least two items.
3. Toggle the indent, using the toolbar buttons.

**Tested in**

Mac OS 10.13.6, Safari 11.1.2
Mac OS 10.13.6, Chrome 67.0.3396.99

**Comment by draganescu** [comment]
As an example of prior art, Google Docs has slightly different icons:

- English
<img width="197" alt="en" src="https://user-images.githubusercontent.com/107534/79744702-822da900-830f-11ea-947e-8533bb108115.png">

- Arabic
<img width="76" alt="ar" src="https://user-images.githubusercontent.com/107534/79744714-8659c680-830f-11ea-93f5-ca98e3013235.png">

**Comment by Mamaduka** [comment]
This should be fixed after recent refactoring #39773.
