### ISSUE TITLE
Writing Flow: Extreme latency adding link on text that once had code tag

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8675]
**Describe the bug**

(Note: Details are rough as I report this merely with the reliable steps to reproduce, debugging will surface additional insights)

**To Reproduce**

1. Navigate to Posts > Add New
2. Click into the "Write your story" prompt
3. Insert inline code tag by typing "\`", some text, and "\`"
4. Press Enter
5. Press Backspace
6. Press ArrowRight to escape out of the inline code boundary
7. Move your mouse to reactivate the block toolbar
8. Press the Add Link button in the toolbar
9. Observe extreme lagginess in trying to add a link

**Desktop (please complete the following information):**

 - OS: macOS High Sierra 10.13.6 (17G65)
 - Browser: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by aduth** [comment]
Easier to reproduce:

1. Add a paragraph with some text
2. Press Enter twice
3. Press Backspace twice
4. Attempt to apply link to the first paragraph text

**Comment by youknowriad** [comment]
This is really a weird bug, not sure how to start debugging that :)

**Comment by aduth** [comment]
I briefly did a recording on the Performance tab, and it doesn't look like it's a hanging system, just a delayed evaluation of the events perhaps?

**Comment by iseulde** [comment]
@aduth Cannot reproduce in current master. Probably fixed with the new rich text value?

**Comment by aduth** [comment]
This does appear to have been fixed.
