### ISSUE TITLE
Blank screen seen in place of a new post, edit post once activated.  WP version 4.9.8–en_CA,

### ISSUE THREAD

**Issue by KenBiron** [WordPress/gutenberg#8679]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [x] Tests
- [x] Documentation

**Comment by KenBiron** [comment]
What my edit and add new screen looks like:
![blank-screen-wp-gutenberg](https://user-images.githubusercontent.com/26168680/43796718-e8cdc188-9a39-11e8-9638-5b2d8eb2bb9e.png)

**Comment by designsimply** [comment]
Hi @KenBiron. We are tracking this issue at https://github.com/WordPress/gutenberg/issues/8455 and a fix at #8578 which will be available in the next release.
