### ISSUE TITLE
Custom HTML Block: RTL visual issues

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8680]
**Describe the bug**

When using a RTL language, the Custom HTML block has a couple visual bugs:

![screen shot 2018-08-07 at 2 44 03 pm](https://user-images.githubusercontent.com/1202812/43796231-abf10ea6-9a51-11e8-9e11-2e2e2da99788.png)

- The block hover label is overlapped by the background of the line number column.
- The line numbers appear too far to the right. 

**To Reproduce**

1. Switch to a RTL language (Arabic, Hebrew, etc)
2. Insert a list block with at least two items.
3. Toggle the indent, using the toolbar buttons.

**Tested in**

Mac OS 10.13.6, Safari 11.1.2
Mac OS 10.13.6, Chrome 67.0.3396.99

**Comment by jorgefilipecosta** [comment]
Hi @kjellr thank you for reporting this issue. Given the design changes that happened, it seems this issue is not relevant anymore. If in your tests the problem is persisting feel free to reopen this issue.
