### ISSUE TITLE
Local changes on fresh clone install

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8684]
Regressed in #8596

**To Reproduce**

1. `git clone https://github.com/WordPress/gutenberg.git`
2. `cd gutenberg`
3. `npm install`
4. `npm test`
5. Observe local changes via `git status`

In other branches, I've been seeing errors on a failing snapshot test for DefaultBlockAppender . Not certain yet whether this is related. Will report back.

```diff
diff --git a/package-lock.json b/package-lock.json
index 27462f010..a0e677a15 100644
--- a/package-lock.json
+++ b/package-lock.json
@@ -3640,7 +3640,7 @@
 				"@wordpress/jest-preset-default": "file:packages/jest-preset-default",
 				"@wordpress/npm-package-json-lint-config": "file:packages/npm-package-json-lint-config",
 				"cross-spawn": "^5.1.0",
-				"jest": "^23.3.0",
+				"jest": "^23.4.2",
 				"npm-package-json-lint": "^3.3.0",
 				"read-pkg-up": "^1.0.1",
 				"resolve-bin": "^0.4.0"

```

**Expected behavior**

1. No local changes

**Comment by gziolo** [comment]
It was sorted out with #8660 at last :)
