### ISSUE TITLE
When the interface is RTL, should code editors also be RTL?

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8685]
Over the course of some testing, I noted that Gutenberg isn't being consistent with the way it treats code when the interface language is RTL. 

If you edit a block as HTML, it reads right-to-left:

![screen shot 2018-08-07 at 3 17 13 pm](https://user-images.githubusercontent.com/1202812/43797321-0636f21a-9a55-11e8-8f0a-070d73384310.png)

The Code block also reads right-to-left:

![screen shot 2018-08-07 at 3 19 03 pm](https://user-images.githubusercontent.com/1202812/43797388-3c735774-9a55-11e8-91cd-af6c43980c05.png)

Meanwhile, the code in the Custom HTML block reads left-to-right:
_(The visual issue below has been filed separately in #8680)_

![screen shot 2018-08-07 at 3 19 48 pm](https://user-images.githubusercontent.com/1202812/43797430-59cbcfea-9a55-11e8-8855-cf185a9943a6.png)

I'm not fluent in any languages that read right-to-left, but my guess is that we should be consistent about this one way or another. Can someone clarify which we should use?

Thanks!

**Comment by ntwb** [comment]
Code for RTL locales should read LTR.

There are some screenshots in [#WP44053](https://core.trac.wordpress.org/ticket/44053(https://core.trac.wordpress.org/ticket/44053) that highlight when and where code should be LTR for RTL locales.

**Comment by kjellr** [comment]
Thanks for including that thread, @ntwb — that's helpful. It sounds like the examples I included above should be LTR in RTL locales then. 

One more clarifying question: In the other thread, you noted:

> To clarify, the "Text" editor is not a "code editor", you can add code but it is designed as a "plain text" editor that allows you to inspect any HTML code that may be within the text of your post.

In the case of Gutenberg however, we call the "Text" editor the "Code" editor. It currently reads RTL in RTL locales. Should that be LTR as well?

**Comment by yoavf** [comment]
It's tricky. Once you start adding RTL text (i.e [in Hebrew](http://generator.lorem-ipsum.info/_hebrew)), then editing it while in LTR mode becomes very difficult. 

That's just how the mix of ltr HTML code and RTL text works.

The way it's solved n the classic editor is by adding a text direction button to enable users to quickly switch between directions. cc @azaozz

**Comment by aduth** [comment]
Can someone clarify for me what action needs to be taken here for this issue to be closed?

**Comment by koke** [comment]
Another instance of this is when you chose "Edit as HTML" for an individual block in an RTL context:

![Screen Shot 2019-11-07 at 10 11 05](https://user-images.githubusercontent.com/8739/68375610-71b1b980-0147-11ea-9267-2c06b0673dee.png)
![Screen Shot 2019-11-07 at 10 15 03](https://user-images.githubusercontent.com/8739/68375632-7c6c4e80-0147-11ea-92a7-04f6c7797ac4.png)

**Comment by paaljoachim** [comment]
Is this issue still valid?
Thanks.

**Comment by tellthemachines** [comment]
Currently, Code, Custom HTML and edit as HTML views are all consistent in RTL mode:

<img width="718" alt="Screenshot 2023-05-10 at 1 28 28 pm" src="https://github.com/WordPress/gutenberg/assets/8096000/a85cd159-52bd-4e57-a2a0-0c36984114e9">

If I understand the above correctly, the ideal solution would be to be able to set the text direction on a per-block basis. 

I'm going to go ahead and close this one in favour of  #15349.
