### ISSUE TITLE
Instagram embeds do not display properly while editing

### ISSUE THREAD

**Issue by kriskarkoski** [WordPress/gutenberg#8686]
**Describe the bug**
Instagram embeds do not display in Gutenberg while editing. A placeholder for the image/video appears along with the correct caption, but never loads. The embed loads properly on the front-end

**To Reproduce**
1. Add an Instagram embed
2. Insert a valid URL (tested with https://www.instagram.com/p/BlbiuZ4g56e/)
3. See the attempted embed with the caption, but no image/video displays, but does work on the front-end

**Expected behavior**
The image/video to be embeded as it appears on the front-end

**Screenshots**
![screen shot 2018-08-07 at 3 31 38 pm](https://user-images.githubusercontent.com/1900444/43797942-02787ad4-9a57-11e8-8276-9641cfbffb65.png)

**Desktop (please complete the following information):**

OS: OS X 10
Browser: Chrome
Version 67.0.3396.99

**Additional context**
Gutenberg v3.4.0

**Comment by earnjam** [comment]
@kriskarkoski This worked for me on my local test. 
![image](https://user-images.githubusercontent.com/4267290/43798385-763452d0-9a58-11e8-871a-f807ca133f0e.png)

Do you get any errors in your browser javascript console when this happens?

**Comment by kriskarkoski** [comment]
Thanks for testing so quickly. Looks like just a global one and nothing specific to this embed:

> index.js?ver=1533063701:1 paragraphs block class set is-small-text, ..., is-large-text is deprecated and will be removed from Gutenberg in 3.6. Please use has-small-font-size, ..., has-large-font-size class set instead. Note: If paragraphs using this classes are opened in the editor new classes are automatically applied the post just needs to be saved. This is a global warning, shown regardless of whether the classes are used in the current post.

I see your site is http, where I was testing on https and thought that might be it but it doesn't work on an http site either. After some further testing it looks like this might be getting broken by Jetpack, which was on all the sites I tested before but disabling it allows the embed to show.

**Comment by earnjam** [comment]
It looks like this has come up before in #3499 and there is an open ticket on the Jetpack repo too: Automattic/jetpack#9331 

I'm going to close this as a duplicate. Thanks for reporting it!
