### ISSUE TITLE
Adding Custom URL to Galleries

### ISSUE THREAD

**Issue by PenofJen** [WordPress/gutenberg#8693]
**Is your feature request related to a problem? Please describe.**
I'm very frustrated that you can't link a gallery of photos/images to a custom URL. I was hoping this would be changed in Gutenberg. After taking Gutenberg for a test run just now, I noticed that this hasn't changed.

**Describe the solution you'd like**
Please allow galleries to link to a custom URL.

**Describe alternatives you've considered**

**Comment by danielbachhuber** [comment]
Hi @PenofJen,

Thanks for the report! This suggestion is already tracked in #8305. Closing in favor of that issue.

**Comment by Flaschenzug** [comment]
Closed but not resolved ...
Is there a plan to add this feature in wordpress core?

I think it should be a basic feature to add a custom URL to each gallery image.
