### ISSUE TITLE
Style only selected part of a block

### ISSUE THREAD

**Issue by rocketago** [WordPress/gutenberg#8697]
I was trying to change the color of a single word in my paragraph block, but it seems that isn't yet supported. I need to style individual words and links in paragraphs frequently in my blog, so that's an essential feature for me. 

Thanks

**Comment by kjellr** [comment]
Hi @rocketago! Thanks for submitting this issue. There's actually an existing discussion around changing color of selected text here: https://github.com/WordPress/gutenberg/issues/6080

I'm going to close this duplicate issue for now, but feel free to follow along there.
