### ISSUE TITLE
Gutenberg should not be default in core if the majority of recent reviews continue to be negative

### ISSUE THREAD

**Issue by SuperGeniusZeb** [WordPress/gutenberg#8699]
I really, really, _**really**_ like Gutenberg. I see lots of potential in the project, and I think Gutenberg is a necessary step for WordPress to get better.

But what good is it to get better if you have made a significant number of people angry, and even more people just generally annoyed?

Gutenberg is supposed to be an improvement. However, given the response since the Try Callout, it is not perceived as such by a large number of people.

Now, from a logical perspective, would you merge something into core as default while it was still getting more negative reviews than positive ones? That sounds like PR suicide.

Actually, you have already done a less than ideal job with PR. Many people do not feel like they are being heard. The Gutenberg team says they are listening to feedback on how to improve Gutenberg. But some people think that is pointless because they don't want Gutenberg in the first place.

Many people see Gutenberg as being worse for blogging than the Classic Editor. Other people see Gutenberg as being a very half-baked page builder. Gutenberg is supposed to accomplish the first by WordPress 5.0, and the latter at a future date. If it is accomplishing neither for many people, then it is not ready.

Now, Gutenberg is set for a merge proposal around December. However, I hope this is a flexible deadline, because I think that there are a large number of things that must be addressed before the merge proposal, and not just pushed to a future release.

To appeal to bloggers, Gutenberg must at the very least have total feature parity with the Classic Editor. Actually, it should do more than that. It should provide definite benefits over the Classic Editor; otherwise, users will (and currently many do) see no reason to switch to using Gutenberg, considering it a waste of time.

To appeal to website designers, Gutenberg should have a strong UI that works well for WYSIWYG page building, and should not feel overly lacking in functionality. Of course, Gutenberg is not trying to be a page builder yet, but if it can't fully appeal to bloggers, it should at least try to make up for that by appealing to website designers.

Unfortunately, Gutenberg seems to be far from accomplishing either. I expect it can and will get there, but I have my doubts it can reach it in time for a merge proposal in December.

Whatever the case, if the negative-to-positive reception of Gutenberg does not improve between now and December, I think that Gutenberg should not be made the default editor in WordPress 5.0. It can be added, but it should be opt-in.

Yes, I know the Classic Editor plugin exists, and also that the Gutenberg Ramp plugin exists, and also that Gutenberg has a lot of backwards compatibility features. However, just because alternatives exist, that does not automatically make it okay to make something the default when a large number of people are against it.

Having Gutenberg be the default would send the wrong message to the community if Gutenberg is not perceived by the majority of people as a positive change. It sends the message that core does not care what the users think is important, regardless of whether that is true or not.

It is easy to lose user trust, but way harder to get it back. Many people do not think that core is listening to feedback... or at least, they listen to feedback, but only the feedback they _want_ to listen to and interpret feedback to mean what they want it to mean. It seems to them that no number of one star reviews will change the fact that Gutenberg is coming in WordPress 5.0 as the default editor.

And can you really prove them wrong? From a logical perspective, it seems crazy to merge something into core as a default when over half of its reviews are negative, and seem to have only gotten more negative lately, rather than the reverse.

No previous WordPress update that I am aware of has ever caused so many people to be upset. Many people believe that the commercial interests of Automattic to keep WordPress usage high are conflicting with the desires of the people who actually use WordPress. Regardless of whether or not that is true, it sounds like PR suicide to merge Gutenberg as long as it is still perceived like it is today.

If the general consensus on Gutenberg is mostly positive by December, then great! But if not, I would very strongly recommend either delaying 5.0 until the consensus is positive, or else make Gutenberg part of 5.0 but an opt-in feature to start out with, transitioning to opt-out in 5.1 or later, depending on the state of how Gutenberg is perceived by that time.

Ultimately, I think Gutenberg is wonderful, but I do not want to see it effectively forced into being the new default editor if there is still as much negativity in the community regarding the editor as there is now.

**WordPress may need Gutenberg to grow, but it needs happy users more.**

## Related articles
- http://pfbarrett.uk/gutenberg-editor-the-perils-of-ignoring-users/
- https://wptavern.com/gutenberg-plugin-garners-mixed-reactions-from-new-wave-of-testers

**Comment by pento** [comment]
Thank you for taking the time to write this, @SuperGeniusZeb.

There have certainly been quite a few negative reviews since WordPress 4.9.8 was released, which is to be expected with such a significant change being proposed. Every one of them is read and replied to. Reviews are an extremely useful source of information, they provide significant insight into where people have run into frustrations.

It's important to remember, however, that reviewers are an entirely self-selecting group. They need to be aware of the ability to review the plugin, they need to have a WordPress.org account, and they need to be sufficiently motivated to post a review. This creates a sample that is not representative of the entire WordPress user base.

While reviews will certainly be considered when it comes time to merge Gutenberg, it would be highly irresponsible to tie merge approval to ratings, an action which would only encourage more vote brigading.

I'm going to close this issue now, as there's nothing specifically actionable at this time, but conversation is welcome to continue.

---

As this is a potentially controversial topic, I'll also take the opportunity to remind everyone that disagreement is always welcome, but abusive behaviour and personal attacks are not. _Please keep discussion on topic._
