### ISSUE TITLE
Editor no longer loads

### ISSUE THREAD

**Issue by SoulTransfer** [WordPress/gutenberg#8701]
**Describe the bug**
The editor page does no longer load.

**To Reproduce**
1. Open "Erstellen" in the Wordpress Menu
2. .. not loads

**Expected behavior**
Editor is loaded

**Screenshots**

**Desktop (please complete the following information):**
- OS: Windows 10
- Browser chrome
- Version: most actual

**Comment by swissspidy** [comment]
Are you using CloudFlare by chance?

Does this still happen with any other plugin disabled and when using a default theme like Twenty Seventeen?

Are there any errors in the browser's developer tools (press F12 to open), most notably in the error console and the network tab?

**Comment by Babelguppy** [comment]
I had the same problem. I could not create or edit Pages or Posts, and the "Gutenberg" tab did nothing either; they just took forever to load and displayed blank screen in the main panel of the admin area. I switched browsers from firefox to chrome and the same thing. so i found this post. 

![editor load fail errors posts 0 - blank screen](https://user-images.githubusercontent.com/8624962/43856140-4f81cdba-9b0d-11e8-8f29-a31667383f9e.PNG)

i looked at the error panel and found a bunch of "Failed to load resource: the server responded with a status of 404 (Not Found)" messages. so i recorded the errors and uninstalled both the Classic and the Gutenberg plugins (only the Gutenberg was activated). 

after installing and activating the Gutenberg plugin again, it started giving me the Gutenberg editor. when i went to check firefox, i didn't even reload the page, but it had showed up there too. 

my guess is although the plugin was "installed," the server hadn't been fully updated. I've had problems with my site and updating/caching in the past; especially in the CSS department. What i show in my FTP is not necessarily what my hosting service is showing. Usually with my HTML pages, it updates real fast, but i've seen it take hours to use my new css pages. Honestly, i think my fussing with recording the error logs gave it the time it needed to catch up.

I also reinstalled the classic plugin (so i don't have to think about it later), but did not activate. The editor still seems fine.

It's fixed now, but here's what my error logs looked like. all three tools (posts, pages, and Gutenberg) were pretty much the same. Hope this helps someone.

![editor load fail errors posts 1](https://user-images.githubusercontent.com/8624962/43855288-bfab1234-9b0a-11e8-975f-c808e0ce291d.PNG)
![editor load fail errors posts 2](https://user-images.githubusercontent.com/8624962/43855290-c0612b78-9b0a-11e8-99d1-3b2f8fa6a2c8.PNG)
![editor load fail errors posts 3](https://user-images.githubusercontent.com/8624962/43855292-c0c2aeac-9b0a-11e8-9792-dc3206f89da1.PNG)
![editor load fail errors posts 4](https://user-images.githubusercontent.com/8624962/43855294-c1145662-9b0a-11e8-8617-8d7370eadbaa.PNG)
[editor load fail errors pages new page-1533750583047.log](https://github.com/WordPress/gutenberg/files/2271342/editor.load.fail.errors.pages.new.page-1533750583047.log)
[editor load fail errors posts edit post-1533750627616.log](https://github.com/WordPress/gutenberg/files/2271343/editor.load.fail.errors.posts.edit.post-1533750627616.log)
[editor load fail errors posts new post-1533750507960.log](https://github.com/WordPress/gutenberg/files/2271344/editor.load.fail.errors.posts.new.post-1533750507960.log)

**Comment by designsimply** [comment]
@SoulTransfer, thank you for the report! We are tracking this issue at #8455 and a fix at #8578 which will be available in the next release.

@Babelguppy, I think your case might be something different. Looking at the console errors in the screenshots you provided, it appears communication to your server simply wasn't getting through and I am not sure why. If it happens again, please post at https://wordpress.org/support/plugin/gutenberg/ and include links to those console errors.
