### ISSUE TITLE
Date Setting in Editor

### ISSUE THREAD

**Issue by JohnFreeman96** [WordPress/gutenberg#8702]
Please could you make it an option to enter a date manually in the new editor? If you want to back date or schedule a post on a desktop the new editor's date setting menu requires you to scroll click by click back through months and days. This can be really tedious if, like me, you are adding stories from an older HTML version of a web site to a Wordpress site (in my case, stories from the early 2000s). I appreciate this is a bit specialist but the option at least would be preferred. Thanks

**Comment by youknowriad** [comment]
Yes, there are some explorations to change the date picker and make it more accessible. I'm closing as a duplicate let's consolidate in #1311
