### ISSUE TITLE
No tags and categories in Gutenberg

### ISSUE THREAD

**Issue by dukesaiko** [WordPress/gutenberg#8704]
**Describe the bug**
There's no Tags and Categories to choose.

**To Reproduce**

1. Start a new post
2. Look to the right side
3. Nothing related!

**Expected behavior**
Tags and Categories to pick

**Comment by youknowriad** [comment]
Do you have a security plugin installed on your website? Do you use CloudFlare? Something is probably tweaking/disabling the REST API endpoints. I'm closing as this is a duplicate of #8609.

**Comment by rita3130** [comment]
I am having he same problem. Both tags and categories were there a few days ago and now they are gone.
