### ISSUE TITLE
How can I add no follow to links?

### ISSUE THREAD

**Issue by bucketsoftea** [WordPress/gutenberg#8711]
<blockquote>If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.
</blockquote>

I want to set some links on a blog post to follow links and some to no follow links.  Can't see how I can do that on Gutenberg.  I did use no follow plugin but don't think that is compatible with Gutenberg as can't see how I change the link.  Don't even know if they are follow or no follow.  Is there a compatible plugin?

**Comment by youknowriad** [comment]
I suggest you reach out to the plugin author to see if they have compatibility plans for Gutenberg.

In the meantime. if you set links to open in a new tab, they will have the "no follow" rel. You can also tweak the links using the HTML mode per block.

Thanks
