### ISSUE TITLE
tests: e2e test for the writing flow started to fail

### ISSUE THREAD

**Issue by gziolo** [WordPress/gutenberg#8712]
Similar to: #6956.

**Describe the bug**

When executing e2e tests two tests fail. It seems like there might be some regression introduced in the code or you can blame me for work done in #8301 🤷‍♂️ 😄 
Let's ensure it has nothing to do with the recently merged PRs.

> FAIL test/e2e/specs/writing-flow.test.js (8.849s)
>   ● adding blocks › should clean TinyMCE content
>     expect(value).toMatchSnapshot()
>     Received value does not match stored snapshot "adding blocks should clean TinyMCE content 1".
>     - Snapshot
>     + Received
>       "
>     - <p><strong></strong></p>
>     + <p></p>
>       "
>       147 | 		await clickBlockAppender();
>       148 | 		await pressWithModifier( 'mod', 'b' );
>     > 149 | 		expect( await getEditedPostContent() ).toMatchSnapshot();
>           | 		                                       ^
>       150 | 
>       151 | 		// When returning to Visual mode, backspace in selected block should
>       152 | 		// reset to the provisional block.
>       at Object._callee4$ (test/e2e/specs/writing-flow.test.js:149:42)
>       at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
>       at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:288:22)
>       at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
>       at asyncGeneratorStep (test/e2e/specs/writing-flow.test.js:9:103)
>       at _next (test/e2e/specs/writing-flow.test.js:11:194)
>   ● adding blocks › should clean TinyMCE content
>     expect(value).toMatchSnapshot()
>     Received value does not match stored snapshot "adding blocks should clean TinyMCE content 2".
>     - Snapshot
>     + Received
>     - "
>     - <p><strong>Inside</strong></p>
>     - "
>     + ""
>       157 | 		await pressWithModifier( 'mod', 'b' );
>       158 | 		await page.keyboard.type( 'Inside' );
>     > 159 | 		expect( await getEditedPostContent() ).toMatchSnapshot();
>           | 		                                       ^
>       160 | 	} );
>       161 | } );
>       162 | 
>       at Object._callee4$ (test/e2e/specs/writing-flow.test.js:159:42)
>       at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
>       at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:288:22)
>       at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
>       at asyncGeneratorStep (test/e2e/specs/writing-flow.test.js:9:103)
>       at _next (test/e2e/specs/writing-flow.test.js:11:194)

**To Reproduce**

`npm run test-e2e`

**Expected behavior**
Tests pass.

**Comment by gziolo** [comment]
Also logged in https://github.com/WordPress/gutenberg/pull/8707#issuecomment-411714831:
```log
    - Snapshot
    + Received
      "<!-- wp:paragraph -->
    - <p><strong></strong></p>
    + <p></p>
      <!-- /wp:paragraph -->"
      147 | 		await clickBlockAppender();
      148 | 		await pressWithModifier( 'mod', 'b' );
    > 149 | 		expect( await getEditedPostContent() ).toMatchSnapshot();
          | 		                                       ^
      150 | 
      151 | 		// When returning to Visual mode, backspace in selected block should
      152 | 		// reset to an unmodified default block.
```

**Comment by youknowriad** [comment]
Clearing the milestone because it's not impactful for release (or not).

**Comment by gziolo** [comment]
I haven't seen this issue for a while. Let's close it.
