### ISSUE TITLE
Line separator not displaying

### ISSUE THREAD

**Issue by DeanE1** [WordPress/gutenberg#8718]
**Describe the bug**
I've inserted the line separator in my blog but in preview it does not show, the post hasn't been published yet so I can't confirm whether or not it shows then but I have my doubts.

**To Reproduce**
1. Go to 'blocks'
2. Click on 'line separator'
3. Shows line
4. Click on 'preview'
5. Not shown

**Expected behavior**
The line should be in the preview where the line was placed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67.0.3396.99

**Comment by youknowriad** [comment]
The line separator is just an `<hr />`  tag. Maybe your theme is styling this tag in a way it doesn't show up? you can check the source code of your page to see if the `hr` is there? Can you share a link to your page?

**Comment by DeanE1** [comment]
That's very possible, I use elementor heavily on my website. I can't share a link to the post as I have not published the post. The lines just are not showing in preview mode at this point. In my preview,  I searched for '<hr' and found nothing.

**Comment by designsimply** [comment]
I tested using WordPress 4.9.8 and Gutenberg 3.4.0 and the Gutenberg Starter Theme and this is how the line separator looks for me:

![screen shot 2018-08-08 at wed aug 8 2 56 39 pm](https://user-images.githubusercontent.com/1119271/43863893-4ce10176-9b1b-11e8-91e6-63c2c2b8dc52.png)
<sup>Seen at http://alittletestblog.com/?p=14177&preview=true running WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

Is there a different post already published on your site that also has a line separator that we can look at?

**Comment by DeanE1** [comment]
Yes, I added the line separator in a previously created post at the top and it does not show, although it can be seen while inspecting the code just above the first paragraph.

Here is what I see when inspecting the code, but the actual line cannot be seen.

<hr class="wp-block-separator  is-style-wide">

Here is the post.

https://www.deancentgarage.com/deancent-garage/intro/

**Comment by youknowriad** [comment]
You have a CSS rule in your theme making the separator invisible (background transparent)

<img width="315" alt="screen shot 2018-08-08 at 22 08 42" src="https://user-images.githubusercontent.com/272444/43864476-b4d835e2-9b57-11e8-8059-db113b742af8.png">

**Comment by youknowriad** [comment]
Actually it's not a theme rule, it's added by the elementor plugin.

**Comment by DeanE1** [comment]
Thank you youknowriad, sorry to waste your time.

**Comment by youknowriad** [comment]
No worries :)
