### ISSUE TITLE
Audio block center alignment does not stick to post preview or published posts

### ISSUE THREAD

**Issue by lizkarkoski** [WordPress/gutenberg#8724]
Issue discovered after a report came through the forum here:
https://wordpress.org/support/topic/center-aligned-audio-is-aligned-left/#post-10572210

The user briefly makes mention of an issue with the audio block alignment. 

Using Gutenberg 3.4.0

**To Reproduce**
1. Create a new post in Gutenberg
2. Chose the Audio block
3. Add an audio file to the block
4. Use the editor tools to center align the file
5. Check the post preview, the file will remain left aligned
6. Publish the post with the center aligned file, the file remains left aligned

**Expected behavior**
I expect that the center alignment option would stick to the post for a post preview and especially on the published update. 

**Screenshots**
Here is the post in edit mode with the center alignment chosen for the audio file.
<img width="735" alt="screen shot 2018-08-08 at 1 29 39 pm" src="https://user-images.githubusercontent.com/16867830/43854126-f855212e-9b0f-11e8-8def-618e4183c3ed.png">

This is what the post looks like both published and previewed with the center alignment selected. 
<img width="795" alt="screen shot 2018-08-08 at 1 29 27 pm" src="https://user-images.githubusercontent.com/16867830/43854177-18d80218-9b10-11e8-9878-24d9caa8afc5.png">

**Desktop (please complete the following information):**
 - OS: Mac Sierra
 - Browser Chrome v67

The same behavior was seen intermittently with using the file block and the download button. Haven't been able to pin down consistent behavior to report that yet.

**Comment by designsimply** [comment]
I tested this using three different themes (Atomic Blocks, Gutenberg Starter Theme, Navi) and found that a centered audio player only worked in one of those (Navi). May I ask what theme you tested for reference?

![screen shot 2018-08-08 at wed aug 8 3 25 54 pm](https://user-images.githubusercontent.com/1119271/43865237-3a834530-9b1f-11e8-8e7c-484e131a8488.png)
<sup>Seen at http://alittletestblog.com/2018/08/08/audio-block-test/ running WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by lizkarkoski** [comment]
@designsimply - I tested in Lodestar which replicated the user report.

**Comment by jorgefilipecosta** [comment]
Hi @lizkarkoski thank you for reporting this issue. In my tests, it appears the problem is not happening anymore. When center alignment is chosen the bock is aligned center (and normally takes all the content width). I tested using Lodestar and some default themes. If the problem is still happening, feel free to reopen the issue.
