### ISSUE TITLE
Add a "Feedback" link to Gutenberg

### ISSUE THREAD

**Issue by wpscholar** [WordPress/gutenberg#8725]
**Is your feature request related to a problem? Please describe.**
It is quite helpful when desiring feedback, to make the process as easy and fast as possible. At present, the user has to go to the WP site, find the plugin, go to support, and start a new topic.

Inspired by: https://wordpress.org/support/topic/gutenburg-provide-a-place-feedback-here-button/

**Describe the solution you'd like**
A simple "Feedback" button placed in the editor (say top right). I think it would make sense to link the "Feedback" button to the Gutenberg support form (https://wordpressdotorg.polldaddy.com/s/gutenberg-support) as this form can automatically create GitHub issues where appropriate. This would help to get feedback rapidly, including from those who might be less able, which means a broader sample of users is available for helping to make it as simple to use as possible.

**Comment by karmatosed** [comment]
@wpscholar we have one as a link in the menu. I think over having it directly in the editor this works for now.

**Comment by karmatosed** [comment]
For reference what we have now:

![2018-08-08 at 18 59](https://user-images.githubusercontent.com/253067/43855363-3bf9379e-9b3d-11e8-99d5-854641760fd4.png)

**Comment by wpscholar** [comment]
@karmatosed  I think that is very easy to overlook... especially for new users who are trying to edit their own posts. At a minimum, should that be part of the onboarding tooltips?

**Comment by karmatosed** [comment]
I wouldn't be against adding it to a Tip. I standby I don't think it needs to be as obvious as a button in the actual interface, whilst feedback is amazing not everyone wants or should be forced to do it.

**Comment by jaumecantarino** [comment]
This is a good and helpful improvement for gutenberg and it will help solving problems faster.

**Comment by aduth** [comment]
I had thought there was a separate issue for it (perhaps someone else is better at search than I am), but I think it would be nice to include some visual indication on the editor screen that the plugin is being used at all. Currently, it's easy to overlook whether you're running WordPress stable or the plugin version of the Gutenberg block editor.

As a point of reference, Automattic's Calypso project includes an "environment badge" in development environments:

https://github.com/Automattic/wp-calypso/tree/master/client/components/environment-badge

I can imagine a similar pattern being applied for Gutenberg, including development information, and support/feedback links.
