### ISSUE TITLE
Change how required built-ins are polyfilled

### ISSUE THREAD

**Issue by blowery** [WordPress/gutenberg#8727]
The current npm packages that being built for Gutenberg polyfill usage of some browser features that are not available on older browsers. This polyfill is global and affects any client who uses the gutenberg npm packages. This is unexpected and can alter the runtime environment in surprising ways. Additonally, some client environments do not require these polyfills and would work without them. Bundling them increases the overall bundle size and slows down loading.

Instead, gutenberg's packages should take one of two approaches: use use babel's `transform-runtime` plugin to replace problematic built-in usage, or stop polyfilling altogether and declare that host environments must polyfill certain features for Gutenberg to work on downlevel browsers. The later is the direction being taken by react-dom and some other libraries that require full ES5 compliance. 

Original discussion: https://github.com/WordPress/gutenberg/pull/8057#issuecomment-411415555

**Comment by blowery** [comment]
@gziolo Awesome, that looks great!

**Comment by blowery** [comment]
Here's an example of [what Gutenberg outputs today](https://babeljs.io/en/repl#?babili=false&browsers=%3E%201%25%2C%20ie%20%3E%3D%2011%2C%20last%201%20Android%20versions%2C%0A%09last%201%20ChromeAndroid%20versions%2C%0A%09last%202%20Chrome%20versions%2C%0A%09last%202%20Firefox%20versions%2C%0A%09last%202%20Safari%20versions%2C%0A%09last%202%20iOS%20versions%2C%0A%09last%202%20Edge%20versions%2C%0A%09last%202%20Opera%20versions&build=&builtIns=usage&spec=false&loose=false&code_lz=GYVwdgxgLglg9mABMGYAmBhAhgJx3KACkVx0QEpEBvAKEURwFMoQclSA6FdYmKRgLaIAvAD5EfQRygBPAA6MRw4YgDkEUgVUUA3DQC-QA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&sourceType=module&lineWrap=false&presets=es2015%2Ces2016%2Ces2017%2Cenv&prettier=false&targets=&version=7.0.0-beta.37&envVersion=7.0.0-beta.36).

**Comment by gziolo** [comment]
@blowery, we have just published new packages to npm which have `@babel/runtime` usage replaced with `@babel/runtime-corejs2`. Can you double check if that changes anything?

/cc @aduth @youknowriad @ntwb

**Comment by gziolo** [comment]
Okey, this is still the case. I see:
```js
import "core-js/modules/es6.array.find";
```
in https://unpkg.com/@wordpress/editor@2.0.0/build-module/components/navigable-toolbar/index.js

**Comment by gziolo** [comment]
This should be resolved with the #9171 and is now available on npm.

Check related versions of updated packages in https://github.com/WordPress/gutenberg/commit/df6f8da7b557894e4364c17db2dd4af0d1e20252.
