### ISSUE TITLE
Classic Block: Block contains its own undo/redo buttons. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8729]
**Describe the bug**

Gutenberg has a set of undo/redo buttons in the top toolbar. The classic block also contains a set of undo/redo buttons (with slightly different icons):

<img width="890" alt="screen shot 2018-08-08 at 3 51 47 pm" src="https://user-images.githubusercontent.com/1202812/43860990-800004be-9b23-11e8-96e4-4dae16a6c35b.png">

For most  in-block actions, the block's undo/redo actions perform just like the global buttons. Some more granular actions (adding a link, changing text color) are only undo/redo-able via the block-level controls. 

In any case, having two sets of undo/redo buttons on the page is confusing. If we can get the global controls to work identically to the block buttons, I'd suggest we remove the block-level buttons entirely. 

**To Reproduce**

1. Add a Classic Block
2. Click the "More" button to expose the second row of controls. 
3. Observe that there are two sets of undo/redo buttons in the UI.

_Tested in Gutenberg 3.4_

**Comment by draganescu** [comment]
I wonder if the fact that the classic block _is_ an editor inside an editor isn't a reason to _keep_ the buttons. I tested with Gutenberg 7.9.1 and I can't even undo a bold word with the global buttons.

**Comment by mtias** [comment]
I think this is alright, even if perhaps not ideal. Embeded editors can have their own history to which the block editor might not be exposed. I don't think the work involved in reconciling is worth the effort at the moment.
