### ISSUE TITLE
Create self-documenting block documentation for developers

### ISSUE THREAD

**Issue by mor10** [WordPress/gutenberg#8733]
For theme (and plugin) developers to take full advantage of the controls Gutenberg affords them, they need comprehensive documentation of what each block does and how it can be targeted using DOM methods.

I propose the creation of a Block Documentation resource (name tbd) containing information about each core block including

- Block name
- Description of block function
- Classes and attributes surfaced in the block editor
- Classes and attributes surfaced on the front end
- (Optional) Live sample of the block as it appears in the block editor
- (Optional) Live sample of the block as it appears on the front end

The Block Documentation would be used by developers to quickly identify how to target blocks in the block editor and on the front end, ie answer questions like "How do I change the font size of a paragraph nested inside a column block?"

## Automation
Ideally the blocks should be self-documenting and this resource should use some form of framework populated by data pulled directly from Gutenberg. There is precedence for this approach in the larger web community and it may be possible to use an existing styleguide or element library framework to create this resource.

## Urgency
Getting this resource up and running, even if it means populating it by hand, is key to developers being able to take advantage of Gutenberg's features from day one.

**Comment by draganescu** [comment]
Hey @mor10 does the addition of the [Gutenberg Storybook](https://wordpress.github.io/gutenberg/?path=/story/docs-introduction--page) help with this?

**Comment by mrleemon** [comment]
> * Classes and attributes surfaced in the block editor
> * Classes and attributes surfaced on the front end

This is long-awaited!

**Comment by mtias** [comment]
[BlockBook](https://youknowriad.github.io/blockbook/) accomplishes this and we might integrate it in the main storybook.
