### ISSUE TITLE
Screen Options Missing - which makes it impossible to turn off Meta Boxes

### ISSUE THREAD

**Issue by rickandersonaia** [WordPress/gutenberg#8737]
**Describe the bug**
The Classic Editor retains the original Screen Options tab which allows the user to turn off unwanted meta boxes.

**To Reproduce**
1. Go to the post or page list screen, open with gutenberg
2. Screen Options don't exist

**Expected behavior**
I expected to be be able to see the Screen Options tab and to be able to disable meta boxes

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 67

**Additional context**
- WP 4.9.8, Gutenberg 3.4.0
![2018-08-08_16-10-40](https://user-images.githubusercontent.com/2720463/43869142-e82b7fbc-9b25-11e8-81ff-df5d16924975.png)
![2018-08-08_16-06-46](https://user-images.githubusercontent.com/2720463/43869143-e8400126-9b25-11e8-865f-1a0ffc82fad0.png)

**Comment by youknowriad** [comment]
A decision was made to abandon these options because:

 - A lot of people don't know about them (discoverability) 
 - Prefer Gutenberg extensibility APIs over metaboxes in plugins. (those plugins support pinning/unpinning)

More discussion here #5841

Thanks for the feedback
