### ISSUE TITLE
Layout Settings - not allowing fullwidth / no sidebar

### ISSUE THREAD

**Issue by lauracgeorge** [WordPress/gutenberg#8739]
In my Layout Settings section, selecting the layout with no sidebars or columns results in the default layout (which for me includes the right sidebar).

**To Reproduce**
1. In page editor, scroll down to the Layout Settings section.
2. Next to Select Layout, choose the one with no sidebars or separate columns.
3. Save it.
4. See that it still has sidebar. :(

**Expected behavior**
Page will not have sidebar.

**Computer Info:**
 - iOS - Yosemite
 - Chrome browser - fully updated on version 67
 - WP - fully updated on version 4.9.8
 - Gutenberg - version 3.4.0

**Comment by designsimply** [comment]
I don't see Layout Settings, could you be referring to Document Settings > Page Attributes > Template? ([screenshot](https://user-images.githubusercontent.com/1119271/43905896-3c046322-9baf-11e8-968a-b0663e08f725.png))

May I ask which theme you are testing with or if you are using a plugin that adds customized Layout Settings?

**Comment by nickcernis** [comment]
Hi, @lauracgeorge!

This sounds like it may relate to the custom Genesis child theme you are using.

If you are still unable to select the full-width page layout from the Genesis layout options only when Gutenberg is active, you are welcome to get in touch with the StudioPress support team to share further information (such as the URL of the page this is affecting): https://my.studiopress.com/help/. We'd be happy to look into this further for you.

**Comment by designsimply** [comment]
Thank you @nickcernis!! 

Closing with Nick's note to post details to https://my.studiopress.com/help/.
