### ISSUE TITLE
Limiting functionality or just hiding it?

### ISSUE THREAD

**Issue by lauracgeorge** [WordPress/gutenberg#8740]
I'd like to start by saying that my goal in writing here is to provide a perspective of a tech-competent, but non-developer, small business owner running their site on WordPress.org.

I've poked around in Gutenberg for a total of about 30 minutes now, so admittedly not much time. Yet, I feel it provides me with less functionality than I had with the classic editor, and many more clicks to make things happen.

For example, when I created a page, I was automatically given a box to write a heading in. So I wrote a heading. I decided I'd like to have an image on the page. So I added an image box. Then I decided I wanted the image first and the heading second... But I can't drag them around. So if I wanted to switch them around, I would have to go into the html and copy/paste them around. This requires clicking some little dots you might not realize are up there in the corner, away from all the other settings, and switching over to Code Editor. But it also requires that I am capable in HTML. I happen to be, personally. But what about the millions of WP users who don't touch the html side of their WP pages/posts? When they want to move a block, they will have to delete it and recreate it in the new spot. Though perhaps I'm missing an easier way to do this? If I am, I'm glad there's an easier method, but I'm also disappointed that the user interface is confusing enough that I can't find the easier method. I'm very well-versed in picking up new software and a basic page/post editor should not take more than 20 minutes for someone at my skill level to pick up.

Another thing I notice is that several of my plugins have completely disappeared from their spots in my page editor because of the Gutenberg coding. While I am under no impression that WP devs should have to keep things smooth for all plugins (or that that would be possible), I've never seen a change before that has made a plugin disappear. It creates a huge lack of functionality for me, and I can only assume for many other users who have cobbled together their dream WP dashboard. What is essentially just a different UI for the page/post editor, will likely create months of upheaval in my small business while I try to work through a domino effect of issues. It might be enough for me to switch website platforms. I hope not. I love WP. But if too many of my customizations are impossible because the new editor has broken plugins (plugins which may not be updated in a timely manner to adjust to the change), it just won't be a smart business move to stick around.

While I see a ton of developers on here, I'd like to say that I am a fair representation of a ton of small businesses with a little tech/coding capability (but not to developer level) who are the bridge between most of the people in this forum and the people who I would guess Gutenberg was created for - kind of the .com side of it. And as a member of this subset of WP users, I feel obligated to say that I think WP might be mis-assessing their spot in the marketplace. From my perspective, WP is the ultimate go-to for people who want to build a website and have a lot of customization control, without having to code it from scratch. I've spoken with dozens of people directly who have chosen WP for this reason, and I did as well. And since I follow the online business world a little, I've also heard indirectly from hundreds of people who chose WP for this reason. Yet, Gutenberg appears to be catering to the novice. There are tons of viable website platforms for the novice that have a much easier-to-use-than-Gutenberg editor, primarily the popular drag-and-drop styles. I know of plenty myself, even though I have no interest in using them, that are smoothly fulfilling this need and their customers are thrilled. So why would WP try to get out of the market they're killing it in, only to get into a market that already has loads of competitors killing it? It doesn't make sense to me. But I don't know the perspective of the WP developers, so perhaps I'm missing a really good reason for this change.

Sure the classic editor was a bit clunky and did need a plugin or two to extend its functionality enough, but it didn't require this level of overhaul. And this level of overhaul has welcomed in a litany of problems that simply tweaking the classic editor would not have.

Hopefully I'm adding to the conversation in a valuable way, despite my lack of extensive tech knowledge. My goal was to provide a perspective of a tech-competent, but non-developer, small business owner running their site on WordPress.org.

**Comment by aduth** [comment]
Thanks for the feedback. Since issues in this repository should be actionable, I want to make sure that the points are considered, but directed to tasks as identified before closing this issue.

>Then I decided I wanted the image first and the heading second... But I can't drag them around. 

I don't recall the date of its introduction relative your posting, but blocks can both be dragged, and reordered using the block movers shown adjacent a block when it is selected.

![image](https://user-images.githubusercontent.com/1779930/58724530-def83c00-83aa-11e9-9757-d8a4113e23d3.png)

>Another thing I notice is that several of my plugins have completely disappeared from their spots in my page editor because of the Gutenberg coding. While I am under no impression that WP devs should have to keep things smooth for all plugins (or that that would be possible), I've never seen a change before that has made a plugin disappear.

I would need more specific information here, but plugins using existing metabox functionality should have been largely unimpacted by the 5.0 release.

More information about backwards-compatibility and meta boxes can be found at: https://developer.wordpress.org/block-editor/developers/backward-compatibility/meta-box/
