### ISSUE TITLE
Publish requires two clicks

### ISSUE THREAD

**Issue by bkjproductions** [WordPress/gutenberg#8744]
**Publish button takes two clicks*
When I click "Publish" then I expect it to publish. No need to ask again.

**To Reproduce**

1. Create a Post
2. Click the Publish Button
3. You have to click again to confirm that you indeed want to publish.

**Expected behavior**
When I want to publish, I click that button and it should just publish right then and there.

**Screenshots**
![are you ready to publish](https://user-images.githubusercontent.com/4551281/43875418-5d7bae94-9b5e-11e8-80ef-8bf8ff22572d.JPG)
![publishing](https://user-images.githubusercontent.com/4551281/43875419-5d8b54fc-9b5e-11e8-9df0-c62b1d633a10.JPG)

**Desktop (please complete the following information):**
 - OS:  Windows10
 - Browser: Chrome
 - Version: 3.4.0 Gutenberg, 4.9.8 WordPress

**Smartphone (please complete the following information):**
 - n/a

**Additional context**
- It is also possible to publish without a title, but that was possible before this editor, too. Still, I think if you are going to improve things, then require a title.

**Comment by youknowriad** [comment]
This was a design decision that was largely discussed:

 The goal is to avoid accidental publishing while offering room for plugin authors to hook into prepublish/postpublish workflows. More discussion in this thread #3279
