### ISSUE TITLE
Help and Screen Options Missing

### ISSUE THREAD

**Issue by bkjproductions** [WordPress/gutenberg#8745]
**Interface becomes inconsistent**
Throughout most of WordPress there are two links at the upper right corner, **Screen Options** and **Help**.

**To Reproduce**

1. Create a new Post or Page
2. Look in the upper right corner.
3. There is only a gear, and three dots stacked one on top of another.
4. On the Posts List, Media Library, Comments List, etc. you can easily find Screen Options and Help in the upper right corner, consistently.

**Expected behavior**
It has taken a while for many naive users to realize that Help and Screen Options relevant to the things they are viewing are in the upper right corner. If the new editor does not have this, it is going to cause some confusion. 

**Screenshots**
In the Post or Page Editor, upper right corner:
![no more screen options or help](https://user-images.githubusercontent.com/4551281/43875699-7345351e-9b5f-11e8-83dd-740b180cbec5.JPG)

Everywhere else:
![everywhere else there are screen options and help](https://user-images.githubusercontent.com/4551281/43875694-6b3bd5b2-9b5f-11e8-87da-fc85eca6ff42.JPG)

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Chrome
 - Version: 3.4.0 Gutenberg, 4.9.8 WordPress

**Smartphone **
 - Did not test

**Additional context**
- How will this change be implemented throughout the rest of the WordPress dashboard? Will the add_help_tab method need to be changed to match the interface found in the new editor?

**Comment by youknowriad** [comment]
A decision was made to abandon these options because:

 - A lot of people don't know about them (discoverability) 
 - Prefer Gutenberg extensibility APIs over metaboxes in plugins. (those plugins support pinning/unpinning)

More discussion here #5841

I'm not certain about the help button, I think the NUX work (tips) are supposed to achieve the same goal but I may wrong cc @karmatosed 

Thanks for the feedback

**Comment by karmatosed** [comment]
Help likely will come back as we move to having keyboard shortcuts. Help could include maybe tutorials - likely a later consideration. If we did it would be that same modal. As far as screen options goes, we don't need that as the interface is different and we have pinning.

**Comment by bkjproductions** [comment]
I'm thinking it would be good to keep the Help system consistent across WordPress.
Also the same thing for Screen Options. 

Not sure what you mean about tips; generally, I've seen little tool-tip like hovering balloons or words in boxes when you mouse over a (?) next to an item that may warrant more explanation. Is that what you mean by Tips?

**Comment by youknowriad** [comment]
> I'm thinking it would be good to keep the Help system consistent across WordPress.

Definitely, and Gutenberg is providing the tools to do that for WordPress JS UIs (which we can expect more to come).

> Not sure what you mean about tips; generally, I've seen little tool-tip like hovering balloons or words in boxes when you mouse over a (?) next to an item that may warrant more explanation. Is that what you mean by Tips?

Yes, these are the tips I was talking about.

**Comment by karmatosed** [comment]
In this case screen options don't quite work in parity as the interface is different. Similarly help will fit under the ellipsis along with keyboard shortcuts. Let's close this and focus on bringing help in there and building up Tips as a first start.

**Comment by LiveBy5** [comment]
If it's ok to add my 2 cents, I think abandonning screen options is MASSIVE loss for WordPress devs who try to tailor the individual experience of their builds to their clients.

I have about 18 different metaboxes showing sometimes, and others aren't appearing for anyone (having to retrofit  a lot of custom fields as we can't 'find' them in the Gutenberg interface, or delay rollout entirely). These are things our team switch 'on' or off on a per user basis when we're deploying a site to ensure their workflow is uncluttered. I do not what my clients stressing about seeing scripts added to certain pages or layout options that are targeted at specific pages. It completely interrupts their publish workflow. Screen options is a fantastic and built-in way to manage this, without having to add yet another bit of custom code or plugin to achieve something we've been able to do.

My argument is that screen options is most relevant to those of us  who build sites for customers, and care about their workflow and experience of WordPress, with out us having to employ plugins or custom code to minimise the 'noise'.

I've added an example of what my client see's with, vs without screen options available.

I do not think we should have to add plugins or code to fix what was already perfectly adequate in WordPress previously.

![with-screen-options-toggled](https://user-images.githubusercontent.com/43019193/45127728-0673fc80-b1bd-11e8-879e-1416eba5a1fb.png)
![without-screen-options-show-all](https://user-images.githubusercontent.com/43019193/45127729-0673fc80-b1bd-11e8-9fee-771eb4d81132.png)

**Comment by bkjproductions** [comment]
I think you have a really good point there, and your screenshots really demonstrate the problem.  I think the Gutenberg philosophy is that it will de-clutter the interface for you, and then you can rebuild the interface like you want to using the Rest API or some such thing.

However, for myself, I think the bar for learning that way of doing things is dramatically different and more difficult than the existing way that we have come to know and love.

Tammy, can the Gutenberg interface handle the additional metaboxes that are shown in the screenshots? "Groups" and "access restrictions"? Maybe this is something we would use the Advanced Custom Fields plugin for?

And is there a way to have a toggle to show the various custom fields that are used to create these metaboxes? 

In this situation, there is an advantage to the power user who may know to show the hidden fields, and for the regular user to hide them.

Also it is great to be able to hide such things as the Comments or Tags metabox and so forth that we don't want to see. At the same time, some users may want to see them, so while that little help and screen options button set may be ugly, it is useful. :-)

**Comment by anneminford** [comment]
Has anyone worked out how do you switch on the Post Revisions option in Gutenberg?  It doesn't show as an option?
![revisionsnotshwoing](https://user-images.githubusercontent.com/17688226/52264191-f0639700-2928-11e9-8996-b49d6b37c14c.JPG)

**Comment by andymb** [comment]
Not having Help is an upgrade blocker for us on our (100+) client's websites.  We use it to add guidance on image sizes for certain types of Page or CPT, for example, and currently I don't see anywhere else we can put this apart from an external manual which people just won't consult.  We've habituated users to check Help when they need to.

**Comment by JBCSU** [comment]
My themes provide a number of custom shortcodes. There is nowhere to document the shortcodes other than under the help tab. Please ensure Gutenberg users have access to the same help information that Classic editor users have.
