### ISSUE TITLE
Copy All Content not reliable

### ISSUE THREAD

**Issue by bkjproductions** [WordPress/gutenberg#8746]
**Describe the bug**
When using the **Copy All Content** tool found in the upper right corner of the new editor, the formatting doesn't seem to follow.

**To Reproduce**

1. Go to a Post where you have a Title and a Classic Editor block with some content, including at least three (3) paragraphs.
2. Go to the upper right corner, choose three-dots-stacked-one-on-top-of-another.
3. Click **Copy All Content**
4. The button changes its name to **Copied!** for about five seconds and then it changes back to "Copy All Content" again.
5. Create a new Post
6. Paste (control V)
7. Nothing happens
8. Click on the area where normally you would put text
9. Paste (control V)
10. Two new Paragraph blocks are created. The first contains your first paragraph, the second contains all of the other paragraphs, but they are run together.

**Expected behavior**
I should think that "Copy all content" would copy all of the content, including the Title and all elements on the page. Then if I go to a new Post, I should be able to Paste that content, and it would look the same as when I copied.  I thought just doing a Paste might make it "clone" the content I just copied, populating the Title and rest of the content identically. I didn't think it would require me to put the cursor anywhere necessarily. When putting the cursor in a text box and then pasting, I should think that would still paste the way the text looked when I copied it.

**Screenshots**
Content I want to copy, consisting of a Title and a Classic block
![content before copying](https://user-images.githubusercontent.com/4551281/43876429-065258de-9b63-11e8-9e08-05d9772158b5.JPG)

Choosing the Copy All Content tool
![copy all content](https://user-images.githubusercontent.com/4551281/43876401-dbf0b1bc-9b62-11e8-9e90-6e863200583d.JPG)

Copied!
![copy all content says copied](https://user-images.githubusercontent.com/4551281/43876400-dbd17d60-9b62-11e8-8b55-1d1b73eb4c72.JPG)

Does not paste accurately; second and later paragraphs merged together.
![copy all content not pasting](https://user-images.githubusercontent.com/4551281/43876399-dbc04e82-9b62-11e8-9fed-fd9e75712e72.JPG)

Looking at the content in the Clipboard, found by just Pasting into WordPad, note that there are several DIVS in there with classes for unknown reasons unrelated to this editor
![what the pasted content looks like elsewhere](https://user-images.githubusercontent.com/4551281/43876403-dc93183a-9b62-11e8-90ff-1524bd19ea87.JPG)

**Desktop (please complete the following information):**
 - OS: Windows10
 - Browser: Chrome
 - Version: Gutenberg 3.4.0 and WordPress 4.9.8

**Smartphone**
 - N/A

**Additional context**
- It might be good to let the user know what to expect when pasting, to indicate where to paste. Maybe it says "Copied! You can now edit/create another Post, create a new Block, and Paste. Note that this will not copy the Title."
- Perhaps the DIVS in the content cause a problem? I had no idea they were there. Maybe when copying you could say, "Warning! The content has fancy formatting of some sort and may not paste accurately" if that is the case.

**Comment by gonzomir** [comment]
I experienced the same problem when pasting a custom block into the visual editor. The block contains image, heading and text, and it's being copied fine (pasting in text editor shows the HTML). But when pasting into the visual editor the block is converted to three separate ones - a image block, a heading block and a paragraph block. Pasting in the code editor work as expected.

This is the console output:

```
Received HTML:

Received plain text:

 <!-- wp:gonzo/thumb-paragraph -->
<div class="wp-block-gonzo-thumb-paragraph alignleft"><img src="http://wp.local/wp-content/uploads/sites/24/2018/08/involvement_3.svg" alt="" data-id="39657"/><div><h3>Test content copying</h3><p>We will test how Gutenberg content is being copied between posts.</p></div></div>
<!-- /wp:itce/block-thumb-paragraph -->

<!-- wp:paragraph -->
<p></p>
<!-- /wp:paragraph -->
Processed HTML piece:

 <figure><img src="http://itce.wp.local/wp-content/uploads/sites/24/2018/08/involvement_3.svg" alt=""></figure><h3>Test content copying</h3><p>We will test how Gutenberg content is being copied between posts.</p>
```

**Comment by sourourn** [comment]
I created a page with three blocks below. I then copied using the Copy All Content command. I opened a new page, clicked inside the editing area and was able to paste the 3 blocks as it without any issues. The only content that did not get copied is the page title.

Screenshots:
![screen shot on 2018-11-22 at 14-29-46](https://user-images.githubusercontent.com/39188945/48903341-eff84b80-ee63-11e8-88ca-e664c9da8b7c.png)
![screen shot on 2018-11-22 at 14-31-11](https://user-images.githubusercontent.com/39188945/48903342-eff84b80-ee63-11e8-9ff7-30590814c289.png)

Firefox (61.0.2) on MacOS
Gutenberg version: 4.5.1
WordPress version: 4.9.8

**Comment by dromero20** [comment]
I didn't have a problem with the formatting, but I could replicate what @gonzomir mentioned - If you're creating a single classic block with 3 paragraphs and a heading:

<img width="740" alt="screen shot 2018-11-22 at 13 33 47" src="https://user-images.githubusercontent.com/23258551/48903403-c3d8cc80-ee5b-11e8-823f-6641a502b3bb.png">

And then you're copying all content and pasting it in a new Page or Post, the title is not being pasted and headings and paragraph are added in 4 different blocks (1 heading - 3 paragraph):

<img width="728" alt="screen shot 2018-11-22 at 13 34 40" src="https://user-images.githubusercontent.com/23258551/48903498-fb477900-ee5b-11e8-893d-a4d47ef9c43b.png">

Tested in Firefox 63.0.1 (64-bit). macOS 10.14.
Gutenberg: 4.5.1
WordPress: 4.9.8

**Comment by youknowriad** [comment]
The pasting algorithm received a lot of iterations in the last releases. If you're still experiencing issues, please create new issues and make sure to attach the HTML you're trying to paste. Thanks a lot.
