### ISSUE TITLE
Let us use only keyboards to control basic document settings and publish

### ISSUE THREAD

**Issue by juliankim** [WordPress/gutenberg#8753]
**Is your feature request related to a problem? Please describe.**
Posting requires using mouse and therefore slowing down the productivity. I know it's very minor but it would be very convenient if it is possible to just write a very short post and pick some tags, categories and publish.

**Describe the solution you'd like**
Coming up with more shortcuts on the top of well-written user guide would do it. It would be also easier if folding and unfolding category/tag section could be in settings. Maybe a simple pin button next to them will do.

**Describe alternatives you've considered**
Maybe we can have 'preset' of posts that we can make and use?

**Comment by earnjam** [comment]
Thanks for the feedback @juliankim!

There are a lot of [open issues around keyboard based functionality](https://github.com/WordPress/gutenberg/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+keyboard) that we are working through. The general goal is to be able to use Gutenberg efficiently with only a keyboard. 

Can you elaborate on what you mean by "folding and unfolding category/tag section could be in settings". Do you mean have the editor remember the open/closed status of sidebar sections when moving from post to post? So if you expanded Categories, then when you open or create another post, it is already expanded there too?

**Comment by jasmussen** [comment]
Gutenberg 3.6 comes with a slew of new keyboard shortcuts. Including a keyboard shortcut help sheet accessible in the More menu (ellipsis in the top right), or by pressing Ctrl+Option+H.

On this keyboard sheet you can see shortcuts for navigating the whole interface. For example if your cursor is in text, having just written, you can press Shift + Option + P to set focus on the Sidebar. Then you can press Tab to navigate down to the Categories section, Space to open it, then proceed to tab through and check or uncheck any categories you need.

Given that the interface is keyboardable, and there is documentation as to how to do this, I'm going to close this ticket as fixed. 

If there are additional keyboard shortcuts Gutenberg is missing, please add to those instead. Thanks for your ticket!
