### ISSUE TITLE
Remove `wp.element`; embrace React

### ISSUE THREAD

**Issue by nylen** [WordPress/gutenberg#876]
We already have a lot of React-specific code in various places in the editor, so the `wp.element.createElement` abstraction has been more confusing than helpful for a while now.  It seems to me like we are trying to pretend that we're not tied to using React, but this is a giant, untested assumption.  I see two possible ways forward here:

1. Test this assumption and solidify our abstraction by proving that it is possible to switch to a different view rendering engine.
2. Drop the assumption and call our use of React by the name `React`.

Per [recent discussion in core Slack](https://wordpress.slack.com/archives/C02RQBWTW/p1495546673297481), WP core has basically decided to adopt React.  We are now well-positioned to prefer option (2) and remove as much of `wp.element` as possible.

**Comment by aduth** [comment]
With React 16 noisily warning about using `PropTypes` and `createClass` (two top-level API members we'd targeted as discouraging with the abstraction), this might be reasonable to consider.

**Comment by iseulde** [comment]
Agreed.

**Comment by dmsnell** [comment]
Embrace React, embrace ReasonML.
