### ISSUE TITLE
Getting the document ready for publishing.

### ISSUE THREAD

**Issue by siqik** [WordPress/gutenberg#8763]
1.  Can't seem to find a Taxonomy section - Categories, Tags and Change Author.
3.  Can't center YouTube - link or embed. Currently uses embed and increases size of video.
4.  Can't center a heading. 
5.  Very useful. Yoast SEO has a 'meter' on the Classic's sidebar that tells you if your document needs improvement.

Thank you and regards

![sidebar](https://user-images.githubusercontent.com/11298068/43891708-107d8d9c-9bdb-11e8-8f5f-b56e0d6b2f05.png)

**Comment by earnjam** [comment]
1. Categories and Tags should be above Featured Image. It's possible one of your active plugins is removing those?
![image](https://user-images.githubusercontent.com/4267290/43898522-19040d5c-9bad-11e8-9bc5-6688923346cc.png)

2. Can't speak to that one in enough detail. Perhaps should be its own issue?

3. Heading alignment can be done from the sidebar. There is a ticket to discuss whether that should be moved to the main block toolbar #7909
![image](https://user-images.githubusercontent.com/4267290/43898643-79b8bfda-9bad-11e8-816d-5621dbf56779.png)

4. Yoast appears to be making good progress on their Gutenberg integration and it should be coming soon: https://twitter.com/jdevalk/status/1027284212511109131

**Comment by earnjam** [comment]
Thanks. I'm going to close this as an issue outside of Gutenberg.

**Comment by a904guy** [comment]
To fix this, it is under /wp-admin/admin.php?page=itsec&module_type=recommended

Click Configure Settings for WordPress Tweaks
![image](https://user-images.githubusercontent.com/404081/87318025-c63adf00-c4f5-11ea-89a2-c10710c99757.png)

Scroll down to Rest API, and set it to default access.
![image](https://user-images.githubusercontent.com/404081/87317963-b15e4b80-c4f5-11ea-9617-b6453be2c0e0.png)
