### ISSUE TITLE
Quote: can get stuck with empty source placeholder

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#877]
![image](https://cloud.githubusercontent.com/assets/548849/26364334/48334104-3fe4-11e7-8d06-c9fdb8bda54c.png)

Deleting a quote source and unselecting a block is not hiding the field. It works if you reselect and unselect.

**Comment by iseulde** [comment]
@mtias Is this still an issue?

**Comment by mtias** [comment]
It's working reliably well now.
