### ISSUE TITLE
Blocks: Update RichText usage to avoid inline elements

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8773]
Related: #8451
Related: https://github.com/tinymce/tinymce/issues/4488

Using an inline element as the `tagName` property of a `RichText` element is not well-supported by TinyMCE. A few of the core blocks use inline elements for their RichText fields, and are subject to experiencing issues. They should be converted to using block-level elements (e.g. `div`, the default, as in #8451), styled as appropriate to display as though they were inline in the editor.

We should also consider whether this is something which should be documented to advise against, or even explicitly forbidden by the RichText component itself.

Blocks:

- [ ] Pullquote ([`cite`](https://github.com/WordPress/gutenberg/blob/f02064f12a148df60b8d79801858ce3699bdfb89/core-blocks/pullquote/index.js#L80))
- [ ] Quote ([`cite`](https://github.com/WordPress/gutenberg/blob/f02064f12a148df60b8d79801858ce3699bdfb89/core-blocks/quote/index.js#L214))

Reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Inline_elements#Elements

**Comment by nfmohit-wpmudev** [comment]
@aduth Submitted #8785 addressing this task. Looking forward to a review ❤️
