### ISSUE TITLE
I18N Package: reset memoization cache if needed

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#8776]
The i18n package uses [`memize`](https://www.npmjs.com/package/memize) to cache translations. That means when calling `__()` with the same arguments twice, it will fetch the translation from the cache instead of calling Jed.

Because of that it's not possible to change translations on the fly, e.g. by calling `setLocaleData()` after fetching some translations via an API because the user changed the locale in the UI.

Any memoized function has a `clear()` method. In the i18n package it would be:

```js
dcnpgettext.clear();
```

However, calling this would clear the cache for all domains, even if it wasn't needed.

So ideally there should be a way to manually clear the cache for a given domain _or_ it's done automatically when calling `setLocaleData()`.

**Comment by aduth** [comment]
Related: https://github.com/WordPress/packages/pull/101

Ideally we'd not need to do the caching ourselves from the library, and instead the underlying Jed `compile` result of plural forms would be reused.

I've also had some consideration for a "dumber" memoization cache where we simply have a plain object (`Object.create( null )`) of strings. At first I thought this would only work for default domain, but if we cache by domain (as suggested here) this could work for any domain. It would only cover `__`, and we'd need to decide if/how to cache `dcnpgettext`.

```js
const stringsByDomain = Object.create( null );

export function __( text, domain ) {
	if ( ! stringsByDomain[ domain ] ) {
		stringsByDomain[ domain ] = Object.create( null );
	}

	const strings = stringsByDomain[ domain ];
	if ( ! strings[ text ] ) {
		strings[ text ] = dcnpgettext( domain, undefined, text );
	}

	return strings[ text ];
}
```

**Comment by swissspidy** [comment]
Regarding https://github.com/WordPress/packages/pull/101: was it considered to provide an upstream PR to implement some caching there? Happy to have a look at that.

Also, while something like you suggested definitely works, it would be great to not only cover `__()` alone. The same way you leveraged `stringsByDomain` above we could store a memoized `dcnpgettext()` function per domain, I think.

**Comment by aduth** [comment]
>was it considered to provide an upstream PR to implement some caching there? Happy to have a look at that.

I don't recall whether it was considered; or at least, I don't think it was consciously decided _against_, in which case feel free to explore.

>Also, while something like you suggested definitely works, it would be great to not only cover __() alone. The same way you leveraged stringsByDomain above we could store a memoized dcnpgettext() function per domain, I think.

The main reason this works as well as it does it because beyond domain, there's only a single, string argument, which is easy to cache using it as the key of an object. Since other functions have more arguments, it's not quite so easy, at which point using `memize` makes more sense.

**Comment by swissspidy** [comment]
> The i18n package uses memize to cache translations.

That's not true anymore. Closing.
