### ISSUE TITLE
Latest Posts block: Add float alignment options

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#8777]
The Archives, Categories, and Latest Comments blocks both have float alignment options. For some reason, however, the Latest Posts block does not have float alignment options. Since all the other blocks based on legacy widgets have float alignment options, I think the Latest Posts block should have them as well.

## Related issues and PRs
- #10707 would fix this issue
- related issue for Categories block: #11415
- related issue for Archives block: #11416

**Comment by nfmohit-wpmudev** [comment]
Submitted #8814 addressing this enhancement.
