### ISSUE TITLE
Unable to add image in the classic block!

### ISSUE THREAD

**Issue by ahmadawais** [WordPress/gutenberg#8778]
All of my older posts got converted to the classic editor block. But there's no way for me to add a new image inside the classic editor block.

![image](https://on.ahmda.ws/0k0g3N0T0X1a/c)
Peace! ✌️

**Comment by kjellr** [comment]
Hi @ahmadawais — We have an issue filed for this here: https://github.com/WordPress/gutenberg/issues/7762

I'm going to close this issue so we can focus in on that one. Thanks for the submission!

**Comment by ahmadawais** [comment]
Wasn't able to find it on my own so filed it here.
