### ISSUE TITLE
Button block: add text alignment options

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#8780]
The Button block currently has the ability to be floated to the left or right, as well as the ability to be center-aligned. However, there are situations where you want to have a button shown on the right, but you do not want the wrapping behavior of floats. Therefore, I think the Button block should have text alignment options.

Notably, I am _not_ asking that the float alignment controls be removed. I am asking that text alignment controls be provided _in addition to_ the float alignment controls.

**Comment by designsimply** [comment]
Screenshot for reference:

<img width="1280" alt="screen shot 2018-08-09 at thu aug 9 11 09 33 am" src="https://user-images.githubusercontent.com/1119271/43914394-07c3f2b0-9bc5-11e8-92af-8d954795d179.png">
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14188&action=edit running WordPress 4.9.8 and Gutenberg 3.4.0 using Firefox 61.0.1 on macOS 10.13.6.</sup>

**Comment by webtrainingwheels** [comment]
Just to connect the dots.... . A couple of related  issues about float/alignment behaviour 
https://github.com/WordPress/gutenberg/issues/10299
https://github.com/WordPress/gutenberg/issues/4127

**Comment by designsimply** [comment]
> there are situations where you want to have a button shown on the right, but you do not want the wrapping behavior of floats

I am not sure this is likely to be a common enough request to warrant changing the toolbar and I think it might lead to confusion since the expectation for text alignment could be that it operates on the text of the button itself and not on the alignment of the button. I think it would be reasonable, for cases such as you've suggested, to use the "Additional CSS Class" field and some custom CSS to make the desired change. If you feel strongly that is not the case and you feel strongly that adding text alignment options to the button block for layout controls such as showing a button on the right without floating it, please reply back and let me know and I will re-open the issue for you. Thank you!

**Comment by ZebulanStanphill** [comment]
I think the main issue here is that there is no way to align a block to the left or right without also floating it. You can get away with not having a left align option in most cases because most sites default to displaying something on the left, but this is not the cause for RTL sites (or sites that support both LTR and RTL modes). I'm mainly thinking in terms of page building, e.g. the following:
![image](https://user-images.githubusercontent.com/19592990/52506455-4009c300-2bb4-11e9-8866-0dc3dcc158c9.png)

The middle section includes a button (technically a link... but so is the core Button block) right-aligned along with the rest of the content in that section to provide some visual contrast against the sections above and below.

Technically I could have right-floated that button and it would work, but not if there was anything below it in that section... unless the thing following it was using the `clear` css property. But there's no easy way to set a block to clear the previous one in Gutenberg without resorting to a CSS class, and it's far from an intuitive experience, since floats are not intended for situations like this.

This issue isn't really specific to buttons, as it affects any block that you want to align to the left or right edge of its container. Because of that, I expect this issue will end up having to be tackled anyway as things like the core Container block (and any other layout-related blocks) are developed and Gutenberg moves into full page building territory.

So I'm fine with this issue being closed. Adding text alignment options to solve this issue specifically for the Button block feels like a bit of a hack in hindsight, and a proper solution will probably appear in the near (or maybe not-so-near) future anyway.

**Comment by designsimply** [comment]
Agree about exploring it on a larger scale and also about container block as a possible place to tackle it. Thanks for the follow-up!

**Comment by buhlahkay** [comment]
This comes up all the time for me. I frequently need to right align a button, but I've never needed to float it to the right. I think text alignment makes more sense than it's current treatment.

**Comment by jayendrasinhrajput** [comment]
not this option was gone from Gutenberg to align button in centre

**Comment by davidperezgar** [comment]
Please, add again this feature
