### ISSUE TITLE
Raw Handling: Paste strips Markdown code blocks from quote

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8781]
The following snippet of Markdown, when pasted into the editor, correctly creates a Paragraph, Quote, and Paragraph block, but removes the code blocks.

https://gist.github.com/aduth/f8c8204c818a617cfad5d1dd79bb7441

Converted:

```html
<!-- wp:paragraph -->
<p>Before:</p>
<!-- /wp:paragraph -->

<!-- wp:quote -->
<blockquote class="wp-block-quote"><p>Single line comments:</p><p>Multi-line comments should be used for long comments, see also the <a href="https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/javascript/#multi-line-comments">JavaScript Documentation Standards</a>:</p></blockquote>
<!-- /wp:quote -->

<!-- wp:paragraph -->
<p>After:</p>
<!-- /wp:paragraph -->
```

**Expected behavior**

Unsure if this is intended to be covered separately by exploration of nested blocks in a quote.

At the very least, I'd expect the text should not be destroyed, even if that means it is converted to plaintext.

**Screenshots**

![image](https://user-images.githubusercontent.com/1779930/43911725-2edd816e-9bce-11e8-8c45-1f85bf8a3953.png)

**Comment by gektor-de** [comment]
Is this still the case? Can't reproduce on 4.1.1.

**Comment by aduth** [comment]
I've just re-tested, and it still eats my content.

Maybe important distinction: If copying from the Gist, at least for macOS, it's important to "Paste and Match Style", as otherwise it pastes as a table block.

**Comment by ellatrix** [comment]
@aduth That's because the quote block doesn't support anything other than paragraphs. We should change the block to use `InnerBlocks`. :)

**Comment by aduth** [comment]
@ellatrix Is there an existing issue on that effort for which we can close this in favor of?

**Comment by aduth** [comment]
Closing in favor of #15486
