### ISSUE TITLE
Incompatible with Plesk's WP Toolkit wp-includes security feature

### ISSUE THREAD

**Issue by UltimateByte** [WordPress/gutenberg#8791]
Hello there!

First time using Gutenberg, found a compatibility issue with Plesk hosting, thought it would be nice to share it with you, see if you can fix it. 

**Description**
* While the wp-includes security of Plesk's WordPress toolkit is enabled, any edition using Gutenberg malfunctions and triggers an Apache error.
* Additionally, if Fail2Ban is enabled on the server, your client IP quickly gets banned by the Apache jail for accessing restricted elements while you are just trying to edit articles.

Either Gutenberg or the WordPress Toolkit for Plesk shall address this.

**To Reproduce**
1. Run your WordPress Website on a Plesk server
2. Enable WordPress Toolkit's wp-includes enhanced security (enabled by default if WordPress was installed with it)
3. Check the Gutenberg welcome page and see errors already: "Welcome to the Gutenberg Editor" > "This block has encountered an error and cannot be previewed."
4. Check Apache logs and see this error:

```
2018-08-09 20:11:12 | Error | 217.182.172.XX | AH01630: client denied by server configuration: /var/www/vhosts/terageek.org/httpdocs/wp-includes/js/tinymce/wp-tinymce.php, referer: https://terageek.org/wp-admin/post-new.php?gutenberg-demo | Apache error
```
(Don't worry about my IP, I'm proxied)

**Screenshots**
![gutenberg error](https://user-images.githubusercontent.com/8805941/43917372-72f72cc8-9c10-11e8-856e-9af03fe6b6e0.PNG)

**Additional context**
Plesk 17.8.11 Update 16 (latest)
WordPress 4.9.8 (latest)
Gutenberg Version 3.4.0 (latest)
PHP 7.2.8 FPM
Browser detail is irrelevant, it is a server level issue, it has the same behavior using the latest Chrome and Firefox.

Hope this can be resolved with reasonable effort.
Thanks for your attention

**Comment by designsimply** [comment]
Noting that I used the `[Type] Plugin / Theme Interoperability` label because, even though the issue is about a host and security settings, this label seemed the closest fit. Please let me know if you think there's a better [label](https://github.com/WordPress/gutenberg/labels) fit.

**Comment by pento** [comment]
Thank you for the bug report, @UltimateByte!

Plesk are aware of this issue, and are working on a solution. I'd advise [reading and following this article](https://support.plesk.com/hc/en-us/articles/213925505-Unable-to-use-WordPress-plugin-403-Forbidden) from Plesk for a workaround, and notification of when it's fixed.

**Comment by UltimateByte** [comment]
I'm not sure that we can call it a bug from Plesk, it secures wp-includes after all. I'm not sure neither that Plesk will ever fix this. 
Usually, when a plugin doesn't work with the security ON, I just try not to use it... Maybe there is another way?

**Comment by pento** [comment]
We have seen a few security plugins and services that are overzealous in blocking access to parts of WordPress: Cloudflare just rolled out an update to fix the REST API being incorrectly blocked, for example.

Here's a configuration option that will only allow access to `wp-tinymce.php`, rather than the entire `wp-includes` folder: https://github.com/WordPress/gutenberg/issues/8099#issuecomment-406892450.

Also, I'd recommend following #7133: the fix for that should allow you to set `define( 'COMPRESS_SCRIPTS', false );` in your `wp-config.php` to avoid loading `wp-tinymce.php`.
