### ISSUE TITLE
Table: "Edit as HTML" minifies the code

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#8798]
I have a table and clicking "Edit as HTML" shows table's HTML but it's all minified (even though I pasted it as clean).

Can the block not compress/destroy the code that I pasted?

**Comment by manake** [comment]
Whatever is happening with this block this is not usable...

I see some random "This block has been modified externally." like 10th time already while editing this single table.

I think there is some problem with adding "custom CSS class" to it and that breaks the block but I don't provide any steps to reproduce this. It's just buggy and I use this block for the first time ever and I can't.

So, it's not possible to create and edit tables in any reasonable way without encountering many problems. Frustrating.

**Comment by manake** [comment]
It'd say this is a "bug" rather than "help request". I don't need help because I already managed to make it work but I'm reporting this because this involved a lot of frustration and wasted time.

It's completely unclear under what circumstances "This block has been modified externally." appears. It may be one/some of the following:

- If I edit table's class in "HTML mode" then the block breaks.
- Or when I add "colspan" then it can break.
- Or when I convert "td" to "th" in "HTML mode".

I don't know. I know that I'm trying to build a table but it prevents me from doing this.

And it leaves me no choice but to delete the block and re-create it every time.

**Proposed solution**
"This block has been modified externally." should never appear.

**Comment by swissspidy** [comment]
This has come up multiple times in the past, see for example #6826. Current discussion happens at #7604.

**Comment by ZebulanStanphill** [comment]
Also note that the Table block is getting some rewrites and enhancements. See #6923 and #8767.

**Comment by manake** [comment]
Thank you for your responses. I'll close this if the discussion is happening elsewhere.

Last thing I want to emphasize: If it wasn't destroying my work (if I could edit HTML without "This block has been modified externally.") then I would be happy with this block. The remaining UI changes are not important to me. I only want it to not break.
