### ISSUE TITLE
All Gutenberg Pages Are Blank (plugin conflict WP Cerber Security)

### ISSUE THREAD

**Issue by markolbert** [WordPress/gutenberg#8799]
I tried the new Gutenberg editor. But all the pages that it would bring up, however it was launched, were blank. In some cases, but not all, the page would close by itself after a few seconds.

This is on a 4.9.8 WordPress install. It's a multisite setup, so I thought the problem might've been that I installed Gutenberg from within one of the sites, rather than the network site. I did run into a problem trying to activate it after installing it that way, but the editor -- and its blank pages -- came up.

After deleting Gutenberg I tried re-installing it from the network site, simply by adding it as a plugin. This time the install went fine (no errors). But, unfortunately, the same blank page problem persisted. So I've deleted it again.

I am willing to try this thing out. But I need more than a blank page to work with :)

**Comment by youknowriad** [comment]
Which version of Gutenberg did you try to install 3.4 or 3.5?

Also, when you have a blank page, can you check the browser's console to see if you have any JavaScript error, it might be a plugin conflict and the console can give more information about that. Thanks.

**Comment by markolbert** [comment]
I've been installing 3.5.

I checked the browser console and saw an error message about access to some file being forbidden (image attached).

![gutenberg](https://user-images.githubusercontent.com/9095610/43929838-744ab696-9beb-11e8-919e-04a339f93419.png)

**Comment by youknowriad** [comment]
It looks like you have something disabling or restricting REST APIs. Do you use a security plugin?

**Comment by markolbert** [comment]
Yes, WP Cerber Security. Do I need to tweak it to allow Gutenberg to work? Do you know what I need to do?

**Comment by pento** [comment]
@markolbert: In WP Cerber Security settings, go to the Hardening tab, and uncheck the "Block access to the WordPress REST API" settings.

**Comment by markolbert** [comment]
Okay, that got me a non-blank page :). Thanx!

BTW, when I opened an existing post to edit, I got the following error box:

Failed to load plugin url: http://council.olbert.com/wp-content/plugins/nivo-slider-pro/scripts/mce-nivoslider/nivoslider.js

That looks like a problem unique to the nivoslider. Is there a known problem with that plugin? BTW, I'm happy to close this thread and start a new one about the slider if that's protocol.

**Comment by pento** [comment]
@markolbert: Could you open a new issue? Please include any errors that show in your browser's JavaScript console.

**Comment by markolbert** [comment]
Will do!

Sent from my iPad

On Aug 9, 2018, at 9:15 PM, Gary Pendergast <notifications@github.com<mailto:notifications@github.com>> wrote:


@markolbert<https://github.com/markolbert>: Could you open a new issue? Please include any errors that show in your browser's JavaScript console.
