### ISSUE TITLE
First item in list cannot be deleted when the list is the first block

### ISSUE THREAD

**Issue by jeremyfelt** [WordPress/gutenberg#8804]
**Describe the bug**

In Gutenberg 3.5.0, when there is no other block above the list block, the first list item in that list block cannot be deleted by continuously hitting the delete key.

**To Reproduce**
1. Add a list block as the only block
2. Add more than one list item
3. Focus on the first list item
4. Try to delete the full list item with the delete key

**Expected behavior**

I expect (at a minimum) to be able to delete the first item. I would love if it then created an empty paragraph. See #8803 for more details on desired behavior similar to Dropbox Paper.

**Screenshots**

![no-delete-first-item](https://user-images.githubusercontent.com/286171/43935711-139af760-9c0a-11e8-8a1a-d5f2ba418372.gif)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Chrome
 - Version: 68.0.3440.106

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 3.5.0 with Firefox 61.0.2 on macOS 10.13.6.

**Comment by youknowriad** [comment]
Unless, I'm not testing properly, this seems fixed to me. Let's reopen if not.

**Comment by jeremyfelt** [comment]
This is still happening for me, though I did notice this time that the first item can be deleted if I move the cursor to the beginning of the second item first. I could see classifying this as a bug or as a part of the #8803 enhancement. I'm going to reopen just to confirm. :)

* If the cursor is on the first item, I can't continue to hit the "delete" key to remove the item.
* If I move the cursor to the beginning of the second item, the "delete" key will work to remove the first item.

![delete-first-list-item](https://user-images.githubusercontent.com/286171/55657714-04543980-57b0-11e9-8fac-f6a78961bb54.gif)

**Comment by aduth** [comment]
Can you clarify: When you say "Delete" key, do you mean "Backspace" or "Delete" (as in a forward deletion). The forward-delete <kbd>Delete</kbd> should currently achieve the effect of removing the first item (merging two the second item).

I'm not sure I necessarily expect the current behavior of <kbd>Backspace</kbd> to be incorrect, though I suppose it could make sense to remove the item and insert a preceding paragraph. If we go that route, I wonder if it should apply to _any_ list, regardless of whether it's the first in the post, when pressing <kbd>Backspace</kbd> at the start of the first list item.

**Comment by jeremyfelt** [comment]
I mean the "delete" key in the upper right of a Macbook Pro keyboard, which is probably the same as a "Backspace" key in the larger scope of keyboards. I have not tried anything with fn + delete, which I think would mimic the behavior of a forward-delete key.

**Comment by ellatrix** [comment]
Fixed by #18032.
