### ISSUE TITLE
Why Clutterberg

### ISSUE THREAD

**Issue by phirow** [WordPress/gutenberg#8809]
If you have a question you have a few places that you can ask this:

- Support Forums: https://wordpress.org/support/plugin/gutenberg
- Handbook: https://wordpress.org/gutenberg/handbook
- https://chat.wordpress.org #core-editor

If you are unable to ask in those places you can ask here, however you will get faster responses through those recommended places.

**Comment by swissspidy** [comment]
@phirow Was this intended as a reply to another issue or something else? Not sure what to do with your issue here 🙂

**Comment by youknowriad** [comment]
I'm closing as there's nothing tangible on this issue.
