### ISSUE TITLE
Missing uploading indicators when uploading images or videos

### ISSUE THREAD

**Issue by hochitom** [WordPress/gutenberg#8810]
I'm using gutenberg since three months very heavily and i really like it. One thing that annoys me is the missing of uploading indicators when uploading images or videos. especially when working with galleries with several images and with slow networks this is a pain, because it is not visible if the images are already uploaded.

A Solution for this can be a small loading bar above/below the images that indicates that the images are currently uploaded.

**Comment by designsimply** [comment]
Adding a screenshot and short video illustrating the current flow of uploading images into a gallery for reference. ([24s](https://cloudup.com/cyU7Ni9tSzW))

![gallery-images-in-gutenberg-3 5-mid-upload](https://user-images.githubusercontent.com/1119271/43978367-4536c0d4-9ca4-11e8-8221-99362fec6a47.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14195&action=edit running WordPress 4.9.8 and Gutenberg 3.5.0 using Firefox 61.0.2 on macOS 10.13.6.</sup>

**Comment by jasmussen** [comment]
This is the process in Gutenberg:

![gutenberg](https://user-images.githubusercontent.com/1204802/46612212-3130d800-cb10-11e8-83e8-378b7ca1c066.gif)

This is the process in the classic editor:

![classic](https://user-images.githubusercontent.com/1204802/46612231-355cf580-cb10-11e8-9d2d-e758f4eda2e3.gif)

This is how WordPress.com does it:

![calypso](https://user-images.githubusercontent.com/1204802/46612309-71905600-cb10-11e8-9581-3860c2eb3971.gif)


I agree that the Gutenberg process can be a bit too clever for its own good (possibly related: #10251, #10091). 

Let's move closer towards what the classic editor and the WordPress.com editor do both:

- _very_ dimmed previews of the images, like 20% opaque
- progressbar overlay
- filename should be displayed below the progressbar

**Comment by mtias** [comment]
@noisysocks let's also include at least the spinner component on those images, as the fading could not be clear enough.
