### ISSUE TITLE
What's solution for blocks that has updated externally?

### ISSUE THREAD

**Issue by vicolaspetru** [WordPress/gutenberg#8813]
I have created a plugin for Gutenberg blocks, and when it is necessary to change a block HTML, I get message dialog with "This block appears to have been modified externally...".
So, how I as developer can prevent this issue?
If we think so, every time we update the block, the user will have to re-create the block that has been modified.

**Comment by swissspidy** [comment]
This has come up multiple times in the past. Current discussion happens at #7604.

**Comment by youknowriad** [comment]
Let's close in favor of #7604
