### ISSUE TITLE
Undefined function register_block_type() 

### ISSUE THREAD

**Issue by dariuszdawidowski** [WordPress/gutenberg#8815]
Today, just after Gutenberg update to 3.5.0 I have:

Fatal error: Uncaught Error: Call to undefined function register_block_type() 
After searching web I tried to add also wp-edit dependency but didn't help.

macOS/Latest Chrome

My code:
```
function frontpress_block_cta_register()
{
    wp_register_script('frontpress-block-cta-editor-script', plugins_url('block.js', __FILE__), array('wp-blocks', 'wp-element', 'wp-i18n'));
    wp_register_style('frontpress-block-cta-editor-style', plugins_url('editor.css', __FILE__), array('wp-edit-blocks'));
    wp_register_style('frontpress-block-cta-style', plugins_url('style.css', __FILE__), array());
    register_block_type('cta/block', array(
        'editor_script' => 'frontpress-block-cta-editor-script',
        'editor_style' => 'frontpress-block-cta-editor-style',
        //'script' => '',
        'style' => 'frontpress-block-cta-style',
    ));
}

add_action('init', 'frontpress_block_cta_register');

```

**Comment by dariuszdawidowski** [comment]
Ah got it. Gutenberg plugin was deactivated...
Ok. So this is solved.
But actually this is also issue - it deactivates byself after update.

**Comment by swissspidy** [comment]
> But actually this is also issue - it deactivates byself after update.

That's usually not the case with WordPress. WordPress does not deactivate plugins during updates. There must have been something else interfering with that. Hard to tell after the fact from the outside 🙂 

P.S. It's always a good idea to use `if ( function_exists( 'register_block_type' ) ) { … }` to prevent such cases.
