### ISSUE TITLE
Where are the special characters? (using Wordpress Version 4.9.8)

### ISSUE THREAD

**Issue by tamaramyoho** [WordPress/gutenberg#8817]
Hi, 
I have just installed Gutenberg to try out as the new editor in Wordpress Version 4.9.8 and just getting to know it.
However I noticed that the icon for "special characters" is not available in the list of five formatting options within the paragraph block, in the paragrah options for transform, nor in the settings side bar menu for text size and colour etc.  I write up recipes and I need glyphs for fractions. Where can I find them in Gutenberg editor?

If not, it would be great to have them at ones fingertips before it becomes the default editor for Wordpress come September.

many thanks,
Tamara

P.S. I found it in the classic style block...but is there not a shortcut?

**Comment by designsimply** [comment]
Welcome! The character map was discussed in #1678 and ended with special characters being accessible in the Classic block (like you found!) and encouragement to implement it as a plugin for other blocks. I would like to close this issue and consolidate at #1678.

If you still feel strongly, consider adding details about your use case in #1678 even though it has been closed. If it does get re-visited later, it will be good to have a list of use cases in one place.
