### ISSUE TITLE
The server-side rendering block matcher doesn't match blocks with - (hyphen)

### ISSUE THREAD

**Issue by lamosty** [WordPress/gutenberg#882]
I'm building a ["latest posts" block](https://github.com/WordPress/gutenberg/pull/870) and am trying to add server-side rendering to it. However, it seems like the [$open_matcher](https://github.com/WordPress/gutenberg/blob/master/index.php#L124) doesn't like hyphens in the block names. For example, when I removed the hyphen from `wp:core/latest-posts` to `wp:core/latestposts`, it matched my block.

/cc @youknowriad

**Comment by nylen** [comment]
Fixed via #1152.
