### ISSUE TITLE
Gutenberg plugin fails with "Warning: Unknown class passed as parameter"

### ISSUE THREAD

**Issue by scyg** [WordPress/gutenberg#8823]
During installation and when attempting to edit a post, all that appears on the screen is this dialog: Warning: Unknown class passed as parameter in /home/content/46/14010646/html/blog/wp-content/plugins/gutenberg/lib/rest-api.php on line 40. Gutenberg 3.5.0 
WordPress 4.9.8

**Comment by designsimply** [comment]
When you have a blank page, can you check the browser's console to see if you have any JavaScript error, it might be a plugin conflict and the console can give more information about that. Thanks.

**Comment by tofumatt** [comment]
The issue reported here sounds like a PHP error that's appearing on the screen, so I'm not sure JS console will be helpful. But a screenshot and a list of installed plugins would help. If you disable all plugins on your site does the error still appear?

**Comment by designsimply** [comment]
Closing for now. We can re-open after more info is added.

**Comment by TimothyBJacobs** [comment]
@razidahmad Which version of PHP are you running?

**Comment by razidahmad** [comment]
@TimothyBJacobs Godaddy hosting control panel says 5.6, but php -v says 5.4.19.  Does Gutenberg have a higher PHP requirement than the Wordpress core code?

**Comment by TimothyBJacobs** [comment]
Nope, but doing some research that error code seemed to be associated with < php 5.3.9. The error doesn't make much sense, both `WP_REST_Posts_Controller` and `WP_REST_Controller` class should be defined already.

Do you have any custom code running?

**Comment by razidahmad** [comment]
@TimothyBJacobs It's a new install.  Gutenberg is the only plugin.  The warning message no longer appears after I created a Gutenberg native page, even when loading older pages.  The issue that remains is that old pages are only editable via the classic editor or via the code editor in Gutenberg.  The visual editor in Gutenberg does not work pages created with the classic editor, even for ultra basic text only pages.

**Comment by razidahmad** [comment]
Another update - Figured out what needed to be done to avoid re-doing all pages as Gutenberg native.  

For the blocks that don't appear in visual editor, hovering over the block shows a "More Options" menu.  Select "Convert to Blocks" and everything is good to go!  The pages even show the "- Gutenberg" suffix in the Pages list view.  

In retrospect, it seems the warning is related to pages needing conversion to Gutenberg native format.
