### ISSUE TITLE
Option to add selected word like a tag

### ISSUE THREAD

**Issue by dyegocruz** [WordPress/gutenberg#8827]
Would it be nice if I could select a word and gutenberg show me an option to add this same word like a tag on the post.

**Comment by youknowriad** [comment]
To be honest, I don't think we'll ever do that, we try to make the UI as clean as possible and there's already a lot of toolbars/options etc...

That said, A Plugin for this might make sense.

cc @jasmussen @karmatosed for confirmation. Should we close?

**Comment by jasmussen** [comment]
Long term I would love for an API to exist in Gutenberg, so plugins could easily add this type of feature. I can imagine a million cool plugins. 

But I also think it won't be realistically implemented in V1, so we should probably file this under "ideas" and close for now.

**Comment by youknowriad** [comment]
I think @iseulde is working on the API that allows these kind of things.
