### ISSUE TITLE
Trying to change the meta tags freezes my web browser and website becomes unresponsive

### ISSUE THREAD

**Issue by tecnogaming** [WordPress/gutenberg#8828]
## Issue Overview
Yoast SEO Plugin + wordpress 4.9.8 + Gutenberg = freezes when adding tags to the post.

## Steps to Reproduce (for bugs)
1. install Yoast SEO
2. update wordpress to 4.9.8
3. install gutenberg
4. create a post and then try to add several meta tags.

Chrome web browser

## Expected Behavior
Add tags and let me save the article.

## Current Behavior
website freezes and becomes unresponsive.  The saving status gets stuck at saving...

**Comment by PanuWeb** [comment]
I have the same problem. Gutenberg freezes, by placing the cursor on the buttons to add block, update post, when selecting a block. It is usually before clicking. Sometimes the freezing is long (3-4 sec), other times it is hardly noticeable, in the range of milliseconds.

Looking for a solution I came to this problem and by deactivating yoast I did not have any more problems.

WordPress 4.9.8
Gutenberg 3.6.2
Yoast SEO 8.0

**Comment by PanuWeb** [comment]
I have posted this same problem in the Yoast repository: https://github.com/Yoast/wordpress-seo/issues/10798

**Comment by PanuWeb** [comment]
In an initial test it seems that the problem will improve. Later I will use them again in production and I will post the results again.

**Comment by youknowriad** [comment]
Let's close as it seem solved in Yoast SEO 8.1. Thanks
