### ISSUE TITLE
Consider renaming wp-block-columns to wp-block-row

### ISSUE THREAD

**Issue by timlogemann** [WordPress/gutenberg#8830]
The block that contains 2 columns is called 'wp-block-columns' the column inside of it are called 'wp-block-column'. This is, in my opinion, highly confusing and prone to typos.

Renaming the wrapper block to 'wp-block-row' is much less prone to typos and would mimic css frameworks like bootstrap and foundation.

**Comment by karmatosed** [comment]
I feel this could have a lot of implications. It would need to sort out some backwards compatibility. I am inclined to suggest we don't do this just for typo issues, also not sure we should to align simply with other frameworks. That said, if there is a reason beyond that let's give it space to be heard.

**Comment by ZebulanStanphill** [comment]
Several months ago, I would have agreed that the block should be called `wp:row`. But having read lots of discussions on all the things that could happen in the future with handling layouts in Gutenberg, I think the name `wp:columns` is actually the best name.

What if Gutenberg adds a block that uses CSS Flex to lay out children horizontally? That could still count as a row, but it would not be using columns, or at least not in the traditional sense. That block could be called `wp:row`.

And then there is the proposed Container block. The Container block could act as a row if it has flex direction options, but then you would not call it a Row block if you can switch between horizontal and vertical stacking of children.

I now think `wp:columns` is pretty much a perfect name for the Columns block. It is exactly what it says on the tin: a block with columns. Even if the Container block ends up having a lot of the functionality of a row via children stack direction options, I think it will most likely not have traditional columns like the Columns block. Columns would be what makes the Columns block unique, so I think the name fits perfectly.

Of course, the name displayed to users could always be changed to "Row", but I see no reason to change the technical name, or at least not until Gutenberg gets to the stage where it focuses on page building aspects and there is a clearer direction for what the standard layout blocks will be.

See also #4900, especially the more recent discussions in the comments.

**Comment by youknowriad** [comment]
Closing as the block shipped so there's a Backward compatibility concern now and let's see how the section block would work before.
