### ISSUE TITLE
No ability to view images in my media library

### ISSUE THREAD

**Issue by TzinaVarotsi** [WordPress/gutenberg#8838]
I clicked add image block you got text saying “Drag an image, upload a new one or select a file from your library.”, but I can only upload an image. It does not give me the ability to open media library and to see already uploaded images. So writing a post I have to active and (when I want to add images from the library) to reactive your plugin. It's so pity because I love it! Could you repair it?

  Desktop 
 - Os: MacOs High Sierra
 - Browser safari
 - Version of Mac 10.13.6
 -Version of safari 61.0.2

 Thank you in advance
Tzina Varotsi

**Comment by youknowriad** [comment]
It's already possible to open the media library to choose from. See, the "Media Library" button here.

<img width="645" alt="screen shot 2018-08-10 at 16 35 21" src="https://user-images.githubusercontent.com/272444/43967062-6ff5c52e-9cbb-11e8-97df-d05145d01f32.png">

**Comment by TzinaVarotsi** [comment]
@youknowriad , there is not this possibility.. perhaps I have to unistall the plugin and in install it again.

**Comment by TzinaVarotsi** [comment]
Could you please do something about this problem? I have a travel blog which means that in every post there are many photos. As my blog is bilingual you can understand that I have to upload many photos twice!!

**Comment by caxco93** [comment]
Please share with us which version of Gutenberg you are currently using.
You can find it on your list of installed plugins.
![image](https://user-images.githubusercontent.com/3190666/44006418-c859019c-9e49-11e8-85ec-eef9cb17d2d0.png)

**Comment by TzinaVarotsi** [comment]
Hello, it's 3.5.0 version

**Comment by youknowriad** [comment]
> Could you please do something about this problem?

I would love to do something about it, unfortunately, it's very hard to know what's happening because I can't reproduce. I think it's most likely a plugin conflict but that's just a guess. Do you see any errors in the console? What plugins do you have on your site?

**Comment by TzinaVarotsi** [comment]
Ι don't see any errors. The plugins I have on my site are: Ad Inserter, Akismet Anti-Spam, All 404 Redirect to Homepage, Contact Form 7, Default featured image, Google Analytics Dashboard for WP (GADWP), Google XML Sitemaps, greeklish-permalinks, Gutenberg, Imagify, Instagram Feed, MailChimp for WordPress, OneSignal Push Notifications, Polylang, Redux Framework, Social Warfare, SSL Insecure Content Fixer, TinyMCE Advanced, W2E Image Optimizer, Webmaster Tools, WP Content Copy Protection, WP Force SSL, WP Rocket Yoast SEO, Αναρτήσεις δημοσιευμένες απότον Χρήστη

**Comment by youknowriad** [comment]
I suspect one of these plugins overrides the `wp.hooks` global. Can you paste this to the console and send the result `console.log(Object.keys(wp.hooks));`

Also, maybe you can try to disable the plugins one by one to find the cause.

**Comment by meymigrou** [comment]
![gutenberg problem with uploading images](https://user-images.githubusercontent.com/30810726/44144443-355a5d52-a090-11e8-9573-4ed4e73a2cc9.png)

@youknowriad here's a screenshot from the console.

`JQMIGRATE: Migrate is installed, version 1.4.1
index.js?ver=1534000402:1 paragraphs block class set is-small-text, ..., is-large-text is deprecated and will be removed from Gutenberg in 3.6. Please use has-small-font-size, ..., has-large-font-size class set instead. Note: If paragraphs using this classes are opened in the editor new classes are automatically applied the post just needs to be saved. This is a global warning, shown regardless of whether the classes are used in the current post.
u @ index.js?ver=1534000402:1
jn @ index.js?ver=1534000402:12
(anonymous) @ post.php?post=10571&action=edit:2528
console.log(Object.keys(wp.hooks));
VM3109:1 (7) ["removeFilter", "applyFilters", "addFilter", "removeAction", "doAction", "addAction", "storage"]0: "removeFilter"1: "applyFilters"2: "addFilter"3: "removeAction"4: "doAction"5: "addAction"6: "storage"length: 7__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flatMap: ƒ flatMap()flatten: ƒ flatten()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()arguments: (...)caller: (...)length: 1name: "reduceRight"__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]reverse: ƒ reverse()shift: ƒ shift()arguments: (...)caller: (...)length: 0name: "shift"__proto__: ƒ ()[[Scopes]]: Scopes[0]slice: ƒ slice()arguments: (...)caller: (...)length: 2name: "slice"__proto__: ƒ ()apply: ƒ apply()arguments: (...)bind: ƒ bind()call: ƒ call()caller: (...)constructor: ƒ Function()length: 0name: ""toString: ƒ toString()Symbol(Symbol.hasInstance): ƒ [Symbol.hasInstance]()get arguments: ƒ ()set arguments: ƒ ()get caller: ƒ ()set caller: ƒ ()__proto__: Object[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0][[Scopes]]: Scopes[0]No propertiessome: ƒ some()arguments: (...)caller: (...)length: 1name: "some"__proto__: ƒ ()[[Scopes]]: Scopes[0]sort: ƒ sort()arguments: (...)caller: (...)length: 1name: "sort"__proto__: ƒ ()[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0]splice: ƒ splice()arguments: (...)caller: (...)length: 2name: "splice"__proto__: ƒ ()[[Scopes]]: Scopes[0]toLocaleString: ƒ toLocaleString()arguments: (...)caller: (...)length: 0name: "toLocaleString"__proto__: ƒ ()[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0]toString: ƒ toString()Symbol(src)_1.p2qnzbb70x: "function toString() { [native code] }"Symbol(src)_1.tgjdtoemsk: "function toString() { [native code] }"arguments: (...)caller: (...)length: 0name: "toString"__proto__: ƒ ()[[FunctionLocation]]: <unknown>[[Scopes]]: Scopes[0]unshift: ƒ unshift()arguments: (...)caller: (...)length: 1name: "unshift"__proto__: ƒ ()[[Scopes]]: Scopes[0]values: ƒ values()Symbol(src)_1.0zjpz760e6: "function values() { [native code] }"arguments: (...)caller: (...)length: 0name: "values"__proto__: ƒ ()[[Scopes]]: Scopes[0]Symbol(Symbol.iterator): ƒ values()Symbol(src)_1.0zjpz760e6: "function values() { [native code] }"arguments: (...)caller: (...)length: 0name: "values"__proto__: ƒ ()[[Scopes]]: Scopes[0]Symbol(Symbol.unscopables): copyWithin: trueentries: truefill: truefind: truefindIndex: trueflatMap: trueflatten: trueincludes: truekeys: truevalues: true__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
undefined`

**Comment by youknowriad** [comment]
From the screenshot, it's clear to me that there's something (a plugin, a theme) that altered the `wp.hooks` global. See it's different for me 
<img width="1648" alt="screen shot 2018-08-15 at 11 48 09" src="https://user-images.githubusercontent.com/272444/44144865-1e66511e-a081-11e8-8e6e-c0b34f698c5b.png">

We had this issue with an old version of ACF adding their own `wp.hooks` global. I suspect other plugins might use the same `wp.hooks` library.

**Comment by meymigrou** [comment]
What is the easiest way to find out witch plugin or theme has altered the `wp.hooks`?

**Comment by youknowriad** [comment]
Disabling them one by one, or trying them in a fresh install. You can use http://poopy.life/ to setup a quick WP install and try the plugins there.

**Comment by meymigrou** [comment]
I have already tried to deactivate all the plugins. Maybe it's the theme's fault?

**Comment by youknowriad** [comment]
It's possible, try using the theme in a fresh install and see how it goes

**Comment by meymigrou** [comment]
I'm on it! Thank you for replying so quick!

**Comment by meymigrou** [comment]
It's the theme's problem. I've just installed it in a fresh WordPress installation using XAMPP and I have the same problem. Speaking with the developers of the themes, I've been told that they will update the theme when it [Gutenberg] will be officially released. Quick to answer, yet not very helpful. Thanks for your help @youknowriad.

**Comment by youknowriad** [comment]
Ok Good luck ;)
