### ISSUE TITLE
Button Hover

### ISSUE THREAD

**Issue by wongpk** [WordPress/gutenberg#8841]
**Is your feature request related to a problem? Please describe.
A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]**
Currently the button when hover, it seems the text hover to the theme link hover colour.

**Describe the solution you'd like
A clear and concise description of what you want to happen.**
Maybe add a hover state colour settings on editing.

**Describe alternatives you've considered
A clear and concise description of any alternative solutions or features you've considered.**
Keep the exact same text/background colour when hover.

**Comment by youknowriad** [comment]
Dupliccate of #4543, Thanks for the report
