### ISSUE TITLE
Change text colour

### ISSUE THREAD

**Issue by CulturalCat** [WordPress/gutenberg#8844]
How do I change the colour of text in the new Gutenborg world.  Text with hyperlinks is just black and I want it to be blue.

**Comment by samtoll** [comment]
Adding to this, when selecting a single word in the block and then changing that word to a color in the text color sidebar changes all text in the entire block to the new color.

**Comment by designsimply** [comment]
Thanks for submitting this issue. There's an existing discussion around changing color of selected text in #6080 and you can follow along there if you'd like. In the mean time, consider using the classic block or head over to the support forum at https://wordpress.org/support/plugin/gutenberg/ if you want to get into a more detailed discussion about other possible workarounds.
