### ISSUE TITLE
Missing TinyMCE plugin file in /vendor/plugins/lists/plugin.min.js

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#885]
I'm currently getting this error in master a lot:

![screen shot 2017-05-24 at 12 46 30](https://cloud.githubusercontent.com/assets/1204802/26399924/0c69a73a-407f-11e7-926f-44784e108f52.png)

Looks like it might be from the List block, which seems to assume that a plugin file is there, but it's not. This is all I have in my `vendor/` directory:

![screen shot 2017-05-24 at 12 47 19](https://cloud.githubusercontent.com/assets/1204802/26399952/280bbffa-407f-11e7-812e-18a97679cbb6.png)

The block seems to reference a file in `/vendor/plugins/lists/plugin.min.js`. It was probably not committed due to the `.gitignore` file in that vendor directory.

**Comment by iseulde** [comment]
See #863.

**Comment by jasmussen** [comment]
New information has come to light in https://github.com/WordPress/gutenberg/pull/862#issuecomment-303789954, so closing.
