### ISSUE TITLE
Block audit: Spacer

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#8852]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="49" alt="screen shot 2018-08-10 at 3 00 50 pm" src="https://user-images.githubusercontent.com/1202812/43976319-313fa46a-9cae-11e8-99be-4d8ca0327d15.png">

**Name:** Spacer
**Description:** Add an element with empty space and custom height.
**Category:** Layout Elements
**CSS class:** `wp-block-spacer` in frontend and editor
**Can be converted to:** (Nothing)

# States

*Selected/Placeholder:*

<img width="657" alt="screen shot 2018-08-10 at 2 43 01 pm" src="https://user-images.githubusercontent.com/1202812/43976345-3f2d3240-9cae-11e8-894f-6ca4dfd9cadd.png">

*Unselected:*

<img width="655" alt="screen shot 2018-08-10 at 2 43 06 pm" src="https://user-images.githubusercontent.com/1202812/43976370-50e2af56-9cae-11e8-9f0e-8a1097e692dc.png">

# Primary (toolbar) settings

Spacer Settings: Height in pixels
Advanced: Additional CSS Class

# Secondary (sidebar) settings

Gallery Settings: Columns, Crop Images, Link to
Advanced: Additional CSS Class

# Frontend appearance

_(Block is designed to be basically invisible. 🙂)_

# Documentation

No devdocs yet.

# Bugs/errors

_Individual issues will be opened for these soon_

- [x] Block does not function in IE11 (https://github.com/WordPress/gutenberg/issues/8613)
- [x] The block appears broken on small screens (#8853)

# Suggestions

_Individual issues will be opened for these soon_

- There's currently no way to adjust the height of the spacer using the keyboard, without jumping into the sidebar. I'm not 100% sure if that's a problem or not.

**Comment by ZebulanStanphill** [comment]
>There's currently no way to adjust the height of the spacer using the keyboard, without jumping into the sidebar. I'm not 100% sure if that's a problem or not.

What if the size input appeared in the block when you selected it, rather than being in the inspector?

**Comment by mrwweb** [comment]
Relevant issue regarding front-end display: #10081

**Comment by bracketsberlin** [comment]
I don't know if it's valid to make a suggestion here, but I think the spacer block should be extended by a **mobile spacing value**. Right now, there is only one value that is applied to all screen sizes.

**Comment by ZebulanStanphill** [comment]
@bracketsberlin For reference, there's some related discussion in #13363 about how responsive controls should work in blocks, which will likely affect how responsive settings in the Spacer block would be implemented.

**Comment by karmatosed** [comment]
Closing for now as the audit has produced a few solid tickets. Thanks everyone.
