### ISSUE TITLE
Gutenberg Activation from Callout

### ISSUE THREAD

**Issue by maslerdanch** [WordPress/gutenberg#8854]
Trial Gutenberg from callout (4.9.8) - Initially after Installation and Activation results in standard WP error page 'Sorry, you are not allowed to access this page.' whilst accessing ../wp-admin/network/admin.php?page=gutenberg  

Accessing plugins shows installation of the plugin correctly.

Demo for new post results in a blank page.
Demo for new page results correctly.
Some pages result in gutenberg loading correctly but less than 10%.

WIN 10 Pro
FF/Chrome
Mu

![sorry - no access - activating gutenberg](https://user-images.githubusercontent.com/4353002/43981157-939bd752-9ce8-11e8-9056-5b0e0fdcfd36.png)
![add new page works](https://user-images.githubusercontent.com/4353002/43981152-931f626c-9ce8-11e8-84d1-a9c556875049.png)
![blank pages on edit](https://user-images.githubusercontent.com/4353002/43981153-933a3e84-9ce8-11e8-901f-a3ccc74100c7.png)
![gutenberg demo](https://user-images.githubusercontent.com/4353002/43981154-93518d50-9ce8-11e8-8672-575ade51fa90.png)
![sketch](https://user-images.githubusercontent.com/4353002/43981155-936b37d2-9ce8-11e8-9d4f-bc4b3ffce83b.png)
![some pages work](https://user-images.githubusercontent.com/4353002/43981156-9382a5b6-9ce8-11e8-887d-5cb0f7acf74d.png)

**Comment by lookingafar** [comment]
Same thing. After activation adding new post or new page results in a blank page. Win 10 Pro, Firefox. Gutenberg > Demo also results in a blank page.

**Comment by pento** [comment]
Thanks for the bug report, @maslerdanch! This is a bug in how the callout is implemented, we're tracking over on [WordPress Core Trac](https://core.trac.wordpress.org/ticket/44747).
