### ISSUE TITLE
Multiple Problems with Media Library

### ISSUE THREAD

**Issue by lacheby** [WordPress/gutenberg#8855]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by danielbachhuber** [comment]
Hi @lacheby,

Can you share more detail on what you mean by "Multiple Problems with Media Library"?

**Comment by lacheby** [comment]
Sure!

I've been unable to edit photos, particularly when selecting the Feature
Image. I'll click on the desired photo and another window will open for
photo editing, except that it doesn't allow you to edit the photos and then
insert them as the Feature Image. I've been kind of stuck in a loop. After
repeated attempts I switched back to the Classic editor to complete the
task.

I also noticed that when attempting to insert a photo into an article, the
Gutenberg editor was placing the photo block at the end of all the content
blocks, even when the first step was to have the photo in between blocks of
text. This again prompted me to switch back to the Classic version when
dealing with photos.

In general, I like where the Gutenberg version is headed. Much improved,
very modern and has some nice new features to spark creative options in
digital content development.


Matt Chebatoris
*Founder & Managing Editor*
*PaddleXaminer.com <http://PaddleXaminer.com>*
Phone: 310-743-4455
Email: matt@paddlexaminer.com

**Comment by danielbachhuber** [comment]
> I'll click on the desired photo and another window will open for photo editing, except that it doesn't allow you to edit the photos and then insert them as the Feature Image.

Can you describe what you mean by this in greater detail? A short video of your screen would be very helpful.

I wasn't able to reproduce this on my local install. I was able to successfully open the Media Library, edit an image, and then assign the edited image as the featured image.

> I also noticed that when attempting to insert a photo into an article, the Gutenberg editor was placing the photo block at the end of all the content blocks, even when the first step was to have the photo in between blocks of text.

If you could provide a screencast of this too, it would be greatly appreciated.

**Comment by designsimply** [comment]
> When selecting the Feature Image. I'll click on the desired photo and another window will open for photo editing, except that it doesn't allow you to edit the photos and then insert them as the Feature Image.

I was able to get this to work—though there's a little bit of a disconnect between when you edit and closing that window and selecting the image just edited, it should be working in the end. ([48s](https://cloudup.com/cyewklY48Oj))

> I also noticed that when attempting to insert a photo into an article, the Gutenberg editor was placing the photo block at the end of all the content blocks, even when the first step was to have the photo in between blocks of text.

I couldn't reproduce this problem. I tested dragging an image into a post between two paragraph blocks and dropping it there after I see the blue drag and drop indicator appear and it worked in my tests. If you are adding an image a different way, please reply back with a little more detail about how you are adding images and please include a note about your browser version.

**Comment by lacheby** [comment]
Thanks for following up. I think the problem may be associated with my
theme, MH Newspaper. I contacted them because the photos were displaying
one way in the editor and another way when the content was published. They
responded that they have not fully updated the theme to accommodate all of
Gutenberg's functionality yet and were waiting until the final version was
issued so they would have a firm baseline to work from.

All in all, I like what's been done with Gutenberg. It is a major upgrade
and vastly superior to the old classic editor. Can't wait for the final
version to be released!

Matt Chebatoris
*Founder & Managing Editor*
*PaddleXaminer.com <http://PaddleXaminer.com>*
Phone: 310-743-4455
Email: matt@paddlexaminer.com
