### ISSUE TITLE
Post update fails with error 400 only on some browsers

### ISSUE THREAD

**Issue by SMH17** [WordPress/gutenberg#8857]
When I try to update a post with the Gutenberg plugin the request fails with error 400, I'm able to reproduce this issue only on Edge Browser and the more obvious solution to clear all browser data, cache cookies doesn't solve the problem. 

This issue doesn't happen on Chrome and Firefox browsers, I haven't tested further browsers at the moment.

I use Cloudflare CDN, PHP 7, Maria DB, linux server.

**Comment by aduth** [comment]
I am not able to reproduce this error in Microsoft Edge. A 400 error would imply that there is bad request fields being included in the request. Being browser-specific could imply some interference of a browser extension.

Can you clarify the following details?

- Which version of Gutenberg / WordPress are you running?
- Do you have access to another site to see if similar errors occur, or if it's specific to your one site? 
   - You can create a temporary test site at [jurassic.ninja](https://jurassic.ninja/) to verify
- What browser extensions are you using, if any?
- What WordPress plugins are you using, if any?
