### ISSUE TITLE
Editor crash on scrolling demo post

### ISSUE THREAD

**Issue by KleinDevDE** [WordPress/gutenberg#8858]
**Describe the bug**
Editor crash on scrolling demo post (Gutenberg v3.5.0)

**To Reproduce**
1. Open the Gutenberg demo post
2. Scroll down (above the video)
3. Gutenberg editor crash

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 61.0.1

**Error report**
value@https://blog.klein-max.de/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533946410:12:208789
Xf@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:91:266
yh@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:102:317
lg@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88
mg@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386
gc@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202
vb@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230
ub@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65
zd@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:124:449
ra@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:123:319
enqueueSetState@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:189:231
q.prototype.setState@https://blog.klein-max.de/wp-content/plugins/gutenberg/vendor/react.min.ab6b06d4.js:18:428
value@https://blog.klein-max.de/wp-content/plugins/gutenberg/build/editor/index.js?ver=1533946410:12:225603
jg/c.fire@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:190468
fire@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:190978
vh/this.nodeChanged@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:211670
nodeChanged@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:330175
vh/<@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:211157
jg/c.fire@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:190468
fire@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:190978
ip@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:192533
t@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:193010
C@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:11105
d@https://blog.klein-max.de/wp-includes/js/tinymce/wp-tinymce.php?ver=4.9.8:2:11256

**Comment by Robertght** [comment]
Hey!

Thanks for reporting this!

I've just checked the demo post on Gutenberg 4.1.1 and I cannot replicate the issue anymore.
Could you confirm if that's not an issue anymore?

Here are my specs:

OS: Windows 10
Browser Firefox
Version 63

**Comment by designsimply** [comment]
If updating to the latest version of WordPress (currently 5.0.2) and uninstalling the Gutenberg plugin (it is no longer needed unless you are working on development for the project or beta testing) does not solve the problem, please re-open this issue and if possible please check to see if you can get more detailed error information from the console panel in your browser's web developer tools.
