### ISSUE TITLE
Blocks: Allow custom CSS classes on a block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#887]
Idea by Jesse Friedman: Auto-ID every block and let you customize both this ID, and a custom CSS class in the block settings.

These fields could be surfaced in the Inspector. See also #672

**Comment by youknowriad** [comment]
FWIW, we already have a `uid` by block. We'll have to persist it though

**Comment by mtias** [comment]
Done in #1889.

**Comment by StaggerLeee** [comment]
Tell me please you will not ship this in the core ?
Why are you forcing something you know in advance at least 90% od WordPress users dont know what it is, and could not care less.

**Comment by jasmussen** [comment]
@StaggerLeee As a meta note, Gutenberg will not reach core without changes. What we are working towards right now is a "vision complete" state. After that comes a long polish phase, and at some point the project will be presented as our suggestion for the next WordPress editor. I expect many changes to happen once we present it as such. I.e. features may be added or removed. And so some of these features we are building to test them out.

I'd also note that the additional CSS class is optional, and it lives in the sidebar inspector. So if you dismiss the sidebar, you'll never see it. See also https://github.com/WordPress/gutenberg/blob/master/docs/design.md#advanced-settings

**Comment by StaggerLeee** [comment]
OK, thank you for explanation.
