### ISSUE TITLE
Featured Image issue

### ISSUE THREAD

**Issue by mamuphoto** [WordPress/gutenberg#8872]
When writing a new article, i can't insert a featured image because there is no box where to drag in or upload the picture.
![1](https://user-images.githubusercontent.com/42292387/43991547-92bd384e-9d6f-11e8-93f5-add6598c2c12.PNG)

 When a featured image is already chosen, i cant' see the preview of that picture.

![2](https://user-images.githubusercontent.com/42292387/43991549-9754a054-9d6f-11e8-8934-ba1fc7d29d5b.PNG)

All the plugins are **up to date**.
Gutenberg  ver 3.5.0

Wordpress version is 4.9.8

When I disable the plug in "Advanced Custom Fields Pro", the issue is solved.
![3](https://user-images.githubusercontent.com/42292387/43991553-a4e0b262-9d6f-11e8-9198-a7bbf530b451.PNG)

I use ACFP plugin because works with "Elementor"

 - OS: Windows10 64 bit
 - Browsers: Chrome ver. 68.0.3440.106 (64 bit) and Firefox ver. 61.0.2 (64 bit)

Can you help me, please?

**Comment by designsimply** [comment]
Closing with a note that another user reported this earlier and also confirmed that upgrading to ACF Pro to 5.6.10 fixed the problem (https://github.com/WordPress/gutenberg/issues/6919#issuecomment-391765216).
