### ISSUE TITLE
Writing Flow: Pressing enter while within inline boundary forces caret position to revert

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8877]
**To Reproduce**

1. Navigate to Posts > Add New
2. Click writing prompt
3. Press Cmd+B (Ctrl+B) to start bolding text
4. Type a few characters
5. Press Enter
6. Type a few characters
7. Observe caret is forced back into first paragraph unexpectedly

**Expected behavior**

Typing at Step 6 should occur within the second paragraph.

**Comment by aduth** [comment]
This appears to be largely an issue caused by lingering TinyMCE DOM state left in the first paragraph which can incur the forced subsequent re-focus (e.g. `#_mce_caret`, the ZWSP inline boundary character).

@spocke Do you have any recommendations for how we can either reset the TInyMCE DOM state when focus leaves the editor? Or prevent it from incurring future forced focus grabs? I think this _might_ be related to https://github.com/tinymce/tinymce/issues/4472 with the ZWSP placement (trimming the ZWSP on blur fixes the issue). I'll plan to continue debugging this Monday.

**Comment by aduth** [comment]
WIP PR: #8879

**Comment by designsimply** [comment]
Possibly related: #8114, #8387

**Comment by iseulde** [comment]
Seems fixed, because the live DOM is now continuously in sync.
