### ISSUE TITLE
Cannot insert block between selected block and previous block

### ISSUE THREAD

**Issue by markjaquith** [WordPress/gutenberg#8878]
**Describe the bug**
When a block is selected, you cannot insert a block between the selected block and the previous block (you **can** insert one **below** the selected block).

Seems like a more general version of #8632.

**To Reproduce**
1. Add 3 Paragraphs.
2. Select the third paragraph.
3. Hover mouse between second and third paragraphs. **No in-between inserter.**
4. Select the second paragraph.
5. Hover mouse between first and second paragraphs. **No in-between inserter.**

**Expected behavior**
You can still in-between insert above the selected block.

**Screenshots**
![screen shot 2018-08-11 at 3 33 37 pm](https://user-images.githubusercontent.com/353790/43995483-4f11d0d4-9d7c-11e8-80da-132eb663feb3.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Firefox
 - Version 61.0.1

**Additional context**
Running Gutenberg @ `b5490a6e2d917cf911f67bee0e7f98350a17a08e` and toolbar is NOT pinned to the top.

**Comment by chrisvanpatten** [comment]
This was an intentional decision in #7168 / #7220 because the sibling inserter could get hidden below the toolbar. Admittedly it's not a perfect solution, but #7297 will add additional insertion options to the block settings menu as well.

**Comment by ZebulanStanphill** [comment]
Also note that the outcome of #6224 could result in a revised sibling inserter UI which could provide another solution to this issue.

**Comment by talldan** [comment]
@markjaquith I've got a PR open #8909 to add Insert Before and After options to the block settings menu. Do you think that will resolve this issue? Let me know and I'll make sure this gets closed when that's merged.

**Comment by talldan** [comment]
#8909 now merged, so closing this.
