### ISSUE TITLE
Inserter: sort blocks by recency

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#888]
Should we replace the "Common" category with a "Recently used" area?

Or should there be a "Recently used" category at the top, _in addition_ to the "Common" category? Perhaps it only shows 4 blocks, or something in that vein?

**Comment by karmatosed** [comment]
To me, recently used makes more sense so +1.

**Comment by BE-Webdesign** [comment]
Recently used in the context of that post?  Doing that across posts would be a significant amount trickier to do from a technical perspective.

**Comment by jasmussen** [comment]
> Recently used in the context of that post? Doing that across posts would be a significant amount trickier to do from a technical perspective.

No, I'd think recently used by the _user_ across posts. So if all you ever do is use text, then that block is the first one, whereas if you use the "Cover Image" all the time, that would climb up the list.

**Comment by BE-Webdesign** [comment]
> No, I'd think recently used by the user across posts. So if all you ever do is use text, then that block is the first one, whereas if you use the "Cover Image" all the time, that would climb up the list.

This would be pretty technically challenging depending on how far it would be taken, but probably a great user experience.

**Comment by folletto** [comment]
I'd suggest to use not linear recency (macOS emojis inserter) but weighted recency (Slack emojis inserter).

Difference:

* **linear recency**: any time an emoji gets used jumps at the top of the recency list.
* **weighted recency**: any time an emoji gets used it gets a +1 counter. The top X emojis by total counter value gets at the top of the list. 

The benefits of the weighted one is that linear recency can get wiped out quickly with a single time that one does something different, while weighted is more stable over time and far far far more likely to have the actual ones that the user uses. 

The weighted recency is a bit more complex, so we can start with linear at first but wrapping it in a function cleanly so we can easily replace it later with weighted.

A way to approach weighted recency that is relatively simple is to store them locally, so while yes, every browser / device will get a different list, it's still beneficial as when it starts it still behaves like linear recency. But it's far far simpler than storing them somewhere in the DB.

**Comment by notnownikki** [comment]
I have the start of this working at https://github.com/WordPress/gutenberg/pull/1506

**Comment by notnownikki** [comment]
#1506 does a "Recently used" category at the top. The majority of the work in it was keeping tab working when blocks are in more than one category, but the code is easy to change to communicate with an API to do weighting etc.

it might need some tweaking with the search bar move.
