### ISSUE TITLE
Using Enter to split a paragraph block requires two Ctrl-Z's to undo

### ISSUE THREAD

**Issue by vr8hub** [WordPress/gutenberg#8882]
**Describe the bug**
Using Enter to split text in a paragraph block takes two Ctrl-Z's to undo.

**To Reproduce**
1. Create a paragraph block with, say, three sentences.
2. Put the cursor before the first character of the third sentence.
3. Hit Enter to split the block.
4. The result should be two paragraph blocks, one with the first two original sentences, the second with the third sentence.
5. Hit Ctrl-Z.
6. You now have the first block with all three sentences, but you still have the second block with third sentence as well.
7. Hit Ctrl-Z again.
8. The second block is now gone.

**Expected behavior**
The first Ctrl-Z in step 5 should put everything back like it was, i.e. all three sentences in the first block *and* the second block gone. Two Ctrl-Z's should not be required.

**Desktop (please complete the following information):**
 - OS: OSX 10.12.6.
 - Browser: Safari 11.1.2.

**Additional context**
- Gutenberg 3.5.0, according to the Plugin page.

**Comment by chrisvanpatten** [comment]
I was able to reproduce this as well, in 3.5 and `master`. Here's a GIF below.

![kapture 2018-08-12 at 16 58 40](https://user-images.githubusercontent.com/1231306/44006338-fa9fdf20-9e50-11e8-8f9f-e61ba7b76023.gif)

I'm surprised it hasn't been reported yet but I couldn't find another issue in a quick search. So thanks for the report @vr8hub :)

**Comment by caxco93** [comment]
I was unable to reproduce this on Chrome for Windows

**Comment by chrisvanpatten** [comment]
Interesting — I'm able to reproduce in Chrome, Safari, and Firefox for macOS. Definitely possible it's OS-specific.
