### ISSUE TITLE
Tooltip labels: inconstency in case style

### ISSUE THREAD

**Issue by eliorivero** [WordPress/gutenberg#8888]
**Describe the bug**
The texts used in different tooltips are different regarding the case they use:
- some use sentence case
    <img width="134" alt="captura de pantalla 2018-08-11 a la s 19 05 07" src="https://user-images.githubusercontent.com/1041600/43997199-06a56bf0-9dac-11e8-96bb-26750afd6fe0.png"><img width="178" alt="captura de pantalla 2018-08-11 a la s 19 05 01" src="https://user-images.githubusercontent.com/1041600/43997203-0f3cae0e-9dac-11e8-9acc-ebfc69674d83.png">
- others use title case
    <img width="161" alt="captura de pantalla 2018-08-11 a la s 21 26 00" src="https://user-images.githubusercontent.com/1041600/43997293-3181cc32-9dad-11e8-91e4-ed05494e1546.png"><img width="142" alt="captura de pantalla 2018-08-11 a la s 21 27 06" src="https://user-images.githubusercontent.com/1041600/43997300-52b049b0-9dad-11e8-903b-ee367349e122.png"><img width="145" alt="captura de pantalla 2018-08-13 a la s 12 22 44" src="https://user-images.githubusercontent.com/1041600/44041847-21ff699c-9ef5-11e8-8a6d-ba28ed336aa7.png">

- and others are composed in lowercase
    <img width="236" alt="captura de pantalla 2018-08-11 a la s 21 18 34" src="https://user-images.githubusercontent.com/1041600/43997211-2098608a-9dac-11e8-8c20-4fdbdc1ca60b.png">

**To Reproduce**
1. roll the mouse over some of the elements shown in the images above.

**Expected behavior**
Consistency in the case style used in all tooltips.

Happy to work on this unifying the case style but would like to know which standard to go with. I know that WordPress core uses the title case, but given that these are tooltips and not titles, maybe it's better to use sentence case. Color names should probably be capitalized using sentence case too.
I checked the Classic Editor to see if a style was consistently used there, but there are discrepancies there too:
<img width="157" alt="captura de pantalla 2018-08-11 a la s 21 23 13" src="https://user-images.githubusercontent.com/1041600/43997273-e00b2df8-9dac-11e8-8cc1-4359f8659180.png"><img width="194" alt="captura de pantalla 2018-08-11 a la s 21 23 23" src="https://user-images.githubusercontent.com/1041600/43997274-e03667d4-9dac-11e8-879b-c90d51802086.png"><img width="154" alt="captura de pantalla 2018-08-11 a la s 21 24 34" src="https://user-images.githubusercontent.com/1041600/43997283-fcee1304-9dac-11e8-95ab-484d1863c5a6.png">

**Comment by chrisvanpatten** [comment]
Thanks @eliorivero! There's some information on our casing preferences [in the docs](https://github.com/WordPress/gutenberg/blob/master/docs/reference/copy-guide.md#five-pay-attention-to-capitalization).

I think most of the cases you shared are valid per the guidelines, but there are two cases you highlighted that seem like they could improve, so I want to get @karmatosed and @michelleweber's help on these:

+ `More Options` vs `More options` — I like the sentence case version but there's definitely a case (ha!) for the Title Case version
+ Should we auto-capitalise color names when they're displayed in tooltips?

Thanks again for the ticket!

**Comment by michelleweber** [comment]
I'd go sentence case; it's what tooltips in the current editor do, and title case is really best saved for actual titles. I'd sentence case the color names as well.

**Comment by eliorivero** [comment]
Thanks @chrisvanpatten and @michelleweber for the response! Will update as Michelle says, using sentence case for all tooltips 👍

**Comment by chrisvanpatten** [comment]
@eliorivero Thanks! The only thing I think is that the Classic Editor block button tooltips _might_ need to stay for backcompat with the old editor, and because "Document Structure" is a feature (as opposed to an action like the other tooltips) I think it would stay as Title Case. Of course I'm happy to be corrected on either point!

**Comment by eliorivero** [comment]
Thanks, I'm not touching the classic editor. However, I'm typing "Document Structure" as "Document structure" since unlike the "Close Publish Panel", which I typed now as "Close Publish panel", the "structure" here is not a panel or a specific feature name on its own.
