### ISSUE TITLE
Removing categories with block_categories filter causes issues

### ISSUE THREAD

**Issue by LABCAT** [WordPress/gutenberg#8889]
**Describe the bug**
Removing categories using block_categories filter results in a ton of console errors

**To Reproduce**
1. Create a custom post type
2. Add a function such as the following:
`public static function remove_categories( $categories, $post ) {
        if ( $post->post_type === self::$post_type ) {
            return [
                [
                    'slug' => 'common',
                    'title' => __( 'Common Blocks', 'gutenberg' ),
                ],
                [
                    'slug' => 'layout',
                    'title' => __( 'Layout Elements', 'gutenberg' ),
                ]
            ];
        }
        return $categories;
    }`
3. Load gutenberg and look at the console.

**Expected behavior**
None of these blocks are in the allowed types for the custom post type so they shouldn't even be loaded.

**Screenshots**
![image](https://user-images.githubusercontent.com/9105153/43997302-3135511c-9e2b-11e8-9fb6-1689cdf4be80.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 
**Additional context**
- Gutenberg version 3.4

**Comment by youknowriad** [comment]
This filter is meant to add categories and not remove them. If you want to remove blocks from the inserter, you should try to remove the blocks and not the category of the blocks https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#removing-blocks

**Comment by youknowriad** [comment]
The allowed block types hide blocks and don't remove them as stated in the docs https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#hiding-blocks-from-the-inserter

**Comment by LABCAT** [comment]
I don't think this is a help request, I think this is a bug.

I already knew about hiding blocks then I found that filter which allowed to add/hide categories.  

If the filter is not meant for removing categories then it needs to be rewritten to prevent it from happening.  Someone else in the future will do the same thing I did.

The ideal functionality would be that you could remove categories and even reassign the category of other blocks in some situations. For example, I create a custom post type with a custom category that uses 2 custom blocks and 2 core blocks (eg paragraph and columns).  

As this custom post type only has four blocks it doens't really need a ton of categories. For usability purposes it would be great to group these blocks altogether under the same category.

**Comment by youknowriad** [comment]
If you reassign a block's category using the `registerBlockType` filter and at the same time you remove the category, it should work. It just doesn't make sense to remove a category if there are already blocks using this category.

**Comment by youknowriad** [comment]
I hope this answers your questions, I'm going to close for now. Let me know if reassigning and removing work for you. We can still reopen if needed.
