### ISSUE TITLE
Edit screen does not render on Safari

### ISSUE THREAD

**Issue by mitogh** [WordPress/gutenberg#8891]
**Describe the bug**

On the latest release from Gutenberg 3.5 the edit screen does not load any block and contains issues on the console.

**To Reproduce**
1. Go to Admin screen
2. Click on Posts > Add New
3. Observe white screen

**Expected behavior**
Blocks should load correctly

**Screenshots**

![screen shot 2018-08-11 at 8 06 47 pm](https://user-images.githubusercontent.com/3921289/43997491-216e5a32-9da2-11e8-8460-edb9d8e0cdee.png)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Safari
 - Version 11.1.2 (13605.3.8)

**Additional context**
- Please add the version of Gutenberg you are using in the description.

Errors from the console

<details>
[Error] TypeError: Value is not a sequence
	initMessageEvent (post-new.php:12:308)
	Cb (Script Element 1:12:308)
	f (Script Element 1:12:138)
	b (Script Element 1:11:1415)
	(anonymous function) (Script Element 1:72:91)
	(anonymous function) (Script Element 1:74:229)
	Global Code (Script Element 1:74:239)
	appendChild
	(anonymous function) (injected_base.js:84:254)
	(anonymous function)
	bound 
	Gc (injected_base.js:63:318)
	Aa (injected_base.js:55:95)
	forEach
	za (injected_base.js:54:341)
	(anonymous function)
	pc (injected_base.js:23)
	promiseReactionJob
[Error] TypeError: Value is not a sequence
	initMessageEvent (post-new.php:12:308)
	Cb (Script Element 1:12:308)
	f (Script Element 1:12:138)
	f (Script Element 1:66:993)
	b (Script Element 1:11:1415)
	b (Script Element 1:66:936)
	g (Script Element 1:68:157)
	(anonymous function) (jquery-migrate.js:23)
	Global Code (jquery-migrate.js:752)
[Error] TypeError: Value is not a sequence
	initMessageEvent (post-new.php:12:308)
	Cb (Script Element 1:12:308)
	f (Script Element 1:12:138)
	f (Script Element 1:66:993)
	b (Script Element 1:11:1415)
	b (Script Element 1:66:936)
	g (Script Element 1:68:157)
	u (index.js:1:5744)
	jn (index.js:12:76304)
	(anonymous function) (post-new.php:1772)
</details>

Issue is only present on Safari

**Comment by chrisvanpatten** [comment]
Hi @mitogh — I'm using Gutenberg successfully with desktop Safari without any issues in 3.5.

The console error you referenced looks like it's coming from an inline script tag; could you track that down and share the code from that script tag?

**Comment by Ipstenu** [comment]
For reference, I get that error when I’m developing blocks and mess up the Js badly. You may need to disable plugins that add blocks.

**Comment by mitogh** [comment]
I disabled all plugins for now and just leave gutenberg plugin active.

Another thing to consider, not sure if helpful is that I'm testing the ZIP version from WordPress.org site on the latest version 3.5 not the `lastest` from Github.

**Comment by tofumatt** [comment]
@mitogh, to be clear: does the page work once you disabled other plugins or are you still encountering a blank screen? Could you try with the latest release of Gutenberg from WordPress.org?

**Comment by designsimply** [comment]
I found an answer about that error on StackOverflow which asks to temporarily disable the WebDriver extension: https://stackoverflow.com/a/46939504 

If you have that Safari extension installed, can you try disabling it and checking to see if the problem goes away?

**Comment by mitogh** [comment]
Thanks for the follow up here.

@tofumatt yes I disabled all plugins except for Gutenberg.

![screen shot 2018-09-17 at 8 48 35 pm](https://user-images.githubusercontent.com/3921289/45659675-34114d80-babb-11e8-91bf-0c5ee2a83a48.png)

And when I click on `Posts > Add New`

This is the result

![screen shot 2018-09-17 at 8 48 43 pm](https://user-images.githubusercontent.com/3921289/45659685-43909680-babb-11e8-8d6e-1734db1e870b.png)

Let me know if you have additional questions.

**Comment by tofumatt** [comment]
Are you using any Safari extensions? As @designsimply mentioned, this could be similar to an issue encountered with a WebDriver Safari extension installed.

Is your theme something custom or are you using Twenty Seventeen? It could be that your theme is adding code that is messing things up, though I sort of doubt that 😢

Could you copy the full text of the error in your browser console?

**Comment by mitogh** [comment]
Thanks @tofumatt I created a new website and the only plugin installed is Gutenberg, seems like might be a problem with my other plugins or WP installation but seems like that one fixed the problem.

Is working fine on the new installation and same browser as the other, no extension is installed and I'm using default theme from default WP installation on both. 

Let me know if you need additional information but I think we might be able to close this one.

Thanks.

**Comment by tofumatt** [comment]
Thanks for letting us know!

**Comment by designsimply** [comment]
I'm making a note of the inactive plugins from your screenshot just in case it's relevant later:

* Akismet 4.0.8
* Event Tickets 4.8.1
* Event Tickets Plus 4.8.1
* Hello Dolly 1.7
* Query Monitor 3.1.0
* The Events Calendar 4.6.23
* The Events Calendar: Gutenberg Extension 0.2.8-alpha

I'd also like to note that asking for a step to clear browser cache after deactivating plugins would be a good troubleshooting step if this comes up again for others.

Thank you again for the follow-up!
