### ISSUE TITLE
Error in displaying after re-login

### ISSUE THREAD

**Issue by tmatsuur** [WordPress/gutenberg#8892]
Session timeout while editing post.
After that, display the login form as a popup and login,
An error occurred when editing a new block.

The procedure is as follows.

1.Install WordPress 4.9.8. Then install and activate Gutenberg.

 2.Added the following source code to functions.php of Twenty Seventeen.
` function shorten_auth_cookie_expiration( $sec, $user_id, $remember ) {
         return 60;
 }
 add_filter( 'auth_cookie_expiration', 'shorten_auth_cookie_expiration',
 10, 3 );
`

 3.Log in to the admin page.

 4.Click Posts > All Posts in the navigation.

 5.Click 'Hello World!'.

 6.Wait for the login form to pop up.

 7.Enter your username and password to login.

 8.Click the "Add block" area(Move the mouse pointer and the (+)mark is
 displayed).

 9.An error is displayed on the console.
 `GET http://local2/wp-json/wp/v2/types/wp_block?context=edit 403
 (Forbidden)
 index.js?ver=1533789473:1 Uncaught (in promise) {code:
 "rest_cookie_invalid_nonce", message: "Cookie nonce is invalid", data:
 {…}}
 `

 OS: Windows 10
 Browser: Chrome 68.0.3440.84, 68.0.3440.106
 WordPress: 4.9.8
 Gutenberg: 3.4.0, 3.5.0

**Comment by designsimply** [comment]
@tmatsuur, to clarify, is the code you provided in step two required or does it just make it easier to see the problem happen by shortening the login timeout?

**Comment by tmatsuur** [comment]
@designsimply sorry. It seems that the code did not break nicely and it became difficult to see.
As you pointed out, the code just shortens the login timeout.

**Comment by designsimply** [comment]
Adding a screenshot and noting some console errors:

> Error: Permission denied to access property "nodeType"
> tinymce.min.js:2:285363
> Error: Permission denied to access property "nodeType"
> wp-tinymce.php:2:285363

<img width="1280" alt="screen shot 2018-08-23 at thu aug 23 10 34 24 am" src="https://user-images.githubusercontent.com/1119271/44539366-3d2c1c00-a6c1-11e8-9fa2-d9eb9271f0ad.png">
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=13999&action=edit running WordPress 4.9.8 and Gutenberg 3.6.2 using Firefox 61.0.2 on macOS 10.13.6.</sup>

<br><br>
Notes: This post had been left open for over a day, when I viewed the open tab again I saw a login form, after logging in I saw an "Updating failed" error and there are a few errors in the console that appear to be related to other plugins: "editor.getParam(...).join is not a function" and "newest-note-data" and I think the 'Permission denied to access property "nodeType"' errors may be relevant to this issue but I will run another test with the other plugins deactivated to make sure. I did not see the 403 error for the `wp_block` API call that you noted so I think that might be related to the forced timeout.

**Comment by youknowriad** [comment]
I think this was fixed by a recent update to how nonces work cc @ellatrix
