### ISSUE TITLE
Custom Post Type Category...

### ISSUE THREAD

**Issue by MarkOude** [WordPress/gutenberg#8896]
So when you make a new taxonomy for posts with the plugin CPT UI then the taxonomy is not represented in the editor. So you must go to the old editor to add the Taxonomy to an post.

I expect, that i can add an taxonomy from the CPT UI to an post in the gutenberg editor.

Sorry for my english...

**Comment by chrisvanpatten** [comment]
@MarkOude Thanks for the report!

Is [this the plugin you're using](https://wordpress.org/plugins/custom-post-type-ui/)?

Can you make sure that the "Show in REST" setting is enabled for your taxonomy?

![add_edit_taxonomies_ _chris_van_patten_ _wordpress](https://user-images.githubusercontent.com/1231306/44006302-49529244-9e50-11e8-8128-d9197dcd19bf.png)

That is necessary so Gutenberg can pull in the category data through the REST API.

**Comment by MarkOude** [comment]
Ah yeah, I forgot that, thank you very much!

**Comment by chrisvanpatten** [comment]
Glad to hear it helped @markoude! I’ll close this up but if you need further help don’t hesitate to comment again.
