### ISSUE TITLE
Hyphen automatically gets added on 'title' tag of image

### ISSUE THREAD

**Issue by anupviews** [WordPress/gutenberg#8902]
When I upload an image that has no hyphen (eg. round clock.jpg), it automatically adds hyphen in the title tag and appears as: round-clock. This had happened with previous version of WordPress and was fixed, but Gutenberg has this bug.

Please fix this.

**Comment by chrisvanpatten** [comment]
@anupviews do you happen to know if there was a Core Trac ticket about this issue? I was under the impression that WordPress always normalised image filenames, but perhaps I'm wrong :)

**Comment by chrisvanpatten** [comment]
Oh, do you mean in generating the "title" attribute of the image?

A screenshot would be helpful here as well, if you have one!

**Comment by WPprodigy** [comment]
I uploaded an image (`image name.png`) to a Gutenberg image block. Here is the frontend output (no title attribute):

```
<figure class="wp-block-image">
<img src="https://wpdev.test/wp-content/uploads/2018/08/image-name.png" 
  alt="" class="wp-image-73" 
  srcset="https://wpdev.test/wp-content/uploads/2018/08/image-name.png 1200w, https://wpdev.test/wp-content/uploads/2018/08/image-name-300x205.png 300w, https://wpdev.test/wp-content/uploads/2018/08/image-name-768x525.png 768w, https://wpdev.test/wp-content/uploads/2018/08/image-name-1024x700.png 1024w" 
  sizes="(max-width: 706px) 89vw, (max-width: 767px) 82vw, 740px">
</figure>
```

When clicking on the pencil icon in the block for the image though, I do see the hyphenated title: 
![edit-image](https://user-images.githubusercontent.com/8536129/44016937-66c43250-9e9c-11e8-8f02-22df95ac70d2.png)

So a GB uploaded image is auto-hyphenating the image title, but it does not use the title attribute, which looks like it will be addressed here: https://github.com/WordPress/gutenberg/issues/7504


______

I then uploaded a new image through just the media library in WP. This time, the image title was not auto-hyphenated

![edit-image2](https://user-images.githubusercontent.com/8536129/44017120-da9d8ac8-9e9c-11e8-9467-9dd8745994e4.png)

_____

I believe the relevant trac ticket can be found here: https://core.trac.wordpress.org/ticket/37989

**Comment by WPprodigy** [comment]
Ah yea, so the title is getting assigned while the image is being uploaded via the rest api here: https://github.com/WordPress/WordPress/blob/aab929b8d619bde14495a97cdc1eb7bdf1f1d487/wp-includes/rest-api/endpoints/class-wp-rest-attachments-controller.php#L143

Possible Solutions:

1) See if the REST API should be handling this differently, and patch there.
2) Pass along the image title in Gutenberg when first uploading the image. Which I believe would be here: https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/utils/media-upload/media-upload.js

**Comment by anupviews** [comment]
@chrisvanpatten I uploaded image named 'Garcinia cambogia for weight loss (with out hyphen), and the editor adds title tag as follows:

![screen shot 2018-08-13 at 9 21 18 pm 1](https://user-images.githubusercontent.com/570233/44042670-9406a23a-9f40-11e8-9169-7ebf193713e5.png)

I reported this issue with previously, but I don't remember which version had it.

And as @WPprodigy point out, it does not have title tag in frontend output even though I added something using the 'title' filed of the image:

![screen shot 2018-08-13 at 9 36 50 pm](https://user-images.githubusercontent.com/570233/44042900-3b3db20a-9f41-11e8-82f9-5c25e9d63bfd.png)

**Comment by WPprodigy** [comment]
Opened up a wp core issue as well, linking for reference: https://core.trac.wordpress.org/ticket/44789

**Comment by nicopujol** [comment]
Having this issue of hyphens in image file name and titles. Was there a fix or did it get reverted?
![hyphens in file name](https://user-images.githubusercontent.com/1319146/56084878-c8902400-5dee-11e9-8fec-b3c6180d8b8e.jpg)

**Comment by WPprodigy** [comment]
I vaguely remember the issue, but fairly sure your SS is expected behavior. The image name had hyphens on it when uploaded, so they will also be there in the title by default.

**Comment by nicopujol** [comment]
The Gutenberg editor is adding the hypens to the file name. When uploading images from a recipe plugin, for example, the issue does not occur.
