### ISSUE TITLE
No white space between image block and text block

### ISSUE THREAD

**Issue by anupviews** [WordPress/gutenberg#8903]
As the title says, there is not any white space line between image and text block. In post editor it seems like there is space but when you preview it, it does not have any space. Please fix this.

**Comment by chrisvanpatten** [comment]
@anupviews Can you provide screenshots? Information on your browser version, OS, etc. might be helpful too.

**Comment by anupviews** [comment]
@chrisvanpatten Sure! The first one is the image block and the second one is the text block in the editor:
![screen shot 2018-08-13 at 9 21 42 pm](https://user-images.githubusercontent.com/570233/44042160-4d5cff9c-9f3f-11e8-8ce9-b9e90f595da8.png)

But when I post it, it looks like this (post page):

![screen shot 2018-08-13 at 9 22 02 pm](https://user-images.githubusercontent.com/570233/44042183-5daf13b2-9f3f-11e8-95f9-eae09a34e076.png)

Classic editor does not have this issue.

I'm using MacOS Sierra 10.12.6, Google Chrome Version 68.0.3440.106.

**Comment by AdrienGit77** [comment]
Same issue here.

How to get the same look?

**Comment by AdrienGit77** [comment]
My new setting to resolve this:

`.wp-block-image figcaption {font-style:italic; font-size:0.9em; margin-top:-20px; `margin-bottom:15px;}``

**Comment by skorasaurus** [comment]
This appears to be solved for me; with https://github.com/WordPress/gutenberg/pull/9566

Now, Gutenberg 4.5.1 has a default of `.wp-block-image figcaption {margin-top: .5em; margin-bottom:1 em;}`

**Comment by tara2** [comment]
I still have a problem ...we like some space under videos - and also under each video heading - when we have several of them embedded on a page.   The only way I've fudged this so far is putting several letters in a text block and making their colour to be white.

How does one make spaces appear in Gutenberg??

**Comment by CoderGeek700** [comment]
Hi there, 
In desktop website, I faced an issue when I added a video after the title header and I would like to reduce that space and that also happened with mobile devises layout!! please fix that issue

**Comment by youknowriad** [comment]
This seems fixed by default, if you're still seeing similar issues, consider checking the stylesheets of your theme.
