### ISSUE TITLE
How do I remove a text link?

### ISSUE THREAD

**Issue by frodojrr** [WordPress/gutenberg#8904]
Hi:

I see no option in place to remove a text link once it's been set.

So, [if this is my link](https://www.enewspf.com), once it's been put in place, there is no "broken-link icon" to remove it.

This is especially difficult if I put a link at the end of a sentence _before_ I put a period in the sentence. If I add a period, or more text after the link, the link continues to grow and expand as I type. The period at the end of the sentence becomes a link. The next sentence becomes a link. 

Thanks!

Gary Kopycinski

**Comment by caxco93** [comment]
Please follow the steps on this animated gif
![removelink](https://user-images.githubusercontent.com/3190666/44006285-9b8cbba6-9e47-11e8-8b9b-f3eae57ae85f.gif)

**Comment by chrisvanpatten** [comment]
Thanks for the GIF @caxco93! That works for me too. I'll close this issue up but don't hesitate to comment again if you need help @frodojrr! 🚀

**Comment by frodojrr** [comment]
Thank you!

**Comment by arunsathiya** [comment]
It wasn't very clear to me either. 

- I tried removing the link in the popup and hit `Enter`, hoping it would remove the link.
- I also tried to use the `Link settings` dropdown, hoping to see an option to remove the existing link.

The GIF helped eventually! ⚡️
