### ISSUE TITLE
Will Gutenberg / wordpress 5.0 change themes structure and how they are developed?

### ISSUE THREAD

**Issue by swessey** [WordPress/gutenberg#8907]
Will it just change how you make posts and pages, or will it also change the way themes are made code based?

**Comment by youknowriad** [comment]
Gutenberg (5.0) won't change the way themes are built/structured. There are theme "tweaks" you can add to your themes to support some Gutenberg built-in features (see https://wordpress.org/gutenberg/handbook/extensibility/theme-support/) but in general, Gutenberg won't change anything. 

The second phase of the project which will start after 5.0 might have more impacts on themes, but it remains to be seen what it really means as it didn't start yet.
