### ISSUE TITLE
npm install @wordpress/block-library --save not found

### ISSUE THREAD

**Issue by jaschaio** [WordPress/gutenberg#8917]
Trying to install the `@wordpress/block-library` package as [explained in the docs](https://wordpress.org/gutenberg/handbook/packages/packages-block-library/).

Getting a `404 Not Found: @wordpress/block-library@latest` error.

Is it possible that this was done very recently and the package is not yet published to npm?

Thanks

**Comment by chrisvanpatten** [comment]
@jaschaio This was actually just published about 3 minutes ago as of now, so it's likely you _just_ missed it!

https://www.npmjs.com/package/@wordpress/block-library

Can you try again? May need to clear your npm caches too. If it works then, I'll close this out :)

**Comment by jaschaio** [comment]
Well that was great timing ;) tried again and its working
