### ISSUE TITLE
Click To Tweet

### ISSUE THREAD

**Issue by hannahhay** [WordPress/gutenberg#8925]
Maybe I'm just missing it, but where did Click To Tweet go? In the old editor, it was in my toolbar and I could easily click it to add a tweet within the post and now I don't see it. 

I found a plugin for Gutenberg for it, but it doesn't appear to be working, so any advice on how to use it in the new editor is appreciated!

Thanks!

**Comment by chrisvanpatten** [comment]
Hi @hannahhay —

Click to Tweet is a feature added by a plugin, so it would be up to the plugin author to update for Gutenberg.

Which plugin did you find that offers Click to Tweet with Gutenberg so I can test it out? And do you know which plugin you were previously using with the old editor?

**Comment by hannahhay** [comment]
Hey! Thanks for responding so quickly!

Before, I was using the ClickToTweet plugin by TodayMade in the classic editor, but I haven’t seen it in Gutenberg, so I guess it’s not ready for it. The one I found that said it was for Gutenberg, is Gutenberg Click To Tweet Block by Rich Tabor from CoBlocks, but I haven’t had success finding it. I am also still learning Gutenberg, so it’s possible I just don’t know how to use it yet.

Thanks!

**Comment by chrisvanpatten** [comment]
@hannahhay No problem, happy to help!

So in Gutenberg, the "click to tweet" option that CoBlocks provides is actually inserted as a separate block. Screenshots below:

![_untitled____add_new_post_ _chris_van_patten_ _wordpress](https://user-images.githubusercontent.com/1231306/44040787-19570904-9eea-11e8-92ea-4a3e7a92e6be.png)

![_untitled____add_new_post_ _chris_van_patten_ _wordpress](https://user-images.githubusercontent.com/1231306/44040813-2849afac-9eea-11e8-9d10-ebb173facbd0.png)

This does mean you can't currently have a sentence inside a paragraph be "tweetable", but hopefully this still helps you move in the right direction!

I'll close this issue but if you still need help don't hesitate to reply and we can always reopen it :)

**Comment by hannahhay** [comment]
Thanks! I’ll test it again and see if it works for me! :)
