### ISSUE TITLE
Role of React going forward

### ISSUE THREAD

**Issue by PeterKnight** [WordPress/gutenberg#893]
I want to know if part of the vision of the Gutenberg project is a WordPress editor where if you want to build custom functionality for it you have to work with React?

**Comment by aduth** [comment]
What do you have in mind when you say custom functionality? As it stands, yes, blocks registered to the Gutenberg editor must use React to describe its editor form and content to be saved; or more accurately using [a React abstraction](https://github.com/WordPress/gutenberg/tree/master/element), though this abstraction may not live for much longer (#876). This is, of course, subject to change as the project evolves.

The role of React or another framework in WordPress generally has been the topic of [weekly JavaScript Chats in Slack](https://make.wordpress.org/meetings/), which you'd be encouraged to attend if you're interested in weighing in on the discussion. See also recent summaries:

- [2017-05-23](https://make.wordpress.org/core/2017/05/24/javascript-chat-summary-for-may-23rd/)
- [2017-05-16](https://make.wordpress.org/core/2017/05/17/javascript-chat-summary-for-may-16th/)
- [2017-05-09](https://make.wordpress.org/core/2017/05/10/javascript-chat-summary-for-may-9th/)

**Comment by PeterKnight** [comment]
Thank you for the very informative reply @Aduth, I've add some thoughts underneath the latest chat :) 

https://make.wordpress.org/core/2017/05/24/javascript-chat-summary-for-may-23rd/

**Comment by youknowriad** [comment]
Should we close this issue since the discussion is happening broadly in the make/core post and the weekly meetings?

**Comment by jasmussen** [comment]
Yep, let's close this in favor of the core posts, and the weekly meetings. It also addressed the question.
