### ISSUE TITLE
Question: Front Page of Theme only editable using Appearance->Customize

### ISSUE THREAD

**Issue by susanb1** [WordPress/gutenberg#8932]
Gutenberg V3.5.0 installed today - August 8, 2018
Accelerate Theme by ThemeGrill

## Issue Overview

This theme's Front Page is only editable by using the Customize option. I have no visibility to the Page in my Pages list for editing. On top of that, there is a Page in my Pages list that is labeled "Front Page" that does not contain anything that actually shows up on my landing page (https://islesunsets.com). The "Home Page" in the Customizer does specify this "Welcome!" page as my static home page even though the contents of that "Welcome!" page is definitely what shows up on my site.

Because there is no correlation between the Pages and the Customizer in this particular theme, I find it confusing anyway. 

While using Gutenberg as a plug-in in test mode, it seems that I'm still able to use the Customizer to edit the Front Page.

My concern is what will happen when WordPress upgrades to Gutenberg editor for all? Will we still have access to the Customizer to edit Pages that are only editable through the Customizer?

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by ajitbohra** [comment]
Yes, If your theme handles page customization via customizer it will continue to work with Gutenberg.
