### ISSUE TITLE
Copying and pasting a post as HTML

### ISSUE THREAD

**Issue by frodojrr** [WordPress/gutenberg#8934]
I have not found a way to paste a post as HTML. Can it be done?

I transcribe some interviews into Dreamweaver, add links in those interviews. Need to publish the stories with the links.

With the classic editor, I can select "Text" and paste all of the HTML, preserving links, etc.

Is there a way to do that with Gutenberg already, or is this a feature request?

**Comment by kmarshy** [comment]
you can actually. When navigate to the page you want to add the code, there is settings cog on the top left corner, just besides there are dotted buttons, click and select code editor -> go back to your text editor and paste your html. You can switch back to visual editor with same process.
![guternburg-editor](https://user-images.githubusercontent.com/10392696/44084149-a3ca85be-9fbe-11e8-82d2-c60c060fcbe0.jpeg)
