### ISSUE TITLE
Font options please.

### ISSUE THREAD

**Issue by pgiblett** [WordPress/gutenberg#8938]
One of the limitations of Gutenberg plugin it that is does not provide options for adding fonts. It has a limited capability to set font size. To be fair the prior editor doesn't have fonts either, but I have installed a plugin to provide me with fonts. 

Gutenberg is supposed to be more of a WYSWYG editor. You have made great strides, but without fonts you are only halfway there. I may change fonts within a post when demonstrating items. I have found this to be very useful with posts I create.

**Comment by designsimply** [comment]
Thank you for your feedback @pgiblett and for testing out Gutenberg! I searched and found that #6931 was a similar request and the reply there was that adding fonts on a very granular level inside the editor is not something getting focus at this time but that it may be considered in the future and would be great as an optional plugin. 

I also found a request at #8788 which makes a request for the ability to customize fonts for headings/body/etc from one location such as the Customizer. 

I am closing this issue in light of the two previous similar requests.
