### ISSUE TITLE
Release v3.5.0 not tagged here

### ISSUE THREAD

**Issue by goldenapples** [WordPress/gutenberg#8939]
Version 3.5.0 is released in the .org repo, but not available as a tag here. I believe that b66cc665f30aa670a249f2386b27b5aeed659ba0 is the commit that should be tagged as `v3.5.0`

**Comment by designsimply** [comment]
Releases are sorted using milestones such as https://github.com/WordPress/gutenberg/milestone/60?closed=1

I am closing this but if I've misunderstood, please let me know and I will re-open!

**Comment by chrisvanpatten** [comment]
@designsimply I think @goldenapples means the Git tag, not the "labels" in GitHub. It's a bit hard to see because of all the packages releases but the last tagged release was 3.4.0: https://github.com/WordPress/gutenberg/tags?after=%40wordpress%2Fbabel-plugin-import-jsx-pragma%401.0.2

**Comment by chrisvanpatten** [comment]
(There isn't an exact label for "Repo Management" — also noticed that when trying to label #8986 — but Build Tooling feels like it comes closest for this one!)

**Comment by chrisvanpatten** [comment]
Just confirmed that release tagging is [in the release documentation](https://github.com/WordPress/gutenberg/blob/master/docs/reference/release.md#build-the-release), so this might have been a case of a mistakenly skipped push. Should definitely be resolved though; it makes it easier to `checkout` a specific release locally.

**Comment by pento** [comment]
Thanks for the reminder, I've added the release.

https://github.com/WordPress/gutenberg/releases/tag/v3.5.0

**Comment by chrisvanpatten** [comment]
Thanks @pento! 🚢
