### ISSUE TITLE
Rich Text: Patterns transform should undo on subsequent Backspace or Esc

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8942]
Given the following set of steps, I would expect that the "Backspace" key press should result in the list being reverted back into a paragraph.

1. Navigate to Posts > Add New
2. Click the writing prompt to add a paragraph
3. Type "- " (dash, space) or "# " (number sign, space)
4. Observe that a list transform is applied
5. Press Backspace
6. Observe that nothing happens

When a pattern transform is applied, we should consider it a tentative transformation until the user takes further action. If that further action is an immediate Backspace keypress, the transformation should be reverted.

Many WYSIWYG behave this way, for example Google Docs. 

Open questions:

- At what point do we no longer consider the transform tentative?
- What is responsible for maintaining the state of this tentative transaction?
   - Is it internal state of RichText ? Since a transform is a replacement, the RichText may no longer exist after the transformation is applied.
   - Is it the top-level editor state ? It could be integrated into the `replaceBlocks` action creator as an option, perhaps leveraging `redux-optimist` for the start / commit states.

cc @iseulde

**Comment by ellatrix** [comment]
Thinking about this now. We need the same thing to happen for both `escape` and `backspace`. As you mentioned, the replacement is done outside of `RichText`, so I think it should be handled somewhere else. I'm also not sure if it should be tied to `replaceBlocks`, as there may be other actions where we want the same behaviour. E.g.: backticks => code tag transform. In this case, the `RichText` `onChange` prop is used, which means the block attributes are updated.

Perhaps we can play with passing an option to `__unstableMarkLastChangeAsPersistent` where the next change can be undone with those shortcuts.

**Comment by ellatrix** [comment]
#14776 should fix this issue.
