### ISSUE TITLE
“Publish” button doesn’t change to “Schedule” while scheduling a same-day post until focus leaves the hour or minute field

### ISSUE THREAD

**Issue by angelasjin** [WordPress/gutenberg#8944]
**Describe the bug**
When scheduling a post to be published, I can only schedule if it is for the next day. If I select a later time in the same day, the only option is to publish immediately. 

**To Reproduce**
1. Go to 'Posts' and 'Add New'
2. Type out your post :)
2. Click on 'Publish'
3. Try to schedule for later the same day (just a few hours)
4. Only option is to 'Publish', whereas if I select any day after, the option is 'Schedule'

**Expected behavior**
If I select a time after the current time, I want it to say 'Schedule' not 'Publish'. Scheduling does still work, but it was confusing that the button doesn't update to "Schedule" right away.n

**Screenshot**
<img width="1095" alt="screen shot 2018-08-13 at 1 18 15 pm" src="https://user-images.githubusercontent.com/39204905/44055821-5c59f32c-9efb-11e8-88c6-ea60ce395371.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra v10.13.6 
 - Browser: Chrome
 - Version 68.0.3440.106

**Additional context**
Gutenberg version: 3.5.0

**Comment by WPprodigy** [comment]
I can replicate.

`onBlur` is fired when you move away from an object (not necessary making a change). `onChange` is fired when you have both changed the value of the field and it loses focus.

https://github.com/WordPress/gutenberg/blob/6928e41c8afd7daa3a709afdda7eee48218473b7/packages/components/src/date-time/time.js#L115-L121

So with that in mind, both `onChangeHours` and `onChangeMinutes` need to also update the whole date, and not just the hour/minute state. Perhaps most of the logic could be moved into the `onChange` actions and `onBlur` can simply handle the invalid data entries?

**Comment by jessejamesrich** [comment]
Is this effectively broken?

**Comment by earnjam** [comment]
I think this may have been resolved with the updated datepicker component. I can't replicate now. 

@angelasjin or @WPprodigy can either of you confirm this is still occurring? My screenshot below of just 2 minutes ahead of current time shows the schedule button. 

![image](https://user-images.githubusercontent.com/4267290/48682591-f2625900-eb76-11e8-82cb-08c55a8aac70.png)

**Comment by WPprodigy** [comment]
If I'm remembering the bug correctly, it seems fixed for me as well in the latest release.

**Comment by angelasjin** [comment]
Seems fixed for me as well! I think we can go ahead and close. Thank you!
