### ISSUE TITLE
Problems selecting resized image blocks which are aligned without selecting adjacent text

### ISSUE THREAD

**Issue by abrightclearweb** [WordPress/gutenberg#8945]
**Describe the bug**
When selecting resized image blocks which sit inline with paragraph blocks, it can be very difficult to select an image block alone. Instead I end up highlighting 2 blocks and can manipulate neither.

Also, I have ended up with some ugly overlapping.

**To Reproduce**
1. Add some paragraph blocks.
2. Add image blocks between them.
3. Resize the image blocks.
4. Align a resized block left or right.
5. Try to select only an image block, not a paragraph block as well. 

**Expected behavior**
I should be able to click on an image block to select it alone. Instead I often select two blocks.

**Screenshots**

![selecting images within text](https://user-images.githubusercontent.com/7430856/44057331-b6d20cb2-9f42-11e8-90dd-80263e39cd4a.gif)

**Desktop (please complete the following information):**
 -  OS: Windows 10 64-bit
 -  Browser: Firefox Quantum
  -  Version 61.0.1 (64-bit)

**Additional context**
- Gutenberg 3.5.0

**Comment by designsimply** [comment]
Thank you for posting! I think that the problem you've raised here is part of the discussion in #7500 and I am closing this issue in favor of consolidating there. If you feel it should remain separate, please reply here and we can re-open if needed!
