### ISSUE TITLE
How do you change heading font in posts? 

### ISSUE THREAD

**Issue by untamedsloth** [WordPress/gutenberg#8946]
I can't change the font of H2, H3 headings in my posts.

**Comment by nicolasmondada** [comment]
When you select the block you can see the different heading options on the top.
<img width="718" alt="screen shot 2018-08-14 at 08 14 30" src="https://user-images.githubusercontent.com/1138304/44077018-2d23be40-9f9a-11e8-8eb4-6ce83ab3613b.png">

**Comment by ldinoto** [comment]
None of these heading options does anything but resize. Can you not change the actual font (ital, underline, etc) of a heading?

**Comment by untamedsloth** [comment]
That seems rather inconvenient for an “updated” editor. Especially considering the classic editor allows you to easily customize all of the formatting without any css or html

**Comment by jaclyntan** [comment]
I agree; I understand the philosophy behind separating headings into their own blocks but it's really not intuitive or easy to actually use. The extra clicking to make new blocks and select headings makes writing even more tedious than intended. It'd be great if the headings could be grouped with the other options by default- whether that means separating the headings into separate blocks once the user selects out of it or if it forms part of the paragraph is up for debate.

**Comment by tellthemachines** [comment]
Closing this issue as it is now possible to change the font style and size for the heading block:

<img width="396" alt="Screen Shot 2020-04-21 at 4 22 09 pm" src="https://user-images.githubusercontent.com/8096000/79832229-546a6200-83ec-11ea-8cbd-6a43c975002b.png">

Font style (bold, italic) can be changed in the block toolbar, and font size can be adjusted in the block settings menu.
