### ISSUE TITLE
Images aren't mobile responsive?

### ISSUE THREAD

**Issue by untamedsloth** [WordPress/gutenberg#8947]
Images that I uploaded with the classic editor would resize to fit within the post margins when viewed on a mobile device. This no longer happens.

**Comment by ldinoto** [comment]
Yes. This is making me crazy.

**Comment by skorasaurus** [comment]
Is this still an issue? 

I was unable to reproduce this; the image that I used : 

- Added 4800 × 5992 photo while in a draft post on theme TwentyNineteen through the visual editor (the classic editor)
- published post 
- disable classic-editor plugin 
- create new post 
- add image block
- select that existing image from the media library (no other settings touched)
- hit publish. 
- viewed in the page in firefox, using responsive design mode. images resized as expected
