### ISSUE TITLE
Considering a new layout for the editor

### ISSUE THREAD

**Issue by Mocha365** [WordPress/gutenberg#8951]
I was exploring Gutenberg 3.5.0 this last weekend and started to get frustrated with the layout of the editor. I know many have commented on sites about the editor functions being spread out but also hidden. It seems like there is more work and more clicking involved when creating a post.

I believe if the development team wants to gain better interest in this editor, a slight modification of the design for Gutenberg is required. The idea is to make the blocks easily available and to keep them in view at all times instead of having a user clicking around and searching and then scrolling for a block.

I decided to play a bit with a rough mockup of what could be the ideal solution for a slight redesign of the editor. I did one with a dark style and another with a light style.

[Gutenberg Dark](https://www.andrejutras.ca/wp-content/uploads/gutenberg-dark.jpg)
[Gutenberg Light](https://www.andrejutras.ca/wp-content/uploads/gutenberg-light.jpg)

**Comment by karmatosed** [comment]
Thanks for taking a look. Whilst I appreciate this suggestion for now we are going to stick with what we have for the block library. There is also an interation going on with it right now #8719.

A few consideration points I would suggest for you in thinking about iterations:

- Mobile: What you suggest wouldn't adapt to smaller devices.
- Interaction sections: Ideally each area has a section that makes sense, it doesn't if you combine and pull out from the block library as you have.
