### ISSUE TITLE
Blank cells are skipped when copied from Excel

### ISSUE THREAD

**Issue by takotakot** [WordPress/gutenberg#8953]
**Describe the bug**
Tables containing blank cells are not treated correctly.

**To Reproduce**
1. Copy a table which contains blank cells
2. Paste

**Expected behavior**
See **Screenshots**

**Screenshots**
Excel:
![excel_table_2018_0814](https://user-images.githubusercontent.com/10368878/44069365-55de7f04-9fb9-11e8-9da5-d13b0c8955da.png)

Current behavior:
![wordpress_table_wrong_2018_0814](https://user-images.githubusercontent.com/10368878/44069367-564170dc-9fb9-11e8-807e-417e2ce291dc.png)

Expected:
![wordpress_table_expected_2018_0814](https://user-images.githubusercontent.com/10368878/44069366-5611a564-9fb9-11e8-8713-4666cdd50938.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 68.0.3440.106

**Additional context**
- Gutenberg 3.5.0
- WordPress 4.9.8

Ref: Block audit: Table #8398

**Comment by arunsathiya** [comment]
Noting that I am able to reproduce this as well, on Gutenberg 4.0.0. 

<img width="365" alt="screenshot 2018-10-18 at 19 14 31" src="https://user-images.githubusercontent.com/18581859/47158824-19283800-d30a-11e8-95cb-8dc5241a747b.png">
<sup>Image from Google Sheets indicating that row 2, column 2 has no value</sup> 

<img width="700" alt="screenshot 2018-10-18 at 19 14 19" src="https://user-images.githubusercontent.com/18581859/47158823-19283800-d30a-11e8-8c1a-cd0256a33437.png">
<sup>Image from Gutenberg post editor indicating that a cell is missing, at row 2, column 2</sup> 

--- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 4.0.0 using Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) on macOS 10.14 - Mac OS Mojave

**Comment by dromero20** [comment]
I can replicate the issue by copying a Google Docs Excel and pasting it in Gutenberg too.

Tested in Firefox 63.0.1 (64-bit). macOS 10.14.
Gutenberg: 4.5.1
WordPress: 4.9.8

**Comment by sourourn** [comment]
I was able to reproduce this issue by copying from Excel and pasting into Gutenberg.

Firefox (61.0.2) on MacOS
WordPress version: 4.9.8
Gutenberg version: 4.5.1

![screen shot on 2018-11-22 at 14-16-15](https://user-images.githubusercontent.com/39188945/48902546-91ca6900-ee61-11e8-92d1-39b3dea81273.png)
![screen shot on 2018-11-22 at 14-16-33](https://user-images.githubusercontent.com/39188945/48902547-9262ff80-ee61-11e8-8aaa-9f1f4d34da62.png)

**Comment by ellatrix** [comment]
Should be fixed (#14137).
