### ISSUE TITLE
Manage block Category

### ISSUE THREAD

**Issue by amritdeepkaur** [WordPress/gutenberg#8957]
Hi Gutenberg team,
From the link
https://github.com/WordPress/gutenberg/pull/7606
i get to know that i can create my own custom category and in Gutenberg 3.4, its working fine,
But recently i update the plugin to version 3.5 and the following code is not working.

<code>
add_filter( 'block_categories', function( $categories, $post ) {

	if ( $post->post_type !== 'post' ) {
		return $categories;
	}
	return array_merge(
		$categories,
		array(
			array(
				'slug' => 'my-category',
				'title' => __( 'My category', 'my-plugin' ),
			),
		)
	);
}, 10, 2 );
</code>

What should i do???

**Comment by youknowriad** [comment]
It's working just fine for me with your code (make sure to register at least a block for you category)

**Comment by mtias** [comment]
Closing as it should be working. Please, reopen if it doesn't.

**Comment by martinharperlee** [comment]
I also see this as an issue with the exact same code shown above, using v3.9.0

**Comment by pupunzi** [comment]
Have the same problem on Gutemberg 4.1.0:
the below code is not rendering the new category even if a block has been assigned to that category:

PHP code: 

```PHP
add_filter( 'block_categories', 'ytp_block_categories', 10, 2 );
function ytp_block_categories( $categories, $post ) {
  if ( $post->post_type !== 'post' ) {
    return $categories;
  }
  return array_merge(
      $categories,
      array(
          array(
              'slug' => 'mbideas',
              'title' => __( 'mb.ideas Blocks', 'wpmbytplayer' ),
          ),
      )
  );
}
```

javascript code:

```javascript
registerBlockType( 'ytplayer/ytp-block', {
	title: 'YTPlayer Block',
	icon: 'format-video',
        category: 'mbideas',

       ...

} );
```

**Comment by fvonellerts** [comment]
I also had this problem, fixed it by adding a block to the category, building the React package and hooking into `enqueue_block_editor_assets` instead of `init`.
```
add_action('enqueue_block_editor_assets', 'my_block_function');
```
