### ISSUE TITLE
Text align inside cells

### ISSUE THREAD

**Issue by takotakot** [WordPress/gutenberg#8959]
**Describe the solution you'd like**
Want to set 'text-align' inside cells using GUI.
Ex: `<td style="text-align: right;">text</td>`

**Describe alternatives you've considered**
 We can (currently) set 'text-align' styles using "code editor".

Ref: #8398

**Comment by ajitbohra** [comment]
We have one issue(#6923) focusing on feature/enhancement for tables so closing this to focus there.
