### ISSUE TITLE
When using the delete key to remove blocks, the caret is positioned incorrectly

### ISSUE THREAD

**Issue by talldan** [WordPress/gutenberg#8965]
**Describe the bug**
When using backspace to delete blocks, the preceding block is correctly selected after the removal takes place.

However, when using the delete key, the behaviour is the same and the preceding block is still selected. To be consistent with how the delete key works normally when deleting text, the start of the next block should instead be selected

**To Reproduce**
1. Create a new post
2. Add four paragraphs of text
3. Select the middle two paragraphs
4. Press the delete key (you may need to use fn+backspace on a laptop)
5. Observe that the caret is placed in the first block

**Expected behavior**
The caret is positioned at the start of the last block

**Additional context**
- Gutenberg 3.5
- The code that handles the delete event is in the component `EditorGlobalKeyboardShortcuts` (this seems to be triggered for multi-selection) or `BlockListBlock` (when there's only a single block selected). Currently, they trigger the `removeBlocks` action, but the `removeBlocks` is not passed any data about the direction of the delete event. Delete and Backspace are both handled in the same way.
- It would be beneficial to add test cases to the block-deletion e2e test when fixing this.

**Comment by aduth** [comment]
To be clear, is this primarily affecting multi-selection?

**Comment by talldan** [comment]
Yep - good to clarify that. There are quite a few ways to delete blocks:

1. Using the block settings menu in a number of situations (handled in BlockSettingsMenu onRemove)
2. Using backspace/delete while block(s) are selected, seems to be mostly handling multi-selection (handled in EditorGlobalKeyboardShortcuts deleteSelectedBlocks)
3. Using backspace/delete while block wrapper is selected (handled in BlockListBlock deleteOrInsertAfterWrapper)
4. Using backspace while typing in some blocks (handled in RichText onDeleteKeyDown)

1, 2 and 3 seem to be affected.

3 (BlockListBlock) does have its own logic to select the end of the previous block, but I think it gets overridden by the REMOVE_BLOCKS effect selecting the start.

**Comment by designsimply** [comment]
Adding a note about backspace vs delete because it confused me at first. My expectation would normally be that `Backspace`or `Fn+Delete` should remove content to the left of the caret and `Delete` should remove content to the right of the paragraph—however, this is reversed on macOS! ([heh](https://lifehacker.com/5803041/the-mac-os-x-delete-key-it-goes-both-ways))—where the `delete` key removes content to the left of the cursor and `fn+delete` or `backspace` removes content to the right. Here is another macOS explanation:

> The delete key keeps the cursor position in the same place. Backspace moves the cursor as it deletes.

<sup>Source: https://ux.stackexchange.com/a/106115</sup>

> Expected behavior
> The caret is positioned at the start of the last block

When removing multiple blocks, I would expect the cursor to land either in the same place in an empty paragraph (this is how the classic editor currently works) or at the end of the prior block. Why would you expect the caret to be positioned at the start of the content previous block after deleting the block just after it 😆 or are we possibly saying the exact same thing in different ways? ([2m6s](https://cloudup.com/ccgvFHzRYeN))

**Comment by designsimply** [comment]
Also see #9041.

**Comment by talldan** [comment]
@designsimply - yep, I think the same thing. It might be easier to say that if I delete the second block using the delete key (fn+delete), the cursor should be at the start of the new second block.

**Comment by aduth** [comment]
Confirmed this is still an issue as of May 31, 2019.

**Comment by paaljoachim** [comment]
Testing with WordPress 5.7 beta 3.
Gutenberg plugin 10.
Twenty Twenty One.

> To Reproduce
> 
> Create a new post
> Add four paragraphs of text
> Select the middle two paragraphs
> Press the delete key (you may need to use fn+backspace on a laptop)
> Observe that the caret is placed in the first block

Added four paragraphs with text. Selected the two middle paragraphs. Clicked the backspace/del key. 
The two middle paragraphs were deleted and the caret is placed at the end of the first paragraph.

> Expected behavior
> The caret is positioned at the start of the last block

It was not. 
This issue has not yet been fixed.
@ellatrix

**Comment by joelyoder** [comment]
Testing with WordPress 5.6.2
Gutenberg 10
Twenty Twenty One

What's weird about this one is that I only got the error the first time I tried it, and it worked as expected after that.

My first attempt, after deleting the two paragraphs, the first paragraph was focused and there was no caret at all. Every other attempt after that, including making a new page is behaves as expected: [https://recordit.co/7JwxmLEIac](https://recordit.co/7JwxmLEIac)

**Comment by gwwar** [comment]
As a reminder for folks, <kbd>del</kbd> deletes to the right of the cursor, and <kbd>backspace</kbd> to the left. I'm still seeing this behavior with <kbd>del</kbd>

https://user-images.githubusercontent.com/1270189/109210345-8c0b0e80-7761-11eb-98e3-ec25da2f51cd.mp4

**Comment by thomashigginbotham** [comment]
I'm not sure that moving the cursor to the fourth block is the desired behavior with the delete key. In most text editors, if you select text over multiple lines, the caret position afterward does not depend on whether you pressed <kbd>backspace</kbd> or <kbd>del</kbd>.

The end position depends on whether you selected the newline before the selected text or if you selected the newline after the selected text. In the context of selecting blocks, it isn't possible to select a newline, so I suggest the behavior remain as is unless there is a distinct advantage to changing the caret position after the deletion.

**Comment by joelyoder** [comment]
I'm with Thomas that the behavior should be consistent whether you use <kbd>backspace</kbd>or <kbd>del</kbd>.

Testing some popular word processing interfaces, the behavior is consistent regardless of what button you use. In Word, the caret moves to the beginning of the next paragraph. On Google Docs, it just keeps an empty paragraph between the first and last.

If the behavior was different depending on what key you used, I can see that causing more confusion if users expect the editor to behave like other common word processing software.

**Comment by talldan** [comment]
What I'd compare it to is deleting a single paragraph block using the delete key—the caret ends doesn't positionally move. The difference is that the editor considers this a text deletion, whereas with multiple block selected, it will be considered a block deletion. Whether a user should be aware that there's a difference between text or block selection, I don't know.

But this is a very minor thing. I think it's worth closing this now. When I first created this, the block editor was still yet to land in core, and there were a few of these caret position issues being resolved. More than two years later this doesn't seem like something that anyone has noticed, so changing this wouldn't really offer much value.
