### ISSUE TITLE
File Block: Long file name - overflow

### ISSUE THREAD

**Issue by Soean** [WordPress/gutenberg#8966]
**Describe the bug**

If the file name is very long, I cant see the `Copy URL` button.

![bildschirmfoto 2018-08-14 um 12 27 54](https://user-images.githubusercontent.com/695201/44086659-8b15dc0e-9fbd-11e8-8631-8ccd3df4104d.png)

**Comment by jorgefilipecosta** [comment]
I wonder about what would be the best option here. Should we limit the file name to a certain amount of characters and show ... if the file name is too big? Or should we break in multiple lines?

**Comment by mtias** [comment]
Might be good to just do an `text-overflow: ellipsis;` for it.
