### ISSUE TITLE
Image reset button issues after image is resized: images don't look the right size on the back end

### ISSUE THREAD

**Issue by abrightclearweb** [WordPress/gutenberg#8968]
**Describe the bug**
When an image is added and resized and then the Image Dimensions Reset button is pressed, the dimensions revert to their previous values, but the image does not look like the original size in the Gutenberg editor.

**To Reproduce**
1. Create a post.
2. Add an image block.
3. Use the image resize handles to resize the block from Full size. 
4. Use the Reset button under Image Dimensions to return it to the original size as shown in the Image Size dropdown.

Alternatively:
1. Create a post.
2. Add an image block.
3. Change the image size using the Image Size dropdown to e.g. Medium and then select one of the % button sizes. 
4. Use the Reset button under Image Dimensions to return it to Medium size.

**Expected behavior**
I would expect that the image would return to its original size in the block. While the image dimensions update back to what was originally chosen, the image does not look the correct size visually in the Gutenberg block. This is confusing.

If I preview or publish the post, images are the correct size on the front end.

**Screenshots**
Some of the below images have had resizing but no resetting for comparison.

![full size 1920 x 1280](https://user-images.githubusercontent.com/7430856/44088706-1458de1e-9fbc-11e8-9d41-cea8a42f2432.png)

![reszed full and reset -1920 x 1280](https://user-images.githubusercontent.com/7430856/44088739-2952cffa-9fbc-11e8-971e-9dae80e13416.png)

![resized full 406 x 270](https://user-images.githubusercontent.com/7430856/44088943-dca2c416-9fbc-11e8-83ec-e0b25b23f0ed.png)

![resized full and reset - 1920 x 1280 2](https://user-images.githubusercontent.com/7430856/44088827-738c460a-9fbc-11e8-855e-d9e29a6a633b.png)

![resized medium - 150 x 100](https://user-images.githubusercontent.com/7430856/44088957-f53f8626-9fbc-11e8-9d34-004a6dfcd060.png)

![resized medium reset - 300 x 200](https://user-images.githubusercontent.com/7430856/44088963-f9a1c558-9fbc-11e8-94c1-49f85ed7efb0.png)

The front end: 

![image sizing and reset](https://user-images.githubusercontent.com/7430856/44089040-43041430-9fbd-11e8-8f30-53da2d33dacb.png)

**Desktop (please complete the following information):**

 -   OS: Windows 10 64-bit
-    Browser: Firefox Quantum
-    Version 61.0.2 (64-bit)

**Additional context**

  -  Gutenberg 3.5.0

**Comment by davoraltman** [comment]
Are you still experiencing this error with Gutenberg 4.1.0?

I tested on Chrome 69.0.3497.100 on Mac 10.13.6 and can't replicate so I'm wondering if the issue was fixed or if it's present only on Windows.

Video of what I found - http://cld.wthms.co/RSzhGM

**Comment by abrightclearweb** [comment]
I'm still having issues. See this screencap:


![reset image size](https://user-images.githubusercontent.com/7430856/48588154-ce600700-e92d-11e8-828c-98b61d1671f0.gif)


I'm using Firefox Quantum, 63.0.1, Windows 10 64-bit, Gutenberg 4.3.

**Comment by youknowriad** [comment]
Just tested this and it's still happening.

**Comment by paaljoachim** [comment]
Testing

WordPress 5.7 beta 1
One active plugin - WordPress Beta Tester plugin.
Theme: Twenty Twenty One
local site
Chrome
OSX 10.15.7

Testing instructions:

1. Create a post.
2. Add an image block.
3. Use the image resize handles to resize the block from Full size.
4. Use the Reset button under Image Dimensions to return it to the original size as shown in the Image Size dropdown.

Made a new post. Added an Image block. Image size: Full Size.
Dragged the image resize handles to resize the image.
Clicked the Reset button to return to original size. (Does not work - I believe the Reset only affects the Image dimensions settings and not the resize handlebars.)

**Comment by Mamaduka** [comment]
I think I accidentally fixed this issue via #29919. The fix should be part of the Gutenberg 10.4 release.

Current testing screen recording:

https://user-images.githubusercontent.com/240569/120218506-e3ca8180-c24a-11eb-9e88-6a953563f760.mp4

**Comment by paaljoachim** [comment]
Great!
We can then go ahead and close this issue.
