### ISSUE TITLE
Block audit: Separator

### ISSUE THREAD

**Issue by sarahmonster** [WordPress/gutenberg#8970]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="58" alt="screenshot 2018-08-14 13 06 52" src="https://user-images.githubusercontent.com/376315/44090701-04e08250-9fc3-11e8-8288-8f5dca559c9c.png">

**Name:** Separator
**Description:** Insert a horizontal line where you want to create a break between ideas.
***Category:** Layout elements
**CSS class:** `wp-block-separator` in frontend and editor
**Can be converted to:** nothing

# States

*Empty:*
<img width="432" alt="screenshot 2018-08-14 13 03 10" src="https://user-images.githubusercontent.com/376315/44090722-0e8b4c18-9fc3-11e8-87ed-3f2ab6d5b939.png">

*Selected:*
<img width="432" alt="screenshot 2018-08-14 13 03 10" src="https://user-images.githubusercontent.com/376315/44090722-0e8b4c18-9fc3-11e8-87ed-3f2ab6d5b939.png">

*Unselected:*
<img width="408" alt="screenshot 2018-08-14 13 03 19" src="https://user-images.githubusercontent.com/376315/44090737-1903e3c6-9fc3-11e8-87ad-a1a637a18eab.png">

*Placeholder:*
<img width="408" alt="screenshot 2018-08-14 13 03 19" src="https://user-images.githubusercontent.com/376315/44090737-1903e3c6-9fc3-11e8-87ad-a1a637a18eab.png">

# Primary (toolbar) settings

Block styles

# Secondary (sidebar) settings

Advanced: Additional CSS class

# Frontend appearance

**Gutenberg starter theme:**
<img width="700" alt="screenshot 2018-08-20 11 56 36" src="https://user-images.githubusercontent.com/376315/44336730-4bcfc480-a470-11e8-8475-4661ec284b75.png">

**Atomic Blocks**
<img width="730" alt="screenshot 2018-08-20 11 55 21" src="https://user-images.githubusercontent.com/376315/44336763-6144ee80-a470-11e8-8cb1-bc93c249ef85.png">

**twentyseventeen:**
<img width="566" alt="screenshot 2018-08-20 11 53 08" src="https://user-images.githubusercontent.com/376315/44336746-54c09600-a470-11e8-8a0e-d01bc52ee281.png">

**twentyten:**
<img width="684" alt="screenshot 2018-08-20 11 57 30" src="https://user-images.githubusercontent.com/376315/44336782-699d2980-a470-11e8-9470-f2915e6ed244.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] Existing `<hr>` background styling (typically a background colour) is applied via the theme, which can create some unexpected behaviour. Consider setting background: transparent.

- [ ] Often the theme's `<hr>` styling will override any differentiation between wide and short separators, and both end up full-width.

- [ ] Block up/down controls are hard to use because the block is so short.

# Suggestions

_Individual issues will be opened for these soon_

- [x] "a break between ideas" is tricky for translations (#7079); worth keeping in mind when we suggest new descriptions for this block.

**Comment by webmandesign** [comment]
Adding my 2 cents here: #10569 

Possibly fixing:
_Often the theme's `<hr>` styling will override any differentiation between wide and short separators, and both end up full-width._

**Comment by GlennMartin1** [comment]
As of 4.2-rc1, it's not possible to move the Separator like other blocks can be moved.

If it's at the wrong place, it's got to be deleted and reinserted elsewhere.

**Comment by karmatosed** [comment]
#14101 created from this issue.

**Comment by karmatosed** [comment]
Closing out the issue as made into separate ones.
