### ISSUE TITLE
Post preview tab does not show actual preview. Halts at "Please wait" message.

### ISSUE THREAD

**Issue by emfluenceindia** [WordPress/gutenberg#8973]
**Describe the bug**
I have WordPress 4.9.8 fresh installation. Only plugin activated is Gutenberg ( v 3.5.0 ). When I am trying to `Preview` a post, it opens a new window with the following message:

> Please wait…
> Generating preview.

and nothing happens after that.

**To Reproduce**
1. Go to Add New Post
2. Add title and put some content
3. Click on Preview button

**Expected behavior**
Should bring up the preview.

**Screenshots**
https://goo.gl/BQopik

![3b25c596-d569-4b19-8a09-3d1dd4fc5e62](https://user-images.githubusercontent.com/1119271/44121846-9ff52780-9fde-11e8-9ceb-e040e6c58672.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04 LTS
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22] Version 68.0.3440.84 (Official Build) (64-bit)

**Additional context**
- Please add the version of Gutenberg you are using in the description: 3.5.0

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 3.5.0 using Chrome 67.0.3396.99 on macOS 10.13.6 and haven't been able to reproduce the problem where previews get stuck for brand new posts. ([35s](https://cloudup.com/c8FfD7GZ1MQ))

May I ask if you have any plugins installed which could be affecting how posts are saved or ones that affect the API such as security plugins?

**Comment by emfluenceindia** [comment]
@designsimply Thank you for checking and your quick reply! Yes, there are some plugins installed but the only plugin activated is Gutenberg. The major concern is Gutenberg breaks even no plugin is activated. Activation of plugins may cause issues, but only installation should not! This is how I feel any plugin should work. Also another major issue is when Gutenberg will be taken into WP core. A live site can anytime break due to Gutenberg. It must have a proper documentation about its limitations and troubleshooting. I personally feel this is going to be more than a major breaking change which is not properly documented yet and developers do not know much about the trouble shootings! Do you have a list of popular plugins which might get affected due to Gutenberg?

**Comment by emfluenceindia** [comment]
Keeping everything as they were I updated to version 3.6.0 today and the issue got resolved!

**Comment by mtias** [comment]
Glad to hear it's working now. Feel free to reopen if you experience a similar issue again.
