### ISSUE TITLE
Columns (beta) block responsive columns wrapping

### ISSUE THREAD

**Issue by webmandesign** [WordPress/gutenberg#8975]
**Describe the bug**
Columns are using CSS flexbox layout, however, they do not apply `flex-wrap: wrap;` currently and so they break responsive view.

**To Reproduce**
The best way to reproduce is to add 3+ columns and make them aligned full. Then just resize the browser window while previewing the post/page on the front-end of your website to see columns not stacking properly on narrow (mobile) screens.

**Expected behavior**
Columns wrap/stack on narrow (mobile) screens depending on their content width.

**Video**
https://www.dropbox.com/s/xkj1xjux997ailv/gutenberg-columns-block-flex-wrap.mp4

**Comment by chrisvanpatten** [comment]
Hi @webmandesign –

Thanks for the report! We have an issue for responsive columns over at #6048. Since it's a duplicate I'll close this issue but definitely recommend commenting over there with your suggestion on the implementation with `flex-wrap`.

Cheers!

**Comment by chrisvanpatten** [comment]
@webmandesign There was a lot of discussion in #6048 but ultimately the plan was a simpler solution like your suggestion… in spite of all the back and forth 😁
