### ISSUE TITLE
Consider adding a link to more detail about embeds

### ISSUE THREAD

**Issue by kristenzuck** [WordPress/gutenberg#8976]
We did some testing on a team call and all found the embed descriptions a bit unclear. If you aren't sure what an embed is, or where to find the URL you need, it isn't clear how/where to find out. 

It'd be great to link to either a broad guide on embeds or information on individual services in the main block description within the page/post editor, or at least on the sidebar. 

![screen shot 2018-08-09 at 8 50 37 am](https://user-images.githubusercontent.com/10063468/44096259-de1c26e8-9fa8-11e8-8ace-bc698e927d7e.png)

**Comment by designsimply** [comment]
Is the placeholder text inside the text field that says "embed" the part you think may throw people off or is it more that you are worried about discoverability for people trying to embed something like an Instagram block without having any prior knowledge for how to find an embeddable URL from that service?

Note: consider https://codex.wordpress.org/Embeds if an external link is a possibility in the design.

**Comment by kristenzuck** [comment]
More the later, I think providing a link like you have to the .org Embeds page would be a great option to help with this though.
