### ISSUE TITLE
RichText: Initial value not guaranteed to sync with DOM output

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#8983]
In some circumstances, passing a value to RichText can result in that value not being respected.

For example, consider:

```jsx
<RichText value={ [ { type: 'strong', props: { children: [] } } ] } />
```

In this case, while a `strong` node is included in the value, and will be initially rendered by the serializer as `<strong></strong>`, it will be removed by TinyMCE and this removal will not be synced back to the value state (i.e. the `RichText` `onChange` callback will not be called).

Ultimately this is related to TinyMCE's default behavior for removing specific empty nodes:

https://github.com/tinymce/tinymce/blob/ae21de31d0456a9b09a0b79744898c7348b63371/src/core/main/ts/api/html/Schema.ts#L743-L748

_(Aside: It's assumed #8665 may be related to the fact the `code` tag not being included in this set)_

Options for moving forward include:

- Bypass or override these `removeEmpty` defaults from TinyMCE (via `settings.valid_elements`)
- Respect `removeEmpty` at some point in our own rendering / assignment of RichText value: `valueToString` or in the `RichText` constructor
- Force a sync of value when TinyMCE initializes, in case the DOM was changed
   - Not the most performant option

cc @androb

**Comment by azaozz** [comment]
This has come up in the "classic" editor too. The underlying question is: do we want to have empty HTML tags in RichText? As far as I understand TinyMCE treats pretty much all empty tags as "errors", even in cases when they have attributes.

In case we don't want to have empty tags the third option above sounds most attractive as it would cover all DOM changes no matter where they come from, i.e. will include the browser's own "bad html" fixes if any. It will also include any changes that may have been added by plugins on `LoadContent` (if plugins can hook there at all).

In case we want to keep the empty tags, we would need a setting in TinyMCE to stop removing them, on loading and saving. This is not currently possible (as far as I see).

**Comment by iseulde** [comment]
@aduth? Is this still an issue? I think the value is now synced? But an empty tag will indeed be removed, which seems expected.

**Comment by aduth** [comment]
> But an empty tag will indeed be removed, which seems expected.

The bigger issue is the fact that it wasn't synced to state; if we remove the empty tag, is it at least reflected back in state by a change event?

**Comment by iseulde** [comment]
@aduth In my opinion, this is okay, if you don't edit the content. As soon as you edit the content, it will be reflected in state. We also wouldn't want to sync changes e.g. when loading post content? This would unexpectedly change the content without any user action and add undo levels.

**Comment by aduth** [comment]
I think I'm okay to consider this as working as intended.
