### ISSUE TITLE
Fix centering pictures on mobile versions

### ISSUE THREAD

**Issue by ldinoto** [WordPress/gutenberg#8988]
**Describe the bug**
Pictures centered in a post are not centered on mobile versions, so the right side of any picture that's not tiny is chopped off in mobile view.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: current
 - Browser: safarai 
- Version: current

**Additional context**
- Please add the version of Gutenberg you are using in the description: Current

**Comment by designsimply** [comment]
Closing as a duplicate of #8947 and you can follow along there. Thanks!

**Comment by ldinoto** [comment]
Thank you!
