### ISSUE TITLE
Show the formatting toolbar for React Native blocks

### ISSUE THREAD

**Issue by SergioEstevao** [WordPress/gutenberg#8989]
Make the component Format-Toolbar compatible with the React Native implementation and displayable on the RN mobile version of the project.

- [ ]  Make the format bar code (format-toolbar) compatible with React Native
- [ ]  Implement Buttons with text only
- [ ]  Implement Buttons using an image and or SVG
- [ ]  Link Button/Toolbar actions to Aztec RN

**Comment by marecar3** [comment]
Closing this one as it's a duplicate of https://github.com/wordpress-mobile/gutenberg-mobile/issues/55
