### ISSUE TITLE
Block with 3 column template renders with 3 columns

### ISSUE THREAD

**Issue by belcherj** [WordPress/gutenberg#8990]
**Describe the bug**

The template below should produce a 3 column layout when added. It creates a two column layout until you edit as html then switching back to visual the 3rd column appears until page reload.

```
const TEMPLATE = [
	[ 'core/heading', {} ],
	[ 'core/columns', {}, [
		[ 'core/column', {}, [
			[ 'core/heading', {} ],
			[ 'core/paragraph', {} ],
		] ],
		[ 'core/column', {}, [
			[ 'core/heading', {} ],
			[ 'core/paragraph', {} ],
		] ],
		[ 'core/column', {}, [
			[ 'core/heading', {} ],
			[ 'core/paragraph', {} ],
		] ],
	] ],
];
```
`<InnerBlocks template={ TEMPLATE } />`

Gist of full block:  https://gist.github.com/belcherj/b458cba2a26f6a98e75687b187bb42bd

**To Reproduce**
1. Add the block in the gist above to your site
2. Go to Gutenberg editor and add the block
3. Observe that only two columns appear

**Expected behavior**
Three columns should appear.

**Screenshots**
This is the error state:
![screen shot 2018-08-14 at 2 56 00 pm](https://user-images.githubusercontent.com/6817400/44112115-3fd4c092-9fd2-11e8-93e4-2cc2449b044c.png)

Should look like this, looks like this after going to html view and back to visual until page is reloaded.
![screen shot 2018-08-14 at 2 56 12 pm](https://user-images.githubusercontent.com/6817400/44112108-3b9ceeb4-9fd2-11e8-8152-408c8269c59a.png)

**Desktop (please complete the following information):**
 - OS: All
 - Browser Chrome
 - Version Latest

**Additional context**
- Gutenberg Version: 3.5.0

**Comment by haszari** [comment]
There's a `columns` attribute which you can pass to the template explicitly. It looks like the block doesn't infer the column count from the data passed in.

For example:

```js
const TEMPLATE = [
	[ 'core/heading', {} ],
	[ 'core/columns', {
		columns: 3,
	}, [
		[ 'core/column', {}, [
			[ 'core/heading', {} ],
			[ 'core/paragraph', {} ],
		] ],
		[ 'core/column', {}, [
			[ 'core/heading', {} ],
			[ 'core/paragraph', {} ],
		] ],
		[ 'core/column', {}, [
			[ 'core/heading', {} ],
			[ 'core/paragraph', {} ],
		] ],
	] ],
];
```

**Comment by jiteshdhamaniya** [comment]
is there anyway we can control width of Column too. 
like i want to have image(core/image) in one column and content (core/paragraph) in another. 
i can have them in 1:3 ratio ?

**Comment by jnz31** [comment]
> is there anyway we can control width of Column too.
like i want to have image(core/image) in one column and content (core/paragraph) in another.
i can have them in 1:3 ratio ?

core/column has a width parameter. see [here](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/column/block.json).
