### ISSUE TITLE
Toolbar vs. Block Settings - rule of thumb for what goes where

### ISSUE THREAD

**Issue by mikedance** [WordPress/gutenberg#8992]
**Is your feature request related to a problem? Please describe.**

There are two locations where block options are placed: the toolbar and the block settings sidebar. Gutenberg does not have a clear philosophy about which settings go in which section. This results in user experience issues such as:

1. Uncertainty on where to look, and managing similar options from two different places: if I am handling block-wide settings, I should look at the block settings...except when handling alignments.

2. Duplicate options taking valuable screen space: on the heading block, I control the heading level in block settings...but I also have a more limited list of the same options in the toolbar.

3. Inconsistent placement of alignment options - in most blocks they are in the toolbar, but in the Heading block they are in the sidebar. (This was almost changed but reverted in #6794.)

4. Fully hidden options - before researching this ticket I did not know Buttons and Separators had block options hidden underneath the "Change block type" option.

**Describe the solution you'd like**

The toolbar exists in the first place to allow users to make selective settings *within* blocks. This would not be possible with the block settings sidebar, which can only control block-wide settings. So I think the solution is staring at us in the face: keep selective settings (such as bold and italic) in the toolbar, and move block-wide settings like alignments to the block settings.

This creates an understanding for both developers and end-users about not only where options go, but the inherent reason they *belong* there.

Nuances:

- Since "Change block type" is a special sort of control, I'm not advocating moving it, at least in the context of this discussion.
- For image and gallery blocks, the "Edit image"/"Edit gallery" option should stay in the toolbar. While it technically alters the whole block, it is a content tool rather than a setting, and makes more logical sense there.

The following changed would be required:

- Move "text alignment" options to block settings for Paragraph, Quote, Subheading, Verse, and Cover Image.
- Move "block alignment" options to block settings for Image, Gallery, File, Audio, Video, Pullquote, Table, Columns, Button, Separator, all widgets except Shortcode, and all embeds.
- Remove heading levels from the toolbar for Heading.
- Move "List View"/"Grid View" to block settings for Latest Posts.
- Move "Block Styles" hidden under "Change block type" to block settings for Button and Separator.

**Comment by designsimply** [comment]
Thank you for your feedback! I would like to note for reference that the design philosophy for what goes where is that primary actions go in the block toolbar whereas secondary actions go in the block settings sidebar and it's noteworthy that the current design has been influenced by results from usability testing. See https://youtu.be/AJHiMEgALic?t=5h13m37s which is a section from a talk given at WordCamp Europe 2018 that explains the anatomy of block settings.

Does this help make the design philosophy more clear? If you were to follow the current design philosophy for placing primary actions in the toolbar and secondary actions in the sidebar, would you still make the same recommendations that you have noted above?

**Comment by mikedance** [comment]
Thanks for the response, the video was very informative. Obviously I can’t speak to the user testing -- the results of that should override one guy’s opinion. But I do still think there is user experience awkwardness to the current system. My issue arose from trying to create a paragraph block. First I wrote the paragraph, then I wanted to style it. So I moved to the sidebar to change colors, then I realized I wanted it to be centered, scanned the sidebar, realized it was back in the toolbar…then came back to the sidebar for other options. It seemed like a better system was to (1) write in one place and (2) change settings in another.

The delineation between “primary actions” (toolbar) and “secondary actions/nice-to-haves” (sidebar) is vague enough that it’s always going to cause development debates (which is how you end up with heading levels in both places) and confuse users (e.g., why would right-aligning text be more important than font size).

But, to answer your question, if Gutenberg is sticking with that philosophy, my recommendations above would be irrelevant with the exception that the options under “Change block type” for Button and Separator seem unnecessarily hidden.

**Comment by designsimply** [comment]
Appreciate the discussion and feedback! It's interesting because there's probably a wide range of preference on it and also the past editor toolbar has been limited to the same options for such a long time. A lot of people ask to customize regardless of what you put where—plugins have been made to answer those kinds of requests in the past (regardless of which editor) and I hope people will continue to make new ones to make adjustments and explore options the same way going forwrad.

Thank you for taking the time to talk this out and for testing Gutenberg.
