### ISSUE TITLE
Gutenberg and WP Globus

### ISSUE THREAD

**Issue by MirjaSchn** [WordPress/gutenberg#8994]
I noticed that there are problems with the new Gutenberg when it comes to WP Globus.
I am writing my blog posts in English and German (using two websites .com and .com/de).
Unfortunatley Gutenberg does not work well with WP Globus. 
For example: it posts the posts on both sites though it's just created for one language.  
It's also confusing when switching back, changing the blog topic.

**Expected behavior**
It would be great if it can be as easy to switch back and forth as with the classic editor.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Mozilla

Ps. It is great!! I would be super happy if you can improve it with the WP Globus Plugin . :-) Good job!!!

**Comment by designsimply** [comment]
Thank you for the feedback! While it is good to make notes about incompatibilities here, would it be possible for you to also make this request in the WPGlobus forums at https://wordpress.org/support/plugin/wpglobus so that they are aware of the problem?

**Comment by tivnet** [comment]
@MirjaSchn We are actively working on Gutenberg support at WPGlobus.

**Comment by pento** [comment]
Awesome, thanks for confirming that, @tivnet!
