### ISSUE TITLE
Filter {post_gallery} does not work with Gutenberg

### ISSUE THREAD

**Issue by Oxibug** [WordPress/gutenberg#9001]
**Describe the bug**
Hi Guys,

I'm using the {**post_gallery**} filter to styling the post content galleries BUT after activating Gutenberg you force my theme to use your style, I try to turn the filter's priority to 99 but the plugin restyled everything inside the content.

So I think you should make a new filter to help developers to make their own styles.

Thanks for your GREAT project.

**To Reproduce**
Using WordPress filter {post_gallery}
`add_filter( 'post_gallery', array( &$this, 'styling_post_gallery' ), 10, 3 );`

**Expected behavior**
Use masonry galleries

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: 68

**Additional context**
Gutenberg v3.5.0

**Comment by mcsf** [comment]
Hi there.

It's important to note that native Galleries in Gutenberg are blocks and not shortcodes. In your scenario, are you using Gallery blocks, or the `[gallery]` shortcode?

In any case, I suggest reading [Extensibility > Theme Support](https://github.com/WordPress/gutenberg/blob/master/docs/extensibility/theme-support.md), but I'd like to know more details in order to help you.

**Comment by Oxibug** [comment]
Yes pal, I know that I'm using the WordPress shortcode, But if the WordPress decide to use the Gutenberg in version 5.0 Then all websites using galleries will be corrupted and you'll force all websites to use your style.

So We (Developers) must update all themes to style your new gallery and (if we did) we cannot force your gallery to use [Justified-Gallery](http://miromannino.github.io/Justified-Gallery/) (for example) instead, so You'll force us to just style the gallery images css only and this is very bad for any blog theme and bloggers, As well as the filter (post_gallery) will be no longer important for anyone.

Thanks for your great project.

Good Luck :)
