### ISSUE TITLE
Parent page selectively shows pages under Gutenberg

### ISSUE THREAD

**Issue by pojke** [WordPress/gutenberg#9004]
This might be a long shot and possibly compatibility issue but I need help debugging from core team.

**The bug**
We have a number of pages that are created by different authors and under a different tree (multiple parents and children). Under Gutenberg, they randomly show in the field "Parent page" and by randomly I mean, when you go to a different page you get sometimes 5, sometimes 9, sometimes all of them.
I would blame compatibility first, except that:

- It works when switching to standard editor
- Under /wp-json/wp/v2/pages?per_page=-1&exclude=95&parent_exclude=95&orderby=menu_order&order=asc&context=edit reguest you always get a full list of pages so as long as that JSON is used in Parent page select field, there's definitely something wrong

**How to reproduce**
The thing is I wasn't successful so far. It's one website only, with one database. Moving to twentyseventeen and removing all the plugins is not fixing it. However, when I tried to reproduce it on a fresh install I was so far unsuccessful. Important - it's a network site. 

**I want to help but**
I know how hard it is to work on a problem you can't reproduce so I can send someone the database directly or if I can get a little bit of help where to put breakpoints on JS to debug I can try to find an issue.

**Comment by chrisvanpatten** [comment]
Hi @pojke I believe this is fixed by #8908 which should be available in Gutenberg 3.6. If you're comfortable building from source, you might want to try the `master` branch and see if that solves the issue. Otherwise, 3.6 should be released soon, so hang tight :)

**Comment by chrisvanpatten** [comment]
Tagging as duplicate (of #8848), and I'll close this for now since #8908 provides a fix. We can always reopen the issue later if necessary, just reply and we'll get it opened!

**Comment by pojke** [comment]
I'd like to confirm that version 3.6 fixed it. Thank you 👍
