### ISSUE TITLE
Update Block: Latest Posts CPT

### ISSUE THREAD

**Issue by philliproth** [WordPress/gutenberg#9013]
I would love the "Latest Posts"-Block to have a drop down for choosing either the regular posts or if one or several custom post type are enabled the opportunity to choose on of them.

- add a select drop down when one or more custom post types are anabled

![post](https://user-images.githubusercontent.com/12558825/44145486-0cef64c4-a08c-11e8-9fb7-4ba30d03ed37.jpg)

**Comment by Soean** [comment]
Related to #1594

**Comment by 0aveRyan** [comment]
When this gets added, the default selected post type should be the current post type...

i.e. - User is creating a new Movie item, dropdown should default to `movies` CPT, user is editing a Comic Book, dropdown should default to `comic_books`.

**Comment by mtias** [comment]
Also related https://github.com/WordPress/gutenberg/issues/2662

**Comment by klihelp** [comment]
+1 Using this for Articles post type which exactly works the same as the regular post type.

**Comment by klihelp** [comment]
Also related to the Archive block.

**Comment by draganescu** [comment]
@Ringish started some exploration on this issue.

**Comment by Ringish** [comment]
Here's a first working [commit](https://github.com/Ringish/gutenberg/tree/add/latest-posts-cpt).

And as @draganescu mentioned at #20046 I should move it to the `QueryControls`!

![ezgif-3-cbf4b52b789c](https://user-images.githubusercontent.com/3396172/76523735-331b6b00-6469-11ea-9389-167b421edd3f.gif)

**Comment by paaljoachim** [comment]
Based on @ntsekouras Nik's comment here: https://github.com/WordPress/gutenberg/pull/20831#issuecomment-720321646
Should this issue be closed?

**Comment by Mamaduka** [comment]
I think we can close this issue. The query block can be used to display posts from different post types.
