### ISSUE TITLE
ServerSideRender pass internal attributes, forceUpdate and _builtIn flag for attributes

### ISSUE THREAD

**Issue by edirpedro** [WordPress/gutenberg#9019]
This is a example about how I'm building a block to render a common form element to submit data, saves it as custom fields and refresh the block with the results. This is useful to use the ACF plugin to create these blocks, when you don't have "much time" on the project to build all the JavaScript to create a beautiful interface to edit the block.

I would like someone to test this and tell me if the design is correct, because I'm not familiar to React JS and there are some points on Gutenberg that maybe could be improved on the component ServerSideRender. My points:

1. A way to pass additional internal attributes. I'm currently using the `plugin` attribute to pass those data as an array;
2. A flag like `_builtIn` to do not include the attribute in the saved tag `<!-- 'test/block' { attributes } /-->`.
3. I couldn't use the React function `forceUpdate()` to refresh the block and I didn't find another way so i used the attribute `updated` to fire a refresh action.

PHP:
```
register_block_type('test/block', array(
	'attributes' => array(
		'plugin' => array(
			'default' => array(
				'post_id' => 123,
				'key' => 'group_duq8f62hf',
				'title' => 'My Block',
			),
			'_builtIn' => true,
		),
		'updated' => array(
			'type' => 'number',
			'default' => 0,
			'_builtIn' => true,
		),
		'others' => array(
			'type' => 'string',
		)
	),
	'render_callback' => function($attributes, $content) {
		return 'Hello!';
	}
));
```

JS:
```
(function(wp) {
	
	var el = wp.element.createElement,
	    registerBlockType = wp.blocks.registerBlockType,
	    BlockControls = wp.editor.BlockControls;
		ServerSideRender = wp.components.ServerSideRender;
		Toolbar = wp.components.Toolbar;
		IconButton = wp.components.IconButton;

	registerBlockType('test/block', {
		title: 'Block',
		icon: 'megaphone',
		category: 'widgets',
	
		edit: function(props) {
			
			// Simulates a modal with a form to submit data
			function openDialog(props) {
								
				var title = props.attributes.plugin.title;
				var result = confirm(title + ': This simulates open a form into a modal and saves the content to custom fields, then refresh the block.');

				if(result)
					props.setAttributes({ updated: Date.now() });
				
			}

			return [
						el(
							BlockControls,
							{ key: 'controls' },
							el(
								Toolbar,
								null,
								el(
									IconButton,
									{
										className: 'components-icon-button components-toolbar__control',
										label: 'Edit',
										onClick: function() { openDialog(props) },
										icon: 'edit'
									}
								)
							)
						),
						el(
							ServerSideRender, 
							{
								block: props.name,
								attributes: props.attributes
							}
						)
					];

			
		},
	
		save: function() {
			// Rendering in PHP
			return null;
		},
	});
	
})(window.wp);
```

**Comment by youknowriad** [comment]
You can pass the `urlQueryArgs` prop to the `ServerSideRenderer` component to pass the extra arguments without persisting them. I think this addresses the concerns in this issue.

Thanks.
