### ISSUE TITLE
404 Message When Published

### ISSUE THREAD

**Issue by NormHamilton** [WordPress/gutenberg#9021]
When I publish a page or post I can no longer view it as a preview or as a published page as it gives a 404 message. If I change it back to draft, I can view the preview again.

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 3.5.0 and I was not able to see the same problem happen. Can you tell me a little bit more about your setup and your testing steps?

First, are you using the latest stable release of Gutenberg which is 3.5.0 and may I ask you to note your OS and browser version?

Are you using WordPress multisite or a single install?

What settings are you using for permalinks?

Do you have any plugins installed which seem like they might be causing a conflict?

**Comment by NormHamilton** [comment]
I tried Gutenberg on another Wordpress site with a different theme and it
seems to work just fine.
I suspect it is the Atuhalpa theme that is problematic.
When I get a chance I'll try another site that uses Atuhalpa.

Peace, Health and Harmony

Norm Hamilton, Photographer and Writer
*Professional Photography <http://www.normhamilton.ca/photography>  *
*Writer, Copy-editor, Proofreader <http://www.normhamilton.ca/writer>*
*Author of The Digital Eye <http://amzn.to/19iAQmV> and **From Thine Own
Well* <http://fromthineownwell.normhamilton.ca/>
email: ytnorm@gmail.com

**Comment by tofumatt** [comment]
Sounds like this was an issue with a theme and not Gutenberg, so I'm closing the issue for now. Please re-open it if the issue persists without the Atuhalpa theme 😄
