### ISSUE TITLE
The billion dollar cost of Gutenberg

### ISSUE THREAD

**Issue by scottybo** [WordPress/gutenberg#9023]
I’ve now spent a very large amount of time with Gutenberg and created the 1,000th issue (at the time of writing) on this repo. Conservatively I think it’s going to take around a days work per customer to teach them how to use this new system.

Charged out at our daily rate, you’re talking a conservative cost of £40,000 in lost revenue which we won’t be able to bill to our customers as this is “our” change. Multiply this out across the Wordpress ecosystem and the costs of Gutenberg to business are astronomical. Let’s be conservative and say there are 20,000 other businesses in our situation (there are an estimated 75 million websites using Worpress, so this number is not unreasonable).

Gutenberg is potentially costing businesses **£800,000,000 ($1 billion dollars)** in lost revenue.

I have opened this as a Github issue as I would like the Gutenberg team to respond to this observation and get there thoughts on why this cost should be pushed onto the ecosystem.

**Comment by tofumatt** [comment]
I'm not sure about the maths in this issue and I don't think speculation is a very constructive way to frame a discussion.

But it seems like the question you're getting at is "Why does WordPress think you should take time /spend hours learning Gutenberg?" The answer is: because we think it's better and we think it's the future of WordPress editing.

**Comment by scottybo** [comment]
Ok, so let's say may maths is WAY off and it'll be £1,000 in lost revenue on average - that's still £20,000,000.

My question is valid - has the Gutenberg team considered the cost to the owners of 75 million websites in lost time and revenue?

I've been using Wordpress professionally for almost 15 years now and Guternberg is the reason we'll be developing all new websites on a different system.

This will be the Digg of the CMS world, and it's a very sad day indeed.
