### ISSUE TITLE
m4a files not uploading to posts

### ISSUE THREAD

**Issue by detlefholtz** [WordPress/gutenberg#9028]
**Describe the bug**
When editing a post, m4a files cannot be added directly from desktop through the block. It seems to work when going through the Media Library it works, but when uploading through the block I receive the error `Sorry, this file type is not permitted for security reasons.`

**To Reproduce**
1. Create a new post. 
2. Try adding an m4a file from desktop to a block using the audio option. 
3. See error

**Expected behavior**
File should've uploaded straight to post. Works well when choosing an m4a that's already been uploaded to the Media Library.

**Desktop (please complete the following information):**
 - OS: OS X 10.13.4 
- Browser: Chrome Version 68
- Gutenburg Version 3.5.0

**Comment by Soean** [comment]
When I upload an MP4 file it has the mime type `audio/x-m4a`. This one is not supported in [wp_get_mime_types()](https://developer.wordpress.org/reference/functions/wp_get_mime_types/). Trac ticket 40175 will fix this issue: https://core.trac.wordpress.org/ticket/40175

**Comment by jorgefilipecosta** [comment]
Thank you @detlefholtz for reporting this issue. Thank you @designsimply and @Soean for your insights. It seems this issue contains good progress on trac so I will close this issue as we can track it on https://core.trac.wordpress.org/ticket/40175.

**Comment by abt462** [comment]
I have the same issue and we're 6 years later. Is it still in progress or was it fixed and reappeared?
