### ISSUE TITLE
Gutenberg: Convert to blocks drops span tags

### ISSUE THREAD

**Issue by johngoold** [WordPress/gutenberg#9029]
When paragraphs are converted to blocks, the span tags are dropped.

**To Reproduce**
1. Edit (not Classic edit) a post that has HTML span tags inside paragraphs.
2. Click on the menu (3 vertical dots) to the right of the editor toolbar.
3. Select the "Convert to Blocks" item
4. Click on the menu in the top right and select "Code Editor"
5. The span tags have disappeared.

**Expected behavior**
Span tags should be unaffected

**Desktop (please complete the following information):**
 - OS: Linux Mint 18.2 Cinnamon 64-bit
 - Browser: Firefox
 - Version: 61.0.1 (64-bit)

**Smartphone (please complete the following information):**
Not applicable.

**Additional context**
Gutenberg: 3.5.0

Code of post to be converted to blocks: 
[fonts-page.txt](https://github.com/WordPress/gutenberg/files/2290691/fonts-page.txt)

It is not really a .txt file but an .html file.

Active Firefox plugins: Akismet Anti-Spam (4.0.8); Gutenberg (obviously); WP Missed Schedule Posts (1.1)

**Comment by ZebulanStanphill** [comment]
I think this is a duplicate of #6102.

**Comment by johngoold** [comment]
Thank you. Yes it is. I didn't find #6102 when scanning (there are a lot of entries!).

**Comment by johngoold** [comment]
Duplicate of #6102
