### ISSUE TITLE
When scheduling a post to publish, not possible to change and publish immediately

### ISSUE THREAD

**Issue by ericaherschorn** [WordPress/gutenberg#9030]
**Describe the bug**
During testing, I noticed that I was unable to publish a post after scheduling a publish in the future. If you convert your post into a classic editor post the functionality works fine, leading me to believe it is a Gutenberg bug.

**To Reproduce**
1. Go to "create a new post" or "edit a post"
2. Change the date of publish to the future, and click "schedule" (successfully schedules for the future)
3. Go back to edit the post, and change the publish date to today, or a date in the past, and click "publish"
4. Error occurs - it takes you back to the schedule post menu, and there is no way to save the new date.

**Expected behavior**
Post publishes

**Screenshots**
Future date - schedule button shows
<img width="416" alt="future-date-schedule-button" src="https://user-images.githubusercontent.com/13858169/44156466-89895484-a075-11e8-8abe-fc26bbc9d557.png">

Change date to past - publish button shows
<img width="412" alt="change-date-to-past" src="https://user-images.githubusercontent.com/13858169/44156908-ae8f1d80-a076-11e8-81c3-40adc7aea6ba.png">

Click "publish, and this menu slides in from the right, showing a date in the past (today is Aug 15)
<img width="299" alt="menu" src="https://user-images.githubusercontent.com/13858169/44156948-d0ac8c72-a076-11e8-8843-dbe08a48549f.png">

**Desktop (please complete the following information):**
 - OS: MacOS High Sierra v. 10.13.5
 - Browser: Chrome
 - Version 68.0.3440.106

**Smartphone (please complete the following information):**
Not tested on device.

**Additional context**
- WordPress Version 4.9.8
- Gutenberg Version 3.4.0

**Comment by boemedia** [comment]
I tested this with Gutenberg 3.8.0 and WP 4.9.8. I can confirm going straight from schedule to publish doesn't work. Apparently, you have to go back to concept mode now before you're able to publish immediately. I love how Hootsuite handles this: the _'schedule button'_ and _'send now'_ are detached. In my opinion, this gives a clearer UX. 

![hootsuite social media planner](https://user-images.githubusercontent.com/29769622/45669679-1545a200-bb21-11e8-8e77-b8532e921e78.jpg)
Hootsuite publishing screen, with a calendar icon if you want to schedule a post.

![hootsuite after clicking calendar](https://user-images.githubusercontent.com/29769622/45669728-34dcca80-bb21-11e8-8a3c-75126a536267.jpg)
When you click that calendar icon, the pane expands with scheduling options.

**Comment by nosolosw** [comment]
Consolidating in https://github.com/WordPress/gutenberg/issues/10930
