### ISSUE TITLE
Editor package: invalid DOM nesting in PostPublishPanelToggle component

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#9033]
**Describe the bug**

Using the `PostPublishPanelToggle` component from `@wordpress/editor` package produces the following console warning:

```
Warning: validateDOMNesting(...): <button> cannot appear as a descendant of <button>.
```
This is caused by the fact that `PostPublishPanelToggle` nests a `DotTip` inside of a `button`:

https://github.com/WordPress/gutenberg/blob/94f54892c214ebd014ec126a9575b7e902198ad9/packages/editor/src/components/post-publish-panel/toggle.js#L45-L57

and `DotTip` in turn renders a button too (or two if `IconButton` renders it):

https://github.com/WordPress/gutenberg/blob/09dc71c30ebcbf5b1b4475cab433eaa9b21e1908/packages/nux/src/components/dot-tip/index.js#L41-L51

**To Reproduce**

```javascript

import { PostPublishPanelToggle } from '@wordpress/editor';

...

render() {
	return <PostPublishPanelToggle />;
}
```

**Related issue**

A similar issue exist in `edit-post`'s header component, where `DotTip` is nested inside of `IconButton`:

https://github.com/WordPress/gutenberg/blob/master/edit-post/components/header/index.js#L57-L68

**Comment by vindl** [comment]
cc @youknowriad @gziolo @aduth

**Comment by aduth** [comment]
Previously: https://github.com/WordPress/gutenberg/pull/6631#discussion_r196543561

**Comment by pento** [comment]
This issue (or, more broadly, the problem of using a `<DotTip>` inside a `<Button>`) is a blocker for making the dev environment more reliable.

It can currently be reproduced by running e2e tests with `SCRIPT_DEBUG` set to `true`. If you're not sure if your local environment is configured to reproduce it, you can rebuild it and test like so:

```
npm run env stop
rm -rf wordpress
npm run build
npm run env install
npm run test-e2e
```
