### ISSUE TITLE
Editor package: deprecated lifecycle method warning in TinyMCE

### ISSUE THREAD

**Issue by vindl** [WordPress/gutenberg#9037]
The editor package is using the deprecated `componentWillReceiveProps` lifecycle method which produces console warnings when executed in React strict mode.

https://github.com/WordPress/gutenberg/blob/4c28bd0d2740a5293fc449e9dd8b3ac9906ddba5/packages/editor/src/components/rich-text/tinymce.js#L117

```
Warning: Unsafe lifecycle methods were found within a strict-mode tree:
...
componentWillReceiveProps: Please update the following components to use static getDerivedStateFromProps instead: TinyMCE
```

**Comment by iseulde** [comment]
Was fixed in #11368.
