### ISSUE TITLE
Removing a block with Backspace restores removed texts.

### ISSUE THREAD

**Issue by Chintiger** [WordPress/gutenberg#9041]
**Describe the bug**
When removing a paragraph block with backspace key, it restores the removed texts in the end of the previous paragraph.

**To Reproduce**
Steps to reproduce the issue:
1. Select all text in a paragraph block
2. Press DELETE key -> The text is removed
3. Press BACKSPACE key -> the paragraph block is removed
4. The removed texts are added to the end of the previous paragraph

If you remove the text with BACKSPACE, it works properly.

**Screenshots**

![f68d452f6bae6e2e386be00dd362520a](https://user-images.githubusercontent.com/13434151/44180735-068e5880-a139-11e8-942e-fcad88dc47f8.gif)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome
 - Version 68

**Additional context**
- Gutenberg 3.5.0
- It would be beneficial to add test cases to the block-deletion e2e test when fixing this.

**Comment by designsimply** [comment]
I tested and couldn't see the same problem happen. I tried with Chrome 68, Firefox 61, and Safari 11 on macOS 10.13.6 and with Chrome 68 on Windows 10. I will loop back soon with a video example to see if we can work together to figure out what might be different in my testing steps (and setup) compared to yours. Do you happen to know if you have any plugins installed which modify text during editing?

**Comment by Chintiger** [comment]
Thank you for checking. I use some css overwrite to change editor font and size in the report above.

So now I freshly installed WP (official Japanese version). I just enabled Gutenberg and WP Multibyte Patch plugins only. But this problem still reproduces in any of Chrome, Firefox 61.0.2, Canary 70.0.3524, Firefox Dev 62.0b17 and Edge.


![81a413aa7007b69d2613106ab91d7938](https://user-images.githubusercontent.com/13434151/44246036-f77dd800-a216-11e8-9017-28fe41ed533d.gif)


Again, I just selected the paragraph then tapped delete and backspace.
FYI, disabling the WP Multibyte Patch plugin doesn't affect the problem.

**Comment by designsimply** [comment]
Aha! I've got it now. The order is very specific and on macOS I had to highlight text, press `fn+delete`, press `delete`. ([11s](https://cloudup.com/c9tYsOgN5_A))

<sup>Tested with WordPress 4.9.8 and Gutenberg 3.6.2 using Firefox 61.0.2 on macOS 10.13.6.</sup>

Good find!

**Comment by Chintiger** [comment]
This issue has been fixed, not perfect though. Closing.
