### ISSUE TITLE
Gutenberg tries to access the WP Rest API using Site Address, not Wordpress Address

### ISSUE THREAD

**Issue by kettula** [WordPress/gutenberg#9044]
I am using Wordpress as a backend for an SPA developed in react. The client application lives in a different domain (ie. www.mydomain.com) from the Wordpress installation (ie. api.mydomain.com). To correctly display permalinks on the admin side, I have configured the Wordpress Address to point to the domain where WP is located, and the Site Address to the client.

I activated the Gutenberg plugin from the WP repository, and when editing a post, I get a blank edit view with a cross-domain error in the console, as it tries to access the WP Rest API using the Site Address (the client's domain). Is this expected behavior? I would assume that it should search for the API from the Wordpress Address? 

Console error output:

Failed to load https://www.mydomain.com/wp-json/wp/v2/: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://api.mydomain.com' is therefore not allowed access.

Gutenberg plugin version: 3.5.0
Wordpress version: 4.9.8

**Comment by designsimply** [comment]
Closing in favor of #1761. 

@kettula please let me know if you feel we shouldn't consolidate to #1761 and #9044 should be reopened.

@eliorivero thank you for responding with a workaround!
