### ISSUE TITLE
Seitenattribute

### ISSUE THREAD

**Issue by RogerSeifert** [WordPress/gutenberg#9045]
Bei den "Seitenattribute" gibt es ein Problem
Die Eltern werden nicht vollständig von Gutenberg übernommen.
Somit muss Gutenberg wieder deaktiviert werden, damit die Struktur wieder vorhanden ist.
![screenshot_267](https://user-images.githubusercontent.com/42434281/44197497-1446dc80-a13f-11e8-84d2-87c2744145d7.jpg)

**Comment by tofumatt** [comment]
Translation:

> There is a problem with the "page attributes"
> The parents are not completely taken over by Gutenberg.
> Thus, Gutenberg must be disabled again so that the structure is available again.

**Comment by tofumatt** [comment]
Ah, cheers! Sounds like this is fixed but will not be available until the 3.6 milestone.

@RogerSeifert: When version 3.6 is released this version will be fixed, I think we're planning to release that soon, I think either this week or early next week 😄
