### ISSUE TITLE
Transform block allows transforming into blacklisted/non-whitelisted blocks

### ISSUE THREAD

**Issue by tomasruud** [WordPress/gutenberg#9047]
We have a whitelist of default blocks that that are allowed in the editor. For instance we have whitelisted the `core/image` block, but the gallery block is not in this list. However, we are still able to insert a image block, and transform it into a gallery. Once we reload the page in the editor, the block will error out, because the gallery block is not available. 

**To Reproduce**
1. Whitelist only the image block
2. Insert image block into editor and transform it into a gallery
3. Save and reload the page in the editor
4. The block shows an error because the new block is not available

**Expected behavior**
I would expect blocks that can be transformed to not show an option of transforming into a blacklisted/non-available block.

**Comment by designsimply** [comment]
Adding related documentation links for reference: 

* https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#using-a-whitelist
* https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#using-a-blacklist

I found this in a past discussion—it was in a conversation about `parent` blocks, however, I thought it might be relevant here as well :

> Allowed blocks is not a strong contract, it's just filtering out blocks from the initial set.

<sup>Source: https://github.com/WordPress/gutenberg/pull/6753#issuecomment-391401761</sup>

In addition to whitelisting the image block, could you try blacklisting the gallery block to see if that solves the problem in this case?

**Comment by tomasruud** [comment]
I have done all the whitelisting from php, but when I try to add `core/image` to a blacklist using js, I get an error saying `Block "core/gallery" is not registered.`. I would assume this is because the block is not registered in the editor due to the php whitelist?

**Comment by youknowriad** [comment]
How are you exactly "whitelisting" the blocks?

**Comment by tomasruud** [comment]
I'm using this filter
```
add_filter('allowed_block_types', [$this, 'whitelistedBlocks'], 10, 2);
```
The whitelist looks something like this
```
public function whitelistedBlocks($defaultTypes, $post)
{
	$basic = [
		'core/paragraph',
		'core/heading',
		'core/image',
	];
	
	$custom = [
		'nice/anchor',
		'nice/article',
		'nice/article-spotlight',
		'nice/base-map',
		'nice/base-stats',
		'nice/contact',
		'nice/contact-email',
		'nice/contact-flexi',
		'nice/hero-image',
		'nice/hero-color',
		'nice/horizontal-rule',
	];
	
	switch ($post->post_type) {
		case 'news':
			return $basic;
		default:
			return $custom;
	}
}
```

**Comment by dottxado** [comment]
Just tried to unregister all the core blocks but whitelisting the list block: inserted it and trying to transform it, the editor gives an error like "The editor has encountered an unexpected error", and i have this in the console `TypeError: Cannot read property 'name' of undefined`

**Comment by youknowriad** [comment]
I believe this happens because you can't unregister all core blocks, some are mandatory: freeform, paragraph, html probably.

**Comment by youknowriad** [comment]
You can just use a javascript script to unregister the block types you want. And load a separate script per post type to unregister different blocks for different post types.

Closing the issue for now, let me know if you need more help.
