### ISSUE TITLE
After npm run build, I can't save any page

### ISSUE THREAD

**Issue by muhammedmagdi** [WordPress/gutenberg#9054]
I got a clone from the master branch and I did : 
1- npm install
2- npm run build 
Every thing works ok but after saving the page, I got:
The editor has encountered an unexpected error.
I don't have any other plugins .. The plugin that's on wordpress.org works well but the problem is when I get a clone from the master branch.

**Comment by muhammedmagdi** [comment]
The console says: Cannot read length of undefined.

**Comment by tofumatt** [comment]
What do you mean by "everything works okay"? `npm run build` will build a development version for development/testing but it doesn't build an installable plugin ZIP file. How are you interacting with Gutenberg after running `npm run build`?

**Comment by tofumatt** [comment]
For what it's worth: a fresh checkout of master, running `npm install && npm run dev` allows me to save a page no problem.

No plugins installed… if you can provide steps to reproduce we can reopen this issue, but running Gutenberg using a fresh checkout of `master` seems to work fine, so I'm closing this for now.

**Comment by tofumatt** [comment]
This is my bad; I seemingly substituted "page" for "post" everywhere in this issue. I think this is the same as the bug that is fixed by #9082.

Sorry about that.
