### ISSUE TITLE
I can't save/publish post after adding gallery/featured image

### ISSUE THREAD

**Issue by graomogo** [WordPress/gutenberg#9060]
I am not a coder/programmer, so I can't quite clearly explain why my site is behaving the way it does. But here goes.
My website is Frinconsult.co.ke, and a sample post for which I'm  getting issues creating is this one. http://frinconsult.co.ke/2018/08/15/environmental-impact-assessment-of-150-bts-sites/

This is how The problems arise:
1. I open/add new post
2. Choose the Gutenberg option to create, as opposed to DIVI Builder (visual) which I'm used to
3. I paste(previously copied from MsWORD) content onto the editor, Block by block.
***Everything works just fine and autosave also works (as when I check my drafts, the post is there)
4. At the very last stage, **when uploading photos directly onto the post, the saving issue appears**. I can't save at all, and the website URL cannot be accessed entirely from my computer's browsers for a couple of minutes. All
5. If I bypass adding the gallery and add a featured image instead, the issue reccurs.

It could probably be an issue with the adding of photo content. Please adress.
PS: Could the creators also include an option to add/remove the featured image onto the final post when viewed as a blog/post? At the moment, all featured images automatically become the first post image (which can at times be redundant.

Cheers
Collins

![image](https://user-images.githubusercontent.com/42451408/44233858-aede0480-a1ad-11e8-87cd-ccdc639d2b67.png)
Here is a screenshot of the Publishing Error

![image](https://user-images.githubusercontent.com/42451408/44233929-e2209380-a1ad-11e8-83dd-81b754179506.png)
This one is the Timed-out error after the publishing error

This issue makes the website the only link inaccessible from my ISP for an extended amount of time, before it the resumes. I even tried resetting my WIndows 10, thinking it was an issue with my OS, but it wasn't. I even re-installed all browsers.

**Comment by graomogo** [comment]
![image](https://user-images.githubusercontent.com/42451408/44233858-aede0480-a1ad-11e8-87cd-ccdc639d2b67.png)
Here is a screenshot of the Publishing Error

![image](https://user-images.githubusercontent.com/42451408/44233929-e2209380-a1ad-11e8-83dd-81b754179506.png)
This one is the Timed-out error after the publishing error

**Comment by graomogo** [comment]
This issue makes the website the only link inaccessible from my ISP for an extended amount of time, before it the resumes. I even tried resetting my WIndows 10, thinking it was an issue with my OS, but it wasn't. I even re-installed all browsers.

**Comment by designsimply** [comment]
Thank you for posting! I would like to start by making some observations and also asking a few troubleshooting questions.

I tried loading the post you mentioned http://frinconsult.co.ke/2018/08/15/environmental-impact-assessment-of-150-bts-sites/ and I found that it took a very long time to load (noting that this is outside the influence of the editor) and it appears that even though there are only 3 images they are each several megabytes and this could be the main contributing factor to check first. ([screenshot](https://user-images.githubusercontent.com/1119271/44240969-37dd4780-a17e-11e8-8ead-4445b4224d8c.png))

I checked Web Developer Tools > Network tab for the post and I see three images which are 7.4 MB, 7.4 MB,  and 6.8 MB and the load time in the footer is noteworthy:

> 27 requests | 22.8 MB transferred | Finish: 3.5 min

![screen shot 2018-08-16 at thu aug 16 5 50 16 pm](https://user-images.githubusercontent.com/1119271/44240849-8fc77e80-a17d-11e8-8d8f-853b11cbe94f.png)
<sup>Seen at http://frinconsult.co.ke/2018/08/15/environmental-impact-assessment-of-150-bts-sites/ using Chrome 68.0.3440.106 on macOS 10.13.6.</sup>

> when uploading photos directly onto the post, the saving issue appears

As a troubleshooting step, would it be possible for you to optimize the images (make them smaller) before uploading and try the test again?

May I ask what web host you are using?

**Comment by designsimply** [comment]
Regarding the "Updating failed" message, if you are able to open developer tools in your browser and look at the Console tab, it may give a more detailed error message at the time the problem happens. Is checking the console tab something you are able to try? May I ask what OS and browser versions you are using?

**Comment by designsimply** [comment]
Thank you for checking on those things! From the error messages you posted, these look to be the most relevant:

> /wp-json/wp/v2/media/790?context=edit:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
> index.js?ver=1534312507:1 Uncaught (in promise) Object
> 2/wp-json/wp/v2/posts/772/autosaves:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
> DSCN2282.jpg:1 Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

Those are the attempts to reach media via the API and the 500 error indicates the server blocked those requests for some reason. But I am not sure why! May I ask where your site is hosted and whether you have control of the firewall settings for your web server?

**Comment by designsimply** [comment]
@graomogo based on the information provided so far, it appears the problem in your case is related to the interaction between your hosting environment and your website's API. That connection must be working first before media can be uploaded via the block editor which relies on the API. 

Please check with your we hosting provider first and let them know the relevant error to see it they can help check to make sure the traffic through the API is not blocked on their side. This is the first troubleshooting step I can think of to try. Another troubleshooting step would be to check whether there is something in one of your themes are plugins causing a conflict. You can test that by temporarily deactivating all plug-ins and switching to the default theme. If the problem goes away, turn each one back on one by one until you identify which one may be causing the trouble. if you need help with any troubleshooting steps, please post all of the relevant details so far into the WordPress help forums at https://wordpress.org/support/forum/how-to-and-troubleshooting/ to ask for further help.
