### ISSUE TITLE
“Edit in Gutenberg” redirects to wrong page and issues with Revisions

### ISSUE THREAD

**Issue by metallikat36** [WordPress/gutenberg#9062]
Steps:
1. I am doing this on a staging site.
2. I made a post with Gutenberg.
3. I later try to edit the post with Classic Editor
4. It gives me a warning.
5. It says I have no revisions (even though the right-hand side says I do? Is this a bug?)
6. I click Edit in Gutenberg.
7. It redirects me to a settings page for one of my totally unrelated plugins. Huh?

This has an obvious workaround, which is to just click “Edit” rather than “Classic Editor” if your final intended destination is the Gutenberg editor.

See video:
https://www.youtube.com/watch?v=IxybI5-I1Ks

This is just FYI. I am not going to use Gutenberg, so I don't care.

**Comment by designsimply** [comment]
@metallikat36 thank you for posting! I hope to see more of you around here. 🙂 I'm adding a screenshot for reference and noting that I will loop back around to test this soon.

![screen shot 2018-08-16 at thu aug 16 6 12 46 pm](https://user-images.githubusercontent.com/1119271/44242170-7de9d980-a185-11e8-8e18-6557f51fc3e1.png)

**Comment by designsimply** [comment]
All righty, I tested this and the classic editor warning was different in my case and it says:

> You can also browse previous revisions and restore a version of the page before it was edited in Gutenberg.

![screen shot 2018-08-16 at thu aug 16 7 07 23 pm](https://user-images.githubusercontent.com/1119271/44242651-e6d25100-a187-11e8-8cc7-6312f86e6660.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14341&action=edit&classic-editor running WordPress 4.9.8 and Gutenberg 3.5.0 using Firefox 61.0.2 on macOS 10.13.6.</sup>

> It redirects me to a settings page for one of my totally unrelated plugins. Huh?

I couldn't see this problem happening either. Are you using a multisite WordPress install by chance? May I also ask what versions of WordPress and Gutenberg you are currently running?

**Comment by metallikat36** [comment]
Not using a multisite install, that I know of. I was doing this on a staging copy of my only wordpress site, made with WP Staging plugin. 

The plugin settings page it erroneously redirected to is called Responsive Accordian and Collapse. Wordpress version is 4.9.8. Guternberg version I don't know. It was whatever version came when I updated to WP 4.9.8

I just tried to see if I could reproduce the bug on my live site, thinking the issue might be something to do with the staging evironment. I had Classic Editor plugin enabled. I changed the setting to use Gutenberg by defaiulg. I then went to make a new post but found the classic Editor was still being used. I then deactivated the Classic Editor plugin, and tried making another new post. Still the classic editor came up. Not sure if this is another bug, as I seem to have no way to get the the Gutenberg editor on my live site anymore. Not that I want to.

**Comment by tofumatt** [comment]
It could be that you have a plugin that is disabling Gutenberg because it is flagged as incompatible. Could you check with the developers of "Responsive Accordian and Collapse" to see if their plugin is compatible with Gutenberg?

**Comment by metallikat36** [comment]
I just cloned my site again and tried disabling all plugins. New posts still take me to the classic editor. So it seems to me the issue is with the Classic Editor plugin itself making some kind of irreversible change.

**Comment by tofumatt** [comment]
So your site has Gutenberg and the Classic Editor plugin installed? I thought if the Classic Editor plugin was installed all posts would open in the Classic Editor by default.

You can uninstall the Classic Editor plugin if you're using the plugin version of Gutenberg, as I understand it; the Gutenberg plugin will give you the option to open selective posts in the Classic Editor.

You should only need the Classic Editor plugin once WordPress 5.0 is released and Gutenberg is the default editor.

**Comment by metallikat36** [comment]
When I first upgraded to the current version of WP, I think it gave me an option like "do you want to try gutenberg now?" I selected it. I do not have the gutenberg plugin. I did not like Gutenberg, so I installed the classic editor plugin. At some point after that, I lost access to Gutenberg. 

Maybe it just has to do with the way this WP release implemented this gutenberg "trial" feature. I bet I'll regain access to Gutenberg on 5.0.

**Comment by metallikat36** [comment]
I went to my same staging copy where I documented this bug in originally. I tested the following.
- Updating Gutenberg plugin
- Uninstalling Classic Editor plugin
- Reinstalling Classic Editor plugin

The 2 bugs persisted at each of these steps.

Recall that I also completely lost ability to make a new post in Gutenberg at all. Everything would be in Classic. Uninstalling the Classic Editor plugin did not fix this. But when I reinstalled Wordpress just now, this got fixed and I can open posts in Gutenberg now. Strangely, I had tried reinstalling Wordpress 2 months ago when I reported this bug, and at that time this did not fix it. Not sure why that is.

**Comment by designsimply** [comment]
Many updates have been made since then! 

It's a really strange issue and I'm glad you've documented it so we have some details to come back to if the problem reported again. I'll close this issue now since re-installing WordPress at this point in time has resolved the issue in your case. Thank you so much for testing!
