### ISSUE TITLE
Image that is uploaded to an existing gallery does not appear in the edit gallery view

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#9073]
**Describe the bug**

After uploading an image to an existing gallery via the button that appears under the gallery images, this image is not listed in the edit gallery view. I am using Gutenberg 3.5.0.

**To Reproduce**

1. Create a gallery block and select images from the media library for it.
2. Upload an additional image via the button under the gallery images.
3. Click the Edit Gallery button.
4. See that the uploaded image is not listed as a selected image.

**Expected behavior**

The uploaded image should be listed as part of the gallery.

**Screenshots**

![gutenberg-gallery-issue](https://user-images.githubusercontent.com/2310924/44256855-aff14f00-a20a-11e8-9684-2d2e39f3d1db.gif)

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox Nightly
 - Version 63.0a1 (2018-08-16)

**Comment by designsimply** [comment]
Tested and confirmed that if I create a gallery using the "Media Library" option to select images and then add an image using the (+) option at the bottom of the gallery block that the image added via the gallery block interface does not show up when editing the gallery. ([1m53s](https://cloudup.com/cCX5Tw5_V7X))

<sup>Tested with WordPress 4.9.8 and Gutenberg 3.6.2 using Chrome 68.0.3440.106 on macOS 10.13.6.</sup>

**Comment by qpidcock** [comment]
Same issue if you use the add image button. 

Add Block ( or add image - both have same result ) > select image from media library > add image > update > refresh the page you were using to view the finished product & you have no image.

**Comment by eliorivero** [comment]
Experiencing the same issue.
