### ISSUE TITLE
Probleme mit dem Contact-Formular

### ISSUE THREAD

**Issue by jucunda** [WordPress/gutenberg#9078]
Ich habe Probleme, das Kontaktformular zu installieren.
Wie geht das?

**Comment by tofumatt** [comment]
This is the issue tracker for Gutenberg, the new editor in WordPress. For issues with any contact form plugins, please contact the authors of the contact form plugin.

**Comment by designsimply** [comment]
Translated with https://translate.google.com/

> Problems with the contact form
> I'm having trouble installing the contact form.
> How does it work?

There is not a contact form built in. Are you using a plugin for that? If so, there may be a conflict with the plugin you are using and it would be good to test and report that. I may be able to help test!

**Comment by designsimply** [comment]
@tofumatt the tables are turned! I didn't see your reply before adding mine. 🙂
