### ISSUE TITLE
Plugin API: Namespace prefix in plugin names

### ISSUE THREAD

**Issue by tyxla** [WordPress/gutenberg#9080]
I've been working on creating custom blocks and extensions for Gutenberg, and I've noticed a substantial difference between the registration methods for blocks and plugins.

Specifically, block names support and even require having a namespace prefix (see [registerBlockType API](https://github.com/WordPress/gutenberg/blob/48c6a5ef329ad58c85a1377ac4187c9ffaecaf79/packages/blocks/src/api/registration.js#L92)), while plugins don't require, don't support and don't even allow having namespaces (see [registerPlugin API](https://github.com/WordPress/gutenberg/blob/48c6a5ef329ad58c85a1377ac4187c9ffaecaf79/packages/plugins/src/api/index.js#L43)).

This feels a little inconsistent, especially for cases where we'd like to register both custom Gutenberg blocks and plugins for related functionality. I expected to have the same name limitations for registering blocks and plugins.

I realize the no-namespace-prefix limitation for Gutenberg plugins might be in place to keep consistency with the way we register WordPress plugins (they are in a directory, so they can't have forward slashes in the names). If that's the case, it would be a good reason to not introduce namespaces for Gutenberg plugins, but I'd love to learn more about your considerations.

Thank you for your time!

**Comment by gziolo** [comment]
I guess we should relax this check and support both use cases if you want to use more granular namespaces. The only thing that matters here is when you use sidebar it has to be identified by the unique pair - namespace and sidebar name to render properly in the UI altogether with pinned items toolbar.

**Comment by aduth** [comment]
Is this really inconsistent? The namespace _is_ the plugin, so when registering a plugin it's the only relevant piece.

Examples:

```js
registerBlockType( 'jetpack/markdown', { /* ... */ } );
registerPlugin( 'jetpack', { /* ... */ } );
```

**Comment by tyxla** [comment]
Well, what if a single WordPress plugin wants to introduce multiple plugins, and has multiple `registerPlugin` instances? A large plugin with many Gutenberg extensions might need to register multiple plugins, and I think that for those cases it would be useful to be able to namespace the extensions the same way we can do it for blocks. 

FWIW, I don't think a namespace prefix should be a requirement (like it is for blocks) - rather it should be an option available to whoever wishes to use it.

Of course, having a single `registerPlugin` would make sense if we enforce a single `registerPlugin` call, but we're not doing that, right?

Thoughts?

**Comment by atimmer** [comment]
> Is this really inconsistent? The namespace is the plugin, so when registering a plugin it's the only relevant piece.

I tend to agree with @aduth here.

Do you think big plugins really need multiple calls to `registerPlugin`? I think splitting up the plugin can also be done within the plugin and doesn't require multiple `registerPlugin` calls. Which use-cases do you see for calling `registerPlugin` multiple times?

**Comment by tyxla** [comment]
> You can't register the same plugin name twice.

That makes sense, of course, but FWIW I was talking about registering multiple plugins with different names, but using the same namespace.

> Do you have a use-case in mind?

Sure. The use case I'm coming from is building extensions for Jetpack, where separate modules may (or may not, depending on certain conditions) register their own extension as a plugin. What I'd like to have in that case is to keep all those extensions as independent as possible, and to not be obliged to wrap them in a main `render()` that we'd add to a single `registerPlugin()`.

Another way of thinking about this is WordPress's own Plugin API. One can hook multiple callbacks to the same action, and each one of them would be independent, and could be managed in a separate location, without the need of a single wrapper callback.

**Comment by aduth** [comment]
>>You can't register the same plugin name twice.
>
>That makes sense, of course, but FWIW I was talking about registering multiple plugins with different names, but using the same namespace.

But as you observed in your original comment, it's not possible to provide namespaces for plugins, possibly for this exact reason.

https://github.com/WordPress/gutenberg/blob/48c6a5ef329ad58c85a1377ac4187c9ffaecaf79/packages/plugins/src/api/index.js#L43-L48

>Another way of thinking about this is WordPress's own Plugin API.

I'll take a different interpretation of the same thing. WordPress plugins are unique by slug, so while Jetpack includes many features, at the end of the day there's still only one "jetpack" slug used to identify the plugin on a site and in the plugins repository.

I also don't think we're really prohibiting developers from isolating subfeatures leveraging patterns like [dynamic import](https://developers.google.com/web/updates/2017/11/dynamic-import) ([Webpack code splitting](https://webpack.js.org/guides/code-splitting/)). It might require a bit more work, but then again Jetpack is in a small niche set of plugins which demand this sort of functionality. I still think it's wiser to optimize for the general case.

**Comment by tyxla** [comment]
If we're strictly mapping `registerPlugin` to how plugins are structured and the limitations WP plugins have with regards to the plugin name (AKA ID), I'm good with wrapping the discussion up and closing the issue.

**Comment by aduth** [comment]
It's not currently enforced, but I do expect in most cases a plugin would want to use the same slug for `registerPlugin` as they do for their own plugin.

**Comment by aduth** [comment]
I'm going to close this as "Working as Intended". We can reopen if new discussion warrants it.
