### ISSUE TITLE
Latest Posts has stopped working on v3.6.0

### ISSUE THREAD

**Issue by joebloomy** [WordPress/gutenberg#9084]
**Describe the bug**
Quite simply the Latest Posts does not show on the frontend/website. This appears to have presented itself immediately as upgraded to Gutenberg v 3.6.0

See https://bloom.im/blog/

**To Reproduce**
1. Add new/Edit post
2. Click Plus + sign to add new block
3. Add Block +
4. Scroll down to Widgets section, select Latest Posts
5. Save & view the web page, nothing appears

**Expected behavior**
I expected the latest posts to show as they do in the Wordpress Gutenberg editor.

**Screenshots**
Latest posts working on backend: <img width="676" alt="screen shot 2018-08-17 at 12 43 16" src="https://user-images.githubusercontent.com/42468735/44264658-3c0b7280-a21b-11e8-94c5-c8c316cda6ae.png">

**Desktop (please complete the following information):**
 - OS: High Sierra 10.13.6 (17G65)
 - Browser: Safari
 - Version: Version 11.1.2 (13605.3.8)

**Comment by mtias** [comment]
I cannot reproduce this. Are you using any specific settings on the block? Could you switch to the full text editor and show what the HTML comment source is?

**Comment by youknowriad** [comment]
Some people raised that Yoast might cause the dynamic blocks to not work properly. Are you using Yoast? Can you try disabling it?

**Comment by joebloomy** [comment]
> Some people raised that Yoast might cause the dynamic blocks to not work properly. Are you using Yoast? Can you try disabling it?

That fixed it. Thanks. Yoast problem, or gutenberg problem, or both?

**Comment by youknowriad** [comment]
We don't know yet :) @Xyfi @omarreiss @atimmer

**Comment by youknowriad** [comment]
It looks like when the server side registration (`do_blocks`, the `the_content` filter) is called, the content is already free from dynamic blocks, I suspect Yoast to have their own pre filter that removes those for some reason?

**Comment by youknowriad** [comment]
Correction:

I think it's probably a Gutenberg issue, there's a filter now that strip dynamic blocks from `get_the_excerpt` calls but apparently when you have yoast, this filter also messes up with `the_content`. 

Related #8984
