### ISSUE TITLE
adding a link opens only a small window 

### ISSUE THREAD

**Issue by Aldebaran10** [WordPress/gutenberg#9092]
**Describe the bug**
I tried to convert links from the classic editor into Gutenberg editor. In the classic one you get a normal window for input when you tap on the link icon. (see file 1)  In Gutenberg you only get a very small window to type in your input - you can't read what you type (see file 2)

**To Reproduce**
1. Add a text block in Gutenberg 
2. type a link in the text field e.g. https://www.tanzen-basel.ch 
3. Mark this text and tap on 'link icon'
4. the small window opens and you can't make it bigger

**Expected behavior**
I expect that the link feature in Gutenberg editor works like the one in the classic Editor.

**Screenshots**
![screenshot 1](https://user-images.githubusercontent.com/12007820/44269879-163f9700-a236-11e8-9b6b-905a0c34749d.jpeg)
![screenshot 2](https://user-images.githubusercontent.com/12007820/44269905-22c3ef80-a236-11e8-9df3-a263f3430b8a.jpeg)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser Safari 
 - Version 11.1.2
 - Gutenberg Version 3.6.1

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by tofumatt** [comment]
Thanks for reporting!

This is fixed by #9086; we'll be shipping a patch release later today. Check for version 3.6.2 later today 😄
