### ISSUE TITLE
Zedity Plugin not yet compatible with the new "Classic Editor"

### ISSUE THREAD

**Issue by mata-usa** [WordPress/gutenberg#9099]
**Describe the bug**
The Zedity Editor plugin shows a blank page during editing mode of a previous project.

**To Reproduce**
1. Go to Zedity Editor plugin while using classic editor.
2. Click on 'Zedity Icon.
3. Scroll down to 'Project area.
4. See error of a blank page.

**Expected behavior**
Expected to see previously saved Zedity boxes of images and text.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Current

**Comment by ZebulanStanphill** [comment]
Assuming you are referring to the [Classic Editor plugin](https://wordpress.org/plugins/classic-editor/), I am not sure this is the right place to report issues regarding it. But if this is the right place…

Are you running the latest version of WordPress (**4.9.8**)? What version of Gutenberg are you using? The latest is **3.6.2**. Also, what version of Zedity Editor are you using? It looks like the latest version is **7.4.0**.

Have you tried contacting the developers of Zedity Editor to let them know about this issue? It seems like this may be at least partially their issue. If something works in WordPress 4.9.8 with the Classic Editor, it should work just fine with the Classic Editor plugin installed.

Do you also have the Gutenberg plugin installed? If so, does disabling the Gutenberg plugin cause Zedity Editor to work while the Classic Editor plugin is still active?

**Comment by mata-usa** [comment]
Using all updated versions.   Disabling both the Gutenberg and Classic Editor plugins returns usability to Zedity.


I have contacted Zedity directly and they have opened a "ticket" for this item.


Thank you,


Clayton

________________________________

**Comment by tofumatt** [comment]
Thanks for letting us know you've opened a ticket with Zedity directly. I'll close this ticket for now as there's nothing on the Gutenberg side to address. Thanks a lot for filing the issue; hope you get it fixed soon 😄
