### ISSUE TITLE
Surface citation for Quote block

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#91]
The biggest benefit of blocks is that we can surface, right there contextually in the UI, semantic attributes and tags that are helpful. 

For a quote block, that would be a citation. Let's surface that:

![cite attribute](https://cloud.githubusercontent.com/assets/1204802/23074218/76640758-f538-11e6-8ba8-c00f0086437c.png)

**Comment by karmatosed** [comment]
This makes me think of a benefit of blocks of normalising styling. Block styles can get lost sometimes in a sea of text, this sometimes is worse if you had an overly enthusiastic editor stylesheet to the mix. I can see how having something like above helps a lot more people easily read and recognise content.

One thing that I've seen drive users (and also myself) to distraction is having to scroll up to style or even having to root around in sub-sub-sections to find that. This also removes that 👍

**Comment by blackcathikari** [comment]
What would the user then do if they don't want to add something like a citation (e.g. if they've put the citation in the paragraph before)? Should they be able to backspace the citation field to remove it, and if so how do they then get it back if they change their mind? Would there have to be a toolbar button for that? If not, could the behaviour be that if they don't enter anything for a citation, that field disappears when they focus a different block? Is that intuitive, or might it be too confusing? That would probably require some kind of explanation or indicator, whether that was textual and/or via styling.

I think I remember mention on another ticket of making fields such as citations separate, or at least semi-separate, and maybe that could help here.

**Comment by jasmussen** [comment]
> What would the user then do if they don't want to add something like a citation (e.g. if they've put the citation in the paragraph before)?

That's a great question which isn't served well by the static single mockup. Please see updated quote mockups here: https://github.com/WordPress/gutenberg/issues/198 — that thread includes mockups for neutral and selected states. In the neutral state, if a caption hasn't been filled out, it doesn't show up. It only actually shows up as an input field when you select the block. So what you suggest, basically :)

**Comment by iseulde** [comment]
So we'll add possible fields on select, and remove them if nothing is filled in? Also remove any caption/citation buttons? Sounds good to me.

**Comment by jasmussen** [comment]
This is done in both prototypes.
