### ISSUE TITLE
Consider adding a way to bulk transform headings from the Document Outline

### ISSUE THREAD

**Issue by Shelob9** [WordPress/gutenberg#9100]
## Problem to solve:
Here is a screenshot of the heading structure for an article. The highlighed heading, should be h2 and everything below increased by one heading level.

![screen shot 2018-08-17 at 2 09 14 pm](https://user-images.githubusercontent.com/1994311/44281947-68c58700-a227-11e8-94c2-7356df2724f7.png)

## Possible solutions
* Bulk select headings from that drop down, with option to add/subtract levels from all.
* Ability to click and push headings to the left or right to add or subtract levels

**Describe alternatives you've considered**
This might be plugin-scope, not for WordPress core.

**Comment by designsimply** [comment]
> The highlighed heading, should be h2 and everything below increased by one heading level.

To clarify, are you saying that the representation of the content is correct and that you would like a way to bulk change several headings from h2 to h3 using the Content Structure (i) dropdown?

**Comment by Shelob9** [comment]
@designsimply Yes, you understand correctly. This is not a bug with the visualization of headings.

The interface is correctly visualizing a poor heading structure I created. I'm looking for an easier way to fix this type of problem.

**Comment by karmatosed** [comment]
I think at least for phase one this feels like a plugin / idea territory over something to include. I am going to close this, however let me totally put in the idea project as I am not saying at all we couldn't consider this later.
