### ISSUE TITLE
Media Upload broken

### ISSUE THREAD

**Issue by redsoxfan2499** [WordPress/gutenberg#9102]
**Describe the bug**
Since upgrading to Gutenberg 3.6.2 MediaUpload is not working. Does not display in Editor.
Running WP 4.8.2

So the Recipe Block located in the Gutenberg Examples does not display the Image Upload button, plus the MediaUpload is broken on other blocks.

**Comment by youknowriad** [comment]
This is probably the same thing as https://github.com/WordPress/gutenberg/issues/8838 

which is to stay, it's a problem in plugin or theme adding a `wp.hooks` global messing up with the WordPress (Gutenberg) `wp.hooks` module. Please check that issue and let me know if it's similar.

**Comment by redsoxfan2499** [comment]
That was it. I turn off ACF Pro and it works. Turn ACF Pro back on and it breaks.  Thanks so much for the help

**Comment by youknowriad** [comment]
I think it's fixed in the last version of ACF Pro 🎉

**Comment by redsoxfan2499** [comment]
Again, you are correct. For some reason, I was behind in my ACF PRo updates. The Update Notice message did not show up under ACF Pro in my plugins page. So I went to my account and grab the latest version 5.7 .2 and now everything works with ACF Pro.  Hours and hours spent trying to debug this issue to find out something so simple. 

Thanks so much youknowriad!

**Comment by youknowriad** [comment]
Glad it worked for you ;)
