### ISSUE TITLE
2 Blocks disappeared with the new update! All the blocks with galleries are destroyed. Will you fix it?

### ISSUE THREAD

**Issue by moniquedecaro** [WordPress/gutenberg#9103]
Original issue was empty, issue is reported below:

> where I had galleries with 2 pics in a block ...they are now as an overlay over text and other pics .. https://www.dropbox.com/s/1a1byld3rjnedtv/Schnappschuss%20%282018-08-17%2021.38.52%29.png?dl=0
> Can I fix it? Should I delete all galleries? Or will wordpress fix the plugin?
> Thanks for your answer!
> Monique

**Comment by chrisvanpatten** [comment]
Hi @moniquedecaro -

Sorry to hear you're having trouble. Could you describe a little more the problem you're seeing? Is it in the editor interface or on the front-end of your site? Have any screenshots you can share?

Thanks!

**Comment by moniquedecaro** [comment]
Hi Chris,
its both ... where I had galleries with 2 pics in a block ...they are now as an overlay over text and other pics ..
https://www.dropbox.com/s/1a1byld3rjnedtv/Schnappschuss%20%282018-08-17%2021.38.52%29.png?dl=0
Can I fix it? Should I delete all galleries? Or will wordpress fix the plugin?
Thanks for your answer!
Monique

**Comment by tofumatt** [comment]
Are you still having issues with your galleries? I haven't seen this elsewhere.

Do you think you could copy the HTML of your block or show the settings of your block with a larger screenshot? That could help us debug this issue.

**Comment by tofumatt** [comment]
Awesome, thanks for letting us know 😊
