### ISSUE TITLE
A method for adding block variants

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#9104]
I would like to add block variants to my theme, essentially adding classes to the block container. I already add css classes to the theme and they can be styled in the editor by adding the custom class in the advanced block settings, but if there was an easy way to add additional variants then it would improve discoverability for users.

Ideally this would be a simple php request added via add_theme_support. Something along the lines of:

```
add_theme_support(
   'block-variants',
   array(
      'block-name-1' => array(
         'variant-class-1',
         'variant-class-2',
         'variant-class-3',
      ),
      'block-name-2' => array(
         'variant-class-1',
         'variant-class-2',
         'variant-class-3',
      ),
   )
);
```

I guess a javascript option would be possible also, but using add_theme_support seems like a clean and elegant 'WordPressy' way to do it. But any method would be great.

**Comment by youknowriad** [comment]
It's already possible in JavaScript see https://github.com/WordPress/gutenberg/pull/7997

Documentation is lacking though.

**Comment by youknowriad** [comment]
I'm closing this issue for now. but yeah I'll try to see if I can add docs if no one beats me to it. :)

**Comment by BinaryMoon** [comment]
I would happily add to the docs but since I don't understand how to use the command I can't document it :)
