### ISSUE TITLE
Improve the documentation of Panel, PanelBody, PanelHeader components.

### ISSUE THREAD

**Issue by gab9281** [WordPress/gutenberg#9107]
Gutenberg Version : 3.6.2
## Issue Overview

The panel component seem to be not working when using it in a custom block inspector.
It does not generate the button component needed to be able to collapse it and gives it a horrible render.

## Steps to Reproduce (for bugs)

1. Create new block
2. Add Panel to inspector of said block

## Expected Behavior

The panel should be visible with a correct render.

## Current Behavior

Bad render and does not have the possibility to toggle collapsing ( missing button)

## Possible Solution

No solutions to fix the problem but a better documentation of the panel would help

## Screenshots / Video
![error panel](https://user-images.githubusercontent.com/4269418/44288308-e1374280-a23d-11e8-8588-66b7a2d4a187.PNG)

![error panel 2](https://user-images.githubusercontent.com/4269418/44288634-05dfea00-a23f-11e8-8dfe-f9302b214b0f.PNG)

Code Used : 
```JavaScript
    el(
        Panel,
        { 
            header: "Options",
            title:"Options",
         },
         el(
             PanelBody,
             {
                 initialOpen : false
             },
             "Ceci est un test"
         )
     );
```

## Todos
- [ ] Tests
- [ ] Documentation

**Comment by youknowriad** [comment]
I believe you're trying to use the collapsible panel which is basically just the `PanelBody` component (with a title prop) 

```js
el(
             PanelBody,
             {
                 title:"Options",
                 initialOpen : false
             },
             "Ceci est un test"
         )
```

And I agree the Panel's component README needs to be improved and explain the relations between the three components (header, body, panel). Feel free to open a PR to improve the docs.

**Comment by ajitbohra** [comment]
Closed in https://github.com/WordPress/gutenberg/pull/9836
