### ISSUE TITLE
Inline image becomes not resizable after changing post settings such as text size

### ISSUE THREAD

**Issue by mahmoudbasiony** [WordPress/gutenberg#9108]
**Describe the bug**
When you add inline image in a paragraph block and start changing the text attributes such as text size the inline image becomes no longer resizable.

**To Reproduce**
1. Add a paragraph block.
2. Add an inline image.
3. Change text size.
4. The inline image becomes no longer resizable.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Google Chrome

**Comment by designsimply** [comment]
Tested and confirmed that I cannot resize an inline image after changing text settings. ([30s](https://cloudup.com/cbNBwthTrXd))

Note: I found that if I go to "Edit as HTML" then back to "Edit Visually" then I can resize the image again.

![view-after-changing-text-settings-for-a-paragraph-with-an-inline-image](https://user-images.githubusercontent.com/1119271/44291602-95d06480-a23c-11e8-8dd3-b99a0a1ebb75.png)
<sup>Tested with WordPress 4.9.8 and Gutenberg 3.6.2 and Firefox 61.0.2 on macOS 10.13.6.</sup>

**Comment by iseulde** [comment]
Fixed by #13737.
