### ISSUE TITLE
Block conversions

### ISSUE THREAD

**Issue by engmrk** [WordPress/gutenberg#9111]
Select any block and convert it into another block type such as select paragraph block and convert it into heading block...etc.

**Comment by designsimply** [comment]
Converting from a paragraph block into a heading is working for me at the moment. Can you tell me a little bit more about how you are testing? What operating system and browser version are you testing with? Can you verify that you are using the latest version of Gutenberg which is currently 3.6.2? What happens in your case when you try to convert a paragraph block into a heading block? Do you see any specific error message?

**Comment by engmrk** [comment]
No option is appearing for me to convert the block. I am using the latest version 3.6.2. The browser is Chrome Version 68.0.3440.106 (Official Build) (64-bit).

**Comment by mtias** [comment]
The option to convert an existing block is on the block switcher:

![image](https://user-images.githubusercontent.com/548849/44580939-30c8c180-a79c-11e8-8f8a-f810d8bc8e1f.png)

Please, reopen if you don't see the menu.
