### ISSUE TITLE
'multiple' property in MediaPlaceholder forces gallery [GB3.6.2]

### ISSUE THREAD

**Issue by LuigiPulcini** [WordPress/gutenberg#9113]
### SCENARIO
I am trying to create a Gutenberg block for an audio player I developed. The simplest approach would seem to be rendering a MediaPlaceholder for the users to drag, uploads or select audio files. Since the plugin also creates playlists of multiple audio files, I was experimenting with the `multiple` property.

### PROBLEM
The problem I found is that setting `multiple` to `true` forces `gallery` to be `true` as well.
The relevant code is on **line 130** of the [MediaPlaceholder index.js file](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/media-placeholder/index.js#L130) where both properties `multiple` and `gallery` of the MediaUpload component receive the value set for `multiple` of the MediaPlaceholder.

As a result, the Media uploader disregards the `type` property (which is set to `'audio'`) and shows all the mime types.

I am not sure whether this behavior is by design, but of course this prevents us from using the MediaPlaceholder to select multiple files of a specific type.

**Comment by designsimply** [comment]
A playlist block is being worked on in #8396. Consider checking the work there first (if you haven't already!) to see if anything in that code can help answer your question.

**Comment by LuigiPulcini** [comment]
Hi, @designsimply,

Thanks for your prompt reply and for pointing me in that direction.
While I can definitely see how to rework my own block according to the way the playlist is being refactored, I still think that assuming that the MediaUpload must be a Gallery only because the `multiple` property is `true` is kind of counterintuitive, particularly without checking the `type` property.

**Comment by LuigiPulcini** [comment]
Regardless of how the playlist block will be eventually implemented, the `gallery` property of the MediaUpload component invoked by the MediaPlaceholder should not be set to `true` without checking the `type` property, as this would limit the development of other audio-based blocks making use of multiple files.

Pull request: #9139

**Comment by youknowriad** [comment]
Seems like a valid enhancement.
