### ISSUE TITLE
Adjusting table width does not trigger update button

### ISSUE THREAD

**Issue by tjtaylo** [WordPress/gutenberg#9114]
**Describe the bug**
The only way to adjust table cell width is if you make another change that would trigger the update button after adjusting the width.

**To Reproduce**
1. Create a table with 2 columns and 2 rows. 
2. Click Update.
3. Adjust the width or height of one of the cells. 
4. Notice that the update button is still inactive

**Expected behavior**
Adjusting width/height of table cells should trigger the update button.

**Comment by talldan** [comment]
@tjtaylo - I think this isn't an issue since the table block was rewritten, it's no longer possible to adjust the width/height of columns/rows. I could repurpose the issue to reintroduce the feature.

**Comment by ellatrix** [comment]
Closing as it's currently not possible to resize the table.
