### ISSUE TITLE
List block: consider adding options for list types upper-alpha, lower-alpha, roman numerals, etc.

### ISSUE THREAD

**Issue by iamleese** [WordPress/gutenberg#9117]
Once I converted my "classic" page to blocks I lost the ability to choose my list type.

It would be nice that when you select a list block, you get a more robust block inspector that gives you the option of choosing upper-alpha, lower-alpha, roman numerals, etc.

The only quick solution I've found was to create a "classic" block and use my TinyMce Advanced list to customize my list type. This is not the most intuitive way to go about this, especially when having to train clients how to use it.

**Comment by paaljoachim** [comment]
Btw here is an example from the Advanced Gutenberg plugin:

![screen shot 2018-08-31 at 22 15 55](https://user-images.githubusercontent.com/5323259/44933984-83414980-ad6b-11e8-91e8-ac91b8733cde.png)

**Comment by kathrynwp** [comment]
I'm going to close this in favour of https://github.com/WordPress/gutenberg/issues/17738
