### ISSUE TITLE
Update button disabled during autosave

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#9118]
**Is your feature request related to a problem? Please describe.**
When trying to save a post, moving the cursor to the `Update` button and clicking it, sometimes the autosave triggers right before you click and disables the button, leading to a dead click and a waiting period until you can actually save (if the user actually realizes that the click didn't do anything).

**Describe the solution you'd like**
I know this is the behavior with the old editor as well, but maybe now is the chance to stop this. No need to disable the `Update` button, just debounce the save request until autosave is done.

The fact that it's autosaving is pretty irrelevant to the user in my opinion, I wouldn't even show a loader (not to mention if everything is optimal it only takes less than a second, meaning it's just a flicker).

**Comment by designsimply** [comment]
I looked for an already-filed issue for this in Trac to see if I could find a reference link to check history/past discussion and this was the closest: https://core.trac.wordpress.org/ticket/9909

**Comment by jasmussen** [comment]
Given that there's a core WordPress ticket for this, I'm going to close this one so we don't fragment the discussion. Lots of the saving in Gutenberg is powered by the same functionality that's in the classic editor, and so it's not easily fixable just here, but requires a holistic approach.
