### ISSUE TITLE
Unable to add a gallery image after deleting one 

### ISSUE THREAD

**Issue by scottybo** [WordPress/gutenberg#9121]
I can initially populate a gallery component by selecting the images from the media library. However there seems to be no way to add additional images after this initial creation.

It also seems that its not possible to add an image back in after deleting.

**Comment by designsimply** [comment]
You should be able to add images to a gallery after it is created either by clicking the "Edit Gallery" pencil icon in the toolbar above the gallery block or by using the "(+) Upload an image" at the bottom. Are you saying you don't see those options or that those options are there but they are not working for you? Can you let me know your Gutenberg, OS, and browser versions in case those are relevant?

> It also seems that its not possible to add an image back in after deleting.

Ohh, great note to to check this! I added the `Needs Testing` label so we can get someone to take a closer look.

**Comment by noisysocks** [comment]
Admittedly it's not the smoothest flow, but you can add to an existing gallery by clicking on the _Edit_ (pencil) button and clicking _Add to Gallery_.

![gallery](https://user-images.githubusercontent.com/612155/44325686-d0383c80-a49c-11e8-931f-4cdb37662b2a.gif)
