### ISSUE TITLE
music player

### ISSUE THREAD

**Issue by HassaN0152** [WordPress/gutenberg#9123]
Previous WordPress Editor The audio player has a dedicated template, but in this new editor, when we add an audio file, the browser uses the audio player to play the file, this is a very bad case.
translate by google

**Comment by acidf2018** [comment]
Hi,
The biggest problem is the player of google chrome which offers the download (sic).

The musicians are delighted :)

**Comment by kjellr** [comment]
For visual reference: 

The Classic editor relied on the [`[audio]` shortcode](https://codex.wordpress.org/Audio_Shortcode). This shortcode triggers a custom audio player that appears consistently across all browsers:

<img width="448" alt="shortcode" src="https://user-images.githubusercontent.com/1202812/44349445-0a88e600-a46b-11e8-908c-0112d87810bd.png">

Gutenberg instead relies on the standard `<audio>` tag in HTML to embed audio. Each browser displays this a little differently, and Chrome does indeed include a "Download" link in an associated menu (behind the vertical ellipsis):

_Chrome_
<img width="303" alt="screen shot 2018-08-20 at 11 25 09 am" src="https://user-images.githubusercontent.com/1202812/44349753-bf230780-a46b-11e8-9589-f7923330d317.png">

_Firefox_
<img width="273" alt="screen shot 2018-08-20 at 11 13 58 am" src="https://user-images.githubusercontent.com/1202812/44349780-ce09ba00-a46b-11e8-99a4-ce76450ac3e7.png">

_Safari_
<img width="287" alt="screen shot 2018-08-20 at 11 10 18 am" src="https://user-images.githubusercontent.com/1202812/44349792-d2ce6e00-a46b-11e8-8208-45acd9842334.png">

---

Also worth noting while we discuss: the old `[audio]` shortcode is still available for use via the shortcode block:

<img width="597" alt="screen shot 2018-08-20 at 11 27 06 am" src="https://user-images.githubusercontent.com/1202812/44349891-15904600-a46c-11e8-95c5-5a8f552a30c7.png">

**Comment by acidf2018** [comment]
An idea for a more modern audio player : 
(and with a playlist: Cover on the right and name of the tracks on the left)

![player](https://user-images.githubusercontent.com/42499666/44355135-0c26ce00-a4ac-11e8-825a-d454ec85e996.jpg)

Optional cover & link, customizable color of the "play" arrow ...

**Comment by paaljoachim** [comment]
I will associated this issue with the Playlist issue: https://github.com/WordPress/gutenberg/issues/805

**Comment by mtias** [comment]
Closing this as there are no plans to supply a custom player compared to the default browser ones (that are generally more capable and integrated).
