### ISSUE TITLE
Unable to insert blocks through insert block menu above reusable blocks

### ISSUE THREAD

**Issue by orlandomario** [WordPress/gutenberg#9125]
### Description
When using reusable blocks, it is impossible to insert a block via the "insert block" menu above the reusable block.  When clicking on the "+" button above the reusable block the default paragraph block is inserted as it should. The moment a user wants to select another type of block by clicking on the "+" icon on the left, the block menu appears but it then disappears before the user is able to select a new block. I have only seen this behavior when reusable blocks are being used.

### To Reproduce

1. Convert a regular block to a reusable block
2. Click the "+" button above the recently created reusable block
3. Click on the "+" icon to the left of the recently inserted paragraph block
4. Try to select a different block

### Expected Behavior
The insert block menu should stay open to allow users to select a different type of block.

### Desktop
 - OS: MacOS High Sierra 10.13.6
 - Browser: Firefox Nightly
 - Version: 63.0a1 (2018-08-13) (64-bit)

### Wordpress
Gutenberg version: 3.6.2 (I know this happens in 3.5, 3.4, 3.3)
Wordpress version: 4.9.8

### Video
https://youtu.be/W02C2mqJZe8

**Comment by davoraltman** [comment]
I can't reproduce this on Gutenberg 4.1.0. Does it work for you with the latest Gutenberg version?

**Comment by orlandomario** [comment]
You're correct. I cannot reproduce it either on 4.1.0.

**Comment by orlandomario** [comment]
Upon further review, it is still happening on v.4.1.0 whenever I make a custom block into a reusable block. I will close the issue and try to resolve on my end.
