### ISSUE TITLE
Block Transforms should be more discoverable/obvious

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#9127]
I was writing a block, added a line of text I wanted to convert to a heading, and couldn't work out how to convert it to a heading.

I think this is a discoverability/ usability issue. I eventually found it in the toolbar, but it was not obvious. There's no indicator showing clicking the option will offer more options. Something as simple as a small down arrow next to the block type icon would have helped considerably.

I am used to typing and then changing the styling the content after the fact. I don't want to have to leave my flow to add a header/ whatever. But finding the transforms took much longer than it should have, and I was swearing to myself since I know it used to be available but wasn't in any of the places I remembered.

**Comment by ibes** [comment]
My issue is a duplicate of this.

My issue: #9228

**Comment by chrisvanpatten** [comment]
Thanks for noting that @ibes — I'll close that issue in favor of this one since it's older!

**Comment by chrisvanpatten** [comment]
As I shared over on #9228 I wonder if a simple dropdown indicator is enough here?

![test](https://user-images.githubusercontent.com/1231306/44465589-06d09d00-a5ec-11e8-8f38-6b83230bcd55.png)

It doesn't indicate the specific purpose of the icon, but it does promote discoverability.

**Comment by BinaryMoon** [comment]
Glad someone else considers this an issue :) I suggested a down arrow in my original report and think the mockups look great. They'd make this option a lot more discoverable.

**Comment by chrisvanpatten** [comment]
@BinaryMoon Ha, totally missed you mentioning that :)

The arrow could also be used in #9075 for a bit of consistency there.

**Comment by rosswintle** [comment]
Yeah. +1 for this. It’s moved and somehow it used to be discoverable and now is not.

Am out of office until next week but will see if I have any thoughts on how to fix this.

**Comment by folletto** [comment]
I agree, it seems opaque to me the current icon-only approach, and a dropdown will make it more obvious what it's about.

**Comment by karmatosed** [comment]
Noting this originally has a dropdown in the first version of mocks.

![2018-08-23 at 22 02](https://user-images.githubusercontent.com/253067/44551847-4bf5eb80-a720-11e8-91fc-9258ce00e234.png)

That said, what other ways to expose this could we use?

**Comment by ibes** [comment]
Uh - has the "block style" feature ended up somewhere?

**Comment by ZebulanStanphill** [comment]
@ibes Yes. It is a standard API available for themes to use to add custom style variants to any block. The Button, Quote, and Separator blocks all come with multiple style variations included by default.

https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#block-style-variations

![image](https://user-images.githubusercontent.com/19592990/44562257-5fa05280-a71e-11e8-90b1-4580af8888e6.png)

**Comment by BinaryMoon** [comment]
@karmatosed is there a reason why it was removed from the final implementation? Or was it just forgotten/ missed?

**Comment by bph** [comment]
I don't have a solution, just thinking "discoverability" If I were trying to find a feature like transform I would also look in the Block Menu for Block related handling, next to "Duplicate Block" "Remove Block" etc. From some of the support tickets as well as observations of users working with Gutenberg, that's where people seems to start coming up with a solution. Removing Block and copy/pasting content in a new block. If I remember correctly, that where it was before, too. And it would follow the idea that the menu is for everything concerning the Block in relations to the rest of the document. This comes even more obvious, when trying to highlight multiple blocks to transform them to a list. Then the single block formatting bar doesn't fit anymore. It even raises expectation that when I can highlight multiple blocks they also can have applied some of the other features from the tools bar, like bolding multiple paragraphs, which is actually a missing feature, but I digress.

**Comment by ZebulanStanphill** [comment]
@BinaryMoon The arrow was not forgotten... it used to exist, but it got removed in 3.2 when the block switcher was redesigned to match the block inserter design that was introduced back in 3.0.

![image](https://user-images.githubusercontent.com/548849/41767430-dd10d71c-7609-11e8-9c24-6b0e8bb8a91f.png)

**Here is where the arrow was removed:** https://github.com/WordPress/gutenberg/pull/7362#issuecomment-399370570

When that redesign happened, hovering over the block switcher would make a shadow appear below the "block chip" as it was called, which (along with the tooltip that appeared on hover) was considered enough to make the switcher discoverable.

I wasn't really sure about how discoverable it was, but I never bothered to say anything, and I decided to wait and see what the reaction was.

When the block inserter was redesigned again in 3.6, the block switcher was also redesigned slightly to no longer have the shadow, and instead just appear lighter when hovering over it. The background color was also made much lighter for the core blocks. I guess that probably did not help with the discoverability.

Anyway, there is some work being done in #9310 to improve the block switcher by doing things like showing a switcher icon on hover:
![image](https://user-images.githubusercontent.com/548849/44581801-82268000-a79f-11e8-9df6-c0f2c33b33d3.png)

@bph Notably, the ellipsis menu (where the transforms used to be) will likely be moved to the toolbar soon. See #9074 and #9282. See also the work going on in #7635.

**Comment by rosswintle** [comment]
I note that I was working on an iPad when I was finding it difficult. This should be an interface that does not depend on hover. It should be discoverable on touch-only devices too!

**Comment by BinaryMoon** [comment]
Hi Tammie - thanks for the background. I think perhaps the issue previously was that it didn't need to be so obvious since the facility was also in the ellipsis menu but since that has gone it needs to be more prominent.

Agreed with Ross. The hover is nice, but it's still hidden and a bit mystery meat. A dropdown indicator (or something similar) will help a lot and address the touch screen issue.

**Comment by karmatosed** [comment]
> I think perhaps the issue previously was that it didn't need to be so obvious since the facility was also in the ellipsis menu but since that has gone it needs to be more prominent.

That's an interesting insight. I don't think anything yet even with it has solved the block transforms not being found. This isn't saying nothing will, it's just a drop down indication on it's own isn't really working in this case.

> I note that I was working on an iPad when I was finding it difficult. 

I very much agree we need to iterate on the experience to avoid hover being the 'key'. Although right now hover isn't getting there either.

**Comment by BinaryMoon** [comment]
>  it's just a drop down indication on it's own isn't really working in this case

I'm curious why the dropdown isn't working in this case? Do you have data/ tests that show that it's wrong? Is there a chat log I can read that explains why it's not the right thing to use? I'd like to understand the reasoning since it might help spark ideas for alternative suggestions that fit the requirements.

Agreed that the dropdown may not be the best indicator, but I think it's a step up from where we are at currently.

I think the pros of the dropdown icon are that it's a commonly understood icon representing more options available, and it aligns with the fact that clicking on it will pop up a drop down menu of new choices.

The only con I can think of is that it may not be obvious what you will get when you click the icon since you may not understand the relevance of the icon.

Who normally gets involved with the design? Is there some way we can get some alternative design voices in here so we can think through other options?

**Comment by karmatosed** [comment]
@BinaryMoon to be clear I am saying some indicator is good, it's just when we added it feedback continued to come in with issues and also in #core-editor on chat.wordpress.org that people couldn't find it. It's not me saying don't add as much as saying when we did it didn't solve the issue.

> Who normally gets involved with the design? Is there some way we can get some alternative design voices in here so we can think through other options?

Absolutely anyone is welcome to add a design. Usually someone would add to an issue like this and we take from there. I would love you to come up with some suggestions here and we can get feedback from there. @jasmussen going to loop you also into this thread as we sort of have a few threads merging on same point with #9310 work going on. All good but I want to make sure we consider everyone's designs.

Another exploration that would be good to include would be what on touch devices can also work. Excited to see what you come up with there.

**Comment by chrisvanpatten** [comment]
I think that's a really interesting iteration, but want to just highlight that it would have some challenges in narrow contexts like columns and possibly mobile too.

**Comment by jasmussen** [comment]
Hi @kevinwhoffman, nice mockups, thanks for joining us in the fray! 

Back in the day we explored something similar, to figure out the pros and cons to each approach:

![blocks](https://user-images.githubusercontent.com/1204802/44651669-4a5f4880-a9ea-11e8-8386-2895ad9041b6.png)

There are many aspects to consider, though

- The need for the editor to be responsive (see also https://github.com/WordPress/gutenberg/issues/7479#issuecomment-410988762)
- The need for the block toolbar to scale to editors with thin main columns through [editor styles](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor), as well as nested contexts (see also https://github.com/WordPress/gutenberg/issues/9075)
- The need to make transforms plug-in friendly. For example you can't only transform paragraphs, headings, quotes and text blocks. You can transform a heading to a cover image. You can select multiple images and transform to a gallery. One goal is to allow a plugin to register itself as a compatible transform, for example a ToDo list block might register itself as compatible with the List block.
- Because we dock the toolbar to the block so as to be contextual, it essentially covers preceeding text. Although there is an option to fix the toolbar to the top of the screen, this is something to be mindful of when making the toolbar wider.
- The need to accommodate very long block names including translations.
- Accessibility — we have 13px as the minimum font size.

One of the kickoff goals of this editor project was to unify multiple disparate interfaces into one. Instead of you having to learn how to use widgets, shortcodes, oembeds, custom HTML and TinyMCE in order to accomplish a rich layout, we wanted you to *only have to learn a single interface, and once you knew that, you could do anything*. This has been the driving force behind unifying everything under the block metaphor. You may have to learn how to use the block, but once you know it, you know all of WordPress.

It's all a delicate balancing act, but we're definitely open to finding solutions that thread the needle!

**Comment by mtias** [comment]
Just wanted to say thanks for all the constructive voices here and willingness to find better solutions. If there's anything that is fairly clear is that the current "block switching" interaction is not as obvious as it could be.

I think using the paragraph icon instead of the one that is easily confused as aligment, @jasmussen's update in #9310, plus the addition of the drop-down arrow are a good baseline to check on the next release and see if we need something more involved. @kevinwhoffman it'd be great to expand on your proposal and see how it might look across more blocks and nested contexts.

**Comment by kevinwhoffman** [comment]
I hear the concerns about the toolbar width and the need to handle blocks with longer names. Those are valid limitations to the proposed control. Maybe there is a breakpoint at which the block name is changed to the block icon to handle those limitations for smaller viewports.

Overall I feel the need to design a universal block-switching interface is still coming at the expense of simple text transformations. Yes, it's nice to be able to change an Image block to a Gallery block or an Audio block to a File block (however rare that may be), but it's _essential_ that a common action like changing a paragraph to a heading is obvious to the user.

Even if "block-switching" is the technical process happening behind the scenes, the user just wants to format some text.

**Comment by BinaryMoon** [comment]
I really like the mockup @kevinwhoffman has offered. I think it makes things a lot clearer. The design is one that users will recognise from the current editor, and from tools like Google docs and Word.

I understand the concerns regarding design consistency that @jasmussen raises (I'm a big fan of consistency in design) but I think usability should come first and currently the layout doesn't offer a clear suggestion of what that button does. In fact currently it's not clear it's even clickable.

I've been trying to find alternative examples of interfaces that change something from one thing to another - but can't find any equivalents that use icons exclusively.

**Comment by kevinwhoffman** [comment]
I reviewed the most common feedback regarding the increased toolbar width. The following is my attempt to improve the discoverability of the control while still allowing it to fit in smaller viewports and narrow containers.

![gutenberg-change-block-type-control-mobile](https://user-images.githubusercontent.com/1938671/44764759-5567c500-ab1f-11e8-8ec1-b04b89d59157.jpg)

The icon-only mode with the arrow is very similar to what @jasmussen is working on in https://github.com/WordPress/gutenberg/pull/9310#issuecomment-416186517.

**Comment by jasmussen** [comment]
Cool, sounds like we're on the same page with regards to the challenges, then. Would you agree the next iterative step is to ship #9310, and then explore element queries in #9075?

**Comment by mtias** [comment]
Collapsing alignments and other block level tools (not formatting) would make this much easier as well.

**Comment by ZebulanStanphill** [comment]
If you can get past the technical challenges and make it responsive, then I am all for making the switcher show the block name for wide blocks.

**Comment by kevinwhoffman** [comment]
> Cool, sounds like we're on the same page with regards to the challenges, then. Would you agree the next iterative step is to ship #9310, and then explore element queries in #9075?

Yes, I've also provided some thoughts on element queries in https://github.com/WordPress/gutenberg/issues/9075#issuecomment-417084008. I'd consider that a blocker for pursuing the text-based control any further at this point.

**Comment by 0aveRyan** [comment]
I don't think this is a silver bullet solution, but I often look for Block Transforms and Styles in the sidebar, as most advanced options are placed there.

What if the transform UI was integrated into the Sidebar? I think surfacing this feature in another location would help and perhaps better leverage existing real estate. Here are two ideas for how that could go (without adding an additional Panel):

#### Transform interfaces launches from Sidebar Icon
![idea1](https://user-images.githubusercontent.com/9565066/45038808-dc80d580-b016-11e8-8d11-41335aca7576.png)

#### Transform interfaces launches from explicit button/link
![idea2](https://user-images.githubusercontent.com/9565066/45038834-ea365b00-b016-11e8-8496-e4721888b345.png)

**Comment by mtias** [comment]
I had thought of doing something like this before, since we use the "block chip" already in the inspector, it'd be a consistent way of saying "you click the current block type to change it". I'd be ok adding this as another way of changing the format given how relatively low effort it'd be.

**Comment by ZebulanStanphill** [comment]
@0aveRyan That first mockup looks like a good idea to me. It gives extra usefulness to something that was previously just a static icon.

**Comment by karmatosed** [comment]
Whilst I understand this as an option, I have to say not super convinced the sidebar is the right place. A few reasons:

- The sidebar is for secondary actions: I would argue this is a primary one the amount of people find this useful.
- Closed sidebars: what happens when you get a closed sidebar.

I don't think adding in yet another place super solves this issue either.

**Comment by paaljoachim** [comment]
Can we get a status update on this issue?
Should it be updated/closed etc?

**Comment by BinaryMoon** [comment]
Not convinced it's perfect but it's certainly better and it keeps changing so I think we might as well shut it.

**Comment by bph** [comment]
+1 for closing. 
I like the current implementation with the previews. 

https://user-images.githubusercontent.com/39980/107387584-fade3b80-6ac2-11eb-9c1e-2e91d613f0e4.mp4
