### ISSUE TITLE
To make text justify function 

### ISSUE THREAD

**Issue by mifestofele** [WordPress/gutenberg#9128]
V tekstovom redaktore ischezla funktsiya justify 1-2 goda nazad.
In the text editor the function justify disappeared 1-2 years ago.

**Describe the solution you'd like**
Please, make button to justify text. It's very important to make blog beauty. 

Thank you.

**Comment by designsimply** [comment]
Thank you for your comment. We are tracking a request for text justification in #8433.

Also adding a note for referent that there's no justification button in the classic editor since WordPress 4.7, see https://core.trac.wordpress.org/changeset/38932
