### ISSUE TITLE
Date/time picker in Document Settings becomes invisible if viewport is very thin and short and the date is almost off-screen

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#9130]
## The issue
In situations like these, clicking the date does not appear to open the date/time picker. Note that it does actually open, but it is invisible until you scroll up a bit:
![image](https://user-images.githubusercontent.com/19592990/44300023-babcea00-a2c5-11e8-89d8-f117e6bc6bdb.png)

## Steps to reproduce
1. Resize your viewport to approximately the size shown in the screenshot.
2. Click the date to make the date/time picker appear.
3. Scroll down slowly.
4. Notice that the date/time picker becomes invisible after a certain point.

## Other notes
Tested in Gutenberg 3.6.2 on Firefox Beta.

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg `f1d163a9b` that clicking on publish date in the editor's sidebar via Settings > Document does not pull up the date picker on small screens. Tested with Firefox 62.0.3 on macOS 10.13.6 ([15s](https://cloudup.com/clCbX3T2GOJ)) and Pixel on Android 9 ([27s](https://cloudup.com/cuZF8Gd7DA4)).

**Comment by ZebulanStanphill** [comment]
I can no longer reproduce in `master`. It looks like the new date/time picker fixed the issue! :+1:
