### ISSUE TITLE
Hyperlink are not searching for CPT content

### ISSUE THREAD

**Issue by AndreaBarghigiani** [WordPress/gutenberg#9131]
**Describe the bug**
When I use the search field to find a CPT inside my WordPress installation it does not get listed, only the list of articles that match my query. I think that this was not an issue with previous version of Gutenberg but I've started to notice it from the 3.6.

**To Reproduce**
1. have a WordPress installation with CPT and post published on them
2. select a word and click the Add Link button
3. search for a published CPT

**Expected behavior**
Something similar to the TinyMCE behaviour where I had a list of all the matches and a legend that will help me understand if the match is an Article, a Page or a CPT.

**Screenshots**
This is how it looks on Gutenberg:
![screen shot 2018-08-18 at 16 54 15](https://user-images.githubusercontent.com/190159/44300496-18722600-a308-11e8-8791-20c58390d3dc.jpg)

And here how it looks the same link search in the classic TinyMCE:
![screen shot 2018-08-18 at 16 58 26](https://user-images.githubusercontent.com/190159/44300501-245de800-a308-11e8-8a59-f92ea05f6e2d.jpg)

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser Firefox
 - Version 61.0.2

**Comment by designsimply** [comment]
In general, CPT support in Gutenberg requires `show_in_rest => true`. Can you verify your CPT has this?

**Comment by AndreaBarghigiani** [comment]
Sorry for the duplicate @designsimply, I've tried the search but I didn't find any topic, probably because it is closed and I thought the problem was of Gutenberg instead is of the plugin I am usign because it did not set the `show_in_rest => true` option.

Thank you for your support!
