### ISSUE TITLE
ERROR: Docker isn't running. Please check that you've started your Docker app, and see it in your system tray.

### ISSUE THREAD

**Issue by AliBakrOfficial** [WordPress/gutenberg#9132]
hello everybody ,
I have a simple problem to prepare a development environment.
It specifically occurs during this command `./bin/install-docker.sh`
i get `ERROR: Docker isn't running. Please check that you've started your Docker app, and see it in your system tray.`

NOTE : this sh commands : `bootstrap-env.sh` , `bootstrap-env.sh` 
and `install-node-nvm.sh` work good :+1: 

how to fix it ?

**Comment by AliBakrOfficial** [comment]
I've found the fix :100: 

The fix was simple: add yourself to the docker group:

`sudo usermod -aG docker [your_user_name]`

Then, you need to reboot, because group membership is somehow cached on linux. :+1:

**Comment by nicolad** [comment]
Thank you @AliBakrOfficial 
I was a little bit surprised to know that I might need to reboot/ logout, then I found this explanation on why this is needed on ubuntu:
https://askubuntu.com/a/69259
