### ISSUE TITLE
After updating I have to convert all created Headings and Lists (possible plugin conflicts: WooCommerce, LearnDash)

### ISSUE THREAD

**Issue by nmschaller** [WordPress/gutenberg#9141]
... in all course lessons, products and blog posts.

I thought, if I used Gutenberg early on, I would have less work editing my content. Now I have more work.

<img width="1280" alt="bildschirmfoto 2018-08-19 um 08 56 13" src="https://user-images.githubusercontent.com/40534864/44306381-0dfa6f80-a38e-11e8-9638-b3396fa2617c.png">

Nicole

**Comment by designsimply** [comment]
May I ask for a bit more information? 

Did this problem happen for you only after upgrading from Gutenberg 3.5 to 3.6 or were you referring to updating from WordPress 4.9.7 to 4.9.8?

May I ask you to include the version numbers for the WooCommerce and course plugins you are currently using?

**Comment by nmschaller** [comment]
After upgrading from Gutenberg 3.0.1 (the last version without the issue of random redirects when clicking edit) to the latest version.

Also, I have the latest versions of Wordpress, WooCommerce and LearnDash running.

Hope this helps.

**Comment by designsimply** [comment]
Noting for reference that the latest versions are: WordPress 4.9.8, WooCommerce 3.4.4, LearnDash 2.5.8.2 [#](https://www.learndash.com/changelog/) and adding the `Needs Testing` label.

**Comment by maddisondesigns** [comment]
I've had similar issues on one of my test sites, after upgrading to 3.6. I've now got multiple pages that show the "This block has been modified externally" error on a variety of different blocks. e.g. Heading blocks, List blocks, Text Column Blocks, Image Blocks.

**Comment by kallehauge** [comment]
I've experienced the same as @maddisondesigns describes.

**Comment by designsimply** [comment]
@maddisondesigns @kallehauge could you confirm for me if you were using the exact same plugins @nmschaller mentioned (WooCommerce 3.4.4, LearnDash 2.5.8.2)?

**Comment by maddisondesigns** [comment]
@designsimply I've never used LearnDash, so I've never had it installed. That test site from my screenshot above does have WooCommerce activated though.

**Comment by ajitbohra** [comment]
Related https://github.com/WordPress/gutenberg/issues/10348

**Comment by nmschaller** [comment]
Right now, I am using


### WordPress Environment ###

WP Version: 4.9.8
WC Database Version: 3.4.6

### Active Plugins (22) ###

VaultPress: by Automattic – 1.9.6
Akismet Anti-Spam: by Automattic – 4.0.8
bbPress: by The bbPress Community – 2.5.14
BuddyPress: by The BuddyPress Community – 3.2.0
Functionality: by Shea Bunge – 2.0.0
Nicole Schaller: by  – 2016.07.13
Gutenberg - Support for WooCommerce: by conschneider – 0.1 – Not tested with the active version of WooCommerce
Gutenberg: by Gutenberg Team – 3.9.0
Jetpack by WordPress.com: by Automattic – 6.6.1
LearnDash Course Grid: by LearnDash – 1.5.1
LearnDash ProPanel: by LearnDash – 2.1.3
LearnDash WooCommerce Integration: by LearnDash – 1.4.0 – Not tested with the active version of WooCommerce
MiwoFTP: by Miwisoft LLC – 1.0.6
Official MailerLite Sign Up Forms: by MailerGroup – 1.2.7
Reading Time WP: by Jason Yingling – 1.2.2
SendGrid: by SendGrid – 1.11.8
LearnDash LMS: by LearnDash – 2.5.9
WooCommerce Gutenberg Products Block: by Automattic – 1.1.2
WooCommerce EU VAT Number: by WooCommerce – 2.3.11
WooCommerce Stripe Gateway: by WooCommerce – 4.1.10
WooCommerce: by Automattic – 3.4.6
WP-Piwik: by André Bräkling – 1.0.19

### Theme ###

Name: Twenty Seventeen
Version: 1.7
Author URL: https://wordpress.org/
Child Theme: ❌ – If you are modifying WooCommerce on a parent theme that you did not build personally we recommend using a child theme. See: How to create a child theme
WooCommerce Support: ✔


Hope this helps.

**Comment by ajitbohra** [comment]
Heading block is working fine with the latest release closing this. We can reopen if you are still facing the issue.
