### ISSUE TITLE
"Update Failed" message constantly on top of editor

### ISSUE THREAD

**Issue by MindfulTrader-Jeff** [WordPress/gutenberg#9146]
**Describe the bug**
"Update Failed" message constantly on top of editor

**To Reproduce**
It appears by itsself whenever editing a page or post.

**Expected behavior**
It would be nice if it only appeared when an update failed after a large number of attempts. It would also be nice if it did not constantly obstruct a few lines of the editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/37043757/44310947-879d5800-a3a4-11e8-9c35-4b197aebf669.png)

https://www.screencast.com/t/GIVPGyIbdJ

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version Version 68.0.3440.106 (Official Build) (64-bit)

**Additional context**
- Please add the version of Gutenberg you are using in the description: Cannot find this information

**Comment by designsimply** [comment]
If you have Cloudflare installed, please make sure you have the latest updates (https://github.com/WordPress/gutenberg/issues/2704#issuecomment-411621573) and if that doesn't solve the problem please comment at #2704 with details from your Cloudflare WAF log indicating which rule is causing requests to be blocked if possible.

If you are not using Cloudflare, do you have any other plugins installed? In particular, any sort of security plugins?

In Chrome, could you please open Gutenberg, then open browser the Developer Tools, visit the Network tab, then wait for the error to appear? When the "Updating failed" message appears in your browser, you'll see an entry in the Network tab with a name something like /wp/v2/posts/12345, it should be in red, showing that there was an error. Click on that entry, then Headers, then please copy everything in the "Response Headers" section to this issue.

**Comment by tofumatt** [comment]
Unfortunately it sounds like this is an issue with WordFence and Gutenberg interoperability.

We won't really be able to help as the issue isn't caused by Gutenberg; you'll need to report the issue with Wordfence, hopefully they can get it fixed.

Thanks for filing the issue though, and please do file it you encounter any other issues.
