### ISSUE TITLE
Large Image Breaking Layout

### ISSUE THREAD

**Issue by Amandaraoul** [WordPress/gutenberg#9149]
**Describe the bug**
In the theme 2017, I inserted a large image into a post. The image overran the right sidebar. This is admittedly user error, since I chose too large an image for the space allowed, but still, I was surprised at the result.
**To Reproduce**
1. Insert a large image
2. Choose 100% in the image options on the right.
3. The image looks okay in the image editor.
4. When you look at the post on the front end, the image runs off the right side of the screen.

**Expected behavior**
I expected the image to fill the space, but not more, or perhaps an error message?
**Screenshots**
![screen shot 2018-08-19 at 2 42 10 pm](https://user-images.githubusercontent.com/36089982/44313626-9c87e480-a3c0-11e8-9419-60b76bf92d63.png)

**Desktop (please complete the following information):**
 - OS: iOSX version 10.11.6
 - Browser chrome
 - Version 68.0.3440.106

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
Gutenberg Version 3.6.2

**Comment by skinnerace** [comment]
hmm

**Comment by ZebulanStanphill** [comment]
@Amandaraoul @skinnerace I think the recently-merged #7721 fixes this issue, so your problem should be fixed when the next major update to the Gutenberg plugin (3.7) is released.

**Comment by ZebulanStanphill** [comment]
I could be wrong, though. What theme are you using?

**Comment by ZebulanStanphill** [comment]
Also, what web browser are you using?

**Comment by aduth** [comment]
Repeating these testing instructions in a site with the Twentyseventeen them me, using an image originally sized at 5760x3840, set to 100% size, there does not appear to be an overflow of the image on the front-end in Chrome:

![image](https://user-images.githubusercontent.com/1779930/58730784-1373f400-83bb-11e9-80c2-56d44278cc79.png)

This should have been fixed by #8399.
