### ISSUE TITLE
Use correct plural for "children"

### ISSUE THREAD

**Issue by franz-josef-kaiser** [WordPress/gutenberg#915]
Yes, but no, there is _no_ `s` in the plural form form of [`children`](https://github.com/WordPress/gutenberg/blob/91c208e8eab031d0cd58dc7ca2b38428c85bb084/element/index.js#L77) :)

**Comment by aduth** [comment]
Alternative suggestion for "array of children" ?

**Comment by nylen** [comment]
[Chitlins](https://en.wikipedia.org/wiki/Chitterlings).

**Comment by nylen** [comment]
For a more practical suggestion, `childrenArguments` and an updated doc comment like "Array of children arguments (array of arrays) to concatenate".
