### ISSUE TITLE
Floated images duplicate alignment className

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#9160]
If you check out: https://github.com/WordPress/gutenberg/pull/7721/commits/1362fa742a191bbb0479a4ffdbe5d7801170bf27#diff-ccf983e620e4293c811f36bcb9f7aa45R23, you can see the `figure` element is also being rendered with an alignment hook `className`, but it should just be the enclosing `div` that gets the `className`. We should fix that...

**Comment by youknowriad** [comment]
I think this one is important to figure out before the release.
