### ISSUE TITLE
Go to: 

### ISSUE THREAD

**Issue by joostmollerus** [WordPress/gutenberg#9164]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by aduth** [comment]
Hi @joostmollerus . If you have an issue to report, please provide the relevant information in the template.

Closing as invalid.
