### ISSUE TITLE
Remove empty blocks when saving a Post

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#9167]
I decided to go for Bug report.

Please, remove empty blocks when saving a Post. What is the point of empty blocks in a Post ?

**Comment by TopCheff** [comment]
yo tambien estoy deacuerdo con esto. 

gracias!

**Comment by youknowriad** [comment]
How do you consider a block empty?

**Comment by StaggerLeee** [comment]
You know what is empty block. 
Inserted and nothing inside touched/added.

If it has real life uses list them here. Because I don't know them.

**Comment by youknowriad** [comment]
So If I add a "latest posts" block and I don't touch it, it's empty?

**Comment by StaggerLeee** [comment]
Listen, have no lust for verbal games. You know what I mean when I say "empty blocks". Stop playing stupid.

**Comment by youknowriad** [comment]
I'm not playing any game here. Sorry if it was misunderstood.

This was just an example, I can't think of a lot of use-cases where this description of empty block doesn't work. I think it's impossible to know for sure that we can delete a block in a generic way. Plugins can extend core blocks and make them not empty by default... For these reasons, I think it's adding such behavior is impossible.

**Comment by 0aveRyan** [comment]
Fair points raised here. Empty paragraphs are _truly_ empty without characters. Image blocks are _truly_ empty without an image set. 

However, the Latest Posts Block, Spacer block and a few others can be inserted and left alone without being configured.

**Comment by StaggerLeee** [comment]
Not in the wildest dreams a plugin can, or may, edit my own content in a block. Specially when there is no content, and no business for a plugin there. 
Empty block is block inserted by mistake and no plugin has anything to do with it, add/change content inside. If a plugin wants to change HTML tags, schema, etc....what is usual and often normal, it is still empty block (content).

I am talking about content, not block HTML tags, or CSS design.

Empty (0) X Empty (0) = Empty (0) = Plugin is out of the picture.

**Comment by paaljoachim** [comment]
Hey Stagger

I think you are likely talking about this:

![screen shot 2018-08-20 at 17 05 14](https://user-images.githubusercontent.com/5323259/44348649-4b005800-a49b-11e8-8e18-8de0cef2f38f.png)

![empty-blocks-gutenberg](https://user-images.githubusercontent.com/5323259/44348822-d548bc00-a49b-11e8-8de9-dba82b42cd26.gif)

**Comment by StaggerLeee** [comment]
Yes, about this. But not only this. Gallery can be empty and many more. Empty quote block leaves CSS styling on front-page.

All this will later cost much in expensive regex on page load.

**Comment by youknowriad** [comment]
I'm closing as invalid, let's reopen if there's any actionable item we can tackle here

**Comment by StaggerLeee** [comment]
A so, you mean template, and possibly shared, blocks. Now it is legitimate and more clear.

You had it nailed but for some reason decided to change it. When a User clicks outside of empty block you had it so it automatically is removed.

**Comment by youknowriad** [comment]
The behavior you describe was causing Writing Flow issues and was not consistent. Depending on how you'd create/touch the paragraph, it was removed or not. It was removed in #8706 because the root issue for the existence of this behavior was fixed. (accidentally creating empty paragraphs when clicking the in-between line inserter)

**Comment by StaggerLeee** [comment]
Block revolution is you idea, not mine. 

Before in TinyMce I had to use simple regex to remove empty paragraphs. Now they will be much complex and frustrating.
Don't know even if it is possible to target HTML tags this way to remove blocks from display/source code.

**Comment by ZebulanStanphill** [comment]
_Disclaimer: I am not a WordPress or Gutenberg dev._

@StaggerLeee If you are adding empty paragraphs to your content, I would expect that to be your responsibility to clean up?

Also, there is a CSS selector to style empty elements, so you could make empty `<p>` elements use `display: none`, but I think you should probably just clean up your posts and use the Spacer block, Custom HTML block, or CSS classes to add spacing where it is desirable:
https://developer.mozilla.org/en-US/docs/Web/CSS/:empty

**Comment by paaljoachim** [comment]
Well all those empty paragraphs sure do not look nice.... 
https://github.com/WordPress/gutenberg/issues/2466

**Comment by StaggerLeee** [comment]
Not related to this. Inserter is now very confusing for me. You come to the last block down, and plus icon point to insert a block as second last one.

Not logical for me. If whole philosophy of writing flow is to go down, down, down. Why to go back with block insert.

Maybe I have some script conflict on installation.

**Comment by ZebulanStanphill** [comment]
@StaggerLeee I agree that the sibling inserter should appear after the last block, and there are other issues that should be resolved. There are already existing issues that involve discussion about these kinds of issues:

- #3976
- #6224 (see the recent discussion and mockups that include the sibling inserter)
- #6569
- #6842
- #7271
- #7763
- #7884
- #8589
