### ISSUE TITLE
Enable themes to disable setting a custom font size

### ISSUE THREAD

**Issue by LittleBigThing** [WordPress/gutenberg#9168]
Themes may provide a [set of font sizes](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#block-font-sizes) for blocks that support this. By default, users can select from the given sizes (for example 'L' for 'large' defining a certain font size), but also set a custom font size. However, it would be useful if setting a **custom font size could be disabled by themes**.

## Similar idea when setting colors

This request is similar to the feature implemented for colors. A color palette can be [defined by the theme](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#block-color-palettes) and by default, custom colors can be added by the user from a color picker. This latter can be [disabled by](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#disabling-custom-colors-in-block-color-palettes):

`add_theme_support( 'disable-custom-colors' );`

A similar feature could be added to setting the font size:

`add_theme_support( 'disable-custom-font-size' );`

## Reasoning

Setting the font size can be useful for the user to emphasize a certain paragraph, for example. This can give great results when the theme supports the classes added based the selected font size. Support from the theme is crucial because it can define the sizes based on the given class and adjust the size according to screen size. In my opinion, this is the cleanest way allowing different font sizes.

When the user selects a custom font size using the slider, the font-size is set inline:

`style="font-size:36px;"`

This means that the font size is set for each screen size. A large value can look gigantic on a small screen and _vica versa_. In my opinion, there is no proper way for a theme to control this.

This solution might look like this:

<img width="275" alt="screen shot 2018-08-20 at 16 26 31" src="https://user-images.githubusercontent.com/5901923/44348099-d37df900-a499-11e8-801e-667b77e9fb19.png">

**Comment by 0aveRyan** [comment]
Particularly with the inclusion of Heading and Subheading blocks, this seems reasonable to allow theme developers to do.

**Comment by LittleBigThing** [comment]
In the meantime I found that @mtias is mentioning in #5360 that using inline styles is in the advanced category of customization and for these, the following applies:

> For basic we avoid all saved inline styles, and **advanced is something that could be disabled by a theme or plugin** if necessary.

So there may be plans already with regard to the above.

**Comment by LittleBigThing** [comment]
Great, thanks!
