### ISSUE TITLE
Gutenberg to build pages?

### ISSUE THREAD

**Issue by tkovalsky** [WordPress/gutenberg#9173]
I'm working on a project and am curious about the page builder aspect for this use case.

Currently, page builders give users free range to basically do whatever they want.

We want to accomplish a similar goal, but with restrictions so that users can configure widgets within set standards.

If Gutenberg enables users to add columns to the page, what is preventing us from allowing users to add components to those columns?

Feedback would be great.

Appreciate the help.

**Comment by mtias** [comment]
You can combine nested blocks with templates and different locking attributes to get different configurations. For example, you can specify a template with a given set of blocks and lock it down — the user would only be able to edit the block themselves, but can't add new ones not move the existing ones.
