### ISSUE TITLE
Navigating table cells with tab key doesn't work

### ISSUE THREAD

**Issue by kelliwise** [WordPress/gutenberg#9174]
**Describe the bug**
When adding a table block and trying to navigate to another cell using the tab key, the tab key takes you to the next block, not the next cell. Navigating within the table requires using the arrow keys or the mouse. Gutenberg Version 3.6.2

**To Reproduce**
1. Go to 'first cell of table'
2. Click on 'Tab'
3. See that cursor moves to next block

**Expected behavior**
Classic editor and every other word processor uses tab key to skip from one cell to the next within a table. I would expect Gutenberg to act the same way and not require the arrow keys to input data in table to move around within the table.

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome
 - Version 68.0.3440.106

**Comment by designsimply** [comment]
Thank you for reporting! Let's consolidate this one to #6923.
