### ISSUE TITLE
Placing cursor and clicking Add Link should make the whole word a link

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#9183]
In the Classic Editor, placing your cursor in the middle of a word and clicking Add Link makes the entire word a link:

![classic](https://user-images.githubusercontent.com/612155/44372431-2c47a300-a527-11e8-86bf-001800eca2e7.gif)

In Gutenberg, however, the URL is inserted as a link in the middle of the word:

![gutenberg](https://user-images.githubusercontent.com/612155/44372444-3c5f8280-a527-11e8-9a2d-92259ed4fdd9.gif)

We should match the Classic Editor behaviour as it is a nicer UX.

Props to @azaozz for noticing this in https://github.com/WordPress/gutenberg/pull/8807.

**Comment by iseulde** [comment]
I'm going to close this issue as the behaviour is inconsistent with across editors and it seems hard to make it work for all languages. In the old editor, we relied on the browser to format text, which is no longer the case.

Google Docs, CKEditor, Draft.js, Medium, Slate.js, Quill.js, all lack this feature. Some other editors do have this feature, probably relying on some native API.

Lastly, I do prefer to keep it explicit. You select some text, you format it, and only the selected text becomes formatted.

**Comment by iseulde** [comment]
Not as easy, but you can continue to use double click to select a word. :)
