### ISSUE TITLE
Paragraph Block - Encountered an error and cannot be previewed or edited

### ISSUE THREAD

**Issue by GManchester** [WordPress/gutenberg#9188]
**Describe the bug**
When I add a paragraph block, it says this block encountered an error and cannot be previewed. I'm not able to edit anything in the block, or any other block I add.

**To Reproduce**
1. Go to 'add new'
2. Click on 'new block toggle' click on the 'paragraph' block

**Expected behavior**
I expected to be able to edit and write a paragraph of text for my new blog post.

**Desktop (please complete the following information):**
 - OS: Mac OS High Sierra
 - Browser - CHROME
 - Version - 68.0.3440.106

**Comment by designsimply** [comment]
There is a similar report at #9135. Let's consolidate to that issue unless you find you are seeing something different in your browser console.

Would you be able to check your browser console to see if there are any errors showing and verify whether or not it's the same error that you see in the screenshot at #9135?

> Failed to load resource: net::ERR_INCOMPLETE_CHUNKED_ENCODING 
> tinymce-plugin-lists.min.137fa94a.js:1 
> Uncaught ReferenceError: tinymce is not defined at tinymce-plugin-lists.min.137fa94a.js:1

**Comment by designsimply** [comment]
In Chrome, you can check the browser console by going to View > Developer > Developer Tools > Console and it looks like this:

![screen shot 2018-08-21 at tue aug 21 4 08 45 pm](https://user-images.githubusercontent.com/1119271/44431811-bb22e280-a55c-11e8-9004-07baa2001483.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14478&action=edit running WordPress 4.9.8 and Gutenberg 3.6.2 using Firefox 61.0.2 on macOS 10.13.6.</sup>

In my case (in the screenshot above), the paragraph block is working for me and I am not able to see any errors. In your case, you will want to check to see if the error is the one from #9135 and comment there to note that or copy and paste the error into a reply here if the error is something different.

**Comment by GManchester** [comment]
Thank you. I have done this and commented in there. The console error messages I am getting are different.

The console error messages that appear are: 

TypeError: e.on is not a function
    at Object.e (wp-tinymce.php:2)
    at jg.c.fire (wp-tinymce.php:2)
    at Object.fire (wp-tinymce.php:2)
    at new Hx (wp-tinymce.php:2)
    at n (wp-tinymce.php:2)
    at Array.<anonymous> (wp-tinymce.php:2)
    at qt (wp-tinymce.php:2)
    at e (wp-tinymce.php:2)
    at je.b.bind (wp-tinymce.php:2)
    at Object.F [as bind] (wp-tinymce.php:2)

**Comment by designsimply** [comment]
I noticed #9775 has now been opened and looks similar, and I see that the developers asked for more information there—this time from the Network panel. If that is something you're able to check in on, please add a comment to #9775. Looks like this one is a bit tricky to sort out!

Thank you for testing Gutenberg at this stage and for looking into the errors in order to help make bug reports better.
