### ISSUE TITLE
Manually removing paragraph's font size results in font size 0 (zero)

### ISSUE THREAD

**Issue by amielucha** [WordPress/gutenberg#9191]
**Describe the bug**
When editing a Paragraph block manually setting a font size and then removing the value causes the font to be set to 0 (zero.)

**To Reproduce**
1. Edit Paragraph's Text Settings and set Custom Size.
2. Manually remove the value from the input field (backspace.)
3. The paragraph has inlined `style="font-size:0"`

**Expected behavior**
The behavior should match the Reset button. If the value is specifically set to 0 it should be 0, but if the input is empty it should take the default value.

**Comment by designsimply** [comment]
Great find! Thank you for reporting this.

I tested and confirmed using the steps provided and am noting that this also causes the paragraph to disappear from view in the preview as well as the published post on the front end after the post is published and that I am also seeing the following errors in the console as soon as I focus the "Custom Size" textbox field. ([2m13s](https://cloudup.com/c-ZreWVPxdZ))

> Error: Permission denied to access property "nodeType"
> wp-tinymce.php:2:285363

> TypeError: Argument 1 of Node.contains does not implement interface Node.
> wp-tinymce.php:2:51784

<sup>Note: the 'permission denied" error only appears after I have reopened a previously saved post.</sup>

![screen shot 2018-08-21 at tue aug 21 4 14 48 pm](https://user-images.githubusercontent.com/1119271/44432517-90865900-a55f-11e8-9945-24541c7c2ab8.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14478&action=edit running WordPress 4.9.8 and Gutenberg 3.6.2 using Firefox 61.0.2 on macOS 10.13.6.</sup>

Additional testing note: do we need to check other block settings to look for additional uses of the Custom Size field? If yes, please re-add the `Needs Testing` tag and we'll loop back around and do some extra checks!
