### ISSUE TITLE
Icons appear warped and/or clipped. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9194]
**Describe the bug**

Some of our icons appear to be a little over-optimized. Their edges are simplified too much, resulting in imbalanced shapes and clipped edges.

I found and cleaned this up in an instance of the Facebook icon (#9178), but I'm realizing now this effects other icons too (see examples below). 

## Screenshots

**Quote Icon** 

_(Ours on left, original Material design icon on the right)_
<img width="947" alt="screen shot 2018-08-21 at 8 25 41 am" src="https://user-images.githubusercontent.com/1202812/44401539-f6052600-a51c-11e8-80a5-e78afe36ead7.png">

_(Ours in pink, overlaid on the original)_
<img width="382" alt="screen shot 2018-08-21 at 8 26 25 am" src="https://user-images.githubusercontent.com/1202812/44401565-12a15e00-a51d-11e8-853b-9a7ae5c85a49.png">

**Gallery Icon** 

_(Ours on left, original Material design icon on the right)_
<img width="982" alt="screen shot 2018-08-21 at 8 29 33 am" src="https://user-images.githubusercontent.com/1202812/44401588-24830100-a51d-11e8-9e67-c67da23cf75c.png">

_(Ours in pink, overlaid on the original)_
<img width="383" alt="screen shot 2018-08-21 at 8 30 04 am" src="https://user-images.githubusercontent.com/1202812/44401590-277df180-a51d-11e8-8757-beca1819ee29.png">

I can see this occurring on the File, Table, Button, Archives, Latest Comments, SoundCloud, MixCloud, ReverbNation, and Spreaker block icons as well.

**Comment by mtias** [comment]
These might just need a clean SVG update, I think one of the minifcation tools simplified the shapes and some sneaked in.

**Comment by ajitbohra** [comment]
@kjellr this seems to be fixed in https://github.com/WordPress/gutenberg/pull/13659 except for `quote` icon.

**Comment by kjellr** [comment]
Ah, thanks for the ping. I'd forgotten about this issue. 🙂

I'll open a PR with a fix for that quote icon soon.
