### ISSUE TITLE
Invalid block via bad HTML remains on page load after 'keep as HTML' selected

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#9198]
**Describe the bug**
As described in https://github.com/WordPress/gutenberg/pull/8304#issuecomment-414406458 if you trigger an invalid block by adding invalid HTML to a block and then pick 'Keep as HTML', the block is re-invalidated when the page is reloaded.

**To Reproduce**
1. Add a quote block
2. Edit block HTML and set the HTML to `<blockquote class="wp-block-quote">fsdfsdfsd<p>fdsfsdfsdd</pfd fd fd></blockquote>`
3. Pick 'Keep as HTML' from the invalid block options
4. Save the post
5. Reload the page and notice that the block is again invalid

**Expected behavior**
It should be possible to resolve the invalid block in some way that is saved. This may include presenting the user with a different message and different options or ignoring validation problems on certain blocks (for example, allow invalid HTML in an HTML block)

**Comment by aduth** [comment]
>presenting the user with a different message and different options or ignoring validation problems on certain blocks

Ultimately, I think we may want a combination of both things.

**Comment by johngodley** [comment]
I've started work on this in #9625. It adds a different message and does allow invalid HTML to be ignored in an HTML block, solving the problem mentioned here. It's quite a big change though so I may have gone way off-base.

On page reload the block's HTML is then 'fixed', but I think that's another issue.

**Comment by PurpleHippoDesign** [comment]
I'm seeing  **"This block contains unexpected or invalid content"** error message on my HTML blocks when I reload the saved page but the HMTL markup is present on the frontend.
![screen shot 2019-01-31 at 12 18 04](https://user-images.githubusercontent.com/7089177/52053813-57acd000-2552-11e9-9137-d3c5ccb132c0.png)

**Comment by glendaviesnz** [comment]
In WP 6.2 the 'Convert to HTML' option works as expected and the HTML block is shown on reload, so closing this for now.
<img width="619" alt="Screenshot 2023-04-14 at 1 09 43 PM" src="https://user-images.githubusercontent.com/3629020/231915658-55bfdaef-6e63-4c23-b7ad-63e9a281773b.png">
