### ISSUE TITLE
allowed_block_types filter for a Custom post type doesn't add the inserter if 'core/paragraph' is not included in the list

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#9199]
**Describe the bug**
Limiting the allowed block types (as described [here](https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#hiding-blocks-from-the-inserter)) needs 'core/paragraph' to be included in the list, otherwise the inserter does not appear. I noticed this behaviour only with Custom Post Types. It seems to work correctly with the default Post.

**To Reproduce**
1. Register a Custom post type.
1. Include the allowed_block_types filter:
```
function my_plugin_allowed_block_types( $allowed_block_types, $post ) {
    if ( $post->post_type !== 'my_custom_post_type' ) {
        return $allowed_block_types;
    }
    return array( 'core/image', 'core/gallery' );
}
add_filter( 'allowed_block_types', 'my_plugin_allowed_block_types', 10, 2 );
```
2. Create a new Custom post
3. No inserter bar appears, the only way to add blocks is using the top left button.

**Expected behavior**
The inserter bar should appear.

**Screenshots**
<img src="https://i.imgur.com/vbKFdFD.png">

**Additional context**
- WordPress 4.9.8
- Gutenberg 3.6.2

**Comment by designsimply** [comment]
There is an open task to add a default appender that is not paragraph based at #8589, and I would like to consolidate there because I think it will resolve this issue as well. Please let me know if that's not the case!

**Comment by alvaro0555** [comment]
Thanks for the answer. Im still getting to fully understand how the plugin works.
But if I understood correctly the link you provide is related to nested blocks. This issue however is about allowed type of blocks in the **editor** (root level?), although the issue might also happen inside nested blocks.

The thing is, it works correctly in default Posts. Even if there is no 'core/paragraph', the inserter appears and only the allowed blocks show in the menu. But in Custom Post types the behaviour is as described (the inserter doesn't appear).

Hope it makes sense, please let me know otherwise.

**Comment by designsimply** [comment]
I asked for clarification in a comment on the issue to see whether that solution would also cover CPTs in addition to nested/inner blocks.

**Comment by alvaro0555** [comment]
Great, Thanks @designsimply
