### ISSUE TITLE
UI/UX issue with shortcodes between Visual and Code Editors, and AMP video codes inserted as wp-paragraph

### ISSUE THREAD

**Issue by nicopujol** [WordPress/gutenberg#9200]
We’ve had issues with the current/legacy visual WordPress editor removing metadata and AMP video codes upon saving or updating a post in visual editing mode. Optimistically, this issue does not seem to be occurring with Gutenberg.

One UI/UX problem we are seeing, is that we are inserting videos into our posts, and we need to insert the code twice, once for standard HTML, as a shortcode, and right underneath that, as a separate AMP video code snippet for AMP pages. We tested it using the built-in Gutenberg shortcode block and it almost worked. Upon saving the shortcode in visual mode, we could see it, but the Code Editor view just showed an empty wp-shortcode bracket. It was saved, but not rendered. We logged out and came back in, and could see the shortcode on both editors. 

Another issue is the AMP code, which we insert via the Code Editor as a wp-paragraph. We can see the contents in the Code Editor, but when switching to the Visual Editor, it shows an empty paragraph with no content in it, which is misleading. Can we show something in the Visual Editor for post editors to know that this paragraph contains content?

Attaching 2 screenshots: https://drive.google.com/drive/folders/1oHVJquUgVL9B4nEGMI4tJZy7eYtFnpEh?usp=sharing

Thanks!

**Comment by designsimply** [comment]
The drive.google.com link you provided cannot be opened because of lack of permissions. Are you able to upload the screenshots directly to GitHub? You should be able to drag and drop an image into a reply.

> we need to insert the code twice, once for standard HTML, as a shortcode, and right underneath that, as a separate AMP video code snippet for AMP pages

Are you able to include the example code for both the shortcode and the AMP video code snippet as code example in GitHub by surrounding each example with three backticks before and after to indicate it's a code snippet?

**Comment by nicopujol** [comment]
Hi, here are the codes and images reloaded direct in Github: 
```<!-- wp:shortcode -->
[adthrive-in-post-video-player video-id="gNjDAAqq" upload-date="2017-04-12T18:50:48.000Z" name="Receta casera de crepas dulces" description="Receta fácil para preparar la masa de crepas dulces. Esta receta básica de crepes o crepas francesas se prepara con harina, huevos, azúcar, leche, vainilla, y mantequilla."]
<!-- /wp:shortcode -->```
For AMP
```<!-- wp:paragraph -->
<p><amp-jwplayer data-media-id="uSD2ot6u" data-player-id="il2owpY2" layout="responsive" width="16" height="9">
</amp-jwplayer></p>
<!-- /wp:paragraph -->```

![gutenberg-code](https://user-images.githubusercontent.com/1319146/44478176-b52b1100-a5f1-11e8-8fc7-f1c72f88c093.jpg)
![gutenberg-visual](https://user-images.githubusercontent.com/1319146/44478177-b52b1100-a5f1-11e8-979c-baf407b84634.jpg)

**Comment by nicopujol** [comment]
I also extended the viewing permissions on the Google Drive folder to public for anyone with the link.

**Comment by designsimply** [comment]
Please try using the Custom HTML block to add the shortcode and the AMP video code snippet. This is the purpose of that block. If that doesn't help, please reply back here and try to include more detail about the shortcode—is it available in a plugin that can be downloaded and tested? We can re-open the issue at that point or continue the discussion as needed.

**Comment by nicopujol** [comment]
Thanks @designsimply . Using the custom HTML block solved the problem
