### ISSUE TITLE
Invalid argument supplied for foreach() in load.php on line 37

### ISSUE THREAD

**Issue by ssecweb** [WordPress/gutenberg#9213]
**Describe the bug**

Gutenberg 3.6.2
WordPress Multisite 4.9.8

Network activating this plugin and viewing any URL, both Dashboard and user facing Pages, generate this error that shows up in the browser.

**To Reproduce**

1. Network Activate the plugin
2. go to any URL controlled by WordPress Multisite, either a Dashboard URL or a user facing URL
3. the error 'Invalid argument supplied for foreach() in load.php on line 37' will show up in the page near the top

**Expected behavior**

Would expect this error message to not show up.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - Browser: Firefox 
 - Version: 61.0.2

**Comment by ssecweb** [comment]
I added the following above line 37 in load.php

```
$tmp =  glob( dirname(__FILE__) . '/../block-library/*/index.php' );
echo '<pre>';
var_dump($tmp);
echo '</pre>';
```


where `glob( dirname(__FILE__) . '/../block-library/*/index.php' )` is the invalid argument being supplied to the foreach loop.

**OUTPUT:**

bool(false)

**Comment by pavelkrato** [comment]
I had the same bug. During that I was not able to log in the into administration due to disabled cookies and Loader information header already sent by (output started at /mnt/data/accounts/w/ .....

**Comment by danielbachhuber** [comment]
@ssecweb @pavelkrato It could be that your web servers don't support `glob()` traversing `/../` for some reason. Can you share more details on your server and PHP configuration?

**Comment by danielbachhuber** [comment]
Also, could you try executing this code and let me know what results you see?

```
glob( dirname( dirname(__FILE__) ) . '/block-library/*/index.php' );
```

**Comment by pavelkrato** [comment]
> @ssecweb @pavelkrato It could be that your web servers don't support `glob()` traversing `/../` for some reason. Can you share more details on your server and PHP configuration?

This problem starts after upgrade to Gutenberg 3.6.2, before that everything was OK.

Here is my PHP configuration:
http://www.letemgastrosvetem.cz/phpinfo.php

**Comment by pavelkrato** [comment]
> Also, could you try executing this code and let me know what results you see?
> 
> ```
> glob( dirname( dirname(__FILE__) ) . '/block-library/*/index.php' );
> ```

How should I execute this code? Part of some php file?
