### ISSUE TITLE
Insert doesn't work

### ISSUE THREAD

**Issue by Moadede** [WordPress/gutenberg#9214]

**Comment by designsimply** [comment]
Inserting blocks is working in my tests using WordPress 4.9.8 and Gutenberg 3.6.2. May I ask for more information? What are your exact steps to trigger the problem and what error do you see either on screen or in your browser console at the time the problem occurs?

**Comment by Moadede** [comment]
My issue is when I try to insert an URL I have got a message (in French :Désolé, il est impossible d’embarquer ce contenu.), Sorry, it's impossible to emble this content (or something like that).... In my old version it used to work. Thank

**Comment by designsimply** [comment]
Thank you for the additional information. I tested and I was able to insert a link normally into a paragraph block using WordPress 4.9.8 and Gutenberg 3.6.2. 

Are you using the classic block or a paragraph block or some other type of block?

Does inserting a link work for you if you use https://www.google.com/ as the URL? 

Is there any chance you are able to include a screenshot showing the error message?

**Comment by Moadede** [comment]
In my classic version, I had a preview of the page when I inserted a link. 
Here is what I got now : 
![capture d ecran 2018-08-22 a 08 08 13](https://user-images.githubusercontent.com/42588834/44462785-b81f0500-a5e3-11e8-9562-24ec00edffa9.png)
![capture d ecran 2018-08-22 a 08 08 34](https://user-images.githubusercontent.com/42588834/44462786-b81f0500-a5e3-11e8-99b0-fef564683afd.png)
![capture d ecran 2018-08-22 a 08 09 28](https://user-images.githubusercontent.com/42588834/44462787-b81f0500-a5e3-11e8-9570-6f638c49548a.png)
![capture d ecran 2018-08-22 a 08 11 16](https://user-images.githubusercontent.com/42588834/44462788-b8b79b80-a5e3-11e8-87dc-c0749e344181.png)
![capture d ecran 2018-08-22 a 08 11 32](https://user-images.githubusercontent.com/42588834/44462789-b8b79b80-a5e3-11e8-84e2-3d2fad1ac259.png)

**Comment by designsimply** [comment]
My apologies for the slow reply. I see now that you are trying to add a link by itself into a block and it looks like the logic is trying to interpret that as an embed. To add a link, I recommend using a paragraph block and some text then highlighting the text and using the link button in the block toolbar to add a link.
