### ISSUE TITLE
Selecting all text in a paragraph and pasting from elsewhere doesn't replace the text

### ISSUE THREAD

**Issue by noisysocks** [WordPress/gutenberg#9218]
**Describe the bug**
Selecting all of the text in a paragraph block and then pasting content from Google Docs results in the pasted content being appended rather than the pasted content replacing the paragraph block.

**To Reproduce**
1. Copy text into your clipboard from a Google Docs document
2. Add a new post
3. Type in some text to create a paragraph block
4. Press <kbd>Cmd</kbd>+<kbd>A</kbd> to select all of the text in the block
5. Press <kbd>Cmd</kbd>+<kbd>V</kbd> to paste the copied content
6. The pasted content appears _after_ the paragraph block

**Expected behavior**
The pasted content should _replace_ the paragraph block.

**Screenshots**
![google-docs](https://user-images.githubusercontent.com/612155/44436868-d7755c80-a5fa-11e8-93e7-131d935413c2.gif)

**Desktop:**
 - OS: macOS 10.13.6
 - Browser: Latest Chrome & Safari

**Comment by designsimply** [comment]
I tested with current `master` @ `c446d069f` and found that the problem only happens when the paste from a docs.google.com document is multiline as noted by @kriskarkoski in #12443.

<sup>Tested with WordPress 4.9.8 and Gutenberg 4.5.1 `master` @ `c446d069f` using Chrome 70.0.3538.110 and Firefox 63.0.3 on macOS 10.13.6.</sup>

**Comment by con322** [comment]
Tested with copying text from Lorem Ipsum website and had the same issue where it's didn't replace the selected blocks but pasted the blocks below selected blocks.

Wordpress Version: 5.2.3 
Browser: Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by noisysocks** [comment]
Looks like this works now!
