### ISSUE TITLE
IE 11: editor disappears when focusing on it

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#922]
After #917 the editor now correctly loads in IE 11. However, either clicking on it or trying to focus it with the keyboard, causes the editor to disappear completely. In the console: error related to `find` method. Screenshots:

![screenshot 90](https://cloud.githubusercontent.com/assets/1682452/26530548/1dc264e4-43d7-11e7-8043-f0edc57cc441.png)

![screenshot 91](https://cloud.githubusercontent.com/assets/1682452/26530549/1dc47d1a-43d7-11e7-8015-1f926d4d0f40.png)

**Comment by BE-Webdesign** [comment]
I don't think `find()` is currently polyfilled, we can track down where it is being called and use the lodash equivalent instead, rather than polyfilling.  Thank you for the report!
