### ISSUE TITLE
All editors are blocked now!

### ISSUE THREAD

**Issue by Publikanguro** [WordPress/gutenberg#9221]

**Comment by Publikanguro** [comment]
The Gutenberg worked fine for some days but today the Gutenberg and all tghe other editors as Beaver Builder are blocked. When you click on Add new Post the screen ramains blank.

**Comment by designsimply** [comment]
It's hard to say what might be causing this in your case without more information. May I please ask for you to check the browser console to see if you can find any errors there at the time a blank screen happens for you?

**Comment by ZebulanStanphill** [comment]
Additionally, what browser are you using? Is your WordPress installation up-to-date? The latest version is **4.9.8**. Are you running the latest version of Gutenberg (**3.6.2**)? What theme are you using? Is Beaver Builder up-to-date? Does reloading the page fix the issue?

**Comment by Publikanguro** [comment]
Hi, I´m using the Wordpress Latest version. I deactivated all my plug ins
and still the Gutenberg does not work. Its "frozen".
Gutenberg and Beaver Builder are updated as well!

**Comment by designsimply** [comment]
@Publikanguro if you update to Gutenberg 3.8 and clear your local browser cache, doe the problem go away? 

If you are still having trouble after that, could you let us know your OS and browser versions and would it be possible for you to check the web console tab in your browser developer tools to see if any errors appear there?

**Comment by Publikanguro** [comment]
Gutenberg its okay now! it Works!!
Thank you!"

**Comment by designsimply** [comment]
@Publikanguro, awesome! May I ask how you fixed the problem?

**Comment by Publikanguro** [comment]
Sure, UI did nothing it seems it fixed itself

**Comment by designsimply** [comment]
Thank you for the reply. My guess is that something was either fixed at the server level or something like clearing local browser cache or restarting helped solve the problem.

**Comment by Publikanguro** [comment]
[image: Image]




Obtén Child Theme Divi-Commerce



https://publikanguro.com

Descarga Child Theme
Divi -Ecommerce por solo
$10 USD

En la compra de tu Child Theme Obtienes una *API KEY 100% GRATIS*

[image: Image]



Visita nuestra WEB
PUBLIKANGURO
<https://www.cloudhq-mkt24.us/mail_track/link/b555df61a7b816c016_1628716578000?uid=1886204&url=https%3A%2F%2Fpublikanguro.com%2F>
DESCARGAR PDF
<https://www.cloudhq-mkt24.us/mail_track/link/b555df61a7b816c016_1628716578000?uid=1886204&url=https%3A%2F%2Fshare1.cloudhq-mkt3.net%2Ff11b5c2ee656c2.pdf>


Contactanos
[image: Facebook]
<https://www.cloudhq-mkt24.us/mail_track/link/b555df61a7b816c016_1628716578000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>
[image: Instagram]
<https://www.cloudhq-mkt24.us/mail_track/link/b555df61a7b816c016_1628716578000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>
[image: Twitter]
<https://www.cloudhq-mkt24.us/mail_track/link/b555df61a7b816c016_1628716578000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>


My Company Name, 80 Marshall St.
Mechanicsburg, PA 17050
https://www.cloudhq.net/main_gmail_templates/dashboard_tag
Unsubscribe
<https://www.cloudhq-mkt24.us/mail_track/link/b555df61a7b816c016_1628716578000?uid=1886204&url=https%3A%2F%2Fwww.cloudhq.net%2Fgmail_campaigns%2Funsubscribe%2F26683855%2F50f087ddcd634230387862155dcf4b94>



*Powered by MailKing: Email Campaigns in Gmail by cloudHQ
<https://www.mailking.io/>*

**Comment by Publikanguro** [comment]
[image: Image]




Obtén Child Theme Divi-Commerce



https://publikanguro.com

Descarga Child Theme
Divi -Ecommerce por solo
$10 USD

En la compra de tu Child Theme Obtienes una *API KEY 100% GRATIS*

[image: Image]



Visita nuestra WEB
PUBLIKANGURO
<https://www.cloudhq-mkt22.us/mail_track/link/a32709256ace695f54_1628716585000?uid=1886204&url=https%3A%2F%2Fpublikanguro.com%2F>
DESCARGAR PDF
<https://www.cloudhq-mkt22.us/mail_track/link/a32709256ace695f54_1628716585000?uid=1886204&url=https%3A%2F%2Fshare1.cloudhq-mkt3.net%2Ff11b5c2ee656c2.pdf>


Contactanos
[image: Facebook]
<https://www.cloudhq-mkt22.us/mail_track/link/a32709256ace695f54_1628716585000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>
[image: Instagram]
<https://www.cloudhq-mkt22.us/mail_track/link/a32709256ace695f54_1628716585000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>
[image: Twitter]
<https://www.cloudhq-mkt22.us/mail_track/link/a32709256ace695f54_1628716585000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>


My Company Name, 80 Marshall St.
Mechanicsburg, PA 17050
https://www.cloudhq.net/main_gmail_templates/dashboard_tag
Unsubscribe
<https://www.cloudhq-mkt22.us/mail_track/link/a32709256ace695f54_1628716585000?uid=1886204&url=https%3A%2F%2Fwww.cloudhq.net%2Fgmail_campaigns%2Funsubscribe%2F26683856%2F67417a4978b6ba51e3023fe52ef7b42e>



*Powered by MailKing: Email Campaigns in Gmail by cloudHQ
<https://www.mailking.io/>*

**Comment by Publikanguro** [comment]
[image: Image]




Obtén Child Theme Divi-Commerce



https://publikanguro.com

Descarga Child Theme
Divi -Ecommerce por solo
$10 USD

En la compra de tu Child Theme Obtienes una *API KEY 100% GRATIS*

[image: Image]



Visita nuestra WEB
PUBLIKANGURO
<https://www.cloudhq-mkt12.us/mail_track/link/a02ea44b7355877796_1628716592000?uid=1886204&url=https%3A%2F%2Fpublikanguro.com%2F>
DESCARGAR PDF
<https://www.cloudhq-mkt12.us/mail_track/link/a02ea44b7355877796_1628716592000?uid=1886204&url=https%3A%2F%2Fshare1.cloudhq-mkt3.net%2Ff11b5c2ee656c2.pdf>


Contactanos
[image: Facebook]
<https://www.cloudhq-mkt12.us/mail_track/link/a02ea44b7355877796_1628716592000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>
[image: Instagram]
<https://www.cloudhq-mkt12.us/mail_track/link/a02ea44b7355877796_1628716592000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>
[image: Twitter]
<https://www.cloudhq-mkt12.us/mail_track/link/a02ea44b7355877796_1628716592000?uid=1886204&url=https%3A%2F%2Fwww.facebook.com%2Fpublikanguro>


My Company Name, 80 Marshall St.
Mechanicsburg, PA 17050
https://www.cloudhq.net/main_gmail_templates/dashboard_tag
Unsubscribe
<https://www.cloudhq-mkt12.us/mail_track/link/a02ea44b7355877796_1628716592000?uid=1886204&url=https%3A%2F%2Fwww.cloudhq.net%2Fgmail_campaigns%2Funsubscribe%2F26683857%2Fe5f5a0f29c9bfbd69c26527c04cf4617>



*Powered by MailKing: Email Campaigns in Gmail by cloudHQ
<https://www.mailking.io/>*
