### ISSUE TITLE
We should make it front-end editing instead of back-end.

### ISSUE THREAD

**Issue by sandeshjangam** [WordPress/gutenberg#9224]
**Why frontend editing?**
I experienced the medium.com editor and it is very clean and shows me the exact look of content while editing. Right now Gutenberg editing experience is at the backend and it is not same as a frontend.
Example. H1 while editing and after publish will show you the difference. Because font family and other factors are different in the backend as well as frontend.

**Solution**
Let's make Gutenberg as frontend editor.

It will clear the confusion of the user that it is not a page builder. It will enhance the user experience as well.

**Comment by AndreaBarghigiani** [comment]
Hi @sandeshjangam,
I am sure there have been plenty of discussions about make Gutenberg a frontend editor but for the time beign the project is solely focused on improve the backend editing experience. There are plans to work with the Customizer and get closer to what you're asking but for the moment this kind of reflection between front and back is a WordPress theme developer duty.

We as theme developer have the ability to [create a CSS that will style Gutenberg](https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#editor-styles) to make as similar as possibile to what our user will see on the frontend.

This is not a Gutenberg focus (yet).

**Comment by ZebulanStanphill** [comment]
Relevant: #9008

**Comment by tofumatt** [comment]
Gutenberg is not an exact "What you see is what you get" (WYSIWYG) editor; the intent is not to render a 1:1 copy of how a theme will render a page inside the editor. @karmatosed explained this really well at WordCamp London in 2017, but I couldn't find the video 😢
