### ISSUE TITLE
"Transform to" function should be easier to find [UX Improvement necessary] (Issue title updated)

### ISSUE THREAD

**Issue by ibes** [WordPress/gutenberg#9228]
I am just starting with Gutenberg. 

And when I am writing unique texts I happened a couple of time to just write text and then noticed "oh, that will be a headline".

How I handle that so far:
cmd + a, cmd + c, add new block above, cmd + v, remove old block. 

What would be great to be able to do: 
click on the context menu of the block, select "convert to headline" or "convert to block type" and then be able to select some. 

This will for sure not work between every block types. 

But eg. paragraph, quote, headline, list all work with text and could be able to be transformed into each other. 

Maybe that function is already present. If so, I would be grateful for knowing how. 
If not - does someone see a point in my feature request?

**Comment by DannyCooper** [comment]
There should be a button before the text-align controls that allows you to "transform" a block to another type:

![image](https://user-images.githubusercontent.com/152804/44450959-38486900-a5ea-11e8-908e-1633093170e1.png)

**Comment by ibes** [comment]
Yes - super - great. Exactly what I hoped to be there. 

Gut in a place that I have not expected and with an icon I would have never guessed without being shown by you. 

I would have expected it at the three-dots-menu on the right hand side of the block.

Or with an icon that symbolizes change
(for inspiration).

I guess the existing button displays the current type - and so you can change the type through clicking there. 

It's quite a nice place for that. 
But it works opposite to the other buttons. 
All other buttons in that bar will transform to the stage you see in the button. 
If you press "b" text gets bold, if you press "right aligned" the text will be right aligned. 
The "transform to" button let you choose a transformation.



Great - for me the ticket is solved as I now know how to do the change I want to see in my Gutenberg. 
Thank you!

**Comment by DannyCooper** [comment]
I agree the button could be improved - it looks too much like the text-alignment controls.

**Comment by ibes** [comment]
The button's icon change to represent the type of the block.
So for headlines it will be two "t"s (at least in my version - as I read some icons got a redesign)

Is there a way to ask some UX people if there could be a level up for the clarity of this feature?
I guess that is a feature that needs to be explained in the beginners tour (maybe it was, but than I skipped it or was not concentrated while doing it - and likely I am a normal user in that aspect) or it will likely not be clear. 
Also there is no way to see it by looking - what I mean with that: the icon doesn't communicate what it is (unlike the "b" or "left align" buttons) and there is no text like at "Delete block" (unless you interact with the button already - but that is already "random click mode")

**Comment by chrisvanpatten** [comment]
Any chance it could be as simple as a dropdown indicator?

![test](https://user-images.githubusercontent.com/1231306/44465589-06d09d00-a5ec-11e8-8f38-6b83230bcd55.png)

**Comment by chrisvanpatten** [comment]
Closed in favor of #9127 :)
