### ISSUE TITLE
Non admin user roles gets a broken editor

### ISSUE THREAD

**Issue by slimmilkduds** [WordPress/gutenberg#9233]
I have a bunch of custom user roles. They have been working fine but with Gutenberg I'm getting some really weird behavior. Icons are missing, the first default empty block is missing, the little + sign in the top left corner is missing etc. 

If you compare the images you see that there's some stuff missing when I create a new post. If I highlight the title block and press enter I get to the invisible block but none of the icons are visible.

I'm wondering if there's some magical capability or permission I need to set to get normal functionality for my custom user roles?

_What admin sees when creating new post:_
![screen shot 2018-08-22 at 10 38 31](https://user-images.githubusercontent.com/40266703/44452870-eb6b8f00-a5f7-11e8-94e7-968e0f94613e.png)

_What custom user role sees:_
![screen shot 2018-08-22 at 10 39 03](https://user-images.githubusercontent.com/40266703/44452859-e73f7180-a5f7-11e8-92cf-5123286e86f5.png)

Any help is appreciated!

**Comment by tofumatt** [comment]
Gutenberg shouldn't require any extra permissions to run and will work fine on a stock install with other user roles.

Could you copy the console output from your browser? In Firefox it's in `Tools > Web Developer > Web Console`. In Chrome it's under `View > Developer > JavaScript Console`. If you're using another browser please check its support docs or let us know which one 😄

It would help to see what the console output of the Gutenberg page is here.

**Comment by slimmilkduds** [comment]
Thanks for the quick reply. This is super weird, when I was gonna copy the console output everything all of the sudden worked. I'm trying to retrace what I've done since I sent the question but I can't figure out anything that would have either caused or fixed this problem hehe. Have a great day!

**Comment by tofumatt** [comment]
No worries! Happy to hear it's working! If you see it happen again feel-free to re-open/post in this issue with any extra info. For now I'll close this though, thanks! 😄
