### ISSUE TITLE
Shortcode executed in paragraph even if wrapped in backtick

### ISSUE THREAD

**Issue by AndreaBarghigiani** [WordPress/gutenberg#9236]
**Describe the bug**
I am working on a project where I immediatly installed Gutenberg (3.6.2). The project is a simple WordPress (4.9.8) theme and involves the Genesis framework and the Genesis Simple FAQ plugin. 

But the same problem is happening with the standard Twentyseventeen and the shortcode `[audio]` as showed in the following screenshot.

![error-shortcode](https://user-images.githubusercontent.com/190159/44456599-3c33b580-a601-11e8-9660-8fe511509457.jpg)

The shortcode is added to a paragraph block and is wrapped in backtick (`) to show how to use the shortcode in the body of the article. I've tested it on different website so I quite sure it is replicable.

**To Reproduce**
1. Go to any WordPress installation with any theme activated
2. insert a shortcode in a paragraph block, I am usign `[audio src="https://ia800209.us.archive.org/20/items/ElephantsDream/ED-CM-St-16bit_64kb.mp3"]` wrapped in backticks
3. Save & view the page

**Expected behavior**
I am expecting to see the shortcode not executed in a paragraph block since there is a specific block for it, expecially if I wrap it in backticks. This is a useful feature because plenty of WordPress plugin developers could use this kind of writing style to document their shortcodes.

**Screenshots**

This is the screenshot of Gutenberg where i first find this issue:
![schermata 2018-08-22 alle 12 02 05](https://user-images.githubusercontent.com/190159/44457356-4787e080-a603-11e8-9aae-a0171a6d85ea.jpg)

And this is hot it looks when viewing the article:
![schermata 2018-08-22 alle 12 02 27](https://user-images.githubusercontent.com/190159/44457378-5373a280-a603-11e8-805d-d8535b7664ae.jpg)

Note how the secon list, the paragraph where I explain which shortcode I used, is the same as the previous one but wrapped in a `<code>` tag because of the backticks.

**Desktop (please complete the following information):**
 - OS: macOS 10.13.1
 - Browser Firefox
 - Version 61.0.2

Thanks for the future support, hopes this is not duplicated ;)

**Comment by ktmn** [comment]
Has the backtick ever worked? I use `&#91;` and `&#93;`.

**Comment by AndreaBarghigiani** [comment]
@ktmn actually you're righy, in TinyMCE where the post content was a single blob of characters it was needed to use the ASCII to inject the square brakets without firing the shortcode.

I also understand that the paragraph block has to run the shortcodes maybe for backward compatibility but I think that this kind of feature has to go because now we have a shortcode block and the paragraph one shout contain only text.

**Comment by tofumatt** [comment]
Maybe there's context I'm missing (like @AndreaBarghigiani says, maybe it's for backward compatibility that we execute shortcodes in paragraphs)… maybe that's just how WordPress loads content and there's nothing we can do about it from the editor? I'd guess that's the case… do shortcodes run through other text-only blocks too, like lists?

Anyway, I think this would be a good enhancement if we can do it.

**Comment by youknowriad** [comment]
There are inline shortcodes as well and people still want to use them in Gutenberg paragraphs. I think it's unrealistic to avoid running shortcodes in paragraphs. Maybe once all shortcodes are blocks, inline blocks or using the coming Gutenberg RichText API. But I don't see this happen in the near future.

**Comment by tofumatt** [comment]
Ah, if there are inline shortcodes then yeah, I'd say this is a won't fix as long as they're around.

I empathise with your issue, @AndreaBarghigiani, but looks like we have to support the old inline shortcodes for the foreseeable future. Sorry 😞

**Comment by AndreaBarghigiani** [comment]
Thank you @tofumatt,
I understand the retrocompatibility need of the project and I have only to say that I hope that theme and plugin creators will move fast to switch from inline shortcode to a complete block experience.

Let's keep as it is for the moment and work with `&#91;` and `&#93;` as suggested from @ktmn 😄

**Comment by tofumatt** [comment]
I agree; it would be awesome to support your use-case in the future! 👍
