### ISSUE TITLE
Create a bot that assigns milestones to merged PRs

### ISSUE THREAD

**Issue by tofumatt** [WordPress/gutenberg#9239]
Right now we rely on developers to set the correct milestone for closed pull requests (and issues), but we often forget and it's not a clearly-defined process.

We should be able to set the next milestone in a file or something that all merged PRs will be assigned.

**Comment by chrisvanpatten** [comment]
There is some good brainstorming about using Probot for this here: https://lab.civicrm.org/infrastructure/gitlab/issues/3

(I'm a big Probot advocate if you can't tell 😉)

**Comment by tofumatt** [comment]
That's handy, I've been looking into it as well, so the help is much appreciated 👍
