### ISSUE TITLE
Improved Text Tab (TinyMCE) Code View (Gutenberg)

### ISSUE THREAD

**Issue by irishetcher** [WordPress/gutenberg#9244]
Something that has been neglected in the current editor/TinyMCE for years, is being ignored in Gutenberg when in fact it would be a perfect time to update the text tab/code view to become a more immersive IDE experience with syntax highlighting, respect for indentation, like what you see on CodePen. 

Pasting in and out of Word has become part of the pattern for many. Having to paste in and out of Sublime Text is similar for the purpose of keeping some shape on HTML and dealing with the pain of trying to work with code in the text tab/code view.  HTML in plain text, unformatted and un-indented, after pasting,  becomes illegible and doesn't provide a canvas large enough to deal with the amount of HTML that gets generated. The text tab/code view in it current state is not practical for anything longer than a couple of paragraphs. 

A good IDE experience would also delineate better the comment tags and you could in fact provide a way to hide/unhide comments with a toggle. 

Add to this a way to de-block the content, return it to one TinyMCE block would go a long way to alleviating a lot of the issues people are having with the block concept and facilitate users needing to copy code to an external editor without the comment tags. In fact you can cut all the block content and copy it to a classic block and then manually strip out the comment tags. You just need to write a script to do this manually.

**Comment by tofumatt** [comment]
I think this kind of thing would be cool!

An IDE-like experience inside a block would be super-cool (maybe even some kind of CodePen/JSFiddle/etc. block), but it's beyond the scope of the core editor blocks. I think this is perfect plugin territory.

Unfortunately it's not the kind of thing the core editor team can provide.

**Comment by irishetcher** [comment]
To be clear I was referring to to the code view and not specifically to something in a block. That's a shame as it makes Gutenberg a very limited prospect.

**Comment by tofumatt** [comment]
Ah, thanks for the clarification. I see that code view as an escape hatch… again, a more complicated editor these would be cool, but I actually think that would need to be a project around incorporating an existing, quality HTML editor we could use. Right now ours is just a `textarea`–we don't have the bandwidth to roll our own HTML editor. 😢

**Comment by irishetcher** [comment]
Keep it in mind. Something for the future that would make WordPress a lot more valuable. Code Mirror was introduced to WP recently, developing it a bit further and pushing it into more corners other than the HTML block might be do the trick.

**Comment by designsimply** [comment]
> provide a way to hide/unhide comments with a toggle

#9018 is related and has some good explanations/discussion.
