### ISSUE TITLE
Metabox Improvements

### ISSUE THREAD

**Issue by irishetcher** [WordPress/gutenberg#9245]
Certain workflows are not possible with the way metaboxes are implemented.  

For example I have a site of artist's prints. The very first thing, after the title, that I want to enter is an image of the print (Featured Image), then details such as dimensions and medium, which are in a custom field group metabox and, them the description. This best suits the data entry use case I have set up. On another day I decide I need to do some work on keywords, so I drag Yoast to the top of the page, below the title.  NOTE: This is possible on the current custom post type because I have disabled the main content text area and replaced it with a bespoke print description text area.

I can do all this with the current editor but not in Gutenberg because:

a. many of the standard controls for featured image etc. are fixed.
b. There seems to be a bug whereby if there aren't any metaboxes below the content area you can't drag any to that location and you can't re-arrange any from there back over to the right sidebar. 

Finally a little more definition is required to delineate where a metabox sits in the interface. They look a little bit lost and bleed into one another. Even if you used the style (very light grey tile banner and border) that is used around the classic block it would be useful.

While I get how the block concept works for the specific use case that is it targets, Gutenberg interface does not work well for the data entry use cases I have outlined above.

**Comment by tofumatt** [comment]
If there are editor plugins you are using that currently use Metaboxes, I would encourage you to request that the developers look into porting their functionality to Gutenberg blocks. As mentioned in the [Gutenberg docs on Metaboxes](https://wordpress.org/gutenberg/handbook/extensibility/meta-box/): *porting PHP meta boxes to blocks is highly encouraged*.

The goal of Gutenberg is to encourage plugin authors to migrate to blocks, so with the current amount of issues on-hand I don't think it's realistic to focus on Metabox improvements when they're discouraged in the new editor.

If there are specific things about the featured image section that could use improving though, please do file an issue surrounding it 😄

**Comment by irishetcher** [comment]
Ok I see what you mean. Gutenberg is not going to fit my use case where above all else, pardon the pun, the featured image must be placed at the top above custom the field groups I have configured with Toolset. 

I will continue to use the current editor which can handle the workflows and data entry required by the sites I build. I will tune in occasionally to see how Gutenberg is developing.
