### ISSUE TITLE
Insert Link: Link Modal doesn't move when clicking on another link within Paragraph block

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/gutenberg#9246]
When there are multiple links within a paragraph block and you click on one to edit it. If you click directly on another link, the modal will change to edit the new link, but it does not move the modal window to the new link.

**To Reproduce**
1. Create a paragraph with multiple links
2. Click on one link, then click directly on another without closing the modal
3. The modal does not move to the second link

**Expected behavior**
The modal should move to the most recent clicked link

**Desktop**
 - OS: Windows 10
 - Browser Chrome
 - Version 68.0.3440.106

**Additional context**
- Gutenberg 3.6.2
- WP 5.0-alpha-20180817.111643

**Comment by designsimply** [comment]
I'd like to consolidate this one to #7992. Let me know if you disagree!
