### ISSUE TITLE
Page builder Integrations

### ISSUE THREAD

**Issue by irishetcher** [WordPress/gutenberg#9247]
I don't see any sensible approach regarding integrations with these other than the anodyne suggestions of doing something with blocks. 

I would suggest that page builders are concerned with page structure and layout, what we need is the equivalent of sections/rows/columns, flex and, for the daring Grid, offered in the form of blocks. Provide this with a good API for the page builder devs to work with it to add their own bells & whistles and interfaces. 

This would provide a common foundation that users can chose to use or not use and would introduce a more streamlined approach to changing themes and builders if one choses do do so.

I know Gutenberg is pretending to not be a page builder but sure, go on, it's great fun! Even being a very basic one, Gutenberg could act as an intro for those new to the concept of page building in this blocky manner. 

For those who don't like page builders at all at all, look at my suggestion to de-block back to one classic block:

https://github.com/WordPress/gutenberg/issues/9244

**Comment by tofumatt** [comment]
Gutenberg is about a block-based editing experience and it would be up to page-building plugins to supply their own layout blocks for things like sections/rows/columns etc. That is totally within the scope of a Gutenberg plugin as I understand it, but it's not something we'll be shipping as part of the core editing experience. 😄
