### ISSUE TITLE
Slug not updated on the fly when left open and OK

### ISSUE THREAD

**Issue by RobinRoelofsen** [WordPress/gutenberg#9250]
**Describe the bug**
When the slug of a page or post is deleted to generate a new slug, the old slug is still shown when the OK button is pressed, only after the page/post is saved. This used to be on the fly.

**To Reproduce**
1. on a page/post, go to the title, click over it and press Edit on the slug
2. clear the slug and click on OK
3. the old slug is still showing
4. save the changes
5. the new slug is there

**Expected behavior**
When the slug had been deleted and the OK button is pressed, it should immediately generate a new slug based on the page/post name.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 68.0.3440.106

**Additional context**
Gutenberg version 3.6.2

**Comment by designsimply** [comment]
I tested with WordPress 4.9.8 and Gutenberg 3.6.2 on Firefox 61.0.2 on macOS 10.13.6 and was unable to reproduce the problem as described. ([37s](https://cloudup.com/cOhCP2pG8Cp))

In my test, I started with a published post that had a previously saved custom permalink. Could some steps be missing from my test or should I have started in a different state? If yes, let me know and we can re-open if needed.

If your test case for a post that has not yet been saved, please see #7129.

**Comment by RobinRoelofsen** [comment]
Justed tested on Firefox using Windows 10 on a published page.

Let's assume the page is called Test with slug test:

1. Change the name of the page to Test 1
2. Click on the page name, and click on Edit next to the slug
3. Empty the slug and press OK
4. The slug returns to the original slug test instead of changing immediately to test-1
5. Now save the page
6. Click on the page name, and check the slug. Now it's test-1
