### ISSUE TITLE
The "Order" field within "Page Attributes" does not allow for negative numbers

### ISSUE THREAD

**Issue by cwpnolen** [WordPress/gutenberg#9254]
**Describe the bug**
When attempting to update the "Order" field to a negative number, the "-" key is ignored. 

**To Reproduce**
1. Create a new page using Gutenberg
2. Scroll to the "Page Attributes" section
3. Attempt to update the "Order" field to "-1"
4. Notice the "-" key is ignored and the value is updated to "1"

**Expected behavior**
The negative number should be respected. 

**Desktop (please complete the following information):**
 - OS: macOS Sierra
 - Browser Chrome
 - Version 68

**Additional context**
- Using Gutenberg 3.6.2
- Where I work, the vast majority of our clients organize their pages via the Page Attributes Order field. Often times, the front page, home page and landing pages are given negative numbers to position them quickly to the top of their list of pages. We have attempted to have customers organize their pages using large positive numbers, but their preference has been to not do that.

**Comment by tofumatt** [comment]
Indeed, I tested locally and removing the check here: https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/page-attributes/order.js#L17 and entering `2`, then adding the negative to make the order `-2`, I can save it and the server is fine with that. This seems to be a bug, we should allow the old behaviour.

Odd that if I type the minus symbol first, even with that code commented out, it will reset to `0`. Maybe there's another event.

At any rate I can replicate this and we should allow negative numbers here.
