### ISSUE TITLE
NUX Tip Confusion: Tip misses nuance of pre-publish flow

### ISSUE THREAD

**Issue by 0aveRyan** [WordPress/gutenberg#9256]
**Describe the bug**
The final NUX tip points to the `Publish...` button, which isn't a one-click Publish button anymore and really triggers the pre-publish workflow on the sidebar. However, the NUX tip says click "... and you're good to go." It also misses the potential that a user may schedule the post for the future in that `Are you ready to publish?` workflow by saying "lets get this published right now." 

**To Reproduce**
1. Go to Add New Post in Gutenberg 3.6.2 & stock WP trunk In Incognito Window.
2. Click through to the final NUX tip on publishing.

**Expected behavior**
The tip should reflect the control offered the user in this confirmation step. The text should be corrected to reflect current behavior, though not necessarily needing to describe both clicks.

**Screenshots**
<img width="281" alt="screen shot 2018-08-22 at 12 15 25 pm" src="https://user-images.githubusercontent.com/9565066/44485336-17414180-a605-11e8-994d-dde77b2cbb53.png">
<img width="568" alt="screen shot 2018-08-22 at 12 15 16 pm" src="https://user-images.githubusercontent.com/9565066/44485338-17d9d800-a605-11e8-8a73-0ad0f1ff3f7e.png">

**Comment by 0aveRyan** [comment]
Also relevant to this is @mapk's comment on #8061 re: timing of prompt

https://github.com/WordPress/gutenberg/issues/8061#issuecomment-406400495

**Comment by karmatosed** [comment]
I am very OK with iterating on Tips, what would you suggest?

**Comment by jorgefilipecosta** [comment]
I guess the simples way to address this issue would be to the change the copy to something simpler like "Finished writing? That’s great, let’s get this published. Click the “Publish” button." That does not pass wrong information to users, would that be ok?

**Comment by michelleweber** [comment]
As long as we're updated language, I wonder about changing "writing" to "drafting" to be a little broader; not everyone who publishes writes. Two options:

Short and sweet:
Finished drafting? Great -- let’s get this published.

More detail to set expectations:
Finished drafting? Great -- let’s publish. Click the “Publish” button to review this post's settings and choose a publication time.

**Comment by mapk** [comment]
This looks like it will be resolved with https://github.com/WordPress/gutenberg/pull/16131. Once that PR is merged, let's close this issue.

**Comment by 0aveRyan** [comment]
@mapk That does improve some confusion, but the language is quite specific to text-based content by using "readers." It also doesn't address the nuance of publish/schedule.

### In #16131 
```
Once you’ve drafted some content, use the “Preview” button to see how it will look to readers. When you’re ready to add it to your site, use the “Publish” button.
```
Once you’ve drafted some content, use the “Preview” button to see how it will look to readers. When you’re ready to add it to your site, use the “Publish” button.
```

### Proposed
```
Want to see how your work will be displayed? Use the "Preview" button. Ready to publish your work (or schedule for later)? Use the "Publish" button.
```

**Comment by noisysocks** [comment]
#18041 has addressed this by removing dot tips in lieu of a welcome guide modal.
