### ISSUE TITLE
withSafeTimeout: Unguarded `window` reference breaks SSR

### ISSUE THREAD

**Issue by ockham** [WordPress/gutenberg#9265]
**Describe the bug**
See title, and https://github.com/Automattic/wp-calypso/pull/26838#issuecomment-415338127. Trying to boot that Calypso branch (which uses `@wp/compose` results in

```
~/src/wp-calypso/build/webpack:/node_modules/@wordpress/compose/build-module/with-safe-timeout/index.js:29
var _window = window,
^
ReferenceError: window is not defined
```

**To Reproduce**
1. Clone Calypso, and check out the branch for https://github.com/Automattic/wp-calypso/pull/26838
2. Apply https://github.com/WordPress/gutenberg/pull/9261/files#r212224119 locally (to work around another issue that would otherwise get in the way)
3. `npm start`

**Expected behavior**
Calypso booting

**Additional context**
Can we simply drop [this line](https://github.com/WordPress/gutenberg/blob/a6c36e53974ac8a9fdd6163e61b54064cfd8910f/packages/compose/src/with-safe-timeout/index.js#L19)? Since `setTimeout` and `clearTimeout` are methods of the `window` object, they should be globally available -- as they are in [Node](https://nodejs.org/api/timers.html#timers_settimeout_callback_delay_args).

**Comment by tofumatt** [comment]
I thought we could reference those directly but maybe I'm wrong? They're not language functions though, right? [They're part of `window`… or really part of `WindowOrWorkerGlobalScope`](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout)

**Comment by ockham** [comment]
> I thought we could reference those directly but maybe I'm wrong? They're not language functions though, right? [They're part of `window`… or really part of WindowOrWorkerGlobalScope](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/setTimeout)

Uh, not sure I'm getting you right. Yeah, so I think they are part of `window` (for all practical purposes :wink:) and should thus be available globally. Same on the node side, hence my proposed fix in #9266...

**Comment by tofumatt** [comment]
Ah, I just wasn't sure how pure we were being about those globals; elsewhere I see "globals" being taken off `window` too; I wondered if there was a reason we were doing it 🤷‍♂️

**Comment by aduth** [comment]
These are globals and we shouldn't be referencing them off the `window` object.

I'm recalling some previous discussion with @iseulde on this, so... cc 😄

**Comment by aduth** [comment]
Previously: https://github.com/WordPress/gutenberg/pull/2271#discussion_r132196040
