### ISSUE TITLE
Dashicons library incorrect spelling of WordPress.

### ISSUE THREAD

**Issue by BE-Webdesign** [WordPress/gutenberg#927]
In the Dashicons component, which is output from somewhere else I believe, the title for WordPress is mispelt as Wordpress 🙀!  Capital P dang'it!

**Comment by ryelle** [comment]
The Dashicons react component is built from [the dashicons repo](https://github.com/WordPress/dashicons), by a grunt process. Can you create this issue over on that repo?

**Comment by nylen** [comment]
- https://github.com/WordPress/dashicons/blob/9b200bcccf641487f84e8d47f24871c4510c0766/codepoints.json#L122
- https://github.com/WordPress/dashicons/blob/9b200bcccf641487f84e8d47f24871c4510c0766/Gruntfile.js#L299

Seems like adding a `.replace( /wordpress/gi, 'WordPress' )` is a decent way to fix this.

**Comment by BE-Webdesign** [comment]
@ryelle 

Thank you for the info, here is the link https://github.com/WordPress/dashicons/issues/186.
