### ISSUE TITLE
Block audit: Shortcode

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9279]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="37" alt="screen shot 2018-08-23 at 12 04 56 pm" src="https://user-images.githubusercontent.com/1202812/44537426-cb59cf80-a6cc-11e8-9d63-eb3953806949.png">

**Name:** Shortcode
**Description:** Add a shortcode -- a WordPress-specific snippet of code written between square brackets.
***Category:** Widgets
**CSS class:** None
**Can be converted to:** Nothing

# States

*Empty/Unselected/Placeholder*

<img width="604" alt="screen shot 2018-08-23 at 12 07 18 pm" src="https://user-images.githubusercontent.com/1202812/44537544-196ed300-a6cd-11e8-94a1-1007d5cfbbf4.png">

*Selected:*
<img width="651" alt="screen shot 2018-08-23 at 12 04 48 pm" src="https://user-images.githubusercontent.com/1202812/44537556-1f64b400-a6cd-11e8-861a-f1ff4d84ac20.png">

# Primary (toolbar) settings

None

# Secondary (sidebar) settings

None

# Frontend appearance

None — the block just renders the shortcode that's entered into it. 

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] 

# Suggestions

_Individual issues will be opened for these soon_

- The visual appearance of this block (slim, with the "Shortcode" label and icon on the left) is unlike any of our other blocks. Part of me wonders if it should mimic our other blocks that rely on a single-line text field for input ([example](https://cloudup.com/cKPKUGXrbMd)). (That said, I do prefer this slimmer design for this since it's not technically a placeholder like those are — it's also the only display state of the block within the editor.)

**Comment by sarahmonster** [comment]
I'm going to make the executive decision to close this out, since we've only got a single suggestion here, and there are ongoing efforts to consistentify the UI. Do feel free to file as a separate issue if you feel it's something that warrants further discussion! 💬
