### ISSUE TITLE
Block Audit: Archives

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9280]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

<img width="32" alt="screen shot 2018-08-23 at 12 22 24 pm" src="https://user-images.githubusercontent.com/1202812/44538479-65bb1280-a6cf-11e8-93c9-3a50b8013c55.png">

**Name:** Archives
**Description:** Display a monthly archive of your site’s Posts.
***Category:** Widgets
**CSS class:** None
**Can be converted to:** Nothing

# States

*Empty/Selected/Placeholder*

<img width="679" alt="screen shot 2018-08-23 at 12 22 21 pm" src="https://user-images.githubusercontent.com/1202812/44538547-a024af80-a6cf-11e8-9035-3687930efb7a.png">

*Unselected:*

<img width="662" alt="screen shot 2018-08-23 at 12 25 39 pm" src="https://user-images.githubusercontent.com/1202812/44538553-a9ae1780-a6cf-11e8-9266-dd5075fd3044.png">

# Primary (toolbar) settings

Align Left, Align Center, Align Right

# Secondary (sidebar) settings

Archives Settings: Show Post Counts, Display as Dropdown

# Frontend appearance

**Gutenberg Starter Theme**

<img width="735" alt="screen shot 2018-08-23 at 12 30 37 pm" src="https://user-images.githubusercontent.com/1202812/44538772-5ab4b200-a6d0-11e8-818e-01bb1db88569.png">

**Atomic Blocks**

<img width="686" alt="screen shot 2018-08-23 at 12 36 11 pm" src="https://user-images.githubusercontent.com/1202812/44539044-22fa3a00-a6d1-11e8-82ed-eee4c58a7bd7.png">

**twentyseventeen**

<img width="588" alt="screen shot 2018-08-23 at 12 37 41 pm" src="https://user-images.githubusercontent.com/1202812/44539127-5937b980-a6d1-11e8-85e9-1dbdf0226756.png">

**twentyten**

<img width="672" alt="screen shot 2018-08-23 at 12 38 19 pm" src="https://user-images.githubusercontent.com/1202812/44539161-6f457a00-a6d1-11e8-8ac3-25e1f644eb5c.png">

# Bugs/errors

_Individual issues will be opened for these soon_

- [x] Indentation for the block does not match indentation for other list-based blocks. (#9281)

# Suggestions

_Individual issues will be opened for these soon_

- [ ] Block should (at least have the option to) include custom post types. (Related to #9013, #1594)

**Comment by ZebulanStanphill** [comment]
It would be really nice if the Archives, Categories, and Latest Posts blocks all supported custom post types. That is probably out-of-scope for WordPress 5.0, but it would definitely be a nice addition.

**Comment by kjellr** [comment]
@ZebulanStanphill That's a great point. I'll add that to the suggestions above.

**Comment by mtias** [comment]
See Query Panel proposal: https://github.com/WordPress/gutenberg/issues/2662

**Comment by davidknight4242** [comment]
This is actually a general point about all the widgets in Gutenberg....absolutely love them, they work great for me....however, id love to see an optional title available for them as do in other widget areas. Without a title, well its not 100% clear what a visitor is looking at. Optional would mean if someone doesnt want it, well they can leave it blank. 

Sorry if this has been mentioned elsewhere, I couldn't find any more information.

**Comment by ZebulanStanphill** [comment]
@davidknight4242 You could simply use a Paragraph block to add a title before them, couldn't you?

**Comment by davidknight4242** [comment]
Yes a Paragraph block would work, so would a heading. Am actually making a theme and its a not really something I would expect users to remember to do. 

I would argue that any widget inside post/page content is an aside to the main content and should have its own aside container and heading, just for better code. At the moment you have a list of dates that to a lot of visitors will not mean anything without a title to explain they are archives. They could be links to old posts, upcoming posts or completely something else.

I get what you mean about the paragraph tag, but requiring one block to explain another seems an unnecessary thing to remember.

**Comment by kjellr** [comment]
@davidknight4242: There's a bit of prior discussion about widget titles over in this thread: https://github.com/WordPress/gutenberg/issues/1011#issuecomment-306433255.

**Comment by ZebulanStanphill** [comment]
@davidknight4242 Actually, wrapping widgets in `<aside>`s would apparently be bad for accessibility and may not actually be semantically correct for individual widgets.

See https://core.trac.wordpress.org/ticket/30556 and some related discussion in #9599.

Personally, I don't see any issue with having to use a Heading or Paragraph block before one of the widget blocks. I already use Heading blocks before the Paragraph blocks in my document to give names to the different sections, so it makes sense to me that I do the same thing for widgets. The best part is that I have complete control over what heading level I use or if I even use a heading at all or just a paragraph, which means I can ensure semantic correctness. If this was all added to the widget blocks, it would clutter their UI with options.

**Comment by davidknight4242** [comment]
Thank you Kjellr and ZebulanStanphill, looks like I have some reading to do! Thanks for the help!!

**Comment by sarahmonster** [comment]
I'm going to go ahead and close this tracking issue out since it seems that all issues and suggestions have been filed. If we missed anything, please do feel free to open a new issue. 

Thanks for your feedback, everyone! 🌟
