### ISSUE TITLE
Link Tool: automatically add URL to the "Paste URL or type" field if the text selected is a URL

### ISSUE THREAD

**Issue by cwpnolen** [WordPress/gutenberg#9283]
**Describe the solution you'd like**
If a user has highlighted text that is a URL, it would be helpful to automatically populate the "Paste URL or type" field with that URL instead of forcing the user to re-type or close the dialog to copy and paste the URL.

This is what the current behavior looks like in Gutenberg:
![gutenberg-link-tool](https://user-images.githubusercontent.com/2512650/44542492-f4815c80-a6da-11e8-8614-109e039a805d.gif)

This is functionality that currently exists in the classic editor
![tiny-mce-link-tool](https://user-images.githubusercontent.com/2512650/44542480-e6334080-a6da-11e8-9b07-8127afe4f0dd.gif)

**Comment by chrisvanpatten** [comment]
Hi @cwpnolen —

Thanks for the report! This will be fixed when 3.7 is released. You can see the fix here in PR #9067.

Since this is solved already I'll close this up but feel free to comment if you have any questions as we can always reopen the report :)
