### ISSUE TITLE
Generalize the native mobile ports of DIVs

### ISSUE THREAD

**Issue by hypest** [WordPress/gutenberg#9284]
During #9012 , we introduced a couple of container components (`ToolbarContainer` and `ToolbarButtonContainer`) to componentize some specific usages of `<div>` elements and provide native mobile (React Native) implementations for them. At the time, the rationale was that an introduction of a general `Div` component would move the problem of nativizing the `<div>` element into the styling domain (CSS/SCSS) to define the element's behavior, but SCSS support in the React Native app is still highly experimental and not mature enough. See also [this comment thread](https://github.com/WordPress/gutenberg/pull/9012/files#r211247127).

We expect to see patterns arising as we "port" more `<div>`s like that and this ticket serves as a reminder to "clean up" and hopefully generalize the various container components that will crop up.

**Comment by mtias** [comment]
@hypest has anything come out from this one? We should probably close anyways until there's something more tangible to pursue.

**Comment by hypest** [comment]
Nothing actionable out of this so far, or better, no particularly "generalized" patterns to follow. Thanks for pinging, let's close this and we can always revisit if it makes sense 👍
