### ISSUE TITLE
name of shortcode is rendered instead of echoing content of function

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#9285]
**Describe the bug**
A shortcode's block is not rendering; just the name of the shortcode is. 

**To Reproduce**

1. open twentyseventheme, create a very crude shortcode example like the following which is valid: 
https://gist.github.com/skorasaurus/cbecd264daa91730a9d624c3249dc98d

2. create a new post 
3. create a new shortcode block 
3. insert the name of the shortcode
![selection_150](https://user-images.githubusercontent.com/955351/44544384-0adde700-a6e0-11e8-89d6-6ba2da9d78c1.png)

4. view post
![selection_151](https://user-images.githubusercontent.com/955351/44544524-64deac80-a6e0-11e8-86be-d999487169c2.png)

**Expected behavior**
I expect the function to run which in this case; a string echo'ed. 

**Desktop (please complete the following information):**
 - OS: [ ubuntu
 - Browser [firefox 
 - Version: 61.0.1

**Additional context**
- Gutenberg 3.6.2

**Comment by youknowriad** [comment]
I think you need to write the `[]` as well. Let me know if that works for you.

**Comment by skorasaurus** [comment]
I received an 'update failed' ; nothing in the console - 
![selection_152](https://user-images.githubusercontent.com/955351/44545249-8f316980-a6e2-11e8-908a-fae20d06de20.png)

**Comment by youknowriad** [comment]
Check the network response of the "save" API call instead

**Comment by youknowriad** [comment]
(I bet you have a PHP error/warning somewhere)

**Comment by danielbachhuber** [comment]
@skorasaurus Were you able to sort this out?

**Comment by skorasaurus** [comment]
Hi, 

I still have the same problem; although a much longer error log displays in the console now - https://gist.github.com/skorasaurus/0e6bd7600d460b2810f01e57c8fef944

**Comment by skorasaurus** [comment]
Yes, Gutenberg functions as expected; except that I' receive an "Update failed" alert when a drafted post (that has a shortcode block in it) autosaves and when I click publish, I receive "Publishing failed". 
The post and shortcode will display as intended....

The alerts do not display when I use return instead of echo (silly me forgot to use return instead the first time around when making this report) in the shortcode function.

If you want to make an actionable item out of this; perhaps have a more clearer error message when detecting output from a shortcode block that is echo'ed instead of returned?

**Comment by danielbachhuber** [comment]
> If you want to make an actionable item out of this; perhaps have a more clearer error message when detecting output from a shortcode block that is echo'ed instead of returned? Otherwise, feel free to close.

This is harder to solve for and falls generally in the territory of broken REST API responses

Related #4936
