### ISSUE TITLE
2&3 Column Text Block Displays as Single Column

### ISSUE THREAD

**Issue by AMcGrady** [WordPress/gutenberg#9289]
**Describe the bug**
While creating a test post (https://amwpapp060718.com/2018/08/23/gutenberg-testing-1/) I created a 2 Column Text Block that Previews and Displays in a Single Column.

**To Reproduce**
1. On Simple Site using Booklet Theme add Text Column Block with 2 or 3 Columns of Text
2. Preview and Publish
3. See error

**Expected behavior**
Expected that text to appear in 2 or 3 Columns.

**Screenshots**
Expected:
https://image.ibb.co/m7TDce/Screenshot_2018_08_23_at_2_53_33_PM.png

![screenshot_2018_08_23_at_2_53_33_pm](https://user-images.githubusercontent.com/1119271/44551362-2ea32c00-a6e4-11e8-9b32-0a28bb18caef.png)

Actual:
https://image.ibb.co/bDytAz/Screenshot_2018_08_23_at_3_18_30_PM.png

![screenshot_2018_08_23_at_3_18_30_pm](https://user-images.githubusercontent.com/1119271/44551387-437fbf80-a6e4-11e8-986f-146f3a23d831.png)

**Desktop (please complete the following information):**
 - OS: Chrome OS
 - Browser: Chrome
 - Version: 67

**Comment by designsimply** [comment]
The Text Columns block was removed (#8036). 

I tested using the replacement, the Columns (beta) block, with WordPress 4.9.8 and Gutenberg 3.6.2 and I was able to add two columns and they look correct in a preview using the Twenty Seventeen theme.

![screen shot 2018-08-23 at thu aug 23 3 13 36 pm](https://user-images.githubusercontent.com/1119271/44552335-37e1c800-a6e7-11e8-8e7b-21ac4778ab40.png)
<sup>Seen at http://alittletestblog.com/?p=14767&preview=true running WordPress 4.9.8 and Gutenberg 3.6.2 using Firefox 61.0.2 on macOS 10.13.6.</sup>

Can you confirm if you are using the deprecated Text Columns block in your case? If yes, are you able to try a test using the Columns (beta) block?

**Comment by ZebulanStanphill** [comment]
What theme are you using? What is the theme version number? What version of Gutenberg are you using? (The latest is **3.6.2**.)

**Comment by AMcGrady** [comment]
@designsimply 
I confirm I was using the Text Columns block. I've now tested the Columns (beta) block and it led to the same error. Also tried using Theme Twenty Seventeen with the Columns (beta) block which led to the same error.
This is on a Simple Site hosted on WordPress.com that is stickied for Gutenberg.

@ZebulanStanphill 
Theme is Booklet. 

I'm not sure how to find the version information you are asking for regarding WordPress, Gutenberg and Theme. If you need this info I'd appreciate some guidance on finding it.

Thanks!

**Comment by ZebulanStanphill** [comment]
**How to find WordPress version:**
![blah](https://user-images.githubusercontent.com/19592990/44592656-d7a26300-a786-11e8-9cfd-3fc23c04cf28.png)

**How to find theme version:**
![image](https://user-images.githubusercontent.com/19592990/44592399-0704a000-a786-11e8-8a9a-a1ebf7123e86.png)
![image](https://user-images.githubusercontent.com/19592990/44592488-521eb300-a786-11e8-9361-523e2b97107d.png)

**How to find Gutenberg plugin version:**
![image](https://user-images.githubusercontent.com/19592990/44592577-9a3dd580-a786-11e8-8711-2bb32f608c70.png)

Actually, looking at your screenshots, the UI looks like that of an older Gutenberg version (I can tell by the expand/close arrows visible in the sidebar, which got redesigned in 3.6), so you are definitely running an out-of-date version of the plugin. Updates for WordPress, themes, and plugins should all appear here:
![image](https://user-images.githubusercontent.com/19592990/44593399-d96d2600-a788-11e8-9cac-54878be6a9cb.png)

After making sure that WordPress, Gutenberg, and your theme are all up-to-date, perhaps you should try contacting the developers of the Booklet theme:
https://wordpress.com/theme/booklet/support
(I think you need to be logged into your WordPress.com account to contact their support from this page.)

**Comment by youknowriad** [comment]
I think WP.com's Gutenberg experiment is still running an outdated version of Gutenberg. You might want to reach out to the people handling that. I'm closing as there's no actionable items to be done in Gutenberg "Core"
