### ISSUE TITLE
Allowed HTML tags are stripped in gut

### ISSUE THREAD

**Issue by BoiteAWeb** [WordPress/gutenberg#9291]
**Describe the bug**
The SCRIPT tag and javascript attributes are stripped from my content when I convert a classic bloc into a gut one.

**To Reproduce**
1. Log in as administrator
2. Add a new classic post and add a `<script>alert(gut/)</script>` tag + `<p onmouseover="javascript:alert('/gut/)">enberg</p>` in the content
3. Save
4. Edit it in gutenberg
5. Convert your classic bloc as a gut one

**Expected behavior**
Since SCRIPT tags and JS attrs are allowed as administrator, gut should not strip them without any notice.

**Screenshots**
Classic text mode
https://www.dropbox.com/s/ii7b4j26piahj0v/Capture%20d%27%C3%A9cran%202018-08-23%2023.15.31.png?dl=0
Classic visual mode
https://www.dropbox.com/s/bkyw91yeyjuaota/Capture%20d%27%C3%A9cran%202018-08-23%2023.15.46.png?dl=0
Gut after conversion
https://www.dropbox.com/s/6igyvs0xgt7y2bf/Capture%20d%27%C3%A9cran%202018-08-23%2023.16.31.png?dl=0

**Desktop (please complete the following information):**
 - OS: Mac 10.11.6
 - Browser: Chrome 
 - Version 68

**Additional context**
- Gutenberg 3.6.2

**Comment by ZebulanStanphill** [comment]
I think this is a duplicate of #6102. See also: #6878 and #7604.

**Comment by BoiteAWeb** [comment]
My bad you're right.
