### ISSUE TITLE
Hard coded width for center, right, and left aligned images

### ISSUE THREAD

**Issue by gutterberg** [WordPress/gutenberg#9302]
**Describe the bug**
If an image is left, centred, or right aligned, it cannot be resized beyond 580 pixels within the Gutenberg editor regardless of the dimensions of  the actual image file. This makes it impossible to predict what it will look like on the front end as it will likely display as the actual size specified as opposed to how it shows in the Gutenberg editor.

**To Reproduce**
Add and image
Leave it centered or set it to left or right alined.
Try to display is larger that 580px. 

**Expected behavior**
You should be able to drag-resize the image up to the actual pixel dimensions of the file, whether it's the original, large, medium-large, etc., or at the very least to the content width of the theme.

The culprit is this line of code in /editor/index.js

line 4778: 			maxWidth: 580,

**Desktop (please complete the following information):**
 - All
 - All

Gutenberg version 3.6.2

**Comment by gutterberg** [comment]
Further thoughts on this:

If themes can control the width of the Gutenberg editor (and they absolutely should be able to!), then Gutenberg also needs to respect the images sizes set by the user or the theme. IF a medium image is 630px wide, it needs to be shown as 630 pixels wide. At the moment, this is impossible in Gutenberg. Only wide and full width images show as expected (going from memory here, maybe they don't).

**Comment by samikeijonen** [comment]
I noticed the same issue when you change content width in the editor via CSS.

In the editor image block `block-library-image__resizer` have inline styles which set the `width: 580px;`. If I change editor width to something else via CSS this doesn’t match anymore.

1. Can those inline values be off before user start resizing the image?
1. If not, can that hard coded  `width: 580px;` be changed somehow?

**Comment by chrisvanpatten** [comment]
I noticed this on an un-aligned image as well, not just left/right/center.

**Comment by samikeijonen** [comment]
> I noticed this on an un-aligned image as well, not just left/right/center.

Yep.

**Comment by azaozz** [comment]
> ... [an image] will likely display as the actual size specified as opposed to how it shows in the Gutenberg editor.

This will (should) be fixed in #6177. It adds a `scale` attribute to the image block that will be used to scale images according to the block width on the front-end. This ensures images will displayed on the front-end exactly as they are displayed in the editor. (By default all images will have `scale = 1`, i.e. 100% width.)

**Comment by azaozz** [comment]
Updated the image block branch: https://github.com/WordPress/gutenberg/tree/update/image-block, please test :)

**Comment by gutterberg** [comment]
Tested. Note sure what's changed in that version, but it is still impossible to size images beyond 580 pixels in the editor unless they are "wide" or "full". Right, left or center aligned images are hard coded to 580 pixels, which is tremendously stupid.

**Comment by azaozz** [comment]
Updated the branch again, please re-test :)

How are you trying to resize the image? The only way to set "hard coded" size is to use the sidebar width or height, otherwise the size is set on the front-end automatically (some fixes there in the update).

When using `srcset` (as this branch implements) it is not necessary to pick a specific image file. It will be overridden by the `srcset` and `sizes` attributes on the front-end, the browser "decides" which file to download.

**Comment by gutterberg** [comment]
I think you are misunderstanding the problem that this thread is about. It was nothing to do with specific image files or srcset. The issue is purely in regard to the editor refusing to allow images to display at a size larger than 580px. They cannot be dragged larger, they do not get large is you choose "full size" in the sidebar. Because some idiot decided to hardcode 580px into the gutenberg code. So if you choose a medium size image, for example, it might display at 700px on the front end, but will stuboornly refuse to get larger than 580px in the back end.

This has ruined WYSIWYG editing for anything that uses fixed layouts of any kind, which, despite the prevailing myopic view among developers today, are still very useful and can be quite mobile friendly if coded correctly.

Your branch does not appear to solve this issue, unless it changes the specific line of code reference in the first post which is the culprit.

**Comment by gutterberg** [comment]
Images are still locked to 580px in latest Gutenberg version. Will this ever be fixed?

**Comment by gutterberg** [comment]
Still not fixed.

**Comment by gutterberg** [comment]
Honestly, how can such a stupid design decision like this still no have been fixed, and still complete ignore any settings described here? https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor

And this crapware is expected to be released on November 19? This is insane. Plus, everything seems to have regressed and none of the settings described in this page: https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#changing-the-width-of-the-editor seem to have any effect anymore anyway.

**Comment by timhibberd** [comment]
@gutterberg - I feel your pain and agree that this issue should be fixed but the people in charge of the core code and the core contributors are working hard at the moment tackling a large number of issues in a short amount of time. Patience. Something this obvious will get fixed. Also it's open source...you can always fork it and delete that one constant. A fairly small effort to achieve your goal :-)

I speak to you as another issue creator waiting patiently and optimistically that Gutenberg will slow down long enough to take a deep breath and solve issues such as this one before shipping.

**Comment by gutterberg** [comment]
> 
> 
> @gutterberg - I feel your pain and agree that this issue should be fixed but the people in charge of the core code and the core contributors are working hard at the moment tackling a large number of issues in a short amount of time. Patience. Something this obvious will get fixed. Also it's open source...you can always fork it and delete that one constant. A fairly small effort to achieve your goal :-)
> 
> I speak to you as another issue creator waiting patiently and optimistically that Gutenberg will slow down long enough to take a deep breath and solve issues such as this one before shipping.

Well Tim, you're a lot more optimistic than I given that the core contributors have been tone-deaf at best, and completely antagonistic at worst when it comes to forcing this half-baked monstrosity on everyone.

**Comment by timhibberd** [comment]
You have to remind yourself that these are, in many cases, people like you and I working for free using our spare time to give back to open source. Patience and optimism are a must in open source :-)

**Comment by gutterberg** [comment]
> 
> 
> You have to remind yourself that these are, in many cases, people like you and I working for free using our spare time to give back to open source. Patience and optimism are a must in open source :-)

The people forcing this garbage are absolutely not working for free, but in fact have become filthy rich on the backs of the people working for free. 

I'd have patience and optimism if there was any indication they listened or care at all for the feedback they have received. They have made it abundantly clear that they do not.

**Comment by timhibberd** [comment]
Gutenberg is a big change. Big changes are sometimes messy. WordPress needs to stay relevant in a Wix / Squarespace world. That's the reality. If you do, really, believe that Gutenberg is not the destiny you believe in, perhaps ClassicPress is your better future path. Just a thought...do not mean to be presumptuous or rain on your rant :-)

**Comment by gutterberg** [comment]
> 
> 
> Gutenberg is a big change. Big changes are sometimes messy. WordPress needs to stay relevant in a Wix / Squarespace world. That's the reality. If you do, really, believe that Gutenberg is not the destiny you believe in, perhaps ClassicPress is your better future path. Just a thought...do not mean to be presumptuous or rain on your rant :-)

I've heard that excuse before, and it's still nonsense. WordPress runs 35% of the top 10,000 websites in the world, and they sure as hell weren't in danger of switching to WIX. The WordPress market has never been the WIX market, and it never will be the WIX.

So basically they are crapping on their actual users in favour of courting users they'll never get.

**Comment by gutterberg** [comment]
New version of Crappenberg released today.

Still not fixed.
