### ISSUE TITLE
Schedule button: "The editor has encountered an error"

### ISSUE THREAD

**Issue by KPeregrinePgh** [WordPress/gutenberg#9316]
I often schedule posts for future dates but when I click on [Schedule] in Gutenberg version 3.6.2 it's first attempt often fails with error "The editor has encountered an error" [Attempt recovery] [Copy Post Text] [Copy Error]
SO I click on [Attempt Recovery], then click [Schedule], and it works.  
This has happened numerous times on posts that I've worked on in Draft mode for a few days.
NOTE: This doesn't always happen!  When I set the post to draft via Quick Edit the next time I tried to Schedule it worked just fine.  Hmmmm!

**To Reproduce**  (see above)

[Copy Error] is pasted below:
```
this.wp.editor</Ba<@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/build/editor/index.js?ver=1534582241:12:272762
r@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/build/data/index.js?ver=1534582241:1:63924
e@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/build/data/index.js?ver=1534582241:1:64121
yh@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:97:111
lg@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:88
mg@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:120:386
gc@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:127:202
vb@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:230
ub@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:126:65
wg@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:137:182
Ze@https://www.birdsoutsidemywindow.org/wp-content/plugins/gutenberg/vendor/react-dom.min.82e21c65.js:41:24
```

**Desktop (please complete the following information):**
 - Windows 10
 - Firefox version 61.0.2

**Comment by youknowriad** [comment]
Unfortunately, this doesn't help a lot to reproduce the issue. Do you think you can share the error from the browser's console, it can contain more information?
