### ISSUE TITLE
Error when adding blocks

### ISSUE THREAD

**Issue by Aldebaran10** [WordPress/gutenberg#9317]
**Describe the bug**
 error message "an error occurred in this block and you can't see a preview" after adding blocks and the page is blank

**To Reproduce**
1. Go to '+-sign for adding blocks'
2. Click on 'e.g. title block' to add it
same for an existing page or a new one
4. See error "an error occurred in this block and you can't see a preview"

**Expected behavior**
I am no longer able to add blocks so I have to switch back to the classic editor.

**Screenshots**
![block error](https://user-images.githubusercontent.com/12007820/44585893-18fa3900-a7ae-11e8-95ce-70bb1c9e65b9.jpeg)

**Desktop (please complete the following information):**
 - OS: macOS High Sierra 10.13.6
 - Browser Safari
 - Version 11.1.2

**Smartphone (please complete the following information):**
 - Browser Safari

**Additional context**
- Please add the version of Gutenberg you are using in the description.
  Gutenberg Version 3.6.2
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by youknowriad** [comment]
Which block is causing this issue? is it all the blocks? Also, can you open the browser's console and send us the JavaScript errors reported there? Thanks.

**Comment by Aldebaran10** [comment]
I tried it with several blocks, always the same error back. Here are two error messages from JavaScript: First I added a title block, second I added a text block. Thanks

[Error] TypeError: undefined is not an object (evaluating 'Wc.a.init')
value — index.js:12:211685
value — index.js:12:210267
jc — react-dom.min.82e21c65.js:134:141
gc — react-dom.min.82e21c65.js:127:226
vb — react-dom.min.82e21c65.js:126:233
ub — react-dom.min.82e21c65.js:126
wg — react-dom.min.82e21c65.js:137:185
Ze — react-dom.min.82e21c65.js:41
Ze

	bg (react-dom.min.82e21c65.js:110)
	callback (react-dom.min.82e21c65.js:116:181)
	Jf (react-dom.min.82e21c65.js:73:105)
	Kf (react-dom.min.82e21c65.js:73:411)
	jc (react-dom.min.82e21c65.js:134:382)
	gc (react-dom.min.82e21c65.js:127:226)
	vb (react-dom.min.82e21c65.js:126:233)
	ub (react-dom.min.82e21c65.js:126)
	wg (react-dom.min.82e21c65.js:137:185)
	Ze (react-dom.min.82e21c65.js:41)
	Ze
[Error] TypeError: undefined is not an object (evaluating 'Wc.a.init')
value — index.js:12:211685
value — index.js:12:210267
jc — react-dom.min.82e21c65.js:134:141
gc — react-dom.min.82e21c65.js:127:226
vb — react-dom.min.82e21c65.js:126:233
ub — react-dom.min.82e21c65.js:126
wg — react-dom.min.82e21c65.js:137:185
Ze — react-dom.min.82e21c65.js:41
Ze

	bg (react-dom.min.82e21c65.js:110)
	callback (react-dom.min.82e21c65.js:116:181)
	Jf (react-dom.min.82e21c65.js:73:105)
	Kf (react-dom.min.82e21c65.js:73:411)
	jc (react-dom.min.82e21c65.js:134:382)
	gc (react-dom.min.82e21c65.js:127:226)
	vb (react-dom.min.82e21c65.js:126:233)
	ub (react-dom.min.82e21c65.js:126)
	wg (react-dom.min.82e21c65.js:137:185)
	Ze (react-dom.min.82e21c65.js:41)
	Ze

**Comment by youknowriad** [comment]
Do you see the `index.js:12:211685` file at the top of the error trace? Can you get the full path of this script? It should available somewhere in the error trace (by clicking or on the right)

Another question, do you use a Gutenberg Plugin or a Metabox Plugin? Thanks

**Comment by Aldebaran10** [comment]
Is it this what you need?
And I use Gutenberg Plugin
https://genussautoren.cmg-webdesign.ch/wp-content/plugins/gutenberg/build/editor/index.js?ver=1535112919

**Comment by youknowriad** [comment]
Looks like an issue with TinyMCE. Do you see any network error on the console?

I'm closing this issue as it's a duplicate of #8936 and #8690 

You can find more information on how to debug this and potentially fix it on one of these issues.

**Comment by Aldebaran10** [comment]
Thanks Riad, I found TinyMCE errors and I checked the other threads but nobody seems to have a solution yet. I didn’t. have this issue in Gutenberg 3.6.1 so it doesn’t help at this point of time.

**Comment by youknowriad** [comment]
I don't have anything else on my mind to fix the issue. 

What I can say is that 3.6.1 and 3.6.2 are not that different. This issue can't be present in 3.6.2 but not in 3.6.1. It must have been something else that triggered the issue.

In general, this is more a "server side" issue with the way TinyMCE is enqueued. Maybe your `wp-includes` folder is "protected" which means we can't load any file from this folder. Some WordPress installs do that. 

You can follow these issues. If we have a fix for all these breakage at once, we will update the status of these issues. but it's very hard because these issues are more related to the server's configuration than the code in itself.
