### ISSUE TITLE
Article

### ISSUE THREAD

**Issue by LowSpirit79** [WordPress/gutenberg#9325]
the articles overlap both on the article page and on the blog page
going over the sharing tools

OS: 10.13.06
chrome: 68.0.3440.106
Gutenberg 3.6.2
<img width="616" alt="schermata gutenberg1" src="https://user-images.githubusercontent.com/42677405/44593508-d2afd480-a7c3-11e8-8053-fd51b2051ca7.png">

<img width="612" alt="schermata gutenberg2" src="https://user-images.githubusercontent.com/42677405/44593514-d6dbf200-a7c3-11e8-9013-df9b6d3b50fa.png">

**Comment by youknowriad** [comment]
This is probably a theme issue. I can't reproduce with Twenty Seventeen for example. I'd consider asking  your theme's author about this.

**Comment by youknowriad** [comment]
If you're using a custom block, it could be also an issue with the custom block's styling.

**Comment by LowSpirit79** [comment]
if I duplicate three empty blocks, it does not overlap!
