### ISSUE TITLE
Toolbar on classic block disappears on scroll

### ISSUE THREAD

**Issue by rosswintle** [WordPress/gutenberg#9341]
**Describe the bug**

I’m on an iPad (not yet tested on anything else). I have a classic block with more content than will fit inside the Gutenberg block editor. The toolbar of the classic editor scrolls out of view. This makes formatting very difficult.  The toolbar of the classic editor in the classic block should probably fix to the top when it scrolls.

See screen grab at: 
https://cl.ly/2fe58e172be1

**To Reproduce**

1. Start a new post in Gutenberg on an iPad
2. Add a classic block
3. Add enough content to make the classic block scroll inside the editor window

**Expected behavior**

I should be able to format text without having to scroll up and down.

**Screenshots**

https://cl.ly/2fe58e172be1

**Tablet (please complete the following information):**
 - Device: iPad Air 2
 - OS: iOS
 - Browser: Chrome
 - Version: 68

**Comment by mtias** [comment]
The toolbar should be scrolling with the Classic block text now:

![image](https://user-images.githubusercontent.com/548849/46609828-5a019f00-cb09-11e8-9a03-937ea503fc98.png)
