### ISSUE TITLE
Gallery Block: consider adding the ability to add a caption below a gallery block

### ISSUE THREAD

**Issue by homebrandcola** [WordPress/gutenberg#9342]
Started using the new Gutenberg editor, quite liking it.

What I would like is the ability to add a caption to a Gallery Block like this:

<img width="735" alt="gallery-caption" src="https://user-images.githubusercontent.com/5846428/44616520-c0ea3200-a894-11e8-958f-93a3e3321156.png">

It would be property of the block, not of an individual image.

**Comment by karmatosed** [comment]
I can see this being useful, thanks for suggesting it. We could simply have the same design as we have for images but expand to fit this.

**Comment by linux4me** [comment]
Adding an option to display the captions below gallery images would solve an issue I've run across when the captions are multiple lines. On a mobile display, the captions cover so much of the image they prevent a user from clicking on the image to visit the full-size image or custom URL associated with the image.

**Comment by kjellr** [comment]
> I can see this being useful, thanks for suggesting it. We could simply have the same design as we have for images but expand to fit this.

Quick mockup of this: 

![gallery-caption](https://user-images.githubusercontent.com/1202812/51772706-ad98f800-20ba-11e9-9b7c-cd64a0870d4d.png)

---

> Adding an option to display the captions below gallery images would solve an issue I've run across when the captions are multiple lines. On a mobile display, the captions cover so much of the image they prevent a user from clicking on the image to visit the full-size image or custom URL associated with the image.

This is actually a separate issue, which was explored in https://github.com/WordPress/gutenberg/issues/8030. 

The implementation ran into some [technical issues](https://github.com/WordPress/gutenberg/pull/8344), and it was closed for Phase 1. I'm not 100% sure whether those are surmountable, but it could be worth another discussion in the context of Phase 2.

**Comment by talldan** [comment]
Fixed by https://github.com/WordPress/gutenberg/pull/17101
