### ISSUE TITLE
Block: File - Drag+drop upload results in combined title + placeholder

### ISSUE THREAD

**Issue by eddhurst** [WordPress/gutenberg#9348]
When uploading a new file into the editor via drag+drop, Gutenberg recognises this as a file block and automatically starts uploading it, showing the placeholder "Write file name..." in semi-transparent blue. At the same time, it also renders the upload, identifies the title and shows the title of the file being uploaded.

This results in the two clashing (see screenshot).

**To Reproduce**
Steps to reproduce the behaviour:
1. Drag + Drop upload into editor
2. See error

**Expected behaviour**
After drop, I would expect to either:
* see "File processing..." until successfully uploaded
* once uploaded, switch to show identified file title

**Screenshots**
<img width="418" alt="screen shot 2018-08-25 at 12 37 48" src="https://user-images.githubusercontent.com/9933592/44618104-9f268600-a867-11e8-8d0e-dd857b0258c3.png">

**Desktop (please complete the following information):**
 - OS: Mac Sierra 10.12.5
 - Browser: Chrome
 - Version: 67.0.3396.99

**Additional context**
Gutenberg: 3.6.2

**Comment by eddhurst** [comment]
Just noted - if you click to add a File block first, and then drag + drop into the area that says "
Drag a file, upload a new one or select a file from your library." this does actually work more or less as expected: with the placeholder text pulsing until successfully uploaded, and then switching to show file title.

The above bug is specifically for dragging and dropping inline into the editor, without a destination-block.

**Comment by arunsathiya** [comment]
Noting that I was able to reproduce this on my tests as well. I tested on a local setup and a remote setup.

- Dragged a PDF file to the Gutenberg editor, without a file block defined. 
- The video uploaded immediately (on localhost) and took a few seconds to upload on a remote setup.
- During the remote upload test, I was able to notice that the pulsating file title was overlapping the `Write file name` input field. **But, this happens only after a few seconds of uploading the file.**

GIF indicating this behavior.

![gutenberg file upload without a file block shows the write file name notice overlapped with identified file title](https://user-images.githubusercontent.com/18581859/44627336-bdfd4900-a949-11e8-8991-ed748a800876.gif)

GIF indicating the behavior when the file is uploaded to the defined file block:

![gutenberg file upload with the file block defined first](https://user-images.githubusercontent.com/18581859/44627337-ca81a180-a949-11e8-9600-063be9125a80.gif)

Sorry, the GIFs might not be high quality.

--- 

Tested on a local install of WordPress, and a remote installation as well. 

WordPress 4.9.8 and Gutenberg 3.6.2 using Firefox Quantum 61.0.2 (64-bit) on macOS 10.13.6

**Comment by nosolosw** [comment]
Could not reproduce on Chrome or Firefox under Linux (Ubuntu). Will leave this open in case this is an OS specific issue.

**Comment by arunsathiya** [comment]
@nosolosw Is it possible that you're on a high-speed network and are testing with small files? I wasn't able to notice this either for small files on high-speed networks.

You might want to try with larger files?

**Comment by youknowriad** [comment]
I was not able to reproduce this either. It might have been fixed. let's reopen If there's any detailed steps.
