### ISSUE TITLE
InnerBlocks template causes extra blocks to disappear on editor reload

### ISSUE THREAD

**Issue by felixarntz** [WordPress/gutenberg#9349]
**Describe the bug**
I'm using the `InnerBlocks` component in a block in which I want to allow only a single specific block type to be used as children, however as many times as necessary. Gutenberg's own columns block is similar in the way that only the `core/column` block is allowed as child, however different as in that there is a template set that must not be changed (via `templateLock` set to 'all').

As I understand from the documentation, the `templateLock` prop sets whether/how the template can be modified. And when I set it to `false`, I can duplicate blocks, add new blocks, remove blocks as expected. However, when reloading the editor, it only shows the (number of) blocks that the original template would allow.

**To Reproduce**
Create a block such as the following:
```js
const { Fragment } = wp.element;
const {
	InnerBlocks,
} = wp.editor;
const { __ } = wp.i18n;

const ALLOWED_BLOCKS = [ 'core/image' ];
const TEMPLATE = [
	[ 'core/image' ],
	[ 'core/image' ],
	[ 'core/image' ],
];

export const name = 'myplugin/test';

export const settings = {
	title: __( 'Test', 'textdomain' ),
	category: 'layout',
	icon: 'grid-view',
	attributes: {},
	edit: () => {
		return (
			<Fragment>
				<div className="my-blocks-container">
					<InnerBlocks
						allowedBlocks={ ALLOWED_BLOCKS }
						template={ TEMPLATE }
						templateLock={ false }
					/>
				</div>
			</Fragment>
		);
	},
	save: () => {
		return (
			<div className="my-blocks-container">
				<InnerBlocks.Content />
			</div>
		);
	},
};
```

As you can see, by default three image blocks are placed inside the outer block. You can add further ones, and they will save correctly. They will show up on the frontend too. However, when you reload the editor window, you will only see the first three inner blocks as before, as for some reason it always sets back to the template. The properties of them will still be in place, but the extra blocks will simply have vanished. And after saving again, of course they're then no longer present in the frontend as well.

Note that removing blocks is not an issue, they will be gone as expected. Only additional blocks are affected.

**Expected behavior**
When a template is given and `templateLock` is set to false, additional blocks should show up as expected when reloading the editor.

**Additional context**
- WordPress 4.9.8
- Gutenberg 3.6.2

**Comment by chrisvanpatten** [comment]
I think this is a duplicate of #8901. Can you check @felixarntz?

**Comment by felixarntz** [comment]
@chrisvanpatten Is the issue number you referred to as intended? I don't see any relationship to this issue tbh :)

**Comment by chrisvanpatten** [comment]
@felixarntz argh! My bad, sorry! 🙈 I meant #8109!

**Comment by felixarntz** [comment]
@chrisvanpatten Ah, indeed! I'll close this.
