### ISSUE TITLE
Edit post blank on block of image

### ISSUE THREAD

**Issue by Roxyssi** [WordPress/gutenberg#9351]
Hello everyone!
**Describe the bug**
I create all post with gutenberg, but now when I edit this the block of image doesn't exist. 

**To Reproduce**
- Open my post
- Edit
- doesn't exist block image 

![wordpress-blockimage](https://user-images.githubusercontent.com/42695425/44618174-4a880880-a871-11e8-97ce-7f8866c53d4c.gif)

**Expected behavior**
I could modify the image of my post

**Desktop**
 - OS: macOs HighSierra
 - Browser chrome
 - Version 68.0.3440.106

Thanks for support! :)

**Comment by youknowriad** [comment]
Do you see any 404 requests in the console, do you see any javascript error? Can you send the HTML content of one of your posts with the issue?

**Comment by Roxyssi** [comment]
This is the error on console 
![schermata 2018-08-25 alle 14 47 26](https://user-images.githubusercontent.com/42695425/44618428-d865f280-a875-11e8-8c88-b4450ce2e93d.png)

This is a HTML of content post
[content-post.zip](https://github.com/WordPress/gutenberg/files/2320641/content-post.zip)

Thanks for reply!

**Comment by Roxyssi** [comment]
Ohhhh yes! I move wordpress install
I'll have to change them one by one?

**Comment by youknowriad** [comment]
Unfortunately yes, I'm surprised it works in the frontend. (That's unrelated with Gutenberg, I suspect you have the same issue if you open in the classic editor)

**Comment by youknowriad** [comment]
Closing as this seems resolved.

**Comment by Roxyssi** [comment]
No sorry the path of media is correct, there isn't a folder path /wordpress,
If you click and show the URL of image is correct! rossanavalastro.com 

I change the path of image one by one... But, I think Gutenberg not change this path when move the wordpress install .

**Comment by youknowriad** [comment]
Gutenberg don't have anything to do with moving WordPress. Can you do something for me. Switch to the "code editor" mode and grab the HTML from there?

**Comment by youknowriad** [comment]
What's happening is that the `srcset` attribute in the frontend is correct because the image ids in the classname are correct. The frontend is using the `srcset` to display the image properly, but in the backend (the raw HTML) there's no `srcset` because these are added automatically on the frontend so the `src` attribute of the block is wrong.
