### ISSUE TITLE
Visual editor <-> Code editor

### ISSUE THREAD

**Issue by puerstik** [WordPress/gutenberg#9354]
**Description of the issue**
I have a bunch of blog posts where I use a simple style section for the tables within the post. The problem with Gutenberg is that as soon as I edit an old post, it automatically adds a html break `"<br` />" after each line, which completely brakes my work. Also it seems to add a `"<tbody>"` and unneccessary `";"` to my tables.

I would highly recommend to re-think the way you dealing with manual code. As a developer, I'd like to add content the way I want, not the way Gutenberg thinks it should. Please be so kind to resolve that - it's very hard to work like that, if not impossible (because as soon as I delete the `"<br/>` stuff, Gutenberg is adding it again automatically. 

My Version of Gutenberg is 

**To Reproduce**
1. Go to a blog post and switch to Code editor mode
2. Insert a table style section with a simple table below e.g.
`<style>
table, th, td {
    border: 2px solid black;
    border-radius: 2em 1em 4em / 0.5em 3em;
    text-align: center;
    padding: 5px;
}
th, td {
    border-radius: 0px;
    border: none;
    border-collapse: collapse;
}
</style>`
`<table style="width: 100%" cellspacing="0" align="center">
<tr>
<th style="border-bottom: 1px solid black">Schwierigkeitsgrad</th>
<td style="border-left: 1px solid black; border-bottom: 1px solid black;">D/E</td>
</tr>
</table>`
3. Switch from Code editor back to Visual 
4. And back again to the code editor
5. See some unwanted `<br/>` and `";"` added

**Expected behavior**
Do not change code which was added manually.

**Desktop (please complete the following information):**
 - OS: Windows 10 1803
 - Browser: Firefox ESR
 - Version: 52.9.0

**Comment by youknowriad** [comment]
For these advanced use-cases, you can use the HTML block where you can paste any random HTML and it will be kept as is. How does that work for you?

**Comment by youknowriad** [comment]
👍 I'm going to close this for now. I hope you enjoy Gutenberg.
