### ISSUE TITLE
Backspace not working when typing paragraphs

### ISSUE THREAD

**Issue by Andromeda2803** [WordPress/gutenberg#9360]
**Describe the bug**
Backspace doesn't remove text. Del does work to delete text. Backspace does work in headers.

**To Reproduce**
1. Go to new post
2. Click on any paragraph
3. Scroll down to where you want to type
4. Be unable to use backspace

**Expected behavior**
Text is removed like usual.

**Desktop (please complete the following information):**
 - Windows
 - Chrome
 - 68.0.3440.106

**Additional context**
- Latest version. Also have Bateaux installed as a theme.

**Comment by youknowriad** [comment]
>  Backspace does work in headers.

What do you mean by headers. Backspace seems to work properly in my testing.
