### ISSUE TITLE
The keyboard shortcut to open the Keyboard Shortcuts modal conflicts with native shortcuts

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#9361]
Follow up to #8316 

> Pressing ctl+option+h (shift+alt+h on windows/linux) displays a modal detailing keyboard shortcuts.

When VoiceOver is running, `ctrl+option+h` opens the VoiceOver help and the modal doesn't open at all:

![ctrl option h](https://user-images.githubusercontent.com/1682452/44629256-bc815000-a94c-11e8-9021-10ec1c3f7831.jpg)

`shift+alt+h` on Windows opens the Firefox and IE11 Help menu: the modal opens but focus is on the browser's menu:

![screenshot 64](https://user-images.githubusercontent.com/1682452/44629265-cd31c600-a94c-11e8-85dc-dbd160385376.png)

![screenshot 65](https://user-images.githubusercontent.com/1682452/44629267-cd31c600-a94c-11e8-8bf1-92604f97f71c.png)

**Comment by afercia** [comment]
Re: `shift+alt+h` on Windows, worth noting in the Classic Editor it works and it opens the TinyMCE help without opening also the browser's Help menu (I guess it prevents default?).

**Comment by tofumatt** [comment]
Would using `?` (and `Control+?`, mainly for when an input has focus) as shortcuts be alright? They don't seem to be used by the OSes for anything and sites like Trello and GitHub use them (see #10914).

**Comment by afercia** [comment]
This is still a problem:
- on Windows, `Shift Alt H` opens the browser's help menu in Firefox and IE11
- on macOS with VoiceOver running, `Control Option H` opens the VoiceOver help, see also #11154

**Comment by afercia** [comment]
Related: #3218

**Comment by paaljoachim** [comment]
Is this issue still valid @joedolson ?
If so how can we move forward with it?
Thanks!

**Comment by afercia** [comment]
Closing in favor of https://github.com/WordPress/gutenberg/issues/15335 (which comes from the WPCampus accessibility audit).
