### ISSUE TITLE
Consider to improve the Post Format suggestion design and accessibility

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#9363]
When Gutenberg detects a post content could benefit from applying a specific post format, a suggestion appears in the Sidebar:

<img width="354" alt="screen shot 2018-08-26 at 19 26 11" src="https://user-images.githubusercontent.com/1682452/44631321-83f06f00-a96a-11e8-935e-f1ac880f8cd9.png">

Depending on the content, it can be any of the post formats, e.g. a Gallery:

<img width="312" alt="screen shot 2018-08-26 at 19 56 52" src="https://user-images.githubusercontent.com/1682452/44631335-9f5b7a00-a96a-11e8-8811-cd64b82ea96b.png">

Clicking the suggested format, sets the format in the post.

I think there are a couple things that could be improved:
- the placement of the suggestion could maybe be improved and be aligned to the left
- the button text could be improved for better understanding and accessibility: UI controls should make sense even when read out of context; instead, the button says just "Video" (or "Gallery", etc.), the current rendered markup is:

```
<div class="editor-post-format__suggestion">
	Suggestion:
	<button type="button" class="components-button is-link">Video</button>
</div>
```

Instead, the post format suggestion displayed in the publishing flow is clearer and makes sense even when read out of context:

<img width="311" alt="screen shot 2018-08-26 at 19 57 19" src="https://user-images.githubusercontent.com/1682452/44631388-1f81df80-a96b-11e8-8379-688e25026385.png">

<img width="308" alt="screen shot 2018-08-26 at 19 57 38" src="https://user-images.githubusercontent.com/1682452/44631389-1f81df80-a96b-11e8-9547-f7dfc25f20e7.png">

I'd suggest to refactor the text used in the Sidebar to use something along the lines of the one used in the Publishing flow.

**Comment by afercia** [comment]
A very quick first attempt, before (left) and after(right):

![screen shot 2018-08-27 at 18 38 47](https://user-images.githubusercontent.com/1682452/44672514-f2940200-aa28-11e8-87bf-845d469e8799.png)

**Comment by karmatosed** [comment]
What is the a11y reason for the left? I ask as it's making it less readable so trying to find the balance.

**Comment by afercia** [comment]
> What is the a11y reason for the left?

I'm not sure I fully understand. Do you mean left alignment? To me, it's more readable left aligned. Besides subjective opinions that might differ, this text now is longer (and potentially even longer when translated) and doesn't look so nice when right-aligned.

**Comment by karmatosed** [comment]
@afercia thanks for the explanation. I wanted to make sure it was a visual not hierarchy for screen readers or other assisted devices.

As people expect to see post formats in the actual sidebar right now, it's not a mental model I think we should break today. Some themes hook into it for display.

Let's get this in but not aligned left. I think right for now. Do we need to say all of that text, fine if we do but wanted to check.

**Comment by tofumatt** [comment]
All of that text needs to be there. It's inaccessible if not, but it's also just poor usability. It should read:

> Suggestion: Apply the "`$FORMAT`" format.

I can't think of a less-verbose way of phrasing it that doesn't lose context, but if anyone can, go for it ^_^
