### ISSUE TITLE
Add Noscript tag for when javascript is disabled

### ISSUE THREAD

**Issue by BinaryMoon** [WordPress/gutenberg#9365]
Chrome for Android may start disabling javascript for slow connections.
https://www.androidpolice.com/2018/08/23/chrome-android-may-start-disabling-javascript-2g-connections/

Plus some people disable javascript.

Currently if you don't have javascript enabled the page loads totally blank, it almost looks like something went wrong.

I think it would be helpful to add a noscript tag with a message explaining why javascript is needed and how to enable it for the current site.

**Comment by tomaszpoliszuk** [comment]
It would be even better if we could have completely basic textarea for power users who disable javascript or have slow connections (similar to what we have in classic editor).

**Comment by earnjam** [comment]
This was resolved in ee51293373d5b90c9c0a2580004188f7bbfa28c0

**Comment by tomaszpoliszuk** [comment]
Ignoring problem != resolving problem.

Site can be used by two people:
- one with js disabled
- one with js enabled

Using Gutenberg and Classic Editor on the same page is not an option.
