### ISSUE TITLE
"wide" and "full" alignments should always be usable in editor

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#9367]
## The issue
**Please read the discussion that led to the creation of this issue:**
https://wordpress.slack.com/archives/C02QB2JS7/p1535317929000100

The `wide` and `full` alignment options are only shown in the editor when the theme uses `add_theme_support( 'align-wide' )`. However, this approach can causes issues when switching themes.

## Example of problematic situation
1. Use a theme that supports the `wide` and `full` alignments.
2. Create and save a post containing a Columns block using the `wide` or `full` alignment options.
3. Switch to a theme that does not support the `wide` and `full` alignments.
4. Try to change the alignment of the Columns block.
5. Notice that you can not change the alignment because there are no alignment options shown.

## Expected behavior
The editor should always show the `wide` and `full` alignment options, even when the theme does not provide styling for them.

Changing themes should not cause content to become uneditable like this. **The editor should not care if the theme provides styling for any of the alignment options**; it should always make them available anyway. Technically, a theme could choose to not provide styling for the `left`, `center`, or `right` alignments, but that does not mean that those alignments should be hidden in the editor.

Either the `wide` and `full` alignments should always be available or else they are not a standard feature and should not be included in core. The `wide` and `full` alignments should be treated like any other standard alignment in WordPress.

## But what about making the editor look like the front-end?
The Columns block in the aforementioned situation already does not look like the front-end, and worse, there is no way to change it to the standard width.

If something like #9008 is implemented to make the editor import styles from the theme, the appearance of `wide` and `full` alignments would be derived from there, and in the case of a theme that does not provide styles, the alignments would simply look the same as the default alignment.

## Screenshot
![image](https://user-images.githubusercontent.com/19592990/44637494-02eba480-a977-11e8-8032-ddc643218f0f.png)

## See also
- https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#wide-alignment

**Comment by ZebulanStanphill** [comment]
@chrisvanpatten There are really two problems here: a UX one and a conceptual one.

I would have opened 2 separate issues, but in the past I have had issues closed for being too closely related, so I decided to make this issue about the conceptual issue, mentioning the UX issue as one of the things caused by it.

The conceptual issue is that there are 2 alignments that the editor will not let you use unless your theme toggles a flag for it, but the blocks remain in those alignments after you switch back to a theme that does not support the alignments, so the alignments are not truly theme-specific, though the styling is.

But the styling is irrelevant. Why should the editor hide the alignment options if the theme does not explicitly say it supports them? It does not treat the existing alignments this way. It is treating the `wide` and `full` alignments like something from a plugin... but if it is being treated like a feature from a plugin, then why is it in (what will soon be merged into) core?

Gutenberg already does not look like the front-end, and applying theme styles to the editor should make the `wide`/`full` alignments look like they do on the front-end (which could just be the same as the default alignment), not hide the alignments.

The reality is that the `wide` and `full` alignments can not be disabled, so hiding them is misleading and leads to confusing behavior when switching themes.

>Could you also share some screenshots or video of the issue?

I added a screenshot of what a Columns block with wide alignment looks like when using a theme that does not declare support for the `wide` and `full` alignments. Notice the complete lack of alignment controls. Even if the Columns block had other alignments, it would be confusing that once you switch to another alignment, you can not go back. **This is a destructive action as it results in a change that can not easily be reversed except through the <kbd><samp>Undo</samp></kbd> button.**

Now, I know of one cheap solution to the UX issue. You could make the `wide`/`full` alignment options remain visible for blocks that are already using them. But the problem with this is that once you change the alignment for a block, the `wide`/`full` options disappear. This is confusing to users who would expect the alignments to work the same as all the others. Why should those two just disappear once you stop using them?

**Comment by chrisvanpatten** [comment]
There's also some related discussion over in #4747 which I plan to read in the morning 😴

**Comment by designsimply** [comment]
Consolidating to #4342. Note: that issue will get a link back to here automatically and if you want to continue discussing here about that finer points around the columns block, other specifics raised here, and how they related to #4747, that's ok to do here in this issue. Thanks!
