### ISSUE TITLE
Can not load new Editor, Error Failed to load plugin url: https://.../functions/tinymce/langs/vi.js

### ISSUE THREAD

**Issue by mucdong** [WordPress/gutenberg#9369]
**Describe the bug**
After installed and actived the Editor, I couldn't load it
Error: https://.../functions/tinymce/langs/vi.js

**To Reproduce**
1. Installed & Actived
2. Go to Post, edit one post
3. Editor couldn't be loaded fully
4. See error: Error: https://.../functions/tinymce/langs/vi.js

**Comment by designsimply** [comment]
Thank you for reporting here and for including the error! I am not quite sure what is causing the error without a bit more information though. As a basic troubleshooting step, are you able to temporarily turn off all plugins and switch to a default theme such as Twenty Seventeen to see if the problem goes away? If it does, turning each previously active plugin back on and checking for the error will help narrow down the potential source of the problem.

**Comment by saviocamacam** [comment]
Same Problem with language file. 'Failed to load plugin url: http://atlacontexto.github.io/tinymce4-i18n/pt_BR.js'.
