### ISSUE TITLE
Inner Blocks reset to block template in the backend.

### ISSUE THREAD

**Issue by Sephsekla** [WordPress/gutenberg#9375]
Gutenberg 3.6.2

**Describe the bug**
I'm working on a plugin adding Gutenberg blocks with child blocks inside.

The container block has a block template. This works correctly on creating a post, and displays correctly in the frontend.

However editing an existing post resets the block content to the template.

When the block template code is removed everything works as expected.

**To Reproduce**

Block registration code attached below.

(Hopefully not just an obvious mistake in my code.)

[example.txt](https://github.com/WordPress/gutenberg/files/2324613/example.txt)

**Expected behavior**
The content should be loaded as expected in the backend.

**Comment by chrisvanpatten** [comment]
Thanks for the report @Sephsekla! We're tracking this in issue #8109. As this is a duplicate I'll close it here but definitely recommend following over at #8109, and we can reopen later if necessary too.

Cheers!
