### ISSUE TITLE
REST issue when activating Gutenberg on IIS

### ISSUE THREAD

**Issue by caseyctg** [WordPress/gutenberg#9376]
Warning: Attempt to modify property 'data' of non-object in C:\inetpub\SERVER_FOLDER\wp-content\plugins\gutenberg\lib\rest-api.php on line 202

Warning: Attempt to modify property 'data' of non-object in C:\inetpub\SERVER_FOLDER\wp-content\plugins\gutenberg\lib\rest-api.php on line 203

Fatal error: Uncaught Error: Call to a member function get_data() on array in C:\inetpub\SERVER_FOLDER\wp-content\plugins\gutenberg\lib\rest-api.php:223 Stack trace: #0 C:\inetpub\SERVER_FOLDER\wp-includes\class-wp-hook.php(286): gutenberg_add_block_format_to_post_content(Array, Object(WP_Post), Object(WP_REST_Request)) #1 C:\inetpub\SERVER_FOLDER\wp-includes\plugin.php(203): WP_Hook->apply_filters(Array, Array) #2 C:\inetpub\SERVER_FOLDER\wp-includes\rest-api\endpoints\class-wp-rest-posts-controller.php(1609): apply_filters('rest_prepare_po...', Object(WP_REST_Response), Object(WP_Post), Object(WP_REST_Request)) #3 C:\inetpub\SERVER_FOLDER\wp-includes\rest-api\endpoints\class-wp-rest-posts-controller.php(465): WP_REST_Posts_Controller->prepare_item_for_response(Object(WP_Post), Object(WP_REST_Request)) #4 C:\inetpub\SERVER_FOLDER\wp-includes\rest-api\class-wp-rest-server.php(936): WP_REST_Posts_Controller->get_item(Object(WP_REST_Request)) #5 C:\inetpub\SERVER_FOLDER\wp-includes\rest-api.php(390): WP_REST_Server->dispatch(Object(WP_REST_Request)) #6 C:\inetpub\SERVER_FOLDER\w in C:\inetpub\SERVER_FOLDER\wp-content\plugins\gutenberg\lib\rest-api.php on line 223

**Comment by caseyctg** [comment]
This also happens after trying to post.

**Comment by caseyctg** [comment]
Note, pages ARE working with gutenberg. I just can't add posts. I'm wondering if this is an issue with the custom post types in the theme.

**Comment by caseyctg** [comment]
Default theme works, so it must be something within my current theme. closing.

**Comment by caseyctg** [comment]
BTW, removing this filter allowed Gutenberg to function:
add_filter( 'rest_prepare_post', 'get_all_posts', 10, 3 );

**Comment by caseyctg** [comment]
Reopening because this should work still. The fact that my theme uses this filter should not cause Gutenberg to break.

**Comment by caseyctg** [comment]
It seems the issue is the fact that the data is an array and so get_data and get_links do not accept an array.

**Comment by caseyctg** [comment]
Ok, so it seems returning an array in rest_prepare_posts is an issue. This works:

	$data->data['myarr'] = [
		'id'		=> $data->data['id'],
		'date'		=> $data->data['date'],
		'link'     	=> $data->data['link'],
		'title'    	=> $data->data['title']['rendered'],
		'content'	=> $data->data['content']['rendered'],
		'excerpt'	=> $data->data['excerpt']['rendered'],
		'featuredimage' => $data->data['featured_image_url'],
		'authorName'	=> $data->data['authorname'],
		'tags'		=>  $data->data['tags'] 
	];
	
	return $data;

**Comment by caseyctg** [comment]
This accomplished it and allowed Gutenberg to function:

`function get_all_posts( $data, $post, $context ) {
	
	//Featured Image
	$featured_image_id = $data->data['featured_media']; // get featured image id
	$featured_image_url = wp_get_attachment_image_src( $featured_image_id, 'original' ); // get url of the original size
	if( $featured_image_url ) {
		$data->data['featuredimage'] = $featured_image_url[0];
	}else{
		$data->data['featuredimage'] = '';
	}
	
	//tags
	$tags = wp_get_post_tags($post->ID);
    $data->data['tags'] = [];
	$keyCount = 0;
    foreach ($tags as $tag) {
		$data->data['tags'][$keyCount]['id'] = $tag->term_id;
        $data->data['tags'][$keyCount]['tag'] .= $tag->name;
		$data->data['tags'][$keyCount]['slug'] .= $tag->slug;
		$keyCount++;
    }
	
	//author
	$author_name = get_author_name($data->data['author']); 
	$data->data['authorName'] = $author_name;
	
	//flatten out nested objects
	$data->data['title'] = $data->data['title']['rendered'];
	$data->data['content'] = $data->data['content']['rendered'];
	$data->data['excerpt'] = $data->data['excerpt']['rendered'];
		
	//filter out unneeded stuff
	unset($data->data['date_gmt']);
	unset($data->data['guid']);
	unset($data->data['modified']);
	unset($data->data['modified_gmt']);
	unset($data->data['slug']);
	unset($data->data['status']);
	unset($data->data['type']);
	unset($data->data['categories']);
	unset($data->data['_links']);
	unset($data->data['author']);
	unset($data->data['featured_media']);
    unset($data->data['comment_status']);
    unset($data->data['ping_status']);
    unset($data->data['sticky']);
    unset($data->data['template']);
    unset($data->data['format']);
    unset($data->data['meta']);
	
	/*
	this is the needed format:
	[
		'id'		=> $data->data['id'],
		'date'		=> $data->data['date'],
		'link'     	=> $data->data['link'],
		'title'    	=> $data->data['title']['rendered'],
		'content'	=> $data->data['content']['rendered'],
		'excerpt'	=> $data->data['excerpt']['rendered'],
		'featuredimage' => $data->data['featured_image_url'],
		'authorName'	=> $data->data['authorname'],
		'tags'		=>  $data->data['tags'] 
	];
	*/
	return $data;
}`

**Comment by TimothyBJacobs** [comment]
You should not be changing the response format so drastically of core endpoints. This is [not supported](https://developer.wordpress.org/rest-api/extending-the-rest-api/modifying-responses/#important-note-about-changing-responses).

**Comment by caseyctg** [comment]
Note, unset doesn't work on _links. Had to remove them manually. There has to be a better way. 

	$data->remove_link( 'collection' );
    $data->remove_link( 'self' );
    $data->remove_link( 'about' );
    $data->remove_link( 'author' );
    $data->remove_link( 'replies' );
    $data->remove_link( 'version-history' );
    $data->remove_link( 'https://api.w.org/featuredmedia' );
    $data->remove_link( 'https://api.w.org/attachment' );
    $data->remove_link( 'https://api.w.org/term' );
    $data->remove_link( 'curies' );
	$data->remove_link('predecessor-version');

**Comment by caseyctg** [comment]
TimothyBJacobs, what's the proper way to do this? Based on what you're saying, I assume I should be creating a custom route?

**Comment by TimothyBJacobs** [comment]
Yes. You should create a custom route in your own namespace.

**Comment by caseyctg** [comment]
@TimothyBJacobs Ok, thanks. I'll try that route.
