### ISSUE TITLE
Value of array type attribute become undefined on save

### ISSUE THREAD

**Issue by foysalremon** [WordPress/gutenberg#9377]
I am trying to put several element style settings on a single array type attribute and add there control separately. Everything is working fine onChange. And also on frontend I have notice the changes perfectly. But on the backend it's throwing block validation error because of the attribute index value being undefined.

**Comment by Soean** [comment]
Hey @foysalremon,
Do you have a link to your code?

**Comment by youknowriad** [comment]
Your `titlestyle` attribute's default value is an object it's not an array. If you want to use it as an object, you should probably change its type to "object".

I'm closing for now, let me know if it didn't fix your issue.
