### ISSUE TITLE
The editor has encountered an unexpected error - Cannot read property 'rest_base' of undefined

### ISSUE THREAD

**Issue by styledev** [WordPress/gutenberg#9381]
**Describe the bug**
When you create a new page and click [Publish...] for the first time I get an error/modal prompt that states: "The editor has encountered an unexpected error. [Attempt Recovery] [Copy Post Text] [Copy Error]"

The console shows the following error at the same time: 

react-dom.min.82e21c65.js:110 TypeError: Cannot read property 'rest_base' of undefined
    at index.js?ver=1534535888:12
    at r (index.js?ver=1534535888:1)
    at new e (index.js?ver=1534535888:1)
    at yh (react-dom.min.82e21c65.js:97)
    at lg (react-dom.min.82e21c65.js:120)
    at mg (react-dom.min.82e21c65.js:120)
    at gc (react-dom.min.82e21c65.js:127)
    at vb (react-dom.min.82e21c65.js:126)
    at ub (react-dom.min.82e21c65.js:126)
    at wg (react-dom.min.82e21c65.js:137)

If you click [Attempt Recovery] the editor comes back and when you click [Publish...] the page will save. If you then change the page back to a draft, refresh the browser, and click [Publish...] you will get the error again.

TO NOTE: I just realized that if you open up the "Settings" (Shift + CMD + ,) and then click [Publish...] the page published as expected. It seems that the error stems from the Settings panel not being present. Works even if you close the settings then click [Publish...].

**To Reproduce**
1. Go to Pages > Add New
2. Fill in title and add some test content.
3. Click the [Publish...] button
4. See Error
5. Click [Attempt Recovery] button
6 Click [Publish] button
7. Page saves
8. Click the [x] next to "Published" in top right.
9. Click [Switch to Draft]
10. Reload page
11. Go to Step #3 above.

**Expected behavior**
The expected behavior is for the page to be published and a green confirmation notice that says "Post published! View post"

**Screenshots**
Error: https://www.dropbox.com/s/coy9ekr51vciiiz/20180827-wordpress-4.9.8-gutenberg-v3.6.2-unexpected-error.png?dl=0

![hjiizv2g](https://user-images.githubusercontent.com/1119271/44691180-e739da00-aa1a-11e8-8e4f-b95a7972d7ac.png)

**Desktop:**
 - OS: MacOS High Sierra
 - Browser(s): Chrome 68.0.3440.106 (Official Build) (64-bit) | Safari Version 11.1.2 (13605.3.8) | FireFox 61.0.2 (64-bit)

**Additional context**
WordPress v. 4.9.8
Gutenberg v. 3.6.2
Safari and Firefox seem to state slightly different console error text.

**Comment by designsimply** [comment]
Thank you for including clear details and a screenshot!

I am able to run Gutenberg 3.6.2 without error, so I believe the problem in your case may be due to a conflict with server settings or possibly a conflict with a plugin.

Are you able to temporarily turn off all other plugins and check to see if the error still happens? This will help rule out a plugin conflict.

I also noticed a similar-sounding error in #8802 where the problem turned out to be related to custom rewrite rules. Do you have anything like that setup on your web server which could be causing the trouble in this case?

**Comment by styledev** [comment]
@designsimply I should have stated that I am not running any other plugins and using the latest Twenty Seventeen theme.

The only other thing to note is I am running WordPress in it's own directory /wp/ so admin sits at /wp/wp-admin. Though, I just did a fresh install of Wordpress 4.9.8 on it's own with only the Gutenberg plugin installed and activated and I am getting the same error.

I made a recording of the issue > https://www.dropbox.com/s/so8hn1nbr3e18ue/Gutenberg%20Error.mov?dl=0

**Comment by youknowriad** [comment]
Looks like something related to the REST API, something (a plugin, a firewall, Cloudflare) is probably touching the REST API in the wrong way. I can't say more than that.

**Comment by youknowriad** [comment]
Maybe a server config but I don't know. It would be good to find the source of this kind of issues though. Other persons might experience it and think Gutenberg is completely broken while it's not :)

Maybe you can try to dump the `$preload_data` in the `client-assets.php` file to see if there's anything wrong in the REST API responses?

**Comment by styledev** [comment]
@youknowriad  Here is a dump of $preload_data > https://gist.github.com/styledev/fccd3f996eec7b2033f8f541baacf8f0

Honestly, it looks like the culprit for all of this is that the settings sidebar does not exist if you load the page when the user has set the state of it to hidden. The initial "Add Page" load on a fresh install has the Settings sidebar shown and everything works fine. If you load in with out the Settings open then this issue occurs but if you click the Settings button first and then again to close it the issue does not happen.

**Comment by youknowriad** [comment]
The preload data looks ok. 

You're saying the issue happens when you open or close the sidebar. Can you monitor the network requests triggered when this happens and paste their responses here. (Essentially requests to `/wp/v2/types/*` and `/wp/v2/taxonomies/*`

**Comment by styledev** [comment]
@youknowriad Have you watched the video I attached up above of the issue? 

Reproduce Error
- Fresh install click on Add New under Pages.
- Settings sidebar is shown.
- Click Settings cog icon to hide.
- Refresh page and Settings sidebar is not shown
- Add title and content click Publish... and this is where I get the error.

Error does not happen if you do:
- Fresh install click on Add New under Pages.
- Settings sidebar is shown.
- Add title and content click Publish...
- Page publishes

Error also does not happen if you do:
- Fresh install click on Add New under Pages.
- Settings sidebar is shown.
- Click Settings cog icon to hide.
- Refresh page and Settings sidebar is not shown
- Add title and content click Settings cog to show Settings Sidebar
- Click Settings cog to hide sidebar (optional)
- Click Publish... and the page is published.

**Comment by youknowriad** [comment]
Yes, but I can't reproduce personally.

**Comment by RickorDD** [comment]
here is the same. 
I tested with a shortcode.
-Test as Title
-copy "[date]" in Write your story
-Publish
-> this Error

<img width="758" alt="bildschirmfoto 2018-08-28 um 20 47 54" src="https://user-images.githubusercontent.com/6922544/44743798-c0a39e00-ab03-11e8-9955-d10254a218d5.png">

MacOS 10.13.6
Chrome  68.0.3440.106

**Comment by RickorDD** [comment]
i tested again without HTTPS and without plugins.
This is the SQL Query. Why is a "draft"?

<img width="929" alt="bildschirmfoto 2018-08-29 um 20 25 49" src="https://user-images.githubusercontent.com/6922544/44807472-f7dc8280-abc9-11e8-8773-56815c38b55f.png">

**Comment by RickorDD** [comment]
I found the Bug.
The Categories is not select. When i selected the Categories in Checkbox then not the error.

<img width="1016" alt="bildschirmfoto 2018-08-29 um 20 45 42" src="https://user-images.githubusercontent.com/6922544/44808481-a4b7ff00-abcc-11e8-8d61-1b81ff56d195.png">

**Comment by youknowriad** [comment]
This is just a warning, the real issue is the `rest_base` error. It seems like we're trying to access this property on a taxonomy or CPT object that's missing for some reason.

**Comment by styledev** [comment]
@youknowriad Yeah, the issue has always been trying to access "rest_base" on an object that is undefined. If you have the Settings sidebar this error does not happen so it goes to reason that the object that "rest_base" is being called on is only defined if the Settings area has been initiated.

Please also note, while I am a programmer and have been learning React I have not been digging into the Gutenberg core code. I am just trying to support you on the error side. I hope everyone now has enough information. It is curious though that you can't recreate the error when I have no problem doing so both locally with a fresh WP and Gutenberg instance and on a production site.

**Comment by youknowriad** [comment]
> Please also note, while I am a programmer and have been learning React I have not been digging into the Gutenberg core code. I am just trying to support you on the error side. I hope everyone now has enough information.

I know and you're already helping a lot, I can now try "to guess" what might break. I'll plan to take a deeper look in the code soon and see if there's anything suspicious 🤷‍♂️ .

**Comment by RickorDD** [comment]
i tested again. I have changed the permalinks to "plain" and now is not a error.
But wenn i change to "Day and name" and create a new post the a blank screen.
I remember that there was a bug with similar phenomenon earlier.

<img width="636" alt="bildschirmfoto 2018-08-31 um 12 36 09" src="https://user-images.githubusercontent.com/6922544/44908087-79dbc100-ad1a-11e8-896c-2b5ece160be3.png">

**Comment by styledev** [comment]
@RickorDD Changing my permalink structure to "Plain" did not solve this issue for me.

**Comment by Fathurhoho** [comment]
I'm also experiencing same issue, Previously it was fine and I have made 2 articles with guttenberg. It seems getting conflict with Yoast SEO plugin, it works fine when i disabled Yoast SEO plugin. 

1. Screenshot: ![2018-09-02_15h00_36](https://user-images.githubusercontent.com/17008473/44953642-15a73180-aec1-11e8-8501-27ba8d8d3b41.png)
2. Video: https://telegra.ph/file/b7641442669fff5e85022.mp4
3. Log: https://gist.github.com/Fathurhoho/8bb35c1ff9b629855dcb2b4cf776e639

This happens when 'add new' and 'edit' any post.
- Wordpress version: 4.9.8
- Running in localhost
- Yoast SEO plugin version: 8.1

**Comment by latereverafter** [comment]
Hello I am having an error with Gutenberg.  When I create a new post and add a block it says "The editor has encountered an unexpected error."  Here is a copy of the code.  Any suggestions on how to fix this?  
TypeError: Object(...) is not a function
    at ve (https://www.latereverafter.com/wp-includes/js/dist/blocks.min.js?ver=6.0.3:2:83680)
    at https://www.latereverafter.com/wp-includes/js/dist/blocks.min.js?ver=6.0.3:2:83120
    at i (https://www.latereverafter.com/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.11:6:91)
    at An.filter (https://www.latereverafter.com/wp-includes/js/dist/vendor/lodash.min.js?ver=4.17.11:99:338)
    at _e (https://www.latereverafter.com/wp-includes/js/dist/blocks.min.js?ver=6.0.3:2:83097)
    at we (https://www.latereverafter.com/wp-includes/js/dist/blocks.min.js?ver=6.0.3:2:83557)
    at t.value (https://www.latereverafter.com/wp-includes/js/dist/editor.min.js?ver=9.0.4:55:266041)
    at Fd (https://www.latereverafter.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:92:367)
    at Mf (https://www.latereverafter.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:92:160)
    at ph (https://www.latereverafter.com/wp-includes/js/dist/vendor/react-dom.min.js?ver=16.6.3:98:474)

**Comment by designsimply** [comment]
@styledev I tried testing this again today using a test site created at https://jurassic.ninja/ and could not see the error happen in my testing. I used these steps from one of your earlier comments:

<blockquote>Reproduce Error

* Fresh install click on Add New under Pages.
* Settings sidebar is shown.
* Click Settings cog icon to hide.
* Refresh page and Settings sidebar is not shown
* Add title and content click Publish... and this is where I get the error.</blockquote>

I ran my test using WordPress 5.0.3 and no active plugins and I used Safari 12.0.3 on macOS 10.13.6.

![9381-30s](https://user-images.githubusercontent.com/1119271/52669583-a30c9a00-2ed3-11e9-8f51-64b3ff0f3296.gif)

Are you still seeing the "Cannot read property 'rest_base' of undefined" error after updating to the latest version of WordPress (5.0.3 at the time of this writing)?

Since you mentioned that you are not running any other plugins and that you used the latest Twenty Seventeen theme at the time of testing, I feel in that case it has got to be related to something in your server config…  🕵️‍♀️ are you able to try testing using https://jurassic.ninja/ as a check? Can you think of anything related to your server config or firewall that could have been blocking the REST API inadvertently?

**Comment by designsimply** [comment]
@Fathurhoho thanks for chiming in! I see that the error from your video and screenshot is different than the one @styledev mentioned.

> TypeError: Cannot read property 'getCollectionByRoute" of undefined

Just below your error, the `wp-seo-post-scraper-810.min.js?ver=8.1:1` is mentioned, and that indicates that the problem in your case is potentially a conflict with the Yoast SEO plugin and I also saw that it was reported at https://github.com/Yoast/wordpress-seo/issues/10867 and is now closed so I think that updating to the latest version of Yoast SEO should resolve the problem in your case!

**Comment by designsimply** [comment]
@latereverafter there's not quite enough information to go on from the error you posted. 

> TypeError: Object(...) is not a function

First, can you update to the latest version of WordPress and also make sure that all of your plugins have been updated to their latest versions? If you're still having trouble after that, a good place to start will be to temporarily deactivate all active plugins and try the test again. If you're still seeing problems, please post all of the relevant details you've tried, note the latest version of WordPress you've tested with, and if possible include a copy/paste or a screenshot of the full error from the console panel in your browser's web developer tools to https://wordpress.org/support/forum/how-to-and-troubleshooting/ If you are not sure how to get the information needed for a bug report, the support forums are the very best place to ask for help with troubleshooting steps for that. Thank you!

**Comment by styledev** [comment]
Closing as this error is not present in the core version of Wordpress 5.

**Comment by MWalid** [comment]
I have the same issue with gutenberg. It's not caused by yoast since it's been deactivated.

Leaving to classic editor for now!

**Comment by maharzan** [comment]
Similar thing was happening to me with WordPress 5.9 RC3. and changing permalinks to default helped. Tracking back to the issue, I found out that nginx.conf had this line

    location / {
        try_files $uri $uri/ /index.php?$uri&args;
    }
    
The $ was missing in args.. after I added $, the issue is resolved and there is no longer react dom error.

    location / {
        try_files $uri $uri/ /index.php?$uri&$args;
    }
