### ISSUE TITLE
Reusable block naming field hidden on long block.

### ISSUE THREAD

**Issue by davidwolfpaw** [WordPress/gutenberg#9384]
**Describe the bug**
When creating a very long block, for instance one that holds general HTML markup, it can take up more height than the browser window. Since the name field for creating reusable blocks is located at the bottom of the block, it can be easy to miss.

**To Reproduce**
1. Create a very long block. My example is an HTML block with indented and spaced HTML causing the height of the block to be taller than the height of my browser.
2. Click the block settings then click "Add to Reusable Blocks".
3. Note that the name field for the reusable block is off the view of the screen and no visual indicator is given that the name field is below.

**Potential Solutions**
I have a few potential solutions in mind:
1. Position the name field at the top of the block, nearer to the button that activates that field.
2. Create a visual indicator of some sort that notifies the user that a setting is located at the bottom of the block.
3. Reposition the browser via scroll at the bottom of the block, to indicate that you have moved to a field that requires attention.

**Screenshots**
These screenshots are some random CSS as an example of this action on long

![An HTML block with general CSS code](https://user-images.githubusercontent.com/1971070/44696490-c9ce3580-aa45-11e8-914e-f38b2be8f1ad.png)

![The block settings overlaid on the HTML block](https://user-images.githubusercontent.com/1971070/44696491-c9ce3580-aa45-11e8-99c2-93306ec9383a.png)

![The location of the reusable block name field. Note the amount of scroll required.](https://user-images.githubusercontent.com/1971070/44696492-c9ce3580-aa45-11e8-9e3b-a73846c0f9e8.png)

**Additional context**
- WordPress v4.9.8
- Gutenberg v3.6.2

**Comment by noisysocks** [comment]
The name field is at the top of the reusable block now.
