### ISSUE TITLE
Allow overriding the templateLock of existing blocks

### ISSUE THREAD

**Issue by haszari** [WordPress/gutenberg#9386]
**Is your feature request related to a problem? Please describe.**
We're using [templates](https://wordpress.org/gutenberg/handbook/templates/) to implement reusable chunks of layout for landing pages. For example, a call-to-action header block with two columns containing heading, text, an image, a button, and some custom styling.

Templates are really powerful and convenient for this purpose, but there are quirks that are causing problems for us:

- It's hard to navigate nested blocks. In particular, it's very easy to add new blocks inside another block's outer container (and it's conversely hard to add things to the top-level page).
- When containers allow editing, a placeholder `core/paragraph` block is added, which is not needed for our layouts, and causes issues on the front end.

To work around these issues, we're looking at locking all our template blocks for now using `templateLock`. This will reduce the flexibility of the blocks, but will make things much simpler and more predictable for our authors.

This works well most of the time. However, when a template contains columns, [the columns block overrides `templateLock` locally](https://github.com/WordPress/gutenberg/blob/6c846f8819e1e136215b4e079618695aab24f6d3/packages/block-library/src/columns/column.js#L21). This is frustrating, because the extra placeholder paragraph appears again, breaking the layout, and allowing accidental insertion of a template within a template!

**Describe the solution you'd like**
Since we are instantiating the columns blocks (and their children) directly within our template, it seems appropriate that we could instruct them to not allow editing. If `core/columns` had a `forceLock` attribute, which inhibited the override, we could set this as needed in our templates.

**Describe alternatives you've considered**
Would love to hear other ideas for how to work around this. Here are some ideas:

- Implement our own custom columns block, and not use `core/columns` block.
- Implement our columns as markup directly in our template blocks, and use multiple template/InnerBlocks. (Is this possible?)

**Comment by haszari** [comment]
This issue [_More versatile templateLock_](https://github.com/WordPress/gutenberg/issues/8112) could potentially help with this, though the scope there is much broader.

**Comment by designsimply** [comment]
Would #8589 work as a solution to problems you described where empty placeholder blocks are causing layout issues in this case?

**Comment by haszari** [comment]
@designsimply I'm not sure! When #8589 converges on a solution we can see how it works for us.

**Comment by youknowriad** [comment]
I think it should be explored whether we could override the "templateLock" of existing container blocks, the same we're able to do it for the "template" content.

**Comment by t-hamano** [comment]
At least for Columns/Column blocks, `templateLock` is added as an attribute and should inherit the parent's `templateLock` setting.

- #49132
- #42677

In the markup below, Columns/Column blocks exist within a group block that has `templateLock:true` set.

```html
<!-- wp:group {"templateLock": "all","layout":{"type":"constrained"}} -->
<div class="wp-block-group">
  <!-- wp:columns -->
  <div class="wp-block-columns">
    <!-- wp:column -->
    <div class="wp-block-column"></div>
    <!-- /wp:column -->
    <!-- wp:column -->
    <div class="wp-block-column"></div>
    <!-- /wp:column -->
  </div>
  <!-- /wp:columns -->
</div>
<!-- /wp:group -->
```

![template-lock](https://github.com/WordPress/gutenberg/assets/54422211/ef5ee162-9a07-4f2d-998b-f54220c00fb5)

You can see that the Columns/Column blocks inherit the Group block's `templateLock` and are locked. Furthermore, you can also roverride this lock for specific columns only.

As far as I know, there is no container block that supports `templateLock` that does not respect the parent's `templateLock` setting.

Therefore, I would like to close this issue, but if there is anything I have missed, please comment.
