### ISSUE TITLE
Block API docs have malformatted link

### ISSUE THREAD

**Issue by benlk** [WordPress/gutenberg#9387]
**Describe the bug**

A 404 in the Block API docs.

**To Reproduce**

On https://wordpress.org/gutenberg/handbook/block-api/#supports-optional, under "supports (optional)", there is the following text:

> alignWide (default true): Gutenberg allows to enable wide alignment for your theme. To disable this behavior for a single block, set this flag to false.

The text "wide alignment" has a link to the URL `https://wordpress.org/gutenberg/handbook/extensibility/theme-support.md#wide-alignment/`, which is a 404. 

This link is defined in `gutenberg/docs/block-api.md`, which was most-recently edited at https://github.com/WordPress/gutenberg/commit/f6fd8e57ba217d1fad9d9f8906478e6800b826cf, and in which the affected link is written thusly:

```md
- `alignWide` (default `true`): Gutenberg allows to enable [wide alignment](../docs/extensibility/theme-support.md#wide-alignment) for your theme. To disable this behavior for a single block, set this flag to `false`.
```

**Expected behavior**
The correct link would appear to be `https://wordpress.org/gutenberg/handbook/extensibility/theme-support/#wide-alignment` , without the `.md`

**Comment by benlk** [comment]
I'm not sure of the details of how internal links work in this build system, but removing the `.md` from the Markdown link text might fix this?

**Comment by ZebulanStanphill** [comment]
Relevant: #6126 and #6161.

It looks like the docs parser for the Gutenberg Handbook site does not account for anchors in links, so it is not finding the `.md` extension to remove it:

https://meta.trac.wordpress.org/changeset/7104

@pento

**Comment by designsimply** [comment]
Tested and confirmed that `[wide alignment](../docs/extensibility/theme-support.md#wide-alignment)` results in a broken link to "wide alignment" at https://wordpress.org/gutenberg/handbook/block-api/#supports-optional

Moved to https://meta.trac.wordpress.org/ticket/3780
