### ISSUE TITLE
Issue with template options

### ISSUE THREAD

**Issue by megateg** [WordPress/gutenberg#9391]
When i activate the gutenberg plugin, then in page setting the template options are disappear.

**Comment by youknowriad** [comment]
<img width="281" alt="screen shot 2018-11-26 at 11 37 05" src="https://user-images.githubusercontent.com/272444/49009006-a3688500-f16f-11e8-86c3-fe7edaae57f0.png">

I do see the template selector using a custom theme. Closing as WFM.
