### ISSUE TITLE
Docs: overlapping content on 'Outreach'

### ISSUE THREAD

**Issue by DannyCooper** [WordPress/gutenberg#9393]
https://wordpress.org/gutenberg/handbook/outreach/

Browser: Chrome on OSX.

The 'East Bay WP...' seems to be causing problems.

![image](https://user-images.githubusercontent.com/152804/44710984-43e1d700-aaa5-11e8-86e6-c0d3a1f253ea.png)

**Comment by DannyCooper** [comment]
The problem seems to be the absolute positioning on the .wp-embedded-content

**Comment by tofumatt** [comment]
I appreciate this is an issue with the docs and I don't mean to be unhelpful saying this: unfortunately I don't think this is a valid issue for the Gutenberg repo as the code/styles causing this are outside the repo/our control. As far as I know the styles for this are all on the WordPress.org handbook, so this may need to be filed with the WordPress.org… Trac I'm guessing?

At any rate we can't fix this issue in this repo (right?) so I'm going to close this, but this is valid. Just not for this repo. Thanks/sorry! 😅
