### ISSUE TITLE
Create TinyMCE prototype view

### ISSUE THREAD

**Issue by mtias** [WordPress/gutenberg#94]
Let's set up a demo for tinymce only improvements in https://wordpress.github.io/gutenberg/tinymce

It should be a single text paragraph so we can focus on the link-boundary improvements and other formatting ideas.

**Comment by timmyc** [comment]
So to clarify - this involves taking the current UI prototype, and inserting a TinyMCE paragraph within a block?

**Comment by mtias** [comment]
No, I was thinking just a new html with a paragraph and embed tinymce to manage it, without any of the block stuff.
