### ISSUE TITLE
Button Block: Cannot Move Button with Alignment Applied

### ISSUE THREAD

**Issue by jakerambo** [WordPress/gutenberg#9401]
**Describe the bug**
Button cannot be moved with alignment options applied. You must remove alignment to move button then reapply alignment option. The add new block button is overlapping the up and down arrows.  Very confusing behavior. 

**To Reproduce**
Create Button block with other blocks of content in editor.
Apply alignment. 
Try to move button block up or down.

**Expected behavior**
Options to move button block up or down should be usable when block is in focus.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser chrome
 - Version  68.0.3440.106 

**Additional context**
gutenberg: 3.6.2

**Comment by jakerambo** [comment]
Center is fine. I cannot move it on left or right on Chrome 68.0.3440.106 or firefox. It is very difiicult to discern but in your gif there is a moment where you where moving down and it moved the text not the button. It is related. I think the issue here is that the floating of the button is causing issues with the move controls being overlapped by other controls. So that instead of being able to move the button block it moves the text block. Also if you add the button to the the very bottom and apply left or right alignment the "Add New Block" button covers the move arrows.

**Comment by ellatrix** [comment]
<img width="564" alt="Screenshot 2019-06-18 at 13 47 53" src="https://user-images.githubusercontent.com/4710635/59679653-b1dfc200-91cf-11e9-8b19-e32741f3a500.png">

I'm seeing the buttons appear fine now in the latest Gutenberg release.

**Comment by jayendrasinhrajput** [comment]
this option was not available to aligned button on the centre
