### ISSUE TITLE
TinyMCE

### ISSUE THREAD

**Issue by LowSpirit79** [WordPress/gutenberg#9406]
hello,
With Gutenberg I can't use TinyMCE anymore?

OS: 10.13.06
chrome: 68.0.3440.106
Gutenberg 3.6.2

**Comment by designsimply** [comment]
There are two general ways to use TinyMCE with Gutenberg:

1. Use a classic block—the classic block is TinyMCE.
1. Use the [Classic Editor](https://wordpress.org/plugins/classic-editor/) plugin.

If you were referring to using TinyMCE another way such as in development, let me know the specifics and I can try to help get a more detailed answer for you.
