### ISSUE TITLE
Right clicking within a table cell causes page to crash

### ISSUE THREAD

**Issue by mapk** [WordPress/gutenberg#9409]
**Describe the bug**
Right clicking within a table block causes page to crash. I'm using Gutenberg 3.6.2.

**To Reproduce**
1. Create a table block
2. Add some text to a cell
3. Right click on that cell

**Expected behavior**
I expected the page not to crash.

**Screenshots**
![snap](https://user-images.githubusercontent.com/617986/44744662-7fd36700-aaba-11e8-9159-a41bf51254d5.gif)

**Desktop (please complete the following information):**
 - OS: OSX High Sierra
 - Browser Chrome
 - Version 68.0.3

**Comment by talldan** [comment]
I'm unable to reproduce this @mapk - are there any other steps required to reproduce?

**Comment by brandonpayton** [comment]
I'm able to reproduce this reliably. Over repeated tests, I've only been able to reproduce this when right clicking in the last cell of the last row. The row count doesn't seem to matter.

![table-right-click-crash](https://user-images.githubusercontent.com/530877/46125037-20ad6300-c1dc-11e8-83c1-d49733516c5b.gif)

**Comment by brandonpayton** [comment]
I was able to reproduce with 3.6.2 but realized I hadn't tested with `master`. I'm not able to reproduce on `master`.

Let's close for now and reopen if the issue resurfaces.
