### ISSUE TITLE
Why is the Categories block rendered inside a div, while other similar blocks are not?

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9411]
During the course of the [Block Audit](
https://github.com/WordPress/gutenberg/projects/19#card-12517154), I noticed that the Categories block is rendered inside of a container div:

```
<!-- Categories Block -->
<div class="wp-block-categories wp-block-categories-list aligncenter">
  <ul>
    <li class="cat-item cat-item-1"><a href="#">Category</a></li>
    <li class="cat-item cat-item-2"><a href="#">Category</a></li>
    <li class="cat-item cat-item-3"><a href="#">Category</a></li>
  </ul>
</div>
```

This is at odds with the way the Latest Posts and Archives posts are handled. Those also render simple `ul` elements, but they have no outer `div` wrapper:

```
<!-- Latest Posts Block -->
<ul class="wp-block-latest-posts">
  <li><a href="#">Blog Post 1</a></li>
  <li><a href="#">Blog Post 2</a></li>
  <li><a href="#">Blog Post 3</a></li>
</ul>

<!-- Archives Block -->
<ul class="wp-block-archives alignnone">
  <li><a href="#">August 2018</a></li>
  <li><a href="#">July 2018</a></li>
  <li><a href="#">June 2018</a></li>
</ul>
```

Is there a reason for this inconsistency? (If not, I suggest we align these one way or another.)

**Comment by mtias** [comment]
@kjellr this seems like an oversight on the categories case. Would you mind updating it?
