### ISSUE TITLE
Unclickable Leave dialogue

### ISSUE THREAD

**Issue by unfamousfly** [WordPress/gutenberg#9415]
**Describe the bug**
I entered a post to grab a copy of a shortcode then went to close it again. The Leave /save dialogue opened very quickly - too fast to actually do anything with and it became impossible to get out the post or even simply close the browser tab.
**To Reproduce**
Steps to reproduce the behaviour:
1. Open an existing post
2. Copy some code ( in my case a shortcode)
3. Return to All Posts link to open a post I wanted to add the shortcode to
4. Couldn't do it as Leave/Save dialogue kept flashing up but was too fast to even use.

PS. I got out it eventually by hitting the enter key as soon as I clicked the tab close link and the dialogue flashed- took a few goes by I got there.

**Expected behaviour**
I would expect to simply be able to leave the page or even close the browser tab

**Screenshots**
screencap video of issue
https://www.dropbox.com/s/3q2ttkcqf4yy7wo/2018-08-28_21-16-53.mp4?dl=0

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Additional context**
- version 3.6.2

**Comment by designsimply** [comment]
Thank you for the report! I'm adding a screenshot from the video you provided for reference and noting that I'm adding the `Needs Testing` label too so we can loop back around for some detailed testing.

![screen shot 2018-08-28 at tue aug 28 6 42 04 pm](https://user-images.githubusercontent.com/1119271/44758566-6f3ee300-aaf2-11e8-9f6f-f408ba1797cc.png)

**Comment by jorgefilipecosta** [comment]
Hi @unfamousfly, in the last version of Gutenberg I'm not being able to reproduce this problem. I think the bug maybe have been fixed as part of other changes if the bug is still happening in your tests with the last version feel free to reopen the issue.
