### ISSUE TITLE
Photos don't resize correctly

### ISSUE THREAD

**Issue by natashauspensky** [WordPress/gutenberg#9417]
Selecting a large or full size photo doesn't yield a full-width image as it does in classic. Also, after resizing an image in the Media library (new pop up), the image does not remain resized in the library.
![screen shot 2018-08-28 at 5 08 57 pm](https://user-images.githubusercontent.com/42789381/44757676-1f0d5400-aae5-11e8-9395-f748f380be07.png)

Screenshot attached.

**Comment by designsimply** [comment]
Are you able to note your theme and version as well as what you have listed for large on your Settings > Media page?

I think the first issue might be #9207 and the second issue might be #9404. I'm closing this issue so we can consolidate to the existing ones in case that's right and we can re-open if additional detail is added to show it's separate from the previous issues.

It is also worth noting that way images are inserted is not exactly the same compared to the past. If the result looks different in your theme, it's possible the theme may need to be adjusted but I can't say for sure without more information such as knowing what theme you are using and what you expected the full-width image to look like compared to what it looks like now. 

Thank you for reporting this!
