### ISSUE TITLE
Form-token-field generated from a custom taxonomy doesn't display proper labels

### ISSUE THREAD

**Issue by stockHuman** [WordPress/gutenberg#9420]
**Describe the bug**
Form inputs generated by custom taxonomies don't reflect the labels set in `register_taxonomy()`, instead defaulting to 'Add new Term" in the placeholder. Additionally, the hover pop-up when one goes to remove a term only describes it as a "Term" (ie: "Remove Term" instead of what's defined in the `labels` array).

**To Reproduce**
1. Register a REST-queryable taxonomy with custom labels
2. view the page/post/CPT that taxonomy is enabled for and go add a new term
3. See the placeholder text does not reflect the labels set in the taxonomy

**Expected behavior**
One would expect to see the placeholder prop passed to the form so that "Add new Term" becomes, say, "Add a Byline".
![screenshot](https://user-images.githubusercontent.com/13852458/44763625-23a02f80-ab1a-11e8-8267-bc6f2b4263be.png)

**Env:**
 - OS: Windows 10
 - Browser: Firefox (and others?)
 - Version: 61.0.2
 - Gutenberg: 3.6.2

**Comment by youknowriad** [comment]
Related #8448

**Comment by youknowriad** [comment]
I think this is fixed by #10962
