### ISSUE TITLE
Editor: Use-once validation and top-level error handler display no action options

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#9431]
Regression introduced in #7741

With the removal of the `actions` prop in #7741, both the ErrorBoundary component and "use-once" validation warnings display no options.

v3.6|master
---|---
![image](https://user-images.githubusercontent.com/1779930/44788489-2de91a80-ab68-11e8-9f14-9d0fdcb5e5f0.png)|![image](https://user-images.githubusercontent.com/1779930/44788497-35102880-ab68-11e8-878e-e7abb2c7bc96.png)

**Steps to reproduce:**

1. Navigate to Posts > Add New
2. Switch to Code Editor
3. Paste text:

```
<!-- wp:more -->
<!--more-->
<!-- /wp:more -->

<!-- wp:more -->
<!--more-->
<!-- /wp:more -->
```

4. Switch to Visual Editor

Actual: Block warning with options
Expected: Block warning without options

Same applies for `ErrorBoundary`:

v3.6|master
---|---
![image](https://user-images.githubusercontent.com/1779930/44789071-ad2b1e00-ab69-11e8-93e9-66875fa180bc.png)|![image](https://user-images.githubusercontent.com/1779930/44789077-b4522c00-ab69-11e8-8fbd-41b551735115.png)

**Steps to reproduce:**

Repeat steps from #9303

**Comment by aduth** [comment]
High-level observations:

- We can't make one-off breaking changes to components which are part of a public API. They are subject to our [deprecation policy](https://github.com/WordPress/gutenberg/blob/master/docs/reference/deprecated.md).
- Most components are purpose-built to be used in multiple contexts. Changes to a component should be verified against _all_ usage of that component.

**Comment by johngodley** [comment]
Sorry. I thought I'd verified all usage. I've not seen 'use once' before but the ErrorBoundary I really should have checked.

I'll add some tests to catch these.

**Comment by aduth** [comment]
I'd recommend not relying on familiarity for validating against existing usage. For example, I discovered the two usages not because of my familiarity with them, but because I did a ["Find in Files"](http://docs.sublimetext.info/en/latest/search_and_replace/search_and_replace_files.html) search for the term "<Warning" and checked whether they were using the prop.

This isn't always 100% (e.g. wouldn't catch if imported as a different name), but is a good start.

**Comment by nosolosw** [comment]
FWIW, I was testing https://github.com/WordPress/gutenberg/issues/9303 and saw this issue mentioning it. Not sure if https://github.com/WordPress/gutenberg/pull/9435 was supposed to bind the error within the columns block, but it doesn't: the whole editor breaks. Thought it'd worth mentioning it. I'm looking that over.

**Comment by nosolosw** [comment]
John helped me to understand this: the `BlockListBlock` has a `BlockCrashBoundary` that handles a block crash, anything outside of that will trigger the editor to crash. I've traced the cause for https://github.com/WordPress/gutenberg/issues/9303 to the `BlockMover` component which is outside the `BlockCrashBoundary`, so it seems unrelated to this issue.
