### ISSUE TITLE
Multiple time tagName not working in Custom block

### ISSUE THREAD

**Issue by nitishkaila** [WordPress/gutenberg#9432]
**Describe the bug**
The Gutenberg Custom block doesn't work correctly when we use same **tagName** multiple time for an element. The problem will come when we update the post and than after refresh the post editor.

**Error:** This block has been modified externally.

It was working fine if we enter same content in the same **tagName** elements.

Example code:
```
el(
                        'div', { className: 'aid three-calls-item', style: {backgroundColor: attributes.backgroundColor}},
                        el( RichText, {
                            tagName: 'h3',
                            className: props.className,
                            placeholder: 'Write column title',
                            value: attributes.title1,
                            onChange: function( value ) {
                                props.setAttributes( { title1: value } );
                            }
                        }),
                        el( RichText, {
                            tagName: 'p',
                            className: props.className,
                            value: attributes.content1,
                            onChange: function ( value ) {
                                props.setAttributes( { content1: value });
                            }
                        })
                    ),
                    el(
                        'div', { className: 'cheap three-calls-item', style: {backgroundColor: attributes.backgroundColor } },
                        el( RichText, {
                            tagName: 'h3',
                            className: props.className,
                            placeholder: 'Write column title',
                            value: attributes.title2,
                            onChange: function( value ) {
                                props.setAttributes( { title2: value } );
                            }
                        }),
                        el( RichText, {
                            tagName: 'p',
                            className: props.className,
                            value: attributes.content2,
                            onChange: function ( value ) {
                                props.setAttributes( { content2: value });
                            }
                        })
                    ),
```

**Comment by youknowriad** [comment]
Would you mind sharing your "save" function declaration and the "attributes" definition as well?

Note that `tagName` should not correspond to an inline element (`span`, `cite, `a`, ...), this breaks because TinyMCE doesn't support it.

**Comment by nitishkaila** [comment]
Thanks, @youknowriad attending ticket.

Here is a simple example code.
`
var el = wp.element.createElement,
    registerBlockType = wp.blocks.registerBlockType,
    RichText = wp.editor.RichText;

registerBlockType( 'md-custom-block/columns-block', {
    title: 'Custom Block',
    icon: 'universal-access-alt',
    category: 'layout',
    attributes: {
        content1: {
            type: 'array',
            source: 'children',
            selector: 'p'
        },
        content2: {
            type: 'array',
            source: 'children',
            selector: 'p'
        }
    },
    edit: function( props ) {
        var attributes = props.attributes;

        function onChangeContentFirst( newContent ) {
            props.setAttributes( { content1: newContent } );
        }

        function onChangeContentSecond( value ) {
            props.setAttributes( { content2: value } );
        }

        return (
            el( 'div', { className: 'custom-element'},
                el(
                    RichText,
                    {
                        tagName: 'p',
                        className: "kaila",
                        onChange: onChangeContentFirst,
                        value: attributes.content1
                    }
                ),
                el(
                    RichText,
                    {
                        tagName: 'p',
                        className: "nitish",
                        onChange: onChangeContentSecond,
                        value: attributes.content2
                    }
                )
            )
        )
    },
    save: function( props ) {
        var attributes = props.attributes;
        return(
            el( 'div', { className: 'custom-element'},
                el( RichText.Content,
                    {
                        tagName: 'p',
                        className: props.className,
                        value: attributes.content1
                    }
                ),
                el( RichText.Content,
                    {
                        tagName: 'p',
                        className: props.className,
                        value: attributes.content2
                    }
                )
            )
        )
    }
} );
 `

**Comment by youknowriad** [comment]
The problem here is the way you define the attributes:

```
content1: {
type: 'array',
source: 'children',
selector: 'p'
},
```

Both attributes are parsed from the selector "p" which means both will probably contain the value of the first paragraph and not the second which will cause the output of the "save" function before refreshing different from the one after parsing.

I'd suggest you update the "selector" to be more specific (by adding classNames to your paragraphs for instance).

I hope this helps, I'm closing let me know if it fixes the issue for you.
