### ISSUE TITLE
Images Not Following Size Constraints

### ISSUE THREAD

**Issue by Jaden-Drury** [WordPress/gutenberg#9436]
**Describe the bug**
Some images when set to full don't follow the image resizing buttons in the post editor. When selecting a size between 25, 50, 75, and 100% the image will not change in size, the image can be modified in size by directly changing the pixel size however proportional sizing is lost in this case. Images that have this issue also appear on the page as taking up the full width of the page or at the very least expanding far outside of the post content area. Other images that are set to full size but don't have an issue scaling don't have this issue, even if the image uploaded was larger than the one that is affected by the scaling problem.

**To Reproduce**
1. Go to Create Post
2. Click on add image 
3. Click on image scaling buttons in right sidebar
4. You may have to upload several images to see this problem, it seems to sporadically affect images.
5. Go to preview post to see any issues with affected images expanding outside of content area.

**Expected behavior**
I expected the image to scale down to either 25%, 50%, 75%, or 100% depending on which option I selected in the post editor sidebar. Some images did actually resize according to this making it more expected that it would do so for all images.

**Screenshots**
![image](https://user-images.githubusercontent.com/25126849/44790110-6b4fa700-ab6c-11e8-937a-3b5284c60e61.png)
Image here is size when set to 25%

![image](https://user-images.githubusercontent.com/25126849/44790140-7f93a400-ab6c-11e8-9226-28db5d0789b1.png)
Same image but set to 100%, yet no size difference

![image](https://user-images.githubusercontent.com/25126849/44790163-9a661880-ab6c-11e8-8aa3-31c8fd49db4b.png)
Image when set to 25%, taking up nearly whole page.

Other images in the screenshots 

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser Chrome
 - Version 68.0.3440.106 

**Additional context**
-Gutenberg version 3.6.2

- Images that aren't initially affected appear to occasionally become affected by the resizing issue if another image is selected, and then that image is immediately selected afterwards. Often times this increases the default values of the image size and hitting reset doesn't appear to correct it.

**Comment by designsimply** [comment]
I think you might be expecting the percentage sizing to be relative to the editor width but in fact they are relative to the original size of the image. If the image is very large, then 25% might still be too big. Can you try using the "Image Size" drop-down selector instead of the "Image Dimensions"?

I am closing this issue to start, but if we can absolutely re-open this later if we continue the discussion and find a bug or want to re-open this as a feature request!
