### ISSUE TITLE
Once in Code Editor provide suggestion on how to get back to visual editor

### ISSUE THREAD

**Issue by robertdall** [WordPress/gutenberg#9445]
If you click into the Code Editor you are brought t an editor with a number of comments and a bunch of HTML code. If you didn't know where you click or what you clicked you / a basic WordPress user will be very confused as to what you did to find yourself in the code editor and how to get back. Since the switch code editor / visual editor is hidden behind a hamburger style menu of three dots and a user would go searching for how to get back to the visual editor. 

If you try to click undo you are actually undoing changes you made to the page, not undoing clicking to go to the code editor. 

We provided warnings in [WordPress 4.9 that you were going to the code editor](https://make.wordpress.org/core/2017/10/22/code-editing-improvements-in-wordpress-4-9/) I believe and lobby for at least an easy way to get back to the visual editor (just the first time) or we will have a lot of lost users editing code they shouldn't be wondering how they will get back and clicking everywhere to do so.

**Expected behavior**
If you want the switch between the code and visual editor hidden then A line of text with a yellow background saying that you have gone into the code editor and asking if that is really where you wanted to go, with a text link back to the visual editor.  

**Suggested notification**
Easy Suggested Notification to the user who has entered the code editor.

<img width="838" alt="screen shot 2018-08-29 at 1 45 55 pm" src="https://user-images.githubusercontent.com/1909677/44814570-027b2580-ab92-11e8-93d0-2d35c1cd493b.png">

**Screenshots**
<img width="1218" alt="screen shot 2018-08-29 at 12 24 52 pm" src="https://user-images.githubusercontent.com/1909677/44810634-238a4900-ab87-11e8-8d9e-25515bfa7d53.png">

**Desktop**
 - OS: OSX 10.11.6
 - Browser Firefox 
 - Version 61

**Comment by tofumatt** [comment]
While I think switching to the Code Editor is *probably* pretty intentional (the keyboard shortcut is obscure enough likely to not be hit accidentally), I think this is a solid UX nudge and will definitely be helpful to someone who accidentally clicks it and then gets spooked. Especially because the setting persists. Nice 👍

**Comment by jasmussen** [comment]
I think this is sensible, and I've had similar thoughts about this. In fact I could swear there was an existing ticket about this — perhaps @designsimply will know?

In any case, it feels sensible to me that the code editor is something you enter and exit. In that vein, here's a mockup for how an "Exit Mode" interface could look:

![exit code editor all blocks](https://user-images.githubusercontent.com/1204802/44833715-440dde00-ac2f-11e8-9065-1c537d8498a4.png)

Note that we could fit quicktag buttons in the space between the label and button if we so desired. 

We could reuse this pattern if you're just editing the HTML of a single block:

![exit code edit on block basis](https://user-images.githubusercontent.com/1204802/44833744-59830800-ac2f-11e8-8240-92b0020b8fd8.png)

**Comment by robertdall** [comment]
I would prefer the first example seeing the "x Exit Code Editor" In the top corner as it's more visible to the average user.

**Comment by jasmussen** [comment]
For sure — the 2nd design is if you're editing the HTML of a single block (click ellipsis for a block, click Edit HTML). The latter thing arguably needs the exit button more than the former, as it's hard to exit otherwise.
