### ISSUE TITLE
Fails with Ninjaforms

### ISSUE THREAD

**Issue by Luke-SF** [WordPress/gutenberg#9447]
**Describe the bug**
Ninja forms fails to load with Gutenberg activated.

**To Reproduce**
1. Go to edit a form.

**Expected behavior**
Form should load

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Browser Firefox
 - Version 61

The console shows an error:
TypeError: wp.media.view.settings.post is undefined in media-audiovideo.min.js

Not sure if this should be considered a Gutenberg or Wordpress bug as that is in /wp-includes/.

**Comment by youknowriad** [comment]
Unfortunately, Gutenberg can't support all the current classic editor plugins. I think a Ninjaforms block would be a good addition. Did you consider checking with the plugin author if they have any plans on Gutenberg support? Thanks.

**Comment by tofumatt** [comment]
Agreed that a Ninjaforms block would be the right approach here; unfortunately class editor plugins may not function with Gutenberg. It's up to the plugin developer to make sure their plugin doesn't crash Gutenberg, as mentioned we unfortunately can't support all classic editor plugins.

Please do report this to Ninjaforms as they will need to fix the issue. Sorry about that!
