### ISSUE TITLE
Enhancement: On mobile, columns should be stacked

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#9449]
Due to size constraints on mobile, columns should be stacked.

This would be in keeping with general practice, such as page builders.

**Comment by youknowriad** [comment]
Thanks for the issue, I'm closing as a duplicate of #9449 please follow the discussion there. Thanks.

**Comment by GlennMartin1** [comment]
This is issue # 9449. Your evidently meant a different issue number.

**Comment by youknowriad** [comment]
Yes sorry #6048 I probably should go to bed :P
