### ISSUE TITLE
link in text without target=_blank is ok but with target=_blank get error in chrome en opera like 'Image cannot be loaded. Make sure the path is correct and image exist.' Versie: 3.6.2

### ISSUE THREAD

**Issue by astrid-berkhout** [WordPress/gutenberg#9456]
link in text without target=_blank is ok but with target=_blank get error in chrome en opera like 'Image cannot be loaded. Make sure the path is correct and image exist.' Versie: 3.6.2

**Comment by astrid-berkhout** [comment]
![link](https://user-images.githubusercontent.com/42831413/44838643-f009f600-ac3c-11e8-826a-540eb830a51f.jpg)
Like this!

**Comment by astrid-berkhout** [comment]
I discovered the problem! When I give one of my galleries a open media -> all links in the text above wants to open a image, all links under this gallery stay unchanged. This is a big problem.

**Comment by designsimply** [comment]
> When I give one of my galleries a open media

How are you doing this step exactly? 

Could you tell me a short list of steps to reproduce the problem and could you please also let me know if you are using any media-related plugins?

**Comment by youknowriad** [comment]
Closing as stale.
