### ISSUE TITLE
Documentation: Provide some developer guidance on server-side block handling

### ISSUE THREAD

**Issue by mcsf** [WordPress/gutenberg#9463]
Providing a broader client-and-server-side validation framework and API was brought up in #4063. This is an ambitious and arguably premature goal that should be revisited after WordPress 5.0. See my reasoning [here](https://github.com/WordPress/gutenberg/issues/4063#issuecomment-411438156) and [here](https://github.com/WordPress/gutenberg/issues/4063#issuecomment-411715145), and the summary:

> For now, developers (and third-party solutions which are likely to emerge) should be left to solve this as most fitting for their use cases, provided we ship the basic tooling per **PHP APIs Overview #8352**.

**Comment by paaljoachim** [comment]
Is this issue still relevant?

**Comment by mcsf** [comment]
It has definitely proved less pressing than others, given its age!

It should be good to close if we consider that we have enough prior art in Gutenberg and other noteworthy plugins, or in existing documentation. Feel free to do so, @paaljoachim.

**Comment by paaljoachim** [comment]
Closing for now. It can always be reopened.
