### ISSUE TITLE
Translator comments are sometimes missed out

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#9464]
**Describe the bug**

When generating `languages/gutenberg.pot`, sometimes the built files are used instead of the original source files and translator comments get missed.

In `packages/editor/src/components/block-list/block.js` we have this on lines 382-384:

```
		const blockType = getBlockType( blockName );
		// translators: %s: Type of block (i.e. Text, Image etc)
		const blockLabel = sprintf( __( 'Block: %s' ), blockType.title );
```

This gets built to this in `packages/editor/build-module/components/block-list/block.js`:

```
      var blockType = getBlockType(blockName); // translators: %s: Type of block (i.e. Text, Image etc)

      var blockLabel = sprintf(__('Block: %s'), blockType.title); // The block as rendered in the editor is composed of general block UI
```

and when translations are generated, the `build-module` version's translation entry is used and the translator comment is not included.

**To Reproduce**

Run `npm run build` and see that `build-module` versions of files are referenced in `languages/gutenberg.pot`

**Expected behavior**

Only the original `src` versions should be referenced, and all translator comments should be included.

**Comment by mayukojpn** [comment]
I also found 3 translator comments in [packages/keycodes/src/index.js:L124](https://github.com/WordPress/gutenberg/blob/6712e28279c2f654bf2263db5f34d66fccb452fa/packages/keycodes/src/index.js#L124:L129) are not imported to [GlotPress](https://translate.wordpress.org/projects/wp-plugins/gutenberg/dev/ja/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6631269&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc). I don't know why :(

**Comment by 00travelgirl00** [comment]
I translate strings to german right now and also found some missing translator comments:

- Archives (can be singular or plural in englisch. in german those are different words.)

and the most strings which are still open:

https://translate.wordpress.org/projects/wp-themes/twentynineteen/de/default?filters%5Bstatus%5D=untranslated&sort%5Bby%5D=priority&sort%5Bhow%5D=desc

**Comment by swissspidy** [comment]
This should be mostly solved now that Gutenberg has merged into WordPress core and WP-CLI is used to extract the strings and comments. There are only a few exceptions: https://github.com/wp-cli/i18n-command/issues/106

See #9440.

**Comment by youknowriad** [comment]
Should we close this @swissspidy?
