### ISSUE TITLE
Packages that ship polyfills should depend on core-js@2

### ISSUE THREAD

**Issue by blowery** [WordPress/gutenberg#9478]
At the moment, many npm packages from Gutenberg ship with polyfills that use `core-js@2`. However, they only declare a dependency on `@babel/runtime-corejs2`. Since the built code has a bare require for `core-js`, the packages should also declare `core-js@2` as a dependency. Otherwise, version conflicts can occur, as the dependency is only transitive. If a client is using some other package that also relies on core-js, but another version, that version may end up being loaded instead of the version bundled with babel's runtime-corejs2.

For example:
```
npm i core-js@1
npm i @wordpress/i18n
```
Results in an npm tree with `core-js@1` in the root. When client code loads `@wordpress/i18n`, the bare require for `core-js` loads the version from the root and fails.

Ideally no polyfills would be shipping with Gutenberg packages, but that's #9171

cc @gziolo @jsnajdr

**Comment by blowery** [comment]
A sample gist to illustrate

https://gist.github.com/blowery/4812bd7497c3d65aee44ce9d2dac0068

**Comment by gziolo** [comment]
> Since the built code has a bare require for core-js, the packages should also declare core-js@2 as a dependency. Otherwise, version conflicts can occur, as the dependency is only transitive. If a client is using some other package that also relies on core-js, but another version, that version may end up being loaded instead of the version bundled with babel's runtime-corejs2.

That's interesting. I wasn't aware of it. I assumed those nested dependencies will be properly resolved from `@babel/runtime-corejs2`.

> Ideally no polyfills would be shipping with Gutenberg packages, but that's #9171

Yes, we are aiming to resolve it with #9171. It makes everything more consistent and doesn't force you to add those dependencies when you use a different polyfill strategy :)

**Comment by jsnajdr** [comment]
See also Automattic/wp-calypso#26212 where we added the top-level dependency after we got burned in real life.

> Ideally no polyfills would be shipping with Gutenberg packages, but that's #9171

The discussion in #9171 shows that there are pros and cons to both approaches.

Not shipping the polyfills at all makes it difficult to describe the environment that the package expects. It's "ES5 language syntax + list of 30+ modern builtins we call (`Array.includes`, `String.padStart` etc.)". Hard to figure out the list and maintain it.

Having a runtime dependency on `core-js` and using `useBuiltins: 'usage'` is a bit more bloated, but it moves the description of the 30+ required builtins to the code: it's the package code that requires a polyfill before using it. No longer a documentation task.

**Comment by gziolo** [comment]
> It's not just that it's bloated, it alters the global environment. That's unexpected for a library.

I think the goal of `@babel/runtime-core2` was to solve this issue and make those overrides local. However, don't take that for granted, I'm not sure if that is even possible :)

**Comment by blowery** [comment]
> I think the goal of @babel/runtime-core2 was to solve this issue and make those overrides local. 

I think that's the goal of `transform-runtime`, to ponyfill usage in place. The problem there is that it doesn't fix usage of prototype methods like Array.prototype.includes. 

I think a longer term fix could be something like babel-preset-env with builtins:usage that, instead of adding polyfills, warns you or breaks the build when it sees usage of prototype methods that would require a polyfill on some browsers in the target set.

**Comment by gziolo** [comment]
This should be resolved with the #9171 and is now available on npm.

Check related versions of updated packages in https://github.com/WordPress/gutenberg/commit/df6f8da7b557894e4364c17db2dd4af0d1e20252.
