### ISSUE TITLE
Invalid JSON when trying to add image block

### ISSUE THREAD

**Issue by danieltj27** [WordPress/gutenberg#9479]
I was trying to add an image block on the [Make/Core](https://make.wordpress.org/core/wp-admin/) site and when I tried to upload an image, the image appeared very briefly and then disappear when a red noticed popup saying '_Invalid JSON_'. I tried it a couple of times and it didn't work.

**Comment by mtias** [comment]
I run into this myself too, appears to be an issue with WP trunk as reported here in the comments: https://core.trac.wordpress.org/ticket/43757
