### ISSUE TITLE
Redirection

### ISSUE THREAD

**Issue by Albertopi78** [WordPress/gutenberg#9486]
**Describe the bug**
I installed Gutenberg Plugin, my page https://www.albertopuliafito.it/seo/ started redirecting to this one https://www.albertopuliafito.it/seo-copywriting-non-esiste-scrivere-bene/
I tryed disinstalling and reinstalling it, same behaviour.

**Comment by designsimply** [comment]
I was unable to reproduce the problem using the following testing steps:

1. Publish a new page with a title of "SEO".
1. Publish another new page with a title of "SEO Copywriting Non-esiste-scrivere Bene".
1. Visit the first page.

<strong>Result:</strong> no redirect happened in my case.

What a strange issue! 

Would it be possible for you to try repeating the same problem with two different pages to see if the same thing happens in more than one case for you?

A good basic troubleshooting step would also be to clear your browser cache and try visiting the page again.

I am not sure if it would help, but maybe try going to Settings > Permalinks and clicking the "Save Changes" button to see if that makes a different at all?

Please write back to let us know what you find or to let me know if my testing steps are missing any detail you think is needed!
