### ISSUE TITLE
Gutenberg and get_attached_media

### ISSUE THREAD

**Issue by wpalchemist** [WordPress/gutenberg#9487]
**Describe the bug**
Uploading images into Gutenberg does not attach them to the post, so you can't use `get_attached_media` to get all of the images in a post.

**To Reproduce**
1. Create a post
2. Upload one or more images into the post
3. In the loop, use the `get_attached_media()` function, or use `get_children()` to find child media

**Expected behavior**
Without Gutenberg, `get_attached_media()` will return all images attached to the post.  

**Additional context**
Gutenberg 3.6.2

**Comment by mindgraffiti** [comment]
Uploading videos into Gutenberg has the same issue. Following.

**Comment by designsimply** [comment]
Thanks for reporting! I would like to consolidate this issue to #8748 because I think fixing that one will also solve this issue as well as they are very similar. Let me know if there's a good reason for leaving this one separate though!

**Comment by wpalchemist** [comment]
Yep, sounds like the two issues have the same root problem.  Thanks!
