### ISSUE TITLE
3.7 block inserter styling broken

### ISSUE THREAD

**Issue by ktmn** [WordPress/gutenberg#9491]
**Screenshots**
![](https://i.imgur.com/P8DCXjx.png)

**Additional context**
Chrome 68.0.3440.106
Twenty Seventeen
Gutenberg 3.7 from [here](https://make.wordpress.org/test/2018/08/30/call-for-testing-gutenberg-3-7-pre-release/).

**Comment by imath** [comment]
Thanks for reporting the issue, I was about to do it 😊. I have the same bug with the master branch.

**Comment by ktmn** [comment]
Still pretty weird behavior with "stacked" blocks.

![](https://i.imgur.com/23RnpEV.png)
