### ISSUE TITLE
Publishing Date for Posts - New Gutenberg Screen versus Classic Screen

### ISSUE THREAD

**Issue by CynthiaBlue44** [WordPress/gutenberg#9492]
To edit the publishing date for a post in the new Gutenberg screen, a drop down calendar is available, unfortunately this does not give me the ability to edit the year the same way using the "Classic"  screen method, where you could alter the year, month, day, time in a line entry. This problem caused me to go back to the "Classic" screens.

I use the publishing date to help sort a Time-Line-Journal for an historical figure, Allan Cunningham Botanist Explorer. I set the publishing date in the years 1791 to 1839; this allows my blogs to sort in the date order of the journal. Clicking back using the new Gutenberg publishing date calendar, is too time consuming because you can only click back one month at a time.

Is it possible to include the line entry method, as per the "Classic" screen, in the new Gutenberg screens? If not, could we have the ability to click back years as well as months. But really, I'd love to have the line entry availability.

Thank you.

**Comment by youknowriad** [comment]
Thanks for the issue, you're not the only one expression this struggle and this is being worked on in #1311

Closing as duplicate.
