### ISSUE TITLE
Drop Cap should ignore initial non-breaking space....

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#9505]
**Describe the bug**
If a paragraph opens with a non-breaking space `<br>`, Drop Cap should ignore that `<br>` and still Drop Cap the first character in the paragraph.

Not sure why someone would open a paragraph with a `<br>` but I discovered this by mistake and it took a while to understand why the first letter was not drop-cap.

**To Reproduce**
1. Create a paragraph that begins with a non-breaking space `<br>`
2. Turn on Drop Cap
3. Note that the paragraph does not Drop-Cap.

**Expected behavior**
A leading `<br>` should be ignored by Drop-Cap.

**Comment by mtias** [comment]
I think this could get rather complicated to address with diminishing returns. I'm inclined to close as wontfix. Potentially a better thing to do would be to highlight these "invisible" characters?
