### ISSUE TITLE
Multi Select: Better sticky toolbar

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#951]
From #896, multiple block selection is now in. When you select across blocks, you can delete them all at once with a trash can at the top.

That toolbar is only sticky to the first selected block, so it doesn't scroll with you down the page. There are some ideas on how to improve this [here](https://github.com/WordPress/gutenberg/pull/896#issuecomment-304701949):

> Regarding sticky positioning... We could wrap the selected block in an extra div. This would also be far cleaner than adding the buttons to the first selected block. A big downside is that iframes would reload. The other solution is adding the buttons to the parent division, but we'll have to reposition it with JS.

An alternative from [here](https://github.com/WordPress/gutenberg/pull/896#issuecomment-304778342), is to add a new toolbar which overlays the Editor Bar entirely, and appears only when you select multiple blocks at the same time. The pattern to emulate could be that of Google Photos, where you have one toolbar when you don't have any photos selected:

![photos](https://cloud.githubusercontent.com/assets/1204802/26569130/0cbd90e6-4509-11e7-91d0-e3666290b14b.png)

... and another toolbar replacing it, when you have photos selected:

![photos selected](https://cloud.githubusercontent.com/assets/1204802/26569136/17d3545c-4509-11e7-9e99-c1214d4b6431.png)

Might be nice to even copy the "8 blocks selected" pattern. This could even be the location of the mover buttons.

Here's a quick and dirty mockup of how that could look:

![selecting across blocks](https://cloud.githubusercontent.com/assets/1204802/26621890/b2e644ba-45e8-11e7-9173-85ab1860c899.png)

**Comment by iseulde** [comment]
Thanks for reposting these @jasmussen!

**Comment by iseulde** [comment]
I love this BTW!!! This is what I mean in the previous ticket with iOS photos too. :)

**Comment by iseulde** [comment]
Fixed in #955.
