### ISSUE TITLE
Pictures can not be inserted in table

### ISSUE THREAD

**Issue by jan2803** [WordPress/gutenberg#9514]
In the classic editor, it is possible to insert a graphic into a table cell. That's great too, because sometimes you do not want the text to the picture flow around the picture.

In Gutenberg, however, this does not work anymore. There is no possibility to insert a picture in a table.
But I still want to create a table where photos are on the left and a description of the image on the right.
The block "columns" is unfortunately not usable for this.

What is needed for that?

I would like to introduce my team. For this I use a table. On the left the photo, on the right the short vita of the person. I have not found another option yet.

To say, for a picture one uses a block "picture" is not a solution.

Here must necessarily be improved.

Thank you, Jan

**Comment by iseulde** [comment]
It is possible to insert images inline into a table. To do that, set the caret in a table cell, open the "Inserter" by clicking the `(+)` icon at the top left of the page, scroll a bit down and open the "Inline Elements" section, click "Inline Image", select or upload an image, click the "Select" button at the bottom, and the image will appear inside the table.

**Comment by jepser** [comment]
@ellatrix I don't see the `(+)` icon when focusing in one cell in the table. Can you assure that by version 5.1 it still like that?

**Comment by ellatrix** [comment]
@jepser There should be a + icon in the top left corner. It should work in earlier versions. #14233 will hopefully make it easier to find the button.

**Comment by kachan64** [comment]
Thanks alot. It works! Wish Wordpress made it easier.

**Comment by mkitcowt** [comment]
Running wordpress 5.2.1 and this solution does NOT work. There is no "Inline Elements" option when clicking on "+". Other attempts to add an image in a table result in the image outside the table.
Any suggestions?
(Not a fan block mode ... maybe its the learning curve but it seems as if Wordpress is trying to build a better mousetrap.)

**Comment by ellatrix** [comment]
@mkitcowt This has now been moved to the rich text tools. Click the arrow down next to bold, italics and link, then you'll see a button to insert an image inline.

**Comment by mkitcowt** [comment]
@ellatrix Thank you. But is there an option for a URL?

**Comment by asherber** [comment]
Doesn't look like there's a way to add an image via URL using this method. I think you have to edit the HTML source of the table and insert the `img` tag by hand.
