### ISSUE TITLE
Why can you collapse the Block Switcher?

### ISSUE THREAD

**Issue by mintplugins** [WordPress/gutenberg#9522]
I'm unsure if this is a bug, or if the option serves a purpose I am not seeing. 

When switching blocks, there's an option to collapse the pop-up. With it collapsed, it doesn't really seem to serve a true purpose, and might just be something that got overlooked. 

![why-is-this-here](https://user-images.githubusercontent.com/1638128/44936544-1fa32600-ad43-11e8-946b-0437e497b6c0.jpg)

**Comment by kjellr** [comment]
> Style variations for blocks can be registered (and some core blocks come with a default set of variations, such as the Quote block), and these also appear in the block switcher:
> That is why you can collapse the block transforms group.

True, but we should be able to detect whether there are Block Styles and hide the dropdown indicator when there are none. In that case, it doesn't serve any real purpose. 👍

**Comment by gziolo** [comment]
This issue is waiting for a developer to take care of it. There is some prior work done by @milesdelliott in #9886 which got out of date and can be used as a base for the fix.

**Comment by Soean** [comment]
This issue will be fixed by #19344

<img width="380" alt="Bildschirmfoto 2020-02-24 um 12 49 32" src="https://user-images.githubusercontent.com/695201/75131147-39d57e80-5704-11ea-9855-c8bc034d4421.png">
