### ISSUE TITLE
Iranian calendar

### ISSUE THREAD

**Issue by HassaN0152** [WordPress/gutenberg#9525]
Add Iranian calendar to this add-on. Although WordPress is an installer for Persian language extensions, the gutenberg calendar is Gregorian calendar.
translate by google

**Comment by draganescu** [comment]
Howdy @HassaN0152 :) Would this calendar be the calendar block? If so I wonder if this isn't plugin territory. To some extent I've searched core and all calendar variations are offered by plugins.

**Comment by skorasaurus** [comment]
@draganescu I don't know if @HassaN0152 is referring to the calendar provided in core as a block or the calendar in the side panel used for post publishing, etc.

**Comment by ndiego** [comment]
@HassaN0152 just checking in. Can you provide a bit more context about the calendar that you are referring to? Is it the Calendar block or the calendar popup for post-publishing?

**Comment by priethor** [comment]
Let's close this issue, as it needs more info to be actionable. Please feel free to reopen again if there is more information. 🙏
