### ISSUE TITLE
<br> tags in custom html

### ISSUE THREAD

**Issue by Aljnk** [WordPress/gutenberg#9528]
I use my own theme for wordpress website. My html code written in theme files has extra tag `<br>` in many different places, when I activate Gutenberg plugin.

How can I switch off this `<br>` adding by Gutenberg plugin (AT ALL)?

![3](https://user-images.githubusercontent.com/11256478/44944446-69414e80-addf-11e8-8dc5-91967c13bf00.jpg)

- Windows 10 - Google Chrome, Opera, Firefox
- Gutenberg Version 3.9.0 (and <3.9.0).

**Comment by bkyam** [comment]
I've noticed that when you add HTML code, Gutenberg inserts a <br> before the code block, and two <br> tags after the code block.

See similar issue:
https://github.com/WordPress/gutenberg/issues/5872

**Comment by Aljnk** [comment]
I'm not using Gutenberg at all - It just activated. This code inside "THEME" php files.

**Comment by designsimply** [comment]
@Aljnk I noticed that an update was made to formatting whitespaces in https://github.com/WordPress/gutenberg/pull/12166 in Gutenberg 4.7, and I was wondering if you are still having trouble with this if you update to the latest version of WordPress (the plugin is no longer needed).

The description about browser behavior in https://github.com/WordPress/gutenberg/issues/5872#issuecomment-441008535 may also be relevant here.

**Comment by Aljnk** [comment]
Now Everything is Good - Thanks!
