### ISSUE TITLE
Problem with caption for aligned images

### ISSUE THREAD

**Issue by SeniorSpielbergo** [WordPress/gutenberg#9530]
**Describe the bug**
When adding a centered / left aligned / right aligned image to a post, the caption and the image are correctly aligned, but there is no space between the image and the caption.

**To Reproduce**
1. Create a post
2. Add an image block with some picture comprising a caption
3. Select an alignment (either centered / left / right)
4. In the Gutenberg editor the image is correctly aligned and the space between the image and the caption is correct (cf. Screenshot 1)
5. However, when switching to the preview or publishing the post, this space is not displayed anymore (cf. Screenshot 2)

**Expected behavior**
The space  between the image and the caption should be displayed not only in the editor, but also in published posts

**Screenshots**
Screenshot 1 (Post shown in the Gutenberg editor; the space between the image and the caption is correctly displayed)
![1](https://user-images.githubusercontent.com/996503/44944618-4bbdb600-adda-11e8-81fe-dbdb0dc96b5f.png)

Screenshot 2 (Preview of the Post; the space between the image and the caption _is not_ correctly displayed)
![2](https://user-images.githubusercontent.com/996503/44944619-4f513d00-adda-11e8-95ac-6721dcca7d8e.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 68.0.3440.106

**Additional context**
- Wordpress 4.9.8
- Gutenberg 3.7

**Comment by GlennMartin1** [comment]
Similar issue in the context of buttons: see https://github.com/WordPress/gutenberg/issues/7812

Left/center/right alignment choice should never affect top/button padding.

**Comment by ianbelanger79** [comment]
Hi @SeniorSpielbergo,

Thanks for your report. The styles on the front-end of your site should be controlled mostly by your theme. Could you please tell us what theme you are using? And could you try using 2017 or some other default theme and report back if you still have the issue.

Thanks

**Comment by mtias** [comment]
@jasmussen is there a discrepancy in centered / non-aligned images we could address here?

**Comment by jasmussen** [comment]
> before switching to the Gutenberg editor everything was working fine.

Did you add image captions before using Gutenberg? If so can you let me know the steps?

Also, are the caption margin issues present _only_ when an image is left/center/right aligned? Or is the issue present even on non-aligned images?

> @jasmussen is there a discrepancy in centered / non-aligned images we could address here?

Yes, I can set an explicit margin on the caption, right now I believe we rely on what that figcaption is styled with by the browser.

**Comment by jasmussen** [comment]
@SeniorSpielbergo 

> However, before switching to the Gutenberg editor everything was working fine. Thus, I was wondering why using the new Gutenberg editor would affect how posts are displayed.

I would love more information on this.

Did you add captions to your images before using Gutenberg? Do you have any links you can share?

I would like to fix this issue for you, but I need to understand more about what the theme does that regressed here.

**Comment by jasmussen** [comment]
Without further information, I don't know what the best approach to this ticket is. As it is, we are relying on the intrinsic margins on the `figure` element to ensure spacing for the image block. This is the same regardless of alignment:

![figure](https://user-images.githubusercontent.com/1204802/46727564-22b5fe00-cc81-11e8-80d7-60cf2413b1db.gif)

If the WordPress theme does the following:

```
figure {
margin: 0;
}
```

... then the issue described in this ticket will appear. The only way we can "fix" that is by adding the following to the Gutenberg CSS:

```
figure {
margin-top: 1em;
margin-bottom: 1em;
```

But this effectively overrides the theme CSS to go back to the vanilla CSS, which seems a little heavy handed. 

Let me know what the best approach should be and I'll submit a PR.

**Comment by SeniorSpielbergo** [comment]
@jasmussen 
> Did you add captions to your images before using Gutenberg?
Indeed I added the captions prior to using Gutenberg. However, after switching to Gutenberg, I also tried to update the captions, rearrange the pictures, completely remove the pictures and readd them, ...

> Do you have any links you can share?
One of the affected links is: https://www.david-wille.de/autumn-street-scene/

I hope this information helps you to better understand the problem. Just let me know if you have further questions.

**Comment by jasmussen** [comment]
Yes, thank you. I created https://github.com/WordPress/gutenberg/pull/10525 to fix this.

**Comment by SeniorSpielbergo** [comment]
@jasmussen Thank you for submitting the fix. However, it does not solve my issue. When you look at https://www.david-wille.de/autumn-street-scene/, you can see that there still is no space between the caption and the figure.

**Comment by jasmussen** [comment]
Thanks for the followup. I found the problem, but it's not a problem in Gutenberg. I will respond on your other ticket.
