### ISSUE TITLE
Alignment: problem with centering gallery

### ISSUE THREAD

**Issue by SeniorSpielbergo** [WordPress/gutenberg#9531]
**Describe the bug**
When centering a gallery block with a single column of images (e.g., with images that are not spanning the complete width of the column) and disabled cropping, the images in the gallery _are not_ centered. Also the caption of the images shows some weird behavior with added scrollbars.

**To Reproduce**
1. Create a post
2. Add a gallery block with images, which are not spanning the column width. Select display in a single column and deactivated cropping of the images. The result looks similar to Screenshot 1.
3. Center the gallery
4. Weird scrollbars show up for the caption and also the images is not centered (cf. Screenshot 2).

**Expected behavior**
The images in the gallery should be centered. Also the caption should be centered without the scrollbars showing up.

**Screenshots**
Screenshot 1 (after inserting the gallery, the images are not centered in the single column)
![3](https://user-images.githubusercontent.com/996503/44944728-56794a80-addc-11e8-9a60-da5107e76672.png)

Screenshot 2 (the gallery images are not centered and a scrollbar shows up for the caption)
![4](https://user-images.githubusercontent.com/996503/44944730-59743b00-addc-11e8-8aa4-a1bbaea3baa6.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 68.0.3440.106

**Additional context**
- Wordpress 4.9.8.
- Gutenberg 3.7

**Comment by madavibr** [comment]
Same problem here.

**Comment by SeniorSpielbergo** [comment]
I am not sure about the internals of the gallery block, but might this problem be linked with #9530?

**Comment by jasmussen** [comment]
Thanks for the ticket. I submitted #11040 to fix this.
