### ISSUE TITLE
[3.7.0] Editor fails to load while editing some pages

### ISSUE THREAD

**Issue by TheEpicSnowWolf** [WordPress/gutenberg#9542]
After I updated to version 3.7.0, I'm not able to edit some pages with Gutenberg anymore. Instead, WordPress shows me a blank page. The Chrome console gives me the following errors:

![errors](https://user-images.githubusercontent.com/6506715/44948676-3d938800-ae22-11e8-9cb4-6549a4a44d46.jpg)

Interesting to note is, that this only happens on a few pages. Other pages, I can edit without any problems. I can't detect a "pattern" of on which kind of pages the editor fails to load though.

**Comment by youknowriad** [comment]
See https://github.com/WordPress/gutenberg/issues/9541#issuecomment-417874697 It should be related.

**Comment by TheEpicSnowWolf** [comment]
I can confirm that the workaround plugin seems to have resolved the issue for now.

**Comment by youknowriad** [comment]
👍

**Comment by GlennMartin1** [comment]
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, deactivate and remove the workaround plugin, and confirm the issue is addressed.

**Comment by TheEpicSnowWolf** [comment]
Yes, the update seems to have resolved the issue! Thank you!
