### ISSUE TITLE
Block request: Vertical/Horizontal tabs

### ISSUE THREAD

**Issue by flashtox** [WordPress/gutenberg#9543]
I would love if you could add Vertical/Horizontal tabs as a block.

Like the one that Elementor have:

![vertical-tabs-1024x536](https://user-images.githubusercontent.com/42897207/44948875-2b1b4d80-ae26-11e8-9e17-07fd6c7e5fc8.png)

Thanks!

**Comment by designsimply** [comment]
Thank you for posting! I think this will be best added as a plugin and not something fore core blocks. I will add the `Needs Decision` label in order to double check that.

**Comment by SeniorSpielbergo** [comment]
Are there any updates on the timeline for this request?

**Comment by paaljoachim** [comment]
It looks like the issue in on freeze until a future date.
Anybody can ask about this feature during the Open Floor portion of a Core Editor meeting on Slack.

@phpbits 
Would this feature be something for EditorsKit?

**Comment by mtias** [comment]
This is better — for now — done in plugin space. As HTML continues to evolve and we can natively support more tools like this we'll reconsider.

**Comment by paaljoachim** [comment]
I believe that in relation to the Navigation block that we will see it drip down into adding horizontal and vertical tabs.
