### ISSUE TITLE
H5/H6 header support

### ISSUE THREAD

**Issue by AtwoodEditor** [WordPress/gutenberg#9544]
I’d like the ability to customize my options for headings, as H5 and H6 are my primary go-tos and neither seems present in Gutenberg. Thank you!

**Comment by ZebulanStanphill** [comment]
You can set a heading to the `h5` or `h6` options in the block inspector:
![image](https://user-images.githubusercontent.com/19592990/44951992-f82e8500-ae38-11e8-8ad8-69062f4a9e7f.png)

However, it sounds like you are using the headings wrong. Headings have semantic meaning. An h2 represents a heading for a section/chapter of the main article/post/page (which uses an h1). An h3 is a heading for a sub-section (like a section of a chapter). An h4 is a heading of a sub-sub-section, and so on. If you want to have small looking headings that are really just 2nd-level headings, then you should use CSS. Your theme may support changing the h2 size in the Theme Customizer, and if not you could use the Additional CSS box in the Customizer.

https://codex.wordpress.org/CSS#Custom_CSS_in_WordPress

Proper usage of headings is good for people using accessibility tools such as screen readers, as well as for search engine optimization (SEO).

Additional info:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/Heading_Elements
https://www.w3.org/TR/html53/sections.html#the-h1-h2-h3-h4-h5-and-h6-elements

**Comment by 0aveRyan** [comment]
thanks for answering this so thoroughly @ZebulanStanphill!
