### ISSUE TITLE
Idea to make Custom font size responsive

### ISSUE THREAD

**Issue by edirpedro** [WordPress/gutenberg#9549]
I was trying to figure out how to make responsive the custom font size tool in the editor. I didn't find any solution unless it returns more information about the font size that the user selected in the slider control.

When using a custom font size, that value should be placed as an attribute `data-font-size=10`, so we can check that value using CSS

Usage example: https://codepen.io/edirpedro/pen/NLpBww

In the example above I tested another units and I think this could be implemented on the editor.

1. Theme support `editor-font-sizes` could define another __unit__ for the font size _%_, _rem_, _em_, for example.

2. There is no theme support to define `editor-custom-font-sizes` to `false` and disable this feature if the developer doesn't want to offer this feature to users, using only the buttons S,M,L and XL because those buttons have a classname.

**Comment by mtias** [comment]
This could be interesting.

**Comment by karmatosed** [comment]
I am removing design feedback as whilst interesting this doesn't change anything visually - or the goal should be for that to not happen :)

**Comment by chrisvanpatten** [comment]
Just a note that the second point on here "There is no theme support to define `editor-custom-font-sizes` to false" — that has been fixed! You can now use `add_theme_support( 'disable-custom-font-sizes', true );` to disable the custom size selector.

I also just created #11671 to track some of the ways we can start to decouple pixels from font sizes in the editor.

**Comment by unknys** [comment]
Why cant i with Gutenberg decide FONT, and size of the fonts ? This has to be the worst "forgotten" implementation ever. No wonder we have to use Siteorigin, DIVI and others.

Ive checked the Blocks, and it dosent say or show anywhere as how i can enable this. Anyone who has figured this out and can help me get this in place ?

**Comment by tellthemachines** [comment]
Given that is is now possible to disable custom font sizes, and that we have #11671 for making the font size picker work with responsive units, I think we can close this issue now.
