### ISSUE TITLE
Layout Elements adding blockis row styling

### ISSUE THREAD

**Issue by grappler** [WordPress/gutenberg#9553]
**Describe the bug**
The blocks in the "Layout Elements" section are not being displayed on their line.

**To Reproduce**
1. Add new block from the top left corner
2. Open the "Layout Elements" section

**Screenshots**
![image](https://user-images.githubusercontent.com/1785641/44959468-c7a92280-aeee-11e8-9250-a5b3dee58d4f.png)

Gutenberg v3.7.0

**Comment by ianbelanger79** [comment]
Hi @grappler,

Thanks for your report. Could you please provide the OS and browser that you are using when you see this issue?

Thanks

**Comment by grappler** [comment]
I see this problem on both latest versions of Chrome and Firefox on macOS High Sierra.

**Comment by grappler** [comment]
This seems to be fixed in Gutenberg 3.9
