### ISSUE TITLE
contributors can't edit published post without unpublishing it

### ISSUE THREAD

**Issue by unnami** [WordPress/gutenberg#9554]
1. contributor is writing a post
2. subbimting to review
3. admin is publishing post
4. contributor wants to change one word or some mistake, but he can't. he has only "submit to review" option and when he will click on it the published post is going to be unpublished. 

we need (or tell me where is it)  option as admins have "update", just changing one word or two without unpublishing published post.

**Comment by La-Geek** [comment]
This is totally okay. The role is like before WordPress 5.0 and does not break the backward compatibility.

Normally a contributor can't edit a published post (no difference, if he wrotes the post or someone else), and this is the behavio in Beta 5, what is good.

https://en.support.wordpress.com/user-roles/
(The roles in w.com and w.org are similar, except of the roles follower and viewer)

**Comment by youknowriad** [comment]
I'm closing as this works as expected, if you disagree with this behavior, consider opening a trac ticket to get more information.
