### ISSUE TITLE
Can't center images after last update

### ISSUE THREAD

**Issue by PaulLiles** [WordPress/gutenberg#9558]
After downloading Version 3.7.0, the ability to center images stopped?  The images will align right or left, but NOT the center??

Code from an image that I put in several days ago that works (previous version of Gutenberg):

<div class="wp-block-image"><figure class="aligncenter"><img src="http://lilesnet.com/dailydiary/wp-content/dailydiary/uploads/2018/09/nuts.jpg" alt="" class="wp-image-31762"/><figcaption>I have a little of everything!</figcaption></figure></div>

Code that Gutenberg put in today that does NOT work (the image is aligned right):  

Note: It shows in edit and preview that the image is centered like expected but in webview using Chrome the image is right aligned???

<div class="wp-block-image"><figure class="aligncenter"><img src="http://lilesnet.com/dailydiary/wp-content/dailydiary/uploads/2018/09/knee.jpg" alt="" class="wp-image-31796"/><figcaption>Ouch!</figcaption></figure></div>

**Comment by Soean** [comment]
Hey @PaulLiles,
thanks for your ticket, we already have an issue about this, see #9503. So I am closing this one.
