### ISSUE TITLE
I can't add new post after the latest update - 3.7.0

### ISSUE THREAD

**Issue by fatihozdemir** [WordPress/gutenberg#9559]
I am getting "The editor has encountered an unexpected error" notice when I try to add a new post after the latest update.

1. Go to 'Posts'
2. Click on 'Add Post'

It has happened after the last update.

**Screenshots**
https://ibb.co/mLawnz

 - OS: [MAC High Sierra]
 - Browser [safari]
 - Version [11.1.2 ]

**Comment by GlennMartin1** [comment]
This is almost certainly a conflict with Yoast. They have a bug which is supposed to be fixed Monday in version 8.1.1.

Disable Yoast until Yoast 8.1.1 is released.

**Comment by fatihozdemir** [comment]
Yeah, that's right. It works now after the disabling. Thanks.

**Comment by GlennMartin1** [comment]
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, and confirm the issue is addressed.
