### ISSUE TITLE
Unable to publish new post - editor crashes when trying to select a category 

### ISSUE THREAD

**Issue by Sixtina1990** [WordPress/gutenberg#9560]
When I am creating a new post and I click on the right side on "Category", everything crashes and I can't access my post for days, neither can I publish anything. 

I tried to reproduce it in all Browsers I have and always the same happens: Safari, Firefox, Chrome.

I attached screenshots of the error, please tell me how to solve this, so I can publish posts again. Let me know if you need any further information. Thank you so much! 

<img width="1133" alt="bildschirmfoto 2018-09-03 um 08 51 15" src="https://user-images.githubusercontent.com/42411182/44974555-f1e2fa80-af57-11e8-8d00-1fcf386c5cac.png">
<img width="954" alt="bildschirmfoto 2018-09-03 um 08 58 23" src="https://user-images.githubusercontent.com/42411182/44974556-f27b9100-af57-11e8-97c5-7d28b43fe325.png">

**Comment by Sixtina1990** [comment]
**Describe the bug**
Unable to publish new post - editor crashes when trying to select a category 

**To Reproduce**
Steps to reproduce the behavior:

Go to create a new post
>click on category on the right side under "document"
>error message appears immediately and I am unable to access this post for some days

Screenshots
Attached.

Desktop (please complete the following information):

OS 10.13.6
Safari 11.1.2, Chrome 68.0.3440.106

Additional context
>using latest version of Gutenberg

**Comment by Sixtina1990** [comment]
<img width="269" alt="bildschirmfoto 2018-09-03 um 09 13 48" src="https://user-images.githubusercontent.com/42411182/44975248-df69c080-af59-11e8-9ca5-de2d621bf691.png">

**Comment by Soean** [comment]
Hey @Sixtina1990,
thanks for this report.  Unfortunately, there is a bug in Yoast 8.1 which was made visible by the Gutenberg 3.7 update. They are working on a fix (see here https://github.com/Yoast/wordpress-seo/pull/10870) Yoast 8.1.1 should be published soon.

**Comment by GlennMartin1** [comment]
Yoast 8.1.1 has been released. Please update and activate your Yoast plugin, and confirm the issue is addressed.

**Comment by Sixtina1990** [comment]
@GlennMartin1 thanks for letting me know :) I just updated it and all works fine again :)
