### ISSUE TITLE
Unable to indent when choosing list block, even though option is available as a button

### ISSUE THREAD

**Issue by Sixtina1990** [WordPress/gutenberg#9561]
**Describe the bug**
Unable to indent when choosing list block, even though option is available as a button. ( see screenshot)

**To Reproduce**
1. Choose block "list"
2. Click on 'indent' button
3. Nothing happens

**Expected behavior**
The list should indent and not stick to the left like the rest of the text

**Screenshots**
attached.

**Desktop (please complete the following information):**
 - OS: 10.13.6
 - Browser : Safari, Chrome, Firefox
 - Version 11.1.2.; 68.0.3440.106

**Additional context**
- using latest version of Gutenberg
<img width="722" alt="list" src="https://user-images.githubusercontent.com/42411182/44974822-aed55700-af58-11e8-893f-3e94d8e6c39e.png">
.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by jorgefilipecosta** [comment]
Hi @Sixtina1990 it seems the indent buttons are working correctly in my tests. Watching by the image it seems they did not work because the selection was made from the first item so no item was available to be the parent e.g: if the first item is not selected the indent should work.
![sep-11-2018 11-34-34](https://user-images.githubusercontent.com/11271197/45355004-19207400-b5b7-11e8-9420-582406baaaa4.gif)

**Comment by Sixtina1990** [comment]
@jorgefilipecosta Thanks Jorge for the answer. :) I just tried again but it seems to be the way you said. The very first "dot" does not move/indent, only all the ones below, like in your video/image. But isn't that strange? Why would the first one not indent as well?

Basically I have a paragraph saying something, then I make double dots and then I list the items, e.g.

You can go swimming here:
-pool
-shower
-ocean

With this indent function it would look like this...
You can go swimming here:
-pool
        -shower
        -ocean

Is there smth with CSS or code again to overcome this? Thank you so much for your help. :)
