### ISSUE TITLE
Plugin incompatibility

### ISSUE THREAD

**Issue by jucunda** [WordPress/gutenberg#9568]
Wenn Sie schon eine neue Oberfläche anbieten, dann sollten sie auch die Nebenprogramme wie "Kontaktformular oder Buttons" aktualisieren. 
Sonst muss ich dafür immer in den klassischen Editor wechseln.

**Comment by Soean** [comment]
Hallo @jucunda,
die meisten Plugins kommen von unabhängigen Entwicklern, die ihr Plugin kostenlos auf wordpress.org bereit stellen. Einige Plugins funktionieren noch nicht mit dem neuen Editor und müssen noch angepasst werden. Bitte wende dich dazu, bsw. über die jeweiligen Plugin Support-Foren auf wordpress.org an die Entwickler. Diese findest du auf den Pluginseiten im Tab "Support".

WordPress ist ein internationales Projekt, das von vielen Freiwilligen weltweit entwickelt wird. Daher sollten wir uns auf englisch unterhalten.

If you have any further questions about the Gutenberg project or the plugins, we will try to answer them here

**Comment by jucunda** [comment]
Mein Englisch ist sehr schlecht. Ich finde, da machen Sie es sich zu leicht. Da sollten Sie sich mit diesen Betreibern auseinandersetzen und das zur Zufriedenheit ihrer (zahlenden) Kunden lösen.

Google-Englisch:
My English is very bad. I think that makes it too easy. There you should deal with these operators and solve this to the satisfaction of their (paying) customers.

**Comment by Soean** [comment]
WordPress ist eine kostenlose Open Source Software, für die keiner bezahlen muss. Alle arbeiten hier freiwillig in ihrer Freizeit oder werden von ihrem Unternehmen dafür freigestellt, um am Projekt mitzuarbeiten.

GitHub dient dafür bestimmte Fehler zu melden und diese zu beheben. Es gibt ein deutschsprachiges Support forum, bei dem deine Anfrage besser aufgehoben ist: https://de.wordpress.org/support/forum/allgemeine-fragen/
Um dir weiterhelfen zu können, solltest du dort aber genauere Angaben machen, was genau die Probleme sind und welche Plugins du installiert hast.
