### ISSUE TITLE
Issues with Featured Image, Spacers, and Media Library

### ISSUE THREAD

**Issue by JessiEoin** [WordPress/gutenberg#9574]
Hi, could anyone please help me? I'm having several issues with Gutenberg:

1. Featured Image isn't showing anything in the drop down area at all.
![featured image](https://user-images.githubusercontent.com/42937559/44988111-8ef16380-af57-11e8-9035-bda549fd8a3b.jpg)

2. I'm unable to select images from my Media Library when creating a new post. There is simply no option to do so-- I've had to upload directly from my computer each time.
![media library](https://user-images.githubusercontent.com/42937559/44988173-c6601000-af57-11e8-8b6b-5d3a6912b61f.jpg)

3. I was able to adjust the size of the spacer when I initially created a post, but two days later, that disappeared completely when I created a new post, leaving an annoyingly large spacer where I only needed a smaller one.
![spacer issue](https://user-images.githubusercontent.com/42937559/44988336-4ab29300-af58-11e8-96f7-bc49cffd47cb.jpg)

I'm really a beginner still to pretty much all website maintenance, so if anyone could explain to me in plain language the steps I need to take, I would very much appreciate it! Thank you!

**Comment by gziolo** [comment]
Can you provide more details? Which user role has the account you used when seeing this issue? Can you also share which operating system and browser you were using?

**Comment by gziolo** [comment]
@antpb - do you happen to know how does it compare to the Classic Editor? Are you able to access your own uploaded items when you don't have permissions to use Media Library?

**Comment by PivotDev** [comment]
@JessiEoin Are you, by chance, running Advanced Custom Fields? I was having both the featured image and media library issue you mentioned (can't speak to the spacer issue). Updating to Gutenberg 4.0.0 and ACF 5.7.7 fixed the two issues.

**Comment by gziolo** [comment]
@JessiEoin, can you try again with the latest changes introduced? We landed #4155 which should show proper messages when you can't manage media when using user's role with not enough capabilities.
