### ISSUE TITLE
Why is the Add title "block" not a block ?

### ISSUE THREAD

**Issue by polygbrl** [WordPress/gutenberg#9575]
For now (3.7.0 plugin version), the "Add title" component is displayed as if it was a block. In fact, it is more a document meta field than a block and I find it confusing having it there pretending to be a block. Let me explain my point of view.

### The "Add title" component is a heading
The *post name* and *a post title* isn't quite the same. The first is some document data (like the publishing date) and is related to the post's permalink. The second is a heading (text), with maybe the same value as the *post name*, displayed or not in the post content.

### How do I understand the "Add title" component now ?
The "Add title" component is displayed as a block, in the editor's post content. However, it can't be moved nor removed. It is also related to the permalink as it is where the permalink is shown. The editor seems to show us that the *post name* must be a *post title* starting at the very beginning of the post (no matter what) even if the theme isn't displaying it in the post content. This is breaking the idea of having a *wysiwyg* editor: the *post name* isn't the *post title* !

### A post title is theme related
Having *a post title* at the beginning of the post is more theme related. It should never be Gutenberg's choice. Having the same *post title* and *post name* is good for SEO but remains the user's and his theme's choice. If not, why is the publishing date in the document "status and visibility" panel and not an irremovable block under the "Add title" component ?

### What then ?
One thing for sure is that this component can't stay as somehow-a-block-but-not-really. I'm listing some ideas to make a good choice:
- A *post title* should be optional.
- A *post name* must be required and can be randomly generated if not provided.
- A heading block acting as a *post title* could be automatically added when a *post name* is given in the document panel.
- A *post name* block could be made. If not used, a randomly generated *post name* is given to the post.

> My question is in the title, which is part of the content, because it is a *post title*.

**Comment by Soean** [comment]
Also see `Give the title area a block description` #8469

**Comment by designsimply** [comment]
Thank you for posting! Making the title into a block is a planned update. We can consolidate this to #4482 and note that it is in the `To Do in Customization` project which that means it will be looked at after Gutenberg has been merged into WordPress core.

**Comment by designsimply** [comment]
Also see https://github.com/WordPress/gutenberg/issues/11553
