### ISSUE TITLE
Unable to de-indent a line inside a nested list.

### ISSUE THREAD

**Issue by vedanshujain** [WordPress/gutenberg#9576]
It seems impossible to visually de-indent a single line while working in a nested list. 

**Steps to reproduce the behavior:**

In Gutenberg editor, add content like in the following screenshot:

<img width="845" alt="screen shot 2018-09-03 at 7 03 00 pm" src="https://user-images.githubusercontent.com/7571618/44989664-2d0f1900-afac-11e8-821f-b7926ca8bb56.png">

**Expected behavior**
Ideally, I want to be able to out dent a line, at the parent's level, without breaking the parent's list numbering.

**Desktop**
 - OS: High Sierra 10.13.6
 - Browser: Firefox 61.0.2 (64-bit)

**Comment by Soean** [comment]
Maybe related to #9561

**Comment by ianbelanger79** [comment]
I am going to close this issue because it is related to another ticket
