### ISSUE TITLE
Shift + Arrow keys (and combinations) should work even with block boundaries faded out

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#958]
Steps to reproduce:

- Set focus in a text block. Start typing. Note the block boundaries fade out.
- Hold shift, press left arrow to select in that direction. 

Expected result: block boundaries fade in and you select one character leftwards.

Actual result: block boundaries fade in.

![may-31-2017 15-26-41](https://cloud.githubusercontent.com/assets/1204802/26634071/ba46c9b4-4615-11e7-93a9-d92ed8f8bda3.gif)

It's a bit hard to see in that GIF. Sometimes you _do_ select one character leftwards but that selection is immediately unset.

**Comment by iseulde** [comment]
Maybe I'm not understanding it correctly, but you wanted the boundaries to show when text is selected right?

**Comment by jasmussen** [comment]
> Maybe I'm not understanding it correctly, but you wanted the boundaries to show when text is selected right?

Yes absolutely! That part is working.

The problem is that as I'm writing text, using just the keyboard, every once in a while I'll want to delete a few characters, and I'll hold shift, press left, and delete. Only here, I have to press left twice to select a single character. 

Try the following in a normal text editor, then in the gutenberg editor, to see the difference:

1. type a little
2. hold shift, press left

In the normal text editor, the above will select one character. In gutenberg, currently, it doesn't select anything. You have to press left twice.

**Comment by jasmussen** [comment]
Just to clarify, I didn't want to suggest this was an issue with the inline boundaries specifically, but rather with the basic text block as a whole in gutenberg. I don't think it's a tinymce issue, actually.

**Comment by iseulde** [comment]
@jasmussen Is this still an issue? I can't reproduce in master.

**Comment by jasmussen** [comment]
You're right, this seems addressed! Thanks 🎉
