### ISSUE TITLE
Video Block: Captions do not inherit standard caption front-end styles

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9581]
**Describe the bug**

The Image and Embed Blocks (for instance) come with a set of standard image caption styles for the front end: 

<img width="561" alt="screen shot 2018-09-03 at 3 31 25 pm" src="https://user-images.githubusercontent.com/1202812/44992204-810b0500-af8e-11e8-8942-ed1c318ff69e.png">

The Video block does not inherit those styles:

<img width="602" alt="screen shot 2018-09-03 at 3 31 30 pm" src="https://user-images.githubusercontent.com/1202812/44992200-7fd9d800-af8e-11e8-9c32-f1ddf23885ac.png">

(Screenshots taken using Twenty Seventeen)

**To Reproduce**
1. Add a video block, and add a caption.
2. Add an embed or image block, and add a caption to that one too. 
3. View/preview the post on the front end. 
4. Observe that the Video block caption style does not match the style of the Image/Embed caption. 

**Expected behavior**

I expected these captions to be identical on the front end.

**Tested in:**
Gutenberg 3.7, Using Twenty Seventeen, Twenty Sixteen, and Twenty Fifteen.

**Comment by nfmohit-wpmudev** [comment]
Submitted #9609 addressing this bug.
