### ISSUE TITLE
Ability to convert embed blocks to paragraphs

### ISSUE THREAD

**Issue by swissspidy** [WordPress/gutenberg#9587]
**Describe the bug**

I just happened to convert an old post to blocks and noticed that I can't convert an embed block to something else.

The old post content looked like this:

```
Some text

https://wordpress.org/ideas/

Some more text
```

**To Reproduce**
1. Create a new post
2. Paste a URL like `https://wordpress.org/ideas/` and notice that it can't be embedded
3. Notice a request to `…wp-json/oembed/1.0/proxy?url=https%3A%2F%2Fwordpress.org%2Fideas%2F` with the following response:  
  ```json
{"provider_name":"Embed Handler","html":"<a href=\"https:\/\/wordpress.org\/ideas\/\">https:\/\/wordpress.org\/ideas\/<\/a>"}
  ```
4. Realize that there's no way to have this URL on a line on its own

**Expected behavior**

WordPress turns non-embeddable URLs to links in the classic editor. The same should happen here, or at least I should have the option to do so.

For this, the `html` part of the oEmbed proxy response could be used to create a paragraph block with a link in it (automatically or by manually converting the block).

**Screenshots**

<img width="727" alt="screen shot 2018-09-03 at 18 22 04" src="https://user-images.githubusercontent.com/841956/44996103-5cbb2280-afa6-11e8-862f-22fd6606d5da.png">

**Desktop (please complete the following information):**
 - OS: macOS 10.13
 - Browser: Chrome 68

**Comment by youknowriad** [comment]
I think there's already an issue for "not turning links into embeds if they're not embeddable" 

When it comes to converting Embeds to paragraphs, I think we shouldn't support it for now because if it's a valid embeddable URL, WordPress will turn it into an embed in the frontend whether it's in a paragraph or not.

**Comment by youknowriad** [comment]
I'm closing as duplicate. Thanks
