### ISSUE TITLE
Max 8 taxonomy type meta tabs

### ISSUE THREAD

**Issue by RavanH** [WordPress/gutenberg#9589]
**Describe the bug**
When a custom post type has more than 8 custom taxonomies, number 9 and onward are not shown in the Gutenberg meta sidebar.

This bug seems to have been introduced in the latest update: Version 3.7.0

**To Reproduce**
1. Create a custom post type and attach 9 taxonomies
2. Go edit a post or create new one
3. Notice how on the right side only the first 8 taxonomy meta tabs are present

**Expected behavior**
Unlimited taxonomy meta tabs

**Desktop (please complete the following information):**
 - Browser Chrome, Firefox

**Comment by caxco93** [comment]
Confirmed that the sidebar shows a maximum of 8 custom taxonomies.
![image](https://user-images.githubusercontent.com/3190666/45064727-fa802180-b07a-11e8-8c2b-96c44f2918d6.png)

**Comment by RavanH** [comment]
Fantastic, thanks :)
