### ISSUE TITLE
Unable to edit slug for a page

### ISSUE THREAD

**Issue by rossahall** [WordPress/gutenberg#9590]
**Describe the bug**

The feature to edit the slug for a page or post is missing. This is present in 4.6, so assume it is another basic feature that isn't working properly.

**Comment by youknowriad** [comment]
Did you try to click on the post/page title? It should show up. 

We think it's not great at the moment and there are open issues to improve it but it's definitely there.

**Comment by GlennMartin1** [comment]
It is possible to edit.

On the post/page, click the Title, and the permalink will display just above the title, along with an Edit button.

**Comment by youknowriad** [comment]
I'm closing. Let's discuss improvements in #8949 and #6268
