### ISSUE TITLE
Basic Code Editor

### ISSUE THREAD

**Issue by cjc1867** [WordPress/gutenberg#9593]
Hi
Just switched to the code editor view on a page using Gutenberg plugin and there’s no code editor.

Viewing as HTML as well doesn’t give you the basic code editor.

Is this going to be added?

Kind regards

Colin

**Comment by Soean** [comment]
Hey @cjc1867 ,
you don't see the editor or do you mean there is no code highlighting?

**Comment by cjc1867** [comment]
If I switch to see the html version I don't see the basic code editor. Is it there and for some unknown reason I can't see it?

With the Classic editor I only use the Text view so that I have complete control with the html code and you get a basic code editor to add the code. Using Gutenberg editor I don't see the code editor.

I hope this makes sense.

**Comment by tofumatt** [comment]
I don't think there's a plan to add a code-highlighting, syntax-aware editor to Gutenberg right now; that'd be a big undertaking (or would require using a third-party one, increasing the editor size substantially) for relatively little gain: there will be better dedicated code editors, which is probably the best place to edit large amounts of HTML if that's how you want to edit your posts.

Or maybe a third-party, Gutenberg-aware, editor would be cool.

**Comment by tofumatt** [comment]
I just fired up the Classic Editor and I don't see syntax highlighting or anything like an advanced code editor experience:

![2018-09-06 20 27 42](https://user-images.githubusercontent.com/90871/45180451-58e00800-b213-11e8-8e25-ef58f68051d5.gif)

Do you maybe have an editor plugin installed on your site that adds this ability?

**Comment by cjc1867** [comment]
Click on the Text view and not Visual.

**Comment by tofumatt** [comment]
The GIF I posted starts in text view.

**Comment by cjc1867** [comment]
It's text view is what I am referring to as it is a very basic code editor and I don't see it in the Gutenberg one.

I am not asking for a fully blown code editor but the one under Text view.

**Comment by tofumatt** [comment]
Oh! Okay I totally misunderstood. You can access the "Code editor" in Gutenberg via the "More" menu:

![2018-09-06 20 47 04](https://user-images.githubusercontent.com/90871/45181336-15d36400-b216-11e8-90a3-7715198d5f76.gif)

There's a keyboard shortcut as well, which you'll see next to the menu option (it varies based on your operating system).

Hope that helps!

**Comment by cjc1867** [comment]
![basic-code-editor](https://user-images.githubusercontent.com/4077090/45182345-db1efb00-b218-11e8-95e3-db8348650a12.png)

Highlighted in Yellow is what I am after and I can't see it.

**Comment by tofumatt** [comment]
Ah, I understand. My understanding is we won’t be providing that functionality in the code/text editor of Gutenberg. There are blocks for those controls though.

**Comment by cjc1867** [comment]
Just tried adding a code block and no basic editor so it won't be any use to me or others. I will be sticking to the Classic Editor as I will have more control.

Hopefully Gutenberg can be switch off or have an option what I want to use and not be forced to use this.
