### ISSUE TITLE
"hidden_meta_boxes" Filter Does Not Work When Gutenberg and Classic Editors are Active

### ISSUE THREAD

**Issue by arkytn** [WordPress/gutenberg#9596]
**Describe the bug**
When the Gutenberg and Classic editor plugins are active, the "hidden_meta_boxes" filter does not hide any meta boxes.

**To Reproduce**
1.     add_filter('hidden_meta_boxes', 'on_hidden_meta_boxes', 10, 3 );

2.   
function on_hidden_meta_boxes($hidden, $screen, $use_defaults){
    if($screen->id == 'asset'){  
      $hidden[] = 'commentstatusdiv';  
      $hidden[] = 'commentsdiv';  
      $hidden[] = 'page-links-to';  
      $hidden[] = 'pageparentdiv';  
    }  
  
    return $hidden;  
  }  

3. Meta boxes will not be hidden .

**Expected behavior**
Should hide the hidden set of metaboxes and un-check the Screen Options for those boxes.

**Desktop (please complete the following information):**
 - OS: [e.g. Win10, Linux]
 - Browser [e.g. All]
 - Version [e.g. WP 4.9.8]

**Additional context**
Gutenberg Version 3.7.0
Classic Editor Version 0.4

**Comment by danielbachhuber** [comment]
Thanks for the report, @arkytn.

Can you try changing your hook priority to 11?

```
add_filter('hidden_meta_boxes', 'on_hidden_meta_boxes', 11, 3 );
```

Gutenberg has some code to disable hidden metaboxes, because there isn't corresponding Screen Options UI for managing them. It may be that we need to apply the Gutenberg code on an earlier priority. Previously #7570 #9232

**Comment by arkytn** [comment]
Very good. The higher priority did indeed solve the problem. Thank you
