### ISSUE TITLE
Paragraph block: Allow usage of wide and full block alignment

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#9597]
## What?
I think you should be able to use the wide and full block alignments with the Paragraph block.

## Why?
Sometimes, you want to make a single paragraph stand out from the rest of a post or page. Gutenberg already provides background and text options in the Paragraph for this very reason. I think the ability to make a specific paragraph wider than the rest of an article is another good way to make it stand out.

## How?
I think the wide and full block alignment options should be shown in the block inspector, since they would not be commonly used options.

**Comment by mtias** [comment]
Paragraph block used to have this setting but it was removed because it made using paragraphs more confusing and complex. This is a case where the section block would be better. It'd be nice to have a simple transform from paragraph to paragraph-within-section too.

**Comment by nickfmc** [comment]
I still wish this would come back :( a lot of people are switching their themes to this type of layout https://github.com/WordPress/gutenberg/issues/25160 and not having this really makes nesting a paragraph inside a full width or wide with div hard, if you are saying by default things are not 100% but limited to your regular block wrapper width. @mtias when you say "the Section Block" to what are you referring as WP has no "section block" to my knowledge

**Comment by mtias** [comment]
It referred to what became the "group" block

**Comment by paaljoachim** [comment]
Hey @mtias 
Let's add the alignment controls to the Paragraph block similar to what we have in the Heading block. As Heading has it and Paragraph does not creates a lack of consistency in relation to the two text blocks.
