### ISSUE TITLE
Нет произвольных полей

### ISSUE THREAD

**Issue by ErdTim** [WordPress/gutenberg#9598]
**Describe the bug**
Нет произвольных полей в редакторе.

does not show fields.
Advanced Custom Fields 4.4.12

**Comment by Soean** [comment]
Gutenberg will be compatible with Advanced Custom Fields 5, see https://www.advancedcustomfields.com/blog/the-state-of-acf-in-a-gutenberg-world/

**Comment by youknowriad** [comment]
Duplicate of #8539
