### ISSUE TITLE
restricted services issue in iran

### ISSUE THREAD

**Issue by sazmankav** [WordPress/gutenberg#9601]
Hi, i was using "gutenberg" in one of my websites last week properly. after resetting my website and reinstalling the wordpress i couldn't use gutegberg and editing page didn't load at all. last night i used a VPN and suddenly gutenberg worked! 
now i have this question: is the services of this plugin restricted in any country?

**Comment by GlennMartin1** [comment]
That's unlikely the reason. Another possible reason - do you use Yoast?

Yoast 8.1.0 had a bug that caused the backend to crash in some cases. Yoast 8.1.1 was released yesterday which resolved that issue.

**Comment by sazmankav** [comment]
Dear Glenn, good day. 
No i don't use Yoast at all. i have deactivated all other plugins and test if gutenberg works, but it wouldn't work(load) unless i use a VPN. and i don't have many plugins just 3 plugins more than default plugins .
(in case you know everything I had some problems with AIOW security last week that caused complete resetting and reinstalling of the website because of admin login problem. so installation is new. )

**Comment by mintplugins** [comment]
If you check in the javascript console, do you see any errors coming up? Specifically I'm wondering if there are 404 errors. If there are, that might indicate some sort of a firewall blocking parts of the page from loading. If not, it's likely not a VON/Location issue. That's the first thing I would check to investigate that further. 

- To open the console, in Google Chrome right click on the page and then click "Inspect".
- In the popup that appears, click on the "Console" tab.

**Comment by sazmankav** [comment]
because of time restrictions, I told my Server company to reset website and all values to its defaults again. now gutenberg is working.  i think it was that All In One Wordpress Security plugin issue.  thanks everyone.
