### ISSUE TITLE
Keyboard shortcuts for list items are missing 

### ISSUE THREAD

**Issue by skorasaurus** [WordPress/gutenberg#9611]
Similar issues filed: #4181, #5087, #7051, #12142.

While editing a post in Gutenberg, I couldn't figure out how to indent list items by the keyboard which is a habit of mine (and I'd argue many others editors as well). 

**Describe the bug**
No keyboard shortcuts display for the list block. 

Mentioned in https://github.com/WordPress/gutenberg/issues/7051 but that issue is not dedicated to this, I decided to make a new issue for this; close if this is too explicit. 

**To Reproduce**
without looking on a separate page of documentation, right now: 

1. add a new page or edit a page in Gutenberg
2. add a list block, 
3. try to indent a list item using only the keyboard; did ya have to look at the docs :D. 

**Expected behavior**
Personally, the expected action to indent an item in a list block would be done by issuing 'TAB' but that has been [decided against for accessibility reasons](https://github.com/WordPress/gutenberg/issues/4181#issuecomment-354091113)
That the default behavior isn't used stresses the utility of having the keyboard shortcuts for list actions (outdenting, indenting) available. 

**Screenshots**
see https://user-images.githubusercontent.com/1682452/40778281-f1054ca2-64d0-11e8-953f-704ef1e5ba1d.png

**Additional context**
- (Update: still present in WordPress 5.0.2) 
(Issue made on CPL time)

**Comment by mtias** [comment]
> While editing a post in Gutenberg, I couldn't figure out how to iNdent list items by the keyboard which is a habit of mine (and I'd argue many others editors as well).

This is quite annoying for me too. It's a bit blocked in that the expected behaviour is to use tabs, but that can interfere with keyboard navigation.

@mcsf do we have other issues for this? Can we consolidate? I'd like to move forwards with using tabs and showing that shortcut in the tooltip.

**Comment by skorasaurus** [comment]
@mtias - See https://github.com/WordPress/gutenberg/issues/7051 and #4181

**Comment by iseulde** [comment]
As noted in https://github.com/WordPress/gutenberg/pull/10744#issuecomment-438634036, the current list shortcuts aren't the best. I think we should update them before making them more visible.

**Comment by iseulde** [comment]
@afercia Any ideas for good list indentation shortcuts that don't cash with the browser/OS?

**Comment by afercia** [comment]
@iseulde I'm afraid there's no _Escape_ 😆 from potential clashes. As mentioned in https://github.com/WordPress/gutenberg/issues/4181#issuecomment-354314096 Google Docs uses Cmd+square brackets and yes, they clash with browsers history navigation on macOS. Also Gmail uses the same combination:

<img width="341" alt="screenshot 2018-11-21 at 13 14 07" src="https://user-images.githubusercontent.com/1682452/48840975-6c215f00-ed90-11e8-91a8-a259b08bcca4.png">

Any keys combination will always have a chance to conflict with browsers, OSes, and assistive technologies shortcuts. Also, users have different needs. The only real solution to this problem is a mechanism to allow users to remap shortcuts based on their own needs. See https://github.com/WordPress/gutenberg/issues/3218. I understand at this point of the release cycle that's not feasible, but #3218 is open since more than _one year_ and it hasn't been prioritized by the team.

At this point I can only suggest to try with two modifier keys. Maybe `primaryAlt` + square brackets? Not sure about the alternative `m` shortcuts, they never made too much sense to me. Maybe `primaryAlt` and some more meaningful letters?

**Comment by iseulde** [comment]
What are the action items here?

**Comment by afercia** [comment]
@aduth #5807 was an experiment and we've decided to not implement it. role=application destroys any native semantics, i.e. any document information, as the page is not treated as a document any longer. That means no lists of heading announced, no list of links, no screen reader shortcuts to navigate through elements, no landmarks, etc. etc.
role=application should be used only for apps that needs to be treated differently from a web document, where every interaction is replicated with JavaScript and any lost semantics is rebuilt with ARIA. 

Also, as already noted in previous issues and although Google Docs is not comparable to Gutenberg, it is true that the tab key works for indentation but the keyboard shortcut exposed to users is (on a mac) `Cmd + ]` / `Cmd + [`:

<img width="425" alt="screenshot 2019-01-04 at 08 58 45" src="https://user-images.githubusercontent.com/1682452/50678490-357d6c00-0fff-11e9-9eee-56e79f7cd563.png">

**Comment by mcsf** [comment]
As much as I'd like the convenience of using <kbd>tab</kbd> for list indentation, I gather from @afercia that we still have a ways to go to make that happen. I think we could at least start with something like <kbd>cmd + ]</kbd>. Two questions that stand:

- Can we compile idiomatic shortcuts from platforms other than macOS? Mostly Windows and whatever Google Docs does on Linux desktops (@nosolosw: AFAIR your daily driver is Linux; could you have a quick look?)
- <kbd>cmd + ]</kbd> will require more than two keys to compose on many non-US keyboards (as a personal example: <kbd>cmd + alt + 9</kbd>). That's not necessarily a dealbreaker, just something to be aware of, and let's make sure that the shortcut doesn't break for those keyboard layouts.

**Comment by afercia** [comment]
True that square brackets are not directly available in some keyboard layouts. As mentioned in many other issues, the only real solution to this and to potential shortcuts conflict is a mechanism to allow users to re-map the shortcuts. See https://github.com/WordPress/gutenberg/issues/3218

**Comment by nosolosw** [comment]
@mcsf In Linux, the control keys are either CTRL, CTRL+ALT. ALT and ALT+SHIFT are reserved to open menu items.

This is how Google Docs Keyboard Shortcuts looks like for me (Ubuntu Linux w Firefox browser):

**Text formatting**

![text-formatting](https://user-images.githubusercontent.com/583546/50778786-18ff5f00-129f-11e9-85ef-f69f40e33d36.png)

**Paragraph formatting**

![paragraph-formatting](https://user-images.githubusercontent.com/583546/50778785-18ff5f00-129f-11e9-9ab4-d13e86a9290a.png)

**Editing**

![editing](https://user-images.githubusercontent.com/583546/50778783-1866c880-129f-11e9-825f-1dcdc31e8533.png)

**Comment by nosolosw** [comment]
Actually, I've realized indentation was not part of the shortcuts I captured and I can only know the shortcut if I search for "indent"! Crazy GDocs. It looks like there are two shortcuts for Indentate paragraphs/lists on Google Docs:

* Increase indent: CTRL+] or TAB
* Decrease indent: CTRL+[ or SHIFT+TAB

Only the first one gets announced through the shortcuts help menu:

![indent](https://user-images.githubusercontent.com/583546/50780945-8366ce00-12a4-11e9-9e18-587695626e2a.png)

**Comment by mcsf** [comment]
Thanks for the insight, @nosolosw!

**Comment by mcsf** [comment]
Wild idea: what if <kbd>space</kbd> and <kbd>backspace</kbd> could be used at the start of a list item to indent in/out?

**Comment by iseulde** [comment]
@mcsf I like your idea! Would it be strange to require two spaces? Backspace definitely makes a lot of sense.

**Comment by iseulde** [comment]
> Hm, at least on first consideration, two spaces would seem awkward to me. Single space seems more discoverable and natural. What do you think?

Sounds good, if we work towards it being undoable.

> <kbd>space</kbd> / <kbd>backspace</kbd> as keyboard shortcuts for that sounds very odd to me.

Could you elaborate? Or does it merely sound odd?

**Comment by iseulde** [comment]
I like it because it's a bit inspired by Markdown, where you would create the following:

```md

* base
  * indented
```

**Comment by mcsf** [comment]
> we could try if there are no a11y drawbacks

Definitely. This was, in my mind, a way to keep <kbd>tab</kbd> intact, as well as keyboard arrows. Indentation events (increase/decrease) would be announced (`wp.a11y.speak`).
