### ISSUE TITLE
The BaseControl (TextControl etc.) label is too wide

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#9612]
By default, the BaseControl `<label>` element is styled as a block element with `display: block;`. The controls that extends from it, for example TextControl, inherit the "block" label.

While this may not be a big issue for controls that are rendered in the narrow space (e.g. the sidebar):

<img width="330" alt="textcontrol label 1" src="https://user-images.githubusercontent.com/1682452/45046587-dde1ea80-b076-11e8-9a12-24d81c58c329.png">

it may be a bit annoying when the space is wider, for example in the content area, where the chance to trigger unwanted clicks is higher:

<img width="699" alt="textcontrol label 2" src="https://user-images.githubusercontent.com/1682452/45046589-dde1ea80-b076-11e8-815a-001ed15b77fd.png">

As a small enhancement, maybe worth considering some different styling.

**Comment by karmatosed** [comment]
Assuming it adapts well I think a good iteration so design approving this.
