### ISSUE TITLE
Core blocks: Block alignment and text alignment should use different and consistent attribute names

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#9614]
## The issue
I have noticed that `supports: { align: true }` adds an `align` attribute to a block. Notably, core blocks that have text alignment options tend to name the text alignment attribute `align`. I think this is confusing, and it makes it difficult to update blocks to support block alignment later on. I think the name used for block alignment vs text alignment attributes should be made more consistent.

## Proposed solution
I think that block alignment attributes should remain as `align`, and I think text alignment attributes should be called `textAlign`.

## Related issues and PRs
- #7912

**Comment by 0aveRyan** [comment]
This is a great callout @ZebulanStanphill!

**Comment by youknowriad** [comment]
I think it's too late to change any block attribute at the moment.
Also there has been some work recently to bring consistency to the "align" support usage. Right @ZebulanStanphill
