### ISSUE TITLE
Color settings on paragraph has lost padding

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#9616]
Just noticing what maybe is a little regression:

![2018-09-04 at 21 26](https://user-images.githubusercontent.com/253067/45055927-3d48f600-b089-11e8-94ce-542f2aa3a3f1.png)

**Comment by ianbelanger79** [comment]
Hey @karmatosed, what browser are you seeing this in? I don't see this issue on Chrome or Firefox, Windows 10 OS.

**Comment by karmatosed** [comment]
This is in Chrome using latest version.

**Comment by karmatosed** [comment]
Interestingly it seems to be applying a 'last' class to not the last one to get this:

![2018-09-04 at 22 03](https://user-images.githubusercontent.com/253067/45057793-7b94e400-b08e-11e8-9556-78ece6b4d703.png)

**Comment by youknowriad** [comment]
Right @afercia I opened #9654 to fix it
