### ISSUE TITLE
[Enhancement] as MS Word, offer ipsum inserter...

### ISSUE THREAD

**Issue by GlennMartin1** [WordPress/gutenberg#9618]
No doubt, many/most web developers use lorem ipsum on a regular basis.

Microsoft Word has a nifty shortcut to insert a segment of lorem ipsum text. See https://www.labnol.org/software/lorem-ipsum-in-microsoft-word/8532/

Gutenberg should do something similar. By typing `/lorem`, it could insert Loren ipsum in paragraph blocks.

It would be a great timesaver for me and probably many others. 

Thanks for your consideration.

**Comment by tofumatt** [comment]
This is a cool idea and would actually make for a great block (that's what the `/` inserter is: a shortcut to bring up a searchable list of block). A "Lorem ipsum" block!

So we won't be adding this feature in core Gutenberg but a block to do so as a plugin is a great idea and should be pretty straightforward to implement!
