### ISSUE TITLE
Display of invalid block warning inside a column block needs improvement

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#9627]
**Describe the bug**
Adding a column block and then invalidating a block inside a column results in a lot of boxes and general overflowing:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/45094749-1a175880-b114-11e8-94b6-c156b1c4e4d3.jpg)

I know the columns block is marked as beta so this may be a problem that is being looked at elsewhere, but logging it so it gets tracked.

**To Reproduce**
1. Add a column block
2. Type some text in the first column
3. Click the block ellipsis and 'edit as html'
4. Remove the trailing `</p>` to trigger the invalid block warning and see the above screenshot

**Expected behavior**
Not entirely sure. Fewer boxes and no overflow!

**Comment by youknowriad** [comment]
<img width="739" alt="Capture d’écran 2019-10-29 à 5 57 54 PM" src="https://user-images.githubusercontent.com/272444/67790198-a5208400-fa75-11e9-8f59-e69830541f0c.png">

This seems way better these days.
