### ISSUE TITLE
Removing core taxonomy from post produces and error when publishing

### ISSUE THREAD

**Issue by vguerrerobosch** [WordPress/gutenberg#9629]
**Describe the bug**
Removing a core taxonomy (category or post_tag) from posts produces and error when publishing.

**To Reproduce**
1. Add the following code to `functions.php` in the active theme:

```
function my_custom_theme_init() {
	unregister_taxonomy_for_object_type( 'post_tag', 'post' );
}

add_action( 'init', 'my_custom_theme_init' );
```

2. Create a new post and publish it.
3. See error `TypeError: n.types.some is not a function`.

**Expected behavior**
Post publishing normally.

**Desktop**
 - OS: Mac OS 10.12.6
 - Browser [Chrome]
 - Version [68.0.3440.106]

**Additional context**
- Gutenberg 3.7.0.

**Comment by designsimply** [comment]
Can you try the PR #9744 to see if it fixes your issues? See #9693.

**Comment by vguerrerobosch** [comment]
Yes, PR #9744  fixes the bug.

**Comment by youknowriad** [comment]
👍
