### ISSUE TITLE
Add error boundaries around plugin components and inside api functions.

### ISSUE THREAD

**Issue by Xyfi** [WordPress/gutenberg#9630]
**Is your feature request related to a problem? Please describe.**
We would also like to see error boundaries around plugins and maybe also inside of API methods, so if a plugin integration malfunctions, the editor (and other plugins) continues to function normally and an error can be shown which plugin caused the error. This also allows non-developer users to see what plugin is not functioning properly.

**Describe the solution you'd like**
Add a `PluginErrorBoundary` component, that will be rendered as a top-level component around plugin elements in `wp.api.registerPlugin`. This error will make sure an error is shown telling the user what Plugin is faulty.

Add `try/catch` clauses inside of public facing API methods to prevent plugins from causing Gutenberg to crash.

**Comment by gziolo** [comment]
Some other places to implement errors catching in code registered by plugins:
* `withSelect` / `useSelect`
* `withDispatch` / `useDispatch`
* `withFilters`
* `PluginArea`

#16842 is slightly related in terms of seeking the way which plugin triggered an error.

**Comment by Mamaduka** [comment]
I've started working on this enhancement.

I think using notices to display error messages is our current best option. Plugins can use different slots or decide not to render, so they have no single point of rendering.

We have two options when it comes to dispatching the notices:

1. Dispatch them from the error boundary, but this would require adding a `data` package as a dependency.
2. Add the `onError` prop and let the editors handle notices.

What do you think, which options should we use?

Personally, I prefer the second option and keeping the `plugins` package light on dependencies.
