### ISSUE TITLE
Undo doesn't recognize changing font style

### ISSUE THREAD

**Issue by nabsul** [WordPress/gutenberg#9636]
When I type some text and then change the font (bold, italic, etc.), and then press ctrl-z to undo the font change, I end up losing the text I just typed as well. Seems the font change isn't considered a "step" that can be undone.

1) Type some text, 
2) highlight the text and make it bold by pressing ctrl-b, 
3) press ctrl-z to undo.

Expected behavior: The text that was made bold goes back to being not-bold.

Actual behavior: The text I just typed gets deleted. Moreover ctrl-shift-z doesn't re-type the text so my work is lost.

OS:
 - OS: Windows
 - Browser Chrome
 - Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by mtias** [comment]
This seems to have been addressed. Could you test again and reopen if it still happens? Thanks!
