### ISSUE TITLE
Avoid hardcoding WP Links inside Gutenberg

### ISSUE THREAD

**Issue by youknowriad** [WordPress/gutenberg#9637]
We use links to target WP Admin pages inside Gutenberg packages
 
- revisions
- Shared blocks management
- ...

These links only work in WP context and the packages are meant to be context agnostic.
We need to find a way to add these links in an "augmented" manner. Keeping the packages WP links free.

**Comment by paaljoachim** [comment]
Is this issue still relevant?

**Comment by youknowriad** [comment]
yes :)

**Comment by paaljoachim** [comment]
Alrighty. Let's keep it open..:)

**Comment by ramonjd** [comment]
Possibly related:

- https://github.com/WordPress/gutenberg/issues/59536

Maybe the links could be generated in the WP backend and only display when they're accessible via editor settings in JS?

**Comment by youknowriad** [comment]
I think for the block editor package and agnostic packages, there's no hard coded links anymore.
