### ISSUE TITLE
Chrome OS/General difficulties 

### ISSUE THREAD

**Issue by willcunningham** [WordPress/gutenberg#9638]
**Describe the bug**
The whole Gutenberg Editor is rife with errors.   I get an "Update Failed" error at top of screen, when saving, or editing a post.  Nothing saves therefore. (2) I added a Block,  you cannot move the Block "Up or Down."    The Second paragraph I wrote (the second Block I added) automatically moves to the Top of the first paragraph (the first Block.) (3) Moving the second Block UP melded into the first Block;  (4) The Second Block floated or moved ontop of the first block - since there was text in the first block I couldn't see what I was writing in the second block (5) The second block when moved above the first block pushed text of the first block over, (6) Not sure any of this matters because nothing is saved. (7) Since you can't just write text into the new editor I'm not sure anything works at all -- Since there are so many Errors and Bugs I'm wondering if this has to do with the fact that I am using a Chrome Browser on a Chrome OS Pixelbook.   Will this even work?  
**To Reproduce**
1.  I couldn't even write two paragraphs using two Blocks,  I could get no further than that. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Chrome OS]
 - Browser [e.g. chrome, ]
 - Version [Version 68.0.3440.118 (Official Build) (64-bit)]

[end] 

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description.
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by ianbelanger79** [comment]
Hi @willcunningham,

Thanks for your report and I am very sorry to hear about your difficulties with the new editing experience. We are looking into the problems on Chromebook and will address your issues as soon as possible.

**Comment by willcunningham** [comment]
Thank you Ian, I've uninstalled the Gutenberg editor and I look forward to your progress on the issue. Thanks and good luck! -BC 


Sent from Samsung Galaxy smartphone.
-------- Original message --------From: Ian Belanger <notifications@github.com> Date: 9/5/18  2:53 PM  (GMT-05:00) To: WordPress/gutenberg <gutenberg@noreply.github.com> Cc: willcunningham <william@williamcunningham.us>, Mention <mention@noreply.github.com> Subject: Re: [WordPress/gutenberg] Chrome OS/General difficulties  (#9638) 
Hi @willcunningham,
Thanks for your report and I am very sorry to hear about your difficulties with the new editing experience. We are looking into the problems on Chromebook and will address your issues as soon as possible.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/WordPress/gutenberg","title":"WordPress/gutenberg","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/WordPress/gutenberg"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ianbelanger79 in #9638: Hi @willcunningham,\r\n\r\nThanks for your report and I am very sorry to hear about your difficulties with the new editing experience. We are looking into the problems on Chromebook and will address your issues as soon as possible."}],"action":{"name":"View Issue","url":"https://github.com/WordPress/gutenberg/issues/9638#issuecomment-418841197"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/WordPress/gutenberg/issues/9638#issuecomment-418841197",
"url": "https://github.com/WordPress/gutenberg/issues/9638#issuecomment-418841197",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [WordPress/gutenberg] Chrome OS/General difficulties  (#9638)",
"sections": [
{
"text": "",
"activityTitle": "**Ian Belanger**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@ianbelanger79",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"WordPress/gutenberg\",\n\"issueId\": 9638,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"WordPress/gutenberg\",\n\"issueId\": 9638\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/WordPress/gutenberg/issues/9638#issuecomment-418841197"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 376277251\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by jorgefilipecosta** [comment]
Hi @willcunningham, Gutenberg passed by many changes since this issue was opened. Would it be possible to do a new test with ChromeOS and verify if any of these issues still apply? Thank you in advance!

**Comment by noisysocks** [comment]
Closing this out, but happy to re-open if there's more info on how to create the issue.
