### ISSUE TITLE
Break variables stylesheet up

### ISSUE THREAD

**Issue by MichaelArestad** [WordPress/gutenberg#964]
Currently, the variables are in a single massive junk drawer of a stylesheet. Break them up for more context and simplicity. I would also keep the variables relevant to specific components with those specific components (most of the stuff in the Other section).

You may also look into a breakpoints mixin that avoids pixel overlap, but I trust @mtias work that out if needed.

**Comment by youknowriad** [comment]
Not exactly related to this, but worth noting that we're using these common stylesheets in `blocks`, `components`, `editor` .... (basically all the modules) but they are declared inside the `editor` module, we should move them to a global "assets" folder I think.

**Comment by nylen** [comment]
Also semi-related, it looks like we're currently duplicating a lot of stuff across all of our Webpack builds ([ref](https://github.com/WordPress/gutenberg/blob/cb45cf800beedb7ff91410296468bdd4a760e2a0/webpack.config.js#L77)).

In the development build, **every single stylesheet** (not just every Webpack target) gets all of the comments from [`_variables.scss`](https://github.com/WordPress/gutenberg/blob/cb45cf800beedb7ff91410296468bdd4a760e2a0/editor/assets/stylesheets/_variables.scss#L1) added to it.  I am not sure if there is more duplication beyond just the comments, but ideally this should only be included once globally.

**Comment by MichaelArestad** [comment]
I would also make most of the comments `// this style of comments` since they aren't output. The duplication of variables doesn't really matter much unless an expected cascade (or changed variable) is supposed to happen halfway through for some reason (don't do that). Also, I'm pretty sure the comments can be stripped out for the build regardless.
