### ISSUE TITLE
Quickly Reorganize parts from content structure menu

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#9652]
Hello, 

I was thinking of a way to easily reorganize chunks of content directly from this menu : 

![capture 2018-09-06 a 12 11 16](https://user-images.githubusercontent.com/1785489/45151502-d0d80f00-b1ce-11e8-8a25-9a3d233dd58b.jpg)

Imagine I want to invert my 2 h2 titles, with a drag'n'drop feature I could invert the two (the hard part is, when I do this, all blocks from this title to the next one are following). 

This idea is inspired a lot by the Elementor navigator feature : 

![navigator-cover-36v3wiksjtblrd54tye9z4](https://user-images.githubusercontent.com/1785489/45151579-00871700-b1cf-11e8-94f2-52ed97ad6993.png)

As a writer, I sometimes change my mind and changes the order of my content (like, often). Do you think it could be a good idea?

**Comment by designsimply** [comment]
A similar request was made in #9100 and closed with the following note:

> I think at least for phase one this feels like a plugin / idea territory over something to include. I am going to close this, however let me totally put in the idea project as I am not saying at all we couldn't consider this later.

Because of that, I'm going to close this issue for now but with a note that, even though it is not currently a planned update, it can be re-visited later based on additional feedback as it comes in.

**Comment by maximebj** [comment]
Yes of course, It's just an idea and it's not necessery now. thanks for the answer !
