### ISSUE TITLE
Font Style Not Applied To Entire Selected Text

### ISSUE THREAD

**Issue by reginabally** [WordPress/gutenberg#9658]
Font styling (bold and italic) did not apply to the entire selected text if they're not on the same line. So far I have only tested with Paragraph and List blocks and the issue happened to these two types of blocks.

I'm running WordPress 4.9.8 Multisite with Gutenberg Version 3.7.0.
**Note**: The PHP version of my web host is currently defaulted as 5.6.37.

**To Reproduce**
1. In a Paragraph or List block, enter texts that occupy more than one line.
2. Select the texts that are located at different lines.
3. Apply bold and italic font size to the selected text.
4. Only partial text is applied with the font style, mostly on the second line of the chosen text.

**Expected behavior**
Font style should be applied to any selected texts even though they're not on the same line.

**Screenshots**
Highlighted text in List block. The chosen text "reginafoo.blog," is not having any font style applied to it.
![fontstyle](https://user-images.githubusercontent.com/40906847/45159873-867c7f80-b21a-11e8-9d4b-27f60ff98daf.png)

Tested with Paragraph block. The text "reginafoo" is not bold and italicized.
![fontstyle2](https://user-images.githubusercontent.com/40906847/45159943-bcb9ff00-b21a-11e8-81f9-4ea4ed72b213.png)

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise SP1
 - Browser: Google Chrome
 - Version: 68.0.3440.75 (Official Build) (64-bit)

**Comment by ianbelanger79** [comment]
Hi @reginabally,

Thanks for your ticket. I cannot recreate the issue that you are reporting on a single site install. I do not have a multisite test environment right now. Could you show me the html after you try adding Bold and Italic please?

Thanks

**Comment by reginabally** [comment]
Hi @ianbelanger79,

Thanks for your reply.

Here's the HTML code.

```
<p>2. Enter your email address (optional) and the domain name that you want to install SSL certificate. To simplify things, I would suggest <em><strong>generating a wildcard certificate</strong></em> that can be installed for your domain as well as its sub-domains. In my example, I entered <em><strong>"</strong></em><g class="gr_ gr_8 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" id="8" data-gr-id="8">reginafoo</g><g class="gr_ gr_10 gr-alert gr_gramm gr_inline_cards gr_run_anim Style replaceWithoutSep" id="10" data-gr-id="10">.blog</g><em><strong>, *.reginafoo.blog"</strong></em> in the Domains field.</p>
```

I tried to replicate the issue again. Seems like this only happens when the chosen text is having a comma in between. If I select texts that are crossing 2 lines that are without a comma, I don't have an issue applying the font style to them.

See another screenshot here:
![fontstyle3](https://user-images.githubusercontent.com/40906847/45162792-63a19980-b221-11e8-8993-b15bf5d18519.png)

**Comment by reginabally** [comment]
I think I might have found the issue. I have enabled Proofreading under my Profile. After unchecking all the options and removing all the proofread tags, I'm able to apply font styles to the reported texts.

**Comment by designsimply** [comment]
On a generic install with Gutenberg as the only active plugin, I don't see the proofreading option on the Users > Your Profile page:

![screenshot_2018-09-06 profile gutenberg dev wordpress](https://user-images.githubusercontent.com/1119271/45184110-37672800-b1e3-11e8-8257-75aacffced76.png)
<sup>Seen at http://localhost:8888/wp-admin/profile.php running WordPress 4.9.8 and Gutenberg 3.7 using Firefox 62.0 on macOS 10.13.6.</sup>

This makes me think it is likely a plugin conflict, and it would be great to confirm which plugin (Jetpack perhaps?) in order to note that here and also to make sure an issue is filed in the correct plugin bug tracker.

**Comment by reginabally** [comment]
Hi @designsimply,

Thanks for the help.

Yes, you're right. I have Jetpack installed for the site I'm working on.

Here's the section I can see when editing my user profile.
![image](https://user-images.githubusercontent.com/40906847/45191211-8e690d80-b274-11e8-959b-9c410bbb8179.png)

So should I file this issue on Jetpack bug tracker again?

**Comment by designsimply** [comment]
> So should I file this issue on Jetpack bug tracker again?

Yes please!

**Comment by reginabally** [comment]
Thanks @designsimply!
