### ISSUE TITLE
Inserter menu layout broken with long labels

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#9659]
When a label takes 2 lines or more, the display is broken :

![pouet](https://user-images.githubusercontent.com/1785489/45160531-ffafae80-b1e9-11e8-91ec-9994ef664755.jpg)

A lot of label are not as short as english in many languages (like French).

As a rule of thumb, I always use flexbox (or grid) and not float or inline for this kind of UI. 

(I'm sorry if it was already posted but I checked before but didn't found anything).

**Comment by ianbelanger79** [comment]
Possibly related #9553

**Comment by maximebj** [comment]
Same issue indeed. 

The trigger is not a too long label but the column block borders this time.

**Comment by ianbelanger79** [comment]
I am closing this issue. If you feel this is an error, we can reopen it.
