### ISSUE TITLE
Question about render_callback as per attribute value

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9664]
Is it possible to render callback function if the specified attribute value is set

For example -

call this function only if my post_data attributes from props has value dynamic? 

if('post_data' == 'dynamic'){

'render_callback' => 'uagb_blocks_render_block_core_latest_posts');

}

**Comment by tofumatt** [comment]
We have docs on creating dynamic blocks, which it sounds like you're talking about, here: https://github.com/WordPress/gutenberg/blob/master/docs/blocks/creating-dynamic-blocks.md

I'm not sure exactly what you're asking as it relates to Gutenberg, so I'm closing this issue for now. If you're having an issue with Gutenberg and/or have further steps to reproduce an issue please let us know!

**Comment by prajaktagadhave** [comment]
No, this block doesn't cover the entire thing. I have a block which accepts static as well as the dynamic attribute.

For example, if the attribute is static then save methos will execute my output from an index,js files else if it is dynamic the render call back from PHP file display the output.

Do you get my point?

**Comment by tofumatt** [comment]
Hmm, I'm not sure we support that kind of block; they're generally aimed at either being generated on the client or the server, not either/both contextually. Server generation is generally discouraged anyway.

Why are you looking to vary where the block is output based on an attribute?

**Comment by prajaktagadhave** [comment]
Thanks for the reply!

I want to create a block as per user selection. That means if a user selects the static block then post query will execute is select dynamic block then rich text content block executed.

Do you have idea about how to render <ReachText.content> in the serverside PHP file? If yes then it will resolve my issue.

**Comment by tofumatt** [comment]
> That means if a user selects the static block then post query will execute is select dynamic block then rich text content block executed.

Sorry, I don't exactly follow.

`RichText` is a JS, client API though, we don't support using it on the server.
