### ISSUE TITLE
Get ReachText.content in PHP file?

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9665]
How can I get ReachText.content in the serverside PHP file?

Can anyone provide an example?

**Comment by tofumatt** [comment]
I think you mean `RichText.content`; that's a JS API that's not really aimed at PHP consumption.

If you wanted to create a block with a server-side component–known as "Dynamic blocks" in Gutenberg–please have a look at: https://github.com/WordPress/gutenberg/blob/master/docs/blocks/creating-dynamic-blocks.md
