### ISSUE TITLE
How to get data from state?

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9666]
How can I get data stored in state to save() method in gutenberg?

**Comment by tofumatt** [comment]
The editor state is based on Redux, so if you have a familiarity with it and React it should look familiar. If not you may want to read up on React+Redux.

We have docs on Gutenberg's `data` layer, built on top of Redux, which uses selectors. You can see the docs here: https://github.com/WordPress/gutenberg/tree/master/docs/data

You can see how selecting data from state is done here: https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/post-title/index.js#L132
