### ISSUE TITLE
Multiple Editors

### ISSUE THREAD

**Issue by jeremyMoore85** [WordPress/gutenberg#9676]
In word press prior to Gutenberg you where able to create multiple instances of the editor through meta boxes (which they recommend porting over to blocks).

I have used this on many templates to display content in specific sections of my template files.

Will Gutenberg have the ability to create multiple block sections so that you can populate different areas of a template with the appropriate boxes?

For example I have a website for a real estate company. I want them to be able to take full advantage of the gutenberg interface allowing them to create the main content section of the page through the block system.

However i also want to lock down a section of blocks that will be an area where they input specific information about a listing (price, address, bedrooms etc.)

Is it possible to have a block that is automatically created on my listing custom post type as the last block item and not allow users to change the order of this specific block?

or are we able to add a section to the right sidebar to include these fields.  With the implementation of blocks and what seems like the phasing out of meta boxes I am curious how we can accomplish instances like this.

**Comment by designsimply** [comment]
I think what you want is to create a custom block for listings and then use template locking. See https://wordpress.org/gutenberg/handbook/block-api/#register-block-type and https://wordpress.org/gutenberg/handbook/templates/#locking
