### ISSUE TITLE
Cannot use get_post_gallery() WordPress function

### ISSUE THREAD

**Issue by Oxibug** [WordPress/gutenberg#9677]
**Describe the bug**
Firstly Many Thanks for the great project BUT I need to share with you some flexibility issues, I contact you before about filter {post_gallery} and I successfully modified your gallery style but I fall in another issue that I cannot read the post content's galleries with functions { **get_post_gallery() - get_post_galleries()** } and I noticed that a complete class destroyed because I cannot get the post's galleries IDs.

I test everything in the project and main and most things that the user {**blogger for example**} use like {**Gallery, Audio and Video**} and all of 'em have flexibility issues.

**1. Gallery**
I need to remove the first gallery from the post content and use it as a post banner in the Homepage that I already do with {**get_post_gallery()**} function beside {**the_content**} filter .. Now the users must see all galleries embedded inside post content in the Homepage's items.

**2. Audio and Video**
I still can use {**get_media_embedded_in_content()**} function to get all Audios and Videos inside the post content BUT you used {**`<video>`**} tag instead of {**[video]**} WordPress shortcode to display videos so we cannot style the videos buttons and seek bar whereas the {**[video]**} shortcode using {**mejs**} so it gives us the ability to style everything when the audio or video inside content or in any other place.

So Have you create a complete blogger posts have {Galleries, Audios and Videos} and see what will the Homepage like? There's no flexibility like old WordPress, if I used Gutenberg I MUST use an image as post thumb and use post excerpt instead of using a {**filtered content**}, I cannot get the first gallery from the post content and use it as a post thumb, I cannot remove galleries from the post content in the Homepage, I cannot use the {video} as post thumb unless using a RegEX to get src and perform a {**do_shortcode**} for that source so I can style my video items (a lot of unnecessary work).

Actually I appreciate your work but I need some features like WordPress already has, They think about everything very well and made helper functions like {**get_post_gallery() and get_media_embedded_in_content()**}, If they used {divs} for gallery and {**`<video>`**} tags there's no way to use those functions and the users won't understand the differences.

Thanks for the GREAT project and hope you help me with functions because my all projects suspended because of these issues.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - Chrome

**Additional context**
- Gutenberg v3.7.0

**Comment by BinaryMoon** [comment]
Related: https://github.com/WordPress/gutenberg/issues/5797

**Comment by BinaryMoon** [comment]
Had this problem myself today so made a polyfill that fixes the issue (for my use case at least):
https://gist.github.com/BinaryMoon/cd1eb239d4a14ba3ab45b756e4c64828

**Comment by designsimply** [comment]
I found that get_post_galleries() support was requested for Gutenberg at https://github.com/WordPress/gutenberg/issues/5797 and then moved to https://core.trac.wordpress.org/ticket/43826 and I would like to close this issue in favor of the work being done at https://core.trac.wordpress.org/ticket/43826. Please let me know if that does not work and we can re-open this issue. Thank you!

**Comment by dimative** [comment]
Hello guys.
Please recommend me temp solution for this issues. 
I need to get images URL from first gallery block.
I tried @BinaryMoon 's solution. But seems didn't return image url. 
Thanks all.

**Comment by designsimply** [comment]
@dimative this issue has moved to https://core.trac.wordpress.org/ticket/43826 which you may comment on if you are interested in working on or testing the patch for that case or you can log in and use the "Watch this ticket button" at the bottom of the issue if you'd like to be notified about progress for that ticket.

If you are looking for support in the mean time or wanting to look for help with a potential workaround before the upstream issue has gone through, please post at https://wordpress.org/support/forum/wp-advanced/ and include code examples if possible as well as notes about your current WordPress version and what you have tried already that did not work. Thank you!
