### ISSUE TITLE
UI: Add author dropdown

### ISSUE THREAD

**Issue by jasmussen** [WordPress/gutenberg#968]
When there are multiple authors on a blog, we need a way for the user to be able to pick which author wrote the post. This is a metabox in the current editor. Can we do better?

Here's a dropdown that sits at the top of the screen:

![author](https://cloud.githubusercontent.com/assets/1204802/26671706/ca5636a4-46b6-11e7-87c8-bc93dc4bd50b.png)

![author dropdown](https://cloud.githubusercontent.com/assets/1204802/26671708/ccef998c-46b6-11e7-9bc1-fa7b5dcaaeb5.png)

**Comment by sbangnielsen** [comment]
What happens on sites with hundreds, maybe even thousands of authors? Some way of searching/filtering would be nice.

What if a post is co-written by several different authors? (plugin-territory?)

What if a post is written by an author, that doesn’t have a user-profile? (plugin-territory?)

**Comment by jasmussen** [comment]
What about this?

![screen shot 2017-06-02 at 09 36 40](https://cloud.githubusercontent.com/assets/1204802/26715818/634f6266-4777-11e7-925d-6628ead9ebfc.png)

**Comment by paaljoachim** [comment]
Hey Joen. I think that looks cleaner. If there are multiple authors they could be listed in the drop down by alphabetical order. 

Are there plans on adding multi select to WordPress?
Multiple Selection
A selection dropdown can allow multiple selections
https://semantic-ui.com/modules/dropdown.html

**Comment by jasmussen** [comment]
Multi select seems cool, but it also seems like something worth opening a separate ticket for, because it seems like a bigger undertaking, meaning we might not want to focus on that immediately, but rather, down the road a bit.

**Comment by paaljoachim** [comment]
I opened a Github issue. I also did a search and found this trac issue: https://core.trac.wordpress.org/ticket/31696

**Comment by mtias** [comment]
> What happens on sites with hundreds, maybe even thousands of authors? Some way of searching/filtering would be nice.

You'll be able to search authors.

**Comment by GaryJones** [comment]
I'd definitely prefer to see this just in the Post Settings - it really doesn't need to be visible (and a distraction) all of the time by sitting above the editor.

**Comment by mtias** [comment]
I think it's quite nice to see in multiple-author sites (only).

**Comment by StaggerLeee** [comment]
Please hide it properly. It is less used than birthdays on 29. February,

**Comment by hedgefield** [comment]
Another vote for putting it in the Post Settings. I do like it when an avatar can be displayed somewhere :) but this shouldn't be such a highly visible action. Putting it in the document area also might confuse functionality with the author bio block in #1844.

**Comment by StaggerLeee** [comment]
Are you rewriting this code ? Author option is now missing completely.

**Comment by youknowriad** [comment]
@StaggerLeee If you have a unique user, the author dropdown is not shown. It should appear in the sidebar if you have several users.

**Comment by youknowriad** [comment]
Are you using the master version of the last release? This hasn't been released yet

**Comment by StaggerLeee** [comment]
0.6.0 public version.

**Comment by mtias** [comment]
This is planned to be released in 0.7.
