### ISSUE TITLE
Where to save this data so that I can access this from save() method to render output on frontend?

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9684]
Here is screenshot - https://goo.gl/BnYRBx

```JS
const { postsToShow, order, orderBy, categories, postType } = props.attributes;    
    if( postType == 'post'){ 
        const { getEntityRecords } = select( 'core' );
        const latestPostsQuery = pickBy( {
            categories,
            order,
            orderby: orderBy,
            per_page: postsToShow,
        }, ( value ) => ! isUndefined( value ) );
        const categoriesListQuery = {
            per_page: 100,
        };        
        return {
            latestPosts: getEntityRecords( 'postType', 'post', latestPostsQuery ),
            categoriesList: getEntityRecords( 'taxonomy', 'category', categoriesListQuery ),
        };
    }
```
In this We get latestPost as props how can we access this props.latestPosts value in save method ?

Urgent..

**Comment by tofumatt** [comment]
You can look through the `packages/block-library` package to see how existing blocks handle `props`, the `save()` method, etc.

Thanks for your interest in writing Gutenberg blocks but this issue tracker is aimed at tracking reproducible bugs that are actionable (basically: bugs that can be fixed/features that can be implemented).

It's not the place for help requests writing a plugin; if you'd like support writing a block/plugin, please try the Make WordPress forums: https://wordpress.org/support/forum/wp-advanced/
