### ISSUE TITLE
RichText keepPlaceholderOnFocus buggy when cutting and pasting

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#9691]
Most of the `RichText`s in Gutenberg set `keepPlaceholderOnFocus` to false, that means the placeholder will hide as soon as the editable field receives focus (note: this is different by the native behavior, but it's out of this issue scope).

However, some blocks, for example the File block, set `keepPlaceholderOnFocus` to true. Custom blocks may do that as well.

When set to true, the placeholder text doesn't disappear when the editable field receives focus. It disappears only after typing something. This works well except when cutting and pasting something.

To reproduce:
- add a File block
- select a file
- by default, the block will display the file name:

<img width="676" alt="screen shot 2018-09-07 at 16 46 54" src="https://user-images.githubusercontent.com/1682452/45225825-b4ff6680-b2bd-11e8-94ab-5c0321903cb4.png">

- edit the file name and enter a different name
- Cmd/Ctrl + A to select the new name
- Cmd/Ctrl + X to cut it
- Cmd/Ctrl + V to paste it
- at this point, both the pasted text and the placeholder are visible at the same time:

<img width="399" alt="screen shot 2018-09-07 at 16 30 37" src="https://user-images.githubusercontent.com/1682452/45225891-dfe9ba80-b2bd-11e8-857b-5ab239b08989.png">

Additionally:
- with both text displayed, save the post as draft
- refresh the page
- the new entered text is not saved:

<img width="375" alt="screen shot 2018-09-07 at 16 50 15" src="https://user-images.githubusercontent.com/1682452/45226053-3951e980-b2be-11e8-93de-bb4dc6fa4aab.png">

**Comment by afercia** [comment]
Worth noting this: 
> the new entered text is not saved:

happens also with custom blocks, when selecting all, cutting, and pasting again then the content is not saved.

**Comment by iseulde** [comment]
@afercia I cannot reproduce this in `master`. Is it still an issue?

**Comment by youknowriad** [comment]
I can't reproduce this either. Let's close for now.
