### ISSUE TITLE
Latest Posts Block: Inconsistent fallback title for untitled posts. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9695]
When a post does not have a title, WP-Admin defaults to calling it `(no title)`:

<img width="555" alt="screen shot 2018-09-07 at 1 54 24 pm" src="https://user-images.githubusercontent.com/1202812/45235038-91302680-b2a5-11e8-836f-7823c476e30c.png">

The existing "Recent Posts" widget does the same:  

<img width="176" alt="screen shot 2018-09-07 at 1 55 04 pm" src="https://user-images.githubusercontent.com/1202812/45235056-a442f680-b2a5-11e8-8213-d30e98244313.png">

The Latest Posts widget however, calls those posts `(Untitled)` instead:

<img width="729" alt="screen shot 2018-09-07 at 1 27 17 pm" src="https://user-images.githubusercontent.com/1202812/45235076-bcb31100-b2a5-11e8-9cfd-659f2b0fa22d.png">

WordPress should be consistent with this label. I don't have a strong preference either way, but I'd suggest we go with our existing `(no title)` precedent unless we have a reason not to. 

_Tested in Gutenberg 3.7_

**Comment by afercia** [comment]
+1 👍
