### ISSUE TITLE
Latest Posts Block: Clipped bullet points on small screens when using Grid View

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9697]
**Describe the bug**

On breakpoints `<600px`, the "Grid View" setting for the Latest Posts block displays all posts in a single column. When this happens, the left margin is incorrect, resulting in cut off bullet points: 

<img width="342" alt="screen shot 2018-09-07 at 2 10 14 pm" src="https://user-images.githubusercontent.com/1202812/45235833-1f0d1100-b2a8-11e8-8d7e-44c02cd772ea.png">

**To Reproduce**

1. Add a Latest Posts block. 
2. Activate "Grid View" from the block toolbar.
3. Resize your screen to be smaller than `600px` wide.
4. Observe issue.

**Expected behavior**

Ideally, when this is shown in just one column, it should appear just like it does for "List View":

<img width="343" alt="screen shot 2018-09-07 at 2 13 34 pm" src="https://user-images.githubusercontent.com/1202812/45235905-4cf25580-b2a8-11e8-84b9-cb31dde65ab8.png">

**Tested in**

Mac OS 10.13.6, Safari 11.1.2, Chrome 68.0.3440.106

**Comment by jorgefilipecosta** [comment]
Hi @kjellr, in what theme is this problem happening?

**Comment by kjellr** [comment]
This was happening with the default editor styles. But I just re-tested using the Gutenberg Starter Theme, and the problem seems to have disappeared in the past 8 months. 🙂

I'll go ahead and close this one!
