### ISSUE TITLE
Block Audit: Latest Comments

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9700]
_Note: We'll be doing these audits in waves and editing this as we work through the blocks, so this text will be updated and fleshed out as we progress. [See the full picture here](https://github.com/WordPress/gutenberg/projects/19)._

# Overview

![screen shot 2018-09-07 at 3 06 29 pm](https://user-images.githubusercontent.com/1202812/45238375-9d20e600-b2af-11e8-9b28-07b0145dd323.png)

**Name:** Latest Comments
**Description:** Show a list of your site’s most recent comments.
***Category:** Widgets
**CSS class:** `wp-block-latest-comments`
**Can be converted to:** Nothing

# States

*Empty/Selected/Placeholder*

![screen shot 2018-09-07 at 3 07 54 pm](https://user-images.githubusercontent.com/1202812/45238441-d22d3880-b2af-11e8-9098-a53d3b0ed9d0.png)

*Unselected:*

![screen shot 2018-09-07 at 3 07 48 pm](https://user-images.githubusercontent.com/1202812/45238442-d3f6fc00-b2af-11e8-9e04-bb89440885bf.png)

# Primary (toolbar) settings

Align Left, Align Center, Align Right

# Secondary (sidebar) settings

Latest Comments Settings: Display Avatar, Display Date, Display Excerpt, Number of comments
Advanced: Additional CSS Class

# Frontend appearance

**Gutenberg Starter Theme**

![screen shot 2018-09-07 at 3 10 15 pm](https://user-images.githubusercontent.com/1202812/45238540-26381d00-b2b0-11e8-9164-244522f74eba.png)

**Atomic Blocks**

![screen shot 2018-09-07 at 3 10 47 pm](https://user-images.githubusercontent.com/1202812/45238560-3b14b080-b2b0-11e8-8504-60c2caf420c8.png)

**twentyseventeen**

![screen shot 2018-09-07 at 3 09 50 pm](https://user-images.githubusercontent.com/1202812/45238523-17ea0100-b2b0-11e8-834f-aa34724c4dca.png)

**twentyten**

![screen shot 2018-09-07 at 3 09 28 pm](https://user-images.githubusercontent.com/1202812/45238508-0acd1200-b2b0-11e8-943d-47b4c9c7709b.png)

# Bugs/errors

_Individual issues will be opened for these soon_

- [ ] 

# Suggestions

_Individual issues will be opened for these soon_

- [ ]

**Comment by sarahmonster** [comment]
No bugs and no suggestions = closing time!
