### ISSUE TITLE
Cannot read property 'parentNode' of undefined

### ISSUE THREAD

**Issue by russosalv** [WordPress/gutenberg#9703]
Open "New Page"  wordPress show "The editor has encountered an unexpected error."
![image](https://user-images.githubusercontent.com/3062596/45243648-fb23ec80-b2f4-11e8-9b75-2fd351e587e0.png)

**To Reproduce**
1. Post
2. New Post

**Expected behavior**
Possibility to create a new page using gutenberg

**Screenshots**
![image](https://user-images.githubusercontent.com/3062596/45243717-32929900-b2f5-11e8-93c4-ab958107cbf7.png)
**Cannot read property 'parentNode' of undefined** 

**Desktop (please complete the following information):**
 - OS:  MAC OS 10,13,6
 - Browser chrome
 - Version 68.0.3440.106

**Additional context**
Installed JetPack & Yoast

**Comment by 0aveRyan** [comment]
@russosalv i'm sorry something is broken, thanks for taking the time to write in. 

Could you provide the version of Gutenberg you're using (as well as the jetpack & yoast version numbers)? 

Also, does the editor work properly with those plugins deactivated? 

With more info we can hopefully get this sorted out.

**Comment by youknowriad** [comment]
Closing as stale, we can reopen if there are reproducible steps.

**Comment by saharsalman** [comment]
I am having this issue on focus out the postcode field in my account/address

Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at o (jquery.blockUI.min.js?ver=2.70:14)
    at Function.b.blockUI (jquery.blockUI.min.js?ver=2.70:14)
    at HTMLInputElement.<anonymous> (ajax-date-calculate.js?ver=5.6.2:110)
    at HTMLBodyElement.dispatch (jquery.min.js?ver=3.5.1:2)
    at HTMLBodyElement.v.handle (jquery.min.js?ver=3.5.1:2)
    at Object.trigger (jquery.min.js?ver=3.5.1:2)
    at Object.simulate (jquery.min.js?ver=3.5.1:2)
    at HTMLDocument.i (jquery.min.js?ver=3.5.1:2)
