### ISSUE TITLE
Gutenberg first time use: several issues, including whole blog post disappearing 

### ISSUE THREAD

**Issue by ckohut** [WordPress/gutenberg#9705]
I spent hours creating a several thousand word post, and hit the save button several times, it showed as saved. I discovered a glitch when trying to add an image, it would not load the image and kept saying there was an error. I tried to use the Preview but nothing showed up, so I tried to publish privately to see how it looked. Again, hit save before publishing. Next thing, the whole post is gone. I went to ALL POSTS to see if it was there, and the only thing in my files is "auto post", and it's blank. Tried the back button to go back to the editor page and it is gone. I doubt there is a way to recover it, but I lost so many work hours on this today, and it's extremely frustrating.

**Comment by youknowriad** [comment]
I'm going to close this issue as stale and not actionable. If you have some practical steps to reproduce the issue we can reopen.
