### ISSUE TITLE
LIST BOX all bullet rows will not indent when clicking INDEX LIST ITEM button

### ISSUE THREAD

**Issue by goyakpacking** [WordPress/gutenberg#9706]
Testing out Gutenberg

I wanted to create a list with a text Header.  The Header text not to have a “bullet” symbol preceding it.  

So I created the header in a TEXT box
Our recommendations “Tools of the Trade” list:

I then created a LIST box and added a list of 7 items. 
•  Several Heavy Duty Garbage Bags
•  Disposable Gloves
•  Leather Gloves
•  Extension Grabbing device or "Paper Picker"
•  Container to hold trash bag
•  Zip Ties or Twist Ties - To seal stinky trash bags
•  Hand Cleaner, Hand Sanitizer, Paper Towels

 When I first saved, the 7 Bullets were left of the normal margin of anything else on the page.  In my opinion the default should be indented.  But regardless of default opinions, an edit should suffice.

So I went back in to EDIT and highlighted all 7 rows of Bulleted text… and clicked the “INDEX LIST ITEM” button…..nothing happens.

I found I could un-highlight the first row and highlight rows 2 through 7.  2 through 7 will indent….but not row 1.   Tried 1 by itself.  1 would not indent.

I tried them individually and could indent 2 through 7, but never 1.

This is on Domain/Page/
http://tradingfortrash.com/tools-of-the-trade/

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  W7
 - Browser [e.g. chrome, safari] Firefox 62.0 64 Bit

**Smartphone (please complete the following information):**

**Additional context**
- Please add the version of Gutenberg you are using in the description. [ Gutenberg Ver 3.7.0 ]
- To report a security issue, please visit the WordPress HackerOne program: https://hackerone.com/wordpress.

**Comment by tofumatt** [comment]
The margin of your list items should be controlled by your theme, not by Gutenberg. You should update your theme's CSS to indent lists more.

It looks like you created a nested list, from the HTML output on the page you made:

<img width="583" alt="screenshot 2018-09-08 09 55 50" src="https://user-images.githubusercontent.com/90871/45252401-8335e080-b34d-11e8-9920-8780568f220e.png">

You can try editing your theme's CSS to change the indentation of lists. 🙂

**Comment by goyakpacking** [comment]
Hmmm.  Not the resolution I anticipated.  If I have to start doing things in CSS I don’t find the plugin acceptable.  Many of us using WordPress are not CSS experts.  

The list with the indention issue was created using your plugin LIST BOX.  In the visual or WYSIWYG not in the Code/HTML mode. To me there is some kind of bug. 

I can fix it another way, but that defeats the purpose of using your plugin.

**Comment by goyakpacking** [comment]
I agree with you on the default “left alignment”.  But there iappears to be something in the plugin causing the first row to not indent to the right somewhat to line up with rows 2 Thru 7. 

I must not be explaining it correctly.

**Comment by tofumatt** [comment]
Here's me editing a list in Gutenberg:

![2018-09-08 15 08 09](https://user-images.githubusercontent.com/90871/45254998-26501f80-b379-11e8-8e48-1202631a034d.gif)

Is this similar to what you experienced? Maybe we're misunderstanding each other, sorry if so! 😓
