### ISSUE TITLE
Bilingual versions of posts mismatched after activating Gutenberg plugin

### ISSUE THREAD

**Issue by lauriannegd** [WordPress/gutenberg#9709]
Hello,
I've been using the Polylang plugin for years to write & manage blog posts in English and French. I switched to Gutenberg and wrote a new post in French before adding its English translation. However, I found out a few minutes later that:

1- My original French post has "lost" its English translation (they're no longer paired together)
2- This English translation has been turned into its own post (independent from its parent French version)
3- The most baffling thing of all is that Gutenberg assigned to this English post the French version of a completely random French post I wrote over a year ago.

How could that be? Even more baffling is the fact that I tried to pair my French and English posts together manually and Gutenberg just won't allow it. I saved everything, but Gutenberg keep linking back to that random article.

Thanks for your help!

**Comment by tofumatt** [comment]
Does Polylang create multiple post IDs and link them? Gutenberg would be unaware of that kind of usage–it's a clever "hack" but it's not exactly something we can account for.

I think this might be an issue with the Polylang plugin–have you contacted them and asked them if their plugin is compatible with Gutenberg?

**Comment by lauriannegd** [comment]
I just checked, Polylang does create multiple post IDs. 

I believe Polylang is compatible with Gutenberg. I looked up their development page and saw they fixed a conflict with Gutenberg earlier this year. I brought up the issue here because it happened after using Gutenberg for the first time but I'll bring it up to Polylang as well. In the meantime, I have deactivated Gutenberg.

**Comment by tofumatt** [comment]
I think #9816 is similar, and it looks like it's not really a Gutenberg issue but it's that the plugin isn't compatible with Gutenberg.

Thanks for contacting the plugin developer; unfortunately I don't think there's much we can do here but thanks for filing and letting us know.

Until the bug is fixed, yes: I'd recommend using the Classic Editor (when WordPress 5.0 is released you can use the Classic Editor Plugin). Sorry about that!
