### ISSUE TITLE
YouTube embedding = Updating failure

### ISSUE THREAD

**Issue by krisub** [WordPress/gutenberg#9713]
If I embed youtube videos posts can just be updated by using the classical editor.
With "Gutenberg" there is always the red message "Updating Failed"

**Comment by youknowriad** [comment]
I expect you have some issue in your API request saving the posts. Can you check in the network tab of your browser's dev tools the response of these requests?

**Comment by krisub** [comment]
How can I do this?

**Comment by youknowriad** [comment]
If you're using Chrome, you can find a video in youtube showing how to do so. https://www.youtube.com/watch?v=nl8iKlo2NeM

Similar tools exist in other browsers.

In general, it's coming from a conflict with other plugins (disabling one by one might help finding the source of the error) or a server configuration to disable REST APIs or aggressive security configuration on your server or security plugin.

**Comment by krisub** [comment]
It's seems that it works now. I don't konw what has changed.

**Comment by krisub** [comment]
I don't know how to close this issue...
