### ISSUE TITLE
InnerBlocks layouts - no controls show

### ISSUE THREAD

**Issue by virgiliud** [WordPress/gutenberg#9714]
I assigned layout as an object to InnerBlocks and no controls are presented to the user in the editor. 

```
<InnerBlocks layouts={ {
	normal: { label: 'Normal Width', icon: 'align-center' },
	wide: { label: 'Width Width', icon: 'align-wide' },
} } />

```
I am using Gutenberg 3.7.0

**Comment by aduth** [comment]
Related:

- #7841
- #3745

It was originally a goal of `InnerBlocks` to support automated UI generation, i.e. present controls to the user to switch layout regions. This was never implemented, and in #7841 the documentation was updated to avoid confusion on this point. Currently it is the responsibility of the block to implement its own controls and assign to the `layout` attribute.

I am okay to leave this issue remain open as a two-pronged question:

- Is the `layouts` concept still desirable?
- And if so, should controls be generated automatically for each layout?

**Comment by gziolo** [comment]
I can't see `layouts` prop in `InnerBlocks` definition. It would mean this issue should be closed, @jorgefilipecosta or @aduth, can you confirm?

**Comment by aduth** [comment]
It can be closed. The layouts concept was removed in #11029.
