### ISSUE TITLE
insertion point vanishes pressing return in title field on iPad

### ISSUE THREAD

**Issue by troutcolor** [WordPress/gutenberg#9715]
**Describe the bug**
After writing a title I press return. A new block is created. This block is hidden behind the keyboard of the iPad.

**To Reproduce**
1. On an iPad, create a New Post
2. Type in Title
3. Press the Return Key
4. See error: The insertion point in the new block is hidden behind the keyboard.

**Expected behavior**
I expected the screen to scroll/jump so that the new block is visible.

**Screenshots**

[Video on YouTube](https://www.youtube.com/watch?v=hEAr6_kw3vc)
 

**Tablet**
 - iOS
 - Safari
 - IPad Air WiFi A1474 (first air)
- iOS 11.4.1

 

**Additional context**
Gutenberg 3.70
WordPress 4.9.8

I work on a large set of multi-sites used by Education in Scotland, more than 200,000 blogs into total. A lot of the users are children as young as 8. They are supported by teachers who are generally not familiar with WordPress. There are a lot of people posting with iPads. We are unable to use the WordPress app. I am worried that this will be off putting and have a negative affect on usage.

**Comment by ellatrix** [comment]
@troutcolor Same as #9716, I will close this and we'll use #16193 as a tracking issue. I'll have a look at these problems on iOS soon. Thanks for your patience. :)
