### ISSUE TITLE
Block created on iPad is hidden by keyboard

### ISSUE THREAD

**Issue by troutcolor** [WordPress/gutenberg#9716]
**Describe the bug**
When editing a paragraph block, which is near the bottom of the editor, hitting return creates a new block which is hidden by a keyboard.  

**To Reproduce**
1. On iPad create a new post.
2. Create a first paragraph block.
3. Create some more paragraph blocks by pressing return.
4. Block is created behind the keyboard.

**Expected behavior**
I expected the screen to scroll/jump so that the new block is visible.

**Screenshots**
 [YouTube Video](https://www.youtube.com/watch?v=fnfNsMWK9CI)

**Tablet**
 - iOS
 - Safari
 - IPad Air WiFi A1474 (first air)
- iOS 11.4.1

 

**Additional context**
Gutenberg 3.70
WordPress 4.9.8

I work on a large set of multi-sites used by Education in Scotland, more than 200,000 blogs into total. A lot of the users are children as young as 8. They are supported by teachers who are generally not familiar with WordPress. There are a lot of people posting with iPads. We are unable to use the WordPress app. I am worried that this will be off putting and have a negative affect on usage. 

This might be the same problem as the one I posted about [creating a new block from the title field](https://github.com/WordPress/gutenberg/issues/9715). This one is more bothersome imo.

**Comment by ellatrix** [comment]
Thanks for the report @troutcolor. We've discovered similar problems recently with pressing Enter in iOS Safari in general. Let's use #16193 as a tracking issue for all of this.
