### ISSUE TITLE
Paste from Word or LibreOffice produces block of CSS first 

### ISSUE THREAD

**Issue by ogalinski** [WordPress/gutenberg#9719]
**Description**
When pasting some simple text (one heading, one paragraph) from Word or LibreOffice, Gutenberg first creates a paragraph block of some CSS text and then the content blocks. 

**To Reproduce**
1. Create a document in Word or LibreOffice, one heading and one paragraph (any text will do). Select all and copy.
2. Create a new Gutenberg post.
3. Paste content.

**Expected behavior**
One heading block and one paragraph block.

**Screenshots**
![gutenberg-error](https://user-images.githubusercontent.com/2190095/45260063-7f807900-b3a2-11e8-8ed8-a5c273be64a1.jpg)

**Desktop (please complete the following information):**
- Windows 10 Pro
- Tested on Chrome 69 and FireFox Quantum 62 (64 bits)

**Additional context**
- Gutenberg 3.7.0
- Tested on local setup and also on testgutenberg.com.

**Comment by maximebj** [comment]
I was about to post this issue too! 

Same thing with Word for Mac. 

![capture 2018-09-10 a 11 51 09](https://user-images.githubusercontent.com/1785489/45290506-127af980-b4f0-11e8-9238-e12cf3e373a5.jpg)

I know than this is not a good practice to do this but we won't be able to avoid people to do this.

By the way, when pasting from Word, it would be cool to "clean" this awful Wordish CSS ;)

**Comment by youknowriad** [comment]
Is this a known issue @iseulde @mcsf?

**Comment by ogalinski** [comment]
Funny thing is, I tested this in Gutenberg v2.0 and it was working fine.

**Comment by maximebj** [comment]
Regression! I'm calling the unit test police ! 

I think that it could be handled simply by removing block beginning with a styles statement + comment tag

**Comment by designsimply** [comment]
Also see #9759, #9761.

**Comment by designsimply** [comment]
Tested and confirmed using LibreOffice 6.0.6.2 and WordPress 4.9.8 and Gutenberg 3.8.0-rc.1 with Firefox 62.0 on macOS 10.13.6.

Sample file https://github.com/WordPress/gutenberg/files/2367501/Word.docx 
<sup>(h/t @troytempleman for linking to this sample file in another issue)</sup>

![screen shot 2018-09-10 at 12 08 09 pm](https://user-images.githubusercontent.com/1119271/45315747-65ee4700-b4f2-11e8-9924-f7b07e1a872c.png)

![screen shot 2018-09-10 at 12 08 17 pm](https://user-images.githubusercontent.com/1119271/45315755-6a1a6480-b4f2-11e8-95bc-056316b44bb9.png)

<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14846&action=edit running WordPress 4.9.8 and Gutenberg 3.8.0-rc.1 using Firefox 62.0 on macOS 10.13.6.</sup>

**Comment by troytempleman** [comment]
Pasting into Internet Explorer gives a different result, as described in [#9759](https://github.com/WordPress/gutenberg/issues/9759). Styles don't get inserted but all text gets inserted into one block and is not properly formatted (i.e paragraph breaks, lists, etc.).

**Comment by tanjoymor** [comment]
Tested and found that using a Classic block allows for proper pasting. No CSS code and it retains formatting.

**Comment by mcsf** [comment]
It's a bit late here for a proper Git bisecting, but we are indeed missing integration tests for document styling. See #10019 for said tests and a possible fix.

**Comment by pwkip** [comment]
This problem still occurs when you paste inside a block that only allows paragraphs.

To reproduce:

- create a block that only allows paragraphs. `<!-- wp:myblocks/group-content {"allowedBlocks":["core/paragraph"]} --> ... <!-- /wp:myblocks/group-content -->`
- Try to paste from word or libreoffice in this block.
- You will see the `@page` styles appearing as plain text

**Comment by paaljoachim** [comment]
WordPress 5.8
Twenty Twenty One theme
Gutenberg plugin 11.3. (Only plugin activated.)

Pasting text into a page. (I am not certain how to reproduce your testing @pwkip Jules.)

Testing with TextMakerFree from Softmaker Free office 2018.
---> Works. 

------------

Testing with LibreOffice 7.2.
---> Works.

**Comment by pwkip** [comment]
Thanks for testing Paal. However, you would need to create your own custom group that only allows paragraph blocks before you can reproduce this. Creating your own Gutenberg blocks is still not something trivial as you will need to register the block trough PHP and include  some additional JS and CSS files. Explaining how to reproduce the error would mean writing a complete tutorial first. Instead, I'll try to write a quick plugin that registers a group that only allows `<p>`-blocks. Will keep you posted.
