### ISSUE TITLE
Some metaboxes are not visible in Gutenberg

### ISSUE THREAD

**Issue by rabirom** [WordPress/gutenberg#9721]
**Describe the bug**
My theme is bespoke and has custome template in page atrribute. It desappears when gutenberg is ON.

**To Reproduce**
1. Go to wordpress dashboard
2. Click on pages
3. Click on new page

**Expected behavior**
I expect to see an option to select page atribute and once selescted a homepage setting area benath the text editor. Which is working fine without gutenberg, but need it to work with the gutenberg.

**Screenshots**

Screenshot of how it works [fine without gutenberg.](https://mega.nz/#!eq5FwYJI!TZeXz1Djk9tn9r40lZJ7AwrUZsdIL2CJchmemnPO-P4)

**Desktop (please complete the following information):**
All

**Smartphone (please complete the following information):**
NA

**Additional context**
I want to make sure this is sloved, becuse it is integral part of my theme, which I use for almost all the pages on the site. Please help. Although I have tried many coders but they are not able to solve it.

**Comment by youknowriad** [comment]
I do have this option on the sidebar

<img width="282" alt="screen shot 2018-09-10 at 13 32 33" src="https://user-images.githubusercontent.com/272444/45297670-026a1680-b4fe-11e8-97b3-929659ce7c5c.png">

I'm using a different theme though. Can you check again if you have it? If now, how can we get a free version of your theme for testing purpose?

**Comment by rabirom** [comment]
Hello,

Thank you for the response. I am using a customised theme. 
Even I can see the option to change the page attribute as you have shown. But some custom made functions it is supposed to handle disappears.
I can give you access to staging environment if you want to check.

Kindly refer to these images for better understanding : 

https://imgur.com/a/pk7xg9H

Thank you.

**Comment by youknowriad** [comment]
Could you provide the "code" you use to register those metaboxes?

**Comment by rabirom** [comment]
I am sorry I am not aware of this. I will ask my coder to join the conversation shortly.

**Comment by rabirom** [comment]
Hello,
We are still struggling with the issue.
Kindly see if this image helps: https://imgur.com/a/f5wn3v2

**Comment by youknowriad** [comment]
It looks like an issue with the Carbon Fields plugin, I suggest you reach out directly to the author of the plugin to ensure they're aware of this compatibility issue with Gutenberg.

(I'm not sure about the caching issue, the `dist` CSS is probably generated from a `src` file, so you might want to change the source file and regenerate a new dist)

**Comment by rabirom** [comment]
Okay, I will convey to the coder accordingly.

Thank you for the help, I will soon update you.
