### ISSUE TITLE
Images not centered after published

### ISSUE THREAD

**Issue by goyakpacking** [WordPress/gutenberg#9726]
I like the Gallery feature of Getunberg.  But it seems quirky?  I was adding several images as a Gallery block.  But also some single images as a Image block.  Both built on the same page.  When published they were not centered as I though I had set them.  Went back in as an edit and used the quick edit on the image tool bar, to center.  When republished the GALLERY (two photos) and the single IMAGE did not center but remained left justified.

Another quirky thing is I can't use the quick edits in the tool bar at the top to alter highlighted font color in a PARAGRAPH block I had text in.   Some I wanted to remain at default color, and some I wanted to grey out.  That didn't work.   At least not in any way I am accustomed to think it would flow.

At this point I re-installed the classic editor.  Oddly the two Gallery images created and published in the Gutenberg editor had "bullet points" off on the left of the two images, now viewed the classic editor.  To correct this using the classic editor, I had to delete the photos, then backspace to delete the bullet points.  Then re-add the two images back into my page. 

I will remain on Classic until Gutenburg is less buggy.  Too much work backed up to do further beta testing.

**Smartphone (please complete the following information):**
Os Win7 64 Bit
Browser Firefox 62.0 (64-bit)
Gutenberg 3.7.0

**Comment by globalmatt** [comment]
Image centring should be fixed in [v3.8.0-rc.1](https://github.com/WordPress/gutenberg/releases/tag/v3.8.0-rc.1).

Possibly related to #9533.

**Comment by youknowriad** [comment]
Closing as the image centering is fixed.
