### ISSUE TITLE
Error - Updating failed error with following js warning- 

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9728]
After adding the dev version of Gutenberg 3.8.0 - we faced following error on adding paragraph block- 

`index.js?ver=1536553937:1 Uncaught (in promise) {code: "invalid_json", message: "The response is not a valid JSON response."}`

Here is screenshot - https://goo.gl/G1p41z

**Comment by youknowriad** [comment]
Can you check which network request is triggering this error? You can check in the network panel of the browser dev tools. It could be that one of the XHR responses have some extra PHP errors/warnings making it impossible to read it as JSON.

**Comment by prajaktagadhave** [comment]
NO problem, we resolved this issue.

**Comment by youknowriad** [comment]
Thanks, could you share the origin of the issue, it can be helpful for others. Thanks

**Comment by CarlasHub** [comment]
How did you solve your issue @prajaktagadhave ?
