### ISSUE TITLE
Drag and drop Edge broken

### ISSUE THREAD

**Issue by romain25** [WordPress/gutenberg#9729]
**Describe the bug**
It's impossible to drag and drop element on EDGE

**To Reproduce**
You can see the problem in this video
https://streamable.com/egfzl

**Screenshots**
https://streamable.com/egfzl

**Desktop (please complete the following information):**
 - Windows 10
 - EDGE
 - Version 42.17134.228

**Additional context**
- Last version of Guthenberg 3.7.0
- Last version of wordpress on fresh installation without other plugin

**Comment by designsimply** [comment]
Thank you for reporting this! I tested and confirmed while running WordPress 4.9.8 and Gutenberg 3.8.0-rc.1 with Edge 17 on Windows 10 via browserstack.com.

**Comment by talldan** [comment]
Thanks for the report @romain25 - this should be fixed in v4 of gutenberg 😄
