### ISSUE TITLE
Placeholder text is still visible with actual input

### ISSUE THREAD

**Issue by emfluenceindia** [WordPress/gutenberg#9746]
**Describe the bug**
Placeholder text is visible in custom block editor when I take focus out from the RichText.

**Expected behavior**
Placeholder text should not appear if input has a value entered into it.

**Screenshots**
Attached.
![screenshot from 2018-09-10 19_03_18](https://user-images.githubusercontent.com/11072678/45300886-28f37600-b52d-11e8-97ea-5926695f3a15.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 14.04 Trusty Thar
 - Browser: Chrome
 - Version: 69.0.3497.81 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
Not applicable

**Additional context**
- Please add the version of Gutenberg you are using in the description. Version 3.7.0
- WordPress version: 4.9.8

**Comment by emfluenceindia** [comment]
The block adds an Alignment toolbar into RichText block editor.
Here is the block code:

```
export default registerBlockType(
    'sar/block-alignment-toolbar', {
	title: __( 'Block Alignment Toolbar' ),
	description: __( 'Aligns the entire block' ),
	category: 'common',
	icon: 'align-none',
	keywords:[],

	attributes:{
		message: {
			type: 'array',
			source: 'children',
			selector: '.message-body',
		},
		textAlignment: {
			type: 'string',
		},
		blockAlignment: {
			type: 'string',
			default: 'wide',
		},
	},

	getEditWrapperProps( { blockAlignment } ){
		if( 'left' === blockAlignment || 'right' === blockAlignment || 'full' === blockAlignment ) {
			return { 'data-align': blockAlignment };
		}
	},

	edit: props => {
		const {
			attributes: { textAlignment, blockAlignment, message },
			isSelected, className, setAttributes } = props;

		return(
			<div className={ className }>
				{ isSelected && (
					<BlockControls>
						<BlockAlignmentToolbar
							value={ blockAlignment }
							onChange={ blockAlignment => setAttributes( { blockAlignment } ) }
						/>
						<AlignmentToolbar
							value={ textAlignment }
							onChange={ textAlignment => setAttributes( { textAlignment } ) }
						/>
					</BlockControls>
				) }

				<RichText
					tagName="div"
					multiline="p"
					placeholder= { __( 'Enter your message here...' ) }
					value={ message }
					style={ { textAlign: textAlignment } }
					onChange={ message => setAttributes( { message } ) }
				/>
			</div>
		);
	},

	save: props => {
		const{ blockAlignment, textAlignment, message } = props.attributes;

		return(
			<div
				className={ `align${blockAlignment}` }
				style={ { textAlign: textAlignment } }
			>
				{ message }
			</div>
		);
	}

} );
```

**Comment by iseulde** [comment]
Is this still an issue now? Also note that the `source` should be `string`, not `children`.

**Comment by designsimply** [comment]
I tried adding the code and could not see the problem. 

Please update to the latest version of WordPress (currently 5.0.1) and make the modification mentioned in the last reply and try testing again. If the problem is still happening, please re-open the issue. Thank you!

**Comment by greghollowell** [comment]
@emfluenceindia, if you're still messing with this, try replacing
`onChange={ message => setAttributes( { message } ) }`
with
`onChange={ newMessage => setAttributes( { message:newMessage } ) }`
in your edit function.

**Comment by emfluenceindia** [comment]
> @emfluenceindia, if you're still messing with this, try replacing
> `onChange={ message => setAttributes( { message } ) }`
> with
> `onChange={ newMessage => setAttributes( { message:newMessage } ) }`
> in your edit function.

Thank you!
