### ISSUE TITLE
Clicking the "Keyboard Shortcuts" button in the Classic block does nothing. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9748]
**Describe the bug**

Clicking the "Keyboard Shortcuts" button in the Classic block has no effect. 

**To Reproduce**

1. Insert a classic editor block.
2. Expand the classic block controls to show the second line. 
3. Click the question mark icon. 
4. Nothing happens.

**Expected behavior**

It seems like (most of?) the classic editor shortcuts work, so I'd expect that the keyboard shortcuts modal shows up. 

**Screenshots**

<img width="670" alt="screen shot 2018-09-10 at 9 42 06 am" src="https://user-images.githubusercontent.com/1202812/45301892-e0619b80-b4df-11e8-95a8-30a10b3ef845.png">

**Tested in:**
Mac OS 10.13.6, Safari 11.1.2, Chrome 69.0.3497.81

**Comment by ianbelanger79** [comment]
I can confirm that the "Keyboard Shortcuts" button does nothing when clicking on it.

Tested in Windows 10, Chrome and Firefox

**Comment by mtias** [comment]
Should we remove this button here given there's a more general one?

**Comment by chrisvanpatten** [comment]
Does the Classic block/TinyMCE have its own set of shortcuts that aren't included in Gutenberg's Keyboard Shortcuts modal?

**Comment by tofumatt** [comment]
> Does the Classic block/TinyMCE have its own set of shortcuts that aren't included in Gutenberg's Keyboard Shortcuts modal?

They aren't labelled, but yes.

**Comment by tofumatt** [comment]
I don't see any keyboard shortcuts on the TinyMCE buttons:

<img width="258" alt="screenshot 2018-11-19 11 45 13" src="https://user-images.githubusercontent.com/90871/48705249-95a38480-ebf0-11e8-9e7e-5ff08b6e0fde.png">
<img width="136" alt="screenshot 2018-11-19 11 45 07" src="https://user-images.githubusercontent.com/90871/48705250-95a38480-ebf0-11e8-8ea2-ed2f02a3239f.png">

But actually I don't see too many we're missing from https://www.tiny.cloud/docs/advanced/keyboard-shortcuts/

What you're talking about doing (having keyboard shortcuts vary based on block selection) is bad UX to me. Keyboard shortcuts should be global and the Classic Block isn't a UX I think we want to advertise, right? It taking up space in the global shortcuts just adds noise and having it contextually appear seems like a lot of added complexity for a UX that won't be clear. Would that extend to other blocks? Would a custom block be able to add to the shortcuts modal (but only when selected).

I think we should just remove the button. If the Classic Block has extra features we aren't advertising I think that's fine. Classic Block is already quite "expert mode". 🤷‍♂️

**Comment by mtias** [comment]
Related #6195.

**Comment by youknowriad** [comment]
closed in #11856
