### ISSUE TITLE
Packages: Deprecated: Gutenberg-independent deprecations

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#9753]
Related: [Discussed during September 4th JavaScript Chat](https://make.wordpress.org/core/2018/09/05/javascript-chat-summary-september-4th/)

Currently, all calls to the `deprecated` function pass a Gutenberg version number at which the feature is to be deprecated. This is sensible within the context of the Gutenberg plugin, but has no meaning in the context of the published npm package.

This raises a few questions (action items denoted by ⚠️):

- Should npm package releases have a separate schedule for feature deprecation?
   - Currently: **No**
   - ✅ Operating assumption for intended ideal: **No**. Preferably, at least one minor version of the package with `deprecated` message is published ([reference](https://semver.org/#spec-item-7)).
- Should npm packages log warnings including the Gutenberg deprecation version?
   - Currently: **Yes**
   - ⚠️Operating assumption for intended ideal: **No**. It's suggested that the message be made filterable, with no default Gutenberg references for the published `deprecated` module messaging. The Gutenberg references should be added by an extension via [_???_] (implementation undetermined)
- Should the public API interface of `deprecated` include `plugin` and `version` options?
   - Currently: **Yes**
   - ⚠️Operating assumption for intended ideal: **Unknown**. The `plugin` option is probably unnecessary, though it may be sensible to have some built-in knowledge / messaging of a deprecation removal version. In these cases, it may be required to allow granular extension of specific message fragments (e.g. [the variables composing the `deprecated` message](https://github.com/WordPress/gutenberg/blob/960bb6e263ed4ee1d57a8b84c8e2fc62c1d69920/packages/deprecated/src/index.js#L34-L35)).

**Comment by paaljoachim** [comment]
I see a merged PR here so that I will close this old issue.

@gziolo (Greg I have been pinging you a lot to Andrew's older issues. I do hope that is alright.)

**Comment by gziolo** [comment]
It's less relevant as of today but we could change the package to print the Gutenberg plugin version only inside the plugin. It should be doable by using `GUTENBERG_PHASE` constant.
