### ISSUE TITLE
Classic Editor Toolbar doesn't disappear when out-clicking

### ISSUE THREAD

**Issue by ianbelanger79** [WordPress/gutenberg#9754]
After adding a Classic Editor block, the TinyMCE toolbar never goes away, even when clicking off the block. 

**To Reproduce**
1. Add a Classic block to a post/page
2. Click within the block, you can add text or not, doesn't matter
3. Click outside of the block and the toolbar remains

**Expected behavior**
The toolbar should disappear when you click off the block, just as all of the other blocks do.

**Screenshots**
![classic-editor-toolbar](https://user-images.githubusercontent.com/34601694/45305184-c330cb00-b4e7-11e8-9d31-4662c235b7cd.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome and Firefox
 - Gutenberg 3.7 and 3.8-rc-1

**Comment by youknowriad** [comment]
Actually, this is not a bug :) This is a special block reproducing the "classic editor"'s behavior. There has been a lot of exploration on how we can achieve this but with TinyMCE's toolbar, it's not possible to reliably hide/show it on focus. cc @jasmussen @iseulde

**Comment by ianbelanger79** [comment]
Ok thanks @youknowriad, I will re-label and close it out

**Comment by jasmussen** [comment]
Yep, the context is in https://github.com/WordPress/gutenberg/issues/4926. 👍 👍
