### ISSUE TITLE
React.js is loaded in production mode, making React dev throw "Minified React error #130"

### ISSUE THREAD

**Issue by mintplugins** [WordPress/gutenberg#9758]
I'm not totally sure what the right path forward here is, so my apologies if this is wrong place to ask for clarification. 

I'm doing development with React.js in my own plugin, but I am not running Gutenberg in `development` mode, nor am I even pulling it from Github. Therefore, I believe Gutenberg assumes it is in production mode, and thus, loads the minified version of ReactJS. 

However, in my own plugin, I am enqueueing React using wp_enqueue_script, and I am unable to get Javascript error messages in my console, with all errors outputting a generic message, which is `"Minified React error #130"`. 

If I uninstall Gutenberg, everything is fine, and I get full Javascript errors in the console, allowing me to do development work on the plugins I am working on. 

Is there a way to put Gutenberg into `development` mode without needing to pull it from Github and run npm ([which fails for me currently](https://github.com/WordPress/gutenberg/issues/9474))?

**Comment by youknowriad** [comment]
Try setting `SCRIPT_DEBUG` to true in your local install, it should load an unminified version of React.

**Comment by mintplugins** [comment]
Yep that did it. Thanks @youknowriad. Totally slipped my mind (new dev environment).

**Comment by emilushi** [comment]
Setting `SCRIPT_DEBUG` to `true` isn't working on WordPress 5.0

**Comment by jakeparis** [comment]
Fwiw, it's working in WP 5.6
