### ISSUE TITLE
Editor disappearing when tabbing to the end of the editor while sidebar is open

### ISSUE THREAD

**Issue by afercia** [WordPress/gutenberg#976]
I can reproduce this on both Chrome and Firefox, macOS. To reproduce:

- using the keyboard, tab through the admin content 
- when you reach the Post Settings button (hard to see because there's no visual focus indicator right now), press the button to open the Sidebar
- continue tabbing
- when you reach the end of the content, the whole editor disappears

Note: to make point 2 easier to test, notice the Inserter button slight color change when focused, tab again and you're on the Post Settings button.

Video (22 seconds):
https://cloudup.com/cVM3pq9zGZx

**Comment by youknowriad** [comment]
I can't reproduce this anymore.

**Comment by youknowriad** [comment]
Closing, feel free to reopen if you experience this again.
