### ISSUE TITLE
Copy and Paste from Microsoft Word into Gutenburg in Google Chrome

### ISSUE THREAD

**Issue by troytempleman** [WordPress/gutenberg#9761]
**Description of the bug**

Copying and pasting text from Microsoft Word into the Gutenburg editor in Google Chrome gives undesirable results. The title pastes fine but when pasting the remaining text underneath the title, the first block of text gets filled with code, seemingly font styles from Microsoft Word (see https://user-images.githubusercontent.com/15160389/45310537-1400ed80-b501-11e8-9310-5eff8681ddf3.jpg).

The text does get pasted and formatted as expected but you have to scroll down underneath the first block to see it (see https://user-images.githubusercontent.com/15160389/45310546-1fecaf80-b501-11e8-97b6-8cc875161d62.jpg). You then have to delete the first block of styles to achieve the desired result.

**To Reproduce**

1. Copy title **Lorem ipsum dolor...** from  https://github.com/WordPress/gutenberg/files/2367501/Word.docx and paste into Gutenburg editor in Google Chrome
2. Copy remaining text from Word document and paste into Gutenburg editor, underneath above title.

**Expected behavior**

Pasted text should retain the same formatting as in the Word document, without any extra code and/or styles being inserted.

**Screenshots**

![screenshot-1](https://user-images.githubusercontent.com/15160389/45310537-1400ed80-b501-11e8-9310-5eff8681ddf3.jpg)
![screenshot-2](https://user-images.githubusercontent.com/15160389/45310546-1fecaf80-b501-11e8-97b6-8cc875161d62.jpg)

**Desktop**
 - Windows NT 10.0
 - Chrome 68
 - See whatsmybrowser.org/b/YKKNBLZ for more information

**Additional context**
- WordPress 4.9.8 and Gutenburg 3.7.0

**Comment by designsimply** [comment]
Thank you for reporting this! Noting that you've tested different browsers is valuable, and I would like to consolidate this report together with #9719 as it looks the same to me. If you think this issue should remain open separately, please let me know.

**Comment by wouthe** [comment]
I have the same issue.

I used to copy text from Word to WP all the time. Now a ton of unnecessary markup shows up in Gutenberg from Word that is not even visible in word itself.

A solution to this is in Word to go to mark-up options and uncheck 'comments, ink, insertions and  formatting' before copying the text.

This needs to be fixed asap!

**Comment by designsimply** [comment]
@wouthe your issue looks different enough than the one reported here to create a new issue—it looks like it could be a copy/paste of some text while in a comment or editing mode of some kind. It would be really helpful to have some additional details posted in a new issue with screenshots of both Word and WP (it's best to get the whole window, including the menu bar). Please go to https://github.com/WordPress/gutenberg/issues/new/choose and create a new issue and add your screenshot and, if possible, please also note:

* Mac or Windows or Linux
* Browser version you are using
* Word version you are using (online or standalone install?)
* When you are in Word, do you have [Track Changes](https://support.office.com/en-us/article/track-changes-in-word-197ba630-0f5f-4a8e-9a77-3712475e806a) turned on?
* Screenshot of the same text in the Word doc if you can get one
