### ISSUE TITLE
IE11: Uncropped gallery images are being stretched. 

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9764]
**Describe the bug**

When using the `master` branch in IE11, gallery images appear stretched when the gallery is set to uncropped. I'm seeing this in both the front and backend. 

This doesn't happen when using `3.8-rc1`, so I'm guessing it has to do with #9622 (cc @jasmussen). This could use verification just in case there's something weird going on with my IE virtual machine. 

**To Reproduce**

1. Use IE11
2. Add a gallery
3. In the settings sidebar, set the gallery images to appear uncropped.

**Screenshots**

![ie-11](https://user-images.githubusercontent.com/1202812/45317392-e2d7eb80-b507-11e8-84f7-faa4c6007047.gif)

![screen shot 2018-09-10 at 2 47 30 pm](https://user-images.githubusercontent.com/1202812/45317605-7b6e6b80-b508-11e8-8bf3-24921b2ffdfd.png)

**Tested in**
Windows 7, IE 11.0.9600.19080

**Comment by b3rend** [comment]
I tested in in IE 11 on a Windows 10 machine as well (using 3.8.0-rc.1) but the issue still exists:

![ie11_test](https://user-images.githubusercontent.com/3236267/45416925-433e6880-b681-11e8-9a28-6f4833c2591c.png)

Chrome is fine, except for the alignment of the text. However I see a fix suggested for that in #9762 
![chrome_test](https://user-images.githubusercontent.com/3236267/45416985-69fc9f00-b681-11e8-8ddf-b8ab4bdc4dc4.png)

**Comment by youknowriad** [comment]
I can't reproduce this anymore
