### ISSUE TITLE
Drag & Drop stalls

### ISSUE THREAD

**Issue by bph** [WordPress/gutenberg#9766]
**Describe the bug**
Drag & Drop works very well, until a Twitter embed is in the picture. After a few drag’n drops – it all of a sudden stalls. Seems only to happen with Google Chrome browser. I was not able to replicate it in Firefox Developer edition. 

**To Reproduce**
1. create a few blocks
2. make one of them a Twitter embed ([example](https://twitter.com/jrf_nl/status/1039199312448761857))
3. Drag and drop blocks to different positions a few times
4. See stalling

**Expected behavior**
I expected to drag and drop as often as I want, until I make up my mind. 

**Screenshots**
Made a video : http://recordit.co/lTWDYXHgLM

**Desktop (please complete the following information):**
 - OS: MAC 
Google Chrome 68.0.3440.106 , 
Firefox Developer 63.0b1

**Comment by nosolosw** [comment]
Thanks for the detailed report! 

This is a known issue that has been reported at https://github.com/WordPress/gutenberg/issues/6145 We have a fix prepared https://github.com/WordPress/gutenberg/pull/9511 that will be merged in 3.9.
