### ISSUE TITLE
Keyboard Shortcut Cmd-Shift-D results in duplicate toolbar items when used on the same block more than once

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#9773]
Steps to reproduce:

1. Use the More menu in the top toolbar and make sure "Unified Toolbar" is unchecked.
1. Create a post and add any block such as a cover image or paragraph.
1. Select the block.
1. Press Cmd-Shift-D to duplicate the block.
1. Select the previous block again.
1. Press Cmd-Shift-D to duplicate the same block again.

<strong>Result:</strong> when the block is duplicated the second time around the main toolbar items appear duplicated until there is an autosave or until something in the toolbar is clicked that alters the contents of the block. ([54s](https://cloudup.com/c198tns1xTd))

![duplicate-toolbar-items](https://user-images.githubusercontent.com/1119271/45329589-68669600-b51e-11e8-9f72-5612dcf52e32.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14849&action=edit running WordPress 4.9.8 and Gutenberg 3.8.0-rc.1 using Firefox 62.0 on macOS 10.13.6. Note: also tested with Chrome 68.0.3440.106 on macOS 10.13.6.</sup>

Note: I tested with 3.7, 3.8.0-rc.1, 47cd11fbb (3.8-pre-release), and the same problem happened in all of those versions.

Odd bug, rather obscure, might be worth a low priority lable and I'll wait for a 2nd opinion on that.

**Comment by jorgefilipecosta** [comment]
Hi @designsimply thank you for reporting this issue. I'm not being able to reproduce the problem, the blocks and the interface suffered many changes, I guess this problem was solved as a side effect of these changes.
