### ISSUE TITLE
Automatically add `mailto:` to email addresses when linking

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#9774]
The Classic editor automatically prepends `mailto:` to email addresses if you highlight them and click on the link icon. I think users will expect that Gutenberg does this as well ([example](https://wordpress.org/support/topic/links-in-gutenberg/)).

**Comment by iseulde** [comment]
Sounds like a fairly simple fix. Added the Good First Issue label.

**Comment by luisherranz** [comment]
I've made a PR: https://github.com/WordPress/gutenberg/pull/14857

The `link` component is using `@wordpress/url` to do the URL check but I haven't found anything similar in `@wordpress` so I have added a regexp. If you want I can do a PR to include an email validator in `@wordpress/url` or the appropiate library.
