### ISSUE TITLE
Table Block: table cells in thead are misaligned when "Fixed width table cells" is toggled off

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#9779]
Steps to reproduce:

1. Create a new table block.
1. Edit it to use the sample HTML below which contains `thead` and `tbody` tags.
1. Switch back to "Edit Visually."
1. Toggle the "Fixed width table cells" option in the sidebar.

<strong>Result:</strong> when "Fixed width table cells" is toggled off, the `thead` and `tbody` table cells are misaligned. 

<strong>Sample HTML:</strong> 

```
<table class="wp-block-table"><thead><tr><td><strong>Column One</strong></td><td><strong>Column Two</strong></td></tr></thead><tbody><tr><td>one</td><td>two</td></tr><tr><td>three</td><td>four</td></tr></tbody></table>
```

![screen shot 2018-09-10 at 8 01 26 pm](https://user-images.githubusercontent.com/1119271/45333705-cd2ceb00-b534-11e8-8b18-b36df5080ba5.png)
<sup>Seen at https://madefortesting.com/wp-admin/post.php?post=512&action=edit running WordPress 4.9.8 and Gutenberg 3.7 using Firefox 62.0 on macOS 10.13.6.</sup>

h/t @mcsf for the report at https://github.com/WordPress/gutenberg/pull/8767#issuecomment-417854831

**Note:** even though the alignment looks off in the editor, it looks correct on the front-end using the Twenty Seventeen theme ([screenshot](https://user-images.githubusercontent.com/1119271/45333658-9b1b8900-b534-11e8-838d-32595abcbb08.png)).

**Comment by fschtn** [comment]
I have this issues again on WP 5.9.1 😭

**Comment by talldan** [comment]
@francescosche Would you be able to make a new issue with some details of how to reproduce the problem?

If you can include information like which theme you're using, which browser and OS, that would be great. Thanks.
