### ISSUE TITLE
Is there iconpicker in gutenberg?

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9780]
Is there icon picker available for Gutenberg similar to this - https://www.youtube.com/watch?v=3y6-ESMHCZc

**Comment by youknowriad** [comment]
There's no "tutorial" or link to show this. You can just combien `Dashicon` to show the icons and build a react component looping over an array of icons and displaying them.

**Comment by prajaktagadhave** [comment]
Yes.. We managed to add this.

Just one question is there is any privilege to add iconpicker for core Gutenberg? 

Thank you.

**Comment by youknowriad** [comment]
> Just one question is there is any privilege to add iconpicker for core Gutenberg?

I'm not certain about this, it doesn't seem like a common component that will be used by a lot of plugin authors etc... In general UI libraries don't include such a component and is more composed from simpler ones. That said, it's just my opinion, others might feel differently.
