### ISSUE TITLE
Inline-Image needs alignment options

### ISSUE THREAD

**Issue by burnuser** [WordPress/gutenberg#9787]
At the moment Gutenberg does not allow embedding an image in the text flow within a block (Paragraph, List, ...) like in Classic editor.
The existing "Inline-Image" could resolve this problem, but it needs alignment (and size) options like regular images to do so. Without alignment, it only breaks the text flow!

**Comment by burnuser** [comment]
No developer response?
No solution?
No Milestone?
Nothing?

**Comment by youknowriad** [comment]
The inline-image has the "inline" alignment built-in. If you want to left/right align images, you should use the image block instead.

I'm closing as this doesn't seem like something actionable. Let's reopen if more information/actionable items are provided.
