### ISSUE TITLE
Center shortcodes

### ISSUE THREAD

**Issue by Sixtina1990** [WordPress/gutenberg#9790]
Hello,

I don't really have an issue more a question about what is possible.

I added a block "shortcodes"and entered the link of a website that I want to embed. 

I wanted to know if it is possible to also center the image or if it is always on the left? (see screenshot)
<img width="867" alt="bildschirmfoto 2018-09-11 um 14 01 37" src="https://user-images.githubusercontent.com/42411182/45362234-39a6f900-b5cc-11e8-949f-cf3d5ead59a7.png">

Thank you so much.

**Comment by Sixtina1990** [comment]
@Soean Thank you for the fast reply. I changed it to the embed blog. :) 
At the moment there seems to be a problem with the center function as I also cannot center my images anymore. :( but okay, no problem. I can wait for it to be fixed...at least I see what you mean when I choose embed, as I now have the same center option like with images, when it works 👍 Thank you so much :)

**Comment by tofumatt** [comment]
It might be that your theme doesn't support our alignment options, does the image appear centered in the editor?
