### ISSUE TITLE
The WP_Block_Parser class can't be loaded in the gutenberg_parse_blocks() function

### ISSUE THREAD

**Issue by imath** [WordPress/gutenberg#9791]
**Describe the bug**
Testing 3.8RC1 with one of my plugin, I've found that the `block-serialization-default-parser` package was missing into the packages folder.

**To Reproduce**
1. Download & Activate https://github.com/imath/gutenblocks/releases/tag/1.2.5
2. Create a new post
3. Type `/dubb` (or `/doubl` if you're french) into the default block and select the Dubber (or Doubleur if you're french) block
4. Type anything into one of the nested blocks and wait for the Autosave to throw the error "Updating failed"
5. Here's the output of the rest response:
```
Warning: require_once(PathTo\gutenberg\lib/../packages/block-serialization-default-parser/parser.php): failed to open stream:
No such file or directory in PathTo\gutenberg\lib\blocks.php on line 79
```

Looking into the packages folder of the **3.8 Release Candidate 1**, there's no block-serialization-default-parser/parser.**php** file in it. See screenshot below.

**Expected behavior**
the `gutenberg_parse_blocks()` function should load the WP_Block_Parser.

**Screenshots**
![ouchissue](https://user-images.githubusercontent.com/1834524/45362140-4b8c9a00-b5d4-11e8-9e6f-48d9dc5df5d0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 68

**Additional context**
- Gutenberg version: https://github.com/WordPress/gutenberg/releases/tag/v3.8.0-rc.1

**Comment by aduth** [comment]
Proposed fix at #9799
