### ISSUE TITLE
Add indication there are more blocks

### ISSUE THREAD

**Issue by karmatosed** [WordPress/gutenberg#98]
Where you have the + icon, it would be great to show there are more blocks. For example here is what you see and here is a rather obvious (not at all styled) but visual adding of an indicator:

![2017-02-20 at 11 53](https://cloud.githubusercontent.com/assets/253067/23124157/71b34dd6-f763-11e6-9447-77438dc3166a.png)

I didn't want to add in any styling as much as try and show the need for some indication. This could be indication with an interaction though. Perhaps that will be better suited here. On first load for me, knowing there was scrolling wasn't obvious.

**Comment by jasmussen** [comment]
The latest mockup adds a drop shadow to the bottom element to show that the "sheet" continues downwards:

https://github.com/WordPress/gutenberg/blob/master/mockups/Insert.png

There's also a scrollbar. But this definitely needs iteration still. solid points.

**Comment by aduth** [comment]
>The latest mockup adds a drop shadow to the bottom element to show that the "sheet" continues downwards:

Would the gradient disappear once scrolled to the bottom of the list?

**Comment by jasmussen** [comment]
> Would the gradient disappear once scrolled to the bottom of the list?

That's a good idea.

**Comment by karmatosed** [comment]
The gradient is a good idea. I also really like the removing when at bottom - showing state.

**Comment by aduth** [comment]
For reference, the WordPress.com editor does something similar for indicating more options available in the small viewport toolbar:

![toolbar](https://cloud.githubusercontent.com/assets/1779930/23130277/d033eb3c-f753-11e6-9684-7c7184b968e6.gif)
