### ISSUE TITLE
Text color for selected text WITHIN a paragraph

### ISSUE THREAD

**Issue by RayWaldo** [WordPress/gutenberg#9809]
**Is your feature request related to a problem? Please describe.**
I cannot find any way to highlight / change text color for selected text - e.g. within a block - not for the entire block.
**Describe the solution you'd like**
Please add text color to the options available within a block (similar to how BOLD is featured).
**Describe alternatives you've considered**
I don't see any alternatives.

**Comment by GlennMartin1** [comment]
Agreed. This is a legitimate issue.

**Comment by GlennMartin1** [comment]
In a similar vein, it's impossible to specify a different size for select text within a block. 

The paragraph block will be the most commonly used block, and hence should have greater functionalities.

**Comment by Soean** [comment]
@RayWaldo Thanks for this feature request, we already have a ticket for this feature: see https://github.com/WordPress/gutenberg/issues/6080
We can discuss over there, so I am closing this one.
