### ISSUE TITLE
Release Candidate Notification before updating Gutenberg Plugin on the repository

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#9810]
Been thinking about this comment of Joost de Valk : https://www.facebook.com/groups/161444577756897/permalink/325434208024599/?comment_id=327563271145026&reply_comment_id=328723721028981&notif_id=1536729213684932&notif_t=group_comment_mention and realized that there's no way for us devs to get notification when RC is available. This will help us a lot to upload fixes before the users will upgrade their versions. 

Email notification to plugin devs with "Gutenberg" tag will be great but if this can't be done this thread will surely help. @aduth @gziolo Will it be possible to post the RC link here? With this, we can just turn on notification on this thread to get notified via email. Let me know your thoughts. Thanks!

**Comment by pento** [comment]
Hey @phpbits!

Gutenberg RC releases are posted to the [make/test blog](https://make.wordpress.org/test/), you can subscribe to that blog for notifications.

**Comment by phpbits** [comment]
@pento Woah! Perfect! Subscribed! Thank you very much.

**Comment by phpbits** [comment]
@pento Oops. Got this error when subscribing 

<img width="271" alt="screen shot 2018-09-12 at 1 46 08 pm" src="https://user-images.githubusercontent.com/3365507/45404627-4b52d400-b692-11e8-95c7-96266bef7cbb.png">
