### ISSUE TITLE
Error when using blocks.getSaveElement to wrap blocks in wrapper div with block style variations

### ISSUE THREAD

**Issue by florianbrinkmann** [WordPress/gutenberg#9811]
**Describe the bug**

I try to wrap core blocks into wrapper elements. For that, I use the `blocks.getSaveElement` filter like that:

```
wp.hooks.addFilter(
	'blocks.getSaveElement',
	'namespace/modify-get-save-element',
	modifyGetSaveElement
);

/**
 * Wrap block in div.
 * 
 * @param {object} element 
 * @param {object} blockType 
 * @param {object} attributes 
 * 
 * @return The element.
 */
function modifyGetSaveElement( element, blockType, attributes  ) {
	if (!element) {
		return;
	}

	if (blockType.name === 'core/quote') {
		return (
			<div className='quote-wrapper'>
				{element}
			</div>
		)
	}

	return element;
}
```

This works well when no block style variation is selected. When using a variation, I get block validation errors:

```
Block validation: Expected attribute `class` of value `wp-block-quote`, saw `wp-block-quote is-style-large`.
Block validation: Expected attribute `class` of value `wp-block-quote`, saw `wp-block-quote is-style-large`.
Block validation: Expected attribute `class` of value `wp-block-quote blocks-quote-style-1`, saw `wp-block-quote is-style-large`.
```

I don’t know if I am just using the filter wrong maybe? I also tried to use `cloneElement()`, because it is mentioned in the Handbook (https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/#blocks-getsaveelement), but that did not make a difference.

**To Reproduce**
1. Put the code from above into a plugin, compile it via Babel and activate it.
2. Insert a quote block.
3. Select the large quote style.
4. Save the post and reload the editor.
5. You should get block validation errors.

**Expected behavior**

No block validation error :)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version 64.0a1 (2018-09-10) (64-Bit)

**Additional context**
- Gutenberg 3.7.

**Comment by designsimply** [comment]
I found a past issue that sounds similar to me. As a first check, do the replies in #6380 help you?

**Comment by f4w-pwharton** [comment]
For some reason the 'is-style-large' etc classes have to be on the outer (root) element for the block. So in your case the div.quote-wrapper you've added.

I haven't had time to trace this but getActiveStyle takes a class string and array of styles and returns the active style from that:
https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/components/block-styles/index.js#L30

I'd guess the class of the root block element is being used as the source of truth for the active style rather than (say) an attribute.

```javascript
wp.hooks.addFilter('blocks.getSaveElement', 'pw-examples/wrap-core-blocks', function (element, blockType, attributes) {
  if ( blockType.name.substr(0, 5) === 'core/' && wp.element.isValidElement(element) ) {
    return wp.element.createElement('div', {
      'class': 'wp-block-wrapper ' + (
          typeof element.props.className === 'string' && element.props.className.match(/(^|\s+)wp-block-/) ? 
          element.props.className.replace(/wp-block-/, 'wp-block-wrapper-') : 
          'wp-block-wrapper-' + blockType.name.replace(/\//, '-').replace(/^core-/, '')
        ),
      'data-type': blockType.name
    }, element);
  }
  return element;
});
```

The above is my hacky work around; it will transform the wp-block-* class to wp-block-wrapper-* and leave the rest of the classes intact.

e.g. `wp-block-quote is-style-large` becomes `wp-block-wrapper wp-block-wrapper-quote is-style-large`

This seems to work although I've only tested it on a few blocks.

**Comment by giacomoalonzi** [comment]
@f4w-pwharton hi, I tried your script but i have this error.
Can you help me? 

![Image error](https://duaw26jehqd4r.cloudfront.net/items/110N3G1Q0k292P1i270j/Screenshot%202019-01-10%20at%204.40.19%20PM.png?X-CloudApp-Visitor-Id=2805656&v=122f4fd6)

**Comment by f4w-pwharton** [comment]
Most of the core blocks are static (not dynamic) so their rendering is done in the block editor when saving the post.

Options:

1. Turn them all in to [dynamic blocks](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/creating-dynamic-blocks/): You'd probably have rewrite all the renderers in PHP so this wouldn't really be feasible.
2. Write a [block deprecation](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-deprecation/) for each of the core blocks to convert them automatically. There is probably a way to automate this and inject it via the [registerBlockType filter](https://wordpress.org/gutenberg/handbook/designers-developers/developers/filters/block-filters/#blocks-registerblocktype)
3. Recreate all your content (delete/insert the block again) - or only use this wrapper on new sites.

Whatever you choose, you'll run in to this problem again when WP updates one of the core blocks as their included deprecation won't work; so you'll have to work out a way around this (maybe via point 2. above).

**Comment by designsimply** [comment]
@florianbrinkmann since this issue was originally posted some time ago, may I check in with you to ask if you're still seeing block validation errors when using block style variations for your custom block?

**Comment by florianbrinkmann** [comment]
Hey @designsimply, tested it with WP 5.0.3 and seems to work now!

**Comment by thiagolcks** [comment]
Hey @florianbrinkmann, I tried to use your snippet and it seems to work fine, but when I reload the editor I get the message "This block contains unexpected or invalid content". Any idea how to fix?

**Comment by florianbrinkmann** [comment]
Hi @thiagolcks, are you running the filter inside `wp.domReady()`? If so, move the code outside of that and it should work (I had this issue with a current project and needed some time to find the reason).

**Comment by thiagolcks** [comment]
@florianbrinkmann, nops, I'm using it outside domReady. Just using your snippet as it is.

**Comment by florianbrinkmann** [comment]
Hm, what error is triggered exectly?

**Comment by thiagolcks** [comment]
This error:
```
Block validation: Block validation failed for `core/quote` ({name: "core/quote", title: "Quote", description: "Give quoted text visual emphasis. "In quoting others, we cite ourselves." — Julio Cortázar", icon: {…}, category: "common", …}).

Expected:

<blockquote class="wp-block-quote blocks-quote-style-1 quote-wrapper"><p>Something</p><p></p></blockquote>

Actual:

<div class="quote-wrapper"><blockquote class="wp-block-quote"><p>Something</p><p></p></blockquote></div>
```

Thanks you, @florianbrinkmann

**Comment by florianbrinkmann** [comment]
Tried it out and got the same error. Reopening the issue.

To reproduce:

Add the following code into a plugin:

```
wp.hooks.addFilter(
	'blocks.getSaveElement',
	'namespace/modify-get-save-element',
	modifyGetSaveElement
);

function modifyGetSaveElement( element, blockType, attributes  ) {
	if (!element) {
		return;
	}

	if (blockType.name === 'core/quote') {
		return (
			<div className='quote-wrapper'>
				{element}
			</div>
		)
	}

	return element;
}
```

Enable the plugin, insert a quote block and select the `large` style. Save and reload the editor.

Issue is present in both – Gutenberg that comes with WP 5.1 and the Gutenberg plugin 5.2.

**Comment by danielbachhuber** [comment]
I'm experiencing a similar issue with the following custom code:

```js
/**
 * Wrap block in div.
 *
 * @param {object} element
 * @param {object} blockType
 * @param {object} attributes
 *
 * @return The element.
 */
function modifyGetSaveElement( element, blockType, attributes  ) {
	if (!element) {
		return;
	}

	if (blockType.name === 'core/quote' || blockType.name === 'core/paragraph' || blockType.name ===  'core/heading') {
		return (
			<div class='feature-content'>
				<div class='feature-body'>
					<div class='feature-cell'>
						{element}
					</div>
				</div>
			</div>
		)
	}

	if (blockType.name === 'core/media-text' || blockType.name === 'core/columns') {
		return (
			<div class='feature-content'>
				<div class='feature-body'>
					{element}
				</div>
			</div>
		)
	}

	return element;
}
```

When I add `testclass` to a column block with a paragraph block:

<img width="1163" alt="image" src="https://user-images.githubusercontent.com/36432/56987756-29d02b00-6b43-11e9-9beb-a2d6227c7455.png">

Then the block serializes as expected:

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/36432/56987803-4b311700-6b43-11e9-86f9-fa35a394a22b.png">

However, if I "Save Draft" and reload the page, the block is crashed:

<img width="812" alt="image" src="https://user-images.githubusercontent.com/36432/56987836-5e43e700-6b43-11e9-995c-5c088d6821c9.png">

**Comment by philbirnie** [comment]
@danielbachhuber I ran into the same issue, although as @strive-phil suggested, adding the class to the new element container as  shown code below seems to allow everything to work as it should.

```js
import classnames from 'classnames';

const pbUpdateGroupWrapper = function ( element, blockType, blockAttributes ) {
	if (!element) {
		return;
	}

	if (blockType.name === 'core/group') {
		const sectionClassNames = classnames( 'o-section', blockAttributes.className );
		const containerClassNames = classnames( 'o-container' );

		return (
			<section className={ sectionClassNames }>
				<div className={ containerClassNames }>
					{ element }
				</div>
			</section>
		)
	}
	return element;
};
```

**Comment by fastpenguin91** [comment]
@florianbrinkmann  It's weird how the original code you posted works for you without a style variation.

When I use the exact code you have and use the default style I'm still getting a block validation error.  I mean it makes sense since in that code there's no deprecation added...

**Comment by florianbrinkmann** [comment]
Hi @fastpenguin91,

I have not tested it, but yes, after thinking about it, I guess you are right, and it will only work for blocks that are added after the code change, with old blocks breaking because of block validation error. Maybe the best way to add a wrapper would be to use the `render_block` PHP filter.

**Comment by markhowellsmead** [comment]
https://github.com/WordPress/gutenberg/issues/9811#issuecomment-488083972

@danielbachhuber A long time ago, now. But this code uses `class` instead of `className`. That won't work.

**Comment by paaljoachim** [comment]
Hey @florianbrinkmann Florian.
It would be great to test using the newest WordPress version and Gutenberg plugin.
How can we move this issue forward?
@danielbachhuber @markhowellsmead @fastpenguin91

**Comment by florianbrinkmann** [comment]
Hi @paaljoachim,

for me that is not an issue anymore, because I would do that via the `render_block` filter now.

**Comment by paaljoachim** [comment]
Thank you for the feedback Florian.
I will get a hold of one more person to confirm we can close this issue.

**Comment by youknowriad** [comment]
Closing. `render_block` is indeed a better solution when it comes to altering the markup without risking invalidation.

**Comment by deveasin** [comment]
I have solved it by checking the current modified block is used/saved in the current post/page. Below the example code.

```
wp.hooks.addFilter(
	'blocks.getSaveElement',
	'namespace/modify-get-save-element',
	modifyGetSaveElement
);

/**
 * Wrap block in div.
 * 
 * @param {object} element 
 * @param {object} blockType 
 * @param {object} attributes 
 * 
 * @return The element.
 */
function modifyGetSaveElement( element, blockType, attributes  ) {
	if (!element) {
		return;
	}

    let getBlocks = wp.data.select('core/editor').getBlocks();
    // checking current block is used in the current post/page
	if (blockType.name === 'core/quote' && getBlocks.find(block => block.name === 'core/quote')) {
		return (
			<div className='quote-wrapper'>
				{element}
			</div>
		)
	}

	return element;
}
```
