### ISSUE TITLE
How to get current Page Template when editting a page?

### ISSUE THREAD

**Issue by foreverpinetree** [WordPress/gutenberg#9817]
I am working on making my theme to be compatible with Gutenberg. The theme has many page templates and each template has different options & layout, so I want to split them out according to the page template (After getting the page template, I will add a class to the body like page-template-{value}).

Question: 
Is there a API/Hook to get the value? Or, should I use the JS: `$('.editor-page-attributes__template select').val()` to get it?

Regards

**Comment by foreverpinetree** [comment]
Any info about this question?

OK, I used the JS to query the select value, BUT!!!!!!!!!!! This project use React tech so when the Page attributes is closed it wouldn't render the select tag. That means I have no way to get the value unless providing API or Hook. Help!!!!!!!!!!!!

**Comment by designsimply** [comment]
Apologies for not being able to get to this request sooner! Some changes have happened to how Custom Editor Styles work and I have posted an explanation and example which may be helpful to you at https://github.com/WordPress/gutenberg/issues/12874#issuecomment-452929053 and I would like to close this issue in favor of continuing the discussion there.

Thank you so much for your testing and asking questions about Gutenberg styling!
