### ISSUE TITLE
Drop a block above another moves it below instead

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#9823]
Steps:

- Drag a block A at index i.
- Drop it on the top dropzone of a block B whose index is j > i.
- The expected result is that the block A is positioned on top of block B.

Currently, what happens is that block A is moved below block B:

![peek 2018-09-27 12-11](https://user-images.githubusercontent.com/583546/46139340-94885380-c24e-11e8-8dfd-8d6e2ec4fce3.gif)

**Comment by bph** [comment]
The drag & drop seems to be intermittent. It’s hard to nail down, though, what exactly goes wrong when. 
Sometimes the landing zone is on the top of another block, but when I release the block it actually lands underneath the block. 
The scrolling is delayed so when I try to move things below the top of the bottom edge it doesn’t seem to wanna go….
It feels a bit arbitrary – here is a screen recording of such a session: http://recordit.co/AQYO4qrr1R
Google Chrome V. 68.0.3440.106
OS MAC 10.13.6

**Comment by nosolosw** [comment]
This will be fixed by https://github.com/WordPress/gutenberg/pull/10201

**Comment by nosolosw** [comment]
https://github.com/WordPress/gutenberg/pull/10201 has been merged and the fix will be included in the 4.0 RC.
