### ISSUE TITLE
Do not allow dropping a block below the blank inserter

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#9824]
See 

![peek 2018-09-12 13-49](https://user-images.githubusercontent.com/583546/45423538-f57f2b80-b693-11e8-90d7-0fa97ee7eaeb.gif)

**Comment by jorgefilipecosta** [comment]
Hi @nosolosw thank you for reporting this issue. I verified the issue is still happening I guess the best solution would be to not pass onDrop in the block appender.

**Comment by ellatrix** [comment]
I don't understand what the issue is here.
