### ISSUE TITLE
Add "Paragraph" Alignment for Headers

### ISSUE THREAD

**Issue by cdfleming** [WordPress/gutenberg#9825]
Gutenberg allows users to left, center, or right-align paragraph text, **but not headers.** Blog posts look strange when you can't justify/align headers the same as text. Please give headers the ability to be left, center, and right-aligning.

**Comment by youknowriad** [comment]
Thanks for the issue,

The alignment toolbar is already available for headings. It's in the inspector sidebar though and not in the block toolbar.

There's already this issue #3785 discussing consistency between blocks.

**Comment by varunsngl** [comment]
Thank you so much!
