### ISSUE TITLE
Gutenberg, Grammarly, and Feedly

### ISSUE THREAD

**Issue by bekeeg** [WordPress/gutenberg#9831]
**Describe the bug**
Using the Gutenberg editor (v3.6.2) and the Chrome extension Grammarly, when a word is marked as unknown or not capitalized correctly, and the user does not correct the issue, the word *sometimes* ends up missing from the RSS reader. This appears after the user activated the Gutenberg editor.

**To Reproduce**
1. Ensure Grammarly extension is active on the domain
2. Add New Post
3. Type the name of any day of the week in lower case in a sentence
4. Allow Grammarly to apply the thick, red underline so you know it's been flagged
5. Do not correct the issue
6. View the RSS feed to see classes applied to the flagged word:
`<g class="gr_ gr_5 gr-alert gr_spell gr_inline_cards gr_run_anim ContextualSpelling ins-del multiReplace" id="5" data-gr-id="5">`
7. View post in Feedly RSS Reader

**Expected behavior**
All text in the post is expected to appear in the Feedly RSS reader.

**Screenshots**
<img width="660" alt="wp post" src="https://user-images.githubusercontent.com/17302087/45429519-18e0b100-b669-11e8-9ada-91aada6ea595.png">
<img width="961" alt="raw rss feed" src="https://user-images.githubusercontent.com/17302087/45429527-1d0cce80-b669-11e8-8b43-525fcd4ae8b4.png">
![feedly post](https://user-images.githubusercontent.com/17302087/45429642-52192100-b669-11e8-981a-3d6ea5c61428.png)

**Desktop (please complete the following information):**
- iOS 10.13.5
- Chrome 
- Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by dartiss** [comment]
Grammarly is also doing the same for AMP posts - essentially rendering sections of a Gutenberg post invisible in AMP output.

Not sure if this is a Gutenberg issue or Grammarly's but it certainly only happens under GB.

**Comment by youknowriad** [comment]
Unfortunately this isn't immediately actionable within Gutenberg, I suggest raising this issue to the Grammarly extension authors.
