### ISSUE TITLE
Cannot Leave a Page or Post without Publishing (possible theme conflict Genesis/StudioPress)

### ISSUE THREAD

**Issue by OnQmarketing** [WordPress/gutenberg#9833]
When I was testing the Gutenberg plugin on a site using Genesis and a Studio Press Theme, I opened a page and clicked on several blocks.

I added a block to see how it might appear.

There was no intent to publish changes.  When trying to leave the page, I could see the warning box at the top of the screen inform me about leaving the page without making changes, but only for less than a second and it was gone. 

Clicking undo several times to get back to the original page did not resolve the issue.

I save the file as a draft and then changed its status to Publish to get the page back to a live status.

**Comment by designsimply** [comment]
Thanks for noting this. I can help with getting this reported to the theme authors. Do you know if it has already been reported to them by chance?

May I ask for version numbers so we have them noted for reference (for Gutenberg and Genesis and your theme name)?

Can you recommend a specific StudioPress theme and do you know if any are available for free for testing?

**Comment by OnQmarketing** [comment]
This is the first location I have noted this issue. It has not been directly reported to the theme authors.

Genesis version 2.6.1 Release March 2018

**Comment by nickcernis** [comment]
@OnQmarketing I was not able to reproduce this in my tests with any Genesis child theme so far.

I tried the following with [Gutenberg 4.0-rc1](https://make.wordpress.org/test/2018/10/10/call-for-testing-gutenberg-4-0-pre-release/) Genesis Sample 2.6.0, and Genesis 2.6.1:

1. Creating a new page.
2. Saving as draft.
3. Adding a new block.
4. Saving.
5. Visiting the Dashboard.

I am able to visit the dashboard without publishing, and the page is still in draft status when I return to it.

I also tried:

1. Editing an existing page that's in draft status.
2. Adding a new block.
3. Immediately attempting to visit the dashboard before auto-save has taken place.
4. I see this dialogue box and am not able to leave the page before choosing an option:
    ![screen shot on 2018-10-12 at 20 48 00](https://user-images.githubusercontent.com/647669/46888236-2d7ab980-ce60-11e8-97a8-09d189614ff6.png) 
    If I click Leave, I see the Dashboard. Returning to the page shows the content as it was, prior to adding the new block. If I click Cancel, I see the page again instead of leaving for the Dashboard.

I work on Genesis child themes with the StudioPress team. If you are still seeing issues, I'd be happy to investigate further if you can offer more information. Specifically:

1. What are the exact steps you are taking that cause a page to require publishing before you can leave it? (Or is the issue something else?)
2. What child theme is currently active?

**Comment by designsimply** [comment]
Several updates have been made since the time of this report. Because of the updates and because someone else was unable to reproduce the problem in a test, I have closed this issue. Please re-open and note whether you've tested the latest versions if the problem is still happening for you!
