### ISSUE TITLE
Granular role management

### ISSUE THREAD

**Issue by gtermini** [WordPress/gutenberg#9839]
I was wondering if there were any plans of adding a more granular role management to Gutenberg, so that it can work on large-scale websites. What I mean by that is: allow a given WP role to only edit/use a given subset of block elements and features. This would allow editors and authors to be given edit access to pages on a website, but prevent them from changing the layout or adding "blacklisted" elements. Not sure if this makes sense, but Visual Composer implements it in a quite granular way - https://wpbakery.com/video-academy/control-user-group-access-wpbakery-page-builder-wordpress/

**Comment by tofumatt** [comment]
I think this is an interesting notion, though this might not be exactly the approach. I think it might be that we offer locked templates only to certain user roles which have a limited set of blocks?

I tried looking through open issues to see if we had an existing issue on this and I couldn't find one, but I think the idea that someone could offer this functionality is a good idea.

My thought is that this kind of role management is better left to a plugin, but I'm not sure if there's anything we need to do before a plugin could realistically do this.

**Comment by gtermini** [comment]
Thank you, Matt! On Slack someone pointed me to this plugin: https://wordpress.org/plugins/advanced-gutenberg/ which seems to implement what I had in mind. And yes, I agree with you that ideally this feature would be left to a plugin. I wanted to make sure Gutenberg has all it takes to allow it (and it looks like it does).

**Comment by tofumatt** [comment]
Oh, that's awesome! I didn't know about that plugin, but it looks great. I guess that means this issue is closed then? I will remember that plugin for any future user requests for such a feature, thanks!

**Comment by gtermini** [comment]
Yes, I think we can close it for now.

**Comment by StaggerLeee** [comment]
Do you make hiding/removing/adapting Gutenberg screen page difficult by purpose ?
I cannot hide items in "More Tools & Options" even with simple CSS code.
Everything has class **"components-button components-menu-item__button"**.

**Comment by StaggerLeee** [comment]
Anyway, if someone needs it. Put it in functions.php with User check to leave items available for Amdinistrator.

```
[aria-labelledby=components-menu-group-label-3] button:last-child  {
      display: none;
}
[aria-labelledby=components-menu-group-label-3] a:last-child  {
      display: none;
}
[aria-labelledby=components-menu-group-label-2] button:nth-child(3)  {
      display: none;
}
[aria-labelledby=components-menu-group-label-2] a:nth-child(2)  {
      display: none;
}

```
