### ISSUE TITLE
Heartbeat Autosave confusion

### ISSUE THREAD

**Issue by StaggerLeee** [WordPress/gutenberg#9840]
It is easy for User to think Post is really saved and to close browser. And all edits are gone.
Can you hide it ? Because nothing is saved for real, so why to show it ? Let it do its own thing in the background.

Additional confusion is "Preview" and "View Post" are not the same.

**Comment by tofumatt** [comment]
Autosave is working for me on my test site running the latest `master` of Gutenberg:

![2018-09-12 19 02 08-min](https://user-images.githubusercontent.com/90871/45444262-e9f52a00-b6be-11e8-9807-9d3ca7be1aec.gif)

What are the steps to reproduce the issue you're having?

**Comment by StaggerLeee** [comment]
Hi. 
It is working and all well. Just can be confusing for beginners. Confusing to me when started with Gutenberg.

As I see it you have to click Update/Publish button. So what is purpose of autosave icon in top bar.

When you "save" something in MS Word it is there for all the world (front-end). When autosave kicks in in Gutenberg change is not visible on front-end.

OK, fine and usefull but I am experienced and my first reaction was it really saves edit to be able to see it on front-end. Maybe just wording is strange.

**Comment by tofumatt** [comment]
The autosave icon shows the post (or any changes) being automatically saved as a draft. You'll note in my screenshot I didn't click the publish button and the post appeared as a draft in my list of posts.

I suppose for WordPress the notion of saving is just making sure the content is saved and accessible again in the future, but _published_ is for the world to see.

This is consistent with terminology WordPress has used for some time and has worked well, so I'm going to close this as won't fix.
