### ISSUE TITLE
Gutemberg editor, Error inserting external links, images, theme incompatibility, etc.

### ISSUE THREAD

**Issue by spatecc** [WordPress/gutenberg#9843]
I am trying to use the Gutemberg editor. New post, etc. When I try to insert an external link, it leaves open the "tootltip" empty, and I need to change views to get rid of that tootltip. When I try again the visual editor, the link is missing.

Another problem is when I try to insert a new image: I need to upload image to media library before I can insert it onto the post, instead of just uploading image on the post.

Another: On my theme (Modernize, from ThemeForest) I can define an image as preferred thumbnail for the post, and that option is not present when I use Gutemberg.

I prefer to change to the old reliable editor. Not sure if I can work with Gutemberg for a long time.

**Comment by tofumatt** [comment]
I think the first issue could be related to #9512; sometimes RichText changes are not respected across editor mode changes. This is a known bug. The link tooltip should remain until you have left the link but I understand it's frustrated to have to type more content, select it, and remove the link to continue.

You can upload an image directly in Gutenberg:

![2018-09-12 19 41 35](https://user-images.githubusercontent.com/90871/45446240-49096d80-b6c4-11e8-9023-6a3b1fcd12a7.gif)

That last point about your theme sounds like an issue with the theme offering what sounds like plugin features in the classic editor. You should reach out to your theme developer to let them know they'll need to update their theme to work with Gutenberg. They may want to create a plugin with a "Preferred thumbnail" block for their theme.

Gutenberg is still in beta though we're working hard to fix bugs like this, so thanks for reporting them. Right now I think the main bug here is at #9512 around link text being lost between mode switches. If you're having issues with your existing plugins/themes and Gutenberg, you can use the Classic Editor plugin until they are updated to work with Gutenberg.
