### ISSUE TITLE
Fullscreen close button misleading

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#9856]
Hi,

Testing the Fullscreen feature and it's awesome. The close button on the left side is confusing though, it's redirecting to posts edit page rather than going back to default Gutenberg editor mode. Thanks!

**Comment by Soean** [comment]
See #9838 `Replace the fullscreen "x" icon with a back arrow`

**Comment by Soean** [comment]
The PR is merged, so I think we can close the issue. 
![bildschirmfoto 2018-09-25 um 15 53 32](https://user-images.githubusercontent.com/695201/46018897-371fc580-c0db-11e8-927a-a757e5dca729.png)
