### ISSUE TITLE
Need Help in toolbar controls

### ISSUE THREAD

**Issue by jatind93** [WordPress/gutenberg#9857]
how can i implement Heading toolbar in my Blocks-control or InspectorControls.

**Comment by designsimply** [comment]
Please see the [Block Controls: Toolbars and Inspector](https://wordpress.org/gutenberg/handbook/designers-developers/developers/tutorials/block-tutorial/block-controls-toolbars-and-inspector/) handbook page to see an example of how to customize the toolbar to include controls specific to your block type. If that page does not answer your question completely, please post to https://wordpress.org/support/forum/wp-advanced/ and describe what you're trying to do in a bit more detail and include a code example for what you have tried already if at all possible. Thank you!
