### ISSUE TITLE
Add Image. Add Gallery buttons

### ISSUE THREAD

**Issue by femiyb** [WordPress/gutenberg#9859]
**Is your feature request related to a problem? Please describe.**
So, it's been a few weeks of using Gutenberg, and I didn't understand why there is no ADD Images button, until today when I realised It's actually below the Edit Box

**Describe the solution you'd like**
I think it would be better if the Images button go to the top with all other edit tools as it's easier to find

**Comment by Soean** [comment]
Related to https://github.com/WordPress/gutenberg/pull/9682 and https://github.com/WordPress/gutenberg/issues/8589#issuecomment-416533354

**Comment by mtias** [comment]
The main mechanism for inserting content in to a post is the "inserter" which can be accessed from multiple places:

* Top header the "+" button.
* Next to an empty line with the "+" button.
* Between content blocks with the centered "+" button on hover.
* Typing `/` on a new line.

A few related items in https://github.com/WordPress/gutenberg/issues/10519
