### ISSUE TITLE
Gallery block claiming it has been "modified externally" even when it hasn't

### ISSUE THREAD

**Issue by MoeGamer** [WordPress/gutenberg#9860]
**Describe the bug**
A Gallery block can be inserted normally, but on reloading the editor it claims the block has been "modified externally", then offers the option to "convert to blocks" (which loses the images and creates a bulleted list) or "keep as HTML" (which removes the ability to use the Gallery interface to edit the Gallery)

**To Reproduce**
1. Insert a new "Gallery" block.
2. Add images.
3. Save or publish the post.
4. Leave Gutenberg, then reload the same post/page.

**Expected behavior**
The Gallery block should remain as a Gallery block, and should only give a message about being modified externally if it has actually been modified externally.

**Screenshots**
![image](https://user-images.githubusercontent.com/43234760/45477721-15692a80-b73a-11e8-917d-b32fea9213a4.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser: Chrome
 - Version: 69.0.3497.81

**Additional context**
- Using the preview version of Gutenberg available through the wp-admin Dashboard on WordPress.com.

**Comment by Soean** [comment]
I can reproduce this error on wordpress.com but not with mit current Gutenberg Test installations.

**Comment by youknowriad** [comment]
It looks like the `data-*` attributes on the gallery markup are stripped on save in WP.com

**Comment by notnownikki** [comment]
Looks like a couple of new kses rules are needed to allow these attributes. Looking at it now.

**Comment by Soean** [comment]
How should we handle this WP.com specific tickets? 
Is there a repository or a Bug tracker? Or should we add a label?

**Comment by youknowriad** [comment]
@notnownikki do you know if there's a repository we should direct people to if it's only a WP.com bug?

**Comment by notnownikki** [comment]
@youknowriad I don't think there is one since we got rid of the fork. Perhaps we should have them here and tag them as 'wpcom', because this is actually a core bug too, and I don't want people to bounce around projects trying to find where the bug actually belongs. Also, it might highlight where we're making assumptions about environment, and allow us to make things more adaptable?

**Comment by youknowriad** [comment]
Agreed if it's a core issue and we should probably reopen in that case. But maybe more specific issues should be redirected elsewhere, could be addressed later since this one is Core.
