### ISSUE TITLE
Invalid block message could show more details

### ISSUE THREAD

**Issue by johngodley** [WordPress/gutenberg#9863]
When an invalid block is triggered you are shown this message:

![edit_post_ _wordpress_latest_ _wordpress](https://user-images.githubusercontent.com/1277682/45479503-932f3500-b73e-11e8-8cd2-5db077eca1d8.jpg)

For an unfamiliar user it's not immediately clear what this means, why they should care, and what they should do.

Space is fairly tight in the warning so it may be helpful to show more details, either in a tooltip or elsewhere.

See #9667 for details

**Comment by draganescu** [comment]
This appears to have been closed by #9667
