### ISSUE TITLE
wordpress gutenberg validation error on save function

### ISSUE THREAD

**Issue by derridHeidegger** [WordPress/gutenberg#9865]
so i am playing with wordpress gutenberg block dev. and already made some simple one. now i am trying to make a more complicated one of a slider.
everything works untill the save function where i get validation error and a bizzare notice about EndTag which i do not get.
this is my save function , for now i am just trying to save the slides titles. if i console log within the map, i do get what i want.
`	save: function( props ) {
    const { slides } = props.attributes; 
    const id = props.attributes.id;
    
    const displaySlides = slides.map((slide) => {
      return (
        <div>
          <span>{slide.title}</span>
        </div>
      )
    });

    return (
      <div>
        {displaySlides}
      </div>
    )
  },`

and here is the error i get in my dev tools:
![validation-error-slider-last](https://user-images.githubusercontent.com/1025218/45482177-f8425500-b755-11e8-8bf2-e32924f1acc8.png)

as you can see i do get the titles but still a validation error. so what am i missing here?

**Comment by aduth** [comment]
In order for the attributes to become known again the next time you edit the post, you must define an `attributes` definition for your block which instructs Gutenberg on where to find attribute values.

https://wordpress.org/gutenberg/handbook/blocks/introducing-attributes-and-editable-fields/
https://wordpress.org/gutenberg/handbook/block-api/attributes/

If this still does not work for you, can you share more of your block's code?

**Comment by aduth** [comment]
I am going to preemptively close this issue as being addressed via attributes definition. If continued help is needed or a bug is discovered, we can reopen.

**Comment by derridHeidegger** [comment]
hey
thanks for the answer. if i understood what you mean, i do have attributes definition:
`	attributes: {
    slides: {
      type: "array",
      source: "query",
      default: [],
      selector: "blockquote.slide",
      query: {
        image: {
          source: "attribute",
          selector: "img",
          attribute: "src"
        },
        index: {
          type: "string",
          source: "text",
          selector: "span.slide-index"
        },
        content: {
          type: "string",
          source: "text",
          selector: "span.slide-text"
        },
        title: {
          type: "string",
          source: "text",
          selector: ".slide-title span"
        }
      }
    },
    id: {
      type: "string",
      source: "attribute",
      selector: ".carousel.slide",
      attribute: "id"
    }
  },`

can you explain what and how to do: "you must define an attributes definition for your block which instructs Gutenberg on where to find attribute values." ?

**Comment by aduth** [comment]
Reformatted for clarity:

```json
{
  "attributes": {
    "slides": {
      "type": "array",
      "source": "query",
      "default": [],
      "selector": "blockquote.slide",
      "query": {
        "image": {
          "source": "attribute",
          "selector": "img",
          "attribute": "src"
        },
        "index": {
          "type": "string",
          "source": "text",
          "selector": "span.slide-index"
        },
        "content": {
          "type": "string",
          "source": "text",
          "selector": "span.slide-text"
        },
        "title": {
          "type": "string",
          "source": "text",
          "selector": ".slide-title span"
        }
      }
    },
    "id": {
      "type": "string",
      "source": "attribute",
      "selector": ".carousel.slide",
      "attribute": "id"
    }
  }
}
```

Your `selector` is looking for a `blockquote` element which does not exist in your `save` markup. The `save` output should complement the `attributes` definition, since the definition is what Gutenberg uses to restore those attribute values the next time the editor is loaded.

See also: https://github.com/WordPress/gutenberg/blob/master/packages/editor/README.md#how-it-works
