### ISSUE TITLE
Miss not being able to justify captions right, center, or left.

### ISSUE THREAD

**Issue by andrewdreszer** [WordPress/gutenberg#9870]
Gutenberg only allows photo captions to be centered.  Miss not being able to justify captions right, center, or left.  Have seen one work around that requires coding each time.  Havn't tried to see if works, but just seems to be too much effort for what should be a simple text editor function.

**Comment by designsimply** [comment]
I found this was asked in #8901 with `[Status] Won't Fix` applied. 

I am adding the `Needs Design Feedback` tag to see if we can get a designer perspective on whether to consider adding this as a feature or try to get an explanation of why it should not be added if there is a reason.

Thanks for asking about it.

**Comment by andrewdreszer** [comment]
Thanks for the reply. Glad this photo caption question has been bumped to design. Depending a layout and positioning of photos in that layout being able to left, center, or right justify captions can be an important visual aesthetic. I hope Gutenberg will accommodate this feature. Thank you for its consideration.

Andy Dreszer

On September 13, 2018, at 2:50 PM, Sheri Bigelow <notifications@github.com> wrote:

I found this was asked in #8901 with [Status] Won't Fix applied.

I am adding the Needs Design Feedback tag to see if we can get a designer perspective on whether to consider adding this as a feature or try to get an explanation of why it should not be added if there is a reason.

Thanks for asking about it.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/WordPress/gutenberg","title":"WordPress/gutenberg","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/WordPress/gutenberg">https://github.com/WordPress/gutenberg</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@designsimply in #9870: I found this was asked in #8901 with `[Status] Won't Fix` applied. \r\n\r\nI am adding the `Needs Design Feedback` tag to see if we can get a designer perspective on whether to consider adding this as a feature or try to get an explanation of why it should not be added if there is a reason.\r\n\r\nThanks for asking about it."}],"action":{"name":"View Issue","url":"<a href="https://github.com/WordPress/gutenberg/issues/9870#issuecomment-421112948">https://github.com/WordPress/gutenberg/issues/9870#issuecomment-421112948</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/WordPress/gutenberg/issues/9870#issuecomment-421112948">https://github.com/WordPress/gutenberg/issues/9870#issuecomment-421112948</a>", "url": "<a href="https://github.com/WordPress/gutenberg/issues/9870#issuecomment-421112948">https://github.com/WordPress/gutenberg/issues/9870#issuecomment-421112948</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [WordPress/gutenberg] Miss not being able to justify captions right, center, or left. (#9870)", "sections": [ { "text": "", "activityTitle": "**Sheri Bigelow**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@designsimply", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"WordPress/gutenberg\",\n\"issueId\": 9870,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close issue", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"WordPress/gutenberg\",\n\"issueId\": 9870\n}" }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/WordPress/gutenberg/issues/9870#issuecomment-421112948">https://github.com/WordPress/gutenberg/issues/9870#issuecomment-421112948</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 379418760\n}" } ], "themeColor": "26292E" } ]

**Comment by karmatosed** [comment]
I think for now let's not have this on captions. A theme could style this and it adds a layer of complexity that could be a little much for some users.

**Comment by andrewdreszer** [comment]
Not only can you not justify captions but caption text don't and color are both changed. I have spent hours at looking at work around with no luck this far. Deactivating Gutenberg also does not work. Gutenberg has a permanent affect on caption text. Frustrating.

On October 11, 2018, at 4:54 PM, Tammie Lister <notifications@github.com> wrote:

I think for now let's not have this on captions. A theme could style this and it adds a layer of complexity that could be a little much for some users.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/WordPress/gutenberg","title":"WordPress/gutenberg","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/WordPress/gutenberg">https://github.com/WordPress/gutenberg</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@karmatosed in #9870: I think for now let's not have this on captions. A theme could style this and it adds a layer of complexity that could be a little much for some users."}],"action":{"name":"View Issue","url":"<a href="https://github.com/WordPress/gutenberg/issues/9870#issuecomment-429114815">https://github.com/WordPress/gutenberg/issues/9870#issuecomment-429114815</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/WordPress/gutenberg/issues/9870#issuecomment-429114815">https://github.com/WordPress/gutenberg/issues/9870#issuecomment-429114815</a>", "url": "<a href="https://github.com/WordPress/gutenberg/issues/9870#issuecomment-429114815">https://github.com/WordPress/gutenberg/issues/9870#issuecomment-429114815</a>", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [WordPress/gutenberg] Miss not being able to justify captions right, center, or left. (#9870)", "sections": [ { "text": "", "activityTitle": "**Tammie Lister**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@karmatosed", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"WordPress/gutenberg\",\n\"issueId\": 9870,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/WordPress/gutenberg/issues/9870#issuecomment-429114815">https://github.com/WordPress/gutenberg/issues/9870#issuecomment-429114815</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 379418760\n}" } ], "themeColor": "26292E" } ]
