### ISSUE TITLE
Add fixed block template option

### ISSUE THREAD

**Issue by eshannon3** [WordPress/gutenberg#9871]
**Is your feature request related to a problem? Please describe.**
Use case: faculty bio CPTs have several required components, so a block template is helpful in setting up the blocks that are required. However, they also often have additional information after the required content which varies in content and format.

**Describe the solution you'd like**
I envision a `fixed` option for `template_lock` which allows theme and plugin developers to set up a block template in which the template itself cannot be changed - no deleting of the required blocks, no additions before or between the required blocks, no moving the required blocks; but the writer can add, edit, and delete blocks after (beneath) the templated blocks.

**Describe alternatives you've considered**
We currently handle this with ACF but it would be so much nicer to handle in Core.

**Comment by youknowriad** [comment]
I have something similar already in [GCF](https://github.com/youknowriad/gcf) (based on Gutenberg APIs by creating a container block where you can add/remove blocks, this container is not locked but it's used in a parent template that's locked which means you can do what you want inside the container but outside you can't touch the remaining blocks.

So, I'd say this is already possible in Gutenberg

**Comment by ihdk** [comment]
Hi, I don't think the GFC provides exactly the solution described by Elaine, I am looking for the same way of template use.
What I want to achieve is template with blocks on the page. Blocks from template cannot be moved and cannot be deleted, **but user can add more blocks beneath the template**. It means the blocks in template are kind of "must use blocks" which user cannot delete or move, but he can still add new blocks beneath blocks from template.

Currently we have two ways of `template_lock` use:
`all` -  prevents all operations. It is not possible to insert new blocks, move existing blocks, or delete blocks.
`insert` - prevents inserting or removing blocks, but allows moving existing blocks.

Third solution could be the way to disallow user move or remove blocks in template, but allow user add more blocks beneath the blocks from template.

Thanks for any feedback:)

**Comment by youknowriad** [comment]
> It means the blocks in template are kind of "must use blocks" which user cannot delete or move, but he can still add new blocks beneath blocks from template.

@ihdk You can do that by using a special container block using `InnerBlocks` where you add all the "must used blocks"' and you specify to `templateLock` prop for `InnerBlocks` as `all`.

GCF does this the other way around, you'd lock the whole template but inside the template you add a container `free HTML area` where  people can insert/remove/move blocks (inside the container, the container itself and its siblings are locked).

**Comment by youknowriad** [comment]
I'm going to close. Let me know if it works for you.

**Comment by youknowriad** [comment]
> Is something like this possible?

No that's not possible at the moment. The difficulty here is that if you allow people to insert block and remove them, you should be able to move them at the template level and we can't lock a specific block. I think some of these things will come at a later point (phase2) as you'd be able to assign a fixed template for the whole page (and not only its content) while the post-content becomes just another block.

**Comment by ihdk** [comment]
Thanks for lightspeed answer. Glad to hear that something like this may be considered in further releases.
Anyway, in my solution the template for page (template is custom block with inner blocks) would not be available in the inserter and user would not be able to delete this block (template), so there would not be present problem with added or deleted "fixed block (template)". Template would stay in place all the time, without ability to be deleted or moved by user. Just after template would start custom users content with blocks added by him.

Thank you, Ivan.
