### ISSUE TITLE
WP post expire

### ISSUE THREAD

**Issue by Etje1971** [WordPress/gutenberg#9874]
**Describe the bug**
Wordpress plugin 'WP post expire' doesn't work in the new Gutenberg layout.

**Screenshots**
![image](https://user-images.githubusercontent.com/43244288/45497112-4d429300-b777-11e8-82d3-804cf3543166.png)

![image](https://user-images.githubusercontent.com/43244288/45497193-7cf19b00-b777-11e8-93ec-76b4bca43ea5.png)

**Comment by Soean** [comment]
Hey @Etje1971 
thanks for your report. Can you contact the author of the plugin? The Publish meta box is now implemented via JavaScript, so the author has to change the code of the plugin.
