### ISSUE TITLE
Unable to Change Text Colours of Lists

### ISSUE THREAD

**Issue by torres126** [WordPress/gutenberg#9879]
**Describe the bug**
When creating a list, there is no option to change the font colours of the text. I'm not certain if this is intentional or not, but since it has been available in every other editor, I am under the assumption that it is unintentional.

**To Reproduce**
1. Write a post
2. Add the "Lists" block
3. Try and change colour of a bullet point

**Expected behavior**
Based on previous editors, I would assume that most people (including myself) would be under the assumption the "Color Settings" which appear for paragraphs would appear for lists too.

**Screenshots**
See here: https://clubpenguinmountains.files.wordpress.com/2018/09/gfdssdgfdfgsdfgsdgf.png

**Desktop (please complete the following information):**
 - Mac 10.6.8
 - Chrome
 - Version 44

**Additional context**
- Using the version of Gutenberg rolled out on WordPress.com.

**Comment by designsimply** [comment]
This has been requested at #9016, and I would like to close this as a duplicate and refer to the discussion there.
