### ISSUE TITLE
Gracefully handle JS errors from plugin and browser extension conflicts

### ISSUE THREAD

**Issue by iandunn** [WordPress/gutenberg#9882]
I'm seeing a lot of reports on the w.org forums about critical errors, like autosaves not working, the interface not loading, etc. Several people have reported losing entire posts and hours of work.

It's hard to get good debugging information, but I'm guessing that they're mostly caused by conflicts with WP plugins they have installed, or browser extensions they're using.

I know we can't control what external code does, but I worry that these types of errors will be much more common in a JS-heavy app than they are in the PHP-based world that people are used to. If that happens, users will have a very poor experience, and likely blame Gutenberg.

Are there any things we can do to gracefully handle these kinds of problems? Maybe wrapping all WP JS execution in a `try...catch` block, to prevent an error in another script from breaking everything else? That might have unintended side-effects, though.

Maybe before the merge, we could add a button a user could click to automatically send in a bug report (with detailed debugging info).

Here's some examples after only spending about 6 hours in the forums this week:
* https://wordpress.org/support/topic/blank-editing-page-for-post-appears-in-classic/
* https://wordpress.org/support/topic/gutenburg-doesnt-really-function-properly/
* https://wordpress.org/support/topic/revisions-not-saved/
* https://wordpress.org/support/topic/the-editor-has-found-an-unexpected-error-what-i-can-do/
* https://wordpress.org/support/topic/updating-failed/

**Comment by iandunn** [comment]
Some more examples I noticed today:

* https://wordpress.org/support/topic/gutenberg-issue-with-editoring-old-post/
* https://wordpress.org/support/topic/white-screen-of-death-when-opening-or-creating-a-page-using-gutenberg-editor/
* https://wordpress.org/support/topic/nvariant-violation-minified-react-error-130/ (permalink flush worked for some people but not others)
* https://wordpress.org/support/topic/after-updating-3-8-cant-write-new-posts/
* https://wordpress.org/support/topic/cant-add-a-featured-image/ (not sure if it's related, but seems likely)
* https://wordpress.org/support/topic/after-the-newest-update-i-cant-edit-any-posts-anymore/

**Comment by youknowriad** [comment]
We have some global error boundaries detection but agreed, we should improve the JS errors.
We also have this issue to track this #8637 so I'm closing as duplicate.
