### ISSUE TITLE
Tag - drop down or other list

### ISSUE THREAD

**Issue by st00p** [WordPress/gutenberg#9890]
**Is your feature request related to a problem? Please describe.**
I work with a lot of tags, so it's easy to forget about existing tags that might be relevant. At the moment have to open up a separate window to see my full list and use the relevant ones.

**Describe the solution you'd like**
I'd love to see some sort of drop-down or list (as for categories) so that I can see all my tags easily and select the relevant ones

**Describe alternatives you've considered**
None.

I'm really enjoying Gutenberg - thanks to anyone who reads this.

**Comment by karmatosed** [comment]
For now, let's stick with the UI we have. This could be added as an improvement but right now I feel we should stick with parity of the existing editor. Now one thing we could add back in is the 'pick from existing tags' link, but for now let's close this and consider if we iterate.
