### ISSUE TITLE
Better support for localized fonts

### ISSUE THREAD

**Issue by naokomc** [WordPress/gutenberg#9891]
Currently, Gutenberg has an option to turn on or off Noto Sans Serif font.
https://github.com/WordPress/gutenberg/blob/master/lib/client-assets.php#L641

However, Google Fonts now offers [Noto Sans JP](https://fonts.google.com/specimen/Noto+Serif+JP) and [Noto Serif JP](https://fonts.google.com/specimen/Noto+Sans+JP), one of which would be a better choice for Japanese text.

The ideal solution:

- For `ja` sites, load `Noto Sans JP` or `Noto Serif JP` instead of `Noto Serif`
- Only load 400 & 700 varieties - Noto Sans|Serif JP doesn't have italics option

Ref: Twenty Seventeen's font support improvemet
https://github.com/WordPress/twentyseventeen/issues/59

I'd like to hear from these locale users (I took the list from the above ticket) about which font choice is the best for them. Google Fonts alternative or any other fonts?

For Japanese,  we'll need to do some test on Windows/iOS/Android with Noto Sans|Serif JP fonts to decide which one looks better.

- [ ] Cyrillic
- [ ] Greek
- [ ] Hebrew
- [ ] Arabic
- [ ] Vietnamese
- [ ] Thai
- [ ] Japanese
- [ ] Korean (can probably use the same solution as JP with Noto Sans|Serif KR)
- [ ] Chinese
- [ ] Devanagari
- [ ] Gujarati

Related: #6099

cc: @mayukojpn @nukaga @ixkaito

**Comment by ckxpress** [comment]
that would be cool Noto Sans also supports Korean and Chinese

**Comment by fierevere** [comment]
there are no problems with **Cyrillic** Noto fonts , Windows/Linux/Android is fine. I cant say for iOS, because i dont own any device, but on mentioned platforms its good default font of choice.

**Comment by mayukojpn** [comment]
@naokomc @nukaga @ixkaito
I created bookmarklets for applying Noto fonts on browsers. Do you have any suggestion for place of I post it and ask designers to test?
https://gist.github.com/mayukojpn/77b113bd05d39974c33c4c2aa11cd570

**Comment by mkaz** [comment]
I welcome feedback on my approach in #11826 - it was easiest to code it up to explain the idea best, I'm open to alternates. I'm also assuming we want to leave the control in the hands of the translators.

So the solution adds additional fields to specify which font to load from Google, and a field to specify the font-family loaded, since it might be different. 

For example the Google font to load would be `Noto Sans JP:400,700` and the default CSS font-family would be `Noto Sans JP`

**Comment by naokomc** [comment]
I think this solution works for this purpose, and I like that translator will be able to specify the font.

For languages with no Noto family option (e.g. Arabic, Hebrew) but other Google font alternatives, should we allow them to chose the one they like? If so, the comment " Translators: Use this to specify the proper Noto font family that is supported by your language" might need to be changed slightly.

**Comment by mtias** [comment]
Margin this as "in progress".

**Comment by danstramer** [comment]
Has this progressed? For Hebrew, the currently displayed font "out of the box" is a bad looking Serif font

**Comment by mkaz** [comment]
@danstramer The ability to switch the font based on a locale translation is in place, it was deployed in #11826 - this still requires each locale to translate and supply a different font that looks best for that language. 

Is there a specific language that isn't looking good, or just a general dislike of the Serif font?

**Comment by danstramer** [comment]
Hi @mkaz , thanks for reaching back.
Google has the Noto project which they have localized their font for 100's of languages.
https://www.google.com/get/noto/
So that could be an option, to localize for hebrew, or using one of the other google fonts with hebrew/english support like; 'Asisstant' or 'Heebo'
Or just default to 'arial' or system font stack (which won't load any external resources):
https://woorkup.com/system-font/;
font-family: -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif
Thanks

**Comment by mkaz** [comment]
The default editor font is `Noto Serif` exactly for the reason of major languages support. However, some languages work better in the Noto Sans font, and hopeful the translations get updated to use those. @naokomc and the Internationization team might be able to respond to those efforts.

Themes also have the ability to override the editor font, ideally to match the front-end being displayed. For example, you can see this using the Twenty Nineteen theme.

**Comment by danstramer** [comment]
Noto Serif is not a good option for Hebrew. 'Noto Sans Hebrew' would be a better font if going down the Noto font path.
Till now, I've been changing the editor's font via a childsheet css, but going forward I think that out of the box Gutenberg should support and display a modern looking font for Hebrew.
How can I help with that?

**Comment by naokomc** [comment]
@danstramer - Hebrew GTE @yoavf took a look and updated [this](https://translate.wordpress.org/projects/wp/dev/admin/he/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6929627&filters%5Btranslation_id%5D=59787049) and [this](https://translate.wordpress.org/projects/wp/dev/he/default?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6929622&filters%5Btranslation_id%5D=59787009) to make the font choices more suitable for the language.

**Comment by danstramer** [comment]
excellent! Thank you @naokomc , has this been merged already?

**Comment by naokomc** [comment]
@danstramer the change will be delivered through the language pack of WordPress core. The most current package is already up-to-date, so if you want to see it on your site please update the translations from your dashboard.
