### ISSUE TITLE
Option to disable default styles to allow AMP compatible theme implementation (solved by changing wp_deregister_style('wp-block-library'); to wp_deregister_style('wp-core-blocks');)

### ISSUE THREAD

**Issue by p2er** [WordPress/gutenberg#9896]
**Is your feature request related to a problem? Please describe.**
I'm trying to build a page with custom theme and amp plugin in combination with Gutenberg. The custom style is so big that there is almost no file size left to fill with the custom theme, because many default styles have to be overwritten.

**Describe the solution you'd like**
Disable Gutenberg default styling in order to create custom block styling in theme. Best option would be to provide a button in the plugin configuration to prevent plugin from adding it's own styling to head. 

**Describe alternatives you've considered**
I've removed the styles in my functions.php during theme setup with:
```
// Remove gutenberg styles to save space for 50kb amp limit
wp_deregister_style('wp-block-library');
```
Does no longer seem to work. Broken as soon as naming is changed by gutenberg implementation.

**Comment by p2er** [comment]
This will work for now, but also points out the problem of using plugin internal names in my custom theme without control over you guys changing it:
```
wp_deregister_style('wp-core-blocks');
```

**Comment by designsimply** [comment]
Thanks for posting the solution you found!

**Comment by aduth** [comment]
Related: #8287
