### ISSUE TITLE
Extending blocks PHP API

### ISSUE THREAD

**Issue by nk-o** [WordPress/gutenberg#9901]
Currently, we have an API for extending blocks using JS. It is ok. But we also need API on the backend to extend dynamic blocks.

For example, I have the plugin, that extends all core blocks and adds custom attribute and class in output using this filter `blocks.getSaveContent.extraProps`. Everything works fine with static blocks, but not with dynamic (for ex. _Latest Posts_ block).

```javascript
function addSaveProps( extraProps ) {
    extraProps.className = ( extraProps.className || '' ) + ' test-class';
    extraProps['data-test-attribure'] = 'test-attribute';
    return extraProps;
}

addFilter( 'blocks.getSaveContent.extraProps', 'test/extra-props', addSaveProps );
```

Tried to change `attributes` argument in `blocks.getSaveElement` filter, but also no luck.

Plus my plugin adds additional attributes to the blocks using filter `blocks.registerBlockType`:

```javascript
function addAttribute( blockSettings ) {

    blockSettings.attributes.testAdditionalClass = {
        type: 'string',
        default: '',
    };

    return blockSettings;
}
addFilter( 'blocks.registerBlockType', 'test/additional-attributes', addAttribute );
```

p.s. all code example simplified just for demonstration. Full extensions code here - https://github.com/nk-o/ghostkit/blob/master/src/blocks/_extend/styles.jsx#L138-L9999

**Comment by mtias** [comment]
#8352

**Comment by mtias** [comment]
Consolidating with #6494.
