### ISSUE TITLE
fontSizes now not working on FontSizePicker

### ISSUE THREAD

**Issue by phpbits** [WordPress/gutenberg#9917]
Hi,

https://wordpress.org/gutenberg/handbook/components/font-size-picker/ the custom fontSizes is working before the latest update. But now it's getting the default fontSizes stored here : https://github.com/WordPress/gutenberg/blob/c5573b7aadf943367321afeac3c2f02a318c7f00/packages/editor/src/store/defaults.js . Thanks!

**Comment by jorgefilipecosta** [comment]
Hi @phpbits, I'm not being able to replicate the problem you are describing. The FontSizePicker seems to use the font sizes passed to it.
I used the following test code:
```
		const fontSizes = [
			{ shortName: 'S', size: 12 },
			{ shortName: 'M', size: 16 },
		];
		const fallbackFontSize = 16;
...
				<FontSizePicker
					fontSizes={ fontSizes }
					value={ 16 }
					fallbackFontSize={ fallbackFontSize }
					onChange={ console.log }
        		/>
```

Could you please check if you are using the FontSizePicker imported from '@wordpress/components';(wp.components) and not the one from '@wordpress/editor';(wp.editor)?

I also checked that themes can overwrite the default font sizes used by wp.editor.FontSizePicker version using the following code:
```
add_theme_support( 'editor-font-sizes', array(
	array(
		'name' => __( 'extra small', 'themeLangDomain' ),
		'shortName' => __( 'XS', 'themeLangDomain' ),
		'size' => 11,
		'slug' => 'small'
	),
	array(
		'name' => __( 'regular', 'themeLangDomain' ),
		'shortName' => __( 'M', 'themeLangDomain' ),
		'size' => 16,
		'slug' => 'regular'
	),
	array(
		'name' => __( 'large', 'themeLangDomain' ),
		'shortName' => __( 'L', 'themeLangDomain' ),
		'size' => 36,
		'slug' => 'large'
	),
	array(
		'name' => __( 'larger', 'themeLangDomain' ),
		'shortName' => __( 'XL', 'themeLangDomain' ),
		'size' => 50,
		'slug' => 'larger'
	)
) );
```

**Comment by jorgefilipecosta** [comment]
Closing this for now, feel free to reopen if my @phpbits did not clarify the situation.

**Comment by phpbits** [comment]
@jorgefilipecosta Thanks! Using `wp.components` fixes the issue ;)
