### ISSUE TITLE
Reusable Blocks: "Export as JSON" link does not work in Firefox

### ISSUE THREAD

**Issue by designsimply** [WordPress/gutenberg#9919]
Steps to reproduce:

1. Install Gutenberg [3.9.0-rc.1](https://github.com/WordPress/gutenberg/releases/tag/v3.9.0-rc.1).
1. Open Firefox and to to your site's WP Admin.
1. Go to Posts > Add New.
1. Add a reusable block so at least one exists (otherwise I don't see a way to reach the Blocks page at `wp-admin/edit.php?post_type=wp_block`).
1. Click the block inserter (+).
1. Click the gear icon at the bottom right of the Reusable panel in the block library.
1. Hover over any block in the list and click the "Export as JSON" link that appears.

<strong>Result:</strong> the "Export as JSON" link seems to generate a JSON file via an API call (I can see it in the Network tab) but does not result in a downloaded file when using Firefox 62.0 on macOS 10.13.6.

![screen shot 2018-09-14 at 11 34 41 am](https://user-images.githubusercontent.com/1119271/45566467-f8a12580-b813-11e8-93a0-221e658139b0.png)
<sup>Seen at https://madefortesting.com/wp-admin/edit.php?post_type=wp_block running WordPress 4.9.8 and Gutenberg 3.9.0-rc.1 using Firefox 62.0 on macOS 10.13.6.</sup>

Question: what are the intended steps to import a reusable block JSON file on a site which does not yet have any reusable blocks?

Aside: this is what I see when I click on the title of a reusable block on the Blocks page at `wp-admin/edit.php?post_type=wp_block`. Is this the expected view? Should the title and content of a reusable block be editable here? Should I be able to change post status, visibility, and publication date/time for reusable blocks?

![screen shot 2018-09-14 at 11 27 39 am](https://user-images.githubusercontent.com/1119271/45566482-035bba80-b814-11e8-9e0c-bc2b66f5d079.png)
<sup>Seen at https://madefortesting.com/wp-admin/post.php?post=538&action=edit running WordPress 4.9.8 and Gutenberg 3.9.0-rc.1 using Firefox 62.0 on macOS 10.13.6.</sup>

**Comment by tofumatt** [comment]
I know this process is all new, so there's no guideline 😄

Any issues with a release candidate should be added to the (still open) `3.9` milestone. I added this one, but it's better to add them there than but it in the title. Any RC bug/regression is likely high priority though, feel free to use that label 😄

**Comment by designsimply** [comment]
Noting that the question about the single-item editing experience was opened as a separate issue at #9964.

**Comment by furyuri** [comment]
I'm having trouble getting export as JSON to work at all on localhost/XAMPP - I keep getting this error in the console:
`index.js?ver=1567441560:1 Uncaught (in promise) {code: "invalid_json", message: "The response is not a valid JSON response."}`
