### ISSUE TITLE
Embeds: Vertical scrollbar on embeds (Demo Vimeo block)

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#9920]
Regression introduced in #9853

**Describe the bug**

A vertical scrollbar appears on the embed block, seen in the demo content Vimeo block.

**To Reproduce**

1. (Prerequisite) In macOS, [ensure scrollbars are always visible](https://cloudup.com/cqF641QROEe) in System Settings. I'd recommend to any developer to always keep this option.
2. Navigate to Gutenberg > Demo
3. Scroll to the Vimeo "The Mountain" video block
4. Observe unnecessary vertical scrollbar

**Expected behavior**

No unnecessary vertical scrollbar.

**Screenshots**

![image](https://user-images.githubusercontent.com/1779930/45569438-86d5d580-b82d-11e8-876a-fb6f7464d3dd.png)

**Browser:**

Chrome Version 69.0.3497.92 (Official Build) (64-bit)
macOS High Sierra 10.13.6 (17G65)

**Comment by jasmussen** [comment]
Hi friends, I tried to push a fix in https://github.com/WordPress/gutenberg/pull/10022.
