### ISSUE TITLE
Change single post link

### ISSUE THREAD

**Issue by HassaN0152** [WordPress/gutenberg#9928]
I used to use this plugin for a while, I realized that to change the link's address, I'd definitely need to save the post so I can change the posting link. If I do not save the post, I'll go into the settings for the unique link when I click on the change link.
Translate by Google

**Comment by arunsathiya** [comment]
In my understanding, you are trying to change the slug for a post. You can do this for a saved post, or on one that is published. One cannot change a slug for a post that is neither saved nor published at the moment. 

This is possible on the classic editor though.

The screenshots below show how you can change the slug after saving a draft/publishing on Gutenberg.

<img width="678" alt="screen shot 2018-09-15 at 19 40 42" src="https://user-images.githubusercontent.com/18581859/45587241-e365ed00-b920-11e8-9a33-35e3ce3f690c.png">
<img width="686" alt="screen shot 2018-09-15 at 19 40 50" src="https://user-images.githubusercontent.com/18581859/45587242-e3fe8380-b920-11e8-95c6-c6416175db27.png">

Are you hoping to see the option to change slug before saving/publishing a post? 

Related thread you might be interested in: https://github.com/WordPress/gutenberg/issues/8949 (positioning of the slug on the Gutenberg editor)

**Comment by HassaN0152** [comment]
> In my understanding, you are trying to change the slug for a post. You can do this for a saved post, or on one that is published. One cannot change a slug for a post that is neither saved nor published at the moment.
> 
> This is possible on the classic editor though.
> 
> The screenshots below show how you can change the slug after saving a draft/publishing on Gutenberg.
> 
> <img alt="screen shot 2018-09-15 at 19 40 42" width="678" src="https://user-images.githubusercontent.com/18581859/45587241-e365ed00-b920-11e8-9a33-35e3ce3f690c.png">
> 
> <img alt="screen shot 2018-09-15 at 19 40 50" width="686" src="https://user-images.githubusercontent.com/18581859/45587242-e3fe8380-b920-11e8-95c6-c6416175db27.png">
> 
> Are you hoping to see the option to change slug before saving/publishing a post?
> 
> Related thread you might be interested in: #8949 (positioning of the slug on the Gutenberg editor)

But do not you think this is a bug?
The content is ready to be published, but since I can not change the link, I have to save it, then link and change. The link can be changed in the classic editor.
It saves time.
Translate by Google

**Comment by arunsathiya** [comment]
I'm not sure if this is intended. If you believe this is a bug, consider reopening this issue, and updating the title of this issue, so that this is addressed by anyone involved.
