### ISSUE TITLE
className saved but not loaded on F5 (reload)

### ISSUE THREAD

**Issue by manake** [WordPress/gutenberg#9929]
## Step 1
Create a custom block:

```
function x() {
	wp_register_script( 'x-script', plugins_url( 'editor.js', __FILE__ ), array( 'wp-blocks', 'wp-element', 'wp-i18n', 'wp-editor' ) );

	register_block_type( 'x/y', array(
		'editor_script' => 'x-script',
	) );
}
add_action( 'init', 'x' );
```

```
(function(){
	var el = wp.element.createElement;
	var InspectorControls = wp.editor.InspectorControls;
	var __ = wp.i18n.__;

	wp.blocks.registerBlockType('x/y', {
		title: __('X'),
		icon: 'some-icon',
		category: 'layout',
		attributes: {
			x: { type: 'string', default: 'on' },
		},
		edit: function(props){
			var attributes = props.attributes;
			var isSelected = props.isSelected;
			var setAttributes = props.setAttributes;

			var inspectorControls = isSelected && el(
				InspectorControls,
				{ key: 'inspector' },
				el(wp.components.SelectControl, {
					multiple: false,
					label: __('X'),
					value: attributes.x || '',
					onChange: function onChange(value) {
						return setAttributes({ x: value });
					},
					options: [
						{ value: 'on', label: 'On' },
						{ value: 'off', label: 'Off' },
					],
				}),
			);

			return [inspectorControls, (
				el( 'div',
					{
						className: props.className,
						style: {
							'color': 'red',
						}
					},
					'Text'
				)
			)];
		},
		save: function(props){
			return null;
		},
	});
})();
```

## Step 2:
Create another custom block with only this difference:
```
save: function(props){
	return el('span');
},
```

## Step 3:
Add these two blocks to a page and add a CSS class to both. E.g. `some-class`.

## Step 4:
Publish the page.
Both classes are saved (correct)!

## Step 5:
Hit F5.

## Step 6:
`className` is not loaded automatically back into the input for the second block (incorrect)!
<img src="https://i.imgur.com/lbJxeOv.jpg">

Gutenberg 3.8.0.

I reported this already. This is not resolved and has been ignored #9423.

# This is a bug.

`className` is saved in both but it's not loaded in one after hitting F5 (reload).

If this is intended (I don't see why such strange/inconsistent behavior should be intended though) then it's not documented in what circumstances `className` is not going to be loaded automatically back into the right field: https://wordpress.org/gutenberg/handbook/extensibility/extending-blocks/

**Comment by Soean** [comment]
Hey @manake 
thanks for reporting this issue. 
I can reproduce the behavior with the build-in dynamic blocks `archives` and `latest-posts`.
