### ISSUE TITLE
Line break in Gutenberg

### ISSUE THREAD

**Issue by StephCii** [WordPress/gutenberg#9930]
Sometimes I want to make a line break without creating a new paragraph (and also a new block in Gutenberg). And when it creates a new block, I would like to be able to join two blocks to avoid this problem. I sometimes want to rearrange a copied text from another editor and Gutenberg break the text in different blocks each time I just want to make a line-break (for example to invert a name, a date and a title of a conference in a program of conferences...). You can imagine how it become a mess in Gutenberg !

Is it possible to create a button and/or a keyboard shortcut to create a line-break `<br />`. And it would be great to be able to join selected blocks (paragraphs, lists...) into one classic block.

**Comment by Soean** [comment]
You can use `Shift + Enter` to just create a line break.

**Comment by StephCii** [comment]
Thank you very much !
You such write this shortcut in the keyboard shortcut list available in Gutenberg.

**Comment by danillolima** [comment]
Shift + Enter doesn't work in lists anymore? or never worked?

**Comment by scottyg7** [comment]
shift + Enter in list blocks is needed.

**Comment by elleryq** [comment]
Please add shift+enter back.

**Comment by TeacherLee** [comment]
For a list, it's a pain but you can switch to "Edit in HTML" mode, enter <br><br> and then return to Visual Mode.

**Comment by danicholls** [comment]
This doesn't work in paragraphs as of right now. It should be reopened.

**Comment by githubeing** [comment]
i confirm that `shift+enter` inside a paragraph creates a new para, not a line break, same as simple enter key 😟
now have to switch to `edit in html`, than enter `<br>`, than switch back to visual mode 😢

**Comment by TeacherLee** [comment]
Gutenberg needs to guten back to the drawing board, I'm afraid.  I'll stick with classic view -- more productive.

**Comment by PayteR** [comment]
This is bug or what? Because i can see in inspector, that `<br data-rich-text-line-break="true">` is created but it's not saved on `<InnerBlocks.Content />`

**Comment by designbydc** [comment]
Hi, this is a current problem! I've tested it right now on visual mode.

Is it possible to fix this bug?
