### ISSUE TITLE
Gutenberg triggers Fail2Ban Wordpress jails in Plesk

### ISSUE THREAD

**Issue by Bitpalast** [WordPress/gutenberg#9933]
**Describe the bug**
The editor frequently triggers the default Fail2Ban Wordpress jails in Plesk as it seems to repeat the same operation within a short period of time over and over again, maybe as an AJAX communication? It frequently seems to save input typed for no reason.

**To Reproduce**
Use the editor.

**Expected behavior**
Do not constantly call the same functions on the server.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox, chrome, but probably others, too

**Comment by youknowriad** [comment]
I don't know if we can do anything about it, autosave is being triggered if there are changes to be saved each "10 seconds" or so (and this delay is tweakable). Did you try to reach out to plesk to see if they're aware of it or have more input there?

**Comment by pento** [comment]
This seems like a thing where Plesk would already have a workaround for exactly the same behaviour in `admin-ajax.php`, they'll need to add one for the REST API, too.

I'm going to close this issue, as it will need a Plesk update to fix it, but please let us know what they get back to you with.
