### ISSUE TITLE
What is the best way to update post meta?

### ISSUE THREAD

**Issue by DonPotato** [WordPress/gutenberg#9934]
What would be the best way in Gutenberg to save/update post meta (not from a block). I can't find an API for it.

I was thinking of doing some ajax in `componentDidMount `using `wp.ajax.post`

Any advice would be much appreciated.

**Comment by youknowriad** [comment]
You can change the `meta` fields of the edited post (if these meta are registered as `show_in_rest => true`) like any other post property using the data module:

```js
const currentMeta = wp.data.select( 'core/editor' ).getEditedPostAttribute( 'meta' );
const newMeta = {
  ...currentMeta,
  keyOfMetaToChange: value
};
wp.data.dispatch( 'core/editor' ).editPost( { meta: newMeta } );
```

**Comment by DOUARA** [comment]
@youknowriad 

why do we need to merge the current meta to the new meta object: 
`const newMeta = {
  ...currentMeta,
  keyOfMetaToChange: value
};`

I found out that this is causing issues on updating posts (failed to update) when other plugins  are registering post meta too 
why not just use it like this: 
`const newMeta = {
  keyOfMetaToChange: value
};`

**Comment by youknowriad** [comment]
Because "meta" is a property that contains all the meta variables and not the one from your plugin, so you shouldn't be overriding it entirely.

That said, I think in the last versions of the plugin we try to be smart and do the merging ourselves.

**Comment by DOUARA** [comment]
I am on the version 5.2.2 of WordPress, I was forced to remove the currentMeta due to a compatibility issue with another plugin (Some REST AUTH error), it seems that there'is no overriding and it works fine
