### ISSUE TITLE
Feedback to gutenberg editor

### ISSUE THREAD

**Issue by digulla** [WordPress/gutenberg#9939]
This is just general feedback for my first time trying to use the gutenberg editor.
My first impression was "meh". 
It seems to waste a lot of screen space (narrow text, huge gaps).
"block" has become a new word for "paragraph". Not sure why that is necessary.
Formatting of source code isn't support (or I couldn't find it).
Preview doesn't work (I get an page with the layout of my blog but the main area just says "Not Found").
So please leave the original editor in, I won't switch to gutenberg. For me, it has no benefit and only additional problems.

**Comment by GlennMartin1** [comment]
I hope you know it's too early to determine if you will like it. It's a developing Beta project. No one considers it finished. 

You said: "It seems to waste a lot of screen space (narrow text, huge gaps)." The editor width is specified by your theme so it can match the front end. This only means you're not using a compatible theme. Contact your theme company to update for Gutenberg. 

Every block offers custom HTML. Just click on the ellipses in the menu bar. You'll see. 

Preview works well for me and thousands of other testers. If you've got an issue with it, file a Bug Report with enough specifics to reproduce the issue.

**Comment by designsimply** [comment]
Thank you for testing Gutenberg!

The idea behind blocks is:

> By embracing “the block”, we can potentially unify multiple different interfaces into one. Instead of learning how to write shortcodes, custom HTML, or paste URLs to embed, you should do with just learning the block, and all the pieces should fall in place.

Source: https://wordpress.org/gutenberg/handbook/

> Preview doesn't work (I get an page with the layout of my blog but the main area just says "Not Found").

Someone else reported a similar-sounding issue recently in #9820 but there is not enough information there. If possible, please consider adding some detail about your experience at #9820. For example, after seeing what you wrote, I wondered whether you have any custom permalink settings.

Regarding the classic editor, it's currently an opt-in but once it is updated in WordPress officially you may keep using the old editor by installing the Classic Editor plugin—and as @GlennMartin1 mentioned, we hope you consider testing Gutenberg again soon!
