### ISSUE TITLE
Image management problems

### ISSUE THREAD

**Issue by fato63** [WordPress/gutenberg#9941]
Lo scrivo prima in italiano, poiche' per me e' piu' facile...
Con il vecchio editor carico le immagini, tipicamente circa 100 immagini 600x600 per articolo, ed esse vengono disposte una sotto l'altra ordinate per nome. In seguito, tra una immagine e l'altra scrivo il testo.
Con Gutemberg non sono riuscito a farlo. Se le carico tutte assieme, le dispone in fila per 3 in ordine sparso. Caricarle una per volta e' impensabile. Ho dovuto abbandonare Gutemberg. Tra l'altro la cancellazione delle immagini non permette di selezionarle tutte ed e' lento nel cancellarle. dopo la cancellazione ripresenta a video le immagini cancellate e si deve fare refresh della pagina piu' volte. Se per sbaglio si richiede di nuovo la cancellazione appare l'errore "Non sei autorizzato a cancellare queste immagini" (o simile).
Now I try in English:
With the old editor I load the images, tipically 100 images 600x600 for every article, and them are arranged one below the other ordered by name. Later, between one image and another I write the text.
With Gutemberg I could not do it. If I load them all together, Gutemberg arrange them in rows for 3 in random order. Loading them one at a time is unthinkable. I had to leave Gutemberg. Among other things, deleting images does not allow you to select them all and is slow to delete them 1 page a time. After deleting, the deleted images are displayed again and the page has to be refreshed several times. If you accidentally request deletion again, the error "You are not authorized to delete these images" (or similar) appears.

**Comment by designsimply** [comment]
Thank you for including a specific example explaining how you work. Your feedback has been noted.

> Later, between one image and another I write the text. With Gutenberg I could not do it.

One thing which may help would be to add several images and then click the "Change block type" option to convert from a gallery to individual images.

![screen shot 2018-09-17 at 12 41 24 pm](https://user-images.githubusercontent.com/1119271/45642961-1de19e00-ba77-11e8-8151-ae8ae2e87ce7.png)
<sup>Seen at http://alittletestblog.com/wp-admin/post.php?post=14967&action=edit running WordPress 4.9.8 and Gutenberg 3.9.0-rc.1 using Firefox 62.0 on macOS 10.13.6.</sup>

This still may not be enough to solve the problem overall in your case, but I hope that it helps and is worth trying it out and letting us know if it was helpful for you or not.
