### ISSUE TITLE
Uncaught Error: only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by marcwiest** [WordPress/gutenberg#9942]
<img width="240" alt="plugins artiade wordpress 2018-09-16 11-18-33" src="https://user-images.githubusercontent.com/815624/45599582-e1dd0900-b9a2-11e8-894c-9d909e7f9a27.png">

Goes away if I disable GB.

## Theme
twentysixteen

## Active Plugins
- Anti-Spambot Email Shortcode | by Robert Peake - 1.1.2
- Force Strong Passwords | by Jason Cosper - 1.8.0
- Gravity Forms Zapier Add-on | by rocketgenius - 3.0
- Gutenberg | by Gutenberg Team - 3.8.0
- Members | by Justin Tadlock - 2.1.0
- NovaFonts | by NovaPlugins - 1.1.0
- Simple Login-Logout Shortcode | by Pronto Tools - 1.1.0
- User Switching | by John Blackbourn & contributors - 1.3.1
- Yoast SEO | by Team Yoast - 8.2

## System
- Chrome (latest)
- Mac OS (latest)

**Comment by youknowriad** [comment]
I believe this is coming from Yoast and I think they're aware of the issue. The idea is that Gutenberg and Yoast both ship with `babel-polyfill` included and I expect more plugins to do so in the future. To avoid breakage like this, we introduce the `wp-polyfill` script you can depend on to avoid duplicating the polyfill across plugins.
