### ISSUE TITLE
Link module fails to show a popup after toggling Unified Toolbar twice

### ISSUE THREAD

**Issue by arunsathiya** [WordPress/gutenberg#9944]
**Describe the bug**: After disabling and enabling `Unified Toolbar` that was launched in [August's final update](https://make.wordpress.org/core/2018/08/31/whats-new-in-gutenberg-31st-august/), when trying to add a link to a text, the popup shows to fail.

**Steps to reproduce**: Follow the steps below to reproduce the issue. 

- Add a text to a paragraph.
- Disable `Unified Toolbar`.
- Enable `Unified Toolbar`.
- Try to add a link, using either the `Link` button on the toolbar, or using the `Cmd+K` keyboard shortcut on Mac (use equivalent keyboard shortcut if you are on Windows)
- Notice that the popup to enter the link fails to appear. 
- Also notice that the word seems to be hyperlinked, with no link.

**Video showing this behavior**: [Link](https://cloudup.com/cwno798W3qR).

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6 
 - Browser: Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) 
 - Version: Gutenberg 3.8.0 

--- 

Tested on a local install of WordPress. WordPress 4.9.8 and Gutenberg 3.8.0 using Google Chrome Version 69.0.3497.92 (Official Build) (64-bit) on macOS 10.13.6

**Comment by designsimply** [comment]
Nice find. Though I've just re-tested with WordPress 4.9.8 and Gutenberg 4.2.0-rc.1 using Firefox 63.0 on macOS 10.13.6 and I am unable to see the problem happen in the current version. ([22s](https://cloudup.com/cXlfUpj4VUS)) Closing for now, but let me know if this problem shows up again!
