### ISSUE TITLE
Changing the year of a publication date is not efficient (too many clicks)

### ISSUE THREAD

**Issue by benoitchantre** [WordPress/gutenberg#9947]
**Describe the bug**
The datepicker only allows us to browse month by month. This works in a standard workflow, but it is not practical when you need to change the value by 2-3 years or more. It happens sometimes when you need to reorganize the content. The Classic editor allows us to do that easily.

Example of use case : your website has a "Press review" page and you decide to reorganize these press reviews as individual posts in a press review category.

Current workaround: use the quick edit panel.

**To Reproduce**
1. Open an existing post or page
2. Click on the publication date
3. Try to change the date 3 years ago
4. Count how many clicks in need

**Expected behavior**
Ability to enter the year manually for a quick change.

Tested in Gutenberg 3.8

**Comment by designsimply** [comment]
Thank you for writing in! This is being worked on as a part of #1311, so I will close this issue as a duplicate and it will be noted there.
