### ISSUE TITLE
Alignment in Tables

### ISSUE THREAD

**Issue by andreasdiehl** [WordPress/gutenberg#9949]
A few questions / remarks about tables:

1. The text seems always to be aligned entered, which is annoying. Is there a way to change that?
2. Column width, is there an option to customise that (eg. expand certain columns manually?

This is a post that includes two tables:
https://digitaleneuordnung.de/blog/jobs-to-be-done/

Maybe I am not aware of styling options, if there are some I' d appreciate a short hint, otherwise I would consider these issues as bugs / feature requests.

**Comment by talldan** [comment]
Hey @andreasdiehl  - there's an open issue here regarding the alignment problem. I think we've identified that we'll need some improvements there - https://github.com/WordPress/gutenberg/issues/9778

For your other issue, there's only the option to toggle 'Fixed width table cells' in the table settings at the moment. I have an open pull request to allow control over the table dimensions here, it needs some further review and design feedback - https://github.com/WordPress/gutenberg/pull/9801.

There's still a number of features to add to the table block, see the umbrella issue here where we're tracking those features - https://github.com/WordPress/gutenberg/issues/6923

**Comment by designsimply** [comment]
Thank you for testing Gutenberg and posting your questions! I am closing this issue since the items you raised are being discussed in other places and you should feel free to continue the discussion here or to follow the issues noted.
