### ISSUE TITLE
Cover image is broken for authors

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#9955]
**Describe the bug**

`kses` does not allow inline styles that have `(` in them. The current implementation of the cover images has `background-image: url(...)` which gets stripped out by `kses` when a non-admin users saves it. When the post is reloaded, the block is broken. The published post does not contain the image.

https://github.com/WordPress/gutenberg/pull/9954 adds tests for `kses` behaviour which showed this.

**To Reproduce**
1. Log in as an author.
2. Add a cover image.
3. Publish the post.
4. View the published post. The image is missing.

**Expected behavior**
The image should appear.

**Comment by aduth** [comment]
This is definitely something which needs to be resolved, but is tracked already at #2539 (although previously confusingly titled as targeting multisite, but it's the same issue).
