### ISSUE TITLE
Is there a reliable way to check if a block can have nested blocks?

### ISSUE THREAD

**Issue by alvaro0555** [WordPress/gutenberg#9956]
Currently the way I found to check if a block has children is:
`wp.data.select("core/editor").getBlock(CLIENTID).innerBlocks > 0`
This works to check if a block has children. The problem is _innerBlocks_ property is added to all blocks, regardless if they can have children. So this approach doesn't work to check if a block can have children.

The only way I found is to check the layout property which is attached to the attributes of the block type, in root blocks:
`wp.data.select("core/editor").getBlockType(BLOCKNAME).attributes.hasOwnProperty("layout")`

It doesn't seem much reliable to me specially as, [if I'm reading correctly](https://github.com/WordPress/gutenberg/pull/7841), layouts might end up disappearing from nested/inner blocks in a future.

Is there an standard way of checking this? Thanks.

**Comment by youknowriad** [comment]
There's no way to check this at the moment AFAIK. Can I ask why do you need this information? 

cc @aduth

**Comment by chrisvanpatten** [comment]
@alvaro0555 Out of curiosity, is there a reason the built-in drag-and-drop functionality isn't enough?

**Comment by aduth** [comment]
There's also the "block list settings" accessible via the [`getBlockListSettings` selector](https://wordpress.org/gutenberg/handbook/data/data-core-editor/#getblocklistsettings), which is used to track runtime nesting settings of a block. Not sure it has all the information you need, it's currently used mostly for tracking whether a block imposes restrictions on allowed types of inner blocks, template, etc.

cc @jorgefilipecosta

**Comment by jorgefilipecosta** [comment]
I'm closing the issue for now, if for some reason the proposed solutions don't fit feel free to reopen.

**Comment by alvaro0555** [comment]
Thanks all for the quick help.
`getBlockListSettings` seems like the best option as it gives extra info like the templateLock and defined/undefined allowedBlocks.
`getInserterItems` returns a list of blocks form the parent, and if passing a non-nestable block still returns a list, I guess from the parent.
`canInsertBlockType` is a good solution, but it needs to be done in a one-by-one check.

Thanks again!
