### ISSUE TITLE
How can I choose landscape or portrait orientation for a gallery?

### ISSUE THREAD

**Issue by kathrinchen** [WordPress/gutenberg#9957]
I‘m currently writing an article with lots of pictures for my blog.

I‘d like to use galleries to present them.

All photos I want to use are taken and uploaded to the mediathek in landscape format.

When I created the first gallery with two pictures, Gutenberg choosed automatically landscape presentation.
But when I want to add further galleries, all photos are presented in portrait orientation, which malkes no sense, because you have to turn your head horizontally to see what‘s shown on them.

Even if I turn the photos in the mediathek, there‘s no change in orientation in the Gallery.
I don‘t find any switch on/off for landscape or portrait orientation for the galleries.

Could anyone please help me?
I like to use Gutenberg very much!
Thank you in advance and please excuse my bad English.

**Comment by designsimply** [comment]
Apologies for the delay in reply. I tested uploading several images into a gallery using both landscape and portrait orientation. I used WordPress 5.0.3 in my test with no active plugins and I used images that were exported using Lightroom and some which I used the Preview app on my Mac to rotate the photo orientation before uploading the image into the gallery. I used Firefox 64.0.2 on macOS 10.13.6 to test. In my testing so far, I haven't seen any of the images show up in an orientation different from what I see when I view the images on my computer before uploading them.

May I ask that you please update to the latest version of WordPress and check to see if the problem still occurs? If it does, may I ask that you please provide a list of testing steps that I can follow to test this again and also please include information about how the images were created and whether any were manually rotated using an app before they were uploaded to your WordPress site?

**Comment by youknowriad** [comment]
Closing as stale, let's reopen if there's are reproducible steps/actionable items.
