### ISSUE TITLE
Dynamic CSS for custom block

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9959]
How to add CSS for before after pseudo element in Gutenberg block? 

As no unique id generated on the frontend, is there another way to write CSS for pseudo-element?

**Comment by aduth** [comment]
Can you expand on your use-case? Is it possible that CSS variations could be applied either through a [`customClassName`](https://wordpress.org/gutenberg/handbook/block-api/#supports-optional) (the "Advanced" > "Additional CSS Class" inspector field) or by saving an attribute for your dynamic block which, on the server, is applied to the generated markup as a class?

Preemptively closing, but let's reopen if the question remains unsettled.

**Comment by aduth** [comment]
From what I understand then, the color would be user-selected? In which case, I might suggest storing this value as an attribute of the block, which can then be accessed in the server-side implementation of your block. 

The components are here, though not documented at the moment (cc @jorgefilipecosta in case I'm missing some):

https://github.com/WordPress/gutenberg/tree/master/packages/editor/src/components/colors

I expect it would work very similarly to the color options for both the Paragraph and Button blocks, in case you want to reference those in the meantime:

- https://github.com/WordPress/gutenberg/blob/57f98b219093a746da6ca3d5a532f106dc238230/packages/block-library/src/paragraph/edit.js
- https://github.com/WordPress/gutenberg/blob/57f98b219093a746da6ca3d5a532f106dc238230/packages/block-library/src/button/edit.js
