### ISSUE TITLE
Ability to open/close a gallery block (to show/hide all gallery images) in Visual Editor

### ISSUE THREAD

**Issue by AndB-GitHub** [WordPress/gutenberg#9961]
Would it be possible to add a button to open/close the gallery block (or any block) in Visual Editor? If my gallery is just 3 or 4 images there is no need, but if I create a gallery containing 100 images it would be very useful to be able to "close" the gallery block so as not to have to scroll all 100 images every time I have to edit something that is under that gallery block

**Comment by mtias** [comment]
I don't think this is something we'd add in core as it would add another layer of complexity for users (collapsed / uncollapsed) states. We are likely to continue to improve navigation instead with things like document outline, etc, to jump to different blocks.

**Comment by karmatosed** [comment]
I would also agree with @mtias, in this case let's close for now. I am very cautious we add complexity here.
