### ISSUE TITLE
Testing: Add E2E test for inserting reusable blocks by inserter after page refresh

### ISSUE THREAD

**Issue by aduth** [WordPress/gutenberg#9962]
To avoid repeated regressions, we should include an end-to-end test for inserting a reusable block by Inserter in a fresh editor page. See https://github.com/WordPress/gutenberg/issues/9962#issuecomment-422125922 .

Original Regression:

----

**Describe the bug**

Reusable blocks are not shown in the Inserter.

**To Reproduce**

1. (Prerequisite) Create a reusable block in a Gutenberg editor session
2. Create a new post
3. Try to insert the reusable block (either one preexisting, or the one created in Step 1) using the Inserter.
4. Observe that the reusable block is not shown in the inserter.

**Expected behavior**

Reusable block is both shown and searchable.

**Additional context**

Slack mentions:

- https://wordpress.slack.com/archives/C02QB2JS7/p1537090223000100
- https://wordpress.slack.com/archives/C02QB2JS7/p1537090223000100

From @youknowriad:
> I think we do have an e2e test, what's missing is an e2e test inserting a reusable block after refreshing the page.

**Comment by aduth** [comment]
Workaround: The reusable blocks appear correctly when the Inserter is closed and reopened again. It appears to hint to a possible race condition on this logic:

https://github.com/WordPress/gutenberg/blob/0816e230c54f908d5e67c1a8becae1c899fb5f84/packages/editor/src/store/effects/reusable-blocks.js#L55-L60

cc @youknowriad Does any of this sound familiar? Perhaps related to recent work in #9732?

**Comment by aduth** [comment]
I'd suggest we approach this from a TDD angle, updating the [E2E reusable block insertion case](https://github.com/WordPress/gutenberg/blob/0816e230c54f908d5e67c1a8becae1c899fb5f84/test/e2e/specs/reusable-blocks.test.js#L119-L162) to a failing state and working backward to a resolution. Based on the above workaround, I expect it may start failing if we ensured a fresh post for each test case run, i.e. using `beforeEach` instead of the [current `beforeAll`](https://github.com/WordPress/gutenberg/blob/0816e230c54f908d5e67c1a8becae1c899fb5f84/test/e2e/specs/reusable-blocks.test.js#L20-L22) (cc @noisysocks).

**Comment by youknowriad** [comment]
the recent changes have been merged after the 3.9 RC, so while it's related, I think the issue was there before.

**Comment by aduth** [comment]
I checked out a detached head at both `41d4223` and `41d4223~1` and it worked in both cases, which led me to believe that it might not have been directly related to #9732, but became introduced afterward.

**Comment by youknowriad** [comment]
Oh sorry, I'm tired, I thought you were linking to the resolvers refactoring that was recently merged. I can take a look at this issue tomorrow hopefully.

**Comment by aduth** [comment]
Reopening as we should have an end-to-end test.

**Comment by youknowriad** [comment]
I think we do have an e2e test, what's missing is an e2e test inserting a reusable block after refreshing the page.

**Comment by tellyworth** [comment]
>  Based on the above workaround, I expect it may start failing if we ensured a fresh post for each test case run, i.e. using `beforeEach` instead of the [current `beforeAll`](https://github.com/WordPress/gutenberg/blob/0816e230c54f908d5e67c1a8becae1c899fb5f84/test/e2e/specs/reusable-blocks.test.js#L20-L22) (cc @noisysocks).

Experimenting with this, we've encountered some other issues to do with tab focusing that interfere with the tests. Tab behaviour is different when starting with a new post for unknown reasons. We're investigating that further.
