### ISSUE TITLE
'assets_callback' not working

### ISSUE THREAD

**Issue by prajaktagadhave** [WordPress/gutenberg#9965]
We want to add dynamic CSS for our custom block. But 'assets_callback' function not working. The CSS not get added to existing enqueing CSS.

Any suggestion here?

**Comment by aduth** [comment]
Duplicates #9959, where I've left some feedback.

As noted at https://github.com/WordPress/gutenberg/pull/5740#issuecomment-422018927 , the `assets_callback` behavior was never added to Gutenberg.
