### ISSUE TITLE
Parsing Issues with classic editor and php rendered blocks.

### ISSUE THREAD

**Issue by jrmd** [WordPress/gutenberg#9968]
**Describe the bug**
in Gutenberg 3.8 where the classic editor doesnt show in the backend if a php rendered block is added just after the classic editor block.

It seems to be something to do with how the comments work. For example my php rendered block would be stored in the database like this:
```<!-- wp:my-blocks/block-custom /-->```

This causes the classic editor not to render, however if you change the comment to
```<!-- wp:my-blocks/block-custom --><!-- /wp:my-blocks/block-custom -->```
Everything will render in the editor correctly

Going back through the commits - it seems that it was caused by the new parser ( #8083 )

If my description you can see the conversation here in slack - https://wordpress.slack.com/archives/C02QB2JS7/p1537188435000100

**To Reproduce**
1. Add Classic editor block add some content
2. Directly after add the `latest posts` block (its a php rendered block)
3. Save the post
4. Refresh to see that the classic editor is not visible even though the content is in the database.

**Expected behavior**
Classic editor should be visible

**Additional context**
- Gutenberg 3.8

**Comment by dmsnell** [comment]
Strange…thanks for reporting! I haven't tried reproducing with those steps yet but I tried adding a new test to the parser just to see what's happening and I think we'll need to dig in more to find out what's up.

```diff
diff --git a/packages/block-serialization-default-parser/test/index.js b/packages/block-serialization-default-parser/test/index.js
index 68a46b39c..90eaf5cc9 100644
--- a/packages/block-serialization-default-parser/test/index.js
+++ b/packages/block-serialization-default-parser/test/index.js
@@ -24,4 +24,11 @@ describe( 'block-serialization-spec-parser', () => {
 			},
 		] );
 	} );
+
+	test( 'treats void blocks and empty blocks identically', () => {
+		const voidBlock = parse( '<!-- wp:block /-->' );
+		const emptyBlock = parse( '<!-- wp:block --><!-- /wp:block -->' );
+
+		expect( voidBlock ).toEqual( emptyBlock );
+	} );
 } );
```

I'll check in later but maybe this has something to do with another oddity? @jrmd I'll try and reproduce later with the steps you added, but in the meantime if you could post here a copy of the test document that produced the error that would be helpful (for example, the minimal document showing the bug).

Maybe there's something funny with newlines or whitespace…

**Comment by jrmd** [comment]
@dmsnell 

here is the entire post content to make this issue occur

```
<p>Hello World</p>

<!-- wp:latest-posts /-->
```

**Comment by chrisvanpatten** [comment]
I was able to reproduce this. You can also see in Code Editor mode that if you paste in the content @jrmd provided, the classic block content is immediately deleted.

**Comment by dmsnell** [comment]
Found it! this one was staring us down - I'm not sure why I missed it but the fix is simple. It was the case where we had leading HTML in front of a void block and we weren't pushing it to the output list.

I've submitted a patch in #9984 and it's ready for review. If you are able to confirm that this fixes the problem for you that'd be awesome to have the additional confirmation.
