### ISSUE TITLE
Unable to use drag handle with multiple block selection

### ISSUE THREAD

**Issue by ZebulanStanphill** [WordPress/gutenberg#9970]
## The issue
The drag handle does not appear for a multiple block selection.

## Screenshot
![image](https://user-images.githubusercontent.com/19592990/45633563-b53df580-ba65-11e8-9af6-af9a5f784da2.png)

**Comment by designsimply** [comment]
Tested and confirmed using WordPress 4.9.8 and Gutenberg 3.9.0-rc.1. 

I added the `Needs Design Feedback` label to try to get a check on whether that is intentionally left out.

**Comment by nosolosw** [comment]
Consolidating this idea in https://github.com/WordPress/gutenberg/issues/9970
