### ISSUE TITLE
Close button on pre-publish panel is out of view

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#9972]
Testing instructions:

* as an admin, change the WordPress language to german
* log out and log in with a contributor role

For reference, this is the screen in English:

![screenshot from 2018-09-17 18-27-52](https://user-images.githubusercontent.com/583546/45636262-86e10a00-baa7-11e8-9d22-d3a635356db8.png)

This in german:

![screenshot from 2018-09-17 18-26-14](https://user-images.githubusercontent.com/583546/45636270-8ba5be00-baa7-11e8-90f1-2e940ad65714.png)

**Comment by sarahmonster** [comment]
This should be fixed by #9398 whenever it's ready to merge. 🙂
