### ISSUE TITLE
Cover Image: Block toolbar overlaps with inline toolbar when there is a lot of text.

### ISSUE THREAD

**Issue by kjellr** [WordPress/gutenberg#9974]
**Describe the bug**

When a cover image wraps onto many lines (or contains many line breaks), the inline edit toolbar gets obscured by the block toolbar:

<img width="679" alt="screen shot 2018-09-17 at 12 48 15 pm" src="https://user-images.githubusercontent.com/1202812/45637372-503fcb00-ba78-11e8-9584-3806e4c4d02c.png">

**To Reproduce**

1. Add a cover image block.
2. Add at least 7 lines of text to it. 
3. Move your cursor over the block, so the block toolbar displays.
4. See error.

**Tested with:**
Gutenberg 3.8

[Originally reported](https://github.com/WordPress/gutenberg/issues/8199#issuecomment-421794965) by @bph

**Comment by youknowriad** [comment]
What's the solution, a higher z-index for the inline toolbar?

**Comment by kjellr** [comment]
Almost! But it'll actually need to be just a little more complicated: right now, there's no way to dismiss the inline toolbar, which means that if it were above the block toolbar, users would never get a chance to click on the block toolbar items that'd be obscured. 😞 Users _can_ remove the blinking cursor from the cover image by clicking outside the text area, but it doesn't hide the controls. 

So a complete solution would need to:

- Adjust the z-index of the inline toolbar so it floats above the block toolbar.
- Also hide the block toolbar when someone clicks out of the editing field.

**Comment by youknowriad** [comment]
> Also hide the block toolbar when someone clicks out of the editing field.

I thought it was already the case, must be a regression :)

**Comment by jorgefilipecosta** [comment]
As a side effect of merging nesting in cover block this issue got solved.
