### ISSUE TITLE
I am using map to save data but not working 

### ISSUE THREAD

**Issue by amitshah14744** [WordPress/gutenberg#9981]
Please check below is my code and please check attachment which is showing error:

(function (blocks, editor, components, element, api) {
    var el = element.createElement;
    var source = blocks.source;
    var InspectorControls = editor.InspectorControls;
    var RichText = editor.RichText;

    blocks.registerBlockType('geb/pdflinks', {
        title: 'PDF-Links',
        icon: 'media-default',
        category: 'geb-employee-block',
        attributes: {
            link: {
                type: 'array',                
                default: [{
                    text: "Fast Banana",                    
                }, {
                    text: "Greens Food Supplies",                    
                }]
            }
        },

        edit: function (props) {
            var attributes = props.attributes;            
            return [
                el(
                    'section',
                    {className: props.className},
                    el('div', {},
                        el('div', {className: 'working-here'},
                            attributes.link.map(function (n, r) {
                                return el(RichText, {
                                    tagName: 'h3',
                                    placeholder: 'Profile Name',
                                    keepPlaceholderOnFocus: true,
                                    value: n.text,
                                    isSelected: false,
                                    onChange: function (newTitle) {
                                        n.text = newTitle;
                                        props.setAttributes({link: attributes.link});
                                    },
                                })
                            }), 
                        )                       
                    )                                       
                )
            ];
        },

        save: function (props) {
            var attributes = props.attributes;                     
            return (
                    el('section', {className: props.className},
                        el('div', {},
                            el('div', { className: 'working-here' },
                                attributes.link.map(function (n, r) {
                                    console.log('comes hreer');
                                    return el(RichText.Content, {
                                        tagName: 'h3',
                                        value: n.text
                                    });
                                })
                            )
                        )
                    )
            );                
        }

    }
    );
})(
        window.wp.blocks,
        window.wp.editor,
        window.wp.components,
        window.wp.element,
        window.wp.api
        );

Can you please help me to solve this issue?

![screenshot from 2018 09 18 08 32 46](https://user-images.githubusercontent.com/20751575/45662022-b3d00400-bb1d-11e8-9a09-1d6441c041b1.png)

**Comment by youknowriad** [comment]
I may be wrong but I think the issue is somewhere here:

```js
n.text = newTitle;
props.setAttributes({link: attributes.link});
```

You're mutating the existing attributes link. While working with React (or Gutenberg), don't mutate props, always generate new instances of objects:

This could be something like:

```js
var newLink = attributes.link.slice(0);
newLink[r] = { text: newTitle };
props.setAttributes({
link: newLink
});
```

Let me know if it works.
