### ISSUE TITLE
Dashboard menus are hidden after opening Gutenberg

### ISSUE THREAD

**Issue by manojvashist91** [WordPress/gutenberg#9985]
**Is your feature request related to a problem? Please describe.**
    Wordpress default dashboard menu are hide frm left site and editer is take whole screen to show 
     edit the content there is many white space left site which is unnessary so chnage editer small not 
     on whole screen so the deault dashbrd menu is also shown when gutenberg editer show. 

**Describe the solution you'd like**
manage the white spacing only.

**Describe alternatives you've considered**
 be gutenburge editer show unter the wrap div 0f wordpress.

**Comment by ktmn** [comment]
Turn off fullscreen mode?

![](https://i.imgur.com/s9CBSfi.png)

**Comment by designsimply** [comment]
I will close this issue because it looks like a good solution was posted. If you feel otherwise, please reply to ask further questions and we can look again.

Thank you for testing Gutenberg!
