### ISSUE TITLE
Custom css classes for dynamic blocks are not saved

### ISSUE THREAD

**Issue by cristian-e** [WordPress/gutenberg#9991]
**Describe the bug**
When you add a custom class to a dynamic block (archives, latest comments etc) and update the post, the custom class gets saved and displayed on the front-end like it should. But the next time you reload the editor, the custom class is no longer there (`Additional CSS Class` field is empty). This means that if you update the post again, the custom classes that you previously added, will be deleted and no longer ouputted on the front-end.
  
**To Reproduce**
![u](https://user-images.githubusercontent.com/43263346/45672712-8ee58c00-bb31-11e8-8eb4-828cc126e3f6.gif)

**Expected behavior**
The custom class that we previously added, should be displayed in `Additional CSS Class` textfield.

**Potential fix**
This only happens to dynamic blocks, so I think the issue is with the `addParsedDifference` filter.  
https://github.com/WordPress/gutenberg/blob/c28d2dbe2e5a01cdb30cfa884170c76e8b548fd6/packages/editor/src/hooks/custom-class-name.js#L134-L154
Because dynamic blocks don't have a save render implementation, this filter will delete the classname from the block attributes. Maybe modify this filter to be applied only to non-dynamic blocks.

Similar issues #9929, #9423.

**Comment by jrgd** [comment]
i experienced the same issue trying to add a custom class onto the legacy menu block in the widget: inserting the custom class, saving the page; reloading the page; no class is displayed in the admin nor in the page
issue partially fixed? :/ :(
