### ISSUE TITLE
Persistence data plugin should take into account the object shape

### ISSUE THREAD

**Issue by nosolosw** [WordPress/gutenberg#9994]
The persistence data plugin helps to persist parts of the state in between sessions. When the data persisted is an object (e.g. the `preferences` key in the [editor](https://github.com/WordPress/gutenberg/blob/master/packages/editor/src/store/index.js#L26), [nux](https://github.com/WordPress/gutenberg/blob/c1c4c7ed80f0f29f60adb44f2fd0cb2f8660045d/packages/nux/src/store/index.js), or [edit-post](https://github.com/WordPress/gutenberg/blob/c1c4c7ed80f0f29f60adb44f2fd0cb2f8660045d/edit-post/store/index.js) stores) new keys added to that object will be invalidated once the persistence mechanism retrieves old data from cache.

### How to test

- Clean browser application cache, check out `master` branch, and run Gutenberg.
- Create a new branch and add some code that adds a new key to the `preferences` object whose value is `true` by default.
- Execute that new branch.

Expected result is that the `preferences` object will have the new truthy value but instead it has the state retrieved from local storage (which doesn't have the new added key).

**Comment by youknowriad** [comment]
This was working at some point, so I think it's a regression.

**Comment by aduth** [comment]
Could be related to #8341
