### ISSUE TITLE
Can't scroll WP menu when in editor

### ISSUE THREAD

**Issue by maximebj** [WordPress/gutenberg#9996]
When having a very long WordPress Menu, it can't be scrolled on the editor page : 

![scroll](https://user-images.githubusercontent.com/1785489/45679464-036ff900-bb39-11e8-96e2-315812aef92f.jpg)

I think it's just a small CSS issue. This seems to cause the issue: 

`
@media (min-width: 782px)
.gutenberg__editor {
    min-height: calc(100vh - 32px);
}
`

Gutenberg v 3.8

**Comment by chrisvanpatten** [comment]
So I'm personally not able to reproduce this — on my end, it scrolls, but the menu does scroll _separately_ from Gutenberg.

That said, there was [another report of this in Slack](
https://wordpress.slack.com/archives/C02QB2JS7/p1537278744000100) so it's probably worth investigating further.

It's also not a great UX to effectively have three separate scroll areas: the left menu, the center editor canvas, and the right inspector sidebar. I wonder if there's a sensible way to consolidate these into fewer scroll areas?

**Comment by Soean** [comment]
@chrisvanpatten I can reproduce the error. If you just resize the window you can scroll, but if you reload the window you aren't able to scroll anymore.

**Comment by johngodley** [comment]
To make this a bit easier to test you can drop this into a file in `wp-content/plugins/` and then activate it from the plugins menu. You'll then have a very tall admin menu!

```php
<?php
/*
Plugin Name: Long Menu
Description: Gives you a really long menu
*/

function really_long_menu() {
}

function add_really_long_menu() {
    for ( $loop = 1; $loop < 30; $loop++ ) {
        add_menu_page( 'Long Menu ' . $loop, 'Long Menu ' . $loop, 'manage_options', 'page-' . $loop, 'really_long_menu' );
    }
}

add_action( 'admin_menu', 'add_really_long_menu' );
```

I've determined that it's something to do with the `sticky-menu` body class. This is present on page load, but removed when you resize the page. Investigating where it comes from.

**Comment by johngodley** [comment]
Debugging further, `sticky-menu` is added by `setPinMenu()` in the core WordPress file `common.js` - this is preventing the scroll.

`sticky-menu` is added because `#adminmenuwrap` has a height of 0

`#adminmenuwrap` has a height of 0 because `is-fullscreen-mode` is present on the body class, and this hides the admin menu.

`is-fullscreen-mode` was added to stop a jump in the UI, according to #9567
