### ISSUE TITLE
Embedded videos have scrollbar in the editor

### ISSUE THREAD

**Issue by notnownikki** [WordPress/gutenberg#9997]
**Describe the bug**

Embedded videos that have a fixed aspect ratio have a scrollbar in Chrome 69 and Firefox 62.

Embedding https://www.youtube.com/watch?v=OKhacWQ2fCs looks like this:

![scrollbar1](https://user-images.githubusercontent.com/3314354/45680237-4ed2d900-bb32-11e8-803d-1a6c974d92cc.png)

and because of the scrollbar, the video's width gets squished a bit.

Things look fine in the published post though.
 cc: @jasmussen

**Comment by youknowriad** [comment]
I'm pretty sure I saw a similar issue some days ago :)

**Comment by notnownikki** [comment]
I could only find https://github.com/WordPress/gutenberg/issues/9952 which looked like a different issue to me. Do you know where the issue is so we can mark this is a duplicate?

**Comment by youknowriad** [comment]
This one #9920 ?

**Comment by notnownikki** [comment]
Wonder how that didn't show up for me... Ok closing this one in favour of that.
